/**
 * Items d'exemple de chaque type : servent au « Labo » (/labo/<jeu>) pour développer et tester
 * chaque mini-jeu indépendamment du contenu des leçons, et aux tests E2E de fumée.
 */
import type { Item, ItemKind } from '@/content/schemas';

const L = 'LABO';

export const FIXTURES: Record<ItemKind, Item[]> = {
  numeric_answer: [
    {
      kind: 'numeric_answer',
      id: 'n1',
      lessonId: L,
      prompt: '7 × 8',
      spoken: '7 fois 8',
      answer: 56,
      decimals: 0,
      difficulty: 0.5,
      explication: '7 × 8 = 56.',
    },
    {
      kind: 'numeric_answer',
      id: 'n2',
      lessonId: L,
      prompt: '47 + 9',
      spoken: '47 plus 9',
      answer: 56 + 0 - 0,
      decimals: 0,
      difficulty: 0.3,
      explication: '+ 9, c’est + 10 puis − 1.',
    },
    {
      kind: 'numeric_answer',
      id: 'n3',
      lessonId: L,
      prompt: '3 + … = 10',
      spoken: '3 plus combien égale 10 ?',
      answer: 7,
      decimals: 0,
      difficulty: 0.2,
      explication: '3 + 7 = 10.',
    },
    {
      kind: 'numeric_answer',
      id: 'n4',
      lessonId: L,
      prompt: '3,7 + 2,6',
      spoken: '3 virgule 7 plus 2 virgule 6',
      answer: 6.3,
      decimals: 1,
      difficulty: 0.6,
      explication: '13 dixièmes = 1 unité et 3 dixièmes.',
    },
    {
      kind: 'numeric_answer',
      id: 'n5',
      lessonId: L,
      prompt: '6 × 4',
      spoken: '6 fois 4',
      answer: 24,
      decimals: 0,
      difficulty: 0.4,
      explication: '6 × 4 = 24.',
    },
    {
      kind: 'numeric_answer',
      id: 'n6',
      lessonId: L,
      prompt: '100 − 35',
      spoken: '100 moins 35',
      answer: 65,
      decimals: 0,
      difficulty: 0.5,
      explication: '35 + 65 = 100.',
    },
  ],
  spelling_word: ['chocolat', 'maison', 'pourtant', 'école', 'grenouille', 'éléphant'].map((w, i) => ({
    kind: 'spelling_word' as const,
    id: `s${i}`,
    lessonId: L,
    word: w,
    sentence: undefined,
    isSentence: false,
    source: 'programme' as const,
    definition: [
      'Friandise au cacao',
      'On y habite',
      'Mot invariable : cependant',
      'On y apprend',
      'Elle saute dans la mare',
      'Grand animal à trompe',
    ][i],
    explication: 'Regarde bien chaque lettre.',
  })),
  mcq: [
    {
      kind: 'mcq',
      id: 'q1',
      lessonId: L,
      question: 'En quelle année commence la Révolution française ?',
      choices: ['1789', '1914', '1492', '1848'],
      answerIndex: 0,
      typedAnswer: '1789',
      explication: 'La Révolution commence en 1789.',
      guillotine: true,
      hints: ['C’est au XVIIIe siècle.', 'La Bastille est prise cette année-là.'],
    },
    {
      kind: 'mcq',
      id: 'q2',
      lessonId: L,
      question: 'Quel est le plus grand nombre ?',
      choices: ['3,5', '3,45'],
      answerIndex: 0,
      explication: '3,5 = 3,50 et 50 centièmes > 45 centièmes.',
      guillotine: true,
    },
    {
      kind: 'mcq',
      id: 'q3',
      lessonId: L,
      question: 'Comment dit-on « chat » en anglais ?',
      choices: ['cat', 'dog', 'cow', 'bird'],
      answerIndex: 0,
      explication: 'Chat se dit « cat ».',
      guillotine: true,
      image: '🐱',
      lang: 'en-GB',
      spoken: 'cat',
    },
    {
      kind: 'mcq',
      id: 'q4',
      lessonId: L,
      question: 'Quelle ponctuation termine cette phrase : « Quelle heure est-il » ?',
      choices: ['?', '.', '!'],
      answerIndex: 0,
      explication: 'C’est une question : point d’interrogation.',
      guillotine: true,
    },
  ],
  true_false: [
    {
      kind: 'true_false',
      id: 't1',
      lessonId: L,
      statement: '7 × 8 = 54',
      answer: false,
      explication: '7 × 8 = 56.',
    },
    {
      kind: 'true_false',
      id: 't2',
      lessonId: L,
      statement: 'L’eau gèle à 0 °C.',
      answer: true,
      explication: 'L’eau devient de la glace à 0 °C.',
    },
    {
      kind: 'true_false',
      id: 't3',
      lessonId: L,
      statement: 'Une semaine a 7 jours.',
      answer: true,
      explication: 'Lundi … dimanche : 7 jours.',
    },
    {
      kind: 'true_false',
      id: 't4',
      lessonId: L,
      statement: '« Ils mange » est bien écrit.',
      answer: false,
      explication: 'Avec ils, le verbe prend -nt : ils mangent.',
    },
  ],
  ordering: [
    {
      kind: 'ordering',
      id: 'o1',
      lessonId: L,
      prompt: 'Range les événements du plus ancien au plus récent.',
      elements: ['Prise de la Bastille', 'Sacre de Napoléon', 'Lois Ferry', 'Armistice de 1918'],
      labels: ['1789', '1804', '1881-1882', '1918'],
      mode: 'chrono',
      explication: 'Regarde bien les dates.',
    },
    {
      kind: 'ordering',
      id: 'o2',
      lessonId: L,
      prompt: 'Range du plus petit au plus grand.',
      elements: ['98', '305', '350', '503'],
      mode: 'croissant',
      explication: 'Compare d’abord les centaines.',
    },
    {
      kind: 'ordering',
      id: 'o3',
      lessonId: L,
      prompt: 'Remets les mots dans l’ordre.',
      elements: ['Le', 'chat', 'dort', 'au', 'soleil.'],
      mode: 'phrase',
      explication: 'Une phrase commence par une majuscule et finit par un point.',
    },
    {
      kind: 'ordering',
      id: 'o4',
      lessonId: L,
      prompt: 'Remets le cycle de vie du papillon dans l’ordre.',
      elements: ['œuf', 'chenille', 'chrysalide', 'papillon'],
      mode: 'etapes',
      explication: 'L’œuf donne une chenille, qui devient chrysalide puis papillon.',
    },
  ],
  classification: [
    {
      kind: 'classification',
      id: 'c1',
      lessonId: L,
      prompt: 'Range chaque mot dans sa classe.',
      categories: ['nom', 'verbe', 'adjectif'],
      elements: [
        { label: 'maison', category: 0 },
        { label: 'courir', category: 1 },
        { label: 'rouge', category: 2 },
        { label: 'chat', category: 0 },
        { label: 'mange', category: 1 },
        { label: 'petit', category: 2 },
      ],
      explication: 'Le verbe se conjugue, le nom désigne, l’adjectif précise le nom.',
    },
    {
      kind: 'classification',
      id: 'c2',
      lessonId: L,
      prompt: 'Divisible par 5 ou non ?',
      categories: ['divisible par 5', 'non divisible par 5'],
      elements: [
        { label: '35', category: 0 },
        { label: '42', category: 1 },
        { label: '100', category: 0 },
        { label: '73', category: 1 },
      ],
      explication: 'Un nombre est divisible par 5 s’il se termine par 0 ou 5.',
    },
    {
      kind: 'classification',
      id: 'c3',
      lessonId: L,
      prompt: 'Solide, liquide ou gaz ?',
      categories: ['solide', 'liquide', 'gaz'],
      elements: [
        { label: 'glaçon', category: 0, image: '🧊' },
        { label: 'lait', category: 1, image: '🥛' },
        { label: 'vapeur', category: 2, image: '♨️' },
        { label: 'pierre', category: 0, image: '🪨' },
      ],
      explication: 'Un solide a une forme propre, un liquide coule, un gaz remplit tout l’espace.',
    },
  ],
  pairing: [
    {
      kind: 'pairing',
      id: 'p1',
      lessonId: L,
      prompt: 'Associe chaque mot à son contraire.',
      pairs: [
        { left: 'grand', right: 'petit' },
        { left: 'visible', right: 'invisible' },
        { left: 'ranger', right: 'déranger' },
        { left: 'chaud', right: 'froid' },
      ],
      relation: 'contraires',
      explication: 'Un contraire a le sens opposé.',
    },
    {
      kind: 'pairing',
      id: 'p2',
      lessonId: L,
      prompt: 'Associe chaque calcul à son résultat.',
      pairs: [
        { left: '6 × 7', right: '42' },
        { left: '8 × 8', right: '64' },
        { left: '9 × 3', right: '27' },
        { left: '5 × 5', right: '25' },
      ],
      relation: 'calcul → résultat',
      explication: 'Révise tes tables.',
    },
    {
      kind: 'pairing',
      id: 'p3',
      lessonId: L,
      prompt: 'Associe le mot anglais à l’image.',
      pairs: [
        { left: 'dog', right: '🐶' },
        { left: 'cat', right: '🐱' },
        { left: 'fish', right: '🐟' },
        { left: 'bird', right: '🐦' },
      ],
      relation: 'mot → image',
      explication: 'Écoute bien chaque mot.',
    },
  ],
  fill_blank: [
    {
      kind: 'fill_blank',
      id: 'f1',
      lessonId: L,
      sentence: 'Léo ___ un vélo rouge.',
      answer: 'a',
      choices: ['a', 'à'],
      hint: 'Remplace par « avait » : Léo avait un vélo.',
      explication: '« a » est le verbe avoir : on peut dire « avait ».',
    },
    {
      kind: 'fill_blank',
      id: 'f2',
      lessonId: L,
      sentence: 'Demain, nous ___ au parc.',
      answer: 'irons',
      choices: ['irons', 'allons', 'allions'],
      conjugaison: { sujet: 'nous', verbe: 'aller', temps: 'futur' },
      explication: 'Futur de aller : nous irons.',
    },
    {
      kind: 'fill_blank',
      id: 'f3',
      lessonId: L,
      sentence: 'Les ___ chats jouent.',
      answer: 'petits',
      choices: ['petit', 'petits', 'petite'],
      explication: 'Le nom est au pluriel, l’adjectif aussi : petits.',
    },
    {
      kind: 'fill_blank',
      id: 'f4',
      lessonId: L,
      sentence: 'Elles ___ (chanter, présent) juste.',
      answer: 'chantent',
      explication: 'Avec elles, le verbe du 1er groupe se termine par -ent.',
      conjugaison: { sujet: 'elles', verbe: 'chanter', temps: 'présent' },
    },
  ],
  number_line: [
    {
      kind: 'number_line',
      id: 'l1',
      lessonId: L,
      prompt: 'Place 640 sur la droite.',
      min: 0,
      max: 1000,
      step: 100,
      subdivisions: 10,
      target: 640,
      display: '640',
      tolerance: 10,
      explication: '640 est entre 600 et 700, plus près de 600.',
    },
    {
      kind: 'number_line',
      id: 'l2',
      lessonId: L,
      prompt: 'Place 3/4 sur la droite.',
      min: 0,
      max: 2,
      step: 1,
      subdivisions: 4,
      target: 0.75,
      display: '3/4',
      tolerance: 0.05,
      explication: 'Partage l’unité en 4 et compte 3 parts.',
    },
    {
      kind: 'number_line',
      id: 'l3',
      lessonId: L,
      prompt: 'Place 2,5 sur la droite.',
      min: 0,
      max: 5,
      step: 1,
      subdivisions: 10,
      target: 2.5,
      display: '2,5',
      tolerance: 0.1,
      explication: '2,5 est au milieu entre 2 et 3.',
    },
  ],
  visual_fraction: [
    {
      kind: 'visual_fraction',
      id: 'v1',
      lessonId: L,
      prompt: 'Colorie 3/8 de la pizza.',
      numerator: 3,
      denominator: 8,
      shape: 'pizza',
      task: 'colorier',
      explication: 'On coupe en 8 parts égales et on en prend 3.',
    },
    {
      kind: 'visual_fraction',
      id: 'v2',
      lessonId: L,
      prompt: 'Quelle fraction de la tablette est colorée ?',
      numerator: 2,
      denominator: 5,
      shape: 'barre',
      task: 'lire',
      explication: '2 parts sur 5 : deux cinquièmes.',
    },
    {
      kind: 'visual_fraction',
      id: 'v3',
      lessonId: L,
      prompt: 'Quelle fraction est la plus grande ?',
      numerator: 1,
      denominator: 3,
      shape: 'tablette',
      task: 'comparer',
      other: { numerator: 1, denominator: 5 },
      explication: 'Plus on partage, plus les parts sont petites : 1/3 > 1/5.',
    },
  ],
  clock: [
    {
      kind: 'clock',
      id: 'h1',
      lessonId: L,
      prompt: 'Quelle heure est-il ?',
      task: 'lire',
      hours: 3,
      minutes: 15,
      answerText: '3 h 15',
      explication: 'La petite aiguille est sur 3, la grande sur le 3 : 15 minutes.',
    },
    {
      kind: 'clock',
      id: 'h2',
      lessonId: L,
      prompt: 'Règle l’horloge sur 7 h 30.',
      task: 'regler',
      hours: 7,
      minutes: 30,
      answerText: '7 h 30',
      explication: 'La grande aiguille sur le 6 : 30 minutes.',
    },
    {
      kind: 'clock',
      id: 'h3',
      lessonId: L,
      prompt: 'Le film commence à 14 h 20 et dure 45 min. À quelle heure finit-il ?',
      task: 'duree',
      hours: 14,
      minutes: 20,
      durationMinutes: 45,
      answerText: '15 h 05',
      explication: '14 h 20 + 40 min = 15 h 00, + 5 min = 15 h 05.',
    },
  ],
  money: [
    {
      kind: 'money',
      id: 'm1',
      lessonId: L,
      prompt: 'Paie 3,50 €.',
      task: 'payer',
      priceCents: 350,
      denominations: [10, 20, 50, 100, 200, 500],
      explication: '2 € + 1 € + 50 c = 3,50 €.',
    },
    {
      kind: 'money',
      id: 'm2',
      lessonId: L,
      prompt: 'Le client paie 5 € pour 3,20 €. Rends la monnaie.',
      task: 'rendre',
      priceCents: 320,
      givenCents: 500,
      denominations: [10, 20, 50, 100, 200],
      explication: '5 € − 3,20 € = 1,80 €.',
    },
  ],
  geometry_shape: [
    {
      kind: 'geometry_shape',
      id: 'g1',
      lessonId: L,
      prompt: 'Comment s’appelle cette figure ?',
      task: 'nommer',
      shape: 'rectangle',
      choices: ['rectangle', 'carré', 'losange', 'triangle'],
      answer: 'rectangle',
      explication: '4 angles droits et des côtés opposés de même longueur.',
    },
    {
      kind: 'geometry_shape',
      id: 'g2',
      lessonId: L,
      prompt: 'Colorie le symétrique par rapport à l’axe.',
      task: 'symetrie',
      shape: 'grille',
      answer: 'symétrique',
      grid: {
        cols: 8,
        rows: 6,
        cells: [
          [1, 1],
          [2, 1],
          [2, 2],
          [3, 3],
        ],
        axis: 'vertical',
      },
      explication: 'Chaque case est à la même distance de l’axe, de l’autre côté.',
    },
    {
      kind: 'geometry_shape',
      id: 'g3',
      lessonId: L,
      prompt: 'Quel est ce solide ?',
      task: 'solide',
      shape: 'cube',
      choices: ['cube', 'pavé', 'pyramide', 'cylindre'],
      answer: 'cube',
      explication: '6 faces carrées.',
    },
    {
      kind: 'geometry_shape',
      id: 'g4',
      lessonId: L,
      prompt: 'Ce patron permet-il de fabriquer un cube ?',
      task: 'patron',
      shape: 'patron_cube_croix',
      choices: ['oui', 'non'],
      answer: 'oui',
      explication: 'La croix se replie en cube.',
    },
  ],
  map_point: [
    {
      kind: 'map_point',
      id: 'mp1',
      lessonId: L,
      prompt: 'Touche la Bretagne.',
      map: 'france-regions',
      target: 'bretagne',
      targetLabel: 'Bretagne',
      explication: 'La Bretagne est à l’ouest de la France.',
    },
    {
      kind: 'map_point',
      id: 'mp2',
      lessonId: L,
      prompt: 'Touche l’Afrique.',
      map: 'monde',
      target: 'afrique',
      targetLabel: 'Afrique',
      explication: 'L’Afrique est au sud de l’Europe.',
    },
  ],
  read_aloud: [
    {
      kind: 'read_aloud',
      id: 'r1',
      lessonId: L,
      title: 'Le cerf-volant de Léna',
      text: 'Léna a un cerf-volant rouge. Ce matin, le vent souffle fort. Elle court dans le pré avec son frère Malo.',
      nbMots: 20,
      targetMCLM: 70,
      explication: 'Lis à ton rythme en respectant les points.',
    },
  ],
  oral_answer: [
    {
      kind: 'oral_answer',
      id: 'or1',
      lessonId: L,
      prompt: '6 × 7',
      spoken: '6 fois 7',
      answer: '42',
      accepted: ['42', 'quarante-deux', 'quarante deux'],
      explication: '6 × 7 = 42.',
    },
    {
      kind: 'oral_answer',
      id: 'or2',
      lessonId: L,
      prompt: 'Lis ce pseudo-mot : choust',
      answer: 'choust',
      accepted: ['choust', 'chouste'],
      explication: 'ch-ou-s-t.',
    },
    {
      kind: 'oral_answer',
      id: 'or3',
      lessonId: L,
      prompt: 'Say it in English: chien',
      answer: 'dog',
      accepted: ['dog'],
      lang: 'en-GB',
      explication: 'Chien se dit « dog ».',
    },
  ],
  bar_model: [
    {
      kind: 'bar_model',
      id: 'b1',
      lessonId: L,
      statement:
        'Lina a 28 billes. Elle en gagne 15 à la récréation. Combien de billes a-t-elle maintenant ?',
      structure: 'transformation',
      bars: [
        {
          label: 'billes',
          segments: [
            { value: 28, label: 'au début' },
            { value: 15, label: 'gagnées' },
          ],
        },
      ],
      total: null,
      question: 'Combien de billes a-t-elle maintenant ?',
      answer: 43,
      unit: 'billes',
      answerSentence: 'Lina a maintenant ___ billes.',
      reformulations: [
        'Lina avait des billes et elle en a eu plus.',
        'Lina a perdu des billes.',
        'Lina a donné des billes à son ami.',
      ],
      operation: '28 + 15 = 43',
      explication: 'On cherche le tout : on ajoute les deux parties.',
    },
    {
      kind: 'bar_model',
      id: 'b2',
      lessonId: L,
      statement: 'Un livre coûte 12 €. Un jeu coûte 3 fois plus. Combien coûte le jeu ?',
      structure: 'multiplicatif',
      bars: [
        { label: 'livre', segments: [{ value: 12 }] },
        { label: 'jeu', segments: [{ value: 12 }, { value: 12 }, { value: 12 }] },
      ],
      total: null,
      question: 'Combien coûte le jeu ?',
      answer: 36,
      unit: '€',
      answerSentence: 'Le jeu coûte ___ €.',
      operation: '12 × 3 = 36',
      explication: '3 fois plus : on multiplie par 3.',
    },
  ],
};
