/**
 * Exemples d'items pour les jeux n° 50 à 56 (frise, cartes, Qui suis-je, laboratoire, EMC, anglais,
 * vrai/faux). Ils servent aux tests unitaires et peuvent être ajoutés aux exemples partagés
 * (src/games/_kit/fixtures.ts) pour le Labo. Tous respectent `checkItem` et les conventions `meta`.
 */
import type { Item, ItemKind } from '@/content/schemas';

const L = 'LABO';

export const MONDE_FIXTURES: Partial<Record<ItemKind, Item[]>> = {
  ordering: [
    {
      kind: 'ordering',
      id: 'mo-frise-republique',
      lessonId: L,
      prompt: 'Range ces événements du plus ancien au plus récent.',
      elements: [
        'Proclamation de la Ire République',
        'Lois de Jules Ferry sur l’école',
        'Loi de séparation des Églises et de l’État',
        'Droit de vote des femmes',
      ],
      labels: ['1792', '1881-1882', '1905', '1944'],
      mode: 'chrono',
      explication:
        'La République est proclamée en 1792, l’école devient gratuite et obligatoire en 1881-1882, l’État se sépare des Églises en 1905 et les femmes obtiennent le droit de vote en 1944.',
    },
    {
      kind: 'ordering',
      id: 'mo-frise-generations',
      lessonId: L,
      prompt: 'Range les membres de la famille du plus âgé au plus jeune.',
      elements: ['l’arrière-grand-mère', 'la grand-mère', 'la maman', 'l’enfant'],
      mode: 'chrono',
      explication: 'Chaque génération naît après la précédente : arrière-grands-parents, grands-parents, parents, enfants.',
    },
    {
      kind: 'ordering',
      id: 'mo-frise-lumiere',
      lessonId: L,
      prompt: 'Range ces objets pour s’éclairer, du plus ancien au plus récent.',
      elements: ['la bougie', 'la lampe à pétrole', 'l’ampoule électrique', 'la lampe à LED'],
      labels: ['il y a très longtemps', 'vers 1860', 'vers 1880', 'aujourd’hui'],
      mode: 'chrono',
      explication: 'On s’éclairait à la bougie, puis à la lampe à pétrole ; l’ampoule électrique arrive vers 1880, la lampe à LED est récente.',
    },
    {
      kind: 'ordering',
      id: 'mo-cycle-grenouille',
      lessonId: L,
      prompt: 'Remets le cycle de vie de la grenouille dans l’ordre.',
      elements: ['les œufs', 'le têtard', 'le têtard avec des pattes', 'la jeune grenouille', 'la grenouille adulte'],
      mode: 'etapes',
      meta: { cycle: true },
      explication: 'Les œufs donnent des têtards ; leurs pattes poussent, la queue disparaît et ils deviennent des grenouilles qui pondront à leur tour.',
    },
    {
      kind: 'ordering',
      id: 'mo-etapes-glace',
      lessonId: L,
      prompt: 'On chauffe un glaçon dans une casserole : remets les étapes dans l’ordre.',
      elements: ['de la glace (solide)', 'de l’eau (liquide)', 'de la vapeur d’eau (gaz)'],
      mode: 'etapes',
      explication: 'En chauffant, la glace fond et devient de l’eau liquide, puis l’eau bout et devient de la vapeur.',
    },
  ],
  classification: [
    {
      kind: 'classification',
      id: 'mo-vivant',
      lessonId: L,
      prompt: 'Vivant ou non vivant ?',
      categories: ['vivant', 'non vivant'],
      elements: [
        { label: 'le chat', category: 0, image: '🐈' },
        { label: 'la pierre', category: 1, image: '🪨' },
        { label: 'l’arbre', category: 0, image: '🌳' },
        { label: 'le vélo', category: 1, image: '🚲' },
        { label: 'le champignon', category: 0, image: '🍄' },
        { label: 'la cuillère', category: 1, image: '🥄' },
      ],
      explication: 'Un être vivant naît, grandit, se nourrit, se reproduit et meurt. Un objet, non.',
    },
    {
      kind: 'classification',
      id: 'mo-regimes',
      lessonId: L,
      prompt: 'Que mangent ces animaux ?',
      categories: ['herbivore', 'carnivore', 'omnivore'],
      elements: [
        { label: 'la vache', category: 0, image: '🐄' },
        { label: 'le lion', category: 1, image: '🦁' },
        { label: 'le lapin', category: 0, image: '🐇' },
        { label: 'le loup', category: 1, image: '🐺' },
        { label: 'le sanglier', category: 2, image: '🐗' },
        { label: 'l’ours brun', category: 2, image: '🐻' },
      ],
      explication: 'L’herbivore mange des végétaux, le carnivore de la viande, l’omnivore un peu de tout.',
    },
    {
      kind: 'classification',
      id: 'mo-conducteurs',
      lessonId: L,
      prompt: 'Place l’objet dans le circuit : l’ampoule s’allume-t-elle ?',
      categories: ['conducteur (l’ampoule s’allume)', 'isolant (l’ampoule reste éteinte)'],
      elements: [
        { label: 'un trombone en métal', category: 0, image: '📎' },
        { label: 'une gomme', category: 1 },
        { label: 'une clé en métal', category: 0, image: '🔑' },
        { label: 'un crayon en bois', category: 1, image: '✏️' },
        { label: 'une pièce de monnaie', category: 0, image: '🪙' },
        { label: 'un bouchon en plastique', category: 1 },
      ],
      meta: { circuit: true },
      explication: 'Les métaux laissent passer le courant électrique (conducteurs) ; le bois, le plastique et le caoutchouc ne le laissent pas passer (isolants).',
    },
    {
      kind: 'classification',
      id: 'mo-etats',
      lessonId: L,
      prompt: 'Solide, liquide ou gaz ?',
      categories: ['solide', 'liquide', 'gaz'],
      elements: [
        { label: 'le glaçon', category: 0, image: '🧊' },
        { label: 'le jus de pomme', category: 1, image: '🧃' },
        { label: 'la vapeur d’eau', category: 2, image: '♨️' },
        { label: 'le caillou', category: 0, image: '🪨' },
        { label: 'l’huile', category: 1 },
        { label: 'l’air', category: 2, image: '🌬️' },
      ],
      explication: 'Un solide garde sa forme, un liquide coule et prend la forme du récipient, un gaz occupe tout l’espace.',
    },
  ],
  mcq: [
    {
      kind: 'mcq',
      id: 'mo-qui-ferry',
      lessonId: L,
      question: 'Qui suis-je ?',
      choices: ['Jules Ferry', 'Victor Hugo', 'Louis XVI', 'Napoléon Ier'],
      answerIndex: 0,
      hints: [
        'J’ai vécu au XIXe siècle et j’ai été ministre.',
        'Je suis un homme politique de la IIIe République.',
        'Des lois portent mon nom, en 1881 et 1882.',
        'Grâce à moi, l’école primaire devient gratuite, laïque et obligatoire.',
        'Beaucoup d’écoles en France portent mon nom.',
      ],
      image: '🏫',
      guillotine: true,
      explication: 'Jules Ferry a fait voter les lois de 1881-1882 : l’école primaire devient gratuite, laïque et obligatoire.',
    },
    {
      kind: 'mcq',
      id: 'mo-qui-schoelcher',
      lessonId: L,
      question: 'Qui suis-je ?',
      choices: ['Victor Schœlcher', 'Jean Moulin', 'Jules Ferry', 'Louis Pasteur'],
      answerIndex: 0,
      hints: [
        'Je suis un homme politique français du XIXe siècle.',
        'J’ai beaucoup voyagé et j’ai été révolté par ce que j’ai vu dans les colonies.',
        'Je me suis battu toute ma vie pour la liberté de tous les êtres humains.',
        'En 1848, je fais signer le décret d’abolition de l’esclavage.',
        'Mon nom commence par « Victor » ; il est inscrit au Panthéon.',
      ],
      guillotine: false,
      explication: 'Victor Schœlcher a obtenu l’abolition définitive de l’esclavage dans les colonies françaises en 1848.',
    },
    {
      kind: 'mcq',
      id: 'mo-qui-grenouille',
      lessonId: L,
      question: 'Qui suis-je ?',
      choices: ['la grenouille', 'le papillon', 'la poule', 'le poisson'],
      answerIndex: 0,
      hints: [
        'Je suis un animal qui pond des œufs.',
        'Je vis une partie de ma vie dans l’eau.',
        'Quand je suis petit, je n’ai pas de pattes mais une queue.',
        'Petit, je m’appelle un têtard.',
        'Je saute et je coasse au bord de la mare.',
      ],
      image: '🐸',
      guillotine: true,
      explication: 'La grenouille pond des œufs dans l’eau ; le têtard se transforme en grenouille : c’est une métamorphose.',
    },
    {
      kind: 'mcq',
      id: 'mo-emc-seul',
      lessonId: L,
      question: 'À la récréation, Lina est toute seule et elle pleure. Que fais-tu ?',
      choices: [
        'Je vais la voir et je lui demande ce qui ne va pas.',
        'Je fais comme si je n’avais rien vu.',
        'Je me moque d’elle avec mes copains.',
      ],
      answerIndex: 0,
      image: '😢',
      guillotine: true,
      explication: 'Aider quelqu’un qui est triste, c’est être solidaire. Si c’est grave, on prévient un adulte.',
    },
    {
      kind: 'mcq',
      id: 'mo-emc-harcelement',
      lessonId: L,
      question: 'Depuis plusieurs jours, des élèves se moquent de Tom et le bousculent. Que faut-il faire ?',
      choices: [
        'En parler tout de suite à un adulte de confiance.',
        'Ne rien dire, ça va passer tout seul.',
        'Se moquer aussi pour ne pas être embêté.',
        'Garder le secret pour toujours.',
      ],
      answerIndex: 0,
      image: '🛑',
      guillotine: true,
      explication: 'Des moqueries répétées, c’est du harcèlement : on dit stop et on en parle à un adulte (maîtresse, parents). En France, on peut aussi appeler le 3018.',
    },
    {
      kind: 'mcq',
      id: 'mo-emc-debat',
      lessonId: L,
      question: 'Pendant le conseil de classe, Malo n’est pas d’accord avec toi. Que fais-tu ?',
      choices: [
        'J’écoute son idée, puis je donne la mienne calmement.',
        'Je lui coupe la parole et je crie plus fort.',
        'Je refuse de lui parler pendant une semaine.',
      ],
      answerIndex: 0,
      image: '🗣️',
      guillotine: true,
      explication: 'Dans un débat, chacun a le droit de donner son avis : on écoute l’autre et on parle à son tour, sans se moquer.',
    },
    {
      kind: 'mcq',
      id: 'mo-en-red',
      lessonId: L,
      question: 'Écoute et touche la bonne couleur.',
      choices: ['🔴', '🔵', '🟢', '🟡'],
      answerIndex: 0,
      spoken: 'red',
      lang: 'en-GB',
      guillotine: true,
      explication: '« Red » veut dire rouge.',
    },
    {
      kind: 'mcq',
      id: 'mo-en-dog',
      lessonId: L,
      question: 'Comment dit-on « chien » en anglais ?',
      choices: ['dog', 'cat', 'bird', 'fish'],
      answerIndex: 0,
      image: '🐶',
      spoken: 'dog',
      lang: 'en-GB',
      guillotine: true,
      explication: 'Chien se dit « dog ».',
    },
  ],
  true_false: [
    {
      kind: 'true_false',
      id: 'mo-vf-marianne',
      lessonId: L,
      statement: 'Marianne est un symbole de la République française.',
      answer: true,
      image: '🇫🇷',
      explication: 'Marianne représente la République ; son buste est dans les mairies.',
    },
    {
      kind: 'true_false',
      id: 'mo-vf-continents',
      lessonId: L,
      statement: 'L’Afrique est un océan.',
      answer: false,
      image: '🌍',
      explication: 'L’Afrique est un continent. Les océans sont l’Atlantique, le Pacifique, l’Indien, l’Arctique et l’Austral.',
    },
    {
      kind: 'true_false',
      id: 'mo-vf-14juillet',
      lessonId: L,
      statement: 'La fête nationale française a lieu le 14 juillet.',
      answer: true,
      explication: 'Le 14 juillet est la fête nationale.',
    },
    {
      kind: 'true_false',
      id: 'mo-vf-plante',
      lessonId: L,
      statement: 'Une plante n’a besoin que de terre pour vivre.',
      answer: false,
      image: '🌱',
      explication: 'Une plante a besoin d’eau, de lumière, d’air et de sels minéraux.',
    },
    {
      kind: 'true_false',
      id: 'mo-vf-en',
      lessonId: L,
      statement: '« Blue » veut dire « bleu ».',
      answer: true,
      spoken: 'Blue veut dire bleu.',
      explication: 'Blue = bleu.',
    },
  ],
  pairing: [
    {
      kind: 'pairing',
      id: 'mo-en-animaux',
      lessonId: L,
      prompt: 'Écoute le mot anglais et touche la bonne image.',
      pairs: [
        { left: 'dog', right: '🐶' },
        { left: 'cat', right: '🐱' },
        { left: 'bird', right: '🐦' },
        { left: 'fish', right: '🐟' },
        { left: 'horse', right: '🐴' },
        { left: 'rabbit', right: '🐰' },
      ],
      relation: 'mot → image',
      lang: 'en-GB',
      explication: 'Dog = chien, cat = chat, bird = oiseau, fish = poisson, horse = cheval, rabbit = lapin.',
    },
    {
      kind: 'pairing',
      id: 'mo-en-corps',
      lessonId: L,
      prompt: 'Simon says… touche la bonne partie du corps.',
      pairs: [
        { left: 'touch your nose', right: '👃' },
        { left: 'touch your ear', right: '👂' },
        { left: 'touch your eyes', right: '👀' },
        { left: 'touch your mouth', right: '👄' },
        { left: 'touch your hand', right: '✋' },
        { left: 'touch your foot', right: '🦶' },
      ],
      relation: 'consigne → image',
      lang: 'en-GB',
      explication: 'Nose = nez, ear = oreille, eyes = yeux, mouth = bouche, hand = main, foot = pied.',
    },
    {
      kind: 'pairing',
      id: 'mo-en-couleurs',
      lessonId: L,
      prompt: 'Écoute la couleur et touche la bonne image.',
      pairs: [
        { left: 'red', right: '🔴' },
        { left: 'blue', right: '🔵' },
        { left: 'green', right: '🟢' },
        { left: 'yellow', right: '🟡' },
        { left: 'orange', right: '🟠' },
        { left: 'purple', right: '🟣' },
      ],
      relation: 'mot → image',
      lang: 'en-GB',
      explication: 'Red = rouge, blue = bleu, green = vert, yellow = jaune, orange = orange, purple = violet.',
    },
  ],
  oral_answer: [
    {
      kind: 'oral_answer',
      id: 'mo-oral-cat',
      lessonId: L,
      prompt: 'Dis en anglais : chat 🐱',
      answer: 'cat',
      accepted: ['cat', 'a cat', 'the cat'],
      lang: 'en-GB',
      spoken: 'Dis en anglais : chat',
      explication: 'Chat se dit « cat ».',
    },
    {
      kind: 'oral_answer',
      id: 'mo-oral-hello',
      lessonId: L,
      prompt: 'Dis bonjour en anglais 👋',
      answer: 'hello',
      accepted: ['hello', 'hi', 'hallo', 'hullo'],
      lang: 'en-GB',
      spoken: 'Dis bonjour en anglais',
      explication: 'Pour dire bonjour : « Hello ! » ou « Hi ! »',
    },
  ],
  map_point: [
    {
      kind: 'map_point',
      id: 'mo-carte-bretagne',
      lessonId: L,
      prompt: 'Touche la Bretagne.',
      map: 'france-regions',
      target: 'bretagne',
      targetLabel: 'Bretagne',
      explication: 'La Bretagne est la région tout à l’ouest, entourée par la mer sur trois côtés.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-reunion',
      lessonId: L,
      prompt: 'Touche La Réunion.',
      map: 'france-regions',
      target: 'la-reunion',
      targetLabel: 'La Réunion',
      explication: 'La Réunion est une île de l’océan Indien : c’est une région d’outre-mer.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-loire',
      lessonId: L,
      prompt: 'Touche la Loire.',
      map: 'france-fleuves',
      target: 'loire',
      targetLabel: 'la Loire',
      explication: 'La Loire est le plus long fleuve de France : elle se jette dans l’océan Atlantique, près de Saint-Nazaire.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-alpes',
      lessonId: L,
      prompt: 'Touche les Alpes.',
      map: 'france-massifs',
      target: 'alpes',
      targetLabel: 'les Alpes',
      explication: 'Les Alpes sont à l’est, à la frontière avec l’Italie et la Suisse ; le mont Blanc s’y trouve.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-italie',
      lessonId: L,
      prompt: 'Touche l’Italie.',
      map: 'europe',
      target: 'italie',
      targetLabel: 'l’Italie',
      explication: 'L’Italie a la forme d’une botte, au sud-est de la France. C’est un pays fondateur de l’Union européenne.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-amerique',
      lessonId: L,
      prompt: 'Touche l’Amérique.',
      map: 'monde',
      target: 'amerique',
      targetLabel: 'l’Amérique',
      explication: 'L’Amérique est à l’ouest de l’océan Atlantique ; elle a deux parties : l’Amérique du Nord et l’Amérique du Sud.',
    },
    {
      kind: 'map_point',
      id: 'mo-carte-pacifique',
      lessonId: L,
      prompt: 'Touche l’océan Pacifique.',
      map: 'monde',
      target: 'ocean-pacifique',
      targetLabel: 'l’océan Pacifique',
      explication: 'Le Pacifique est le plus grand océan : il est entre l’Amérique, l’Asie et l’Océanie.',
    },
  ],
};
