/**
 * Enseignement moral et civique CE1 (programme d'EMC du cycle 2, version en vigueur à confirmer) :
 * règles de vie, émotions, symboles de la République, respect d'autrui (harcèlement : dire stop, en
 * parler à un adulte ; égalité filles-garçons), gestes éco-citoyens et tri des déchets.
 * Situations de vie pour le Conseil de la classe : jamais humiliantes, explication « Pourquoi ? ».
 * Seuls les symboles (thème neutre) se jouent dans la Guillotine ; les QCM de
 * `data/questions/ce1_questions.json` (symboles) complètent la banque.
 */
import type { ContentModule } from '../../registry';
import type { Level } from '../../schemas';
import { type Appariement, type Q, type Tri, type VF, paireGen, qcmPool, triGen, vfPool } from './outils';

/* ------------------------------------------------------------------ */
/* Règles de vie, droits et devoirs                                    */
/* ------------------------------------------------------------------ */

const REGLES_QCM: Q[] = [
  // Réponses courtes (Attrape-Bulles au Facile) — compléments du 08/10/2026
  {
    n: 'f',
    id: 'merci-court',
    q: 'Un camarade te prête sa gomme. Que dis-tu ?',
    ok: 'merci',
    ko: ['rien du tout', 'donne-la-moi'],
    img: '🙂',
    ex: 'On dit merci quand quelqu’un nous rend service : c’est la politesse.',
  },
  {
    n: 'f',
    id: 'bonjour-court',
    q: 'Le matin, tu arrives en classe. Que dis-tu à la maîtresse ?',
    ok: 'bonjour',
    ko: ['au revoir', 'rien'],
    img: '👋',
    ex: 'Dire bonjour en arrivant, c’est une règle de politesse.',
  },
  {
    n: 'f',
    id: 'rang-court',
    q: 'La cloche sonne la fin de la récréation. Que fais-tu ?',
    ok: 'je me mets en rang',
    ko: ['je continue à jouer', 'je me cache'],
    img: '🔔',
    ex: 'Quand la cloche sonne, on se range calmement pour rentrer en classe.',
  },
  {
    n: 'f',
    id: 'parole',
    q: 'Tu veux parler pendant la classe. Que fais-tu ?',
    ok: 'je lève le doigt et j’attends mon tour',
    ko: ['je crie très fort', 'je parle en même temps que tout le monde'],
    img: '✋',
    ex: 'Lever le doigt permet à chacun de parler à son tour et d’être écouté.',
  },
  {
    n: 'f',
    id: 'ranger',
    q: 'Tu as fini de dessiner. Que fais-tu de tes crayons ?',
    ok: 'je les range',
    ko: ['je les laisse par terre', 'je les cache dans le cartable d’un copain'],
    img: '✏️',
    ex: 'Ranger son matériel, c’est respecter la classe et les autres.',
  },
  {
    n: 'f',
    id: 'couloir',
    q: 'Dans le couloir, comment te déplaces-tu ?',
    ok: 'je marche calmement',
    ko: ['je cours en criant', 'je pousse les autres'],
    img: '🚶',
    ex: 'En marchant, on évite de tomber ou de bousculer quelqu’un.',
  },
  {
    n: 'f',
    id: 'cantine',
    q: 'À la cantine, ton voisin a renversé son verre d’eau. Que fais-tu ?',
    ok: 'je l’aide à essuyer ou j’appelle un adulte',
    ko: ['je me moque de lui', 'je renverse le mien aussi'],
    ex: 'Tout le monde peut faire une maladresse : on s’entraide.',
  },
  {
    n: 'n',
    id: 'regle-jeu',
    q: 'À la récréation, un élève ne respecte pas la règle du jeu. Que faites-vous ?',
    ok: 'on lui rappelle la règle calmement, et on demande l’aide d’un adulte si besoin',
    ko: ['on le tape', 'on arrête de lui parler pour toujours', 'on change les règles sans lui dire'],
    ex: 'Une règle se rappelle avec des mots, sans violence ; l’adulte aide à régler les conflits.',
  },
  {
    n: 'n',
    id: 'pourquoi-regles',
    q: 'Pourquoi y a-t-il des règles à l’école ?',
    ok: 'pour bien vivre ensemble et être en sécurité',
    ko: ['pour embêter les élèves', 'pour que les adultes s’amusent', 'pour rien du tout'],
    ex: 'Les règles protègent chacun et permettent d’apprendre dans le calme.',
  },
  {
    n: 'n',
    id: 'casse',
    q: 'Sans faire exprès, tu as cassé le crayon de Noah. Que fais-tu ?',
    ok: 'je m’excuse et je lui prête un de mes crayons',
    ko: ['je le cache', 'je dis que c’est quelqu’un d’autre', 'je ne dis rien'],
    ex: 'Tout le monde peut se tromper : on le dit, on s’excuse et on répare si possible.',
  },
  {
    n: 'n',
    id: 'conseil',
    q: 'Que fait-on pendant le conseil de classe ?',
    ok: 'on discute ensemble des problèmes et des projets de la classe',
    ko: ['on fait une dictée', 'on regarde un film', 'on range la classe'],
    ex: 'Au conseil, chacun peut donner son avis à son tour, et on cherche des solutions ensemble.',
  },
  {
    n: 'n',
    id: 'proposer',
    q: 'Qui peut proposer une nouvelle règle de vie pour la classe ?',
    ok: 'tous les élèves, puis on en discute ensemble',
    ko: ['seulement le plus grand', 'personne', 'seulement celui qui crie le plus fort'],
    ex: 'Chacun peut proposer une règle ; on en discute en conseil, avec l’enseignant.',
  },
  {
    n: 'n',
    id: 'droit',
    q: 'Lequel est un droit de l’enfant ?',
    ok: 'le droit d’aller à l’école',
    ko: ['le droit de taper les autres', 'le droit de ne jamais se laver', 'le droit de casser le matériel'],
    ex: 'Tous les enfants ont le droit d’apprendre, d’être protégés, soignés et de jouer.',
  },
  {
    n: 'n',
    id: 'devoir',
    q: 'Lequel est un devoir de l’élève ?',
    ok: 'respecter les autres et le matériel',
    ko: ['manger des bonbons en classe', 'choisir quand venir à l’école', 'parler quand il veut'],
    ex: 'Avoir des droits, c’est aussi avoir des devoirs : respecter les autres et les règles.',
  },
  {
    n: 'p',
    id: 'doigt',
    q: 'Pourquoi lève-t-on le doigt avant de parler ?',
    ok: 'pour que chacun puisse parler à son tour et être écouté',
    ko: ['pour se dégourdir le bras', 'pour faire plaisir à l’enseignant', 'pour gagner un point'],
    ex: 'Si tout le monde parle en même temps, personne ne s’entend.',
  },
  {
    n: 'p',
    id: 'pas-courir',
    q: 'La règle dit : « On ne court pas dans le couloir. » Pourquoi ?',
    ok: 'pour ne pas se faire mal ni bousculer quelqu’un',
    ko: [
      'parce que courir, c’est mal',
      'pour que les élèves s’ennuient',
      'parce que le couloir est trop court',
    ],
    ex: 'Chaque règle a une raison : ici, la sécurité de tous.',
  },
  {
    n: 'p',
    id: 'cide',
    q: 'Les droits de l’enfant sont écrits dans un texte signé par presque tous les pays. Comment s’appelle-t-il ?',
    ok: 'la Convention internationale des droits de l’enfant',
    ko: ['le règlement de la cantine', 'le dictionnaire', 'le carnet de liaison'],
    ex: 'Cette convention, de 1989, protège les droits de tous les enfants du monde.',
  },
  {
    n: 'n',
    id: 'qui-reglement',
    q: 'Qui suis-je ?',
    ok: 'le règlement',
    ko: ['le cahier', 'la récréation', 'le tableau'],
    img: '📜',
    hints: [
      'Je suis écrit et affiché.',
      'Je dis ce qu’on a le droit de faire et ce qui est interdit.',
      'Chacun doit me respecter, les enfants comme les adultes.',
      'Je sers à bien vivre ensemble à l’école.',
    ],
    ex: 'Le règlement rassemble les règles de vie de l’école.',
  },
  {
    n: 'n',
    id: 'qui-conseil',
    q: 'Qui suis-je ?',
    ok: 'le conseil de classe',
    ko: ['la récréation', 'la dictée', 'la cantine'],
    img: '🗣️',
    hints: [
      'Je suis un moment de la vie de la classe.',
      'On s’assoit souvent en cercle.',
      'Chacun peut donner son avis, à son tour.',
      'On y discute des problèmes et des projets de la classe.',
    ],
    ex: 'Au conseil de classe, on discute et on décide ensemble.',
  },
  {
    n: 'n',
    id: 'qui-politesse',
    q: 'Qui suis-je ?',
    ok: 'la politesse',
    ko: ['la colère', 'la paresse', 'la gourmandise'],
    img: '🤝',
    hints: [
      'Je commence souvent par « bonjour » et je finis par « au revoir ».',
      'Avec moi, on dit « s’il te plaît » et « merci ».',
      'Je rends la vie plus agréable.',
      'Je suis une façon respectueuse de parler aux autres.',
    ],
    ex: 'La politesse, ce sont les mots et les gestes qui montrent qu’on respecte les autres.',
  },
  {
    n: 'n',
    id: 'qui-baton',
    q: 'Qui suis-je ?',
    ok: 'le bâton de parole',
    ko: ['la baguette magique', 'la règle', 'le crayon'],
    img: '🎤',
    hints: [
      'Je suis un objet.',
      'Je passe de main en main pendant les discussions.',
      'Celui qui me tient a le droit de parler.',
      'Les autres écoutent sans couper la parole.',
    ],
    ex: 'Le bâton de parole aide chacun à parler à son tour.',
  },
];

const REGLES_VF: VF[] = [
  {
    n: 'f',
    id: 'doigt',
    s: 'On lève le doigt pour demander la parole.',
    v: true,
    img: '✋',
    ex: 'Ainsi, chacun parle à son tour.',
  },
  {
    n: 'f',
    id: 'courir',
    s: 'On peut courir dans les couloirs.',
    v: false,
    ex: 'On marche dans les couloirs pour ne blesser personne.',
  },
  {
    n: 'f',
    id: 'ensemble',
    s: 'Les règles de la classe servent à bien vivre ensemble.',
    v: true,
    ex: 'Elles protègent chacun et aident à apprendre.',
  },
  {
    n: 'f',
    id: 'ranger',
    s: 'Ranger ses affaires aide toute la classe.',
    v: true,
    ex: 'Une classe rangée, c’est plus agréable et on ne perd rien.',
  },
  {
    n: 'n',
    id: 'adultes',
    s: 'Seuls les enfants doivent respecter les règles.',
    v: false,
    ex: 'Les règles s’appliquent à tout le monde, adultes compris.',
  },
  {
    n: 'n',
    id: 'accident',
    s: 'Si je casse quelque chose sans le vouloir, je le dis et je m’excuse.',
    v: true,
    ex: 'Dire la vérité et s’excuser, c’est respecter les autres.',
  },
  {
    n: 'n',
    id: 'droit-ecole',
    s: 'Tous les enfants ont le droit d’aller à l’école.',
    v: true,
    ex: 'C’est un droit de l’enfant : le droit d’apprendre.',
  },
  {
    n: 'n',
    id: 'conseil',
    s: 'Au conseil de classe, chacun peut donner son avis.',
    v: true,
    ex: 'On parle à son tour et on écoute les autres.',
  },
  {
    n: 'n',
    id: 'politesse',
    s: 'On doit être poli seulement avec les adultes.',
    v: false,
    ex: 'On est poli avec tout le monde : adultes et enfants.',
  },
  {
    n: 'p',
    id: 'raison',
    s: 'Chaque règle de l’école a une raison.',
    v: true,
    ex: 'La sécurité, le calme, le respect : on peut toujours expliquer une règle.',
  },
];

const RES = 'je respecte la règle';
const NRES = 'je ne respecte pas la règle';
const DR = 'un droit de l’enfant';
const DV = 'un devoir de l’élève';
const REGLES_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'respecte',
      prompt: 'Est-ce que je respecte la règle de la classe ?',
      categories: [RES, NRES],
      elements: [
        { label: 'je lève le doigt pour parler', c: RES, n: 'f', img: '✋' },
        { label: 'je range mes affaires', c: RES, n: 'f' },
        { label: 'je marche dans le couloir', c: RES, n: 'f', img: '🚶' },
        { label: 'j’attends mon tour', c: RES, n: 'f' },
        { label: 'j’écoute quand quelqu’un parle', c: RES, n: 'f', img: '👂' },
        { label: 'je coupe la parole', c: NRES, n: 'f' },
        { label: 'je jette mes papiers par terre', c: NRES, n: 'f' },
        { label: 'je cours dans les escaliers', c: NRES, n: 'f' },
        { label: 'je prends la gomme d’un camarade sans demander', c: NRES, n: 'f' },
      ],
      ex: 'Respecter les règles, c’est permettre à chacun de bien vivre et de bien apprendre.',
    },
  ],
  normal: [
    {
      id: 'droits-devoirs',
      prompt: 'Est-ce un droit de l’enfant ou un devoir de l’élève ?',
      categories: [DR, DV],
      elements: [
        { label: 'être protégé', c: DR, n: 'n' },
        { label: 'apprendre à l’école', c: DR, n: 'n' },
        { label: 'jouer', c: DR, n: 'n' },
        { label: 'être soigné', c: DR, n: 'n' },
        { label: 'avoir un nom', c: DR, n: 'n' },
        { label: 'respecter les autres', c: DV, n: 'n' },
        { label: 'prendre soin du matériel', c: DV, n: 'n' },
        { label: 'écouter les consignes', c: DV, n: 'n' },
        { label: 'respecter le règlement', c: DV, n: 'n' },
      ],
      ex: 'Les enfants ont des droits (apprendre, être protégés, jouer…) et des devoirs (respecter les autres et les règles).',
    },
  ],
  plus_loin: [
    {
      id: 'droits-devoirs',
      prompt: 'Est-ce un droit de l’enfant ou un devoir de l’élève ?',
      categories: [DR, DV],
      elements: [
        { label: 'être protégé', c: DR, n: 'p' },
        { label: 'apprendre à l’école', c: DR, n: 'p' },
        { label: 'jouer', c: DR, n: 'p' },
        { label: 'être soigné', c: DR, n: 'p' },
        { label: 'donner son avis', c: DR, n: 'p' },
        { label: 'avoir un nom et une nationalité', c: DR, n: 'p' },
        { label: 'respecter les autres', c: DV, n: 'p' },
        { label: 'prendre soin du matériel', c: DV, n: 'p' },
        { label: 'écouter l’avis des autres', c: DV, n: 'p' },
        { label: 'respecter le règlement', c: DV, n: 'p' },
      ],
      ex: 'Les droits de l’enfant sont écrits dans la Convention internationale des droits de l’enfant ; les devoirs permettent de vivre ensemble.',
      nb: 8,
    },
  ],
};

const REGLES_PAIRES: Record<Level, Appariement[]> = (() => {
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'pictos',
    prompt: 'Associe chaque règle de la classe à son pictogramme.',
    relation: 'règle → pictogramme',
    duos: [
      { l: 'parler doucement', r: '🤫', n },
      { l: 'lever le doigt', r: '✋', n },
      { l: 'marcher dans le couloir', r: '🚶', n },
      { l: 'ranger sa place', r: '🧹', n },
      { l: 'jeter à la poubelle', r: '🗑️', n },
      { l: 'écouter les autres', r: '👂', n },
      { l: 'se laver les mains', r: '🧼', n },
    ],
    ex: 'Les pictogrammes rappellent les règles de vie de la classe.',
    nb,
  });
  return { facile: [a('f', 4)], normal: [a('n', 6)], plus_loin: [a('p', 7)] };
})();

/* ------------------------------------------------------------------ */
/* Émotions                                                            */
/* ------------------------------------------------------------------ */

const EMO_QCM: Q[] = [
  {
    n: 'f',
    id: 'cadeau',
    q: 'Léo a reçu un cadeau qu’il adore. Que ressent-il ?',
    ok: 'de la joie',
    ko: ['de la colère', 'de la peur'],
    img: '🎁',
    ex: 'Recevoir quelque chose qu’on aime donne de la joie.',
  },
  {
    n: 'f',
    id: 'doudou',
    q: 'Sami a perdu son doudou. Que ressent-il ?',
    ok: 'de la tristesse',
    ko: ['de la joie', 'de la fierté'],
    img: '🧸',
    ex: 'Perdre quelque chose qu’on aime rend triste. On peut l’aider à le chercher et le consoler.',
  },
  {
    n: 'f',
    id: 'chien',
    q: 'Un gros chien aboie très fort près d’Anna. Que ressent-elle sans doute ?',
    ok: 'de la peur',
    ko: ['de la joie', 'de la fierté'],
    img: '🐕',
    ex: 'Devant quelque chose qui semble dangereux, on peut avoir peur : c’est normal.',
  },
  {
    n: 'n',
    id: 'chateau',
    q: 'Un élève a fait tomber exprès le château de cubes d’Inès. Que ressent-elle sans doute ?',
    ok: 'de la colère',
    ko: ['de la joie', 'de la fierté', 'de la surprise agréable'],
    img: '😠',
    ex: 'Quand quelqu’un abîme exprès ce qu’on a fait, on peut être en colère. On le dit avec des mots.',
  },
  {
    n: 'n',
    id: 'colere',
    q: 'Quand tu es très en colère, que peux-tu faire ?',
    ok: 'respirer lentement et dire ce que je ressens avec des mots',
    ko: ['taper quelqu’un', 'casser un objet', 'crier des insultes'],
    ex: 'La colère, c’est normal ; on la calme en respirant et on l’exprime avec des mots.',
  },
  {
    n: 'n',
    id: 'copain-triste',
    q: 'Ton copain a l’air triste. Que peux-tu faire ?',
    ok: 'lui demander ce qui ne va pas et l’écouter',
    ko: ['me moquer de lui', 'le laisser seul exprès', 'lui dire d’arrêter de pleurer'],
    ex: 'Écouter quelqu’un qui est triste, c’est déjà l’aider.',
  },
  {
    n: 'n',
    id: 'deviner',
    q: 'Comment peut-on savoir ce que ressent quelqu’un ?',
    ok: 'en regardant son visage et en lui demandant',
    ko: ['en devinant sans rien regarder', 'c’est impossible', 'en regardant ses chaussures'],
    ex: 'Le visage, la voix et les gestes montrent les émotions ; et on peut toujours demander.',
  },
  {
    n: 'n',
    id: 'velo',
    q: 'Tom a réussi à faire du vélo sans petites roues. Il se sent…',
    ok: 'fier',
    ko: ['triste', 'dégoûté', 'effrayé'],
    img: '🚲',
    ex: 'Réussir quelque chose de difficile rend fier de soi.',
  },
  {
    n: 'n',
    id: 'normal-peur',
    q: 'Est-ce normal d’avoir peur parfois ?',
    ok: 'oui, tout le monde a peur parfois',
    ko: ['non, jamais', 'seulement les bébés'],
    ex: 'La peur est une émotion utile : elle nous protège des dangers. Tout le monde la ressent.',
  },
  {
    n: 'p',
    id: 'dire',
    q: 'Pourquoi est-ce utile de dire ce que l’on ressent ?',
    ok: 'pour que les autres comprennent et puissent aider',
    ko: ['pour que tout le monde se moque', 'ce n’est jamais utile', 'pour se disputer'],
    ex: 'Mettre des mots sur ses émotions aide à se sentir mieux et à être compris.',
  },
  {
    n: 'p',
    id: 'perdu-jeu',
    q: 'Ton ami pleure parce qu’il a perdu au jeu. Que lui dis-tu ?',
    ok: '« Ce n’est pas grave, on rejouera ensemble. »',
    ko: ['« Tu es nul ! »', '« Bien fait pour toi ! »', '« Arrête, tu es un bébé ! »'],
    ex: 'On console avec des mots gentils : perdre fait partie du jeu.',
  },
  {
    n: 'p',
    id: 'calmer',
    q: 'Qu’est-ce qui peut aider à se calmer quand on est très en colère ?',
    ok: 'respirer lentement, s’éloigner un moment, puis en parler',
    ko: ['taper du pied sur un camarade', 'crier plus fort', 'casser ses crayons'],
    ex: 'Un coin calme, une respiration lente, puis des mots : la colère passe.',
  },
  {
    n: 'n',
    id: 'qui-colere',
    q: 'Qui suis-je ?',
    ok: 'la colère',
    ko: ['la joie', 'la peur', 'la surprise'],
    img: '😠',
    hints: [
      'Je suis une émotion.',
      'Avec moi, on serre parfois les poings et les dents.',
      'Je peux rendre le visage tout rouge.',
      'Pour me calmer, on respire lentement.',
    ],
    ex: 'La colère est une émotion normale ; on l’exprime avec des mots, sans faire mal.',
  },
  {
    n: 'n',
    id: 'qui-peur',
    q: 'Qui suis-je ?',
    ok: 'la peur',
    ko: ['la joie', 'la colère', 'la fierté'],
    img: '😨',
    hints: [
      'Je suis une émotion.',
      'Avec moi, le cœur bat très vite.',
      'J’arrive dans le noir ou devant un danger.',
      'Avec moi, on a parfois envie de se cacher.',
    ],
    ex: 'La peur nous avertit d’un danger ; on peut en parler à un adulte.',
  },
  {
    n: 'n',
    id: 'qui-joie',
    q: 'Qui suis-je ?',
    ok: 'la joie',
    ko: ['la tristesse', 'la colère', 'la peur'],
    img: '😄',
    hints: [
      'Je suis une émotion.',
      'Je donne envie de rire et de sauter.',
      'J’arrive quand on joue avec ses amis ou qu’on reçoit un câlin.',
      'Je fais sourire.',
    ],
    ex: 'La joie est une émotion agréable qui donne le sourire.',
  },
  {
    n: 'n',
    id: 'qui-tristesse',
    q: 'Qui suis-je ?',
    ok: 'la tristesse',
    ko: ['la joie', 'la colère', 'la surprise'],
    img: '😢',
    hints: [
      'Je suis une émotion.',
      'Avec moi, on a parfois envie de pleurer.',
      'J’arrive quand on perd quelque chose ou quelqu’un qu’on aime.',
      'Un câlin ou une discussion peut m’aider à partir.',
    ],
    ex: 'La tristesse passe mieux quand on en parle à quelqu’un.',
  },
  {
    n: 'n',
    id: 'qui-surprise',
    q: 'Qui suis-je ?',
    ok: 'la surprise',
    ko: ['la peur', 'la colère', 'la tristesse'],
    img: '😲',
    hints: [
      'Je suis une émotion.',
      'J’arrive quand on ne s’y attend pas.',
      'J’ouvre grand les yeux et la bouche.',
      'On dit « Oh ! » quand je suis là.',
    ],
    ex: 'La surprise arrive quand quelque chose d’inattendu se passe.',
  },
];

const EMO_VF: VF[] = [
  {
    n: 'f',
    id: 'peur-normal',
    s: 'Avoir peur, c’est normal : tout le monde a peur parfois.',
    v: true,
    img: '😨',
    ex: 'La peur est une émotion que tout le monde ressent.',
  },
  {
    n: 'f',
    id: 'taper',
    s: 'Quand on est en colère, on a le droit de taper.',
    v: false,
    img: '😠',
    ex: 'On a le droit d’être en colère, mais pas de faire mal : on le dit avec des mots.',
  },
  {
    n: 'f',
    id: 'mots',
    s: 'On peut dire ce qu’on ressent avec des mots.',
    v: true,
    ex: '« Je suis triste », « Je suis en colère » : les mots aident les autres à comprendre.',
  },
  {
    n: 'f',
    id: 'aide',
    s: 'Je peux demander de l’aide à un adulte quand je suis triste.',
    v: true,
    ex: 'Les adultes de confiance sont là pour écouter et aider.',
  },
  {
    n: 'n',
    id: 'garcons-pleurer',
    s: 'Les garçons n’ont pas le droit de pleurer.',
    v: false,
    img: '😢',
    ex: 'Tout le monde a le droit de pleurer : les filles comme les garçons.',
  },
  {
    n: 'n',
    id: 'respirer',
    s: 'Respirer lentement aide à se calmer.',
    v: true,
    ex: 'Une respiration lente calme le corps et la colère.',
  },
  {
    n: 'n',
    id: 'toujours',
    s: 'Une émotion dure toujours.',
    v: false,
    ex: 'Les émotions passent : on peut être triste le matin et joyeux l’après-midi.',
  },
  {
    n: 'n',
    id: 'visage',
    s: 'Le visage montre souvent ce que l’on ressent.',
    v: true,
    ex: 'Sourire, sourcils froncés, larmes : le visage parle.',
  },
  {
    n: 'p',
    id: 'meme-chose',
    s: 'Face à la même situation, tout le monde ressent la même émotion.',
    v: false,
    ex: 'Chacun est différent : un orage fait peur à l’un et amuse l’autre.',
  },
];

const AG = 'une émotion agréable';
const DES = 'une émotion désagréable';
const EMO_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'situations',
      prompt: 'Le plus souvent, cela rend joyeux ou triste ?',
      categories: ['ça rend joyeux', 'ça rend triste'],
      elements: [
        { label: 'recevoir un câlin', c: 'ça rend joyeux', n: 'f', img: '🤗' },
        { label: 'jouer avec mes amis', c: 'ça rend joyeux', n: 'f', img: '⚽' },
        { label: 'fêter mon anniversaire', c: 'ça rend joyeux', n: 'f', img: '🎂' },
        { label: 'réussir un exercice difficile', c: 'ça rend joyeux', n: 'f', img: '⭐' },
        { label: 'perdre mon doudou', c: 'ça rend triste', n: 'f', img: '🧸' },
        { label: 'mon meilleur ami déménage', c: 'ça rend triste', n: 'f', img: '📦' },
        { label: 'casser mon jouet préféré', c: 'ça rend triste', n: 'f' },
        { label: 'être seul à la récréation', c: 'ça rend triste', n: 'f' },
      ],
      ex: 'Certaines situations donnent de la joie, d’autres de la tristesse. Toutes les émotions sont normales.',
    },
  ],
  normal: [
    {
      id: 'agreable',
      prompt: 'Émotion agréable ou désagréable ?',
      categories: [AG, DES],
      elements: [
        { label: 'la joie', c: AG, n: 'n', img: '😄' },
        { label: 'la fierté', c: AG, n: 'n' },
        { label: 'l’amusement', c: AG, n: 'n', img: '😂' },
        { label: 'la tendresse', c: AG, n: 'n', img: '🥰' },
        { label: 'la tristesse', c: DES, n: 'n', img: '😢' },
        { label: 'la colère', c: DES, n: 'n', img: '😠' },
        { label: 'la peur', c: DES, n: 'n', img: '😨' },
        { label: 'le dégoût', c: DES, n: 'n', img: '🤢' },
      ],
      ex: 'Certaines émotions sont agréables, d’autres désagréables ; elles sont toutes normales et elles passent.',
    },
  ],
  plus_loin: [
    {
      id: 'agreable',
      prompt: 'Émotion agréable ou désagréable ?',
      categories: [AG, DES],
      elements: [
        { label: 'la joie', c: AG, n: 'p', img: '😄' },
        { label: 'la fierté', c: AG, n: 'p' },
        { label: 'le soulagement', c: AG, n: 'p', img: '😌' },
        { label: 'la tendresse', c: AG, n: 'p', img: '🥰' },
        { label: 'la tristesse', c: DES, n: 'p', img: '😢' },
        { label: 'la colère', c: DES, n: 'p', img: '😠' },
        { label: 'la jalousie', c: DES, n: 'p' },
        { label: 'la honte', c: DES, n: 'p' },
        { label: 'le dégoût', c: DES, n: 'p', img: '🤢' },
      ],
      ex: 'Toutes les émotions sont normales ; les désagréables passent mieux quand on en parle.',
      nb: 8,
    },
  ],
};

const EMO_PAIRES: Record<Level, Appariement[]> = (() => {
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'visages',
    prompt: 'Associe chaque émotion au bon visage.',
    relation: 'émotion → visage',
    duos: [
      { l: 'la joie', r: '😄', n },
      { l: 'la tristesse', r: '😢', n },
      { l: 'la colère', r: '😠', n },
      { l: 'la peur', r: '😨', n },
      { l: 'la surprise', r: '😲', n },
      { l: 'le dégoût', r: '🤢', n },
    ],
    ex: 'Le visage montre les émotions : sourire pour la joie, larmes pour la tristesse, sourcils froncés pour la colère…',
    nb,
  });
  return { facile: [a('f', 4)], normal: [a('n', 6)], plus_loin: [a('p', 6)] };
})();

/* ------------------------------------------------------------------ */
/* Symboles de la République                                           */
/* ------------------------------------------------------------------ */

const SYM_QCM: Q[] = [
  {
    n: 'n',
    id: 'quatorze',
    q: 'Que fête-t-on le 14 juillet ?',
    ok: 'la fête nationale',
    ko: ['Noël', 'la rentrée', 'le jour de l’An'],
    img: '🎆',
    ex: 'Le 14 juillet est la fête nationale de la France : défilés et feux d’artifice.',
  },
  {
    n: 'n',
    id: 'fronton',
    q: 'Où peut-on lire la devise « Liberté, Égalité, Fraternité » ?',
    ok: 'sur le fronton des mairies et des écoles',
    ko: ['sur les boîtes de céréales', 'sur les panneaux de la route', 'sur les tickets de bus'],
    img: '🏛️',
    ex: 'La devise de la République est inscrite sur les bâtiments publics.',
  },
  {
    n: 'f',
    id: 'milieu',
    q: 'Quelle est la couleur de la bande du milieu du drapeau français ?',
    ok: 'blanc',
    ko: ['bleu', 'rouge'],
    img: '🇫🇷',
    ex: 'Le drapeau français est bleu, blanc, rouge : le blanc est au milieu.',
  },
  {
    n: 'n',
    id: 'marianne',
    q: 'Que représente Marianne ?',
    ok: 'la République française',
    ko: ['une reine', 'une chanteuse', 'une maitresse d’école'],
    ex: 'Marianne est une figure qui représente la République.',
  },
  {
    n: 'p',
    id: 'marseillaise-date',
    q: 'En quelle année La Marseillaise a-t-elle été écrite ?',
    ok: '1792',
    ko: ['1515', '1900', '2000'],
    ex: 'La Marseillaise a été écrite en 1792 par Rouget de Lisle ; elle est devenue l’hymne national.',
  },
  {
    n: 'p',
    id: 'bonnet',
    q: 'Quel bonnet porte souvent Marianne ?',
    ok: 'le bonnet phrygien',
    ko: ['le bonnet de nuit', 'la casquette', 'la couronne'],
    ex: 'Le bonnet phrygien est un symbole de liberté.',
  },
  {
    n: 'n',
    id: 'qui-marianne',
    q: 'Qui suis-je ?',
    ok: 'Marianne',
    ko: ['Jeanne d’Arc', 'une reine', 'Blanche-Neige'],
    img: '🇫🇷',
    hints: [
      'Je suis une femme.',
      'Je ne suis pas une vraie personne : je suis un symbole.',
      'Je porte souvent un bonnet phrygien.',
      'Mon buste est dans les mairies.',
      'Je représente la République française.',
    ],
    ex: 'Marianne est le symbole de la République française.',
  },
  {
    n: 'f',
    id: 'qui-drapeau',
    q: 'Qui suis-je ?',
    ok: 'le drapeau français',
    ko: ['La Marseillaise', 'le coq', 'Marianne'],
    img: '🇫🇷',
    hints: [
      'Je flotte au vent.',
      'On me voit sur les mairies et les écoles.',
      'J’ai trois bandes verticales.',
      'Je suis bleu, blanc, rouge.',
    ],
    ex: 'Le drapeau tricolore bleu, blanc, rouge est un symbole de la République.',
  },
  {
    n: 'n',
    id: 'qui-marseillaise',
    q: 'Qui suis-je ?',
    ok: 'La Marseillaise',
    ko: ['le 14 juillet', 'Marianne', 'la devise'],
    img: '🎵',
    hints: [
      'Je suis une chanson.',
      'J’ai été écrite en 1792.',
      'On me chante avant les matchs de l’équipe de France.',
      'Je suis l’hymne national.',
    ],
    ex: 'La Marseillaise est l’hymne national de la France.',
  },
  {
    n: 'n',
    id: 'qui-14-juillet',
    q: 'Qui suis-je ?',
    ok: 'le 14 juillet',
    ko: ['le 1er janvier', 'le 25 décembre', 'le 1er mai'],
    img: '🎆',
    hints: [
      'Je suis une date.',
      'Je suis en été.',
      'Ce jour-là, il y a des défilés et des feux d’artifice.',
      'Je suis la fête nationale.',
    ],
    ex: 'Le 14 juillet est la fête nationale.',
  },
  {
    n: 'n',
    id: 'qui-devise',
    q: 'Qui suis-je ?',
    ok: 'la devise de la République',
    ko: ['l’hymne national', 'le drapeau', 'Marianne'],
    img: '🏛️',
    hints: [
      'Je suis faite de trois mots.',
      'On m’écrit sur le fronton des écoles et des mairies.',
      'Mon premier mot est « Liberté ».',
      'Je suis « Liberté, Égalité, Fraternité ».',
    ],
    ex: 'La devise de la République est « Liberté, Égalité, Fraternité ».',
  },
  {
    n: 'p',
    id: 'qui-coq',
    q: 'Qui suis-je ?',
    ok: 'le coq',
    ko: ['le lion', 'l’aigle', 'l’ours'],
    img: '🐓',
    hints: [
      'Je suis un animal.',
      'Je chante le matin : cocorico !',
      'Je suis un symbole ancien de la France.',
      'On me voit sur les maillots des équipes de France.',
    ],
    ex: 'Le coq gaulois est un symbole ancien de la France.',
  },
];

const SYM_VF: VF[] = [
  {
    n: 'f',
    id: 'drapeau',
    s: 'Le drapeau français est bleu, blanc, rouge.',
    v: true,
    img: '🇫🇷',
    ex: 'C’est le drapeau tricolore.',
  },
  {
    n: 'f',
    id: 'marseillaise',
    s: 'La Marseillaise est l’hymne national.',
    v: true,
    img: '🎵',
    ex: 'On la chante lors des cérémonies.',
  },
  {
    n: 'f',
    id: 'noel',
    s: 'La fête nationale est le 25 décembre.',
    v: false,
    ex: 'La fête nationale est le 14 juillet ; le 25 décembre, c’est Noël.',
  },
  {
    n: 'n',
    id: 'devise',
    s: 'La devise de la République est « Un pour tous, tous pour un ».',
    v: false,
    ex: 'La devise est « Liberté, Égalité, Fraternité ».',
  },
  {
    n: 'n',
    id: 'marianne',
    s: 'Marianne représente la République.',
    v: true,
    ex: 'Son buste est dans les mairies.',
  },
  {
    n: 'n',
    id: 'buste',
    s: 'On trouve le buste de Marianne dans les mairies.',
    v: true,
    ex: 'Marianne est présente dans toutes les mairies.',
  },
  {
    n: 'n',
    id: 'quatorze',
    s: 'Le 14 juillet, il y a souvent des feux d’artifice.',
    v: true,
    img: '🎆',
    ex: 'On fête la fête nationale avec des défilés et des feux d’artifice.',
  },
  {
    n: 'p',
    id: 'egalite',
    s: '« Égalité » veut dire que tout le monde a les mêmes droits.',
    v: true,
    ex: 'Filles et garçons, tous les citoyens ont les mêmes droits.',
  },
  {
    n: 'p',
    id: 'coq-anglais',
    s: 'Le coq est un symbole de l’Angleterre.',
    v: false,
    ex: 'Le coq est un symbole ancien de la France.',
  },
];

const SYM_PAIRES: Record<Level, Appariement[]> = (() => {
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'symboles',
    prompt: 'Associe chaque symbole à ce qu’il est.',
    relation: 'symbole → description',
    duos: [
      { l: 'le drapeau', r: 'bleu, blanc, rouge', n },
      { l: 'l’hymne national', r: 'La Marseillaise', n },
      { l: 'la fête nationale', r: 'le 14 juillet', n },
      { l: 'la République', r: 'Marianne', n },
      { l: 'la devise', r: 'Liberté, Égalité, Fraternité', n },
      { l: 'un animal symbole', r: 'le coq', n },
    ],
    ex: 'Drapeau tricolore, Marseillaise, 14 juillet, Marianne et la devise « Liberté, Égalité, Fraternité » sont les symboles de la République. Le coq est un symbole ancien de la France, mais pas un symbole officiel de la République.',
    nb,
  });
  // variante aux étiquettes courtes (Dobble des mots)
  const b = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'symboles-courts',
    prompt: 'Associe chaque symbole à ce qu’il est.',
    relation: 'symbole → description',
    duos: [
      { l: 'le drapeau', r: 'bleu, blanc, rouge', n },
      { l: 'l’hymne national', r: 'La Marseillaise', n },
      { l: 'la fête nationale', r: 'le 14 juillet', n },
      { l: 'la République', r: 'Marianne', n },
      { l: 'un animal symbole', r: 'le coq', n },
      { l: 'le bonnet de Marianne', r: 'le bonnet phrygien', n },
    ],
    ex: 'Le drapeau tricolore, La Marseillaise, le 14 juillet et Marianne (avec son bonnet phrygien) sont des symboles de la République. Le coq est un symbole ancien de la France, mais pas un symbole officiel de la République.',
    nb,
  });
  return {
    facile: [a('f', 3), b('f', 3)],
    normal: [a('n', 5), b('n', 5)],
    plus_loin: [a('p', 6), b('p', 6)],
  };
})();

/* ------------------------------------------------------------------ */
/* Respect d'autrui, harcèlement, égalité filles-garçons               */
/* ------------------------------------------------------------------ */

const RESP_QCM: Q[] = [
  {
    n: 'f',
    id: 'stop',
    q: 'Un camarade te dit : « Arrête, je n’aime pas ça ! ». Que fais-tu ?',
    ok: 'j’arrête tout de suite',
    ko: ['je continue', 'je rigole encore plus fort'],
    img: '✋',
    ex: 'Quand quelqu’un dit « stop », on arrête : c’est le respecter.',
  },
  {
    n: 'f',
    id: 'moquerie',
    q: 'Quelqu’un se moque de toi. Que peux-tu dire ?',
    ok: '« Stop ! Je n’aime pas ça. »',
    ko: ['je le tape', 'je me moque de lui encore plus fort'],
    img: '🛑',
    ex: 'On dit « stop » clairement. Si ça continue, on en parle à un adulte.',
  },
  {
    n: 'f',
    id: 'seule',
    q: 'À la récréation, Lina est toute seule et elle pleure. Que fais-tu ?',
    ok: 'je vais la voir et je lui demande ce qui ne va pas',
    ko: ['je fais comme si je n’avais rien vu', 'je me moque d’elle avec mes copains'],
    img: '😢',
    ex: 'Aider quelqu’un qui est triste, c’est être solidaire. Si c’est grave, on prévient un adulte.',
  },
  {
    n: 'n',
    id: 'yanis',
    q: 'Depuis plusieurs jours, des élèves se moquent de Yanis et le bousculent. Que faut-il faire ?',
    ok: 'en parler tout de suite à un adulte de confiance',
    ko: [
      'ne rien dire, ça va passer tout seul',
      'se moquer aussi pour ne pas être embêté',
      'garder le secret pour toujours',
    ],
    img: '🛑',
    ex: 'Des moqueries qui recommencent, c’est du harcèlement : on dit stop et on en parle à un adulte.',
  },
  {
    n: 'n',
    id: 'temoin',
    q: 'Tu vois un élève se faire embêter tous les jours. Que fais-tu ?',
    ok: 'je le dis à un adulte : ce n’est pas rapporter, c’est aider',
    ko: ['je regarde et je ris', 'je ne dis rien, ce n’est pas mon problème'],
    ex: 'Le témoin peut aider : prévenir un adulte protège la personne embêtée.',
  },
  {
    n: 'n',
    id: 'adulte',
    q: 'Qui est un adulte de confiance à qui parler si quelqu’un t’embête ?',
    ok: 'un parent, la maitresse, le maitre ou un animateur',
    ko: ['un inconnu dans la rue', 'personne', 'un inconnu sur internet'],
    ex: 'Les adultes de confiance sont là pour t’écouter et te protéger.',
  },
  {
    n: 'n',
    id: 'harcelement',
    q: 'Qu’est-ce que le harcèlement ?',
    ok: 'être embêté, moqué ou mis à l’écart exprès, plusieurs fois',
    ko: [
      'une petite dispute d’une minute',
      'un jeu où tout le monde rigole ensemble',
      'une partie de chat perché',
    ],
    ex: 'Le harcèlement, c’est quand ça recommence, exprès, contre la même personne. Ce n’est jamais la faute de la victime.',
  },
  {
    n: 'n',
    id: 'foot',
    q: 'À la récréation, des élèves disent à Emma : « Le foot, ce n’est pas pour les filles ! » Qu’en penses-tu ?',
    ok: 'c’est faux : filles et garçons peuvent jouer au foot',
    ko: ['c’est vrai', 'les filles doivent jouer à autre chose'],
    img: '⚽',
    ex: 'Les filles et les garçons peuvent faire les mêmes jeux et les mêmes sports.',
  },
  {
    n: 'n',
    id: 'metiers',
    q: 'Qui peut devenir pompier, médecin ou danseur ?',
    ok: 'les filles comme les garçons',
    ko: ['seulement les garçons', 'seulement les filles'],
    ex: 'Tous les métiers sont ouverts aux filles et aux garçons.',
  },
  {
    n: 'n',
    id: 'danse',
    q: 'Mathis adore la danse. Des élèves se moquent de lui. Que dis-tu ?',
    ok: '« Chacun a le droit d’aimer ce qu’il veut. »',
    ko: ['« La danse, c’est pour les filles. »', '« Tu as raison, c’est bizarre. »'],
    img: '🕺',
    ex: 'Les goûts n’ont pas de genre : chacun peut aimer la danse, le foot ou le dessin.',
  },
  {
    n: 'n',
    id: 'accent',
    q: 'Arthur se moque de Chloé parce qu’elle bégaie un peu. Que fais-tu ?',
    ok: 'je dis à Arthur que ce n’est pas gentil et je vais voir Chloé',
    ko: ['je rigole avec Arthur', 'j’imite Chloé aussi'],
    ex: 'Nos différences sont une richesse : on ne se moque jamais de quelqu’un.',
  },
  {
    n: 'p',
    id: 'rapporter',
    q: 'Pourquoi parler du harcèlement à un adulte, ce n’est pas « rapporter » ?',
    ok: 'parce qu’on aide quelqu’un qui souffre',
    ko: ['parce qu’on veut punir quelqu’un', 'parce que c’est amusant', 'parce qu’on veut une récompense'],
    ex: 'Rapporter, c’est vouloir nuire ; alerter, c’est protéger quelqu’un.',
  },
  {
    n: 'p',
    id: 'egalite',
    q: 'Que veut dire « égalité entre les filles et les garçons » ?',
    ok: 'ils ont les mêmes droits et peuvent faire les mêmes choses',
    ko: [
      'ils doivent porter les mêmes vêtements',
      'ils doivent tous aimer les mêmes jeux',
      'ils doivent toujours jouer séparément',
    ],
    ex: 'Égalité ne veut pas dire « pareils » : chacun est différent, mais tous ont les mêmes droits.',
  },
  {
    n: 'p',
    id: 'message',
    q: 'Un message méchant sur toi circule sur une tablette. Que fais-tu ?',
    ok: 'je ne réponds pas et je le montre à un adulte',
    ko: ['je réponds par un message encore plus méchant', 'je le supprime et je n’en parle à personne'],
    ex: 'On ne répond pas, on garde le message et on le montre à un adulte de confiance.',
  },
  {
    n: 'n',
    id: 'qui-respect',
    q: 'Qui suis-je ?',
    ok: 'le respect',
    ko: ['la moquerie', 'la colère', 'la paresse'],
    img: '🤝',
    hints: [
      'Je suis une valeur importante.',
      'Avec moi, on écoute les autres sans se moquer.',
      'Avec moi, on fait attention aux autres et à leurs affaires.',
      'Grâce à moi, chacun se sent bien à l’école.',
    ],
    ex: 'Le respect, c’est faire attention aux autres, à leurs idées et à leurs affaires.',
  },
  {
    n: 'n',
    id: 'qui-egalite',
    q: 'Qui suis-je ?',
    ok: 'l’égalité',
    ko: ['la liberté', 'la fraternité', 'la politesse'],
    img: '⚖️',
    hints: [
      'Je suis un mot de la devise de la République.',
      'Avec moi, filles et garçons ont les mêmes droits.',
      'Avec moi, personne n’est mis de côté à cause de sa différence.',
      'Dans la devise, je suis entre « Liberté » et « Fraternité ».',
    ],
    ex: 'L’égalité : tout le monde a les mêmes droits.',
  },
  {
    n: 'n',
    id: 'qui-adulte',
    q: 'Qui suis-je ?',
    ok: 'l’adulte de confiance',
    ko: ['l’inconnu', 'le copain', 'le voisin de table'],
    img: '🧑‍🏫',
    hints: [
      'Je suis une grande personne.',
      'Je peux être un parent, la maitresse, le maitre ou un animateur.',
      'Tu peux tout me raconter quand quelque chose ne va pas.',
      'Je suis là pour t’écouter et te protéger.',
    ],
    ex: 'Un adulte de confiance écoute et protège les enfants.',
  },
  {
    n: 'n',
    id: 'qui-stop',
    q: 'Quel mot suis-je ?',
    ok: '« Stop ! »',
    ko: ['« Merci ! »', '« Bravo ! »', '« Encore ! »'],
    img: '✋',
    hints: [
      'Je suis un mot très court.',
      'On me dit quand quelque chose ne nous plaît pas.',
      'On me dit fort, en regardant la personne.',
      'Je veux dire : « Arrête ! »',
    ],
    ex: 'Dire « Stop ! », c’est montrer qu’on n’est pas d’accord. Si ça continue, on va voir un adulte.',
  },
];

const RESP_VF: VF[] = [
  {
    n: 'f',
    id: 'stop',
    s: 'Si quelqu’un me dit « stop », j’arrête.',
    v: true,
    img: '✋',
    ex: 'Respecter le « stop » de l’autre, c’est le respecter.',
  },
  {
    n: 'f',
    id: 'foot',
    s: 'Le foot, c’est seulement pour les garçons.',
    v: false,
    img: '⚽',
    ex: 'Filles et garçons peuvent jouer au foot.',
  },
  {
    n: 'f',
    id: 'pompiere',
    s: 'Une fille peut devenir pompière.',
    v: true,
    ex: 'Tous les métiers sont ouverts aux filles et aux garçons.',
  },
  {
    n: 'f',
    id: 'parler-adulte',
    s: 'Si on m’embête, je peux en parler à un adulte de confiance.',
    v: true,
    ex: 'C’est même ce qu’il faut faire.',
  },
  {
    n: 'n',
    id: 'rapporter',
    s: 'Parler du harcèlement à un adulte, c’est rapporter.',
    v: false,
    sensible: true,
    ex: 'Ce n’est pas rapporter : c’est aider quelqu’un qui souffre.',
  },
  {
    n: 'n',
    id: 'tous-les-jours',
    s: 'Se moquer de quelqu’un tous les jours, c’est du harcèlement.',
    v: true,
    sensible: true,
    ex: 'Des moqueries répétées, exprès, c’est du harcèlement.',
  },
  {
    n: 'n',
    id: 'danse',
    s: 'Les garçons peuvent aimer la danse.',
    v: true,
    img: '🕺',
    ex: 'Les goûts n’ont pas de genre.',
  },
  {
    n: 'n',
    id: 'different',
    s: 'On peut mettre quelqu’un de côté parce qu’il est différent.',
    v: false,
    ex: 'Personne ne doit être mis à l’écart : nos différences sont une richesse.',
  },
  {
    n: 'n',
    id: 'pareils',
    s: 'Les filles et les garçons ont les mêmes droits.',
    v: true,
    ex: 'C’est l’égalité entre les filles et les garçons.',
  },
  {
    n: 'p',
    id: 'faute',
    s: 'Quand un enfant est harcelé, c’est de sa faute.',
    v: false,
    sensible: true,
    ex: 'Ce n’est jamais la faute de la victime : il faut l’aider et prévenir un adulte.',
  },
  // compléments du 08/10/2026 (Vrai ou faux au Plus loin)
  {
    n: 'p',
    id: 'avis',
    s: 'On peut ne pas être d’accord avec quelqu’un et le lui dire poliment.',
    v: true,
    ex: 'On a le droit d’avoir un autre avis : on le dit calmement, sans se moquer.',
  },
  {
    n: 'p',
    id: 'metiers',
    s: 'Certains métiers sont interdits aux filles.',
    v: false,
    ex: 'Filles et garçons peuvent choisir tous les métiers : pompière, infirmier, pilote…',
  },
  {
    n: 'p',
    id: 'langue',
    s: 'Un enfant qui parle une autre langue à la maison mérite le même respect que les autres.',
    v: true,
    ex: 'Chacun mérite le respect, quelle que soit sa langue ou son origine.',
  },
];

const RP = 'respectueux';
const NRP = 'pas respectueux';
const RESP_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'respect',
      prompt: 'Est-ce respectueux ?',
      categories: [RP, NRP],
      elements: [
        { label: 'prêter mon crayon', c: RP, n: 'f', img: '✏️' },
        { label: 'dire bonjour', c: RP, n: 'f', img: '👋' },
        { label: 'écouter quand quelqu’un parle', c: RP, n: 'f', img: '👂' },
        { label: 'aider un camarade tombé', c: RP, n: 'f', img: '🤝' },
        { label: 'inviter un élève seul à jouer', c: RP, n: 'f' },
        { label: 'se moquer d’un camarade', c: NRP, n: 'f' },
        { label: 'pousser dans le rang', c: NRP, n: 'f' },
        { label: 'prendre sans demander', c: NRP, n: 'f' },
        { label: 'couper la parole', c: NRP, n: 'f' },
      ],
      ex: 'Être respectueux, c’est faire attention aux autres comme on aimerait qu’on fasse attention à nous.',
    },
  ],
  normal: [
    {
      id: 'respect',
      prompt: 'Est-ce respectueux ?',
      categories: [RP, NRP],
      elements: [
        { label: 'prêter mon crayon', c: RP, n: 'n', img: '✏️' },
        { label: 'dire « merci »', c: RP, n: 'n' },
        { label: 'inviter un élève seul à jouer', c: RP, n: 'n' },
        { label: 'jouer au foot avec les filles et les garçons', c: RP, n: 'n', img: '⚽' },
        { label: 'dire stop quand on n’aime pas un jeu', c: RP, n: 'n', img: '✋' },
        { label: 'se moquer d’un camarade', c: NRP, n: 'n' },
        { label: 'refuser qu’un garçon joue à la corde à sauter', c: NRP, n: 'n' },
        { label: 'laisser quelqu’un de côté exprès', c: NRP, n: 'n' },
        { label: 'continuer quand on m’a dit stop', c: NRP, n: 'n' },
      ],
      ex: 'Le respect vaut pour tous : filles et garçons peuvent jouer à tous les jeux, et un « stop » se respecte.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'rire',
      prompt: 'Rire avec quelqu’un ou rire de quelqu’un ?',
      categories: [RP, NRP],
      elements: [
        { label: 'rire ensemble d’une blague', c: RP, n: 'p', img: '😂' },
        { label: 'rire avec un ami qui fait le clown', c: RP, n: 'p', img: '🤡' },
        { label: 'faire rire la classe avec un dessin drôle', c: RP, n: 'p' },
        { label: 'rire d’un camarade qui est tombé', c: NRP, n: 'p' },
        { label: 'rire de l’accent de quelqu’un', c: NRP, n: 'p' },
        { label: 'rire d’une erreur au tableau', c: NRP, n: 'p' },
        { label: 'se moquer d’un garçon qui aime la danse', c: NRP, n: 'p' },
      ],
      ex: 'Rire ensemble, c’est joyeux ; rire de quelqu’un peut le blesser.',
    },
  ],
};

const RESP_PAIRES: Record<Level, Appariement[]> = (() => {
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'mots-magiques',
    prompt: 'Associe chaque mot poli au bon moment.',
    relation: 'mot poli → situation',
    duos: [
      { l: '« Bonjour ! »', r: 'j’arrive le matin', n },
      { l: '« Merci ! »', r: 'on me rend un service', n },
      { l: '« S’il te plaît »', r: 'je demande quelque chose', n },
      { l: '« Pardon ! »', r: 'j’ai bousculé quelqu’un', n },
      { l: '« Au revoir ! »', r: 'je quitte quelqu’un', n },
    ],
    ex: 'Les mots polis montrent qu’on respecte les autres.',
    nb,
  });
  return { facile: [a('f', 3)], normal: [a('n', 5)], plus_loin: [a('p', 5)] };
})();

/* ------------------------------------------------------------------ */
/* Environnement : gestes éco-citoyens, tri des déchets                */
/* ------------------------------------------------------------------ */

const TRI = 'bac de tri (emballages, papiers)';
const VERRE = 'conteneur à verre';
const COMP = 'compost';
const OM = 'ordures ménagères';
const COLL = 'collecte spéciale (magasin, déchetterie)';

const DECHETS = [
  { label: 'la bouteille d’eau en plastique', c: TRI, img: '🧴' },
  { label: 'la boîte de conserve', c: TRI, img: '🥫' },
  { label: 'le carton de céréales', c: TRI, img: '📦' },
  { label: 'le journal', c: TRI, img: '📰' },
  { label: 'la brique de lait', c: TRI, img: '🧃' },
  { label: 'la bouteille en verre', c: VERRE, img: '🍾' },
  { label: 'le pot de confiture en verre', c: VERRE, img: '🫙' },
  { label: 'le bocal de cornichons', c: VERRE },
  { label: 'les épluchures de légumes', c: COMP, img: '🥕' },
  { label: 'le trognon de pomme', c: COMP, img: '🍎' },
  { label: 'les coquilles d’œufs', c: COMP, img: '🥚' },
  { label: 'la couche sale', c: OM },
  { label: 'la vieille brosse à dents', c: OM, img: '🪥' },
  { label: 'le pansement usagé', c: OM, img: '🩹' },
];

const ENV_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'tri-verre',
      prompt: 'Où jettes-tu ce déchet ?',
      categories: [TRI, VERRE],
      elements: DECHETS.filter((d) => d.c === TRI || d.c === VERRE).map((d) => ({ ...d, n: 'f' as const })),
      ex: 'Le verre va dans le conteneur à verre ; les emballages et les papiers dans le bac de tri (souvent jaune).',
    },
  ],
  normal: [
    {
      id: 'quatre-bacs',
      prompt: 'Où jettes-tu ce déchet ?',
      categories: [TRI, VERRE, COMP, OM],
      elements: DECHETS.map((d) => ({ ...d, n: 'n' as const })),
      ex: 'Emballages et papiers : bac de tri ; verre : conteneur à verre ; épluchures : compost ; le reste : ordures ménagères. Les couleurs des bacs changent selon les villes.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'cinq-filieres',
      prompt: 'Où va ce déchet ?',
      categories: [TRI, VERRE, COMP, OM, COLL],
      elements: [
        ...DECHETS.map((d) => ({ ...d, n: 'p' as const })),
        { label: 'l’assiette cassée', c: OM, n: 'p', img: '🍽️' },
        { label: 'les piles usagées', c: COLL, n: 'p', img: '🔋' },
        { label: 'le vieux téléphone portable', c: COLL, n: 'p', img: '📱' },
        { label: 'l’ampoule LED usagée', c: COLL, n: 'p', img: '💡' },
      ],
      ex: 'Attention : la vaisselle cassée ne va pas avec le verre. Les piles, ampoules et appareils électriques se rapportent en magasin ou à la déchetterie.',
      nb: 10,
    },
  ],
};

const ENV_QCM: Q[] = [
  {
    n: 'f',
    id: 'papier-bonbon',
    q: 'Que fais-tu de ton papier de bonbon à la récréation ?',
    ok: 'je le jette dans une poubelle',
    ko: ['je le jette par terre', 'je le cache dans un buisson'],
    img: '🗑️',
    ex: 'Un déchet jeté par terre salit et peut blesser les animaux : on le met à la poubelle.',
  },
  {
    n: 'f',
    id: 'robinet',
    q: 'Pour économiser l’eau en te brossant les dents, que fais-tu ?',
    ok: 'je ferme le robinet pendant que je brosse',
    ko: ['je laisse couler l’eau', 'je remplis la baignoire'],
    img: '🚰',
    ex: 'Fermer le robinet pendant le brossage économise beaucoup d’eau.',
  },
  {
    n: 'f',
    id: 'lumiere',
    q: 'Quand on quitte une pièce vide, que faut-il faire ?',
    ok: 'éteindre la lumière',
    ko: ['laisser la lumière allumée', 'allumer toutes les lampes'],
    img: '💡',
    ex: 'Éteindre la lumière économise l’électricité.',
  },
  {
    n: 'n',
    id: 'verre',
    q: 'Où jette-t-on une bouteille en verre vide ?',
    ok: 'dans le conteneur à verre',
    ko: ['dans le compost', 'dans la nature', 'dans la poubelle de la classe'],
    img: '🍾',
    ex: 'Le verre se recycle à l’infini : il va dans le conteneur à verre.',
  },
  {
    n: 'n',
    id: 'recyclee',
    q: 'Que devient une bouteille en plastique bien triée ?',
    ok: 'elle est recyclée pour fabriquer de nouveaux objets',
    ko: ['elle disparaît toute seule', 'elle est jetée à la mer', 'elle redevient du pétrole tout de suite'],
    img: '♻️',
    ex: 'Triée, la bouteille devient une nouvelle matière : un pull polaire, une autre bouteille…',
  },
  {
    n: 'n',
    id: 'compost',
    q: 'Que peut-on mettre dans le compost ?',
    ok: 'les épluchures de légumes',
    ko: ['les piles', 'les bouteilles en verre', 'les boîtes de conserve'],
    img: '🥕',
    ex: 'Les restes de fruits et de légumes deviennent de la bonne terre dans le compost.',
  },
  {
    n: 'n',
    id: 'velo',
    q: 'Pour aller à l’école tout près de chez toi, quel moyen pollue le moins ?',
    ok: 'à pied ou à vélo',
    ko: ['en voiture', 'en avion', 'en camion'],
    img: '🚲',
    ex: 'Marcher ou pédaler ne pollue pas, et c’est bon pour la santé !',
  },
  {
    n: 'n',
    id: 'gouter',
    q: 'Pour le goûter, quel choix fait le moins de déchets ?',
    ok: 'une gourde et une boîte réutilisable',
    ko: ['une bouteille et un emballage jetables', 'trois petits paquets emballés un par un'],
    ex: 'Ce qu’on réutilise ne devient pas un déchet.',
  },
  {
    n: 'p',
    id: 'recycler',
    q: 'Que veut dire « recycler » ?',
    ok: 'transformer un déchet pour fabriquer de nouveaux objets',
    ko: ['jeter un déchet dans la nature', 'brûler tous les déchets', 'cacher les déchets'],
    ex: 'Recycler, c’est donner une nouvelle vie à la matière d’un déchet.',
  },
  {
    n: 'p',
    id: 'piles',
    q: 'Où rapporte-t-on les piles usagées ?',
    ok: 'dans un bac de collecte, en magasin ou à la déchetterie',
    ko: ['dans le compost', 'dans le conteneur à verre', 'dans la nature'],
    img: '🔋',
    ex: 'Les piles contiennent des produits dangereux pour la nature : elles ont une collecte spéciale.',
  },
  {
    n: 'p',
    id: 'nature',
    q: 'Pourquoi ne faut-il pas jeter de déchets dans la nature ?',
    ok: 'ils polluent et peuvent blesser les animaux',
    ko: ['parce que c’est moche, c’est tout', 'parce que les animaux les mangent et grandissent mieux'],
    ex: 'Un sac plastique peut mettre des centaines d’années à disparaître et étouffer un animal.',
  },
  {
    n: 'n',
    id: 'qui-compost',
    q: 'Qui suis-je ?',
    ok: 'le compost',
    ko: ['la poubelle de la cuisine', 'le bac de tri', 'la déchetterie'],
    img: '🌱',
    hints: [
      'Je suis un tas ou une grande boîte au fond du jardin.',
      'On me donne des épluchures et des restes de fruits.',
      'Les vers de terre m’aiment beaucoup.',
      'Je deviens de la bonne terre pour les plantes.',
    ],
    ex: 'Le compost transforme les déchets de cuisine en terre fertile.',
  },
  {
    n: 'n',
    id: 'qui-conteneur',
    q: 'Qui suis-je ?',
    ok: 'le conteneur à verre',
    ko: ['le bac de tri', 'le compost', 'la boîte aux lettres'],
    img: '🍾',
    hints: [
      'Je suis un grand récipient dans la rue.',
      'On me donne des bouteilles et des pots.',
      'Quand on m’utilise, ça fait du bruit : cling !',
      'Je ne veux que du verre.',
    ],
    ex: 'Le conteneur à verre reçoit les bouteilles, les pots et les bocaux en verre.',
  },
  {
    n: 'n',
    id: 'qui-gourde',
    q: 'Qui suis-je ?',
    ok: 'la gourde',
    ko: ['la bouteille en plastique', 'la canette', 'le gobelet en carton'],
    img: '💧',
    hints: [
      'Je suis un objet que l’on remplit.',
      'On m’emporte à l’école ou en promenade.',
      'On me réutilise tous les jours.',
      'Grâce à moi, moins de bouteilles en plastique sont jetées.',
    ],
    ex: 'La gourde se réutilise : elle évite des déchets.',
  },
  {
    n: 'n',
    id: 'qui-dechetterie',
    q: 'Qui suis-je ?',
    ok: 'la déchetterie',
    ko: ['la boulangerie', 'la mairie', 'le parc'],
    img: '🚛',
    hints: [
      'Je suis un lieu de la ville.',
      'On y apporte les gros objets cassés.',
      'J’ai de nombreuses bennes pour trier.',
      'On y dépose aussi les piles, les vieux meubles et les déchets du jardin.',
    ],
    ex: 'À la déchetterie, chaque déchet a sa benne pour être recyclé ou traité.',
  },
];

const ENV_VF: VF[] = [
  {
    n: 'f',
    id: 'verre',
    s: 'Le verre se recycle.',
    v: true,
    img: '🍾',
    ex: 'Le verre se recycle même à l’infini.',
  },
  {
    n: 'f',
    id: 'par-terre',
    s: 'On peut jeter ses papiers par terre, quelqu’un les ramassera.',
    v: false,
    ex: 'Chacun jette ses déchets à la poubelle.',
  },
  {
    n: 'f',
    id: 'robinet',
    s: 'Fermer le robinet en se brossant les dents économise l’eau.',
    v: true,
    img: '🚰',
    ex: 'L’eau est précieuse : on ne la laisse pas couler pour rien.',
  },
  {
    n: 'f',
    id: 'lumiere',
    s: 'Éteindre la lumière en sortant d’une pièce économise l’électricité.',
    v: true,
    img: '💡',
    ex: 'C’est un geste simple pour la planète.',
  },
  {
    n: 'n',
    id: 'epluchures',
    s: 'Les épluchures de légumes vont dans le compost.',
    v: true,
    img: '🥕',
    ex: 'Elles deviennent de la bonne terre.',
  },
  {
    n: 'n',
    id: 'piles-compost',
    s: 'Les piles se jettent dans le compost.',
    v: false,
    img: '🔋',
    ex: 'Les piles se rapportent en magasin ou à la déchetterie.',
  },
  {
    n: 'n',
    id: 'gourde',
    s: 'Une gourde fait moins de déchets qu’une bouteille jetable.',
    v: true,
    ex: 'Elle se réutilise des centaines de fois.',
  },
  {
    n: 'n',
    id: 'velo',
    s: 'Aller à l’école à pied ou à vélo pollue moins qu’en voiture.',
    v: true,
    img: '🚲',
    ex: 'Marcher et pédaler ne rejettent pas de fumées.',
  },
  {
    n: 'p',
    id: 'assiette',
    s: 'Une assiette cassée va dans le conteneur à verre.',
    v: false,
    img: '🍽️',
    ex: 'La vaisselle n’est pas du verre d’emballage : elle va avec les ordures ménagères.',
  },
  {
    n: 'p',
    id: 'sac-plastique',
    s: 'Un sac en plastique jeté dans la nature disparaît en quelques jours.',
    v: false,
    ex: 'Il peut rester des centaines d’années dans la nature.',
  },
];

const ENV_PAIRES: Record<Level, Appariement[]> = (() => {
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'gestes',
    prompt: 'Associe chaque geste pour la planète à son image.',
    relation: 'geste → image',
    duos: [
      { l: 'éteindre la lumière', r: '💡', n },
      { l: 'fermer le robinet', r: '🚰', n },
      { l: 'trier ses déchets', r: '♻️', n },
      { l: 'venir à vélo', r: '🚲', n },
      { l: 'planter un arbre', r: '🌳', n },
      { l: 'ramasser les déchets', r: '🧤', n },
      { l: 'faire un compost', r: '🪱', n },
    ],
    ex: 'Ces gestes économisent l’eau et l’énergie et réduisent les déchets.',
    nb,
  });
  return { facile: [a('f', 4)], normal: [a('n', 6)], plus_loin: [a('p', 7)] };
})();

export const EMC: ContentModule = {
  'CE1.EMC.REGLES': {
    pools: { mcq: qcmPool(REGLES_QCM, { guillotine: false }), true_false: vfPool(REGLES_VF) },
    gens: { classification: triGen(REGLES_TRIS), pairing: paireGen(REGLES_PAIRES) },
  },
  'CE1.EMC.EMOTIONS': {
    pools: { mcq: qcmPool(EMO_QCM, { guillotine: false }), true_false: vfPool(EMO_VF) },
    gens: { classification: triGen(EMO_TRIS), pairing: paireGen(EMO_PAIRES) },
  },
  'CE1.EMC.SYMBOLES': {
    pools: { mcq: qcmPool(SYM_QCM, { guillotine: true }), true_false: vfPool(SYM_VF) },
    gens: { pairing: paireGen(SYM_PAIRES) },
  },
  'CE1.EMC.RESPECT': {
    pools: { mcq: qcmPool(RESP_QCM, { guillotine: false }), true_false: vfPool(RESP_VF) },
    gens: { classification: triGen(RESP_TRIS), pairing: paireGen(RESP_PAIRES) },
  },
  'CE1.EMC.ENVIRONNEMENT': {
    pools: { mcq: qcmPool(ENV_QCM, { guillotine: false }), true_false: vfPool(ENV_VF) },
    gens: { classification: triGen(ENV_TRIS), pairing: paireGen(ENV_PAIRES) },
  },
};
