/**
 * Questionner le monde CE1 — « La matière » et « Les objets » (programme 2020, en vigueur en 2026-2027) :
 * états de l'eau et changements d'état (0 °C et 100 °C en « Plus loin »), objets électriques, circuit
 * pile-ampoule (convention `meta.circuit` du Laboratoire), sécurité électrique, usages du numérique
 * et sécurité adaptés à 7 ans.
 */
import type { ContentModule } from '../../registry';
import type { Level } from '../../schemas';
import {
  type Appariement,
  type Ordre,
  type Q,
  type Tri,
  type VF,
  ordrePool,
  paireGen,
  qcmPool,
  triGen,
  vfPool,
} from './outils';

/** Degrés Celsius avec espace insécable : « 0 °C ». */
const deg = (n: number) => `${n} °C`;

/* ------------------------------------------------------------------ */
/* L'eau : états et changements d'état                                */
/* ------------------------------------------------------------------ */

const SO = 'solide';
const LI = 'liquide';
const GA = 'gaz';

const EAU_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'solide-liquide',
      prompt: 'Solide ou liquide ?',
      categories: [SO, LI],
      elements: [
        { label: 'le glaçon', c: SO, n: 'f', img: '🧊' },
        { label: 'le caillou', c: SO, n: 'f', img: '🪨' },
        { label: 'la cuillère', c: SO, n: 'f', img: '🥄' },
        { label: 'la neige', c: SO, n: 'f', img: '❄️' },
        { label: 'l’eau du robinet', c: LI, n: 'f', img: '🚰' },
        { label: 'le lait', c: LI, n: 'f', img: '🥛' },
        { label: 'le jus d’orange', c: LI, n: 'f', img: '🧃' },
        { label: 'l’huile', c: LI, n: 'f' },
      ],
      ex: 'Un solide garde sa forme ; un liquide coule et prend la forme du récipient.',
    },
  ],
  normal: [
    {
      id: 'trois-etats',
      prompt: 'Solide, liquide ou gaz ?',
      categories: [SO, LI, GA],
      elements: [
        { label: 'le glaçon', c: SO, n: 'n', img: '🧊' },
        { label: 'le caillou', c: SO, n: 'n', img: '🪨' },
        { label: 'la neige', c: SO, n: 'n', img: '❄️' },
        { label: 'le bois', c: SO, n: 'n', img: '🪵' },
        { label: 'l’eau de pluie', c: LI, n: 'n', img: '🌧️' },
        { label: 'le lait', c: LI, n: 'n', img: '🥛' },
        { label: 'le jus de pomme', c: LI, n: 'n', img: '🧃' },
        { label: 'l’huile', c: LI, n: 'n' },
        { label: 'la vapeur d’eau', c: GA, n: 'n', img: '♨️' },
        { label: 'l’air', c: GA, n: 'n', img: '🌬️' },
        { label: 'l’air du ballon de baudruche', c: GA, n: 'n', img: '🎈' },
      ],
      ex: 'Un solide garde sa forme, un liquide coule et prend la forme du récipient, un gaz occupe tout l’espace. La vapeur d’eau est invisible : la buée que l’on voit, ce sont déjà de petites gouttes d’eau.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'etats-eau',
      prompt: 'Sous quel état se trouve l’eau ?',
      categories: ['l’eau solide', 'l’eau liquide', 'l’eau gazeuse (vapeur)'],
      elements: [
        { label: 'la neige', c: 'l’eau solide', n: 'p', img: '❄️' },
        { label: 'la grêle', c: 'l’eau solide', n: 'p', img: '🌨️' },
        { label: 'le givre sur la vitre', c: 'l’eau solide', n: 'p' },
        { label: 'l’iceberg', c: 'l’eau solide', n: 'p', img: '🧊' },
        { label: 'la pluie', c: 'l’eau liquide', n: 'p', img: '🌧️' },
        { label: 'la rosée du matin', c: 'l’eau liquide', n: 'p' },
        { label: 'la mer', c: 'l’eau liquide', n: 'p', img: '🌊' },
        {
          label: 'l’eau qui s’échappe de la casserole qui bout',
          c: 'l’eau gazeuse (vapeur)',
          n: 'p',
          img: '♨️',
        },
        { label: 'l’eau de la flaque qui s’est évaporée', c: 'l’eau gazeuse (vapeur)', n: 'p' },
      ],
      ex: 'L’eau existe sous trois états : solide (glace, neige, grêle), liquide (pluie, mer) et gazeux (vapeur d’eau, invisible).',
      nb: 7,
    },
    {
      id: 'trois-etats',
      prompt: 'Solide, liquide ou gaz ?',
      categories: [SO, LI, GA],
      elements: [
        { label: 'le sable', c: SO, n: 'p', img: '🏜️' },
        { label: 'le sucre en poudre', c: SO, n: 'p' },
        { label: 'le beurre froid', c: SO, n: 'p', img: '🧈' },
        { label: 'le sirop', c: LI, n: 'p' },
        { label: 'l’eau de mer', c: LI, n: 'p', img: '🌊' },
        { label: 'le vinaigre', c: LI, n: 'p' },
        { label: 'la vapeur d’eau', c: GA, n: 'p', img: '♨️' },
        { label: 'l’air', c: GA, n: 'p', img: '🌬️' },
      ],
      ex: 'Attention : le sable et le sucre coulent, mais chaque grain est un petit solide qui garde sa forme.',
      nb: 7,
    },
  ],
};

const EAU_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'glacon-fond',
    prompt: 'Un glaçon est posé au soleil. Remets les étapes dans l’ordre.',
    el: ['le glaçon', 'le glaçon fond', 'une flaque d’eau'],
    mode: 'etapes',
    ex: 'Avec la chaleur, la glace fond et devient de l’eau liquide.',
  },
  {
    n: 'f',
    id: 'congelateur-3',
    prompt: 'On met de l’eau au congélateur. Remets les étapes dans l’ordre.',
    el: ['de l’eau liquide', 'l’eau refroidit au congélateur', 'des glaçons'],
    mode: 'etapes',
    ex: 'Dans le froid du congélateur, l’eau devient de la glace.',
  },
  {
    n: 'n',
    id: 'glacons',
    prompt: 'Fabriquer des glaçons : remets les étapes dans l’ordre.',
    el: [
      'je remplis le bac d’eau liquide',
      'je mets le bac au congélateur',
      'l’eau se solidifie',
      'j’obtiens des glaçons',
    ],
    mode: 'etapes',
    ex: 'Quand l’eau liquide devient solide, c’est la solidification.',
  },
  {
    n: 'n',
    id: 'glace-vapeur',
    prompt: 'On chauffe un glaçon dans une casserole : remets les étapes dans l’ordre.',
    el: ['de la glace (solide)', 'de l’eau (liquide)', 'de la vapeur d’eau (gaz)'],
    mode: 'etapes',
    ex: 'En chauffant, la glace fond et devient de l’eau liquide, puis l’eau bout et devient de la vapeur.',
  },
  {
    n: 'n',
    id: 'bonhomme',
    prompt: 'Le bonhomme de neige au soleil : remets les étapes dans l’ordre.',
    el: [
      'le bonhomme de neige tout neuf',
      'il commence à fondre',
      'il ne reste qu’une petite boule de neige',
      'il ne reste qu’une flaque d’eau',
    ],
    mode: 'etapes',
    ex: 'La neige est de l’eau solide : au soleil, elle fond et devient liquide.',
  },
  {
    n: 'p',
    id: 'temperatures',
    prompt: 'On chauffe de la glace très froide. Remets les étapes dans l’ordre.',
    el: [
      `de la glace à −5 °C`,
      `la glace fond à ${deg(0)}`,
      'l’eau liquide se réchauffe',
      `l’eau bout à ${deg(100)}`,
      'de la vapeur d’eau',
    ],
    mode: 'etapes',
    ex: `La glace fond à ${deg(0)} ; l’eau pure bout à ${deg(100)} et devient de la vapeur.`,
  },
  {
    n: 'p',
    id: 'cycle-eau',
    prompt: 'Pour aller plus loin : remets le cycle de l’eau dans l’ordre.',
    el: [
      'l’eau de la mer s’évapore avec la chaleur du soleil',
      'la vapeur refroidit en altitude et forme des nuages',
      'il pleut ou il neige',
      'l’eau des rivières retourne à la mer',
    ],
    mode: 'etapes',
    cycle: true,
    ex: 'L’eau change d’état sans cesse : elle s’évapore, forme des nuages, retombe en pluie et revient à la mer.',
  },
];

const EAU_QCM: Q[] = [
  {
    n: 'f',
    id: 'glacon-soleil',
    q: 'Que devient un glaçon posé au soleil ?',
    ok: 'de l’eau liquide',
    ko: ['un caillou', 'du sable', 'du sucre'],
    img: '🧊',
    ex: 'Avec la chaleur, la glace fond : elle devient de l’eau liquide.',
  },
  {
    n: 'f',
    id: 'congelateur',
    q: 'Que devient l’eau mise au congélateur ?',
    ok: 'de la glace',
    ko: ['de la vapeur', 'du lait', 'du jus'],
    ex: 'Dans le froid, l’eau liquide devient solide : de la glace.',
  },
  {
    n: 'f',
    id: 'neige-etat',
    q: 'La neige, c’est de l’eau…',
    ok: 'solide',
    ko: ['liquide', 'chaude'],
    img: '❄️',
    ex: 'La neige est faite de minuscules cristaux de glace : c’est de l’eau solide.',
  },
  {
    n: 'n',
    id: 'fusion',
    q: 'Comment appelle-t-on le passage de la glace à l’eau liquide ?',
    ok: 'la fusion',
    ko: ['la solidification', 'l’ébullition', 'la germination'],
    ex: 'Quand la glace fond, c’est la fusion.',
  },
  {
    n: 'n',
    id: 'solidification',
    q: 'Comment appelle-t-on le passage de l’eau liquide à la glace ?',
    ok: 'la solidification',
    ko: ['la fusion', 'l’évaporation', 'la digestion'],
    ex: 'Quand l’eau gèle et devient solide, c’est la solidification.',
  },
  {
    n: 'n',
    id: 'trois-etats',
    q: 'Quels sont les trois états de l’eau ?',
    ok: 'solide, liquide et gazeux',
    ko: ['chaud, froid et tiède', 'dur, mou et mouillé', 'grand, moyen et petit'],
    ex: 'L’eau peut être solide (glace), liquide ou gazeuse (vapeur).',
  },
  {
    n: 'n',
    id: 'liquide',
    q: 'Que fait un liquide quand on le verse dans un verre ?',
    ok: 'il coule et prend la forme du verre',
    ko: ['il garde sa forme', 'il disparaît', 'il devient solide'],
    ex: 'Un liquide coule et prend la forme du récipient qui le contient.',
  },
  {
    n: 'n',
    id: 'solide',
    q: 'Qu’est-ce qui caractérise un solide ?',
    ok: 'il garde sa forme',
    ko: ['il coule', 'il prend la forme du récipient', 'il est invisible'],
    ex: 'Un solide garde sa forme, on peut le saisir.',
  },
  {
    n: 'n',
    id: 'gel-hiver',
    q: 'En hiver, l’eau de la mare devient de la glace. Pourquoi ?',
    ok: 'parce qu’il fait très froid',
    ko: ['parce qu’il fait chaud', 'parce qu’il pleut', 'parce qu’il y a du vent'],
    ex: 'Quand il fait très froid, l’eau gèle : elle devient solide.',
  },
  {
    n: 'p',
    id: 'zero',
    q: 'À quelle température l’eau gèle-t-elle ?',
    ok: deg(0),
    ko: [deg(100), deg(10), deg(50)],
    ex: `L’eau pure gèle à ${deg(0)} et la glace fond à ${deg(0)}.`,
  },
  {
    n: 'p',
    id: 'cent',
    q: 'À quelle température l’eau pure bout-elle ?',
    ok: deg(100),
    ko: [deg(0), deg(37), deg(50)],
    ex: `L’eau pure bout à ${deg(100)} : elle se transforme en vapeur.`,
  },
  {
    n: 'p',
    id: 'linge',
    q: 'Le linge sèche sur le fil. Où est passée l’eau ?',
    ok: 'elle s’est évaporée dans l’air',
    ko: ['elle a disparu pour toujours', 'elle est rentrée dans le fil', 'elle est devenue de la glace'],
    ex: 'L’eau s’évapore : elle devient de la vapeur invisible dans l’air.',
  },
  {
    n: 'p',
    id: 'ebullition',
    q: 'Comment s’appelle le passage de l’eau liquide à la vapeur quand l’eau bout ?',
    ok: 'l’ébullition',
    ko: ['la fusion', 'la solidification', 'la germination'],
    ex: 'Quand l’eau bout, de grosses bulles de vapeur se forment : c’est l’ébullition.',
  },
  {
    n: 'n',
    id: 'qui-glace',
    q: 'Qui suis-je ?',
    ok: 'la glace',
    ko: ['le verre', 'le caillou', 'le sel'],
    img: '🧊',
    hints: [
      'Je suis de l’eau.',
      'Je suis dure et froide.',
      'Si on me chauffe, je fonds.',
      'On me fabrique au congélateur.',
    ],
    ex: 'La glace est de l’eau à l’état solide.',
  },
  {
    n: 'n',
    id: 'qui-vapeur',
    q: 'Qui suis-je ?',
    ok: 'la vapeur d’eau',
    ko: ['la glace', 'la neige', 'la pluie'],
    img: '♨️',
    hints: [
      'Je suis de l’eau.',
      'Je suis un gaz : on ne me voit pas.',
      'Je m’échappe de la casserole quand l’eau bout.',
      'Je suis l’eau à l’état gazeux.',
    ],
    ex: 'La vapeur d’eau est de l’eau à l’état gazeux, invisible.',
  },
  {
    n: 'n',
    id: 'qui-neige',
    q: 'Qui suis-je ?',
    ok: 'la neige',
    ko: ['la pluie', 'la vapeur d’eau', 'le brouillard'],
    img: '❄️',
    hints: [
      'Je tombe du ciel.',
      'Je suis de l’eau à l’état solide.',
      'Je suis blanche et je fonds quand il fait plus chaud.',
      'Avec moi, on fait des bonshommes.',
    ],
    ex: 'La neige est de l’eau solide qui tombe des nuages.',
  },
  {
    n: 'f',
    id: 'qui-pluie',
    q: 'Qui suis-je ?',
    ok: 'la pluie',
    ko: ['la neige', 'la grêle', 'le vent'],
    img: '🌧️',
    hints: [
      'Je tombe des nuages.',
      'Je suis de l’eau liquide.',
      'Je mouille tout sur mon passage.',
      'On se protège de moi avec un parapluie.',
    ],
    ex: 'La pluie est de l’eau liquide qui tombe des nuages.',
  },
];

const EAU_VF: VF[] = [
  {
    n: 'f',
    id: 'glace-solide',
    s: 'La glace est de l’eau à l’état solide.',
    v: true,
    img: '🧊',
    ex: 'La glace est de l’eau solide.',
  },
  {
    n: 'f',
    id: 'glacon-chaud',
    s: 'Un glaçon fond quand il fait chaud.',
    v: true,
    ex: 'La chaleur fait fondre la glace.',
  },
  {
    n: 'f',
    id: 'liquide-forme',
    s: 'L’eau liquide garde toujours la même forme.',
    v: false,
    ex: 'L’eau liquide prend la forme du récipient.',
  },
  {
    n: 'f',
    id: 'neige-liquide',
    s: 'La neige est un liquide.',
    v: false,
    img: '❄️',
    ex: 'La neige est de l’eau solide.',
  },
  {
    n: 'n',
    id: 'gele',
    s: 'Quand l’eau gèle, elle devient solide.',
    v: true,
    ex: 'C’est la solidification.',
  },
  {
    n: 'n',
    id: 'fusion',
    s: 'La fusion, c’est quand la glace devient de l’eau liquide.',
    v: true,
    ex: 'La glace fond : c’est la fusion.',
  },
  {
    n: 'n',
    id: 'solidification',
    s: 'La solidification, c’est quand la glace fond.',
    v: false,
    ex: 'Quand la glace fond, c’est la fusion ; la solidification, c’est quand l’eau gèle.',
  },
  {
    n: 'n',
    id: 'trois',
    s: 'L’eau peut être solide, liquide ou gazeuse.',
    v: true,
    ex: 'Glace, eau liquide, vapeur d’eau.',
  },
  {
    n: 'n',
    id: 'air-gaz',
    s: 'L’air est un gaz.',
    v: true,
    img: '🌬️',
    ex: 'L’air est un gaz : il occupe tout l’espace.',
  },
  {
    n: 'p',
    id: 'zero',
    s: `L’eau pure gèle à ${deg(0)}.`,
    v: true,
    ex: `En dessous de ${deg(0)}, l’eau devient de la glace.`,
  },
  { n: 'p', id: 'cinquante', s: `L’eau bout à ${deg(50)}.`, v: false, ex: `L’eau pure bout à ${deg(100)}.` },
  {
    n: 'p',
    id: 'vapeur',
    s: 'La vapeur d’eau est un gaz invisible.',
    v: true,
    ex: 'La buée qu’on voit au-dessus de la casserole, ce sont déjà de petites gouttes d’eau liquide.',
  },
];

const EAU_PAIRES: Record<Level, Appariement[]> = {
  facile: [
    {
      id: 'etats',
      prompt: 'Associe chaque exemple à son état.',
      relation: 'exemple → état',
      duos: [
        { l: 'le glaçon', r: 'solide', n: 'f' },
        { l: 'l’eau du robinet', r: 'liquide', n: 'f' },
        { l: 'la vapeur d’eau', r: 'gaz', n: 'f' },
      ],
      ex: 'Glaçon : solide ; eau du robinet : liquide ; vapeur : gaz.',
      nb: 3,
    },
  ],
  normal: [
    {
      id: 'etats',
      prompt: 'Associe chaque exemple à l’état de l’eau.',
      relation: 'exemple → état',
      duos: [
        { l: 'le glaçon', r: 'l’eau solide', n: 'n' },
        { l: 'la pluie', r: 'l’eau liquide', n: 'n' },
        { l: 'la vapeur d’eau', r: 'l’eau gazeuse', n: 'n' },
      ],
      ex: 'Le glaçon est de l’eau solide, la pluie de l’eau liquide, la vapeur de l’eau gazeuse.',
      nb: 3,
    },
    {
      id: 'changements',
      prompt: 'Associe chaque situation au nom du changement d’état.',
      relation: 'situation → changement d’état',
      duos: [
        { l: 'la glace fond', r: 'la fusion', n: 'n' },
        { l: 'l’eau gèle', r: 'la solidification', n: 'n' },
        { l: 'la glace', r: 'solide', n: 'n' },
      ],
      ex: 'Fusion : la glace (solide) devient liquide. Solidification : l’eau liquide devient solide.',
      nb: 3,
    },
  ],
  plus_loin: [
    {
      id: 'changements',
      prompt: 'Associe chaque situation au nom du changement d’état.',
      relation: 'situation → changement d’état',
      duos: [
        { l: 'la glace fond', r: 'la fusion', n: 'p' },
        { l: 'l’eau gèle', r: 'la solidification', n: 'p' },
        { l: 'l’eau bout', r: 'l’ébullition', n: 'p' },
        { l: 'la flaque sèche', r: 'l’évaporation', n: 'p' },
        { l: 'la buée sur la vitre', r: 'la condensation', n: 'p' },
      ],
      ex: 'Fusion, solidification, ébullition, évaporation, condensation : ce sont les changements d’état de l’eau.',
      nb: 5,
    },
  ],
};

/* ------------------------------------------------------------------ */
/* L'électricité                                                       */
/* ------------------------------------------------------------------ */

const DA = 'dangereux';
const SD = 'sans danger';
const ALLUME = 'l’ampoule s’allume (circuit fermé)';
const ETEINT = 'l’ampoule reste éteinte';
const COND = 'conducteur (l’ampoule s’allume)';
const ISOL = 'isolant (l’ampoule reste éteinte)';

const ELEC_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'dangers',
      prompt: 'Dangereux ou sans danger ?',
      categories: [DA, SD],
      elements: [
        { label: 'mettre un doigt dans une prise', c: DA, n: 'f', img: '🔌' },
        { label: 'toucher un appareil électrique avec les mains mouillées', c: DA, n: 'f', img: '💦' },
        { label: 'tirer sur le fil pour débrancher', c: DA, n: 'f' },
        { label: 'mettre une pile bouton dans la bouche', c: DA, n: 'f' },
        { label: 'grimper près d’un pylône électrique', c: DA, n: 'f', img: '⚡' },
        { label: 'allumer la lumière avec l’interrupteur', c: SD, n: 'f', img: '💡' },
        { label: 'utiliser une lampe de poche à piles', c: SD, n: 'f', img: '🔦' },
        { label: 'faire un circuit avec une pile plate en classe', c: SD, n: 'f', img: '🔋' },
        { label: 'demander à un adulte de brancher un appareil', c: SD, n: 'f', img: '🙋' },
      ],
      ex: 'L’électricité des prises et des lignes électriques est très dangereuse. Les piles plates permettent de faire des expériences sans danger.',
    },
  ],
  normal: [
    {
      id: 'circuit',
      prompt: 'L’ampoule s’allume-t-elle ?',
      categories: [ALLUME, ETEINT],
      elements: [
        { label: 'les deux fils relient l’ampoule aux deux bornes de la pile', c: ALLUME, n: 'n' },
        { label: 'la boucle est complète, sans coupure', c: ALLUME, n: 'n' },
        { label: 'l’interrupteur est fermé', c: ALLUME, n: 'n' },
        { label: 'un fil est débranché', c: ETEINT, n: 'n' },
        { label: 'un fil est coupé', c: ETEINT, n: 'n', img: '✂️' },
        { label: 'l’interrupteur est ouvert', c: ETEINT, n: 'n' },
        { label: 'les deux fils sont sur la même borne de la pile', c: ETEINT, n: 'n' },
      ],
      ex: 'L’ampoule ne s’allume que si le circuit est fermé : une boucle complète, sans coupure, de la pile à l’ampoule et retour.',
      meta: { circuit: true },
    },
    {
      id: 'electrique',
      prompt: 'Cet objet fonctionne-t-il avec l’électricité ?',
      categories: ['il fonctionne à l’électricité', 'il fonctionne sans électricité'],
      elements: [
        { label: 'la lampe de poche', c: 'il fonctionne à l’électricité', n: 'n', img: '🔦' },
        { label: 'la télévision', c: 'il fonctionne à l’électricité', n: 'n', img: '📺' },
        { label: 'l’ordinateur', c: 'il fonctionne à l’électricité', n: 'n', img: '💻' },
        { label: 'le réfrigérateur', c: 'il fonctionne à l’électricité', n: 'n' },
        { label: 'le grille-pain', c: 'il fonctionne à l’électricité', n: 'n' },
        { label: 'le vélo', c: 'il fonctionne sans électricité', n: 'n', img: '🚲' },
        { label: 'les ciseaux', c: 'il fonctionne sans électricité', n: 'n', img: '✂️' },
        { label: 'le livre', c: 'il fonctionne sans électricité', n: 'n', img: '📖' },
        { label: 'le crayon', c: 'il fonctionne sans électricité', n: 'n', img: '✏️' },
        { label: 'la bougie', c: 'il fonctionne sans électricité', n: 'n', img: '🕯️' },
      ],
      ex: 'Un objet électrique a besoin d’une pile ou d’une prise pour fonctionner.',
    },
  ],
  plus_loin: [
    {
      id: 'conducteurs',
      prompt: 'Place l’objet dans le circuit : l’ampoule s’allume-t-elle ?',
      categories: [COND, ISOL],
      elements: [
        { label: 'un trombone en métal', c: COND, n: 'p', img: '📎' },
        { label: 'une clé en métal', c: COND, n: 'p', img: '🔑' },
        { label: 'une pièce de monnaie', c: COND, n: 'p', img: '🪙' },
        { label: 'une fourchette en métal', c: COND, n: 'p', img: '🍴' },
        { label: 'du papier d’aluminium', c: COND, n: 'p' },
        { label: 'une gomme', c: ISOL, n: 'p' },
        { label: 'une règle en bois', c: ISOL, n: 'p', img: '📏' },
        { label: 'un bouchon en liège', c: ISOL, n: 'p' },
        { label: 'une chaussette en laine', c: ISOL, n: 'p', img: '🧦' },
        { label: 'une feuille de papier', c: ISOL, n: 'p', img: '📄' },
        { label: 'un verre', c: ISOL, n: 'p' },
      ],
      ex: 'Les métaux laissent passer le courant électrique (conducteurs) ; le bois, le plastique, le caoutchouc, le papier et le verre ne le laissent pas passer (isolants).',
      meta: { circuit: true },
    },
  ],
};

const ELEC_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'fil-abime',
    prompt: 'Tu vois un fil électrique abîmé. Remets les bons gestes dans l’ordre.',
    el: ['je vois le fil abîmé', 'je n’y touche pas', 'je préviens un adulte'],
    mode: 'etapes',
    ex: 'On ne touche jamais un fil abîmé : on prévient tout de suite un adulte.',
  },
  {
    n: 'f',
    id: 'lampe-poche',
    prompt: 'Remets dans l’ordre : mettre des piles dans la lampe de poche.',
    el: [
      'j’ouvre la lampe',
      'je mets les piles dans le bon sens',
      'je referme la lampe',
      'j’appuie sur le bouton : elle éclaire',
    ],
    mode: 'etapes',
    ex: 'Les piles doivent être mises dans le bon sens (+ et −) pour que la lampe fonctionne.',
  },
  {
    n: 'n',
    id: 'circuit',
    prompt: 'Remets dans l’ordre : comment allumer une ampoule avec une pile ?',
    el: [
      'je prends une pile, une ampoule et deux fils',
      'je relie un fil à une borne de la pile et à l’ampoule',
      'je relie l’autre fil à l’autre borne et à l’ampoule',
      'la boucle est fermée : l’ampoule s’allume',
    ],
    mode: 'etapes',
    ex: 'Il faut une boucle complète : pile → fil → ampoule → fil → pile.',
  },
  {
    n: 'p',
    id: 'interrupteur',
    prompt: 'Remets dans l’ordre ce qui se passe quand on ouvre l’interrupteur.',
    el: [
      'le circuit est fermé, l’ampoule brille',
      'j’ouvre l’interrupteur',
      'le circuit est coupé',
      'l’ampoule s’éteint',
    ],
    mode: 'etapes',
    ex: 'L’interrupteur ouvert coupe la boucle : le courant ne passe plus.',
  },
];

const ELEC_QCM: Q[] = [
  {
    n: 'f',
    id: 'fil-abime',
    q: 'Que faire si tu vois un fil électrique abîmé ?',
    ok: 'ne pas y toucher et prévenir un adulte',
    ko: ['le toucher pour voir', 'le réparer avec du ruban adhésif', 'jouer avec'],
    img: '⚠️',
    ex: 'Un fil abîmé peut donner une décharge électrique : on n’y touche pas et on prévient un adulte.',
  },
  {
    n: 'f',
    id: 'prise',
    q: 'Peut-on mettre les doigts ou un objet dans une prise électrique ?',
    ok: 'non, jamais : c’est très dangereux',
    ko: ['oui, si on fait vite', 'oui, avec un crayon'],
    img: '🔌',
    ex: 'L’électricité des prises peut gravement blesser : on n’y met jamais rien.',
  },
  {
    n: 'f',
    id: 'objet-elec',
    q: 'Lequel de ces objets fonctionne avec l’électricité ?',
    ok: 'la lampe de poche',
    ko: ['le livre', 'le vélo', 'la cuillère'],
    img: '🔦',
    ex: 'La lampe de poche fonctionne avec des piles.',
  },
  {
    n: 'n',
    id: 'ferme',
    q: 'Pour que l’ampoule s’allume, comment doit être le circuit ?',
    ok: 'fermé, sans coupure',
    ko: ['ouvert', 'coupé en deux', 'sans pile'],
    img: '💡',
    ex: 'Le courant ne passe que dans une boucle complète : un circuit fermé.',
  },
  {
    n: 'n',
    id: 'interrupteur',
    q: 'À quoi sert un interrupteur ?',
    ok: 'à ouvrir ou fermer le circuit',
    ko: ['à rendre la pile plus grosse', 'à changer la couleur de l’ampoule', 'à refroidir les fils'],
    ex: 'L’interrupteur ouvre ou ferme la boucle : il éteint ou allume.',
  },
  {
    n: 'n',
    id: 'pile',
    q: 'Avec quoi peut-on faire des expériences d’électricité sans danger en classe ?',
    ok: 'avec une pile plate',
    ko: ['avec une prise de courant', 'avec le fil d’un appareil branché', 'avec un pylône électrique'],
    img: '🔋',
    ex: 'Une pile plate donne un courant faible, sans danger ; la prise, elle, est dangereuse.',
  },
  {
    n: 'n',
    id: 'bain',
    q: 'Pourquoi ne faut-il jamais utiliser un sèche-cheveux près de la baignoire ?',
    ok: 'parce que l’eau et l’électricité ensemble, c’est très dangereux',
    ko: [
      'parce que ça mouille les cheveux',
      'parce que l’eau devient froide',
      'parce que c’est trop bruyant',
    ],
    ex: 'L’eau laisse passer l’électricité : on n’approche jamais un appareil électrique de l’eau.',
  },
  {
    n: 'n',
    id: 'bornes',
    q: 'Combien de bornes a une pile ?',
    ok: 'deux : le + et le −',
    ko: ['une seule', 'trois', 'aucune'],
    ex: 'Une pile a deux bornes : il faut relier les deux pour fermer le circuit.',
  },
  {
    n: 'p',
    id: 'conducteur',
    q: 'Lequel de ces objets laisse passer le courant électrique ?',
    ok: 'une clé en métal',
    ko: ['une gomme', 'un bouchon en liège', 'une règle en bois'],
    img: '🔑',
    ex: 'Les métaux sont conducteurs : ils laissent passer le courant.',
  },
  {
    n: 'p',
    id: 'isolant',
    q: 'Comment appelle-t-on une matière qui ne laisse pas passer le courant ?',
    ok: 'un isolant',
    ko: ['un conducteur', 'une pile', 'une ampoule'],
    ex: 'Le plastique, le bois ou le caoutchouc sont des isolants.',
  },
  {
    n: 'p',
    id: 'gaine',
    q: 'Pourquoi les fils électriques sont-ils entourés de plastique ?',
    ok: 'parce que le plastique est isolant et nous protège',
    ko: ['pour faire joli', 'pour que le courant aille plus vite', 'pour que le fil soit plus lourd'],
    ex: 'Le plastique isolant empêche le courant de passer dans nos doigts.',
  },
  {
    n: 'n',
    id: 'qui-pile',
    q: 'Qui suis-je ?',
    ok: 'la pile',
    ko: ['l’ampoule', 'l’interrupteur', 'la prise'],
    img: '🔋',
    hints: [
      'Je suis petite.',
      'J’ai deux bornes : le + et le −.',
      'Je donne de l’électricité sans danger aux petits objets.',
      'Quand je suis usée, on me rapporte au magasin pour qu’on me recycle.',
    ],
    ex: 'La pile fournit l’électricité aux petits objets ; usée, on la rapporte dans un bac de collecte.',
  },
  {
    n: 'n',
    id: 'qui-ampoule',
    q: 'Qui suis-je ?',
    ok: 'l’ampoule',
    ko: ['la pile', 'le fil', 'l’interrupteur'],
    img: '💡',
    hints: [
      'J’ai souvent une enveloppe en verre.',
      'J’ai besoin d’électricité.',
      'Quand le circuit est fermé, je brille.',
      'Je donne de la lumière.',
    ],
    ex: 'L’ampoule s’allume quand le courant passe dans le circuit fermé.',
  },
  {
    n: 'n',
    id: 'qui-interrupteur',
    q: 'Qui suis-je ?',
    ok: 'l’interrupteur',
    ko: ['la pile', 'l’ampoule', 'le fil'],
    img: '🔘',
    hints: [
      'Je suis sur le mur ou sur un fil.',
      'Je peux ouvrir ou fermer le circuit.',
      'On appuie sur moi pour allumer ou éteindre.',
      'Sans moi, il faudrait débrancher la lampe !',
    ],
    ex: 'L’interrupteur ouvre ou ferme le circuit.',
  },
  {
    n: 'f',
    id: 'qui-prise',
    q: 'Qui suis-je ?',
    ok: 'la prise électrique',
    ko: ['la pile', 'l’ampoule', 'la lampe de poche'],
    img: '🔌',
    hints: [
      'Je suis dans le mur.',
      'On branche les appareils sur moi.',
      'Mon électricité est très dangereuse.',
      'On ne met jamais les doigts dans mes trous !',
    ],
    ex: 'La prise électrique est dangereuse : seuls les adultes branchent les appareils.',
  },
];

const ELEC_VF: VF[] = [
  {
    n: 'f',
    id: 'prise',
    s: 'On peut mettre ses doigts dans une prise si on fait attention.',
    v: false,
    img: '🔌',
    ex: 'Jamais : l’électricité des prises est très dangereuse.',
  },
  {
    n: 'f',
    id: 'pile',
    s: 'Une pile plate permet de faire des expériences sans danger.',
    v: true,
    img: '🔋',
    ex: 'Son courant est faible.',
  },
  {
    n: 'f',
    id: 'eau',
    s: 'L’eau et l’électricité ensemble, c’est dangereux.',
    v: true,
    img: '💦',
    ex: 'L’eau laisse passer le courant : on n’approche pas d’appareil électrique de l’eau.',
  },
  {
    n: 'f',
    id: 'lampe',
    s: 'La lampe de poche fonctionne avec des piles.',
    v: true,
    img: '🔦',
    ex: 'Les piles fournissent l’électricité.',
  },
  {
    n: 'n',
    id: 'ouvert',
    s: 'Si le circuit est ouvert, l’ampoule s’allume.',
    v: false,
    img: '💡',
    ex: 'Il faut un circuit fermé pour que l’ampoule s’allume.',
  },
  {
    n: 'n',
    id: 'interrupteur',
    s: 'Un interrupteur permet d’allumer ou d’éteindre.',
    v: true,
    ex: 'Il ferme ou ouvre le circuit.',
  },
  {
    n: 'n',
    id: 'une-borne',
    s: 'Pour allumer l’ampoule, il suffit de relier un seul fil à la pile.',
    v: false,
    ex: 'Il faut relier les deux bornes de la pile : une boucle complète.',
  },
  {
    n: 'n',
    id: 'fil-abime',
    s: 'Si je vois un fil électrique abîmé, je préviens un adulte.',
    v: true,
    ex: 'On n’y touche pas et on prévient un adulte.',
  },
  {
    n: 'p',
    id: 'metal',
    s: 'Le métal laisse passer le courant électrique.',
    v: true,
    ex: 'Les métaux sont conducteurs.',
  },
  {
    n: 'p',
    id: 'plastique',
    s: 'Le plastique est conducteur.',
    v: false,
    ex: 'Le plastique est isolant : c’est pour cela qu’il entoure les fils.',
  },
  {
    n: 'p',
    id: 'bois',
    s: 'Si on place une règle en bois dans le circuit, l’ampoule s’allume.',
    v: false,
    ex: 'Le bois sec est isolant : le courant ne passe pas.',
  },
];

/* ------------------------------------------------------------------ */
/* Le numérique                                                        */
/* ------------------------------------------------------------------ */

const NUM = 'un objet numérique';
const PNUM = 'pas un objet numérique';
const ADULTE = 'je demande d’abord à un adulte';
const SEUL = 'je peux le faire';

const NUM_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'numerique',
      prompt: 'Est-ce un objet numérique ?',
      categories: [NUM, PNUM],
      elements: [
        { label: 'la tablette', c: NUM, n: 'f', img: '📱' },
        { label: 'l’ordinateur', c: NUM, n: 'f', img: '💻' },
        { label: 'la console de jeux', c: NUM, n: 'f', img: '🎮' },
        { label: 'l’appareil photo numérique', c: NUM, n: 'f', img: '📷' },
        { label: 'le livre en papier', c: PNUM, n: 'f', img: '📖' },
        { label: 'le crayon', c: PNUM, n: 'f', img: '✏️' },
        { label: 'le ballon', c: PNUM, n: 'f', img: '⚽' },
        { label: 'le puzzle en carton', c: PNUM, n: 'f', img: '🧩' },
      ],
      ex: 'Un objet numérique a un écran ou une puce électronique et fonctionne avec l’électricité.',
    },
  ],
  normal: [
    {
      id: 'numerique',
      prompt: 'Est-ce un objet numérique ?',
      categories: [NUM, PNUM],
      elements: [
        { label: 'la tablette', c: NUM, n: 'n', img: '📱' },
        { label: 'l’ordinateur', c: NUM, n: 'n', img: '💻' },
        { label: 'la console de jeux', c: NUM, n: 'n', img: '🎮' },
        { label: 'la montre connectée', c: NUM, n: 'n', img: '⌚' },
        { label: 'le robot programmable', c: NUM, n: 'n', img: '🤖' },
        { label: 'le livre en papier', c: PNUM, n: 'n', img: '📖' },
        { label: 'l’ardoise et la craie', c: PNUM, n: 'n' },
        { label: 'le vélo', c: PNUM, n: 'n', img: '🚲' },
        { label: 'le jeu de cartes', c: PNUM, n: 'n', img: '🃏' },
      ],
      ex: 'Tablette, ordinateur, console, montre connectée : ce sont des objets numériques.',
    },
    {
      id: 'securite',
      prompt: 'Devant un écran : je peux le faire, ou je demande d’abord à un adulte ?',
      categories: [ADULTE, SEUL],
      elements: [
        { label: 'télécharger une application', c: ADULTE, n: 'n', img: '📲' },
        { label: 'cliquer sur « Tu as gagné un cadeau ! »', c: ADULTE, n: 'n', img: '🎁' },
        { label: 'donner mon nom et mon adresse sur internet', c: ADULTE, n: 'n', img: '🏠' },
        { label: 'acheter quelque chose dans un jeu', c: ADULTE, n: 'n', img: '💰' },
        { label: 'envoyer une photo de moi', c: ADULTE, n: 'n', img: '📸' },
        { label: 'éteindre l’écran à l’heure prévue', c: SEUL, n: 'n', img: '⏰' },
        { label: 'jouer à un jeu que mes parents ont choisi', c: SEUL, n: 'n', img: '🎮' },
        { label: 'faire une pause loin des écrans', c: SEUL, n: 'n', img: '🌳' },
      ],
      ex: 'Sur internet, on ne donne rien de personnel et on ne clique pas sur les publicités : on demande toujours à un adulte.',
    },
  ],
  plus_loin: [
    {
      id: 'securite',
      prompt: 'Devant un écran : je peux le faire, ou je demande d’abord à un adulte ?',
      categories: [ADULTE, SEUL],
      elements: [
        { label: 'télécharger une application', c: ADULTE, n: 'p', img: '📲' },
        { label: 'cliquer sur « Tu as gagné un cadeau ! »', c: ADULTE, n: 'p', img: '🎁' },
        { label: 'donner mon nom et mon adresse sur internet', c: ADULTE, n: 'p', img: '🏠' },
        { label: 'acheter quelque chose dans un jeu', c: ADULTE, n: 'p', img: '💰' },
        { label: 'publier la photo d’un copain', c: ADULTE, n: 'p', img: '📸' },
        { label: 'répondre à un message d’un inconnu', c: ADULTE, n: 'p', img: '✉️' },
        { label: 'éteindre l’écran à l’heure prévue', c: SEUL, n: 'p', img: '⏰' },
        { label: 'fermer une page qui me fait peur', c: SEUL, n: 'p', img: '❌' },
        { label: 'faire une pause loin des écrans', c: SEUL, n: 'p', img: '🌳' },
      ],
      ex: 'On ne partage rien de personnel et on ne répond pas aux inconnus. Si une page fait peur, on la ferme et on en parle à un adulte.',
      nb: 7,
    },
  ],
};

const NUM_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'peur',
    prompt: 'Une image te fait peur sur l’écran. Remets les bons gestes dans l’ordre.',
    el: [
      'je ferme la page ou j’éteins l’écran',
      'je vais voir un adulte de confiance',
      'je lui raconte ce que j’ai vu',
    ],
    mode: 'etapes',
    ex: 'On ferme, on va voir un adulte et on en parle : on n’est jamais seul face à ce qui fait peur.',
  },
  {
    n: 'n',
    id: 'ordinateur',
    prompt: 'Remets dans l’ordre : utiliser l’ordinateur de la classe.',
    el: [
      'j’allume l’ordinateur',
      'j’ouvre le logiciel demandé',
      'je fais mon travail',
      'j’enregistre mon travail',
      'j’éteins l’ordinateur',
    ],
    mode: 'etapes',
    ex: 'On n’oublie pas d’enregistrer son travail avant d’éteindre.',
  },
  {
    n: 'n',
    id: 'inconnu',
    prompt: 'Un inconnu t’écrit dans un jeu en ligne. Remets les bons gestes dans l’ordre.',
    el: ['je ne réponds pas', 'je quitte le jeu', 'j’en parle à un adulte'],
    mode: 'etapes',
    ex: 'On ne répond jamais à un inconnu et on prévient un adulte.',
  },
  {
    n: 'p',
    id: 'photo',
    prompt: 'Tu veux envoyer la photo d’un copain. Remets les étapes dans l’ordre.',
    el: [
      'je demande à mon copain et à un adulte s’ils sont d’accord',
      'l’adulte m’aide à choisir à qui l’envoyer',
      'j’envoie la photo avec l’adulte',
    ],
    mode: 'etapes',
    ex: 'On ne montre jamais la photo de quelqu’un sans son accord.',
  },
];

const NUM_QCM: Q[] = [
  {
    n: 'f',
    id: 'numerique',
    q: 'Lequel de ces objets est numérique ?',
    ok: 'la tablette',
    ko: ['le livre en papier', 'le crayon', 'le ballon'],
    img: '📱',
    ex: 'La tablette a un écran et fonctionne avec l’électricité : c’est un objet numérique.',
  },
  {
    n: 'f',
    id: 'clavier',
    q: 'À quoi sert le clavier de l’ordinateur ?',
    ok: 'à écrire des lettres et des mots',
    ko: ['à prendre des photos', 'à écouter de la musique', 'à imprimer'],
    img: '⌨️',
    ex: 'Chaque touche du clavier écrit une lettre, un chiffre ou un signe.',
  },
  {
    n: 'f',
    id: 'souris',
    q: 'À quoi sert la souris de l’ordinateur ?',
    ok: 'à déplacer la flèche et à cliquer',
    ko: ['à écrire', 'à faire du bruit', 'à éclairer'],
    img: '🖱️',
    ex: 'En bougeant la souris, on déplace la flèche sur l’écran.',
  },
  {
    n: 'n',
    id: 'gagne',
    q: 'Une fenêtre s’ouvre : « Bravo, tu as gagné une console ! Clique ici ! ». Que fais-tu ?',
    ok: 'je ne clique pas et je préviens un adulte',
    ko: ['je clique vite', 'je donne mon adresse', 'je donne le mot de passe de mes parents'],
    img: '🎁',
    ex: 'Ce sont souvent des pièges : on ne clique pas et on en parle à un adulte.',
  },
  {
    n: 'n',
    id: 'inconnu',
    q: 'Un inconnu t’écrit dans un jeu en ligne et te demande ton adresse. Que fais-tu ?',
    ok: 'je ne réponds pas et j’en parle à un adulte',
    ko: ['je lui donne mon adresse', 'je lui envoie une photo', 'je garde le secret'],
    ex: 'On ne donne jamais d’informations personnelles à un inconnu.',
  },
  {
    n: 'n',
    id: 'mot-de-passe',
    q: 'Qu’est-ce qu’un mot de passe ?',
    ok: 'un code secret qu’on ne donne qu’à ses parents',
    ko: ['un mot qu’on dit à tout le monde', 'le nom du jeu', 'une chanson'],
    img: '🔑',
    ex: 'Le mot de passe protège tes comptes : il reste secret.',
  },
  {
    n: 'n',
    id: 'temps',
    q: 'Pourquoi ne faut-il pas passer trop de temps devant les écrans ?',
    ok: 'pour bien dormir, bouger et jouer avec les autres',
    ko: [
      'parce que l’écran va exploser',
      'parce que c’est interdit de regarder un écran',
      'pour que la tablette se repose',
    ],
    ex: 'Le temps d’écran se partage avec le sommeil, le jeu dehors et les copains.',
  },
  {
    n: 'n',
    id: 'imprimante',
    q: 'À quoi sert une imprimante ?',
    ok: 'à mettre sur papier ce qui est à l’écran',
    ko: ['à écrire des lettres', 'à prendre des photos', 'à écouter le son'],
    img: '🖨️',
    ex: 'L’imprimante imprime sur une feuille ce qu’on voit à l’écran.',
  },
  {
    n: 'p',
    id: 'video-peur',
    q: 'Une vidéo te montre quelque chose qui te fait peur. Que fais-tu ?',
    ok: 'j’arrête la vidéo et j’en parle à un adulte',
    ko: ['je continue pour voir la fin', 'je la montre à mes copains', 'je n’en parle à personne'],
    ex: 'On arrête et on en parle à un adulte de confiance : il est là pour t’aider.',
  },
  {
    n: 'p',
    id: 'croire',
    q: 'Peut-on croire tout ce qu’on lit ou voit sur internet ?',
    ok: 'non, il faut vérifier avec un adulte',
    ko: ['oui, tout est vrai', 'oui, si c’est écrit en gros'],
    ex: 'Sur internet, n’importe qui peut écrire : certaines informations sont fausses.',
  },
  {
    n: 'p',
    id: 'photo-copain',
    q: 'Avant d’envoyer la photo d’un copain, que faut-il faire ?',
    ok: 'lui demander s’il est d’accord, et demander à un adulte',
    ko: ['l’envoyer sans rien dire', 'la modifier pour qu’elle soit drôle', 'l’envoyer à tout le monde'],
    ex: 'Chacun a le droit de décider si sa photo est montrée.',
  },
  {
    n: 'n',
    id: 'qui-souris',
    q: 'Qui suis-je ?',
    ok: 'la souris de l’ordinateur',
    ko: ['le clavier', 'l’écran', 'l’imprimante'],
    img: '🖱️',
    hints: [
      'Je ne suis pas un animal, mais j’en porte le nom.',
      'J’ai un fil, ou je fonctionne sans fil.',
      'On me fait glisser sur la table.',
      'Je fais bouger la flèche sur l’écran de l’ordinateur.',
    ],
    ex: 'La souris déplace la flèche et permet de cliquer.',
  },
  {
    n: 'n',
    id: 'qui-clavier',
    q: 'Qui suis-je ?',
    ok: 'le clavier',
    ko: ['la souris de l’ordinateur', 'l’écran', 'le casque'],
    img: '⌨️',
    hints: [
      'J’ai beaucoup de touches.',
      'Sur chaque touche, il y a une lettre, un chiffre ou un signe.',
      'Je suis relié à l’ordinateur.',
      'Je sers à écrire.',
    ],
    ex: 'Le clavier sert à écrire sur l’ordinateur.',
  },
  {
    n: 'n',
    id: 'qui-mot-de-passe',
    q: 'Qui suis-je ?',
    ok: 'le mot de passe',
    ko: ['le prénom', 'l’adresse', 'le jeu vidéo'],
    img: '🔑',
    hints: [
      'Je suis un secret.',
      'Je suis fait de lettres et de chiffres.',
      'Je protège tes jeux et tes messages.',
      'On ne me partage qu’avec ses parents.',
    ],
    ex: 'Le mot de passe est un code secret qui protège tes comptes.',
  },
  {
    n: 'n',
    id: 'qui-imprimante',
    q: 'Qui suis-je ?',
    ok: 'l’imprimante',
    ko: ['l’écran', 'le clavier', 'la tablette'],
    img: '🖨️',
    hints: [
      'Je suis reliée à l’ordinateur.',
      'On me donne des feuilles blanches.',
      'J’ai besoin d’encre.',
      'Je mets sur papier ce qu’il y a à l’écran.',
    ],
    ex: 'L’imprimante imprime les documents sur papier.',
  },
];

const NUM_VF: VF[] = [
  {
    n: 'f',
    id: 'tablette',
    s: 'Une tablette est un objet numérique.',
    v: true,
    img: '📱',
    ex: 'Elle a un écran et fonctionne avec l’électricité.',
  },
  {
    n: 'f',
    id: 'livre',
    s: 'Un livre en papier est un objet numérique.',
    v: false,
    img: '📖',
    ex: 'Le livre en papier n’a ni écran ni électricité.',
  },
  {
    n: 'f',
    id: 'peur',
    s: 'Si quelque chose me fait peur sur un écran, j’en parle à un adulte.',
    v: true,
    ex: 'Un adulte de confiance est là pour t’aider.',
  },
  {
    n: 'f',
    id: 'clavier',
    s: 'Le clavier sert à écrire.',
    v: true,
    img: '⌨️',
    ex: 'Chaque touche écrit une lettre, un chiffre ou un signe.',
  },
  {
    n: 'n',
    id: 'mdp',
    s: 'On peut donner son mot de passe à un inconnu.',
    v: false,
    img: '🔑',
    ex: 'Le mot de passe est secret : on ne le donne qu’à ses parents.',
  },
  {
    n: 'n',
    id: 'internet-vrai',
    s: 'Tout ce qui est écrit sur internet est vrai.',
    v: false,
    ex: 'Certaines informations sont fausses : on vérifie avec un adulte.',
  },
  {
    n: 'n',
    id: 'pauses',
    s: 'Faire des pauses loin des écrans est bon pour la santé.',
    v: true,
    ex: 'Bouger, jouer et dormir sont importants.',
  },
  {
    n: 'n',
    id: 'adresse',
    s: 'On peut répondre à un inconnu qui demande notre adresse.',
    v: false,
    ex: 'On ne répond pas et on en parle à un adulte.',
  },
  {
    n: 'n',
    id: 'cadeau',
    s: 'Quand un message dit « Tu as gagné ! », il faut vite cliquer.',
    v: false,
    img: '🎁',
    ex: 'C’est souvent un piège : on ne clique pas et on prévient un adulte.',
  },
  {
    n: 'p',
    id: 'photo',
    s: 'Avant de montrer la photo d’un copain, je lui demande s’il est d’accord.',
    v: true,
    ex: 'Chacun décide si sa photo peut être montrée.',
  },
  {
    n: 'p',
    id: 'ecran-coucher',
    s: 'Regarder un écran juste avant de dormir aide à bien s’endormir.',
    v: false,
    ex: 'La lumière des écrans retarde l’endormissement : on les éteint avant le coucher.',
  },
];

const NUM_PAIRES: Record<Level, Appariement[]> = {
  facile: [
    {
      id: 'objets',
      prompt: 'Associe chaque objet à son image.',
      relation: 'objet → image',
      duos: [
        { l: 'l’ordinateur', r: '💻', n: 'f' },
        { l: 'la souris', r: '🖱️', n: 'f' },
        { l: 'le clavier', r: '⌨️', n: 'f' },
        { l: 'l’imprimante', r: '🖨️', n: 'f' },
        { l: 'l’appareil photo', r: '📷', n: 'f' },
        { l: 'le casque', r: '🎧', n: 'f' },
      ],
      ex: 'Ce sont des objets numériques ou des accessoires de l’ordinateur.',
      nb: 4,
    },
  ],
  normal: [
    {
      id: 'usages',
      prompt: 'Associe chaque objet à ce qu’il permet de faire.',
      relation: 'objet → usage',
      duos: [
        { l: 'le clavier', r: 'écrire', n: 'n' },
        { l: 'la souris', r: 'cliquer', n: 'n' },
        { l: 'l’imprimante', r: 'imprimer une feuille', n: 'n' },
        { l: 'l’écran', r: 'afficher les images', n: 'n' },
        { l: 'l’appareil photo', r: 'prendre des photos', n: 'n' },
        { l: 'le casque', r: 'écouter le son', n: 'n' },
        { l: 'le micro', r: 'enregistrer sa voix', n: 'n' },
      ],
      ex: 'Chaque objet numérique a son usage : le clavier pour écrire, la souris pour cliquer…',
    },
  ],
  plus_loin: [
    {
      id: 'usages',
      prompt: 'Associe chaque objet à ce qu’il permet de faire.',
      relation: 'objet → usage',
      duos: [
        { l: 'le clavier', r: 'écrire', n: 'p' },
        { l: 'la souris', r: 'cliquer', n: 'p' },
        { l: 'l’imprimante', r: 'imprimer une feuille', n: 'p' },
        { l: 'l’écran', r: 'afficher les images', n: 'p' },
        { l: 'l’appareil photo', r: 'prendre des photos', n: 'p' },
        { l: 'le casque', r: 'écouter le son', n: 'p' },
        { l: 'le micro', r: 'enregistrer sa voix', n: 'p' },
        { l: 'le mot de passe', r: 'protéger un compte', n: 'p' },
      ],
      ex: 'Chaque objet numérique a son usage ; le mot de passe, lui, protège tes comptes.',
      nb: 7,
    },
  ],
};

export const MATIERE: ContentModule = {
  'CE1.QLM.MATIERE.EAU': {
    pools: {
      mcq: qcmPool(EAU_QCM, { guillotine: true }),
      true_false: vfPool(EAU_VF),
      ordering: ordrePool(EAU_ORDRES),
    },
    gens: { classification: triGen(EAU_TRIS), pairing: paireGen(EAU_PAIRES) },
  },
  'CE1.QLM.OBJETS.ELEC': {
    pools: {
      mcq: qcmPool(ELEC_QCM, { guillotine: true }),
      true_false: vfPool(ELEC_VF),
      ordering: ordrePool(ELEC_ORDRES),
    },
    gens: { classification: triGen(ELEC_TRIS) },
  },
  'CE1.QLM.OBJETS.NUMERIQUE': {
    pools: {
      mcq: qcmPool(NUM_QCM, { guillotine: true }),
      true_false: vfPool(NUM_VF),
      ordering: ordrePool(NUM_ORDRES),
    },
    gens: { classification: triGen(NUM_TRIS), pairing: paireGen(NUM_PAIRES) },
  },
};
