/**
 * Mots-clés à savoir écrire en Questionner le monde et en EMC au CE1 (jeux d'écriture : Ascension,
 * Appareil photo, Wordle, Mots croisés…). Mots courts et fréquents au Facile ; vocabulaire de la leçon
 * au Normal ; mots plus longs au Plus loin. Chaque définition est rédigée pour un enfant de 7 ans et ne
 * contient pas le mot.
 */
import type { M } from '../../generators/mots-cles';

export const MOTS_CE1: Record<string, readonly M[]> = {
  /* ------------------------------ Le temps ------------------------------ */
  'CE1.QLM.TEMPS.CALENDRIER': [
    ['jour', 'il y en a sept dans une semaine', 'f'],
    ['mois', 'il y en a douze dans une année', 'f', 'Janvier est le premier mois de l’année.'],
    ['année', 'elle dure douze mois', 'f'],
    ['lundi', 'premier jour de la semaine', 'f'],
    ['été', 'saison la plus chaude', 'f', 'En été, il fait chaud.'],
    ['hiver', 'saison la plus froide', 'f'],
    ['semaine', 'elle dure sept jours', 'n'],
    ['saison', 'il y en a quatre dans une année', 'n'],
    ['printemps', 'saison où les fleurs poussent', 'n'],
    ['automne', 'saison où les feuilles tombent', 'n'],
    ['calendrier', 'il montre les jours et les mois de l’année', 'n'],
    ['dimanche', 'dernier jour de la semaine', 'n'],
    ['mercredi', 'jour entre mardi et jeudi', 'n'],
    ['février', 'deuxième mois de l’année, le plus court', 'p'],
    ['septembre', 'mois de la rentrée des classes', 'p'],
    ['anniversaire', 'fête du jour où l’on est né', 'p'],
  ],
  'CE1.QLM.TEMPS.FRISE': [
    ['avant', 'contraire de « après »', 'f'],
    ['après', 'contraire de « avant »', 'f'],
    ['hier', 'le jour avant aujourd’hui', 'f'],
    ['bébé', 'tout petit enfant', 'f'],
    ['famille', 'les parents, les enfants, les grands-parents…', 'f'],
    ['papa', 'autre nom du père', 'f'],
    ['frise', 'longue bande où l’on range les événements dans l’ordre du temps', 'n'],
    ['passé', 'ce qui est déjà arrivé', 'n'],
    ['présent', 'ce qui se passe maintenant', 'n', 'Le présent, c’est maintenant.'],
    ['futur', 'ce qui va arriver plus tard', 'n'],
    ['demain', 'le jour après aujourd’hui', 'n'],
    ['parents', 'le père et la mère', 'n'],
    ['génération', 'les enfants, les parents ou les grands-parents : chacun en forme une', 'p'],
    ['ancêtre', 'personne de la famille qui a vécu il y a très longtemps', 'p'],
    ['siècle', 'durée de cent ans', 'p'],
  ],
  'CE1.QLM.TEMPS.AUTREFOIS': [
    ['école', 'lieu où les enfants apprennent', 'f'],
    ['lampe', 'objet qui éclaire', 'f'],
    ['plume', 'autrefois, on la trempait dans l’encre pour écrire', 'f'],
    ['cheval', 'animal qui tirait les charrettes', 'f'],
    ['bougie', 'bâton de cire qui éclaire avec une flamme', 'f'],
    ['radio', 'appareil qui fait entendre des voix et de la musique', 'f'],
    ['autrefois', 'il y a longtemps', 'n'],
    ['ardoise', 'petite plaque sur laquelle on écrit à la craie', 'n'],
    ['lavoir', 'bassin où l’on lavait le linge à la main', 'n'],
    ['encre', 'liquide coloré pour écrire', 'n'],
    ['charrette', 'voiture en bois tirée par un cheval', 'n'],
    ['téléphone', 'appareil pour parler à quelqu’un qui est loin', 'n'],
    ['télévision', 'appareil qui montre des images et des films', 'n'],
    ['diligence', 'grande voiture tirée par des chevaux qui transportait les voyageurs', 'p'],
    ['encrier', 'petit pot d’encre posé sur la table de l’écolier', 'p'],
    ['aujourd’hui', 'le jour où nous sommes', 'p'],
  ],

  /* ------------------------------ L'espace ------------------------------ */
  'CE1.QLM.ESPACE.PLANS': [
    ['gauche', 'contraire de « droite »', 'f'],
    ['droite', 'contraire de « gauche »', 'f'],
    ['devant', 'contraire de « derrière »', 'f'],
    ['plan', 'dessin d’un lieu vu d’en haut', 'f', 'Le plan de la classe est affiché au mur.'],
    ['haut', 'contraire de « bas »', 'f'],
    ['rue', 'chemin bordé de maisons dans une ville ou un village', 'f'],
    ['derrière', 'contraire de « devant »', 'n'],
    ['maquette', 'modèle en petit d’un lieu ou d’un objet', 'n'],
    ['légende', 'elle explique les couleurs et les dessins d’un plan', 'n'],
    ['quartier', 'partie d’une ville', 'n'],
    ['carte', 'dessin d’un pays ou d’une région vu d’en haut', 'n'],
    ['dessus', 'contraire de « dessous »', 'n'],
    ['itinéraire', 'chemin à suivre pour aller quelque part', 'p'],
    ['boussole', 'objet dont l’aiguille montre le nord', 'p'],
    ['orientation', 'fait de savoir où l’on est et où aller', 'p'],
  ],
  'CE1.QLM.ESPACE.MONDE': [
    ['Terre', 'planète où nous vivons', 'f'],
    ['mer', 'grande étendue d’eau salée', 'f', 'Les bateaux naviguent sur la mer.'],
    ['océan', 'très grande étendue d’eau salée', 'f'],
    ['pays', 'territoire avec ses habitants, comme la France', 'f'],
    ['île', 'terre entourée d’eau', 'f'],
    ['globe', 'boule qui représente la Terre', 'f'],
    ['continent', 'très grande étendue de terre : il y en a six', 'n'],
    ['Afrique', 'continent au sud de l’Europe', 'n'],
    ['Europe', 'continent où se trouve la France', 'n'],
    ['Asie', 'le plus grand continent', 'n'],
    ['Amérique', 'continent de l’autre côté de l’océan Atlantique', 'n'],
    ['France', 'pays où se trouve Paris', 'n'],
    ['planisphère', 'carte du monde entier à plat', 'p'],
    ['Atlantique', 'océan entre l’Europe et l’Amérique', 'p'],
    ['Antarctique', 'continent glacé autour du pôle Sud', 'p'],
    ['Océanie', 'continent de l’Australie', 'p'],
  ],
  'CE1.QLM.ESPACE.PAYSAGES': [
    ['ville', 'lieu avec beaucoup de maisons, de rues et d’habitants', 'f'],
    ['mer', 'grande étendue d’eau salée', 'f', 'Les bateaux naviguent sur la mer.'],
    ['plage', 'bord de mer couvert de sable', 'f'],
    ['forêt', 'grand espace couvert d’arbres', 'f'],
    ['champ', 'terrain cultivé par l’agriculteur', 'f', 'Le blé pousse dans le champ.'],
    ['montagne', 'relief très haut', 'f'],
    ['campagne', 'espace de champs, de prés et de villages', 'n'],
    ['village', 'petit groupe de maisons à la campagne', 'n'],
    ['littoral', 'bord de la mer', 'n'],
    ['falaise', 'grand rocher à pic au bord de la mer', 'n'],
    ['vallée', 'creux entre deux montagnes', 'n'],
    ['paysage', 'ce qu’on voit autour de soi, quand on regarde loin', 'n'],
    ['agriculteur', 'personne qui cultive la terre et élève des animaux', 'p'],
    ['glacier', 'grande masse de glace dans les montagnes', 'p'],
    ['immeuble', 'grand bâtiment de plusieurs étages', 'p'],
  ],

  /* ------------------------------ Le vivant ------------------------------ */
  'CE1.QLM.VIVANT.CARACT': [
    ['plante', 'être vivant qui pousse dans la terre', 'f'],
    ['animal', 'être vivant qui se déplace et se nourrit', 'f'],
    ['eau', 'tous les êtres vivants en ont besoin pour vivre', 'f'],
    ['air', 'ce qu’on respire', 'f', 'Nous respirons l’air.'],
    ['graine', 'petite chose qui donne une nouvelle plante', 'f'],
    ['caillou', 'petite pierre, qui n’est pas vivante', 'f'],
    ['vivant', 'qui naît, grandit, se nourrit et meurt', 'n'],
    ['naître', 'venir au monde', 'n'],
    ['grandir', 'devenir plus grand', 'n'],
    ['mourir', 'arrêter de vivre', 'n'],
    ['respirer', 'faire entrer et sortir l’air', 'n'],
    ['lumière', 'les plantes en ont besoin pour pousser', 'n'],
    ['nourriture', 'ce qu’on mange', 'p'],
    ['reproduction', 'fait d’avoir des petits ou de donner des graines', 'p'],
    ['végétal', 'autre nom d’une plante', 'p'],
  ],
  'CE1.QLM.VIVANT.CYCLES': [
    ['œuf', 'la poule le pond, le poussin en sort', 'f'],
    ['poule', 'oiseau de la ferme qui pond des œufs', 'f'],
    ['poussin', 'petit de la poule', 'f'],
    ['graine', 'petite chose qui donne une nouvelle plante', 'f'],
    ['fleur', 'partie colorée de la plante', 'f'],
    ['chenille', 'elle deviendra un papillon', 'f'],
    ['têtard', 'petit de la grenouille, qui vit dans l’eau', 'n'],
    ['grenouille', 'animal qui saute et qui vit près de l’eau', 'n'],
    ['papillon', 'insecte aux ailes colorées', 'n'],
    ['adulte', 'animal qui a fini de grandir', 'n'],
    ['larve', 'petit qui ne ressemble pas encore à ses parents', 'n'],
    ['cocon', 'enveloppe dans laquelle la chenille se transforme', 'n'],
    ['chrysalide', 'étape où la chenille se transforme en papillon', 'p'],
    ['métamorphose', 'grande transformation, comme celle du têtard en grenouille', 'p'],
    ['germination', 'moment où la graine commence à pousser', 'p'],
  ],
  'CE1.QLM.VIVANT.ALIM': [
    ['herbe', 'la vache et le lapin la mangent', 'f'],
    ['viande', 'le lion et le loup en mangent', 'f'],
    ['lapin', 'petit animal aux longues oreilles qui mange de l’herbe', 'f'],
    ['renard', 'animal roux qui chasse les poules', 'f'],
    ['loup', 'animal sauvage qui ressemble à un grand chien', 'f', 'Le loup hurle dans la forêt.'],
    ['vache', 'animal de la ferme qui donne du lait', 'f'],
    ['herbivore', 'animal qui mange des plantes', 'n'],
    ['carnivore', 'animal qui mange de la viande', 'n'],
    ['omnivore', 'animal qui mange de tout', 'n'],
    ['proie', 'animal mangé par un autre', 'n'],
    ['prédateur', 'animal qui chasse pour manger', 'n'],
    ['chaîne', 'la ___ alimentaire : qui mange qui', 'n'],
    ['insectivore', 'animal qui mange des insectes', 'p'],
    ['granivore', 'animal qui mange des graines', 'p'],
    ['régime', 'le ___ alimentaire : ce que mange un animal', 'p'],
  ],
  'CE1.QLM.CORPS.SANTE': [
    ['dent', 'on la brosse matin et soir', 'f', 'Je me brosse les dents.'],
    ['main', 'on la lave avant de manger', 'f', 'Je me lave les mains.'],
    ['sport', 'activité qui fait bouger le corps', 'f'],
    ['fruit', 'la pomme et la banane en sont', 'f'],
    ['savon', 'il sert à se laver les mains', 'f'],
    ['eau', 'boisson la meilleure pour la santé', 'f'],
    ['sommeil', 'temps passé à dormir', 'n'],
    ['légume', 'la carotte et le haricot en sont', 'n'],
    ['brosse', 'la ___ à dents', 'n'],
    ['hygiène', 'tout ce qu’on fait pour rester propre et en bonne santé', 'n'],
    ['dentiste', 'médecin des dents', 'n'],
    ['microbe', 'tout petit être vivant invisible qui peut rendre malade', 'n'],
    ['alimentation', 'tout ce qu’on mange', 'p'],
    ['médicament', 'produit qui soigne une maladie', 'p'],
    ['vaccin', 'il protège contre une maladie', 'p'],
  ],

  /* ------------------------------ La matière ------------------------------ */
  'CE1.QLM.MATIERE.EAU': [
    ['eau', 'liquide qu’on boit', 'f'],
    ['glace', 'eau devenue dure à cause du froid', 'f'],
    ['neige', 'flocons blancs qui tombent quand il fait froid', 'f'],
    ['pluie', 'eau qui tombe des nuages', 'f'],
    ['nuage', 'il flotte dans le ciel et donne la pluie', 'f'],
    ['froid', 'contraire de « chaud »', 'f'],
    ['liquide', 'état de l’eau qui coule', 'n'],
    ['solide', 'état de l’eau quand elle est dure, comme la glace', 'n'],
    ['vapeur', 'eau devenue gaz en chauffant', 'n'],
    ['fondre', 'passer de solide à liquide', 'n'],
    ['glaçon', 'petit cube de glace', 'n'],
    ['flaque', 'petite mare d’eau par terre après la pluie', 'n'],
    ['évaporation', 'l’eau qui disparaît dans l’air en devenant gaz', 'p'],
    ['thermomètre', 'il mesure la température', 'p'],
    ['température', 'elle dit s’il fait chaud ou froid', 'p'],
  ],
  'CE1.QLM.OBJETS.ELEC': [
    ['pile', 'petit objet qui donne l’électricité aux jouets', 'f'],
    ['lampe', 'objet qui éclaire', 'f'],
    ['fil', 'il relie la pile et l’ampoule', 'f'],
    ['prise', 'on y branche les appareils électriques', 'f'],
    ['danger', 'ce qui peut nous faire du mal', 'f'],
    ['ampoule', 'elle s’allume et éclaire', 'f'],
    ['circuit', 'chemin fermé que suit le courant électrique', 'n'],
    ['interrupteur', 'il sert à allumer et éteindre la lumière', 'n'],
    ['électricité', 'énergie qui fait marcher les lampes et les appareils', 'n'],
    ['courant', 'le ___ électrique circule dans les fils', 'n'],
    ['batterie', 'grosse pile qu’on peut recharger', 'n'],
    ['allumer', 'faire briller une lampe', 'n'],
    ['conducteur', 'matériau qui laisse passer le courant, comme le métal', 'p'],
    ['isolant', 'matériau qui ne laisse pas passer le courant, comme le plastique', 'p'],
    ['borne', 'chaque bout de la pile où l’on attache un fil', 'p'],
  ],
  'CE1.QLM.OBJETS.NUMERIQUE': [
    ['écran', 'surface où s’affichent les images', 'f'],
    ['tablette', 'petit ordinateur plat qu’on touche avec le doigt', 'f'],
    ['clavier', 'ensemble des touches pour écrire', 'f'],
    ['souris', 'petit objet qu’on déplace pour diriger la flèche sur l’écran', 'f'],
    ['photo', 'image prise avec un appareil', 'f'],
    ['jeu', 'activité pour s’amuser', 'f'],
    ['ordinateur', 'machine qui sert à écrire, calculer, chercher des informations', 'n'],
    ['internet', 'réseau qui relie les ordinateurs du monde entier', 'n'],
    ['téléphone', 'appareil pour parler à quelqu’un qui est loin', 'n'],
    ['message', 'information envoyée à quelqu’un', 'n'],
    ['imprimante', 'machine qui met sur papier ce qui est à l’écran', 'n'],
    ['inconnu', 'personne qu’on n’a jamais rencontrée', 'n'],
    ['application', 'programme qu’on utilise sur une tablette ou un téléphone', 'p'],
    ['numérique', 'qui concerne les ordinateurs, les tablettes et Internet', 'p'],
    ['logiciel', 'programme qui fait marcher un ordinateur', 'p'],
  ],

  /* ------------------------------ EMC ------------------------------ */
  'CE1.EMC.REGLES': [
    ['règle', 'ce qu’il faut respecter pour bien vivre ensemble', 'f'],
    ['classe', 'groupe d’élèves qui travaillent avec le même maître', 'f'],
    ['droit', 'ce qu’on a le droit de faire', 'f'],
    ['devoir', 'ce qu’on doit faire', 'f'],
    ['calme', 'contraire d’« agité »', 'f'],
    ['merci', 'mot poli pour remercier', 'f'],
    ['politesse', 'bonjour, merci, s’il te plaît…', 'n'],
    ['respect', 'attention et gentillesse envers les autres', 'n'],
    ['sanction', 'ce qui arrive quand on ne respecte pas une règle', 'n'],
    ['récréation', 'pause pour jouer dans la cour', 'n'],
    ['partage', 'fait de donner une part aux autres', 'n'],
    ['silence', 'quand personne ne parle', 'n'],
    ['responsabilité', 'tâche qu’on nous confie et qu’on doit faire', 'p'],
    ['coopération', 'fait de travailler ensemble', 'p'],
    ['citoyen', 'personne qui a des droits et des devoirs dans son pays', 'p'],
  ],
  'CE1.EMC.EMOTIONS': [
    ['joie', 'on la ressent quand on est content', 'f'],
    ['peur', 'on la ressent devant un danger', 'f'],
    ['colère', 'on la ressent quand on est fâché', 'f'],
    ['calme', 'quand on se sent tranquille', 'f'],
    ['rire', 'ce qu’on fait quand c’est drôle', 'f'],
    ['pleurer', 'verser des larmes', 'f'],
    ['tristesse', 'on la ressent quand on a du chagrin', 'n'],
    ['surprise', 'on la ressent devant quelque chose d’inattendu', 'n'],
    ['émotion', 'joie, peur, colère, tristesse… en sont', 'n'],
    ['dégoût', 'on le ressent devant quelque chose de sale ou de mauvais', 'n'],
    ['fierté', 'on la ressent quand on a réussi quelque chose de difficile', 'n'],
    ['timide', 'qui n’ose pas parler ou se montrer', 'n'],
    ['inquiétude', 'peur de ce qui pourrait arriver', 'p'],
    ['jalousie', 'envie de ce que l’autre a', 'p'],
    ['frustration', 'déception quand on n’obtient pas ce qu’on voulait', 'p'],
  ],
  'CE1.EMC.SYMBOLES': [
    ['drapeau', 'il est bleu, blanc, rouge pour la France', 'f'],
    ['bleu', 'première couleur du drapeau français', 'f'],
    ['blanc', 'couleur du milieu du drapeau français', 'f'],
    ['rouge', 'dernière couleur du drapeau français', 'f'],
    ['France', 'notre pays', 'f'],
    ['liberté', 'premier mot de la devise de la France', 'f'],
    ['Marianne', 'visage de femme qui représente la République', 'n'],
    ['devise', 'Liberté, Égalité, Fraternité', 'n'],
    ['égalité', 'deuxième mot de la devise de la France', 'n'],
    ['fraternité', 'troisième mot de la devise de la France', 'n'],
    ['hymne', 'chant d’un pays', 'n'],
    ['République', 'nom du régime de la France, qui n’a plus de roi', 'n'],
    ['Marseillaise', 'hymne de la France', 'p'],
    ['tricolore', 'qui a trois couleurs', 'p'],
    ['symbole', 'image qui représente une idée', 'p'],
  ],
  'CE1.EMC.RESPECT': [
    ['ami', 'personne qu’on aime bien et avec qui on joue', 'f'],
    ['aide', 'ce qu’on apporte à quelqu’un qui en a besoin', 'f'],
    ['stop', 'mot qu’on dit pour arrêter quelqu’un qui nous embête', 'f'],
    ['gentil', 'contraire de « méchant »', 'f'],
    ['partage', 'fait de donner une part aux autres', 'f'],
    ['merci', 'mot poli pour remercier', 'f'],
    ['respect', 'attention et gentillesse envers les autres', 'n'],
    ['moquerie', 'parole qui se moque de quelqu’un', 'n'],
    ['égalité', 'filles et garçons ont les mêmes droits', 'n'],
    ['différence', 'ce qui fait qu’on n’est pas pareil', 'n'],
    ['insulte', 'parole méchante', 'n'],
    ['adulte', 'grande personne à qui l’on demande de l’aide', 'n'],
    ['harcèlement', 'méchancetés répétées contre une même personne', 'p'],
    ['tolérance', 'fait d’accepter les autres comme ils sont', 'p'],
    ['solidarité', 'aide qu’on s’apporte les uns aux autres', 'p'],
  ],
  'CE1.EMC.ENVIRONNEMENT': [
    ['tri', 'on le fait pour ranger les déchets dans la bonne poubelle', 'f'],
    ['poubelle', 'bac où l’on jette les déchets', 'f'],
    ['papier', 'on l’utilise pour écrire et on peut le recycler', 'f'],
    ['verre', 'matière des bouteilles et des pots, qui se recycle', 'f', 'La bouteille est en verre.'],
    ['planète', 'la Terre, qu’il faut protéger', 'f'],
    ['eau', 'il ne faut pas la gaspiller', 'f'],
    ['recycler', 'transformer un déchet en nouvel objet', 'n'],
    ['déchet', 'ce qu’on jette', 'n'],
    ['plastique', 'matière des bouteilles d’eau et des emballages', 'n'],
    ['compost', 'tas d’épluchures qui devient de la terre', 'n'],
    ['pollution', 'ce qui salit l’air, l’eau ou la terre', 'n'],
    ['gaspillage', 'fait de jeter ou d’utiliser plus que nécessaire', 'n'],
    ['environnement', 'la nature autour de nous', 'p'],
    ['recyclage', 'transformation d’un déchet en nouvel objet', 'p'],
    ['emballage', 'ce qui entoure un produit qu’on achète', 'p'],
  ],
};
