/**
 * Questionner le monde CE1 — « Se situer dans le temps » (programme 2020, en vigueur en 2026-2027) :
 * calendrier (jours, semaines, mois, saisons, année), frise et générations, modes de vie d'autrefois.
 * Les QCM de `data/questions/ce1_questions.json` (calendrier, autrefois) complètent ces banques.
 * Thèmes neutres : jouables dans la Guillotine.
 */
import type { ContentModule } from '../../registry';
import {
  type Appariement,
  type Ordre,
  type Q,
  type Tri,
  type VF,
  ordrePool,
  paireGen,
  qcmPool,
  triGen,
  vfPool,
} from './outils';

/* ------------------------------------------------------------------ */
/* Calendrier                                                          */
/* ------------------------------------------------------------------ */

const JOURS = ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche'];

const CAL_QCM: Q[] = [
  {
    n: 'f',
    id: 'saison-chaude',
    q: 'Pendant quelle saison fait-il le plus chaud ?',
    ok: 'l’été',
    ko: ['l’hiver', 'l’automne', 'le printemps'],
    img: '☀️',
    ex: 'L’été est la saison la plus chaude : c’est la saison des grandes vacances.',
  },
  {
    n: 'f',
    id: 'week-end',
    q: 'Quels sont les jours du week-end ?',
    ok: 'samedi et dimanche',
    ko: ['lundi et mardi', 'jeudi et vendredi', 'mercredi et jeudi'],
    ex: 'Le week-end, ce sont les deux derniers jours de la semaine : samedi et dimanche.',
  },
  {
    n: 'f',
    id: 'demain-lundi',
    q: 'Aujourd’hui, c’est lundi. Quel jour serons-nous demain ?',
    ok: 'mardi',
    ko: ['dimanche', 'mercredi', 'samedi'],
    ex: 'Demain, c’est le jour qui vient après aujourd’hui : après lundi vient mardi.',
  },
  {
    n: 'n',
    id: 'noel',
    q: 'En quel mois fête-t-on Noël ?',
    ok: 'décembre',
    ko: ['janvier', 'novembre', 'juillet'],
    img: '🎄',
    ex: 'Noël, c’est le 25 décembre, le dernier mois de l’année.',
  },
  {
    n: 'n',
    id: 'feuilles',
    q: 'En quelle saison les feuilles de beaucoup d’arbres tombent-elles ?',
    ok: 'en automne',
    ko: ['en été', 'au printemps', 'en hiver'],
    img: '🍂',
    ex: 'En automne, les feuilles jaunissent puis tombent.',
  },
  {
    n: 'n',
    id: 'janvier-31',
    q: 'Combien de jours y a-t-il dans le mois de janvier ?',
    ok: '31',
    ko: ['30', '28', '12'],
    ex: 'Janvier a 31 jours. Les mois ont 30 ou 31 jours, sauf février.',
  },
  {
    n: 'n',
    id: 'avant-septembre',
    q: 'Quel mois vient juste avant septembre ?',
    ok: 'août',
    ko: ['octobre', 'juillet', 'juin'],
    ex: 'Dans l’ordre : juillet, août, septembre. Août vient juste avant septembre.',
  },
  {
    n: 'n',
    id: 'printemps-mars',
    q: 'Quelle saison commence au mois de mars ?',
    ok: 'le printemps',
    ko: ['l’été', 'l’hiver', 'l’automne'],
    img: '🌷',
    ex: 'Le printemps commence vers le 20 mars ; l’été en juin, l’automne en septembre, l’hiver en décembre.',
  },
  {
    n: 'n',
    id: 'hiver-decembre',
    q: 'Quelle saison commence au mois de décembre ?',
    ok: 'l’hiver',
    ko: ['le printemps', 'l’été', 'l’automne'],
    img: '⛄',
    ex: 'L’hiver commence vers le 21 décembre, juste avant Noël.',
  },
  {
    n: 'p',
    id: 'semaines-annee',
    q: 'Combien de semaines y a-t-il environ dans une année ?',
    ok: '52',
    ko: ['12', '365', '7'],
    ex: 'Une année compte environ 52 semaines (52 fois 7 jours, plus un jour ou deux).',
  },
  {
    n: 'p',
    id: 'jours-annee',
    q: 'Combien de jours y a-t-il dans une année ordinaire ?',
    ok: '365',
    ko: ['100', '52', '12'],
    ex: 'Une année ordinaire a 365 jours ; une année bissextile en a 366.',
  },
  {
    n: 'p',
    id: 'lundi-prochain',
    q: 'Aujourd’hui, c’est lundi 3 mai. Quelle date serons-nous lundi prochain ?',
    ok: 'lundi 10 mai',
    ko: ['lundi 4 mai', 'lundi 17 mai', 'mardi 10 mai'],
    ex: 'Une semaine plus tard, on ajoute 7 jours : 3 + 7 = 10, donc lundi 10 mai.',
  },
  {
    n: 'p',
    id: 'siecle-actuel',
    q: 'En quel siècle vivons-nous ?',
    ok: 'au XXIe siècle (vingt-et-unième)',
    ko: ['au XXe siècle (vingtième)', 'au Xe siècle (dixième)', 'au IIe siècle (deuxième)'],
    ex: 'Les années 2001 à 2100 forment le XXIe siècle : c’est notre siècle.',
  },
  // Devinettes (Qui suis-je ?)
  {
    n: 'n',
    id: 'qui-hiver',
    q: 'Qui suis-je ?',
    ok: 'l’hiver',
    ko: ['l’été', 'l’automne', 'le printemps'],
    img: '⛄',
    hints: [
      'Je suis une saison.',
      'Je commence au mois de décembre.',
      'Avec moi, les jours sont courts et les nuits sont longues.',
      'Il fait froid et il peut neiger.',
      'Noël arrive au tout début de ma saison.',
    ],
    ex: 'L’hiver est la saison la plus froide ; il commence vers le 21 décembre.',
  },
  {
    n: 'n',
    id: 'qui-ete',
    q: 'Qui suis-je ?',
    ok: 'l’été',
    ko: ['l’hiver', 'l’automne', 'le printemps'],
    img: '☀️',
    hints: [
      'Je suis une saison.',
      'Je commence au mois de juin.',
      'Avec moi, les jours sont très longs.',
      'Il fait souvent chaud.',
      'C’est pendant moi qu’ont lieu les grandes vacances !',
    ],
    ex: 'L’été commence vers le 21 juin : c’est la saison la plus chaude.',
  },
  {
    n: 'n',
    id: 'qui-automne',
    q: 'Qui suis-je ?',
    ok: 'l’automne',
    ko: ['l’été', 'l’hiver', 'le printemps'],
    img: '🍂',
    hints: [
      'Je suis une saison.',
      'Je commence au mois de septembre.',
      'Avec moi, il pleut souvent et le vent souffle.',
      'Les feuilles des arbres jaunissent et tombent.',
      'On ramasse des châtaignes dans les bois.',
    ],
    ex: 'L’automne commence vers le 22 septembre, juste après la rentrée.',
  },
  {
    n: 'n',
    id: 'qui-printemps',
    q: 'Qui suis-je ?',
    ok: 'le printemps',
    ko: ['l’été', 'l’hiver', 'l’automne'],
    img: '🌷',
    hints: [
      'Je suis une saison.',
      'Je commence au mois de mars.',
      'Avec moi, les jours rallongent.',
      'Les fleurs poussent et les arbres font des bourgeons.',
      'Les oiseaux construisent leur nid.',
    ],
    ex: 'Le printemps commence vers le 20 mars : la nature se réveille.',
  },
  {
    n: 'f',
    id: 'qui-dimanche',
    q: 'Qui suis-je ?',
    ok: 'dimanche',
    ko: ['lundi', 'mercredi', 'samedi'],
    img: '📅',
    hints: [
      'Je suis un jour de la semaine.',
      'Je fais partie du week-end.',
      'Je suis le dernier jour de la semaine.',
      'Je viens juste après samedi.',
    ],
    ex: 'Dimanche est le dernier jour de la semaine, juste après samedi.',
  },
  {
    n: 'f',
    id: 'qui-calendrier',
    q: 'Qui suis-je ?',
    ok: 'le calendrier',
    ko: ['l’horloge', 'la montre', 'le thermomètre'],
    img: '📅',
    hints: [
      'Je suis un objet.',
      'On m’accroche souvent au mur.',
      'On y lit les jours, les semaines et les mois.',
      'On m’utilise pour connaître la date.',
    ],
    ex: 'Le calendrier montre les jours, les semaines et les mois de l’année.',
  },
];

const CAL_VF: VF[] = [
  {
    n: 'f',
    id: 'semaine-7',
    s: 'Une semaine a 7 jours.',
    v: true,
    ex: 'Lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche : 7 jours.',
  },
  {
    n: 'f',
    id: 'mercredi-jeudi',
    s: 'Mercredi vient juste après jeudi.',
    v: false,
    ex: 'Mercredi vient avant jeudi : lundi, mardi, mercredi, jeudi…',
  },
  {
    n: 'f',
    id: 'week-end',
    s: 'Samedi et dimanche forment le week-end.',
    v: true,
    ex: 'Le week-end, ce sont samedi et dimanche.',
  },
  {
    n: 'f',
    id: 'trois-saisons',
    s: 'Il y a 3 saisons dans une année.',
    v: false,
    ex: 'Il y a 4 saisons : le printemps, l’été, l’automne et l’hiver.',
  },
  {
    n: 'f',
    id: 'lundi-dimanche',
    s: 'Lundi vient juste après dimanche.',
    v: true,
    ex: 'Après dimanche, une nouvelle semaine commence par lundi.',
  },
  {
    n: 'f',
    id: 'dimanche-premier',
    s: 'Dimanche est le premier jour de la semaine.',
    v: false,
    ex: 'En France, la semaine commence le lundi ; dimanche est le dernier jour.',
  },
  {
    n: 'n',
    id: 'douze-mois',
    s: 'Une année a 12 mois.',
    v: true,
    ex: 'De janvier à décembre, il y a 12 mois.',
  },
  {
    n: 'n',
    id: 'fevrier-court',
    s: 'Février est le mois le plus court de l’année.',
    v: true,
    ex: 'Février a 28 jours (29 certaines années) : c’est le plus court.',
  },
  {
    n: 'n',
    id: 'juillet-aout',
    s: 'Juillet vient juste après août.',
    v: false,
    ex: 'Juillet vient avant août : juin, juillet, août.',
  },
  {
    n: 'n',
    id: 'hiver-chaud',
    s: 'L’hiver est la saison la plus chaude.',
    v: false,
    ex: 'L’hiver est la saison la plus froide ; la plus chaude, c’est l’été.',
  },
  { n: 'n', id: 'juin-31', s: 'Le mois de juin a 31 jours.', v: false, ex: 'Juin a 30 jours.' },
  {
    n: 'n',
    id: 'janvier-apres',
    s: 'Après décembre, une nouvelle année commence en janvier.',
    v: true,
    ex: 'Décembre est le dernier mois ; janvier ouvre la nouvelle année.',
  },
  {
    n: 'n',
    id: 'printemps-hiver',
    s: 'Le printemps vient après l’hiver.',
    v: true,
    ex: 'Hiver, printemps, été, automne, puis l’hiver revient.',
  },
  { n: 'p', id: 'siecle-100', s: 'Un siècle dure 100 ans.', v: true, ex: 'Un siècle, c’est 100 ans.' },
  {
    n: 'p',
    id: 'annee-365',
    s: 'Une année ordinaire a 365 jours.',
    v: true,
    ex: 'Une année ordinaire a 365 jours, une année bissextile 366.',
  },
  {
    n: 'p',
    id: 'fevrier-29',
    s: 'Tous les 4 ans environ, février a 29 jours.',
    v: true,
    ex: 'Ces années s’appellent des années bissextiles.',
  },
  {
    n: 'p',
    id: 'xxe',
    s: 'Nous vivons au XXe siècle.',
    v: false,
    ex: 'Depuis l’an 2001, nous sommes au XXIe siècle.',
  },
  {
    n: 'p',
    id: 'mois-30',
    s: 'Tous les mois ont 30 jours.',
    v: false,
    ex: 'Certains mois ont 30 jours, d’autres 31, et février 28 ou 29.',
  },
];

const CAL_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'jours',
    prompt: 'Range les jours de la semaine dans l’ordre, en commençant par lundi.',
    el: JOURS,
    mode: 'chrono',
    ex: 'Lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.',
  },
  {
    n: 'f',
    id: 'jours-debut',
    prompt: 'Range ces jours dans l’ordre.',
    el: ['lundi', 'mardi', 'mercredi', 'jeudi'],
    mode: 'chrono',
    ex: 'La semaine commence par lundi, puis mardi, mercredi et jeudi.',
  },
  {
    n: 'f',
    id: 'saisons-ecole',
    prompt: 'Range les saisons dans l’ordre de l’année scolaire, en commençant par la rentrée.',
    el: ['l’automne', 'l’hiver', 'le printemps', 'l’été'],
    labels: ['septembre', 'décembre', 'mars', 'juin'],
    mode: 'chrono',
    ex: 'Après la rentrée vient l’automne, puis l’hiver, le printemps et enfin l’été.',
  },
  {
    n: 'n',
    id: 'mois-1',
    prompt: 'Range ces mois dans l’ordre de l’année.',
    el: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin'],
    labels: ['1', '2', '3', '4', '5', '6'],
    mode: 'chrono',
    ex: 'Janvier, février, mars, avril, mai, juin : ce sont les 6 premiers mois.',
  },
  {
    n: 'n',
    id: 'mois-2',
    prompt: 'Range ces mois dans l’ordre de l’année.',
    el: ['juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    labels: ['7', '8', '9', '10', '11', '12'],
    mode: 'chrono',
    ex: 'Juillet, août, septembre, octobre, novembre, décembre : ce sont les 6 derniers mois.',
  },
  {
    n: 'n',
    id: 'mois-sauts',
    prompt: 'Range ces mois dans l’ordre de l’année.',
    el: ['janvier', 'mars', 'mai', 'août', 'octobre', 'décembre'],
    labels: ['1', '3', '5', '8', '10', '12'],
    mode: 'chrono',
    ex: 'Récite les mois dans ta tête : janvier, février, mars, avril, mai…',
  },
  {
    n: 'n',
    id: 'jours-jeudi',
    prompt: 'Range ces jours dans l’ordre, en commençant par jeudi.',
    el: ['jeudi', 'vendredi', 'samedi', 'dimanche', 'lundi'],
    mode: 'chrono',
    ex: 'Après dimanche, la semaine recommence : jeudi, vendredi, samedi, dimanche, lundi.',
  },
  {
    n: 'n',
    id: 'saisons-annee',
    prompt: 'Range les saisons dans l’ordre, en commençant par le printemps.',
    el: ['le printemps', 'l’été', 'l’automne', 'l’hiver'],
    labels: ['mars', 'juin', 'septembre', 'décembre'],
    mode: 'chrono',
    ex: 'Printemps, été, automne, hiver : puis le printemps revient.',
  },
  {
    n: 'p',
    id: 'durees',
    prompt: 'Range ces durées de la plus courte à la plus longue.',
    el: ['une journée', 'une semaine', 'un mois', 'une année', 'un siècle'],
    labels: ['24 heures', '7 jours', '28 à 31 jours', '12 mois', '100 ans'],
    mode: 'chrono',
    ex: 'Une semaine = 7 jours, un mois ≈ 4 semaines, une année = 12 mois, un siècle = 100 ans.',
  },
  {
    n: 'p',
    id: 'mois-fin',
    prompt: 'Range ces mois dans l’ordre, en commençant par septembre (la rentrée).',
    el: ['septembre', 'novembre', 'janvier', 'mars', 'juin'],
    mode: 'chrono',
    ex: 'L’année scolaire commence en septembre et se termine en juin ou juillet.',
  },
];

const CAL_TRIS: Record<'facile' | 'normal' | 'plus_loin', Tri[]> = {
  facile: [
    {
      id: 'jour-mois',
      prompt: 'Est-ce un jour de la semaine ou un mois ?',
      categories: ['un jour de la semaine', 'un mois'],
      elements: [
        ...JOURS.map((j) => ({ label: j, c: 'un jour de la semaine', n: 'f' as const })),
        ...['janvier', 'mars', 'mai', 'juillet', 'octobre', 'décembre'].map((m) => ({
          label: m,
          c: 'un mois',
          n: 'f' as const,
        })),
      ],
      ex: 'Il y a 7 jours dans une semaine et 12 mois dans une année.',
    },
  ],
  normal: [
    {
      id: 'jour-mois-saison',
      prompt: 'Range chaque mot : un jour, un mois ou une saison ?',
      categories: ['un jour', 'un mois', 'une saison'],
      elements: [
        ...['lundi', 'mercredi', 'vendredi', 'samedi', 'dimanche'].map((j) => ({
          label: j,
          c: 'un jour',
          n: 'n' as const,
        })),
        ...['février', 'avril', 'juin', 'août', 'novembre'].map((m) => ({
          label: m,
          c: 'un mois',
          n: 'n' as const,
        })),
        { label: 'le printemps', c: 'une saison', n: 'n', img: '🌷' },
        { label: 'l’été', c: 'une saison', n: 'n', img: '☀️' },
        { label: 'l’automne', c: 'une saison', n: 'n', img: '🍂' },
        { label: 'l’hiver', c: 'une saison', n: 'n', img: '⛄' },
      ],
      ex: 'Une semaine a 7 jours, une année a 12 mois et 4 saisons.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'durees',
      prompt: 'Cette durée est-elle plus courte ou plus longue qu’une semaine ?',
      categories: ['moins d’une semaine', 'plus d’une semaine'],
      elements: [
        { label: 'une nuit', c: 'moins d’une semaine', n: 'p', img: '🌙' },
        { label: 'une journée', c: 'moins d’une semaine', n: 'p' },
        { label: 'un week-end', c: 'moins d’une semaine', n: 'p' },
        { label: 'une récréation', c: 'moins d’une semaine', n: 'p' },
        { label: 'un mois', c: 'plus d’une semaine', n: 'p' },
        { label: 'une année', c: 'plus d’une semaine', n: 'p' },
        { label: 'les grandes vacances', c: 'plus d’une semaine', n: 'p', img: '🏖️' },
        { label: 'un siècle', c: 'plus d’une semaine', n: 'p' },
      ],
      ex: 'Une semaine dure 7 jours : une journée est plus courte, un mois est plus long.',
    },
  ],
};

const CAL_PAIRES: Record<'facile' | 'normal' | 'plus_loin', Appariement[]> = {
  facile: [
    {
      id: 'saisons',
      prompt: 'Associe chaque saison à son image.',
      relation: 'saison → image',
      duos: [
        { l: 'l’hiver', r: '⛄', n: 'f' },
        { l: 'le printemps', r: '🌷', n: 'f' },
        { l: 'l’été', r: '🏖️', n: 'f' },
        { l: 'l’automne', r: '🍂', n: 'f' },
      ],
      ex: 'Neige en hiver, fleurs au printemps, plage en été, feuilles mortes en automne.',
      nb: 4,
    },
  ],
  normal: [
    {
      id: 'rang-mois',
      prompt: 'Associe chaque mois à sa place dans l’année.',
      relation: 'mois → rang',
      duos: [
        'janvier',
        'février',
        'mars',
        'avril',
        'mai',
        'juin',
        'juillet',
        'août',
        'septembre',
        'octobre',
        'novembre',
        'décembre',
      ].map((m, i) => ({ l: m, r: i === 0 ? '1er mois' : `${i + 1}e mois`, n: 'n' as const })),
      ex: 'Janvier est le 1er mois de l’année et décembre le 12e.',
    },
  ],
  plus_loin: [
    {
      id: 'fetes',
      prompt: 'Associe chaque fête à son mois.',
      relation: 'fête → mois',
      duos: [
        { l: 'le jour de l’An', r: 'janvier', n: 'p' },
        { l: 'la fête du Travail', r: 'mai', n: 'p' },
        { l: 'la fête nationale', r: 'juillet', n: 'p' },
        { l: 'la Toussaint', r: 'novembre', n: 'p' },
        { l: 'Noël', r: 'décembre', n: 'p' },
        { l: 'la rentrée', r: 'septembre', n: 'p' },
      ],
      ex: 'Jour de l’An le 1er janvier, fête du Travail le 1er mai, fête nationale le 14 juillet, Toussaint le 1er novembre, Noël le 25 décembre.',
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Frise, avant / après, générations                                    */
/* ------------------------------------------------------------------ */

/** Frises d'objets d'autrefois (partagées avec la leçon « Autrefois »). */
export const FRISES_OBJETS: Ordre[] = [
  {
    n: 'p',
    id: 'lumiere',
    prompt: 'Range ces objets pour s’éclairer, du plus ancien au plus récent.',
    el: ['la bougie', 'la lampe à pétrole', 'l’ampoule électrique', 'la lampe à LED'],
    labels: ['il y a très longtemps', 'vers 1860', 'vers 1880', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'On s’éclairait à la bougie, puis à la lampe à pétrole ; l’ampoule électrique arrive vers 1880, la lampe à LED est récente.',
  },
  {
    n: 'p',
    id: 'transports',
    prompt: 'Range ces moyens de transport, du plus ancien au plus récent.',
    el: ['la charrette à cheval', 'la locomotive à vapeur', 'l’automobile', 'l’avion'],
    labels: ['il y a très longtemps', 'vers 1830', 'vers 1890', 'vers 1910'],
    mode: 'chrono',
    ex: 'Le cheval a longtemps servi à se déplacer ; puis sont venus le train à vapeur, l’automobile et enfin l’avion.',
  },
  {
    n: 'p',
    id: 'musique',
    prompt: 'Range ces objets pour écouter de la musique, du plus ancien au plus récent.',
    el: ['le phonographe', 'le tourne-disque', 'le baladeur à cassettes', 'le téléphone portable'],
    labels: ['vers 1880', 'vers 1950', 'vers 1980', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'Le phonographe a été inventé vers 1880 ; tes grands-parents écoutaient des disques, tes parents des cassettes.',
  },
  {
    n: 'p',
    id: 'ecriture',
    prompt: 'Range ces objets pour écrire, du plus ancien au plus récent.',
    el: ['la plume d’oie', 'le porte-plume et l’encrier', 'le stylo à bille', 'l’ordinateur'],
    labels: ['il y a très longtemps', 'vers 1900', 'vers 1960', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'On a écrit avec des plumes d’oiseau, puis des plumes en métal trempées dans l’encre ; le stylo à bille arrive à l’école vers 1960.',
  },
  {
    n: 'p',
    id: 'telephone',
    prompt: 'Range ces téléphones, du plus ancien au plus récent.',
    el: [
      'le téléphone à manivelle',
      'le téléphone à cadran',
      'le téléphone sans fil',
      'le téléphone portable tactile',
    ],
    labels: ['vers 1900', 'vers 1960', 'vers 1990', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'Les premiers téléphones avaient une manivelle ; tes grands-parents tournaient un cadran ; aujourd’hui, on touche un écran.',
  },
];

const FRISE_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'journee',
    prompt: 'Range ces moments de la journée dans l’ordre.',
    el: ['le matin', 'l’après-midi', 'le soir'],
    mode: 'chrono',
    ex: 'La journée commence le matin, continue l’après-midi et finit le soir.',
  },
  {
    n: 'f',
    id: 'hier-demain',
    prompt: 'Range du passé vers le futur.',
    el: ['hier', 'aujourd’hui', 'demain'],
    mode: 'chrono',
    ex: 'Hier, c’est passé ; aujourd’hui, c’est maintenant ; demain, c’est le jour qui vient.',
  },
  {
    n: 'f',
    id: 'age-3',
    prompt: 'Range du plus jeune au plus âgé.',
    el: ['le bébé', 'l’enfant', 'l’adulte'],
    mode: 'chrono',
    ex: 'On est d’abord un bébé, puis un enfant, puis un adulte.',
  },
  {
    n: 'f',
    id: 'matin',
    prompt: 'Remets ces actions du matin dans l’ordre.',
    el: ['je me réveille', 'je prends mon petit-déjeuner', 'je pars à l’école'],
    mode: 'chrono',
    ex: 'On se réveille, on prend son petit-déjeuner, puis on part à l’école.',
  },
  {
    n: 'f',
    id: 'repas',
    prompt: 'Range les repas de la journée dans l’ordre.',
    el: ['le petit-déjeuner', 'le déjeuner', 'le goûter', 'le dîner'],
    mode: 'chrono',
    ex: 'Petit-déjeuner le matin, déjeuner à midi, goûter l’après-midi, dîner le soir.',
  },
  {
    n: 'n',
    id: 'generations-f',
    prompt: 'Range les membres de la famille du plus âgé au plus jeune.',
    el: ['l’arrière-grand-mère', 'la grand-mère', 'la maman', 'l’enfant'],
    mode: 'chrono',
    ex: 'Chaque génération naît après la précédente : arrière-grands-parents, grands-parents, parents, enfants.',
  },
  {
    n: 'n',
    id: 'generations-m',
    prompt: 'Range les membres de la famille du plus âgé au plus jeune.',
    el: ['l’arrière-grand-père', 'le grand-père', 'le papa', 'le fils'],
    mode: 'chrono',
    ex: 'L’arrière-grand-père est le papa du grand-père, qui est le papa du papa.',
  },
  {
    n: 'n',
    id: 'ages-vie',
    prompt: 'Range les âges de la vie, du plus jeune au plus âgé.',
    el: ['le bébé', 'l’enfant', 'l’adolescent', 'l’adulte', 'la personne âgée'],
    mode: 'chrono',
    ex: 'Bébé, enfant, adolescent, adulte, personne âgée : on grandit puis on vieillit.',
  },
  {
    n: 'n',
    id: 'cinq-jours',
    prompt: 'Range du plus ancien au plus lointain dans le futur.',
    el: ['avant-hier', 'hier', 'aujourd’hui', 'demain', 'après-demain'],
    mode: 'chrono',
    ex: 'Avant-hier, hier, aujourd’hui, demain, après-demain.',
  },
  {
    n: 'n',
    id: 'journee-ecole',
    prompt: 'Remets la journée d’école dans l’ordre.',
    el: [
      'l’arrivée à l’école',
      'la récréation du matin',
      'le repas de midi',
      'la classe de l’après-midi',
      'la sortie de l’école',
    ],
    mode: 'chrono',
    ex: 'Le matin on arrive, puis vient la récréation ; à midi on mange, l’après-midi on travaille, puis on sort.',
  },
  {
    n: 'n',
    id: 'ma-vie',
    prompt: 'Range les moments de ta vie, du plus ancien au plus récent.',
    el: [
      'ta naissance',
      'tes premiers pas',
      'ton entrée à l’école maternelle',
      'ton entrée au CP',
      'ton année de CE1',
    ],
    labels: ['0 an', 'vers 1 an', 'vers 3 ans', '6 ans', '7 ans'],
    mode: 'chrono',
    ex: 'D’abord ta naissance, puis tes premiers pas vers 1 an, l’école maternelle vers 3 ans, le CP à 6 ans et le CE1 à 7 ans.',
  },
  {
    n: 'n',
    id: 'moments',
    prompt: 'Range ces moments de la journée dans l’ordre.',
    el: ['le matin', 'midi', 'l’après-midi', 'le soir', 'la nuit'],
    mode: 'chrono',
    ex: 'Matin, midi, après-midi, soir, puis la nuit.',
  },
  ...FRISES_OBJETS,
  {
    n: 'p',
    id: 'naissances',
    prompt: 'Range ces naissances de la plus ancienne à la plus récente.',
    el: ['Mamie', 'Maman', 'Lou'],
    labels: ['1960', '1990', '2019'],
    mode: 'chrono',
    ex: 'Mamie est née en 1960, avant Maman (1990), qui est née avant Lou (2019).',
  },
];

const FRISE_QCM: Q[] = [
  {
    n: 'f',
    id: 'avant-dejeuner',
    q: 'Quel repas vient avant le déjeuner ?',
    ok: 'le petit-déjeuner',
    ko: ['le goûter', 'le dîner'],
    ex: 'Le petit-déjeuner, le matin, vient avant le déjeuner de midi.',
  },
  {
    n: 'f',
    id: 'hier',
    q: 'Quel mot veut dire « le jour avant aujourd’hui » ?',
    ok: 'hier',
    ko: ['demain', 'après-demain'],
    ex: 'Hier, c’est le jour d’avant ; demain, c’est le jour d’après.',
  },
  {
    n: 'f',
    id: 'demain',
    q: 'Quel mot veut dire « le jour après aujourd’hui » ?',
    ok: 'demain',
    ko: ['hier', 'avant-hier'],
    ex: 'Demain, c’est le jour qui vient après aujourd’hui.',
  },
  {
    n: 'f',
    id: 'plus-age',
    q: 'Qui est le plus âgé ?',
    ok: 'le grand-père',
    ko: ['le papa', 'le bébé'],
    img: '👴',
    ex: 'Le grand-père est né avant le papa, qui est né avant le bébé.',
  },
  {
    n: 'n',
    id: 'papa-maman',
    q: 'Le papa de ta maman est ton…',
    ok: 'grand-père',
    ko: ['oncle', 'frère', 'cousin'],
    img: '👴',
    ex: 'Les parents de tes parents sont tes grands-parents.',
  },
  {
    n: 'n',
    id: 'maman-papa',
    q: 'La maman de ton papa est ta…',
    ok: 'grand-mère',
    ko: ['tante', 'sœur', 'cousine'],
    img: '👵',
    ex: 'La maman de ton papa ou de ta maman est ta grand-mère.',
  },
  {
    n: 'n',
    id: 'arriere',
    q: 'Les parents de tes grands-parents sont tes…',
    ok: 'arrière-grands-parents',
    ko: ['oncles et tantes', 'cousins', 'petits-enfants'],
    ex: 'En remontant le temps : parents, grands-parents, puis arrière-grands-parents.',
  },
  {
    n: 'n',
    id: 'oncle',
    q: 'Le frère de ta maman est ton…',
    ok: 'oncle',
    ko: ['grand-père', 'cousin', 'neveu'],
    ex: 'Le frère de ton papa ou de ta maman est ton oncle ; sa sœur est ta tante.',
  },
  {
    n: 'n',
    id: 'frise-debut',
    q: 'Sur une frise chronologique, où place-t-on les évènements les plus anciens ?',
    ok: 'au début, à gauche',
    ko: ['à la fin, à droite', 'au milieu', 'n’importe où'],
    ex: 'Une frise se lit de gauche à droite : du plus ancien au plus récent.',
  },
  {
    n: 'n',
    id: 'premier-vie',
    q: 'Quel évènement s’est passé en premier dans ta vie ?',
    ok: 'ta naissance',
    ko: ['tes premiers pas', 'ton entrée au CP', 'ton entrée en maternelle'],
    ex: 'Tout commence par ta naissance ; les autres évènements viennent après.',
  },
  {
    n: 'n',
    id: 'avant-hier',
    q: 'Aujourd’hui, c’est jeudi. Quel jour était-ce avant-hier ?',
    ok: 'mardi',
    ko: ['mercredi', 'samedi', 'vendredi'],
    ex: 'Hier, c’était mercredi ; avant-hier, c’était mardi.',
  },
  {
    n: 'p',
    id: 'nee-premier',
    q: 'Mamie est née en 1960, Maman en 1990 et Lou en 2019. Qui est née en premier ?',
    ok: 'Mamie',
    ko: ['Maman', 'Lou'],
    ex: '1960 est la date la plus ancienne : Mamie est née la première.',
  },
  {
    n: 'p',
    id: 'frise-2019',
    q: 'Sur une frise, où place-t-on 2019 par rapport à 1990 ?',
    ok: 'après 1990, plus à droite',
    ko: ['avant 1990, plus à gauche', 'au même endroit que 1990'],
    ex: '2019 est plus récent que 1990 : il se place plus loin à droite.',
  },
  {
    n: 'p',
    id: 'age-lou',
    q: 'Lou est née en 2019. Quel âge a-t-elle à son anniversaire de 2026 ?',
    ok: '7 ans',
    ko: ['6 ans', '8 ans', '9 ans'],
    ex: 'De 2019 à 2026, il y a 7 ans : Lou a 7 ans.',
  },
  {
    n: 'p',
    id: 'generation',
    q: 'Toi, tes frères, tes sœurs et tes cousins, vous êtes de la même…',
    ok: 'génération',
    ko: ['saison', 'semaine', 'frise'],
    ex: 'Les enfants nés à peu près à la même époque dans une famille forment une génération.',
  },
  {
    n: 'n',
    id: 'qui-grand-pere',
    q: 'Qui suis-je ?',
    ok: 'le grand-père',
    ko: ['l’oncle', 'le cousin', 'le frère'],
    img: '👴',
    hints: [
      'Je fais partie de ta famille.',
      'Je suis plus âgé que tes parents.',
      'Je suis un homme.',
      'Je suis le papa de ton papa ou de ta maman.',
    ],
    ex: 'Le grand-père est le papa d’un de tes parents.',
  },
  {
    n: 'n',
    id: 'qui-grand-mere',
    q: 'Qui suis-je ?',
    ok: 'la grand-mère',
    ko: ['la tante', 'la cousine', 'la sœur'],
    img: '👵',
    hints: [
      'Je fais partie de ta famille.',
      'J’ai connu tes parents quand ils étaient bébés.',
      'Je suis une femme.',
      'Je suis la maman de ton papa ou de ta maman.',
    ],
    ex: 'La grand-mère est la maman d’un de tes parents.',
  },
  {
    n: 'n',
    id: 'qui-frise',
    q: 'Qui suis-je ?',
    ok: 'la frise chronologique',
    ko: ['le calendrier', 'l’horloge', 'la carte'],
    img: '➡️',
    hints: [
      'Je suis une longue bande.',
      'On me lit de gauche à droite.',
      'Les évènements anciens sont au début, les récents à la fin.',
      'Je sers à ranger les évènements dans l’ordre du temps.',
    ],
    ex: 'La frise chronologique range les évènements du plus ancien au plus récent.',
  },
  {
    n: 'f',
    id: 'qui-demain',
    q: 'Qui suis-je ?',
    ok: 'demain',
    ko: ['hier', 'aujourd’hui', 'avant-hier'],
    img: '🌅',
    hints: [
      'Je suis un jour.',
      'Je ne suis pas encore arrivé.',
      'Je viens juste après aujourd’hui.',
      'Pour se quitter jusqu’au jour suivant, on dit : « À … ! »',
    ],
    ex: 'Demain, c’est le jour qui suit aujourd’hui : « À demain ! »',
  },
];

const FRISE_VF: VF[] = [
  {
    n: 'f',
    id: 'hier-avant',
    s: 'Hier vient avant aujourd’hui.',
    v: true,
    ex: 'Hier est passé : il vient avant aujourd’hui.',
  },
  {
    n: 'f',
    id: 'demain-avant',
    s: 'Demain, c’est le jour d’avant.',
    v: false,
    ex: 'Demain, c’est le jour d’après ; le jour d’avant, c’est hier.',
  },
  {
    n: 'f',
    id: 'bebe-papa',
    s: 'Un bébé est plus âgé que son papa.',
    v: false,
    ex: 'Le papa est né bien avant son bébé : il est plus âgé.',
  },
  {
    n: 'f',
    id: 'soir-matin',
    s: 'Le soir vient après le matin.',
    v: true,
    ex: 'Matin, après-midi, puis soir.',
  },
  {
    n: 'f',
    id: 'gouter',
    s: 'On prend le goûter avant le petit-déjeuner.',
    v: false,
    ex: 'Le petit-déjeuner est le matin ; le goûter, l’après-midi.',
  },
  {
    n: 'n',
    id: 'grand-pere',
    s: 'Le papa de mon papa est mon grand-père.',
    v: true,
    ex: 'Les parents de mes parents sont mes grands-parents.',
  },
  {
    n: 'n',
    id: 'arriere',
    s: 'Mes arrière-grands-parents sont nés avant mes grands-parents.',
    v: true,
    ex: 'Ce sont les parents de mes grands-parents : ils sont nés avant eux.',
  },
  {
    n: 'n',
    id: 'frise-recent',
    s: 'Sur une frise, le plus récent est placé au début.',
    v: false,
    ex: 'Le plus ancien est au début (à gauche), le plus récent à la fin (à droite).',
  },
  {
    n: 'n',
    id: 'tante',
    s: 'La sœur de ma maman est ma tante.',
    v: true,
    ex: 'La sœur d’un de mes parents est ma tante ; son frère est mon oncle.',
  },
  {
    n: 'n',
    id: 'grands-enfants',
    s: 'Mes grands-parents ont été des enfants, bien avant moi.',
    v: true,
    ex: 'Tout le monde a été enfant : mes grands-parents l’ont été il y a longtemps.',
  },
  {
    n: 'n',
    id: 'cousin-frere',
    s: 'Mon cousin est le fils de mes parents.',
    v: false,
    ex: 'Le fils de mes parents est mon frère ; mon cousin est le fils de mon oncle ou de ma tante.',
  },
  {
    n: 'p',
    id: '1960-1990',
    s: 'Une personne née en 1960 est plus âgée qu’une personne née en 1990.',
    v: true,
    ex: 'Elle est née 30 ans plus tôt : elle est plus âgée.',
  },
  {
    n: 'p',
    id: '2001-1999',
    s: 'Sur une frise, 2001 se place avant 1999.',
    v: false,
    ex: '1999 est plus ancien que 2001 : il se place avant.',
  },
  {
    n: 'p',
    id: 'mamie-bebe',
    s: 'Ma grand-mère a été un bébé, elle aussi.',
    v: true,
    ex: 'Tout le monde a été bébé, il y a plus ou moins longtemps.',
  },
  {
    n: 'p',
    id: 'generation-ans',
    s: 'Entre les parents et leurs enfants, il y a souvent 25 à 35 ans d’écart.',
    v: true,
    ex: 'C’est à peu près l’écart entre deux générations.',
  },
];

const FRISE_TRIS: Record<'facile' | 'normal' | 'plus_loin', Tri[]> = {
  facile: [
    {
      id: 'passe-futur',
      prompt: 'C’est déjà passé ou ça va arriver ?',
      categories: ['le passé', 'le futur'],
      elements: [
        { label: 'hier', c: 'le passé', n: 'f' },
        { label: 'la semaine dernière', c: 'le passé', n: 'f' },
        { label: 'quand j’étais bébé', c: 'le passé', n: 'f', img: '👶' },
        { label: 'l’année dernière', c: 'le passé', n: 'f' },
        { label: 'demain', c: 'le futur', n: 'f' },
        { label: 'la semaine prochaine', c: 'le futur', n: 'f' },
        { label: 'quand je serai grand', c: 'le futur', n: 'f' },
        { label: 'l’année prochaine', c: 'le futur', n: 'f' },
      ],
      ex: 'Le passé, c’est avant maintenant ; le futur, c’est après.',
    },
  ],
  normal: [
    {
      id: 'passe-present-futur',
      prompt: 'Passé, présent ou futur ?',
      categories: ['le passé', 'le présent', 'le futur'],
      elements: [
        { label: 'hier', c: 'le passé', n: 'n' },
        { label: 'autrefois', c: 'le passé', n: 'n' },
        { label: 'l’année dernière', c: 'le passé', n: 'n' },
        { label: 'quand j’étais bébé', c: 'le passé', n: 'n', img: '👶' },
        { label: 'aujourd’hui', c: 'le présent', n: 'n' },
        { label: 'maintenant', c: 'le présent', n: 'n' },
        { label: 'en ce moment', c: 'le présent', n: 'n' },
        { label: 'demain', c: 'le futur', n: 'n' },
        { label: 'plus tard', c: 'le futur', n: 'n' },
        { label: 'l’année prochaine', c: 'le futur', n: 'n' },
      ],
      ex: 'Le passé est déjà arrivé, le présent c’est maintenant, le futur va arriver.',
      nb: 7,
    },
  ],
  plus_loin: [
    {
      id: 'generations',
      prompt: 'Range chaque personne dans sa génération.',
      categories: ['ma génération', 'la génération de mes parents', 'la génération de mes grands-parents'],
      elements: [
        { label: 'moi', c: 'ma génération', n: 'p' },
        { label: 'ma sœur', c: 'ma génération', n: 'p' },
        { label: 'mon cousin', c: 'ma génération', n: 'p' },
        { label: 'ma maman', c: 'la génération de mes parents', n: 'p' },
        { label: 'mon oncle', c: 'la génération de mes parents', n: 'p' },
        { label: 'ma tante', c: 'la génération de mes parents', n: 'p' },
        { label: 'mon grand-père', c: 'la génération de mes grands-parents', n: 'p', img: '👴' },
        { label: 'ma grand-mère', c: 'la génération de mes grands-parents', n: 'p', img: '👵' },
      ],
      ex: 'Une génération, ce sont les personnes d’une famille nées à peu près à la même époque.',
      nb: 7,
    },
  ],
};

const FRISE_PAIRES: Record<'facile' | 'normal' | 'plus_loin', Appariement[]> = {
  facile: [
    {
      id: 'repas',
      prompt: 'Associe chaque repas au moment de la journée.',
      relation: 'repas → moment',
      duos: [
        { l: 'le petit-déjeuner', r: 'le matin', n: 'f' },
        { l: 'le déjeuner', r: 'midi', n: 'f' },
        { l: 'le goûter', r: 'l’après-midi', n: 'f' },
        { l: 'le dîner', r: 'le soir', n: 'f' },
      ],
      ex: 'Petit-déjeuner le matin, déjeuner à midi, goûter l’après-midi, dîner le soir.',
      nb: 4,
    },
  ],
  normal: [
    {
      id: 'famille',
      prompt: 'Associe chaque description au bon membre de la famille.',
      relation: 'description → parent',
      duos: [
        { l: 'le papa de ma maman', r: 'mon grand-père', n: 'n' },
        { l: 'la maman de mon papa', r: 'ma grand-mère', n: 'n' },
        { l: 'la sœur de mon papa', r: 'ma tante', n: 'n' },
        { l: 'le frère de ma maman', r: 'mon oncle', n: 'n' },
        { l: 'le fils de mon oncle', r: 'mon cousin', n: 'n' },
        { l: 'la fille de ma tante', r: 'ma cousine', n: 'n' },
        { l: 'la mère de ma grand-mère', r: 'mon arrière-grand-mère', n: 'n' },
      ],
      ex: 'Les parents de mes parents sont mes grands-parents ; leurs frères et sœurs sont mes oncles et tantes.',
      nb: 5,
    },
  ],
  plus_loin: [
    {
      id: 'famille',
      prompt: 'Associe chaque description au bon membre de la famille.',
      relation: 'description → parent',
      duos: [
        { l: 'le papa de ma maman', r: 'mon grand-père', n: 'p' },
        { l: 'la maman de mon papa', r: 'ma grand-mère', n: 'p' },
        { l: 'la sœur de mon papa', r: 'ma tante', n: 'p' },
        { l: 'le frère de ma maman', r: 'mon oncle', n: 'p' },
        { l: 'le fils de mon oncle', r: 'mon cousin', n: 'p' },
        { l: 'la fille de ma tante', r: 'ma cousine', n: 'p' },
        { l: 'la mère de ma grand-mère', r: 'mon arrière-grand-mère', n: 'p' },
        { l: 'le père de mon grand-père', r: 'mon arrière-grand-père', n: 'p' },
      ],
      ex: 'Les parents de mes grands-parents sont mes arrière-grands-parents.',
      nb: 6,
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Autrefois                                                           */
/* ------------------------------------------------------------------ */

const AUT_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'ecole',
    prompt: 'Range ces objets pour écrire, du plus ancien au plus récent.',
    el: ['le porte-plume et l’encrier', 'le stylo à bille', 'la tablette numérique'],
    labels: ['autrefois', 'au temps de tes grands-parents', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'À l’école d’autrefois, on trempait sa plume dans l’encre ; le stylo à bille est venu ensuite, puis la tablette.',
  },
  {
    n: 'f',
    id: 'lumiere-3',
    prompt: 'Range ces objets pour s’éclairer, du plus ancien au plus récent.',
    el: ['la bougie', 'l’ampoule électrique', 'la lampe à LED'],
    labels: ['autrefois', 'il y a environ 100 ans', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'La bougie est très ancienne ; l’ampoule électrique est plus récente et la lampe à LED est d’aujourd’hui.',
  },
  {
    n: 'f',
    id: 'transport-3',
    prompt: 'Range ces moyens de transport, du plus ancien au plus récent.',
    el: ['la charrette à cheval', 'le train à vapeur', 'le TGV'],
    labels: ['autrefois', 'il y a environ 150 ans', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'Le cheval tirait les charrettes, puis le train à vapeur est arrivé ; le TGV est récent.',
  },
  {
    n: 'n',
    id: 'chauffage',
    prompt: 'Range ces façons de chauffer la maison, de la plus ancienne à la plus récente.',
    el: ['le feu dans la cheminée', 'le poêle à charbon', 'le chauffage central'],
    labels: ['il y a très longtemps', 'vers 1900', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'On se chauffait au feu de bois, puis avec un poêle à charbon ; aujourd’hui, des radiateurs chauffent toutes les pièces.',
  },
  {
    n: 'n',
    id: 'linge',
    prompt: 'Range ces façons de laver le linge, de la plus ancienne à la plus récente.',
    el: ['au bord de la rivière', 'au lavoir du village', 'dans la machine à laver'],
    labels: ['il y a très longtemps', 'autrefois', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'On lavait le linge à la main, à la rivière puis au lavoir ; la machine à laver est arrivée dans les maisons bien plus tard.',
  },
  {
    n: 'n',
    id: 'photo',
    prompt: 'Range ces objets, du plus ancien au plus récent.',
    el: ['le portrait peint', 'la photo en noir et blanc', 'la photo prise avec un téléphone'],
    labels: ['il y a très longtemps', 'autrefois', 'aujourd’hui'],
    mode: 'chrono',
    ex: 'Avant la photographie, on faisait peindre son portrait ; les premières photos étaient en noir et blanc.',
  },
  ...FRISES_OBJETS.map((o) => ({ ...o, n: 'n' as const, labels: undefined, id: `${o.id}-sans-date` })),
  ...FRISES_OBJETS,
];

const AUT_QCM: Q[] = [
  {
    n: 'n',
    id: 'chauffer',
    q: 'Il y a très longtemps, comment chauffait-on la maison ?',
    ok: 'avec un feu de bois',
    ko: ['avec une pompe à chaleur', 'avec un radiateur électrique', 'avec des panneaux solaires'],
    ex: 'Autrefois, on se chauffait avec un feu de bois dans la cheminée, puis avec des poêles à bois ou à charbon.',
  },
  {
    n: 'n',
    id: 'blouse',
    q: 'À l’école d’autrefois, que portaient souvent les élèves par-dessus leurs vêtements ?',
    ok: 'une blouse',
    ko: ['un casque', 'un maillot de bain', 'une combinaison de ski'],
    ex: 'Les élèves portaient une blouse pour protéger leurs vêtements de l’encre.',
  },
  {
    n: 'n',
    id: 'pupitre',
    q: 'Dans la classe d’autrefois, où s’asseyaient les élèves ?',
    ok: 'à des pupitres en bois',
    ko: ['sur des ballons', 'sur des canapés', 'par terre sur des coussins'],
    ex: 'Les élèves s’asseyaient à des pupitres en bois, avec un trou pour l’encrier.',
  },
  {
    n: 'f',
    id: 'message',
    q: 'Quel objet d’aujourd’hui permet d’envoyer un message très vite ?',
    ok: 'le téléphone portable',
    ko: ['la plume d’oie', 'la charrette'],
    img: '📱',
    ex: 'Aujourd’hui, un message envoyé avec un téléphone arrive en quelques secondes.',
  },
  {
    n: 'p',
    id: 'ampoule',
    q: 'Vers quelle époque l’ampoule électrique a-t-elle été inventée ?',
    ok: 'vers 1880',
    ko: ['vers 1500', 'vers 1980', 'vers 2010'],
    img: '💡',
    ex: 'L’ampoule électrique a été mise au point vers 1880.',
  },
  {
    n: 'p',
    id: 'avion',
    q: 'Le premier avion a volé…',
    ok: 'vers 1900',
    ko: ['vers 1500', 'vers 1800', 'vers 2000'],
    img: '✈️',
    ex: 'Les premiers avions ont volé au tout début des années 1900.',
  },
  {
    n: 'p',
    id: 'portable-grands-parents',
    q: 'Quand tes grands-parents étaient enfants, avaient-ils un téléphone portable ?',
    ok: 'non, cela n’existait pas encore',
    ko: ['oui, tous les enfants en avaient un', 'oui, mais seulement le dimanche'],
    ex: 'Les téléphones portables sont arrivés dans les familles il y a environ 30 ans.',
  },
  {
    n: 'n',
    id: 'qui-lavoir',
    q: 'Qui suis-je ?',
    ok: 'le lavoir',
    ko: ['la fontaine', 'la piscine', 'le puits'],
    img: '🧺',
    hints: [
      'Je suis un lieu du village d’autrefois.',
      'On venait me voir avec de gros paniers de linge.',
      'J’ai un grand bassin rempli d’eau, souvent sous un toit.',
      'On y lavait le linge à la main, avant la machine à laver.',
    ],
    ex: 'Le lavoir servait à laver le linge à la main, avant l’arrivée des machines à laver.',
  },
  {
    n: 'n',
    id: 'qui-porte-plume',
    q: 'Qui suis-je ?',
    ok: 'le porte-plume',
    ko: ['le crayon de couleur', 'la craie', 'le feutre'],
    img: '✒️',
    hints: [
      'Je servais à l’école d’autrefois.',
      'On me trempait dans un petit pot d’encre.',
      'Il fallait faire attention aux taches !',
      'On écrivait avec moi avant le stylo à bille.',
    ],
    ex: 'Le porte-plume a une plume en métal qu’on trempe dans l’encrier.',
  },
  {
    n: 'n',
    id: 'qui-cadran',
    q: 'Qui suis-je ?',
    ok: 'le téléphone à cadran',
    ko: ['la radio', 'la télévision', 'le tourne-disque'],
    img: '☎️',
    hints: [
      'J’étais dans la maison de tes grands-parents.',
      'J’étais relié au mur par un fil.',
      'On ne pouvait pas m’emporter dehors.',
      'Pour appeler, on tournait ma roue percée de trous avec un doigt.',
    ],
    ex: 'Le téléphone à cadran était fixe : on composait le numéro en tournant le cadran.',
  },
  {
    n: 'n',
    id: 'qui-locomotive',
    q: 'Qui suis-je ?',
    ok: 'la locomotive à vapeur',
    ko: ['le TGV', 'le tramway', 'l’autocar'],
    img: '🚂',
    hints: [
      'Je roule sur des rails.',
      'Je fais beaucoup de fumée.',
      'On me remplit de charbon pour chauffer l’eau.',
      'Je tirais les wagons des trains d’autrefois.',
    ],
    ex: 'La locomotive à vapeur brûlait du charbon pour faire de la vapeur qui la faisait avancer.',
  },
  {
    n: 'f',
    id: 'qui-bougie',
    q: 'Qui suis-je ?',
    ok: 'la bougie',
    ko: ['l’ampoule', 'la lampe de poche', 'la lampe à pétrole'],
    img: '🕯️',
    hints: [
      'Je donne de la lumière.',
      'Je suis faite de cire.',
      'Autrefois, on m’utilisait tous les soirs.',
      'On m’allume avec une allumette et j’ai une petite flamme.',
    ],
    ex: 'Avant l’électricité, on s’éclairait avec des bougies en cire.',
  },
];

const AUT_VF: VF[] = [
  {
    n: 'f',
    id: 'portable',
    s: 'Il y a très longtemps, il n’y avait pas de téléphone portable.',
    v: true,
    ex: 'Les téléphones portables sont récents.',
  },
  {
    n: 'f',
    id: 'bougie',
    s: 'La bougie est plus récente que l’ampoule électrique.',
    v: false,
    ex: 'La bougie est bien plus ancienne que l’ampoule électrique.',
  },
  {
    n: 'f',
    id: 'cheval',
    s: 'Autrefois, on se déplaçait souvent à cheval.',
    v: true,
    ex: 'Avant les voitures, on voyageait à cheval ou en charrette.',
  },
  {
    n: 'f',
    id: 'tablette',
    s: 'La tablette numérique existait déjà il y a très longtemps.',
    v: false,
    ex: 'La tablette numérique est un objet d’aujourd’hui.',
  },
  {
    n: 'n',
    id: 'lavoir',
    s: 'Autrefois, on lavait le linge à la main, au lavoir.',
    v: true,
    ex: 'Avant la machine à laver, on lavait le linge à la main.',
  },
  {
    n: 'n',
    id: 'plume',
    s: 'À l’école d’autrefois, on écrivait avec une plume et de l’encre.',
    v: true,
    ex: 'On trempait sa plume dans l’encrier.',
  },
  {
    n: 'n',
    id: 'voitures',
    s: 'Les voitures existaient avant les charrettes.',
    v: false,
    ex: 'Les charrettes tirées par des chevaux sont bien plus anciennes que les voitures.',
  },
  {
    n: 'n',
    id: 'dessins-animes',
    s: 'Les arrière-grands-parents de tes parents regardaient des dessins animés sur une tablette.',
    v: false,
    ex: 'Les tablettes n’existaient pas à leur époque.',
  },
  {
    n: 'n',
    id: 'charbon',
    s: 'Autrefois, beaucoup de maisons étaient chauffées au bois ou au charbon.',
    v: true,
    ex: 'On brûlait du bois ou du charbon dans la cheminée ou le poêle.',
  },
  {
    n: 'p',
    id: 'avion-train',
    s: 'L’avion a été inventé après le train.',
    v: true,
    ex: 'Le train à vapeur date d’environ 1830, l’avion d’environ 1900.',
  },
  {
    n: 'p',
    id: 'tele-couleur',
    s: 'La télévision en couleurs existe en France depuis plus de 100 ans.',
    v: false,
    ex: 'La télévision en couleurs est arrivée en France il y a environ 60 ans.',
  },
  {
    n: 'p',
    id: 'portable-30',
    s: 'Le téléphone portable est arrivé dans les familles il y a environ 30 ans.',
    v: true,
    ex: 'Les téléphones portables se sont répandus il y a environ 30 ans.',
  },
];

const A = 'autrefois';
const J = 'aujourd’hui';
const AUT_TRIS: Record<'facile' | 'normal' | 'plus_loin', Tri[]> = {
  facile: [
    {
      id: 'autrefois-aujourdhui',
      prompt: 'Cet objet est-il d’autrefois ou d’aujourd’hui ?',
      categories: [A, J],
      elements: [
        { label: 'la bougie', c: A, n: 'f', img: '🕯️' },
        { label: 'la plume et l’encrier', c: A, n: 'f', img: '✒️' },
        { label: 'la charrette à cheval', c: A, n: 'f', img: '🐎' },
        { label: 'la locomotive à vapeur', c: A, n: 'f', img: '🚂' },
        { label: 'le téléphone portable', c: J, n: 'f', img: '📱' },
        { label: 'l’ordinateur portable', c: J, n: 'f', img: '💻' },
        { label: 'la trottinette électrique', c: J, n: 'f', img: '🛴' },
        { label: 'la tablette numérique', c: J, n: 'f' },
      ],
      ex: 'Les objets d’autrefois fonctionnaient souvent sans électricité ; ceux d’aujourd’hui sont souvent électriques ou numériques.',
    },
  ],
  normal: [
    {
      id: 'autrefois-aujourdhui',
      prompt: 'Cet objet est-il d’autrefois ou d’aujourd’hui ?',
      categories: [A, J],
      elements: [
        { label: 'la bougie', c: A, n: 'n', img: '🕯️' },
        { label: 'le porte-plume', c: A, n: 'n', img: '✒️' },
        { label: 'la charrette à cheval', c: A, n: 'n', img: '🐎' },
        { label: 'le téléphone à cadran', c: A, n: 'n', img: '☎️' },
        { label: 'le lavoir', c: A, n: 'n', img: '🧺' },
        { label: 'le poêle à charbon', c: A, n: 'n' },
        { label: 'la cassette vidéo', c: A, n: 'n', img: '📼' },
        { label: 'le téléphone portable', c: J, n: 'n', img: '📱' },
        { label: 'l’ordinateur portable', c: J, n: 'n', img: '💻' },
        { label: 'la trottinette électrique', c: J, n: 'n', img: '🛴' },
        { label: 'l’aspirateur robot', c: J, n: 'n', img: '🤖' },
        { label: 'la lampe à LED', c: J, n: 'n' },
        { label: 'le TGV', c: J, n: 'n', img: '🚄' },
      ],
      ex: 'Un objet d’autrefois a été remplacé par un objet plus récent qui sert à la même chose.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'trois-epoques',
      prompt: 'À quelle époque cet objet était-il utilisé à la maison ?',
      categories: ['il y a très longtemps', 'au temps de mes grands-parents', 'aujourd’hui'],
      elements: [
        { label: 'la bougie', c: 'il y a très longtemps', n: 'p', img: '🕯️' },
        { label: 'la plume d’oie', c: 'il y a très longtemps', n: 'p', img: '🪶' },
        { label: 'la charrette à cheval', c: 'il y a très longtemps', n: 'p', img: '🐎' },
        { label: 'le lavoir', c: 'il y a très longtemps', n: 'p', img: '🧺' },
        { label: 'le téléphone à cadran', c: 'au temps de mes grands-parents', n: 'p', img: '☎️' },
        { label: 'le tourne-disque', c: 'au temps de mes grands-parents', n: 'p' },
        { label: 'la télévision en noir et blanc', c: 'au temps de mes grands-parents', n: 'p', img: '📺' },
        { label: 'le téléphone portable tactile', c: 'aujourd’hui', n: 'p', img: '📱' },
        { label: 'la tablette numérique', c: 'aujourd’hui', n: 'p' },
        { label: 'la trottinette électrique', c: 'aujourd’hui', n: 'p', img: '🛴' },
      ],
      ex: 'Tes grands-parents, enfants, avaient le téléphone à cadran et la télévision en noir et blanc ; la bougie et le lavoir sont encore plus anciens.',
      nb: 8,
    },
  ],
};

export const TEMPS: ContentModule = {
  'CE1.QLM.TEMPS.CALENDRIER': {
    pools: {
      mcq: qcmPool(CAL_QCM, { guillotine: true }),
      true_false: vfPool(CAL_VF),
      ordering: ordrePool(CAL_ORDRES),
    },
    gens: { classification: triGen(CAL_TRIS), pairing: paireGen(CAL_PAIRES) },
  },
  'CE1.QLM.TEMPS.FRISE': {
    pools: {
      mcq: qcmPool(FRISE_QCM, { guillotine: true }),
      true_false: vfPool(FRISE_VF),
      ordering: ordrePool(FRISE_ORDRES),
    },
    gens: { classification: triGen(FRISE_TRIS), pairing: paireGen(FRISE_PAIRES) },
  },
  'CE1.QLM.TEMPS.AUTREFOIS': {
    pools: {
      mcq: qcmPool(AUT_QCM, { guillotine: true }),
      true_false: vfPool(AUT_VF),
      ordering: ordrePool(AUT_ORDRES),
    },
    gens: { classification: triGen(AUT_TRIS) },
  },
};
