/**
 * Questionner le monde CE1 — « Le vivant » et « Le corps et la santé » (programme 2020, en vigueur
 * en 2026-2027) : vivant / non vivant et besoins des êtres vivants, cycles de vie, régimes alimentaires
 * et chaînes alimentaires, hygiène, sommeil, alimentation équilibrée (ton bienveillant, sans culpabiliser).
 */
import type { ContentModule } from '../../registry';
import type { Level } from '../../schemas';
import {
  type Appariement,
  type Ordre,
  type Q,
  type Tri,
  type VF,
  ordrePool,
  paireGen,
  qcmPool,
  triGen,
  vfPool,
} from './outils';

/* ------------------------------------------------------------------ */
/* Vivant / non vivant, besoins                                        */
/* ------------------------------------------------------------------ */

const VI = 'vivant';
const NV = 'non vivant';
const AN = 'un animal';
const VE = 'un végétal';

const CARACT_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'vivant',
      prompt: 'Vivant ou non vivant ?',
      categories: [VI, NV],
      elements: [
        { label: 'le chat', c: VI, n: 'f', img: '🐈' },
        { label: 'l’arbre', c: VI, n: 'f', img: '🌳' },
        { label: 'la fleur', c: VI, n: 'f', img: '🌷' },
        { label: 'le poisson', c: VI, n: 'f', img: '🐟' },
        { label: 'l’oiseau', c: VI, n: 'f', img: '🐦' },
        { label: 'l’escargot', c: VI, n: 'f', img: '🐌' },
        { label: 'la pierre', c: NV, n: 'f', img: '🪨' },
        { label: 'le vélo', c: NV, n: 'f', img: '🚲' },
        { label: 'la cuillère', c: NV, n: 'f', img: '🥄' },
        { label: 'le ballon', c: NV, n: 'f', img: '⚽' },
        { label: 'la voiture', c: NV, n: 'f', img: '🚗' },
        { label: 'la chaise', c: NV, n: 'f', img: '🪑' },
      ],
      ex: 'Un être vivant naît, grandit, se nourrit, se reproduit et meurt. Un objet, non.',
    },
  ],
  normal: [
    {
      id: 'animal-vegetal',
      prompt: 'Animal, végétal ou non vivant ?',
      categories: [AN, VE, NV],
      elements: [
        { label: 'le chat', c: AN, n: 'n', img: '🐈' },
        { label: 'l’escargot', c: AN, n: 'n', img: '🐌' },
        { label: 'le papillon', c: AN, n: 'n', img: '🦋' },
        { label: 'la poule', c: AN, n: 'n', img: '🐔' },
        { label: 'l’araignée', c: AN, n: 'n', img: '🕷️' },
        { label: 'le ver de terre', c: AN, n: 'n', img: '🪱' },
        { label: 'l’arbre', c: VE, n: 'n', img: '🌳' },
        { label: 'l’herbe', c: VE, n: 'n', img: '🌿' },
        { label: 'le cactus', c: VE, n: 'n', img: '🌵' },
        { label: 'le blé', c: VE, n: 'n', img: '🌾' },
        { label: 'la salade', c: VE, n: 'n', img: '🥬' },
        { label: 'la pierre', c: NV, n: 'n', img: '🪨' },
        { label: 'le robot', c: NV, n: 'n', img: '🤖' },
        { label: 'la peluche', c: NV, n: 'n', img: '🧸' },
        { label: 'le nuage', c: NV, n: 'n', img: '☁️' },
        { label: 'le feu', c: NV, n: 'n', img: '🔥' },
      ],
      ex: 'Les animaux et les végétaux sont vivants. Le robot bouge et le feu grandit, mais ils ne naissent pas et ne se reproduisent pas : ils ne sont pas vivants.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'besoins-plante',
      prompt: 'Une plante en a-t-elle besoin pour vivre ?',
      categories: ['elle en a besoin', 'elle n’en a pas besoin'],
      elements: [
        { label: 'l’eau', c: 'elle en a besoin', n: 'p', img: '💧' },
        { label: 'la lumière', c: 'elle en a besoin', n: 'p', img: '☀️' },
        { label: 'l’air', c: 'elle en a besoin', n: 'p', img: '🌬️' },
        { label: 'les sels minéraux de la terre', c: 'elle en a besoin', n: 'p', img: '🪴' },
        { label: 'la musique', c: 'elle n’en a pas besoin', n: 'p', img: '🎵' },
        { label: 'les bonbons', c: 'elle n’en a pas besoin', n: 'p', img: '🍬' },
        { label: 'le sel de cuisine', c: 'elle n’en a pas besoin', n: 'p', img: '🧂' },
        { label: 'la télévision', c: 'elle n’en a pas besoin', n: 'p', img: '📺' },
      ],
      ex: 'Une plante a besoin d’eau, de lumière, d’air et des sels minéraux du sol pour vivre et grandir.',
      nb: 7,
    },
    {
      id: 'animal-vegetal',
      prompt: 'Animal, végétal ou non vivant ?',
      categories: [AN, VE, NV],
      elements: [
        { label: 'le corail', c: AN, n: 'p', img: '🪸' },
        { label: 'l’éponge de mer', c: AN, n: 'p' },
        { label: 'la méduse', c: AN, n: 'p', img: '🪼' },
        { label: 'la mousse des rochers', c: VE, n: 'p' },
        { label: 'l’algue', c: VE, n: 'p' },
        { label: 'le gland du chêne', c: VE, n: 'p', img: '🌰' },
        { label: 'le sable', c: NV, n: 'p' },
        { label: 'le coquillage vide', c: NV, n: 'p', img: '🐚' },
        { label: 'la vague', c: NV, n: 'p', img: '🌊' },
      ],
      ex: 'Le corail et l’éponge de mer sont des animaux ; l’algue et la mousse sont des végétaux ; un coquillage vide n’est plus vivant.',
      nb: 7,
    },
  ],
};

const CARACT_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'graine-3',
    prompt: 'Remets dans l’ordre : comment pousse une plante ?',
    el: ['la graine', 'la jeune pousse', 'la plante adulte'],
    mode: 'etapes',
    ex: 'La graine germe, donne une jeune pousse qui grandit et devient une plante adulte.',
  },
  {
    n: 'f',
    id: 'chaton-3',
    prompt: 'Remets dans l’ordre la vie du chat.',
    el: ['le chaton naît', 'le chaton grandit', 'le chat est adulte'],
    mode: 'etapes',
    ex: 'Le chaton naît, grandit et devient un chat adulte.',
  },
  {
    n: 'n',
    id: 'vie',
    prompt: 'Remets dans l’ordre la vie d’un être vivant.',
    el: ['il naît', 'il grandit', 'il se reproduit', 'il meurt'],
    mode: 'etapes',
    ex: 'Tous les êtres vivants naissent, grandissent, peuvent se reproduire et meurent un jour.',
  },
  {
    n: 'n',
    id: 'chat',
    prompt: 'Remets dans l’ordre la vie du chat.',
    el: [
      'le chaton naît',
      'il boit le lait de sa mère',
      'il grandit et mange des croquettes',
      'la chatte adulte a des petits',
    ],
    mode: 'etapes',
    ex: 'Le chaton naît, tète sa mère, grandit et, adulte, peut avoir des petits.',
  },
  {
    n: 'n',
    id: 'haricot',
    prompt: 'Remets dans l’ordre la croissance du haricot.',
    el: [
      'la graine dans la terre humide',
      'la racine sort de la graine',
      'la tige et les premières feuilles poussent',
      'la plante grandit',
    ],
    mode: 'etapes',
    ex: 'La graine germe : d’abord la racine, puis la tige et les feuilles.',
  },
  {
    n: 'p',
    id: 'experience-lumiere',
    prompt: 'Une expérience : la plante a-t-elle besoin de lumière ? Remets les étapes dans l’ordre.',
    el: [
      'planter deux haricots pareils',
      'mettre l’un à la lumière, l’autre dans le noir',
      'les arroser de la même façon',
      'observer après deux semaines',
    ],
    mode: 'etapes',
    ex: 'On ne change qu’une chose (la lumière) : la plante restée dans le noir devient pâle et faible.',
  },
  {
    n: 'p',
    id: 'experience-eau',
    prompt: 'Une expérience : la graine a-t-elle besoin d’eau pour germer ? Remets les étapes dans l’ordre.',
    el: [
      'poser des graines sur deux cotons',
      'arroser un seul des deux cotons',
      'attendre quelques jours',
      'comparer : seules les graines arrosées ont germé',
    ],
    mode: 'etapes',
    ex: 'Sans eau, la graine ne germe pas : elle a besoin d’eau pour se réveiller.',
  },
];

const CARACT_QCM: Q[] = [
  {
    n: 'f',
    id: 'pas-vivant',
    q: 'Lequel n’est pas vivant ?',
    ok: 'le ballon',
    ko: ['le chat', 'l’arbre', 'la fleur'],
    ex: 'Le ballon ne naît pas, ne grandit pas et ne se nourrit pas : il n’est pas vivant.',
  },
  {
    n: 'f',
    id: 'vivant',
    q: 'Lequel est vivant ?',
    ok: 'l’escargot',
    ko: ['la pierre', 'le vélo', 'la cuillère'],
    img: '🐌',
    ex: 'L’escargot naît, grandit, se nourrit et se reproduit : il est vivant.',
  },
  {
    n: 'f',
    id: 'arbre',
    q: 'L’arbre est-il vivant ?',
    ok: 'oui, il grandit et se nourrit',
    ko: ['non, il ne bouge pas', 'non, c’est un objet'],
    img: '🌳',
    ex: 'Un arbre ne se déplace pas, mais il naît, grandit, se nourrit et se reproduit : il est vivant.',
  },
  {
    n: 'n',
    id: 'criteres',
    q: 'Que fait un être vivant au cours de sa vie ?',
    ok: 'il naît, grandit, se nourrit, se reproduit et meurt',
    ko: ['il roule et s’use', 'il fond au soleil', 'il ne change jamais'],
    ex: 'Ce sont les caractéristiques de tous les êtres vivants.',
  },
  {
    n: 'n',
    id: 'besoins-plante',
    q: 'De quoi une plante a-t-elle besoin pour vivre ?',
    ok: 'd’eau, de lumière et d’air',
    ko: ['de chocolat', 'de musique', 'de bruit'],
    img: '🌱',
    ex: 'Une plante a besoin d’eau, de lumière, d’air et des sels minéraux de la terre.',
  },
  {
    n: 'n',
    id: 'besoins-animal',
    q: 'De quoi un animal a-t-il besoin pour vivre ?',
    ok: 'd’eau, de nourriture et d’air',
    ko: ['d’un écran', 'de jouets', 'de vêtements'],
    ex: 'Tous les animaux ont besoin de respirer, de boire et de manger.',
  },
  {
    n: 'n',
    id: 'robot',
    q: 'Le robot bouge et parle. Est-il vivant ?',
    ok: 'non : il ne naît pas, ne grandit pas et ne se reproduit pas',
    ko: ['oui, car il bouge', 'oui, car il parle'],
    img: '🤖',
    ex: 'Bouger ne suffit pas : le robot est un objet fabriqué.',
  },
  {
    n: 'n',
    id: 'feu',
    q: 'Le feu grandit et bouge. Est-il vivant ?',
    ok: 'non, il ne naît pas et ne se reproduit pas comme un être vivant',
    ko: ['oui, car il grandit', 'oui, car il a besoin d’air'],
    img: '🔥',
    ex: 'Le feu n’est pas vivant : il ne naît pas d’un parent et ne se reproduit pas.',
  },
  {
    n: 'p',
    id: 'bois',
    q: 'Le bois de la table vient d’un être vivant. Lequel ?',
    ok: 'un arbre',
    ko: ['un animal', 'un rocher', 'un nuage'],
    img: '🪵',
    ex: 'Le bois vient des arbres : il a été vivant, mais la table ne l’est pas.',
  },
  {
    n: 'p',
    id: 'graine',
    q: 'Une graine est-elle vivante ?',
    ok: 'oui, elle peut germer et donner une plante',
    ko: ['non, elle ne bouge pas', 'non, c’est un caillou'],
    img: '🌱',
    ex: 'La graine est vivante : elle « dort » jusqu’à ce qu’elle ait de l’eau pour germer.',
  },
  {
    n: 'p',
    id: 'lumiere-noir',
    q: 'Une plante reste dans le noir pendant deux semaines. Que se passe-t-il ?',
    ok: 'elle devient pâle et faible',
    ko: ['elle devient plus verte', 'rien du tout', 'elle se met à fleurir'],
    ex: 'Sans lumière, une plante ne peut pas bien se nourrir : elle s’affaiblit.',
  },
  {
    n: 'n',
    id: 'qui-arbre',
    q: 'Qui suis-je ?',
    ok: 'l’arbre',
    ko: ['la fleur', 'le rocher', 'le champignon'],
    img: '🌳',
    hints: [
      'Je suis un être vivant.',
      'Je ne peux pas me déplacer.',
      'J’ai un tronc, des branches et des racines.',
      'En automne, beaucoup d’entre nous perdent leurs feuilles.',
    ],
    ex: 'L’arbre est un végétal : il est vivant même s’il ne se déplace pas.',
  },
  {
    n: 'n',
    id: 'qui-graine',
    q: 'Qui suis-je ?',
    ok: 'la graine',
    ko: ['le caillou', 'la perle', 'la bille'],
    img: '🌱',
    hints: [
      'Je suis toute petite.',
      'Je suis vivante, même si je ne bouge pas.',
      'Si on me plante et qu’on m’arrose, je germe.',
      'Je deviens une nouvelle plante.',
    ],
    ex: 'La graine contient une petite plante qui attend l’eau pour germer.',
  },
  {
    n: 'n',
    id: 'qui-ver',
    q: 'Qui suis-je ?',
    ok: 'le ver de terre',
    ko: ['le serpent', 'la chenille', 'l’escargot'],
    img: '🪱',
    hints: [
      'Je suis un animal.',
      'Je n’ai pas de pattes.',
      'Je vis dans la terre.',
      'Je creuse des galeries qui aèrent la terre du jardin.',
    ],
    ex: 'Le ver de terre est un animal utile : il rend la terre meilleure pour les plantes.',
  },
  {
    n: 'n',
    id: 'qui-champignon',
    q: 'Qui suis-je ?',
    ok: 'le champignon',
    ko: ['la fleur', 'la pomme de pin', 'la feuille'],
    img: '🍄',
    hints: [
      'Je suis vivant.',
      'Je ne suis ni un animal ni une plante verte.',
      'Je pousse souvent en automne, dans les bois.',
      'Certains se mangent, d’autres sont très dangereux : ne me cueille jamais seul !',
    ],
    ex: 'Le champignon est un être vivant ; on ne le cueille jamais sans un adulte qui le connaît bien.',
  },
];

const CARACT_VF: VF[] = [
  {
    n: 'f',
    id: 'arbre',
    s: 'Un arbre est un être vivant.',
    v: true,
    img: '🌳',
    ex: 'Il naît, grandit, se nourrit et se reproduit.',
  },
  {
    n: 'f',
    id: 'pierre',
    s: 'Une pierre grandit.',
    v: false,
    img: '🪨',
    ex: 'Une pierre n’est pas vivante : elle ne grandit pas.',
  },
  {
    n: 'f',
    id: 'peluche',
    s: 'Une peluche est un être vivant.',
    v: false,
    img: '🧸',
    ex: 'La peluche est un jouet : elle ne naît pas et ne se nourrit pas.',
  },
  {
    n: 'f',
    id: 'chat',
    s: 'Le chat est un être vivant.',
    v: true,
    img: '🐈',
    ex: 'Le chat naît, grandit, se nourrit, se reproduit et meurt.',
  },
  {
    n: 'n',
    id: 'robot',
    s: 'Le robot est vivant parce qu’il bouge.',
    v: false,
    img: '🤖',
    ex: 'Bouger ne suffit pas : le robot ne naît pas, ne grandit pas et ne se reproduit pas.',
  },
  {
    n: 'n',
    id: 'lumiere',
    s: 'Les plantes ont besoin de lumière pour vivre.',
    v: true,
    ex: 'Sans lumière, une plante s’affaiblit.',
  },
  {
    n: 'n',
    id: 'mourir',
    s: 'Tous les êtres vivants meurent un jour.',
    v: true,
    ex: 'C’est une caractéristique de tous les êtres vivants.',
  },
  {
    n: 'n',
    id: 'eau',
    s: 'Les plantes n’ont pas besoin d’eau.',
    v: false,
    img: '💧',
    ex: 'Sans eau, une plante se dessèche.',
  },
  {
    n: 'n',
    id: 'nuage',
    s: 'Le nuage est vivant parce qu’il bouge.',
    v: false,
    img: '☁️',
    ex: 'Le nuage est poussé par le vent : il n’est pas vivant.',
  },
  {
    n: 'n',
    id: 'animaux-manger',
    s: 'Tous les animaux ont besoin de se nourrir.',
    v: true,
    ex: 'Pour vivre et grandir, un animal doit manger et boire.',
  },
  {
    n: 'p',
    id: 'graine',
    s: 'Une graine est vivante.',
    v: true,
    img: '🌱',
    ex: 'Elle peut germer et donner une plante.',
  },
  {
    n: 'p',
    id: 'bois-table',
    s: 'La table en bois est vivante.',
    v: false,
    ex: 'Le bois vient d’un arbre qui était vivant, mais la table, elle, n’est pas vivante.',
  },
];

/* ------------------------------------------------------------------ */
/* Cycles de vie                                                       */
/* ------------------------------------------------------------------ */

const CYCLES_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'poule-3',
    prompt: 'Remets dans l’ordre le cycle de vie de la poule.',
    el: ['l’œuf', 'le poussin', 'la poule'],
    mode: 'etapes',
    cycle: true,
    ex: 'Le poussin sort de l’œuf, grandit et devient une poule qui pondra des œufs.',
  },
  {
    n: 'f',
    id: 'grenouille-3',
    prompt: 'Remets dans l’ordre le cycle de vie de la grenouille.',
    el: ['l’œuf', 'le têtard', 'la grenouille'],
    mode: 'etapes',
    cycle: true,
    ex: 'L’œuf donne un têtard qui se transforme en grenouille.',
  },
  {
    n: 'f',
    id: 'plante-3',
    prompt: 'Remets dans l’ordre le cycle de vie de la plante.',
    el: ['la graine', 'la jeune pousse', 'la plante en fleurs'],
    mode: 'etapes',
    cycle: true,
    ex: 'La graine germe, la pousse grandit, la plante fleurit et fait de nouvelles graines.',
  },
  {
    n: 'f',
    id: 'papillon-3',
    prompt: 'Remets dans l’ordre le cycle de vie du papillon.',
    el: ['l’œuf', 'la chenille', 'le papillon'],
    mode: 'etapes',
    cycle: true,
    ex: 'Une chenille sort de l’œuf, puis elle se transforme en papillon.',
  },
  {
    n: 'n',
    id: 'papillon',
    prompt: 'Remets dans l’ordre le cycle de vie du papillon.',
    el: ['l’œuf', 'la chenille', 'la chrysalide', 'le papillon'],
    mode: 'etapes',
    cycle: true,
    ex: 'La chenille sort de l’œuf, mange, puis se transforme dans la chrysalide en papillon.',
  },
  {
    n: 'n',
    id: 'grenouille',
    prompt: 'Remets dans l’ordre le cycle de vie de la grenouille.',
    el: ['les œufs', 'le têtard', 'le têtard avec des pattes', 'la jeune grenouille', 'la grenouille adulte'],
    mode: 'etapes',
    cycle: true,
    ex: 'Les œufs donnent des têtards ; leurs pattes poussent, la queue disparaît et ils deviennent des grenouilles.',
  },
  {
    n: 'n',
    id: 'poule',
    prompt: 'Remets dans l’ordre le cycle de vie de la poule.',
    el: ['l’œuf couvé par la poule', 'le poussin', 'la jeune poule', 'la poule qui pond'],
    mode: 'etapes',
    cycle: true,
    ex: 'La poule couve l’œuf, le poussin éclot, grandit et devient une poule qui pond à son tour.',
  },
  {
    n: 'n',
    id: 'haricot',
    prompt: 'Remets dans l’ordre le cycle de vie du haricot.',
    el: [
      'la graine',
      'la graine germe',
      'la jeune plante',
      'la plante en fleurs',
      'les gousses pleines de graines',
    ],
    mode: 'etapes',
    cycle: true,
    ex: 'La graine germe, la plante grandit et fleurit, puis les fleurs donnent des gousses avec de nouvelles graines.',
  },
  {
    n: 'n',
    id: 'coccinelle',
    prompt: 'Remets dans l’ordre le cycle de vie de la coccinelle.',
    el: ['l’œuf', 'la larve', 'la nymphe', 'la coccinelle adulte'],
    mode: 'etapes',
    cycle: true,
    ex: 'Comme le papillon, la coccinelle change de forme : œuf, larve, nymphe, adulte.',
  },
  {
    n: 'p',
    id: 'grenouille-6',
    prompt: 'Remets dans l’ordre la métamorphose de la grenouille.',
    el: [
      'les œufs dans la mare',
      'le têtard sans pattes',
      'le têtard avec les pattes arrière',
      'le têtard avec quatre pattes',
      'la jeune grenouille avec une petite queue',
      'la grenouille adulte',
    ],
    mode: 'etapes',
    cycle: true,
    ex: 'Les pattes arrière poussent d’abord, puis les pattes avant ; la queue disparaît : c’est la métamorphose.',
  },
  {
    n: 'p',
    id: 'papillon-6',
    prompt: 'Remets dans l’ordre la métamorphose du papillon.',
    el: [
      'l’œuf pondu sur une feuille',
      'la chenille qui mange les feuilles',
      'la chenille qui a beaucoup grossi',
      'la chrysalide',
      'le papillon qui sort de la chrysalide',
      'le papillon qui pond',
    ],
    mode: 'etapes',
    cycle: true,
    ex: 'La chenille mange et grossit, puis se transforme dans la chrysalide : c’est la métamorphose.',
  },
  {
    n: 'p',
    id: 'pommier',
    prompt: 'Remets dans l’ordre le cycle du pommier.',
    el: [
      'la fleur du pommier',
      'la petite pomme verte',
      'la pomme mûre',
      'le pépin planté dans la terre',
      'le jeune pommier',
    ],
    mode: 'etapes',
    cycle: true,
    ex: 'La fleur devient un fruit, la pomme ; ses pépins sont des graines qui peuvent donner un nouveau pommier.',
  },
  {
    n: 'p',
    id: 'croissance',
    prompt: 'Remets dans l’ordre la croissance d’un être humain.',
    el: ['le bébé', 'l’enfant', 'l’adolescent', 'l’adulte', 'la personne âgée'],
    mode: 'etapes',
    ex: 'Un être humain grandit sans changer de forme : bébé, enfant, adolescent, adulte, personne âgée.',
  },
];

const OE = 'il pond des œufs';
const VT = 'le petit naît du ventre de sa mère';
const CYCLES_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'oeufs',
      prompt: 'Comment naissent les petits de ces animaux ?',
      categories: [OE, VT],
      elements: [
        { label: 'la poule', c: OE, n: 'f', img: '🐔' },
        { label: 'la grenouille', c: OE, n: 'f', img: '🐸' },
        { label: 'le canard', c: OE, n: 'f', img: '🦆' },
        { label: 'la tortue', c: OE, n: 'f', img: '🐢' },
        { label: 'le chat', c: VT, n: 'f', img: '🐈' },
        { label: 'le chien', c: VT, n: 'f', img: '🐕' },
        { label: 'la vache', c: VT, n: 'f', img: '🐄' },
        { label: 'le lapin', c: VT, n: 'f', img: '🐇' },
      ],
      ex: 'Les oiseaux, les tortues et les grenouilles pondent des œufs ; les petits du chat, du chien ou de la vache grandissent dans le ventre de leur mère.',
    },
  ],
  normal: [
    {
      id: 'oeufs',
      prompt: 'Comment naissent les petits de ces animaux ?',
      categories: [OE, VT],
      elements: [
        { label: 'la poule', c: OE, n: 'n', img: '🐔' },
        { label: 'la grenouille', c: OE, n: 'n', img: '🐸' },
        { label: 'le papillon', c: OE, n: 'n', img: '🦋' },
        { label: 'la coccinelle', c: OE, n: 'n', img: '🐞' },
        { label: 'l’escargot', c: OE, n: 'n', img: '🐌' },
        { label: 'le poisson rouge', c: OE, n: 'n', img: '🐟' },
        { label: 'le cheval', c: VT, n: 'n', img: '🐴' },
        { label: 'la vache', c: VT, n: 'n', img: '🐄' },
        { label: 'le mouton', c: VT, n: 'n', img: '🐑' },
        { label: 'le chat', c: VT, n: 'n', img: '🐈' },
        { label: 'le dauphin', c: VT, n: 'n', img: '🐬' },
      ],
      ex: 'Les insectes, les escargots, la plupart des poissons et tous les oiseaux pondent des œufs. Le dauphin, lui, porte son petit dans son ventre, comme la vache.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'metamorphose',
      prompt: 'Cet animal change-t-il de forme en grandissant (métamorphose) ?',
      categories: ['il fait une métamorphose', 'il grandit sans changer de forme'],
      elements: [
        { label: 'la grenouille', c: 'il fait une métamorphose', n: 'p', img: '🐸' },
        { label: 'le papillon', c: 'il fait une métamorphose', n: 'p', img: '🦋' },
        { label: 'la coccinelle', c: 'il fait une métamorphose', n: 'p', img: '🐞' },
        { label: 'le moustique', c: 'il fait une métamorphose', n: 'p', img: '🦟' },
        { label: 'l’abeille', c: 'il fait une métamorphose', n: 'p', img: '🐝' },
        { label: 'le chat', c: 'il grandit sans changer de forme', n: 'p', img: '🐈' },
        { label: 'la poule', c: 'il grandit sans changer de forme', n: 'p', img: '🐔' },
        { label: 'l’escargot', c: 'il grandit sans changer de forme', n: 'p', img: '🐌' },
        { label: 'le cheval', c: 'il grandit sans changer de forme', n: 'p', img: '🐴' },
      ],
      ex: 'Le têtard devient grenouille, la chenille devient papillon : c’est la métamorphose. Le poussin, lui, ressemble déjà à une petite poule.',
      nb: 7,
    },
  ],
};

const CYCLES_QCM: Q[] = [
  {
    n: 'f',
    id: 'tetard',
    q: 'Que devient le têtard ?',
    ok: 'une grenouille',
    ko: ['un poisson', 'un papillon', 'un escargot'],
    img: '🐸',
    ex: 'Le têtard se transforme en grenouille.',
  },
  {
    n: 'f',
    id: 'oeuf-poule',
    q: 'Qui sort de l’œuf de la poule ?',
    ok: 'le poussin',
    ko: ['le têtard', 'le chaton', 'la chenille'],
    img: '🐣',
    ex: 'Le poussin sort de l’œuf couvé par la poule.',
  },
  {
    n: 'f',
    id: 'chenille',
    q: 'Que devient la chenille ?',
    ok: 'un papillon',
    ko: ['une grenouille', 'une poule', 'un ver de terre'],
    img: '🦋',
    ex: 'La chenille se transforme en papillon.',
  },
  {
    n: 'n',
    id: 'petit-papillon',
    q: 'Comment s’appelle le petit du papillon, qui sort de l’œuf ?',
    ok: 'la chenille',
    ko: ['le têtard', 'le poussin', 'le chiot'],
    ex: 'Une chenille sort de l’œuf du papillon.',
  },
  {
    n: 'n',
    id: 'chrysalide',
    q: 'Dans quoi la chenille se transforme-t-elle en papillon ?',
    ok: 'dans la chrysalide',
    ko: ['dans l’œuf', 'dans un terrier', 'dans un nid'],
    ex: 'La chenille s’enferme dans une chrysalide et en sort papillon.',
  },
  {
    n: 'n',
    id: 'germer',
    q: 'De quoi une graine a-t-elle besoin pour germer ?',
    ok: 'd’eau et de chaleur',
    ko: ['de sel', 'de musique', 'de froid glacial'],
    img: '🌱',
    ex: 'Une graine germe quand elle a de l’eau et une température douce.',
  },
  {
    n: 'n',
    id: 'pommes',
    q: 'Que donnent les fleurs du pommier ?',
    ok: 'des pommes',
    ko: ['des graines de tournesol', 'des feuilles mortes', 'des œufs'],
    img: '🍎',
    ex: 'Après la fleur vient le fruit : la pomme, avec ses pépins.',
  },
  {
    n: 'n',
    id: 'pepins',
    q: 'Que sont les pépins de la pomme ?',
    ok: 'des graines',
    ko: ['des œufs', 'des cailloux', 'des racines'],
    ex: 'Les pépins sont des graines : plantés, ils peuvent donner un nouveau pommier.',
  },
  {
    n: 'p',
    id: 'metamorphose',
    q: 'Comment appelle-t-on la transformation du têtard en grenouille ?',
    ok: 'la métamorphose',
    ko: ['la germination', 'la fusion', 'la digestion'],
    ex: 'Quand un animal change complètement de forme en grandissant, c’est une métamorphose.',
  },
  {
    n: 'p',
    id: 'germination',
    q: 'Que se passe-t-il quand une graine germe ?',
    ok: 'une petite racine et une tige sortent de la graine',
    ko: ['la graine fond', 'la graine devient un caillou', 'la graine se transforme en fleur tout de suite'],
    ex: 'Pendant la germination, la racine sort en premier, puis la tige.',
  },
  {
    n: 'p',
    id: 'quel-metamorphose',
    q: 'Lequel de ces animaux fait une métamorphose ?',
    ok: 'la coccinelle',
    ko: ['le chat', 'le chien', 'la poule'],
    img: '🐞',
    ex: 'La coccinelle est d’abord une larve, puis une nymphe, avant de devenir adulte.',
  },
  {
    n: 'p',
    id: 'tetard-respire',
    q: 'Où vit le têtard ?',
    ok: 'dans l’eau',
    ko: ['dans un arbre', 'sous la terre', 'dans le désert'],
    ex: 'Le têtard vit dans l’eau et respire comme un poisson ; la grenouille adulte peut vivre hors de l’eau.',
  },
  {
    n: 'n',
    id: 'qui-papillon',
    q: 'Qui suis-je ?',
    ok: 'le papillon',
    ko: ['la coccinelle', 'l’abeille', 'la libellule'],
    img: '🦋',
    hints: [
      'Je suis un insecte.',
      'Je suis né dans un œuf.',
      'Avant, j’étais une chenille.',
      'J’ai passé du temps dans une chrysalide.',
      'Maintenant, je vole de fleur en fleur.',
    ],
    ex: 'Le papillon a été chenille, puis chrysalide : c’est une métamorphose.',
  },
  {
    n: 'n',
    id: 'qui-grenouille',
    q: 'Qui suis-je ?',
    ok: 'la grenouille',
    ko: ['le papillon', 'la poule', 'le poisson'],
    img: '🐸',
    hints: [
      'Je suis un animal qui pond des œufs.',
      'Je vis une partie de ma vie dans l’eau.',
      'Quand je suis petite, je n’ai pas de pattes mais une queue.',
      'Petite, je m’appelle un têtard.',
      'Je saute et je coasse au bord de la mare.',
    ],
    ex: 'La grenouille pond des œufs dans l’eau ; le têtard se transforme en grenouille.',
  },
  {
    n: 'n',
    id: 'qui-poule',
    q: 'Qui suis-je ?',
    ok: 'la poule',
    ko: ['la grenouille', 'le canard', 'la vache'],
    img: '🐔',
    hints: [
      'Je suis un oiseau.',
      'Je vole très peu.',
      'Je ponds des œufs et je les couve.',
      'Mes petits s’appellent des poussins.',
    ],
    ex: 'La poule couve ses œufs ; les poussins en sortent.',
  },
  {
    n: 'n',
    id: 'qui-coccinelle',
    q: 'Qui suis-je ?',
    ok: 'la coccinelle',
    ko: ['le papillon', 'la fourmi', 'l’araignée'],
    img: '🐞',
    hints: [
      'Je suis un insecte.',
      'Petite, j’étais une larve.',
      'Je mange des pucerons et j’aide les jardiniers.',
      'Je suis souvent rouge avec des points noirs.',
    ],
    ex: 'La coccinelle passe par une métamorphose : œuf, larve, nymphe, adulte.',
  },
];

const CYCLES_VF: VF[] = [
  {
    n: 'f',
    id: 'tetard',
    s: 'Le têtard devient une grenouille.',
    v: true,
    img: '🐸',
    ex: 'Le têtard se transforme en grenouille.',
  },
  {
    n: 'f',
    id: 'chenille',
    s: 'La chenille devient un papillon.',
    v: true,
    img: '🐛',
    ex: 'La chenille se transforme en papillon.',
  },
  {
    n: 'f',
    id: 'poussin',
    s: 'Le poussin sort d’un œuf.',
    v: true,
    img: '🐣',
    ex: 'La poule pond des œufs d’où sortent les poussins.',
  },
  {
    n: 'f',
    id: 'chaton-oeuf',
    s: 'Le chaton sort d’un œuf.',
    v: false,
    img: '🐈',
    ex: 'Le chaton grandit dans le ventre de sa mère.',
  },
  {
    n: 'n',
    id: 'papillon-chenilles',
    s: 'Le papillon pond des chenilles.',
    v: false,
    img: '🦋',
    ex: 'Le papillon pond des œufs ; ce sont les œufs qui donnent des chenilles.',
  },
  {
    n: 'n',
    id: 'graine',
    s: 'Une graine peut donner une nouvelle plante.',
    v: true,
    img: '🌱',
    ex: 'Plantée et arrosée, la graine germe et devient une plante.',
  },
  {
    n: 'n',
    id: 'chrysalide',
    s: 'La chrysalide est une étape de la vie du papillon.',
    v: true,
    ex: 'Œuf, chenille, chrysalide, papillon.',
  },
  {
    n: 'n',
    id: 'tous-oeufs',
    s: 'Tous les animaux pondent des œufs.',
    v: false,
    ex: 'Le chat, la vache ou le dauphin ne pondent pas : leurs petits naissent du ventre de leur mère.',
  },
  {
    n: 'n',
    id: 'fleur-fruit',
    s: 'Le fruit se forme à partir de la fleur.',
    v: true,
    img: '🍎',
    ex: 'Après la fleur vient le fruit, qui contient les graines.',
  },
  {
    n: 'p',
    id: 'tetard-eau',
    s: 'Le têtard vit dans l’eau.',
    v: true,
    ex: 'Le têtard vit dans l’eau comme un poisson.',
  },
  {
    n: 'p',
    id: 'poussin-metamorphose',
    s: 'Le poussin fait une métamorphose pour devenir une poule.',
    v: false,
    ex: 'Le poussin ressemble déjà à une petite poule : il grandit sans changer de forme.',
  },
];

const CYCLES_PAIRES: Record<Level, Appariement[]> = {
  facile: [
    {
      id: 'petits',
      prompt: 'Associe chaque animal à son petit.',
      relation: 'adulte → petit',
      duos: [
        { l: 'la poule', r: 'le poussin', n: 'f' },
        { l: 'la vache', r: 'le veau', n: 'f' },
        { l: 'le chat', r: 'le chaton', n: 'f' },
        { l: 'le chien', r: 'le chiot', n: 'f' },
        { l: 'la grenouille', r: 'le têtard', n: 'f' },
      ],
      ex: 'Chaque animal a un petit qui porte souvent un nom différent : la poule et le poussin, la vache et le veau…',
      nb: 4,
    },
  ],
  normal: [
    {
      id: 'petits',
      prompt: 'Associe chaque animal à son petit.',
      relation: 'adulte → petit',
      duos: [
        { l: 'la poule', r: 'le poussin', n: 'n' },
        { l: 'la vache', r: 'le veau', n: 'n' },
        { l: 'le chat', r: 'le chaton', n: 'n' },
        { l: 'le chien', r: 'le chiot', n: 'n' },
        { l: 'la grenouille', r: 'le têtard', n: 'n' },
        { l: 'la jument', r: 'le poulain', n: 'n' },
        { l: 'la brebis', r: 'l’agneau', n: 'n' },
        { l: 'le papillon', r: 'la chenille', n: 'n' },
        { l: 'la cane', r: 'le caneton', n: 'n' },
        { l: 'la chèvre', r: 'le chevreau', n: 'n' },
      ],
      ex: 'Le petit de la jument est le poulain, celui de la brebis l’agneau, celui de la chèvre le chevreau.',
    },
  ],
  plus_loin: [
    {
      id: 'petits',
      prompt: 'Associe chaque animal à son petit.',
      relation: 'adulte → petit',
      duos: [
        { l: 'la truie', r: 'le porcelet', n: 'p' },
        { l: 'l’ourse', r: 'l’ourson', n: 'p' },
        { l: 'la lionne', r: 'le lionceau', n: 'p' },
        { l: 'la biche', r: 'le faon', n: 'p' },
        { l: 'l’éléphante', r: 'l’éléphanteau', n: 'p' },
        { l: 'la lapine', r: 'le lapereau', n: 'p' },
        { l: 'la jument', r: 'le poulain', n: 'p' },
        { l: 'la chèvre', r: 'le chevreau', n: 'p' },
      ],
      ex: 'Le porcelet est le petit de la truie, le faon celui de la biche, le lapereau celui de la lapine.',
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Régimes et chaînes alimentaires                                     */
/* ------------------------------------------------------------------ */

const HE = 'herbivore';
const CN = 'carnivore';
const OM = 'omnivore';
const HERBIVORES = [
  { label: 'la vache', c: HE, img: '🐄' },
  { label: 'le lapin', c: HE, img: '🐇' },
  { label: 'le mouton', c: HE, img: '🐑' },
  { label: 'le cheval', c: HE, img: '🐴' },
  { label: 'la chèvre', c: HE, img: '🐐' },
  { label: 'la girafe', c: HE, img: '🦒' },
];
const CARNIVORES = [
  { label: 'le lion', c: CN, img: '🦁' },
  { label: 'le loup', c: CN, img: '🐺' },
  { label: 'le requin', c: CN, img: '🦈' },
  { label: 'l’aigle', c: CN, img: '🦅' },
  { label: 'le tigre', c: CN, img: '🐅' },
  { label: 'le crocodile', c: CN, img: '🐊' },
];
const OMNIVORES = [
  { label: 'le sanglier', c: OM, img: '🐗' },
  { label: 'l’ours brun', c: OM, img: '🐻' },
  { label: 'la poule', c: OM, img: '🐔' },
  { label: 'le cochon', c: OM, img: '🐖' },
];

const ALIM_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'herbi-carni',
      prompt: 'Herbivore ou carnivore ?',
      categories: [HE, CN],
      elements: [...HERBIVORES, ...CARNIVORES].map((e) => ({ ...e, n: 'f' as const })),
      ex: 'L’herbivore mange des végétaux ; le carnivore mange d’autres animaux.',
    },
  ],
  normal: [
    {
      id: 'regimes',
      prompt: 'Que mangent ces animaux ?',
      categories: [HE, CN, OM],
      elements: [...HERBIVORES, ...CARNIVORES, ...OMNIVORES].map((e) => ({ ...e, n: 'n' as const })),
      ex: 'L’herbivore mange des végétaux, le carnivore de la viande, l’omnivore un peu de tout.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'reseau',
      prompt: 'Dans la chaîne alimentaire, qui est qui ?',
      categories: ['un végétal', 'un mangeur de plantes', 'un mangeur d’animaux'],
      elements: [
        { label: 'l’herbe', c: 'un végétal', n: 'p', img: '🌿' },
        { label: 'la feuille de salade', c: 'un végétal', n: 'p', img: '🥬' },
        { label: 'le gland', c: 'un végétal', n: 'p', img: '🌰' },
        { label: 'la chenille', c: 'un mangeur de plantes', n: 'p', img: '🐛' },
        { label: 'le lapin', c: 'un mangeur de plantes', n: 'p', img: '🐇' },
        { label: 'l’escargot', c: 'un mangeur de plantes', n: 'p', img: '🐌' },
        { label: 'la chouette', c: 'un mangeur d’animaux', n: 'p', img: '🦉' },
        { label: 'l’araignée', c: 'un mangeur d’animaux', n: 'p', img: '🕷️' },
        { label: 'la buse', c: 'un mangeur d’animaux', n: 'p', img: '🦅' },
      ],
      ex: 'Toute chaîne alimentaire commence par un végétal, mangé par un herbivore, lui-même mangé par un carnivore.',
      nb: 7,
    },
    {
      id: 'regimes',
      prompt: 'Que mangent ces animaux ?',
      categories: [HE, CN, OM],
      elements: [
        ...[...HERBIVORES, ...CARNIVORES, ...OMNIVORES].map((e) => ({ ...e, n: 'p' as const })),
        { label: 'le blaireau', c: OM, n: 'p', img: '🦡' },
        { label: 'le panda', c: HE, n: 'p', img: '🐼' },
        { label: 'le phoque', c: CN, n: 'p', img: '🦭' },
      ],
      ex: 'Le panda mange presque seulement du bambou ; le phoque mange des poissons ; le blaireau mange de tout.',
      nb: 9,
    },
  ],
};

const chaine = (el: string[]) =>
  `Dans une chaîne alimentaire, chacun est mangé par le suivant : ${el.join(' → ')}.`;
const ALIM_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'herbe-lapin-renard',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ? Commence par la plante.',
    el: ['l’herbe', 'le lapin', 'le renard'],
    mode: 'etapes',
    ex: chaine(['l’herbe', 'le lapin', 'le renard']),
  },
  {
    n: 'f',
    id: 'salade-escargot-herisson',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ? Commence par la plante.',
    el: ['la salade', 'l’escargot', 'le hérisson'],
    mode: 'etapes',
    ex: chaine(['la salade', 'l’escargot', 'le hérisson']),
  },
  {
    n: 'f',
    id: 'graines-souris-chouette',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ? Commence par la plante.',
    el: ['les graines', 'la souris', 'la chouette'],
    mode: 'etapes',
    ex: chaine(['les graines', 'la souris', 'la chouette']),
  },
  {
    n: 'n',
    id: 'feuille-chenille-mesange',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ?',
    el: ['la feuille', 'la chenille', 'la mésange'],
    mode: 'etapes',
    ex: chaine(['la feuille', 'la chenille', 'la mésange']),
  },
  {
    n: 'n',
    id: 'herbe-sauterelle-grenouille',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ?',
    el: ['l’herbe', 'la sauterelle', 'la grenouille'],
    mode: 'etapes',
    ex: chaine(['l’herbe', 'la sauterelle', 'la grenouille']),
  },
  {
    n: 'n',
    id: 'algue-poisson-heron',
    prompt: 'Range la chaîne alimentaire de la mare : qui est mangé par qui ?',
    el: ['les algues', 'le petit poisson', 'le héron'],
    mode: 'etapes',
    ex: chaine(['les algues', 'le petit poisson', 'le héron']),
  },
  {
    n: 'p',
    id: 'quatre-heron',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ?',
    el: ['l’herbe', 'la sauterelle', 'la grenouille', 'le héron'],
    mode: 'etapes',
    ex: chaine(['l’herbe', 'la sauterelle', 'la grenouille', 'le héron']),
  },
  {
    n: 'p',
    id: 'quatre-epervier',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ?',
    el: ['la feuille', 'la chenille', 'la mésange', 'l’épervier'],
    mode: 'etapes',
    ex: chaine(['la feuille', 'la chenille', 'la mésange', 'l’épervier']),
  },
  {
    n: 'p',
    id: 'quatre-renard',
    prompt: 'Range la chaîne alimentaire : qui est mangé par qui ?',
    el: ['les graines', 'le mulot', 'la couleuvre', 'la buse'],
    mode: 'etapes',
    ex: chaine(['les graines', 'le mulot', 'la couleuvre', 'la buse']),
  },
];

const ALIM_QCM: Q[] = [
  {
    n: 'f',
    id: 'vache',
    q: 'Que mange la vache ?',
    ok: 'de l’herbe',
    ko: ['de la viande', 'des poissons', 'des insectes'],
    img: '🐄',
    ex: 'La vache est herbivore : elle mange de l’herbe.',
  },
  {
    n: 'f',
    id: 'herbivore',
    q: 'Un animal qui mange seulement des végétaux est…',
    ok: 'herbivore',
    ko: ['carnivore', 'omnivore'],
    ex: 'Herbivore : il mange des herbes, des feuilles, des fruits, des graines.',
  },
  {
    n: 'f',
    id: 'lion',
    q: 'Que mange le lion ?',
    ok: 'd’autres animaux',
    ko: ['de l’herbe', 'des fruits', 'des graines'],
    img: '🦁',
    ex: 'Le lion est carnivore : il chasse d’autres animaux.',
  },
  {
    n: 'n',
    id: 'omnivore',
    q: 'Un animal qui mange des végétaux et des animaux est…',
    ok: 'omnivore',
    ko: ['herbivore', 'carnivore'],
    ex: 'Omnivore veut dire « qui mange de tout ».',
  },
  {
    n: 'n',
    id: 'carnivore',
    q: 'Comment appelle-t-on un animal qui mange d’autres animaux ?',
    ok: 'un carnivore',
    ko: ['un herbivore', 'un végétal', 'un omnivore'],
    ex: 'Le carnivore mange de la viande : le loup, le lion, le requin…',
  },
  {
    n: 'n',
    id: 'chaine-renard',
    q: 'Dans la chaîne « herbe → lapin → renard », qui mange le lapin ?',
    ok: 'le renard',
    ko: ['l’herbe', 'personne'],
    ex: 'La flèche veut dire « est mangé par » : le lapin est mangé par le renard.',
  },
  {
    n: 'n',
    id: 'dents-loup',
    q: 'À quoi servent les dents pointues du loup ?',
    ok: 'à déchirer la viande',
    ko: ['à brouter l’herbe', 'à boire', 'à casser des noisettes'],
    img: '🐺',
    ex: 'Les carnivores ont des crocs pointus pour attraper et déchirer la viande.',
  },
  {
    n: 'n',
    id: 'ours',
    q: 'L’ours brun mange des baies, du miel, des poissons et des insectes. Il est…',
    ok: 'omnivore',
    ko: ['herbivore', 'carnivore'],
    img: '🐻',
    ex: 'Il mange des végétaux et des animaux : il est omnivore.',
  },
  {
    n: 'p',
    id: 'debut-chaine',
    q: 'Qui se trouve toujours au début d’une chaîne alimentaire ?',
    ok: 'un végétal',
    ko: ['un carnivore', 'un omnivore', 'un rocher'],
    ex: 'Les végétaux fabriquent leur nourriture avec la lumière : ils sont au début de toutes les chaînes.',
  },
  {
    n: 'p',
    id: 'lapins-disparus',
    q: 'Si tous les lapins disparaissaient, que se passerait-il pour les renards ?',
    ok: 'ils auraient moins de nourriture',
    ko: ['ils auraient plus de nourriture', 'rien du tout', 'ils mangeraient de l’herbe'],
    ex: 'Les êtres vivants dépendent les uns des autres : sans proies, les prédateurs ont faim.',
  },
  {
    n: 'p',
    id: 'dents-vache',
    q: 'À quoi servent les grosses dents plates de la vache ?',
    ok: 'à broyer l’herbe',
    ko: ['à déchirer la viande', 'à creuser la terre'],
    ex: 'Les herbivores ont des dents plates pour écraser et mâcher les végétaux.',
  },
  {
    n: 'n',
    id: 'qui-vache',
    q: 'Qui suis-je ?',
    ok: 'la vache',
    ko: ['le cochon', 'le cheval', 'la chèvre'],
    img: '🐄',
    hints: [
      'Je suis un animal de la ferme.',
      'Je suis herbivore.',
      'Je mâche l’herbe très longtemps : je rumine.',
      'Je donne du lait, et mon petit s’appelle le veau.',
    ],
    ex: 'La vache est herbivore : elle mange de l’herbe et la rumine.',
  },
  {
    n: 'n',
    id: 'qui-herisson',
    q: 'Qui suis-je ?',
    ok: 'le hérisson',
    ko: ['le lapin', 'la taupe', 'l’écureuil'],
    img: '🦔',
    hints: [
      'Je suis un petit animal sauvage.',
      'Je sors surtout la nuit.',
      'Je mange des limaces, des vers et des insectes.',
      'J’ai des piquants sur le dos.',
    ],
    ex: 'Le hérisson mange des limaces et des insectes : c’est un ami du jardinier.',
  },
  {
    n: 'n',
    id: 'qui-ecureuil',
    q: 'Qui suis-je ?',
    ok: 'l’écureuil',
    ko: ['le hérisson', 'le lapin', 'la souris'],
    img: '🐿️',
    hints: [
      'Je vis dans les arbres.',
      'J’ai une grande queue touffue.',
      'Je mange des noisettes, des glands et des graines.',
      'En automne, je cache des provisions pour l’hiver.',
    ],
    ex: 'L’écureuil se nourrit surtout de noisettes, de glands et de graines.',
  },
  {
    n: 'n',
    id: 'qui-loup',
    q: 'Qui suis-je ?',
    ok: 'le loup',
    ko: ['le renard', 'le chien', 'le lion'],
    img: '🐺',
    hints: [
      'Je suis un animal sauvage.',
      'Je vis souvent en meute.',
      'Je suis carnivore : je chasse d’autres animaux.',
      'On me rencontre dans beaucoup de contes, pourtant j’ai peur des humains.',
    ],
    ex: 'Le loup est un carnivore qui chasse en groupe, la meute.',
  },
];

const ALIM_VF: VF[] = [
  { n: 'f', id: 'vache', s: 'La vache est herbivore.', v: true, img: '🐄', ex: 'Elle mange de l’herbe.' },
  {
    n: 'f',
    id: 'lion',
    s: 'Le lion mange de l’herbe.',
    v: false,
    img: '🦁',
    ex: 'Le lion est carnivore : il mange d’autres animaux.',
  },
  {
    n: 'f',
    id: 'lapin',
    s: 'Le lapin est carnivore.',
    v: false,
    img: '🐇',
    ex: 'Le lapin est herbivore : il mange de l’herbe et des feuilles.',
  },
  {
    n: 'f',
    id: 'loup',
    s: 'Le loup est carnivore.',
    v: true,
    img: '🐺',
    ex: 'Le loup chasse d’autres animaux.',
  },
  {
    n: 'n',
    id: 'ours',
    s: 'L’ours brun mange des plantes et des animaux : il est omnivore.',
    v: true,
    img: '🐻',
    ex: 'Il mange des baies, du miel, des poissons…',
  },
  {
    n: 'n',
    id: 'debut',
    s: 'Une chaîne alimentaire commence par un végétal.',
    v: true,
    ex: 'Les végétaux sont toujours au début de la chaîne.',
  },
  {
    n: 'n',
    id: 'renard',
    s: 'Le renard peut manger le lapin.',
    v: true,
    ex: 'Dans la chaîne herbe → lapin → renard, le lapin est mangé par le renard.',
  },
  {
    n: 'n',
    id: 'mouton',
    s: 'Le mouton mange des souris.',
    v: false,
    img: '🐑',
    ex: 'Le mouton est herbivore : il broute l’herbe.',
  },
  {
    n: 'n',
    id: 'fleche',
    s: 'Dans « herbe → lapin », la flèche veut dire « est mangé par ».',
    v: true,
    ex: 'L’herbe est mangée par le lapin.',
  },
  {
    n: 'p',
    id: 'dependent',
    s: 'Si l’herbe disparaissait, les renards auraient aussi moins à manger.',
    v: true,
    ex: 'Sans herbe, moins de lapins ; sans lapins, moins de nourriture pour les renards.',
  },
  {
    n: 'p',
    id: 'dents',
    s: 'Les herbivores ont des crocs pointus pour déchirer la viande.',
    v: false,
    ex: 'Ce sont les carnivores qui ont des crocs ; les herbivores ont des dents plates pour broyer.',
  },
];

const ALIM_PAIRES: Record<Level, Appariement[]> = (() => {
  const duos = (n: 'f' | 'n' | 'p') => [
    { l: 'la vache', r: 'l’herbe', n },
    { l: 'l’écureuil', r: 'les noisettes', n },
    { l: 'la chouette', r: 'les souris', n },
    { l: 'le hérisson', r: 'les limaces', n },
    { l: 'l’araignée', r: 'les mouches', n },
    { l: 'le panda', r: 'le bambou', n },
    { l: 'l’abeille', r: 'le nectar des fleurs', n },
    { l: 'la chenille', r: 'les feuilles', n },
    { l: 'la poule', r: 'les graines', n },
  ];
  const a = (n: 'f' | 'n' | 'p', nb: number): Appariement => ({
    id: 'repas',
    prompt: 'Associe chaque animal à ce qu’il mange.',
    relation: 'animal → nourriture',
    duos: duos(n),
    ex: 'Chaque animal a son régime alimentaire : la chouette chasse les souris, l’écureuil croque des noisettes…',
    nb,
  });
  return { facile: [a('f', 4)], normal: [a('n', 6)], plus_loin: [a('p', 8)] };
})();

/* ------------------------------------------------------------------ */
/* Le corps et la santé                                                */
/* ------------------------------------------------------------------ */

const BON = 'bon pour ma santé';
const EV = 'à éviter';
const FL = 'fruits et légumes';
const FE = 'féculents';
const PL = 'produits laitiers';
const VPO = 'viande, poisson, œufs';
const SU = 'produits sucrés';

const ALIMENTS = [
  { label: 'la pomme', c: FL, img: '🍎' },
  { label: 'la carotte', c: FL, img: '🥕' },
  { label: 'la banane', c: FL, img: '🍌' },
  { label: 'la tomate', c: FL, img: '🍅' },
  { label: 'le brocoli', c: FL, img: '🥦' },
  { label: 'le pain', c: FE, img: '🍞' },
  { label: 'les pâtes', c: FE, img: '🍝' },
  { label: 'le riz', c: FE, img: '🍚' },
  { label: 'la pomme de terre', c: FE, img: '🥔' },
  { label: 'le lait', c: PL, img: '🥛' },
  { label: 'le fromage', c: PL, img: '🧀' },
  { label: 'le yaourt', c: PL },
  { label: 'le poulet', c: VPO, img: '🍗' },
  { label: 'le poisson', c: VPO, img: '🐟' },
  { label: 'l’œuf', c: VPO, img: '🥚' },
];

const SANTE_TRIS: Record<Level, Tri[]> = {
  facile: [
    {
      id: 'gestes',
      prompt: 'Ce geste est-il bon pour ma santé ou vaut-il mieux l’éviter ?',
      categories: [BON, EV],
      elements: [
        { label: 'me laver les mains avant de manger', c: BON, n: 'f', img: '🧼' },
        { label: 'me brosser les dents matin et soir', c: BON, n: 'f', img: '🪥' },
        { label: 'dormir assez longtemps', c: BON, n: 'f', img: '😴' },
        { label: 'courir et jouer dehors', c: BON, n: 'f', img: '🏃' },
        { label: 'boire de l’eau', c: BON, n: 'f', img: '💧' },
        { label: 'manger des fruits', c: BON, n: 'f', img: '🍎' },
        { label: 'me coucher très tard', c: EV, n: 'f', img: '🌙' },
        { label: 'grignoter des bonbons toute la journée', c: EV, n: 'f', img: '🍬' },
        { label: 'rester des heures devant un écran', c: EV, n: 'f', img: '📺' },
        { label: 'boire beaucoup de sodas', c: EV, n: 'f', img: '🥤' },
      ],
      ex: 'Se laver, bien dormir, bouger et manger varié aident le corps à grandir en forme. Les autres gestes, on essaie de les éviter.',
    },
  ],
  normal: [
    {
      id: 'familles',
      prompt: 'Range chaque aliment dans sa famille.',
      categories: [FL, FE, PL, VPO],
      elements: ALIMENTS.map((e) => ({ ...e, n: 'n' as const })),
      ex: 'Pour être en forme, on mange un peu de chaque famille d’aliments chaque jour.',
      nb: 8,
    },
  ],
  plus_loin: [
    {
      id: 'familles-sucre',
      prompt: 'Range chaque aliment dans sa famille.',
      categories: [FL, FE, PL, VPO, SU],
      elements: [
        ...ALIMENTS.map((e) => ({ ...e, n: 'p' as const })),
        { label: 'le gâteau', c: SU, n: 'p', img: '🍰' },
        { label: 'les bonbons', c: SU, n: 'p', img: '🍬' },
        { label: 'la confiture', c: SU, n: 'p', img: '🍯' },
      ],
      ex: 'Les produits sucrés font plaisir, mais on en mange un peu seulement, de temps en temps.',
      nb: 10,
    },
    {
      id: 'os-articulations',
      prompt: 'Est-ce un os ou une articulation ?',
      categories: ['un os', 'une articulation'],
      elements: [
        { label: 'le crâne', c: 'un os', n: 'p', img: '💀' },
        { label: 'les côtes', c: 'un os', n: 'p' },
        { label: 'le fémur', c: 'un os', n: 'p', img: '🦴' },
        { label: 'la colonne vertébrale', c: 'un os', n: 'p' },
        { label: 'le genou', c: 'une articulation', n: 'p', img: '🦵' },
        { label: 'le coude', c: 'une articulation', n: 'p', img: '💪' },
        { label: 'l’épaule', c: 'une articulation', n: 'p' },
        { label: 'la cheville', c: 'une articulation', n: 'p', img: '🦶' },
        { label: 'le poignet', c: 'une articulation', n: 'p', img: '✋' },
      ],
      ex: 'Les os forment le squelette ; les articulations sont les endroits où deux os se rejoignent et permettent de plier.',
      nb: 7,
    },
  ],
};

const SANTE_ORDRES: Ordre[] = [
  {
    n: 'f',
    id: 'mains-3',
    prompt: 'Remets dans l’ordre : comment se laver les mains ?',
    el: ['je mets du savon', 'je frotte mes mains', 'je rince à l’eau'],
    mode: 'etapes',
    ex: 'Savon, on frotte longtemps, puis on rince : les microbes partent avec l’eau.',
  },
  {
    n: 'f',
    id: 'coucher',
    prompt: 'Remets dans l’ordre le moment du coucher.',
    el: [
      'je mets mon pyjama',
      'je me brosse les dents',
      'je lis une histoire',
      'j’éteins la lumière et je dors',
    ],
    mode: 'etapes',
    ex: 'Un coucher calme et régulier aide à bien dormir.',
  },
  {
    n: 'n',
    id: 'mains',
    prompt: 'Remets dans l’ordre : comment bien se laver les mains ?',
    el: [
      'je mouille mes mains',
      'je mets du savon',
      'je frotte longtemps, entre les doigts aussi',
      'je rince',
      'je sèche mes mains',
    ],
    mode: 'etapes',
    ex: 'Mouiller, savonner, frotter, rincer, sécher : c’est ainsi qu’on chasse les microbes.',
  },
  {
    n: 'n',
    id: 'dents',
    prompt: 'Remets dans l’ordre : comment bien se brosser les dents ?',
    el: [
      'je mets un peu de dentifrice sur la brosse',
      'je brosse toutes mes dents, du rose vers le blanc',
      'je crache le dentifrice',
      'je rince ma brosse',
    ],
    mode: 'etapes',
    ex: 'On brosse de la gencive (le rose) vers la dent (le blanc), environ deux minutes.',
  },
  {
    n: 'p',
    id: 'blessure',
    prompt: 'Je me suis écorché le genou. Remets les étapes dans l’ordre.',
    el: [
      'je préviens un adulte',
      'on nettoie la plaie avec de l’eau et du savon',
      'on désinfecte',
      'on met un pansement',
    ],
    mode: 'etapes',
    ex: 'On prévient un adulte, qui nettoie, désinfecte et protège la plaie.',
  },
];

const SANTE_QCM: Q[] = [
  {
    n: 'f',
    id: 'mains',
    q: 'Quand faut-il se laver les mains ?',
    ok: 'avant de manger et après être allé aux toilettes',
    ko: ['seulement le dimanche', 'jamais', 'seulement quand elles sont noires'],
    img: '🧼',
    ex: 'Se laver les mains souvent enlève les microbes qui rendent malade.',
  },
  {
    n: 'f',
    id: 'dents',
    q: 'Combien de fois par jour faut-il se brosser les dents ?',
    ok: 'au moins 2 fois, le matin et le soir',
    ko: ['une fois par semaine', 'jamais', 'seulement à Noël'],
    img: '🪥',
    ex: 'On se brosse les dents matin et soir, pendant environ deux minutes.',
  },
  {
    n: 'f',
    id: 'boisson',
    q: 'Quelle boisson est la meilleure pour le corps ?',
    ok: 'l’eau',
    ko: ['le soda', 'le sirop'],
    img: '💧',
    ex: 'L’eau est la seule boisson indispensable : on peut en boire autant qu’on veut.',
  },
  {
    n: 'n',
    id: 'fromage',
    q: 'Dans quelle famille d’aliments range-t-on le fromage ?',
    ok: 'les produits laitiers',
    ko: ['les féculents', 'les fruits et légumes', 'les produits sucrés'],
    img: '🧀',
    ex: 'Le fromage est fabriqué avec du lait : c’est un produit laitier.',
  },
  {
    n: 'n',
    id: 'feculent',
    q: 'Lequel de ces aliments est un féculent ?',
    ok: 'les pâtes',
    ko: ['la pomme', 'le yaourt', 'le poulet'],
    img: '🍝',
    ex: 'Pâtes, riz, pain, pommes de terre : ce sont des féculents qui donnent de l’énergie.',
  },
  {
    n: 'n',
    id: 'sommeil',
    q: 'Combien d’heures environ un enfant de 7 ans a-t-il besoin de dormir chaque nuit ?',
    ok: 'environ 10 heures',
    ko: ['environ 4 heures', 'environ 20 heures', 'environ 1 heure'],
    img: '😴',
    ex: 'À ton âge, le corps et le cerveau ont besoin d’environ 10 heures de sommeil pour grandir et apprendre.',
  },
  {
    n: 'n',
    id: 'sport',
    q: 'Pourquoi est-ce bien de bouger et de faire du sport ?',
    ok: 'pour rester en forme et en bonne santé',
    ko: ['pour avoir moins faim', 'pour ne plus jamais dormir', 'pour ne plus grandir'],
    img: '⚽',
    ex: 'Bouger fait travailler le cœur et les muscles : on se sent en forme.',
  },
  {
    n: 'n',
    id: 'varie',
    q: 'Pourquoi faut-il manger varié ?',
    ok: 'pour donner au corps tout ce dont il a besoin',
    ko: [
      'pour avoir de jolies couleurs dans l’assiette seulement',
      'parce que c’est obligatoire de tout finir',
      'pour ne pas avoir besoin de dormir',
    ],
    ex: 'Chaque famille d’aliments apporte quelque chose d’utile au corps.',
  },
  {
    n: 'p',
    id: 'squelette',
    q: 'Comment s’appelle l’ensemble des os du corps ?',
    ok: 'le squelette',
    ko: ['les muscles', 'la peau', 'le cerveau'],
    img: '🦴',
    ex: 'Les os forment le squelette, qui tient le corps debout.',
  },
  {
    n: 'p',
    id: 'articulation',
    q: 'Laquelle de ces parties du corps est une articulation ?',
    ok: 'le genou',
    ko: ['l’ongle', 'les cheveux', 'le nez'],
    ex: 'Une articulation relie deux os et permet de plier : genou, coude, épaule…',
  },
  {
    n: 'p',
    id: 'crane',
    q: 'Quels os protègent le cerveau ?',
    ok: 'les os du crâne',
    ko: ['les côtes', 'le fémur', 'les os du pied'],
    ex: 'Le crâne est une boîte solide qui protège le cerveau.',
  },
  {
    n: 'p',
    id: 'cotes',
    q: 'Quels os protègent le cœur et les poumons ?',
    ok: 'les côtes',
    ko: ['le crâne', 'le fémur', 'les doigts'],
    ex: 'Les côtes forment une cage qui protège le cœur et les poumons.',
  },
  {
    n: 'p',
    id: 'muscles',
    q: 'Qu’est-ce qui fait bouger les os ?',
    ok: 'les muscles',
    ko: ['les cheveux', 'les ongles', 'la peau'],
    img: '💪',
    ex: 'Les muscles tirent sur les os pour faire bouger le corps.',
  },
  {
    n: 'n',
    id: 'qui-brosse',
    q: 'Qui suis-je ?',
    ok: 'la brosse à dents',
    ko: ['le peigne', 'la serviette', 'le savon'],
    img: '🪥',
    hints: [
      'Je suis un objet de la salle de bain.',
      'J’ai un manche et des poils.',
      'On me change environ tous les 3 mois.',
      'Je sers à nettoyer les dents.',
    ],
    ex: 'La brosse à dents s’utilise matin et soir.',
  },
  {
    n: 'n',
    id: 'qui-savon',
    q: 'Qui suis-je ?',
    ok: 'le savon',
    ko: ['la brosse à dents', 'le dentifrice', 'la serviette'],
    img: '🧼',
    hints: [
      'Je suis glissant.',
      'Avec de l’eau, je fais de la mousse.',
      'J’enlève les microbes de tes mains.',
      'On m’utilise avant chaque repas.',
    ],
    ex: 'Le savon et l’eau chassent les microbes des mains.',
  },
  {
    n: 'n',
    id: 'qui-lait',
    q: 'Qui suis-je ?',
    ok: 'le lait',
    ko: ['l’eau', 'le jus de pomme', 'la soupe'],
    img: '🥛',
    hints: [
      'Je suis blanc.',
      'Je suis une boisson.',
      'Je viens souvent de la vache.',
      'Avec moi, on fabrique du fromage et des yaourts.',
    ],
    ex: 'Le lait est un produit laitier, comme le fromage et le yaourt.',
  },
  {
    n: 'n',
    id: 'qui-dentiste',
    q: 'Qui suis-je ?',
    ok: 'le dentiste',
    ko: ['le boulanger', 'le pompier', 'le vétérinaire'],
    img: '🦷',
    hints: [
      'Je suis un métier de la santé.',
      'Il faut venir me voir une ou deux fois par an.',
      'Je regarde dans ta bouche avec un petit miroir.',
      'Je soigne les dents et je chasse les caries.',
    ],
    ex: 'Le dentiste vérifie et soigne les dents.',
  },
  {
    n: 'p',
    id: 'qui-squelette',
    q: 'Qui suis-je ?',
    ok: 'le squelette',
    ko: ['le cerveau', 'le cœur', 'la peau'],
    img: '🦴',
    hints: [
      'Je suis caché à l’intérieur de ton corps.',
      'Je suis fait de plus de 200 os.',
      'Je tiens ton corps debout.',
      'Je protège ton cerveau, ton cœur et tes poumons.',
    ],
    ex: 'Le squelette est l’ensemble des os du corps.',
  },
];

const SANTE_VF: VF[] = [
  {
    n: 'f',
    id: 'dents',
    s: 'Il faut se brosser les dents au moins deux fois par jour.',
    v: true,
    img: '🪥',
    ex: 'Le matin et le soir, pendant environ deux minutes.',
  },
  {
    n: 'f',
    id: 'mains',
    s: 'Se laver les mains avec du savon enlève des microbes.',
    v: true,
    img: '🧼',
    ex: 'Le savon et l’eau chassent les microbes.',
  },
  {
    n: 'f',
    id: 'dormir',
    s: 'Dormir ne sert à rien.',
    v: false,
    img: '😴',
    ex: 'Le sommeil aide le corps à grandir et le cerveau à retenir ce qu’on apprend.',
  },
  {
    n: 'f',
    id: 'bouger',
    s: 'Bouger et jouer dehors aide à rester en bonne santé.',
    v: true,
    img: '🏃',
    ex: 'Bouger fait travailler le cœur et les muscles.',
  },
  {
    n: 'n',
    id: 'fromage',
    s: 'Le fromage est un produit laitier.',
    v: true,
    img: '🧀',
    ex: 'Il est fabriqué avec du lait.',
  },
  {
    n: 'n',
    id: 'pates',
    s: 'Les pâtes sont des fruits.',
    v: false,
    img: '🍝',
    ex: 'Les pâtes sont des féculents.',
  },
  {
    n: 'n',
    id: 'bonbons',
    s: 'Il faut manger des bonbons à chaque repas.',
    v: false,
    img: '🍬',
    ex: 'Les sucreries, c’est de temps en temps et en petite quantité.',
  },
  {
    n: 'n',
    id: 'eau',
    s: 'L’eau est la meilleure boisson pour le corps.',
    v: true,
    img: '💧',
    ex: 'On peut boire de l’eau à volonté.',
  },
  {
    n: 'n',
    id: 'oeuf',
    s: 'L’œuf fait partie de la famille « viande, poisson, œufs ».',
    v: true,
    img: '🥚',
    ex: 'Viande, poisson et œufs aident à fabriquer les muscles.',
  },
  {
    n: 'p',
    id: 'genou',
    s: 'Le genou est une articulation.',
    v: true,
    ex: 'Il relie les os de la cuisse et de la jambe et permet de plier.',
  },
  {
    n: 'p',
    id: 'crane',
    s: 'Le crâne protège le cerveau.',
    v: true,
    ex: 'Le crâne est une boîte en os très solide.',
  },
  {
    n: 'p',
    id: 'muscles-os',
    s: 'Les muscles sont des os.',
    v: false,
    ex: 'Les muscles sont attachés aux os et les font bouger.',
  },
];

const SANTE_PAIRES: Record<Level, Appariement[]> = {
  facile: [
    {
      id: 'gestes',
      prompt: 'Associe chaque geste à son image.',
      relation: 'geste → image',
      duos: [
        { l: 'se brosser les dents', r: '🪥', n: 'f' },
        { l: 'se laver les mains', r: '🧼', n: 'f' },
        { l: 'dormir', r: '🛏️', n: 'f' },
        { l: 'boire de l’eau', r: '💧', n: 'f' },
        { l: 'faire du sport', r: '⚽', n: 'f' },
        { l: 'manger des fruits', r: '🍎', n: 'f' },
      ],
      ex: 'Ce sont des gestes qui aident à rester en bonne santé.',
      nb: 4,
    },
  ],
  normal: [
    {
      id: 'aliments',
      prompt: 'Associe chaque aliment à sa famille.',
      relation: 'aliment → famille',
      duos: [
        { l: 'la pomme', r: 'fruits et légumes', n: 'n' },
        { l: 'le pain', r: 'féculents', n: 'n' },
        { l: 'le yaourt', r: 'produits laitiers', n: 'n' },
        { l: 'le poisson', r: 'viande, poisson, œufs', n: 'n' },
        { l: 'le gâteau', r: 'produits sucrés', n: 'n' },
      ],
      ex: 'Chaque aliment appartient à une famille ; on en mange de plusieurs familles chaque jour.',
      nb: 5,
    },
    {
      id: 'gestes',
      prompt: 'Associe chaque geste à son image.',
      relation: 'geste → image',
      duos: [
        { l: 'se brosser les dents', r: '🪥', n: 'n' },
        { l: 'se laver les mains', r: '🧼', n: 'n' },
        { l: 'dormir', r: '🛏️', n: 'n' },
        { l: 'boire de l’eau', r: '💧', n: 'n' },
        { l: 'faire du sport', r: '⚽', n: 'n' },
        { l: 'manger des fruits', r: '🍎', n: 'n' },
        { l: 'se moucher', r: '🤧', n: 'n' },
      ],
      ex: 'Ce sont des gestes qui aident à rester en bonne santé.',
    },
  ],
  plus_loin: [
    {
      id: 'os',
      prompt: 'Associe chaque os à la partie du corps où il se trouve.',
      relation: 'os → partie du corps',
      duos: [
        { l: 'le crâne', r: 'la tête', n: 'p' },
        { l: 'les côtes', r: 'la poitrine', n: 'p' },
        { l: 'la colonne vertébrale', r: 'le dos', n: 'p' },
        { l: 'le fémur', r: 'la cuisse', n: 'p' },
        { l: 'les phalanges', r: 'les doigts', n: 'p' },
      ],
      ex: 'Le crâne protège le cerveau, les côtes le cœur et les poumons ; le fémur est l’os de la cuisse.',
      nb: 5,
    },
  ],
};

export const VIVANT: ContentModule = {
  'CE1.QLM.VIVANT.CARACT': {
    pools: {
      mcq: qcmPool(CARACT_QCM, { guillotine: true }),
      true_false: vfPool(CARACT_VF),
      ordering: ordrePool(CARACT_ORDRES),
    },
    gens: { classification: triGen(CARACT_TRIS) },
  },
  'CE1.QLM.VIVANT.CYCLES': {
    pools: {
      mcq: qcmPool(CYCLES_QCM, { guillotine: true }),
      true_false: vfPool(CYCLES_VF),
      ordering: ordrePool(CYCLES_ORDRES),
    },
    gens: { classification: triGen(CYCLES_TRIS), pairing: paireGen(CYCLES_PAIRES) },
  },
  'CE1.QLM.VIVANT.ALIM': {
    pools: {
      mcq: qcmPool(ALIM_QCM, { guillotine: true }),
      true_false: vfPool(ALIM_VF),
      ordering: ordrePool(ALIM_ORDRES),
    },
    gens: { classification: triGen(ALIM_TRIS), pairing: paireGen(ALIM_PAIRES) },
  },
  'CE1.QLM.CORPS.SANTE': {
    pools: {
      mcq: qcmPool(SANTE_QCM, { guillotine: true }),
      true_false: vfPool(SANTE_VF),
      ordering: ordrePool(SANTE_ORDRES),
    },
    gens: { classification: triGen(SANTE_TRIS), pairing: paireGen(SANTE_PAIRES) },
  },
};
