/**
 * CM2 — mots de la grammaire à savoir écrire (BO n°16 du 17/04/2025 : l'élève utilise le métalangage
 * de la grammaire — nature, fonction, types de phrases — et mémorise l'orthographe des mots invariables
 * fréquents : prépositions, conjonctions de coordination). Ils rendent jouables les jeux d'écriture
 * (Ascension, Appareil photo, Wordle, Mots croisés…). Définitions d'enfant, sans le mot lui-même ;
 * phrase-contexte pour les mots qui ont un homophone (mais / mes, car / quart, sans / cent…).
 */
import type { M } from '../../generators/mots-cles';

export const MOTS_GRAMMAIRE_CM2: Record<string, readonly M[]> = {
  'CM2.FR.GRAM.TYPES': [
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['point', 'signe qui termine une phrase', 'f', 'Je mets un point à la fin de la phrase.'],
    ['question', 'phrase qui demande quelque chose', 'f'],
    ['majuscule', 'grande lettre au début d’une phrase', 'f'],
    ['virgule', 'petit signe qui sépare des mots ou des groupes dans une phrase', 'f'],
    ['ordre', 'ce que donne une phrase impérative', 'f'],
    ['déclarative', 'se dit d’une phrase qui donne une information', 'n'],
    ['interrogative', 'se dit d’une phrase qui pose une question', 'n'],
    ['impérative', 'se dit d’une phrase qui donne un ordre ou un conseil', 'n'],
    ['exclamative', 'se dit d’une phrase qui exprime un sentiment fort', 'n'],
    ['négative', 'se dit d’une phrase avec ne… pas, ne… jamais', 'n'],
    ['affirmative', 'se dit d’une phrase qui n’est pas à la forme négative', 'n'],
    ['type', 'déclaratif, interrogatif ou impératif : c’est le ___ de la phrase', 'n'],
    ['forme', 'négative ou exclamative : c’est la ___ de la phrase', 'n'],
    ['tiret', 'petit trait qui marque le changement de personne dans un dialogue', 'p'],
    ['guillemets', 'signes « » qui encadrent les paroles de quelqu’un', 'p'],
    ['ponctuation', 'ensemble des signes : point, virgule, point d’interrogation…', 'p'],
    ['interrogation', 'le point d’___ termine une question', 'p'],
    ['exclamation', 'le point d’___ termine une phrase qui exprime un sentiment fort', 'p'],
  ],
  'CM2.FR.GRAM.SUJET': [
    ['sujet', 'il répond à la question « Qui est-ce qui ? » posée devant le verbe', 'f'],
    ['verbe', 'mot qui se conjugue', 'f'],
    ['pronom', 'mot qui remplace un nom : il, elle, ils, elles…', 'f'],
    ['nom', 'mot qui désigne une personne, un animal ou une chose', 'f', 'Le mot « chat » est un nom.'],
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['accord', 'le verbe le fait avec son sujet', 'f'],
    ['inversé', 'se dit du sujet placé après le verbe', 'n'],
    ['groupe', 'le ___ nominal : un nom et les mots qui l’accompagnent', 'n'],
    ['nominal', 'le groupe ___ : par exemple « le petit chat gris »', 'n'],
    ['infinitif', 'forme du verbe qui n’est pas conjuguée : chanter, finir, prendre', 'n'],
    ['personne', 'la 1re, la 2e ou la 3e : elle indique qui fait l’action', 'n'],
    ['propre', 'un nom ___ commence par une majuscule : Léa, Paris', 'n'],
    ['inversion', 'fait de placer le sujet après le verbe', 'p'],
    ['déterminant', 'petit mot devant le nom : le, une, des, mon, ce…', 'p'],
    ['conjugaison', 'ensemble des formes d’un verbe selon la personne et le temps', 'p'],
  ],
  'CM2.FR.GRAM.GROUPES': [
    ['groupe', 'ensemble de mots qui vont ensemble dans la phrase', 'f'],
    ['sujet', 'il dit de qui ou de quoi on parle', 'f'],
    ['verbe', 'mot qui se conjugue', 'f'],
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['déplacer', 'changer de place un groupe de mots', 'f'],
    ['supprimer', 'enlever un groupe de mots', 'f'],
    ['verbal', 'le groupe ___ : il est construit autour du mot qui se conjugue', 'n'],
    ['circonstanciel', 'se dit d’un complément qu’on peut déplacer ou supprimer', 'n'],
    ['complément', 'mot ou groupe de mots qui complète le verbe ou le nom', 'n'],
    ['nominal', 'le groupe ___ : par exemple « le petit chat gris »', 'n'],
    ['déplaçable', 'qu’on peut changer de place dans la phrase', 'n'],
    ['supprimable', 'qu’on peut enlever de la phrase', 'n'],
    ['essentiel', 'se dit d’un complément qu’on ne peut pas enlever', 'p'],
    ['manipulation', 'fait de déplacer, supprimer ou remplacer des mots pour analyser une phrase', 'p'],
    ['suppression', 'fait d’enlever un groupe de mots', 'p'],
  ],
  'CM2.FR.GRAM.COD_COI': [
    ['verbe', 'mot qui se conjugue', 'f'],
    ['complément', 'mot ou groupe de mots qui complète le verbe', 'f'],
    ['objet', 'le complément d’___ dit sur quoi porte l’action', 'f'],
    ['pronom', 'mot qui remplace un nom : le, la, les, lui, leur…', 'f'],
    ['direct', 'se dit du complément construit sans préposition', 'f'],
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['indirect', 'se dit du complément introduit par à ou de', 'n'],
    ['préposition', 'petit mot invariable comme à ou de', 'n'],
    ['leur', 'pronom qui remplace « à eux » ou « à elles » devant le verbe', 'n', 'Je leur parle.'],
    ['remplacer', 'mettre un mot à la place d’un autre', 'n'],
    ['invariable', 'qui ne change jamais d’orthographe', 'n'],
    ['construction', 'manière dont un verbe se construit, avec ou sans préposition', 'p'],
    ['substitution', 'remplacement d’un mot par un autre', 'p'],
    ['pronominalisation', 'remplacement d’un groupe de mots par un pronom', 'p'],
  ],
  'CM2.FR.GRAM.ATTRIBUT': [
    ['sujet', 'il répond à la question « Qui est-ce qui ? » posée devant le verbe', 'f'],
    ['être', 'le plus fréquent des verbes d’état', 'f'],
    ['adjectif', 'mot qui dit comment est le nom', 'f'],
    ['verbe', 'mot qui se conjugue', 'f'],
    ['accord', 'l’adjectif le fait avec le nom ou le sujet', 'f'],
    ['état', 'un verbe d’___ : être, sembler, devenir…', 'f'],
    ['attribut', 'il dit comment est le sujet, après un verbe d’état', 'n'],
    ['sembler', 'verbe d’état qui veut dire « avoir l’air »', 'n'],
    ['devenir', 'verbe d’état : commencer à être', 'n'],
    ['paraître', 'verbe d’état proche de « sembler », plus soutenu', 'n'],
    ['rester', 'verbe d’état : continuer à être', 'n'],
    ['féminin', 'genre des noms comme « la table »', 'n'],
    ['demeurer', 'verbe d’état, synonyme soutenu de « rester »', 'p'],
    ['pluriel', 'nombre qui désigne plusieurs : les chats', 'f'],
    ['identification', 'fait de reconnaître la fonction d’un mot ou d’un groupe', 'p'],
  ],
  'CM2.FR.GRAM.CC': [
    ['temps', 'le complément de ___ répond à « quand ? »', 'f'],
    ['lieu', 'le complément de ___ répond à « où ? »', 'f'],
    ['cause', 'le complément de ___ répond à « pourquoi ? »', 'f'],
    ['quand', 'mot de la question qui trouve le complément de temps', 'f', 'Quand pars-tu ?'],
    ['pourquoi', 'mot de la question qui trouve le complément de cause', 'f'],
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['circonstanciel', 'se dit d’un complément qu’on peut déplacer ou supprimer', 'n'],
    ['complément', 'mot ou groupe de mots qui complète le verbe ou la phrase', 'n'],
    ['déplaçable', 'qu’on peut changer de place dans la phrase', 'n'],
    ['supprimable', 'qu’on peut enlever de la phrase', 'n'],
    ['hier', 'le jour avant aujourd’hui', 'n'],
    ['demain', 'le jour après aujourd’hui', 'n'],
    ['manière', 'le complément de ___ répond à « comment ? »', 'p'],
    ['adverbe', 'mot invariable qui peut être complément : hier, ici, vite…', 'p'],
    ['autrefois', 'il y a longtemps', 'p'],
  ],
  'CM2.FR.GRAM.NATURE_FONCTION': [
    ['nom', 'mot qui désigne une personne, un animal ou une chose', 'f', 'Le mot « chat » est un nom.'],
    ['verbe', 'mot qui se conjugue', 'f'],
    ['adjectif', 'mot qui dit comment est le nom', 'f'],
    ['sujet', 'fonction du groupe qui répond à « Qui est-ce qui ? »', 'f'],
    ['pronom', 'mot qui remplace un nom', 'f'],
    ['déterminant', 'petit mot devant le nom : le, une, des, mon, ce…', 'f'],
    ['nature', 'classe d’un mot : nom, verbe, adjectif…, comme dans le dictionnaire', 'n'],
    ['fonction', 'rôle d’un mot ou d’un groupe dans la phrase', 'n'],
    ['adverbe', 'mot invariable qui modifie le sens d’un verbe : vite, bien, hier…', 'n'],
    ['préposition', 'petit mot invariable comme à, de, dans, pour', 'n'],
    [
      'conjonction',
      'mot invariable qui relie des mots ou des propositions : mais, et, car, quand, parce que…',
      'n',
    ],
    ['complément', 'fonction d’un groupe qui complète le verbe ou la phrase', 'n'],
    ['attribut', 'fonction de l’adjectif qui dit comment est le sujet après un verbe d’état', 'n'],
    ['épithète', 'fonction de l’adjectif placé juste à côté du nom', 'p'],
    ['coordination', 'une conjonction de ___ relie deux mots ou deux phrases', 'p'],
    ['invariable', 'qui ne change jamais d’orthographe', 'p'],
  ],
  'CM2.FR.GRAM.CLASSES': [
    ['avec', 'préposition : en compagnie de', 'f', 'Je joue avec mon frère.'],
    ['dans', 'préposition : à l’intérieur de', 'f', 'Le chat dort dans son panier.'],
    ['pour', 'préposition qui indique le but', 'f', 'Je travaille pour réussir.'],
    ['mais', 'conjonction qui marque une opposition', 'f', 'Il fait beau, mais il fait froid.'],
    ['sans', 'préposition : contraire de « avec »', 'f', 'Il sort sans son manteau.'],
    ['sous', 'préposition : contraire de « sur »', 'f', 'Le chien dort sous la table.'],
    ['préposition', 'mot invariable qui introduit un complément : à, de, dans, pour…', 'n'],
    [
      'conjonction',
      'mot invariable qui relie des mots ou des propositions : mais, et, car, quand, parce que…',
      'n',
    ],
    ['pendant', 'préposition : au cours de', 'n', 'Il a dormi pendant le film.'],
    ['depuis', 'préposition : à partir d’un moment passé', 'n', 'J’habite ici depuis deux ans.'],
    ['donc', 'conjonction qui annonce une conséquence', 'n', 'Il pleut, donc je prends mon parapluie.'],
    ['car', 'conjonction qui annonce une cause', 'n', 'Je reste à la maison, car il pleut.'],
    ['parmi', 'préposition : au milieu de plusieurs', 'n', 'Il se cache parmi les arbres.'],
    ['malgré', 'préposition : en dépit de', 'p', 'Il sort malgré la pluie.'],
    ['coordination', 'une conjonction de ___ relie deux mots ou deux propositions', 'p'],
    ['possessif', 'se dit d’un déterminant comme mon, ta, leurs', 'p'],
    ['démonstratif', 'se dit d’un déterminant comme ce, cette, ces', 'p'],
  ],
  'CM2.FR.GRAM.GN': [
    ['nom', 'mot qui désigne une personne, un animal ou une chose', 'f', 'Le mot « chat » est un nom.'],
    ['adjectif', 'mot qui dit comment est le nom', 'f'],
    ['déterminant', 'petit mot devant le nom : le, une, des, mon, ce…', 'f'],
    ['groupe', 'ensemble de mots qui vont ensemble', 'f'],
    ['accord', 'l’adjectif le fait avec le nom', 'f'],
    ['féminin', 'genre des noms comme « la table »', 'f'],
    ['épithète', 'se dit de l’adjectif placé juste à côté du nom', 'n'],
    ['complément', 'le ___ du nom : « de bois » dans « une table de bois »', 'n'],
    ['expansion', 'mot ou groupe qui enrichit le nom', 'n'],
    ['préposition', 'petit mot qui introduit le complément du nom : de, à, en…', 'n'],
    ['nominal', 'le groupe ___ : par exemple « le petit chat gris »', 'n'],
    ['pluriel', 'nombre qui désigne plusieurs : les chats', 'n'],
    ['apposition', 'groupe séparé du nom par une virgule, qui le précise', 'p'],
    ['enrichissement', 'fait d’ajouter des mots au nom pour le préciser', 'p'],
    ['masculin', 'genre des noms comme « le livre »', 'n'],
  ],
  'CM2.FR.GRAM.COMPLEXE': [
    ['phrase', 'suite de mots qui a un sens, avec une majuscule et un point', 'f'],
    ['verbe', 'mot qui se conjugue', 'f'],
    ['simple', 'se dit d’une phrase qui n’a qu’un verbe conjugué', 'f'],
    ['point', 'signe qui termine une phrase', 'f', 'Je mets un point à la fin de la phrase.'],
    ['virgule', 'petit signe qui sépare des mots ou des groupes', 'f'],
    [
      'mais',
      'conjonction qui relie deux propositions en les opposant',
      'f',
      'Il fait beau, mais il fait froid.',
    ],
    ['complexe', 'se dit d’une phrase qui a plusieurs verbes conjugués', 'n'],
    ['proposition', 'partie de phrase organisée autour d’un verbe conjugué', 'n'],
    ['conjugué', 'se dit d’un verbe qui change selon le sujet et le temps', 'n'],
    ['juxtaposée', 'se dit d’une proposition reliée à une autre par une virgule', 'p'],
    ['coordonnée', 'se dit d’une proposition reliée par mais, ou, et, donc, or, ni, car', 'p'],
    [
      'conjonction',
      'mot invariable qui relie des mots ou des propositions : mais, et, car, quand, parce que…',
      'n',
    ],
    ['subordonnée', 'proposition qui dépend d’une autre (6e)', 'p'],
    ['principale', 'proposition dont dépend une subordonnée (6e)', 'p'],
    ['juxtaposition', 'fait de relier des propositions par une virgule', 'p'],
  ],
};
