/**
 * Anglais CM2 (attendus de fin de CM2 : niveau A1 consolidé — programme de langues vivantes en vigueur ;
 * programme LVER BO n°12 du 19/03/2026, date d'application à vérifier).
 * Règles : tout QCM anglais a un `spoken` en anglais (ce que l'on entend) ; les paires mot ↔ emoji suivent
 * la convention de Jacques a dit (`meta.consigne`) ; les réponses orales listent leurs variantes acceptées.
 */
import type { Fiche, Niv, Oral, Paires, Qcm, Vf } from './outils';

/** QCM en anglais : la question affichée est aussi celle que l'on entend (sauf `spoken` explicite). */
const en = (q: Omit<Qcm, 'spoken'> & { spoken?: string }): Qcm => ({ ...q, spoken: q.spoken ?? q.q });

/* ------------------------------------------------------------------ */
/* Nombres jusqu'à 100                                                 */
/* ------------------------------------------------------------------ */

const UNITES = [
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
  'sixteen',
  'seventeen',
  'eighteen',
  'nineteen',
];
const DIZAINES = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];

/** Nombre en toutes lettres (anglais britannique), de 0 à 100. */
export function nombreAnglais(n: number): string {
  if (n === 100) return 'one hundred';
  if (n < 20) return UNITES[n]!;
  const d = Math.floor(n / 10);
  const u = n % 10;
  return u ? `${DIZAINES[d]}-${UNITES[u]}` : DIZAINES[d]!;
}

/** Distracteurs plausibles : 13 ↔ 30, chiffres inversés, ±1, ±10. Le premier sert au niveau Facile. */
function voisins(n: number): string[] {
  const out: number[] = [];
  const add = (x: number) => {
    if (x >= 0 && x <= 100 && x !== n && !out.includes(x)) out.push(x);
  };
  add(n < 10 ? n + 10 : n > 90 ? n - 50 : n + 25 > 100 ? n - 25 : n + 25);
  if (n >= 13 && n <= 19) add((n - 10) * 10);
  if (n >= 30 && n <= 90 && n % 10 === 0) add(n / 10 + 10);
  if (n >= 21 && n % 10 !== 0 && n < 100) add((n % 10) * 10 + Math.floor(n / 10));
  add(n + 1);
  add(n - 1);
  add(n + 10);
  add(n - 10);
  return out.map(String);
}

const NOMBRES_NIV: [Niv, number[]][] = [
  ['f', [3, 7, 8, 11, 12, 15, 17, 20]],
  ['n', [21, 34, 45, 47, 52, 66, 73, 88, 99, 100]],
  ['p', [13, 30, 14, 40, 16, 60, 18, 80, 19, 90]],
];

const NUMBERS: Fiche = {
  lecon: 'CM2.EN.NUMBERS',
  en: true,
  qcm: [
    ...NOMBRES_NIV.flatMap(([niv, ns]) =>
      ns.map((n): Qcm => ({
        id: `ecoute-${n}`,
        niv,
        q: 'Écoute : quel nombre entends-tu ?',
        spoken: nombreAnglais(n),
        r: String(n),
        f: voisins(n),
        e: `« ${nombreAnglais(n)} » = ${n}.`,
      })),
    ),
    en({
      id: 'plus-5',
      niv: 'f',
      q: 'Ten plus five?',
      r: '15',
      f: ['50', '14', '16'],
      e: 'Ten plus five equals fifteen : 10 + 5 = 15.',
    }),
    en({
      id: 'plus-30',
      niv: 'n',
      q: 'Twenty plus thirty?',
      r: '50',
      f: ['15', '40', '60'],
      e: 'Twenty plus thirty equals fifty : 20 + 30 = 50.',
    }),
    en({
      id: 'times',
      niv: 'p',
      q: 'Three times four?',
      r: '12',
      f: ['7', '34', '20'],
      e: 'Three times four equals twelve : 3 × 4 = 12.',
    }),
    en({
      id: 'minus',
      niv: 'p',
      q: 'Fifty minus ten?',
      r: '40',
      f: ['14', '60', '45'],
      e: 'Fifty minus ten equals forty : 50 − 10 = 40.',
    }),
  ],
  oral: NOMBRES_NIV.flatMap(([niv, ns]) =>
    ns.slice(0, 5).map((n): Oral => ({
      id: `dis-${n}`,
      niv,
      prompt: `Dis ce nombre en anglais : ${n}`,
      spoken: 'Dis ce nombre en anglais.',
      r: nombreAnglais(n),
      ok: [
        nombreAnglais(n),
        nombreAnglais(n).replace('-', ' '),
        String(n),
        ...(n === 100 ? ['a hundred'] : []),
      ],
      e: `${n} se dit « ${nombreAnglais(n)} ».`,
    })),
  ),
  vf: NOMBRES_NIV.flatMap(([niv, ns]) =>
    ns.map((n, i): Vf => {
      const vrai = i % 2 === 0;
      const montre = vrai ? n : Number(voisins(n)[1] ?? voisins(n)[0]);
      return {
        id: `vf-${n}`,
        niv,
        s: `« ${nombreAnglais(n)} » = ${montre}`,
        v: vrai,
        e: `« ${nombreAnglais(n)} » = ${n}.`,
      };
    }),
  ),
  paires: NOMBRES_NIV.map(([niv, ns]): Paires => ({
    id: `nombres-${niv}`,
    niv,
    prompt: 'Associe chaque nombre écrit en anglais à son écriture en chiffres.',
    relation: 'mot → nombre',
    pairs: ns.slice(0, 6).map((n) => [nombreAnglais(n), String(n)]),
    e: ns
      .slice(0, 6)
      .map((n) => `${nombreAnglais(n)} = ${n}`)
      .join(' ; '),
  })),
};

/* ------------------------------------------------------------------ */
/* Leçons                                                              */
/* ------------------------------------------------------------------ */

const PRESENTER: Fiche = {
  lecon: 'CM2.EN.PRESENTER',
  en: true,
  paires: [
    {
      id: 'famille',
      niv: 'f',
      prompt: 'Écoute le mot anglais et touche la bonne image.',
      relation: 'mot → image',
      consigne: 'point to the {mot}',
      pairs: [
        ['mother', '👩'],
        ['father', '👨'],
        ['sister', '👧'],
        ['brother', '👦'],
        ['grandmother', '👵'],
        ['grandfather', '👴'],
        ['baby', '👶'],
      ],
      e: 'Mother = mère, father = père, sister = sœur, brother = frère, grandmother = grand-mère, grandfather = grand-père, baby = bébé.',
    },
    {
      id: 'expressions',
      niv: 'n',
      prompt: 'Associe chaque phrase anglaise à sa traduction.',
      relation: 'anglais → français',
      pairs: [
        ['Hello!', 'Bonjour !'],
        ['Goodbye!', 'Au revoir !'],
        ['What’s your name?', 'Comment t’appelles-tu ?'],
        ['How old are you?', 'Quel âge as-tu ?'],
        ['Where do you live?', 'Où habites-tu ?'],
      ],
      e: 'Ce sont les questions pour se présenter.',
    },
  ],
  qcm: [
    {
      id: 'name',
      niv: 'f',
      q: 'Que veut dire « What’s your name? » ?',
      spoken: 'What’s your name?',
      r: 'Comment t’appelles-tu ?',
      f: ['Quel âge as-tu ?', 'Où habites-tu ?', 'Comment vas-tu ?'],
      e: '« What’s your name? » = Comment t’appelles-tu ? On répond « My name is… ».',
    },
    {
      id: 'old',
      niv: 'f',
      q: 'Que veut dire « How old are you? » ?',
      spoken: 'How old are you?',
      r: 'Quel âge as-tu ?',
      f: ['Comment t’appelles-tu ?', 'Où habites-tu ?', 'Comment vas-tu ?'],
      e: 'On répond « I’m ten. » (J’ai dix ans).',
    },
    {
      id: 'live',
      niv: 'n',
      q: 'Que veut dire « Where do you live? » ?',
      spoken: 'Where do you live?',
      r: 'Où habites-tu ?',
      f: ['Quel âge as-tu ?', 'Comment vas-tu ?', 'Qu’aimes-tu ?'],
      e: 'On répond « I live in Lyon. » (J’habite à Lyon).',
    },
    {
      id: 'brothers',
      niv: 'n',
      q: 'Que veut dire « I’ve got two brothers. » ?',
      spoken: 'I’ve got two brothers.',
      r: 'J’ai deux frères.',
      f: ['J’ai deux sœurs.', 'J’ai deux chats.', 'J’ai deux ans.'],
      e: 'Brother = frère ; « I’ve got » = j’ai.',
    },
    en({
      id: 'answer-old',
      niv: 'n',
      q: 'How old are you?',
      r: 'I’m ten.',
      f: ['I’m Tom.', 'I’m fine.', 'I live in Paris.'],
      e: 'À « How old are you? », on répond avec son âge : « I’m ten. »',
    }),
    en({
      id: 'answer-fine',
      niv: 'n',
      q: 'How are you?',
      r: 'I’m fine, thank you.',
      f: ['I’m ten.', 'My name is Léa.', 'Goodbye!'],
      e: '« How are you? » = Comment vas-tu ? On répond « I’m fine, thank you. »',
    }),
    en({
      id: 'colour',
      niv: 'p',
      q: 'What’s your favourite colour?',
      r: 'My favourite colour is blue.',
      f: ['I’m eleven.', 'I’ve got a dog.', 'It’s Monday.'],
      e: '« Favourite » = préféré.',
    }),
    en({
      id: 'is',
      niv: 'p',
      q: 'Which sentence is correct?',
      r: 'She is my sister.',
      f: ['She are my sister.', 'She am my sister.', 'She be my sister.'],
      e: 'I am, you are, he is, she is : avec « she », on dit « is ».',
    }),
    {
      id: 'like',
      niv: 'f',
      q: 'Que veut dire « I like football » ?',
      spoken: 'I like football.',
      r: 'J’aime le football.',
      f: ['Je n’aime pas le football.', 'Je joue au tennis.', 'Je regarde la télévision.'],
      e: '« I like » = j’aime.',
    },
    {
      id: 'dont-like',
      niv: 'n',
      q: 'Que veut dire « I don’t like carrots » ?',
      spoken: 'I don’t like carrots.',
      r: 'Je n’aime pas les carottes.',
      f: ['J’aime les carottes.', 'Je mange des carottes.', 'Je n’ai pas de carottes.'],
      e: '« I don’t like » = je n’aime pas.',
    },
  ],
  oral: [
    {
      id: 'hello',
      niv: 'f',
      prompt: 'Dis bonjour en anglais 👋',
      r: 'Hello!',
      ok: ['hello', 'hi', 'hello there'],
      e: 'Pour dire bonjour : « Hello! » ou « Hi! ».',
    },
    {
      id: 'name',
      niv: 'f',
      prompt: 'Dis en anglais : « Je m’appelle… » puis ton prénom',
      r: 'My name is …',
      ok: ['my name is', 'i am', 'i’m', 'im'],
      e: 'On dit « My name is… » ou « I’m… ».',
    },
    {
      id: 'goodbye',
      niv: 'f',
      prompt: 'Dis au revoir en anglais 👋',
      r: 'Goodbye!',
      ok: ['goodbye', 'good bye', 'bye', 'bye bye'],
      e: 'Au revoir = « Goodbye! » ou « Bye! ».',
    },
    {
      id: 'ten',
      niv: 'n',
      prompt: 'Dis en anglais : « J’ai dix ans. »',
      r: 'I’m ten.',
      ok: ['i’m ten', 'i am ten', 'im ten', 'i’m ten years old', 'i am ten years old'],
      e: 'En anglais, on « est » dix ans : « I’m ten. »',
    },
    {
      id: 'mother',
      niv: 'n',
      prompt: 'Dis en anglais : « ma mère » 👩',
      r: 'my mother',
      ok: ['my mother', 'my mum', 'my mom', 'mother', 'mum'],
      e: 'Ma mère = « my mother » ou « my mum ».',
    },
    {
      id: 'apples',
      niv: 'p',
      prompt: 'Dis en anglais : « J’aime les pommes. » 🍎',
      r: 'I like apples.',
      ok: ['i like apples'],
      e: '« I like apples. »',
    },
  ],
  vf: [
    { id: 'sister', niv: 'f', s: '« Sister » veut dire « sœur ».', v: true, e: 'Sister = sœur.' },
    {
      id: 'father',
      niv: 'f',
      s: '« Father » veut dire « mère ».',
      v: false,
      e: 'Father = père ; mother = mère.',
    },
    {
      id: 'goodbye',
      niv: 'f',
      s: '« Goodbye » veut dire « au revoir ».',
      v: true,
      e: 'Goodbye = au revoir.',
    },
    { id: 'brother', niv: 'f', s: '« Brother » veut dire « frère ».', v: true, e: 'Brother = frère.' },
    {
      id: 'hello',
      niv: 'f',
      s: '« Hello » veut dire « merci ».',
      v: false,
      e: 'Hello = bonjour ; merci = thank you.',
    },
    {
      id: 'old',
      niv: 'n',
      s: '« How old are you? » veut dire « Comment t’appelles-tu ? ».',
      v: false,
      e: 'Cela veut dire « Quel âge as-tu ? ».',
    },
    {
      id: 'grandmother',
      niv: 'n',
      s: '« Grandmother » veut dire « grand-mère ».',
      v: true,
      e: 'Grandmother = grand-mère.',
    },
    {
      id: 'fine',
      niv: 'n',
      s: 'À « How are you? », on peut répondre « I’m fine, thank you. ».',
      v: true,
      e: 'Cela veut dire « Je vais bien, merci. ».',
    },
    {
      id: 'dont',
      niv: 'n',
      s: '« I don’t like » veut dire « j’aime ».',
      v: false,
      e: '« I don’t like » = je n’aime pas.',
    },
    {
      id: 'lyon',
      niv: 'p',
      s: '« I live in Lyon » veut dire « J’habite à Lyon ».',
      v: true,
      e: 'Live = habiter.',
    },
    {
      id: 'sisters',
      niv: 'p',
      s: '« She’s got two sisters » veut dire « Elle a deux frères ».',
      v: false,
      e: 'Sisters = sœurs.',
    },
    {
      id: 'favourite',
      niv: 'p',
      s: '« My favourite » veut dire « mon préféré ».',
      v: true,
      e: 'Favourite = préféré.',
    },
  ],
};

const DESCRIBE: Fiche = {
  lecon: 'CM2.EN.DESCRIBE',
  en: true,
  paires: [
    {
      id: 'vetements',
      niv: 'f',
      prompt: 'Écoute le vêtement et touche la bonne image.',
      relation: 'mot → image',
      pairs: [
        ['T-shirt', '👕'],
        ['jeans', '👖'],
        ['dress', '👗'],
        ['trainers', '👟'],
        ['cap', '🧢'],
        ['coat', '🧥'],
        ['scarf', '🧣'],
        ['socks', '🧦'],
        ['gloves', '🧤'],
      ],
      e: 'T-shirt = tee-shirt, jeans = jean, dress = robe, trainers = baskets, cap = casquette, coat = manteau, scarf = écharpe, socks = chaussettes, gloves = gants.',
    },
    {
      id: 'emotions',
      niv: 'n',
      prompt: 'Écoute et touche le bon visage.',
      relation: 'mot → image',
      consigne: 'point to the {mot} face',
      pairs: [
        ['happy', '😀'],
        ['sad', '😢'],
        ['angry', '😠'],
        ['tired', '😴'],
        ['scared', '😨'],
        ['surprised', '😮'],
      ],
      e: 'Happy = content, sad = triste, angry = en colère, tired = fatigué, scared = effrayé, surprised = surpris.',
    },
    {
      id: 'corps',
      niv: 'f',
      prompt: 'Simon says… touche la bonne partie du corps.',
      relation: 'consigne → image',
      pairs: [
        ['touch your nose', '👃'],
        ['touch your ear', '👂'],
        ['touch your eyes', '👀'],
        ['touch your mouth', '👄'],
        ['touch your hand', '✋'],
        ['touch your foot', '🦶'],
        ['touch your leg', '🦵'],
      ],
      e: 'Nose = nez, ear = oreille, eyes = yeux, mouth = bouche, hand = main, foot = pied, leg = jambe.',
    },
  ],
  qcm: [
    {
      id: 'blue-eyes',
      niv: 'n',
      q: 'Que veut dire « He’s got blue eyes » ?',
      spoken: 'He’s got blue eyes.',
      r: 'Il a les yeux bleus.',
      f: ['Il a les cheveux bleus.', 'Elle a les yeux verts.', 'Il a un pull bleu.'],
      e: 'Eyes = yeux ; en anglais, la couleur se place avant le nom.',
    },
    {
      id: 'tall',
      niv: 'f',
      q: 'Que veut dire « She’s tall » ?',
      spoken: 'She’s tall.',
      r: 'Elle est grande.',
      f: ['Elle est petite.', 'Il est grand.', 'Elle est fatiguée.'],
      e: 'Tall = grand ; short = petit.',
    },
    {
      id: 'coat',
      niv: 'n',
      q: 'Que veut dire « I’m wearing a red coat » ?',
      spoken: 'I’m wearing a red coat.',
      r: 'Je porte un manteau rouge.',
      f: ['Je porte une robe rouge.', 'J’achète un manteau rouge.', 'J’ai un chapeau rouge.'],
      e: '« I’m wearing » = je porte ; coat = manteau.',
    },
    en({
      id: 'hair',
      niv: 'p',
      q: 'Which sentence is correct?',
      r: 'She has got long hair.',
      f: ['She have got long hair.', 'She has got hair long.', 'She got has long hair.'],
      e: 'Avec « she » : « has got » ; l’adjectif se place avant le nom.',
    }),
    en({
      id: 'tshirt',
      niv: 'n',
      q: 'Which sentence is correct?',
      r: 'I’ve got a blue T-shirt.',
      f: ['I’ve got a T-shirt blue.', 'I has got a blue T-shirt.', 'I’ve got blue a T-shirt.'],
      e: 'La couleur se place avant le nom : « a blue T-shirt ».',
    }),
    {
      id: 'happy',
      niv: 'f',
      q: 'Écoute : quelle image correspond ?',
      spoken: 'He’s happy.',
      r: '😀',
      f: ['😢', '😠', '😴'],
      e: 'Happy = content.',
    },
    {
      id: 'dress',
      niv: 'f',
      q: 'Écoute : quelle image correspond ?',
      spoken: 'She’s wearing a dress.',
      r: '👗',
      f: ['👖', '🧢', '🧦'],
      e: 'Dress = robe.',
    },
    {
      id: 'gloves',
      niv: 'n',
      q: 'Écoute : quelle image correspond ?',
      spoken: 'A pair of gloves.',
      r: '🧤',
      f: ['🧦', '🧣', '👟'],
      e: 'Gloves = gants.',
    },
    {
      id: 'short-hair',
      niv: 'n',
      q: 'Que veut dire « short hair » ?',
      spoken: 'short hair',
      r: 'les cheveux courts',
      f: ['les cheveux longs', 'les cheveux bouclés', 'un short'],
      e: 'Attention : « short » veut dire « court » ou « petit ».',
    },
    {
      id: 'curly',
      niv: 'p',
      q: 'Que veut dire « curly hair » ?',
      spoken: 'curly hair',
      r: 'les cheveux bouclés',
      f: ['les cheveux raides', 'les cheveux courts', 'les cheveux roux'],
      e: 'Curly = bouclé ; straight = raide.',
    },
  ],
  oral: [
    {
      id: 'tshirt',
      niv: 'f',
      prompt: 'Dis en anglais : un tee-shirt 👕',
      r: 'a T-shirt',
      ok: ['t-shirt', 'a t-shirt', 't shirt', 'tshirt', 'tee shirt'],
      e: 'Un tee-shirt = « a T-shirt ».',
    },
    {
      id: 'happy',
      niv: 'f',
      prompt: 'Dis en anglais : content 😀',
      r: 'happy',
      ok: ['happy', 'i’m happy', 'i am happy'],
      e: 'Content = « happy ».',
    },
    {
      id: 'tall',
      niv: 'n',
      prompt: 'Dis en anglais : « Il est grand. »',
      r: 'He’s tall.',
      ok: ['he’s tall', 'he is tall', 'hes tall'],
      e: '« He’s tall. »',
    },
    {
      id: 'scarf',
      niv: 'n',
      prompt: 'Dis en anglais : une écharpe 🧣',
      r: 'a scarf',
      ok: ['scarf', 'a scarf'],
      e: 'Une écharpe = « a scarf ».',
    },
    {
      id: 'eyes',
      niv: 'p',
      prompt: 'Dis en anglais : « J’ai les yeux marron. »',
      r: 'I’ve got brown eyes.',
      ok: ['i’ve got brown eyes', 'i have got brown eyes', 'i have brown eyes', 'ive got brown eyes'],
      e: '« I’ve got brown eyes. »',
    },
  ],
  vf: [
    { id: 'tall', niv: 'f', s: '« Tall » veut dire « grand ».', v: true, e: 'Tall = grand.' },
    {
      id: 'sad',
      niv: 'f',
      s: '« Sad » veut dire « content ».',
      v: false,
      e: 'Sad = triste ; happy = content.',
    },
    { id: 'dress', niv: 'f', s: '« Dress » veut dire « robe ».', v: true, e: 'Dress = robe.' },
    { id: 'angry', niv: 'f', s: '« Angry » veut dire « en colère ».', v: true, e: 'Angry = en colère.' },
    { id: 'trainers', niv: 'f', s: '« Trainers » veut dire « train ».', v: false, e: 'Trainers = baskets.' },
    {
      id: 'short',
      niv: 'n',
      s: '« Short hair » veut dire « cheveux longs ».',
      v: false,
      e: 'Short hair = cheveux courts.',
    },
    { id: 'coat', niv: 'n', s: '« Coat » veut dire « manteau ».', v: true, e: 'Coat = manteau.' },
    { id: 'tired', niv: 'n', s: '« Tired » veut dire « fatigué ».', v: true, e: 'Tired = fatigué.' },
    {
      id: 'scarf',
      niv: 'n',
      s: '« Scarf » veut dire « chaussette ».',
      v: false,
      e: 'Scarf = écharpe ; socks = chaussettes.',
    },
    { id: 'gloves', niv: 'p', s: '« Gloves » veut dire « gants ».', v: true, e: 'Gloves = gants.' },
    {
      id: 'avant',
      niv: 'p',
      s: 'En anglais, on dit « a blue T-shirt » : la couleur se place avant le nom.',
      v: true,
      e: 'L’adjectif se place avant le nom.',
    },
    {
      id: 'green',
      niv: 'p',
      s: '« She has got green eyes » veut dire « Elle a les yeux bleus ».',
      v: false,
      e: 'Green = vert.',
    },
  ],
};

const TIME_DATES: Fiche = {
  lecon: 'CM2.EN.TIME_DATES',
  en: true,
  paires: [
    {
      id: 'heures',
      niv: 'n',
      prompt: 'Écoute l’heure et touche la bonne horloge.',
      relation: 'heure → image',
      consigne: 'point to {mot}',
      pairs: [
        ['one o’clock', '🕐'],
        ['three o’clock', '🕒'],
        ['six o’clock', '🕕'],
        ['nine o’clock', '🕘'],
        ['twelve o’clock', '🕛'],
        ['half past four', '🕟'],
      ],
      e: 'O’clock = heure pile ; half past four = quatre heures et demie.',
    },
    {
      id: 'saisons',
      niv: 'f',
      prompt: 'Écoute la saison et touche la bonne image.',
      relation: 'mot → image',
      consigne: 'point to {mot}',
      pairs: [
        ['spring', '🌸'],
        ['summer', '☀️'],
        ['autumn', '🍂'],
        ['winter', '⛄'],
      ],
      e: 'Spring = printemps, summer = été, autumn = automne, winter = hiver.',
    },
    {
      id: 'meteo',
      niv: 'n',
      prompt: 'Écoute le temps qu’il fait et touche la bonne image.',
      relation: 'mot → image',
      consigne: 'point to the {mot} weather',
      pairs: [
        ['sunny', '🌞'],
        ['rainy', '🌧️'],
        ['snowy', '🌨️'],
        ['windy', '🌬️'],
        ['cloudy', '☁️'],
        ['stormy', '⛈️'],
      ],
      e: 'Sunny = ensoleillé, rainy = pluvieux, snowy = neigeux, windy = venteux, cloudy = nuageux, stormy = orageux.',
    },
  ],
  qcm: [
    en({
      id: 'monday',
      niv: 'f',
      q: 'What day comes after Monday?',
      r: 'Tuesday',
      f: ['Sunday', 'Thursday', 'Friday'],
      e: 'Monday, Tuesday : lundi, mardi.',
    }),
    en({
      id: 'friday',
      niv: 'n',
      q: 'What day comes after Friday?',
      r: 'Saturday',
      f: ['Thursday', 'Sunday', 'Monday'],
      e: 'Friday, Saturday : vendredi, samedi.',
    }),
    en({
      id: 'march',
      niv: 'n',
      q: 'What month comes after March?',
      r: 'April',
      f: ['May', 'February', 'August'],
      e: 'March, April : mars, avril.',
    }),
    {
      id: 'wednesday',
      niv: 'f',
      q: 'Que veut dire « Wednesday » ?',
      spoken: 'Wednesday',
      r: 'mercredi',
      f: ['lundi', 'vendredi', 'dimanche'],
      e: 'Wednesday = mercredi.',
    },
    {
      id: 'july',
      niv: 'n',
      q: 'Que veut dire « July » ?',
      spoken: 'July',
      r: 'juillet',
      f: ['juin', 'janvier', 'avril'],
      e: 'July = juillet ; June = juin.',
    },
    {
      id: 'seven',
      niv: 'f',
      q: 'Écoute : quelle heure est-il ?',
      spoken: 'It’s seven o’clock.',
      r: '🕖',
      f: ['🕚', '🕑', '🕗'],
      e: 'Seven o’clock = sept heures.',
    },
    {
      id: 'half-two',
      niv: 'p',
      q: 'Écoute : quelle heure est-il ?',
      spoken: 'It’s half past two.',
      r: '🕝',
      f: ['🕑', '🕜', '🕞'],
      e: 'Half past two = deux heures et demie.',
    },
    en({
      id: 'week',
      niv: 'f',
      q: 'How many days are there in a week?',
      r: 'seven',
      f: ['five', 'ten', 'twelve'],
      e: 'Il y a sept jours dans une semaine.',
    }),
    en({
      id: 'christmas',
      niv: 'n',
      q: 'When is Christmas Day?',
      r: 'On the 25th of December',
      f: ['On the 1st of January', 'On the 31st of October', 'On the 14th of July'],
      e: 'Noël, c’est le 25 décembre.',
    }),
    en({
      id: 'date',
      niv: 'p',
      q: 'What’s the date today?',
      r: 'It’s the 3rd of May.',
      f: ['It’s three o’clock.', 'It’s sunny.', 'I’m ten.'],
      e: 'Pour donner la date : « It’s the 3rd of May. »',
    }),
    {
      id: 'time',
      niv: 'n',
      q: 'Que veut dire « What time is it? » ?',
      spoken: 'What time is it?',
      r: 'Quelle heure est-il ?',
      f: ['Quel temps fait-il ?', 'Quel jour sommes-nous ?', 'Quel âge as-tu ?'],
      e: '« What time is it? » = Quelle heure est-il ?',
    },
    {
      id: 'weather',
      niv: 'p',
      q: 'Que veut dire « What’s the weather like? » ?',
      spoken: 'What’s the weather like?',
      r: 'Quel temps fait-il ?',
      f: ['Quelle heure est-il ?', 'Quelle est la date ?', 'Qu’aimes-tu ?'],
      e: 'Weather = la météo, le temps qu’il fait.',
    },
  ],
  oral: [
    {
      id: 'monday',
      niv: 'f',
      prompt: 'Dis en anglais : lundi',
      r: 'Monday',
      ok: ['monday'],
      e: 'Lundi = « Monday ».',
    },
    {
      id: 'summer',
      niv: 'f',
      prompt: 'Dis en anglais : l’été ☀️',
      r: 'summer',
      ok: ['summer', 'the summer'],
      e: 'L’été = « summer ».',
    },
    {
      id: 'eight',
      niv: 'n',
      prompt: 'Dis en anglais : « Il est huit heures. » 🕗',
      r: 'It’s eight o’clock.',
      ok: ['it’s eight o’clock', 'it is eight o’clock', 'eight o’clock', 'its eight oclock'],
      e: '« It’s eight o’clock. »',
    },
    {
      id: 'december',
      niv: 'n',
      prompt: 'Dis en anglais : décembre',
      r: 'December',
      ok: ['december'],
      e: 'Décembre = « December ».',
    },
    {
      id: 'raining',
      niv: 'p',
      prompt: 'Dis en anglais : « Il pleut. » 🌧️',
      r: 'It’s raining.',
      ok: ['it’s raining', 'it is raining', 'it’s rainy', 'its raining'],
      e: '« It’s raining. »',
    },
  ],
  vf: [
    {
      id: 'seven',
      niv: 'f',
      s: 'There are seven days in a week.',
      spoken: 'There are seven days in a week.',
      v: true,
      e: 'Il y a sept jours dans une semaine.',
    },
    {
      id: 'tuesday',
      niv: 'f',
      s: 'Tuesday comes after Wednesday.',
      spoken: 'Tuesday comes after Wednesday.',
      v: false,
      e: 'Tuesday (mardi) vient avant Wednesday (mercredi).',
    },
    {
      id: 'twelve',
      niv: 'f',
      s: 'There are twelve months in a year.',
      spoken: 'There are twelve months in a year.',
      v: true,
      e: 'Il y a douze mois dans une année.',
    },
    {
      id: 'spring',
      niv: 'f',
      s: 'Spring comes after winter.',
      spoken: 'Spring comes after winter.',
      v: true,
      e: 'Le printemps vient après l’hiver.',
    },
    {
      id: 'january',
      niv: 'f',
      s: 'January is the last month of the year.',
      spoken: 'January is the last month of the year.',
      v: false,
      e: 'January est le premier mois ; December est le dernier.',
    },
    {
      id: 'august',
      niv: 'n',
      s: 'August comes before July.',
      spoken: 'August comes before July.',
      v: false,
      e: 'July (juillet) vient avant August (août).',
    },
    {
      id: 'winter',
      niv: 'n',
      s: 'Winter is the coldest season.',
      spoken: 'Winter is the coldest season.',
      v: true,
      e: 'L’hiver est la saison la plus froide.',
    },
    {
      id: 'halloween',
      niv: 'n',
      s: 'Halloween is in October.',
      spoken: 'Halloween is in October.',
      v: true,
      e: 'Halloween, c’est le 31 octobre.',
    },
    {
      id: 'thursday',
      niv: 'n',
      s: '« Thursday » veut dire « mardi ».',
      v: false,
      e: 'Thursday = jeudi ; Tuesday = mardi.',
    },
    {
      id: 'half',
      niv: 'p',
      s: '« It’s half past three » veut dire « Il est trois heures et demie ».',
      v: true,
      e: 'Half past = et demie.',
    },
    {
      id: 'february',
      niv: 'p',
      s: 'There are thirty days in February.',
      spoken: 'There are thirty days in February.',
      v: false,
      e: 'Février a 28 jours, ou 29 les années bissextiles.',
    },
    { id: 'autumn', niv: 'p', s: '« Autumn » veut dire « automne ».', v: true, e: 'Autumn = automne.' },
    {
      id: 'weekend',
      niv: 'p',
      s: 'Saturday and Sunday are the weekend.',
      spoken: 'Saturday and Sunday are the weekend.',
      v: true,
      e: 'Samedi et dimanche forment le week-end.',
    },
  ],
};

const ROUTINES: Fiche = {
  lecon: 'CM2.EN.ROUTINES',
  en: true,
  paires: [
    {
      id: 'routine',
      niv: 'f',
      prompt: 'Simon says… mime l’action de la journée !',
      relation: 'consigne → image',
      consigne: '{mot}',
      pairs: [
        ['wake up', '⏰'],
        ['have a shower', '🚿'],
        ['brush your teeth', '🪥'],
        ['get dressed', '👕'],
        ['have breakfast', '🥣'],
        ['go to school', '🏫'],
        ['do your homework', '📝'],
        ['go to bed', '🛌'],
      ],
      e: 'Wake up = se réveiller, have a shower = se doucher, brush your teeth = se brosser les dents, get dressed = s’habiller, have breakfast = prendre le petit déjeuner, go to school = aller à l’école, do your homework = faire ses devoirs, go to bed = aller au lit.',
    },
  ],
  etapes: [
    {
      id: 'journee',
      niv: 'n',
      prompt: 'Range la journée de Tom dans l’ordre.',
      els: [
        'Tom wakes up.',
        'He goes to school.',
        'He has lunch at school.',
        'He goes home.',
        'He does his homework.',
        'He goes to bed.',
      ],
      labels: ['7:00 am', '8:30 am', '12:00', '4:30 pm', '5:00 pm', '8:30 pm'],
      e: 'Le matin, Tom se lève et va à l’école ; il déjeune à la cantine, rentre, fait ses devoirs puis va au lit.',
    },
  ],
  qcm: [
    {
      id: 'teeth',
      niv: 'f',
      q: 'Écoute : que fait Tom ?',
      spoken: 'He brushes his teeth.',
      r: '🪥',
      f: ['🚿', '🥣', '🛌'],
      e: '« He brushes his teeth » = il se brosse les dents.',
    },
    en({
      id: 'goes',
      niv: 'n',
      q: 'Which sentence is correct?',
      r: 'She goes to school by bus.',
      f: ['She go to school by bus.', 'She going to school by bus.', 'She goes at school by bus.'],
      e: 'Avec « she », on ajoute -s ou -es au verbe : she goes.',
    }),
    en({
      id: 'plays',
      niv: 'n',
      q: 'Which sentence is correct?',
      r: 'He plays football on Saturdays.',
      f: [
        'He play football on Saturdays.',
        'He playing football on Saturdays.',
        'He plaies football on Saturdays.',
      ],
      e: 'Avec « he », le verbe prend un -s : he plays.',
    }),
    en({
      id: 'get-up',
      niv: 'p',
      q: 'Which sentence is correct?',
      r: 'I get up at seven o’clock.',
      f: ['I gets up at seven o’clock.', 'I getting up at seven o’clock.', 'I get up at seven o’clocks.'],
      e: 'Avec « I », pas de -s : I get up.',
    }),
    {
      id: 'breakfast',
      niv: 'f',
      q: 'Que veut dire « I have breakfast » ?',
      spoken: 'I have breakfast.',
      r: 'Je prends mon petit déjeuner.',
      f: ['Je prends ma douche.', 'Je vais au lit.', 'Je déjeune à la cantine.'],
      e: 'Breakfast = petit déjeuner.',
    },
    {
      id: 'bed',
      niv: 'f',
      q: 'Que veut dire « I go to bed » ?',
      spoken: 'I go to bed.',
      r: 'Je vais au lit.',
      f: ['Je me lève.', 'Je vais à l’école.', 'Je fais mes devoirs.'],
      e: 'Bed = lit.',
    },
    {
      id: 'homework',
      niv: 'n',
      q: 'Que veut dire « She does her homework » ?',
      spoken: 'She does her homework.',
      r: 'Elle fait ses devoirs.',
      f: ['Elle fait la cuisine.', 'Elle fait du sport.', 'Elle range sa chambre.'],
      e: 'Homework = devoirs.',
    },
    en({
      id: 'third-person',
      niv: 'p',
      q: 'With he or she, the present simple verb usually ends with…',
      r: '-s',
      f: ['-ing', '-ed', 'nothing'],
      e: 'He plays, she reads, it rains : on ajoute -s.',
    }),
    en({
      id: 'wake',
      niv: 'n',
      q: 'What time do you wake up?',
      r: 'I wake up at seven.',
      f: ['I’m seven.', 'It’s Monday.', 'I’ve got seven pens.'],
      e: 'On répond avec l’heure : « I wake up at seven. »',
    }),
  ],
  oral: [
    {
      id: 'get-up',
      niv: 'f',
      prompt: 'Dis en anglais : « Je me lève. » ⏰',
      r: 'I get up.',
      ok: ['i get up', 'i wake up', 'get up', 'wake up'],
      e: '« I get up. » ou « I wake up. »',
    },
    {
      id: 'school',
      niv: 'n',
      prompt: 'Dis en anglais : « Je vais à l’école. » 🏫',
      r: 'I go to school.',
      ok: ['i go to school', 'go to school'],
      e: '« I go to school. »',
    },
    {
      id: 'teeth',
      niv: 'n',
      prompt: 'Dis en anglais : « Je me brosse les dents. » 🪥',
      r: 'I brush my teeth.',
      ok: ['i brush my teeth', 'brush my teeth'],
      e: '« I brush my teeth. »',
    },
    {
      id: 'breakfast',
      niv: 'p',
      prompt: 'Dis en anglais : « Il prend son petit déjeuner. » 🥣',
      r: 'He has breakfast.',
      ok: ['he has breakfast', 'he has his breakfast', 'he eats breakfast'],
      e: 'Avec « he » : « He has breakfast. »',
    },
  ],
  vf: [
    { id: 'bed', niv: 'f', s: '« I go to bed » veut dire « Je vais au lit ».', v: true, e: 'Bed = lit.' },
    {
      id: 'breakfast',
      niv: 'f',
      s: '« Breakfast » veut dire « dîner ».',
      v: false,
      e: 'Breakfast = petit déjeuner ; dinner = dîner.',
    },
    {
      id: 'shower',
      niv: 'f',
      s: '« Have a shower » veut dire « prendre une douche ».',
      v: true,
      e: 'Shower = douche.',
    },
    { id: 'lunch', niv: 'f', s: '« Lunch » veut dire « déjeuner ».', v: true, e: 'Lunch = repas de midi.' },
    {
      id: 'dressed',
      niv: 'f',
      s: '« Get dressed » veut dire « se laver ».',
      v: false,
      e: 'Get dressed = s’habiller.',
    },
    {
      id: 'he-play',
      niv: 'n',
      s: '« He play football » est correct.',
      v: false,
      e: 'On dit « He plays football ».',
    },
    { id: 'watches', niv: 'n', s: '« She watches TV » est correct.', v: true, e: 'Watch → she watches.' },
    { id: 'homework', niv: 'n', s: '« Homework » veut dire « devoirs ».', v: true, e: 'Homework = devoirs.' },
    {
      id: 'wake',
      niv: 'n',
      s: '« I wake up » veut dire « je m’endors ».',
      v: false,
      e: '« I wake up » = je me réveille.',
    },
    {
      id: 's',
      niv: 'p',
      s: 'Avec he, she ou it, on ajoute souvent un -s au verbe au présent simple.',
      v: true,
      e: 'He plays, she reads.',
    },
    {
      id: 'she-go',
      niv: 'p',
      s: '« She go to school » est correct.',
      v: false,
      e: 'On dit « She goes to school ».',
    },
    {
      id: 'brushes',
      niv: 'p',
      s: '« He brushes his teeth » est correct.',
      v: true,
      e: 'Brush → he brushes.',
    },
  ],
};

const SCHOOL: Fiche = {
  lecon: 'CM2.EN.SCHOOL',
  en: true,
  paires: [
    {
      id: 'objets',
      niv: 'f',
      prompt: 'Écoute et touche le bon objet.',
      relation: 'mot → image',
      pairs: [
        ['pencil', '✏️'],
        ['ruler', '📏'],
        ['scissors', '✂️'],
        ['book', '📕'],
        ['schoolbag', '🎒'],
        ['pen', '🖊️'],
        ['notebook', '📓'],
        ['crayon', '🖍️'],
      ],
      e: 'Pencil = crayon, ruler = règle, scissors = ciseaux, book = livre, schoolbag = cartable, pen = stylo, notebook = cahier, crayon = crayon de cire.',
    },
    {
      id: 'matieres',
      niv: 'n',
      prompt: 'Écoute la matière et touche la bonne image.',
      relation: 'mot → image',
      consigne: 'point to {mot}',
      pairs: [
        ['maths', '➗'],
        ['science', '🔬'],
        ['art', '🎨'],
        ['music', '🎵'],
        ['PE', '⚽'],
        ['geography', '🗺️'],
        ['history', '🏰'],
      ],
      e: 'Maths, science, art, music, PE (EPS), geography, history.',
    },
    {
      id: 'consignes',
      niv: 'n',
      prompt: 'Simon says… fais ce que dit le maître !',
      relation: 'consigne → image',
      consigne: '{mot}',
      pairs: [
        ['stand up', '🧍'],
        ['sit down', '🪑'],
        ['raise your hand', '✋'],
        ['open your book', '📖'],
        ['close your book', '📕'],
        ['be quiet', '🤫'],
        ['listen', '👂'],
      ],
      e: 'Stand up = lève-toi, sit down = assieds-toi, raise your hand = lève la main, open/close your book = ouvre/ferme ton livre, be quiet = silence, listen = écoute.',
    },
  ],
  qcm: [
    {
      id: 'ruler',
      niv: 'f',
      q: 'Écoute : quel objet ?',
      spoken: 'a ruler',
      r: '📏',
      f: ['✏️', '✂️', '🎒'],
      e: 'Ruler = règle.',
    },
    {
      id: 'pe',
      niv: 'n',
      q: 'Que veut dire « PE » ?',
      spoken: 'P E',
      r: 'l’EPS (le sport)',
      f: ['les maths', 'la musique', 'les arts plastiques'],
      e: 'PE = Physical Education, l’éducation physique et sportive.',
    },
    {
      id: 'borrow',
      niv: 'p',
      q: 'Que veut dire « Can I borrow your pencil, please? » ?',
      spoken: 'Can I borrow your pencil, please?',
      r: 'Est-ce que je peux emprunter ton crayon, s’il te plaît ?',
      f: ['Est-ce que tu as un stylo ?', 'Peux-tu fermer ton livre ?', 'Où est ma trousse ?'],
      e: 'Borrow = emprunter.',
    },
    en({
      id: 'subject',
      niv: 'n',
      q: 'What’s your favourite subject?',
      r: 'My favourite subject is music.',
      f: ['My favourite colour is red.', 'I’m ten.', 'It’s in my schoolbag.'],
      e: 'Subject = matière.',
    }),
    {
      id: 'open',
      niv: 'f',
      q: 'Que veut dire « Open your book » ?',
      spoken: 'Open your book.',
      r: 'Ouvre ton livre.',
      f: ['Ferme ton livre.', 'Lis ton livre.', 'Range ton livre.'],
      e: 'Open = ouvrir ; close = fermer.',
    },
    {
      id: 'rubber',
      niv: 'p',
      q: 'Que veut dire « rubber » en anglais britannique ?',
      spoken: 'a rubber',
      r: 'une gomme',
      f: ['un crayon', 'une règle', 'un cahier'],
      e: 'En Grande-Bretagne, une gomme se dit « a rubber ».',
    },
    {
      id: 'pencil-case',
      niv: 'n',
      q: 'Que veut dire « pencil case » ?',
      spoken: 'a pencil case',
      r: 'une trousse',
      f: ['un taille-crayon', 'un cartable', 'un crayon'],
      e: 'Pencil case = trousse.',
    },
    {
      id: 'music',
      niv: 'f',
      q: 'Écoute : quelle matière ?',
      spoken: 'music',
      r: '🎵',
      f: ['🎨', '🔬', '⚽'],
      e: 'Music = musique.',
    },
  ],
  oral: [
    {
      id: 'pencil',
      niv: 'f',
      prompt: 'Dis en anglais : un crayon ✏️',
      r: 'a pencil',
      ok: ['pencil', 'a pencil'],
      e: 'Un crayon = « a pencil ».',
    },
    {
      id: 'sit',
      niv: 'f',
      prompt: 'Dis en anglais : « Assieds-toi. » 🪑',
      r: 'Sit down.',
      ok: ['sit down', 'sit down please'],
      e: '« Sit down. »',
    },
    {
      id: 'maths',
      niv: 'n',
      prompt: 'Dis en anglais : « J’aime les maths. »',
      r: 'I like maths.',
      ok: ['i like maths', 'i like math'],
      e: '« I like maths. »',
    },
    {
      id: 'rubber',
      niv: 'p',
      prompt: 'Dis en anglais : une gomme',
      r: 'a rubber',
      ok: ['rubber', 'a rubber', 'eraser', 'an eraser'],
      e: 'Une gomme = « a rubber » (Royaume-Uni) ou « an eraser ».',
    },
  ],
  vf: [
    { id: 'ruler', niv: 'f', s: '« Ruler » veut dire « règle ».', v: true, e: 'Ruler = règle.' },
    { id: 'scissors', niv: 'f', s: '« Scissors » veut dire « ciseaux ».', v: true, e: 'Scissors = ciseaux.' },
    {
      id: 'schoolbag',
      niv: 'f',
      s: '« Schoolbag » veut dire « trousse ».',
      v: false,
      e: 'Schoolbag = cartable ; pencil case = trousse.',
    },
    {
      id: 'book',
      niv: 'f',
      s: '« Book » veut dire « cahier ».',
      v: false,
      e: 'Book = livre ; notebook = cahier.',
    },
    {
      id: 'stand',
      niv: 'n',
      s: '« Stand up » veut dire « assieds-toi ».',
      v: false,
      e: 'Stand up = lève-toi ; sit down = assieds-toi.',
    },
    { id: 'pe', niv: 'n', s: '« PE » désigne le sport à l’école.', v: true, e: 'Physical Education.' },
    {
      id: 'case',
      niv: 'n',
      s: '« Pencil case » veut dire « taille-crayon ».',
      v: false,
      e: 'Pencil case = trousse ; sharpener = taille-crayon.',
    },
    {
      id: 'hand',
      niv: 'n',
      s: '« Raise your hand » veut dire « lève la main ».',
      v: true,
      e: 'Raise = lever ; hand = main.',
    },
    {
      id: 'rubber',
      niv: 'p',
      s: 'En anglais britannique, « rubber » veut dire « gomme ».',
      v: true,
      e: 'Les Américains disent « eraser ».',
    },
    {
      id: 'science',
      niv: 'p',
      s: '« Science » veut dire « la musique ».',
      v: false,
      e: 'Science = les sciences ; music = la musique.',
    },
    {
      id: 'toilet',
      niv: 'p',
      s: '« Can I go to the toilet, please? » sert à demander à aller aux toilettes.',
      v: true,
      e: 'C’est une phrase utile en classe.',
    },
  ],
};

const FOOD: Fiche = {
  lecon: 'CM2.EN.FOOD',
  en: true,
  paires: [
    {
      id: 'aliments-f',
      niv: 'f',
      prompt: 'Écoute et touche le bon aliment.',
      relation: 'mot → image',
      pairs: [
        ['apple', '🍎'],
        ['banana', '🍌'],
        ['bread', '🍞'],
        ['cheese', '🧀'],
        ['milk', '🥛'],
        ['egg', '🥚'],
        ['carrot', '🥕'],
        ['strawberry', '🍓'],
      ],
      e: 'Apple = pomme, banana = banane, bread = pain, cheese = fromage, milk = lait, egg = œuf, carrot = carotte, strawberry = fraise.',
    },
    {
      id: 'aliments-n',
      niv: 'n',
      prompt: 'Écoute et touche le bon aliment.',
      relation: 'mot → image',
      pairs: [
        ['pizza', '🍕'],
        ['cake', '🍰'],
        ['chips', '🍟'],
        ['sandwich', '🥪'],
        ['ice cream', '🍦'],
        ['chicken', '🍗'],
        ['tomato', '🍅'],
        ['orange', '🍊'],
      ],
      e: 'Pizza, cake = gâteau, chips = frites, sandwich, ice cream = glace, chicken = poulet, tomato = tomate, orange.',
    },
  ],
  qcm: [
    {
      id: 'cheese',
      niv: 'f',
      q: 'Écoute : quel aliment ?',
      spoken: 'cheese',
      r: '🧀',
      f: ['🍞', '🥛', '🥚'],
      e: 'Cheese = fromage.',
    },
    {
      id: 'strawberries',
      niv: 'n',
      q: 'Écoute : quel aliment ?',
      spoken: 'strawberries',
      r: '🍓',
      f: ['🍒', '🍎', '🍅'],
      e: 'Strawberries = fraises.',
    },
    {
      id: 'hungry',
      niv: 'f',
      q: 'Que veut dire « I’m hungry » ?',
      spoken: 'I’m hungry.',
      r: 'J’ai faim.',
      f: ['J’ai soif.', 'J’ai chaud.', 'J’ai froid.'],
      e: 'Hungry = qui a faim.',
    },
    {
      id: 'thirsty',
      niv: 'n',
      q: 'Que veut dire « I’m thirsty » ?',
      spoken: 'I’m thirsty.',
      r: 'J’ai soif.',
      f: ['J’ai faim.', 'Je suis fatigué.', 'J’ai mal au ventre.'],
      e: 'Thirsty = qui a soif.',
    },
    {
      id: 'juice',
      niv: 'n',
      q: 'Que veut dire « Would you like some juice? » ?',
      spoken: 'Would you like some juice?',
      r: 'Veux-tu du jus ?',
      f: ['Aimes-tu le jus ?', 'Où est le jus ?', 'Le jus est-il froid ?'],
      e: '« Would you like…? » sert à proposer poliment.',
    },
    {
      id: 'chips',
      niv: 'p',
      q: 'Que veut dire « chips » en anglais britannique ?',
      spoken: 'chips',
      r: 'des frites',
      f: ['des chips', 'des biscuits', 'des bonbons'],
      e: 'Au Royaume-Uni, « chips » = frites ; les chips se disent « crisps ».',
    },
    en({
      id: 'carrots',
      niv: 'p',
      q: 'Do you like carrots?',
      r: 'Yes, I do.',
      f: ['Yes, I like.', 'Yes, I am.', 'Yes, I have.'],
      e: 'À « Do you like…? », on répond « Yes, I do. » ou « No, I don’t. ».',
    }),
    {
      id: 'much',
      niv: 'n',
      q: 'Que veut dire « How much is it? » ?',
      spoken: 'How much is it?',
      r: 'Combien ça coûte ?',
      f: ['Combien y en a-t-il ?', 'Quelle heure est-il ?', 'Qu’est-ce que c’est ?'],
      e: '« How much is it? » sert à demander un prix.',
    },
    {
      id: 'breakfast',
      niv: 'n',
      q: 'Écoute : quel repas ?',
      spoken: 'breakfast',
      r: 'le petit déjeuner',
      f: ['le dîner', 'le goûter', 'le déjeuner'],
      e: 'Breakfast = petit déjeuner, lunch = déjeuner, dinner = dîner.',
    },
  ],
  oral: [
    {
      id: 'apple',
      niv: 'f',
      prompt: 'Dis en anglais : une pomme 🍎',
      r: 'an apple',
      ok: ['an apple', 'apple', 'apples'],
      e: 'Une pomme = « an apple ».',
    },
    {
      id: 'bread',
      niv: 'f',
      prompt: 'Dis en anglais : du pain 🍞',
      r: 'bread',
      ok: ['bread', 'some bread'],
      e: 'Du pain = « bread ».',
    },
    {
      id: 'hungry',
      niv: 'n',
      prompt: 'Dis en anglais : « J’ai faim. »',
      r: 'I’m hungry.',
      ok: ['i’m hungry', 'i am hungry', 'im hungry'],
      e: '« I’m hungry. »',
    },
    {
      id: 'cheese',
      niv: 'n',
      prompt: 'Dis en anglais : « J’aime le fromage. » 🧀',
      r: 'I like cheese.',
      ok: ['i like cheese'],
      e: '« I like cheese. »',
    },
    {
      id: 'carrots',
      niv: 'p',
      prompt: 'Dis en anglais : « Je n’aime pas les carottes. » 🥕',
      r: 'I don’t like carrots.',
      ok: ['i don’t like carrots', 'i do not like carrots', 'i dont like carrots'],
      e: '« I don’t like carrots. »',
    },
  ],
  vf: [
    { id: 'bread', niv: 'f', s: '« Bread » veut dire « pain ».', v: true, e: 'Bread = pain.' },
    { id: 'milk', niv: 'f', s: '« Milk » veut dire « lait ».', v: true, e: 'Milk = lait.' },
    {
      id: 'apple',
      niv: 'f',
      s: '« Apple » veut dire « banane ».',
      v: false,
      e: 'Apple = pomme ; banana = banane.',
    },
    {
      id: 'cheese',
      niv: 'f',
      s: '« Cheese » veut dire « cerise ».',
      v: false,
      e: 'Cheese = fromage ; cherry = cerise.',
    },
    {
      id: 'thirsty',
      niv: 'n',
      s: '« I’m thirsty » veut dire « J’ai faim ».',
      v: false,
      e: '« I’m thirsty » = J’ai soif.',
    },
    {
      id: 'strawberry',
      niv: 'n',
      s: '« Strawberry » veut dire « fraise ».',
      v: true,
      e: 'Strawberry = fraise.',
    },
    { id: 'chicken', niv: 'n', s: '« Chicken » veut dire « poulet ».', v: true, e: 'Chicken = poulet.' },
    {
      id: 'cake',
      niv: 'n',
      s: '« Cake » veut dire « carotte ».',
      v: false,
      e: 'Cake = gâteau ; carrot = carotte.',
    },
    {
      id: 'chips',
      niv: 'p',
      s: 'En anglais britannique, « chips » veut dire « frites ».',
      v: true,
      e: 'Fish and chips = poisson-frites.',
    },
    {
      id: 'would',
      niv: 'p',
      s: '« Would you like…? » sert à proposer quelque chose.',
      v: true,
      e: 'Would you like some tea? = Veux-tu du thé ?',
    },
    {
      id: 'fish',
      niv: 'p',
      s: '« I don’t like fish » veut dire « J’adore le poisson ».',
      v: false,
      e: '« I don’t like fish » = Je n’aime pas le poisson.',
    },
    {
      id: 'crisps',
      niv: 'p',
      s: 'En anglais britannique, les chips se disent « crisps ».',
      v: true,
      e: 'Crisps = chips.',
    },
  ],
};

const COUNTRIES: Fiche = {
  lecon: 'CM2.EN.COUNTRIES',
  en: true,
  lieux: [
    {
      id: 'uk',
      niv: 'f',
      map: 'europe',
      target: 'royaume-uni',
      label: 'le Royaume-Uni',
      prompt: 'Touche « the United Kingdom », le Royaume-Uni.',
      e: 'Le Royaume-Uni réunit l’Angleterre, l’Écosse, le pays de Galles et l’Irlande du Nord.',
    },
    {
      id: 'ireland',
      niv: 'n',
      map: 'europe',
      target: 'irlande',
      label: 'l’Irlande',
      prompt: 'Touche « Ireland », l’Irlande.',
      e: 'L’Irlande est une île à l’ouest de la Grande-Bretagne ; on y parle anglais et irlandais.',
    },
    {
      id: 'spain',
      niv: 'n',
      map: 'europe',
      target: 'espagne',
      label: 'l’Espagne',
      prompt: 'Touche le pays qu’on appelle « Spain » en anglais.',
      e: 'Spain = l’Espagne.',
    },
    {
      id: 'germany',
      niv: 'n',
      map: 'europe',
      target: 'allemagne',
      label: 'l’Allemagne',
      prompt: 'Touche le pays qu’on appelle « Germany » en anglais.',
      e: 'Germany = l’Allemagne.',
    },
    {
      id: 'france',
      niv: 'f',
      map: 'europe',
      target: 'france',
      label: 'la France',
      prompt: 'Touche « France ».',
      e: 'En anglais, la France se dit « France ».',
    },
    {
      id: 'usa',
      niv: 'n',
      map: 'monde',
      target: 'amerique-du-nord',
      label: 'l’Amérique du Nord',
      prompt: 'Touche le continent où se trouvent les États-Unis (the USA).',
      e: 'Les États-Unis sont en Amérique du Nord.',
    },
    {
      id: 'australia',
      niv: 'p',
      map: 'monde',
      target: 'oceanie',
      label: 'l’Océanie',
      prompt: 'Touche le continent où se trouve l’Australie, un pays où l’on parle anglais.',
      e: 'L’Australie est en Océanie.',
    },
    {
      id: 'atlantic',
      niv: 'p',
      map: 'monde',
      target: 'ocean-atlantique',
      label: 'l’océan Atlantique',
      prompt: 'Touche l’océan qui sépare le Royaume-Uni des États-Unis.',
      e: 'L’océan Atlantique sépare l’Europe de l’Amérique.',
    },
  ],
  paires: [
    {
      id: 'pays',
      niv: 'f',
      prompt: 'Associe chaque pays en anglais à son nom en français.',
      relation: 'anglais → français',
      pairs: [
        ['England', 'l’Angleterre'],
        ['Scotland', 'l’Écosse'],
        ['Wales', 'le pays de Galles'],
        ['Ireland', 'l’Irlande'],
        ['Spain', 'l’Espagne'],
        ['Germany', 'l’Allemagne'],
      ],
      e: 'England, Scotland, Wales, Ireland, Spain, Germany.',
    },
    {
      id: 'nationalites',
      niv: 'n',
      prompt: 'Associe chaque pays à sa nationalité.',
      relation: 'pays → nationalité',
      pairs: [
        ['France', 'French'],
        ['England', 'English'],
        ['Scotland', 'Scottish'],
        ['Wales', 'Welsh'],
        ['Ireland', 'Irish'],
        ['Italy', 'Italian'],
        ['the USA', 'American'],
      ],
      e: 'En anglais, les nationalités prennent une majuscule : French, English, Scottish…',
    },
  ],
  qcm: [
    {
      id: 'germany',
      niv: 'f',
      q: 'Écoute : quel pays ?',
      spoken: 'Germany',
      r: 'l’Allemagne',
      f: ['l’Angleterre', 'l’Espagne', 'l’Italie'],
      e: 'Germany = l’Allemagne.',
    },
    {
      id: 'wales',
      niv: 'n',
      q: 'Écoute : quel pays ?',
      spoken: 'Wales',
      r: 'le pays de Galles',
      f: ['l’Écosse', 'l’Irlande', 'l’Angleterre'],
      e: 'Wales = le pays de Galles.',
    },
    en({
      id: 'london',
      niv: 'f',
      q: 'What’s the capital of the United Kingdom?',
      r: 'London',
      f: ['Paris', 'Edinburgh', 'Dublin'],
      e: 'La capitale du Royaume-Uni est Londres.',
    }),
    en({
      id: 'edinburgh',
      niv: 'p',
      q: 'What’s the capital of Scotland?',
      r: 'Edinburgh',
      f: ['London', 'Cardiff', 'Belfast'],
      e: 'Édimbourg est la capitale de l’Écosse ; Cardiff, celle du pays de Galles.',
    }),
    en({
      id: 'dublin',
      niv: 'n',
      q: 'What’s the capital of Ireland?',
      r: 'Dublin',
      f: ['London', 'Belfast', 'Cardiff'],
      e: 'Dublin est la capitale de l’Irlande.',
    }),
    en({
      id: 'uk',
      niv: 'p',
      q: 'Which countries make up the United Kingdom?',
      r: 'England, Scotland, Wales and Northern Ireland',
      f: ['England, France and Spain', 'England and the USA', 'Scotland, Ireland and Canada'],
      e: 'Le Royaume-Uni réunit quatre nations.',
    }),
    en({
      id: 'french',
      niv: 'n',
      q: 'I’m from France. I’m…',
      r: 'French',
      f: ['France', 'English', 'Frenchish'],
      e: 'Je viens de France : je suis « French ».',
    }),
    {
      id: 'from',
      niv: 'n',
      q: 'Que veut dire « Where do you come from? » ?',
      spoken: 'Where do you come from?',
      r: 'D’où viens-tu ?',
      f: ['Où vas-tu ?', 'Où habites-tu ?', 'Comment vas-tu ?'],
      e: 'On répond « I come from France. » ou « I’m from France. ».',
    },
    en({
      id: 'kangaroos',
      niv: 'f',
      q: 'Which country is famous for kangaroos?',
      r: 'Australia',
      f: ['Scotland', 'Ireland', 'Spain'],
      e: 'Les kangourous vivent en Australie.',
    }),
  ],
  oral: [
    {
      id: 'france',
      niv: 'f',
      prompt: 'Dis en anglais : la France',
      r: 'France',
      ok: ['france'],
      e: 'La France = « France ».',
    },
    {
      id: 'england',
      niv: 'f',
      prompt: 'Dis en anglais : l’Angleterre',
      r: 'England',
      ok: ['england'],
      e: 'L’Angleterre = « England ».',
    },
    {
      id: 'french',
      niv: 'n',
      prompt: 'Dis en anglais : « Je suis français » ou « Je suis française ».',
      r: 'I’m French.',
      ok: ['i’m french', 'i am french', 'im french'],
      e: '« I’m French. »',
    },
    {
      id: 'live',
      niv: 'p',
      prompt: 'Dis en anglais : « J’habite en France. »',
      r: 'I live in France.',
      ok: ['i live in france'],
      e: '« I live in France. »',
    },
  ],
  vf: [
    {
      id: 'england',
      niv: 'f',
      s: '« England » veut dire « l’Angleterre ».',
      v: true,
      e: 'England = l’Angleterre.',
    },
    { id: 'london', niv: 'f', s: 'La capitale du Royaume-Uni est Londres.', v: true, e: 'London = Londres.' },
    {
      id: 'spain',
      niv: 'f',
      s: '« Spain » veut dire « l’Allemagne ».',
      v: false,
      e: 'Spain = l’Espagne ; Germany = l’Allemagne.',
    },
    {
      id: 'italy',
      niv: 'f',
      s: '« I’m from Italy » veut dire « Je viens d’Italie ».',
      v: true,
      e: 'Italy = l’Italie.',
    },
    {
      id: 'germany',
      niv: 'f',
      s: '« Germany » veut dire « la Grèce ».',
      v: false,
      e: 'Germany = l’Allemagne ; Greece = la Grèce.',
    },
    { id: 'german', niv: 'n', s: '« German » veut dire « allemand ».', v: true, e: 'German = allemand.' },
    {
      id: 'irish',
      niv: 'n',
      s: '« Irish » veut dire « écossais ».',
      v: false,
      e: 'Irish = irlandais ; Scottish = écossais.',
    },
    {
      id: 'english',
      niv: 'n',
      s: 'On parle anglais aux États-Unis, au Canada et en Australie.',
      v: true,
      e: 'L’anglais est parlé dans le monde entier.',
    },
    {
      id: 'welsh',
      niv: 'n',
      s: '« Welsh » veut dire « gallois ».',
      v: true,
      e: 'Welsh = gallois, du pays de Galles.',
    },
    {
      id: 'dublin',
      niv: 'n',
      s: 'Londres est la capitale de l’Irlande.',
      v: false,
      e: 'La capitale de l’Irlande est Dublin.',
    },
    {
      id: 'four',
      niv: 'p',
      s: 'Le Royaume-Uni réunit l’Angleterre, l’Écosse, le pays de Galles et l’Irlande du Nord.',
      v: true,
      e: 'Ce sont quatre nations.',
    },
    {
      id: 'edinburgh',
      niv: 'p',
      s: 'Édimbourg est la capitale du pays de Galles.',
      v: false,
      e: 'Édimbourg est la capitale de l’Écosse ; Cardiff, celle du pays de Galles.',
    },
    {
      id: 'capital',
      niv: 'p',
      s: 'En anglais, les nationalités s’écrivent avec une majuscule : French, English.',
      v: true,
      e: 'C’est une différence avec le français.',
    },
  ],
};

const CAN_HAVE_GOT: Fiche = {
  lecon: 'CM2.EN.CAN_HAVE_GOT',
  en: true,
  paires: [
    {
      id: 'can',
      niv: 'f',
      prompt: 'Simon says… montre ce que tu sais faire !',
      relation: 'action → image',
      consigne: 'show me how you {mot}',
      pairs: [
        ['swim', '🏊'],
        ['run', '🏃'],
        ['dance', '💃'],
        ['sing', '🎤'],
        ['ride a bike', '🚴'],
        ['climb', '🧗'],
        ['skate', '⛸️'],
        ['ski', '⛷️'],
      ],
      e: 'Swim = nager, run = courir, dance = danser, sing = chanter, ride a bike = faire du vélo, climb = grimper, skate = patiner, ski = skier.',
    },
    {
      id: 'animaux',
      niv: 'n',
      prompt: 'I’ve got a pet! Écoute et touche le bon animal.',
      relation: 'mot → image',
      pairs: [
        ['dog', '🐶'],
        ['cat', '🐱'],
        ['rabbit', '🐰'],
        ['hamster', '🐹'],
        ['fish', '🐟'],
        ['bird', '🐦'],
        ['horse', '🐴'],
        ['mouse', '🐭'],
        ['tortoise', '🐢'],
      ],
      e: 'Dog = chien, cat = chat, rabbit = lapin, hamster, fish = poisson, bird = oiseau, horse = cheval, mouse = souris, tortoise = tortue.',
    },
  ],
  qcm: [
    {
      id: 'swim',
      niv: 'f',
      q: 'Que veut dire « I can swim » ?',
      spoken: 'I can swim.',
      r: 'Je sais nager.',
      f: ['Je ne sais pas nager.', 'J’aime nager.', 'Je nage tous les jours.'],
      e: '« I can » = je sais, je peux.',
    },
    {
      id: 'sing',
      niv: 'n',
      q: 'Que veut dire « I can’t sing » ?',
      spoken: 'I can’t sing.',
      r: 'Je ne sais pas chanter.',
      f: ['Je sais chanter.', 'Je chante bien.', 'J’aime chanter.'],
      e: '« I can’t » = je ne sais pas, je ne peux pas.',
    },
    {
      id: 'cat',
      niv: 'f',
      q: 'Que veut dire « She has got a cat » ?',
      spoken: 'She has got a cat.',
      r: 'Elle a un chat.',
      f: ['Elle est un chat.', 'Il a un chat.', 'Elle veut un chat.'],
      e: '« She has got » = elle a.',
    },
    en({
      id: 'has-got',
      niv: 'n',
      q: 'Which sentence is correct?',
      r: 'He has got a dog.',
      f: ['He have got a dog.', 'He got has a dog.', 'He is got a dog.'],
      e: 'I have got, he has got.',
    }),
    en({
      id: 'can-ride',
      niv: 'p',
      q: 'Which sentence is correct?',
      r: 'She can ride a bike.',
      f: ['She cans ride a bike.', 'She can rides a bike.', 'She can to ride a bike.'],
      e: '« Can » ne change pas, et le verbe qui suit reste à la base : she can ride.',
    }),
    en({
      id: 'can-you',
      niv: 'n',
      q: 'Can you swim?',
      r: 'Yes, I can.',
      f: ['Yes, I do.', 'Yes, I am.', 'Yes, I have.'],
      e: 'À « Can you…? », on répond « Yes, I can. » ou « No, I can’t. ».',
    }),
    en({
      id: 'have-you',
      niv: 'p',
      q: 'Have you got a pet?',
      r: 'Yes, I have.',
      f: ['Yes, I can.', 'Yes, I am.', 'Yes, I got.'],
      e: 'À « Have you got…? », on répond « Yes, I have. » ou « No, I haven’t. ».',
    }),
    {
      id: 'skate',
      niv: 'f',
      q: 'Écoute : que sait faire Lucy ?',
      spoken: 'Lucy can skate.',
      r: '⛸️',
      f: ['⛷️', '🏊', '🚴'],
      e: 'Skate = patiner.',
    },
    {
      id: 'rabbit',
      niv: 'n',
      q: 'Écoute : quel animal a Tom ?',
      spoken: 'Tom has got a rabbit.',
      r: '🐰',
      f: ['🐹', '🐭', '🐱'],
      e: 'Rabbit = lapin.',
    },
  ],
  oral: [
    {
      id: 'swim',
      niv: 'f',
      prompt: 'Dis en anglais : « Je sais nager. » 🏊',
      r: 'I can swim.',
      ok: ['i can swim'],
      e: '« I can swim. »',
    },
    {
      id: 'dog',
      niv: 'n',
      prompt: 'Dis en anglais : « J’ai un chien. » 🐶',
      r: 'I’ve got a dog.',
      ok: ['i’ve got a dog', 'i have got a dog', 'i have a dog', 'ive got a dog'],
      e: '« I’ve got a dog. »',
    },
    {
      id: 'fly',
      niv: 'n',
      prompt: 'Dis en anglais : « Je ne sais pas voler. » 🐦',
      r: 'I can’t fly.',
      ok: ['i can’t fly', 'i cannot fly', 'i can not fly', 'i cant fly'],
      e: '« I can’t fly. »',
    },
    {
      id: 'cats',
      niv: 'p',
      prompt: 'Dis en anglais : « Elle a deux chats. » 🐱🐱',
      r: 'She has got two cats.',
      ok: ['she has got two cats', 'she’s got two cats', 'she has two cats', 'shes got two cats'],
      e: '« She has got two cats. »',
    },
  ],
  vf: [
    {
      id: 'dance',
      niv: 'f',
      s: '« I can dance » veut dire « Je sais danser ».',
      v: true,
      e: 'Dance = danser.',
    },
    {
      id: 'cant',
      niv: 'f',
      s: '« I can’t » veut dire « je peux ».',
      v: false,
      e: '« I can’t » = je ne peux pas.',
    },
    { id: 'dog', niv: 'f', s: '« Dog » veut dire « chien ».', v: true, e: 'Dog = chien.' },
    {
      id: 'horse',
      niv: 'f',
      s: '« Horse » veut dire « maison ».',
      v: false,
      e: 'Horse = cheval ; house = maison.',
    },
    {
      id: 'have-got',
      niv: 'n',
      s: '« He have got a cat » est correct.',
      v: false,
      e: 'On dit « He has got a cat ».',
    },
    {
      id: 'rabbit',
      niv: 'n',
      s: '« She has got a rabbit » est correct.',
      v: true,
      e: 'She has got = elle a.',
    },
    {
      id: 'climb',
      niv: 'n',
      s: '« Can you climb? » veut dire « Sais-tu grimper ? ».',
      v: true,
      e: 'Climb = grimper.',
    },
    {
      id: 'pet',
      niv: 'n',
      s: '« I haven’t got a pet » veut dire « J’ai un animal ».',
      v: false,
      e: '« I haven’t got a pet » = Je n’ai pas d’animal.',
    },
    {
      id: 'no-s',
      niv: 'p',
      s: 'Après « can », le verbe ne prend pas de -s : « he can swim ».',
      v: true,
      e: '« Can » et le verbe qui le suit ne changent pas.',
    },
    { id: 'cans', niv: 'p', s: '« She cans skate » est correct.', v: false, e: 'On dit « She can skate ».' },
    {
      id: 'yes-have',
      niv: 'p',
      s: 'On répond « Yes, I have » à « Have you got a bike? ».',
      v: true,
      e: 'La réponse courte reprend « have ».',
    },
  ],
};

const CULTURE: Fiche = {
  lecon: 'CM2.EN.CULTURE',
  en: true,
  paires: [
    {
      id: 'fetes',
      niv: 'f',
      prompt: 'Écoute la fête et touche la bonne image.',
      relation: 'fête → image',
      consigne: 'point to {mot}',
      pairs: [
        ['Halloween', '🎃'],
        ['Christmas', '🎄'],
        ['Easter', '🐣'],
        ['Bonfire Night', '🎆'],
        ['Thanksgiving', '🦃'],
        ['St Patrick’s Day', '☘️'],
        ['Pancake Day', '🥞'],
        ['Valentine’s Day', '❤️'],
      ],
      e: 'Halloween (31 octobre), Christmas (Noël), Easter (Pâques), Bonfire Night (5 novembre), Thanksgiving (États-Unis), St Patrick’s Day (17 mars), Pancake Day (Mardi gras), Valentine’s Day (14 février).',
    },
    {
      id: 'londres',
      niv: 'n',
      prompt: 'Écoute et touche le symbole de Londres.',
      relation: 'mot → image',
      consigne: 'point to {mot}',
      pairs: [
        ['the double-decker bus', '🚌'],
        ['the black cab', '🚕'],
        ['a cup of tea', '☕'],
        ['fish and chips', '🐟'],
        ['the royal guard', '💂'],
        ['Big Ben', '🕰️'],
      ],
      e: 'Le bus à deux étages, le taxi noir, la tasse de thé, le fish and chips, le garde royal et Big Ben sont des symboles de Londres.',
    },
  ],
  qcm: [
    en({
      id: 'halloween',
      niv: 'f',
      q: 'When is Halloween?',
      r: 'On the 31st of October',
      f: ['On the 25th of December', 'On the 14th of July', 'On the 1st of May'],
      img: '🎃',
      e: 'Halloween, c’est le 31 octobre.',
    }),
    en({
      id: 'trick',
      niv: 'f',
      q: 'What do children say at Halloween?',
      r: 'Trick or treat!',
      f: ['Happy birthday!', 'Merry Christmas!', 'Good night!'],
      e: '« Trick or treat! » = Des bonbons ou un sort !',
    }),
    {
      id: 'bonfire',
      niv: 'p',
      fr: true,
      q: 'Que rappelle Bonfire Night, le 5 novembre, au Royaume-Uni ?',
      r: 'L’échec du complot de Guy Fawkes contre le Parlement, en 1605',
      f: ['La naissance du roi', 'La fin de l’école', 'L’arrivée du printemps'],
      e: 'On allume des feux de joie et des feux d’artifice pour fêter l’échec du complot de 1605.',
    },
    en({
      id: 'stpatrick',
      niv: 'n',
      q: 'In which country is St Patrick’s Day a national holiday?',
      r: 'Ireland',
      f: ['Scotland', 'France', 'Australia'],
      img: '☘️',
      e: 'La Saint-Patrick (17 mars) est la fête nationale de l’Irlande.',
    }),
    en({
      id: 'stpatrick-date',
      niv: 'p',
      q: 'When is St Patrick’s Day?',
      r: 'On the 17th of March',
      f: ['On the 31st of October', 'On the 5th of November', 'On the 25th of December'],
      e: 'La Saint-Patrick, c’est le 17 mars.',
    }),
    en({
      id: 'thanksgiving',
      niv: 'n',
      q: 'What do Americans often eat at Thanksgiving?',
      r: 'Turkey',
      f: ['Pancakes', 'Pizza', 'Snails'],
      img: '🦃',
      e: 'Pour Thanksgiving, on mange souvent de la dinde (turkey).',
    }),
    en({
      id: 'big-ben',
      niv: 'n',
      q: 'What is the name of the great bell of the clock tower in London?',
      r: 'Big Ben',
      f: ['Big Bob', 'Tower Bridge', 'Buckingham'],
      e: 'Big Ben est la grosse cloche de la tour de l’horloge du Parlement.',
    }),
    en({
      id: 'bus',
      niv: 'f',
      q: 'What colour are London’s double-decker buses?',
      r: 'Red',
      f: ['Blue', 'Green', 'Yellow'],
      img: '🚌',
      e: 'Les bus de Londres sont rouges.',
    }),
    {
      id: 'pancake',
      niv: 'n',
      fr: true,
      q: 'Que mange-t-on pour Pancake Day ?',
      r: 'Des crêpes',
      f: ['Des œufs en chocolat', 'De la dinde', 'Du gâteau d’anniversaire'],
      img: '🥞',
      e: 'Pancake = crêpe ; Pancake Day correspond à Mardi gras.',
    },
    {
      id: 'gauche',
      niv: 'n',
      fr: true,
      q: 'Au Royaume-Uni, de quel côté de la route roulent les voitures ?',
      r: 'À gauche',
      f: ['À droite', 'Au milieu', 'Sur le trottoir'],
      e: 'Au Royaume-Uni, on roule à gauche.',
    },
  ],
  oral: [
    {
      id: 'christmas',
      niv: 'f',
      prompt: 'Dis en anglais : « Joyeux Noël ! » 🎄',
      r: 'Merry Christmas!',
      ok: ['merry christmas', 'happy christmas'],
      e: '« Merry Christmas! »',
    },
    {
      id: 'birthday',
      niv: 'f',
      prompt: 'Dis en anglais : « Joyeux anniversaire ! » 🎂',
      r: 'Happy birthday!',
      ok: ['happy birthday'],
      e: '« Happy birthday! »',
    },
    {
      id: 'trick',
      niv: 'n',
      prompt: 'Dis ce que disent les enfants à Halloween 🎃',
      r: 'Trick or treat!',
      ok: ['trick or treat'],
      e: '« Trick or treat! »',
    },
    {
      id: 'easter',
      niv: 'n',
      prompt: 'Dis en anglais : « Joyeuses Pâques ! » 🐣',
      r: 'Happy Easter!',
      ok: ['happy easter'],
      e: '« Happy Easter! »',
    },
  ],
  vf: [
    {
      id: 'halloween',
      niv: 'f',
      s: 'Halloween a lieu le 31 octobre.',
      v: true,
      e: 'La veille de la Toussaint.',
    },
    {
      id: 'bus',
      niv: 'f',
      s: 'Les bus de Londres à deux étages sont souvent rouges.',
      v: true,
      e: 'Ce sont les « double-decker buses ».',
    },
    {
      id: 'thanksgiving',
      niv: 'f',
      s: 'Thanksgiving est une fête française.',
      v: false,
      e: 'C’est une fête des États-Unis (et du Canada).',
    },
    { id: 'christmas', niv: 'f', s: 'Noël se dit « Christmas » en anglais.', v: true, e: 'Merry Christmas!' },
    { id: 'trick', niv: 'f', s: 'On dit « Trick or treat! » à Noël.', v: false, e: 'On le dit à Halloween.' },
    {
      id: 'bonfire',
      niv: 'n',
      s: 'Pour Bonfire Night, on allume des feux de joie et des feux d’artifice au Royaume-Uni.',
      v: true,
      e: 'C’est le 5 novembre.',
    },
    {
      id: 'stpatrick',
      niv: 'n',
      s: 'La Saint-Patrick est la fête nationale de l’Écosse.',
      v: false,
      e: 'C’est la fête nationale de l’Irlande.',
    },
    {
      id: 'gauche',
      niv: 'n',
      s: 'Au Royaume-Uni, les voitures roulent à gauche.',
      v: true,
      e: 'C’est l’inverse de la France.',
    },
    {
      id: 'pancake',
      niv: 'n',
      s: 'Pancake Day est le jour des crêpes.',
      v: true,
      e: 'Il correspond à Mardi gras.',
    },
    {
      id: 'big-ben',
      niv: 'p',
      s: 'Big Ben est le nom d’un pont de Londres.',
      v: false,
      e: 'Big Ben est la cloche de la tour de l’horloge ; le pont célèbre s’appelle Tower Bridge.',
    },
    {
      id: 'jeudi',
      niv: 'p',
      s: 'Aux États-Unis, Thanksgiving se fête le quatrième jeudi de novembre.',
      v: true,
      e: 'C’est un grand repas en famille.',
    },
    {
      id: 'fawkes',
      niv: 'p',
      s: 'Guy Fawkes a voulu faire sauter le Parlement de Londres en 1605.',
      v: true,
      e: 'Son complot a échoué : c’est ce que rappelle Bonfire Night.',
    },
    {
      id: 'euro',
      niv: 'p',
      s: 'Le Royaume-Uni utilise l’euro.',
      v: false,
      e: 'Sa monnaie est la livre sterling (pound).',
    },
  ],
};

export const ANGLAIS: Fiche[] = [
  PRESENTER,
  DESCRIBE,
  TIME_DATES,
  NUMBERS,
  ROUTINES,
  SCHOOL,
  FOOD,
  COUNTRIES,
  CAN_HAVE_GOT,
  CULTURE,
];
