/**
 * Enseignement moral et civique CM2 (programme en vigueur, version à confirmer : `programme: "en_vigueur"`).
 * Les connaissances neutres (symboles, institutions) peuvent se jouer dans la Guillotine ; les situations de vie
 * (`g: false`) ne s'y jouent jamais et vont au Conseil de la classe. Qui suis-je ? n'accepte en EMC que les
 * devinettes à indices (`hints`).
 */
import { PAIRES_SYMBOLES } from './histoire2020';
import type { Fiche } from './outils';

const VALEURS: Fiche = {
  lecon: 'CM2.EMC.VALEURS',
  qcm: [
    {
      id: 'devise',
      niv: 'f',
      q: 'Quelle est la devise de la République française ?',
      r: 'Liberté, Égalité, Fraternité',
      f: ['Paix, Joie, Amitié', 'Un pour tous, tous pour un', 'Honneur et Courage'],
      img: '🇫🇷',
      e: 'La devise est écrite sur la façade des mairies et des écoles.',
    },
    {
      id: 'hymne',
      niv: 'f',
      q: 'Quel est l’hymne national de la France ?',
      r: 'La Marseillaise',
      f: ['Frère Jacques', 'L’Hymne à la joie', 'Au clair de la lune'],
      e: 'La Marseillaise est l’hymne national ; l’Hymne à la joie est l’hymne européen.',
    },
    {
      id: 'drapeau',
      niv: 'f',
      q: 'Quelles sont les couleurs du drapeau français ?',
      r: 'Bleu, blanc, rouge',
      f: ['Bleu, blanc, vert', 'Rouge, jaune, vert', 'Noir, rouge, jaune'],
      e: 'Le drapeau tricolore est bleu, blanc, rouge.',
    },
    {
      id: 'fete',
      niv: 'f',
      q: 'Quelle est la date de la fête nationale ?',
      r: 'Le 14 juillet',
      f: ['Le 1er janvier', 'Le 11 novembre', 'Le 25 décembre'],
      e: 'Le 14 Juillet est la fête nationale depuis 1880.',
    },
    {
      id: 'laicite',
      niv: 'n',
      q: 'Que signifie la laïcité à l’école publique ?',
      r: 'L’école est neutre : elle respecte toutes les croyances et n’en impose aucune.',
      f: [
        'Tous les élèves doivent avoir la même religion.',
        'Les élèves doivent prier ensemble.',
        'Il est interdit de parler de religion en famille.',
      ],
      e: 'La laïcité protège la liberté de croire ou de ne pas croire.',
    },
    {
      id: 'egalite',
      niv: 'n',
      q: 'Que signifie « Égalité » dans la devise ?',
      r: 'Tous les citoyens ont les mêmes droits et les mêmes devoirs devant la loi.',
      f: [
        'Tout le monde doit avoir la même taille.',
        'Tout le monde gagne le même argent.',
        'Tout le monde doit penser la même chose.',
      ],
      e: 'La loi est la même pour tous, sans distinction.',
    },
    {
      id: 'fraternite',
      niv: 'n',
      q: 'Que signifie « Fraternité » ?',
      r: 'S’entraider et être solidaires',
      f: ['Avoir beaucoup de frères', 'Faire ce que l’on veut', 'Obéir au plus fort'],
      e: 'La fraternité, c’est se sentir proches et s’entraider, comme dans une famille.',
    },
    {
      id: 'ou',
      niv: 'n',
      q: 'Où la devise de la République est-elle souvent inscrite ?',
      r: 'Sur la façade des mairies et des écoles',
      f: ['Sur les panneaux routiers', 'Sur les billets de train', 'Sur les boîtes de céréales'],
      e: 'Elle est inscrite sur les bâtiments publics.',
    },
    {
      id: 'charte',
      niv: 'p',
      q: 'Où la Charte de la laïcité à l’École est-elle affichée ?',
      r: 'Dans toutes les écoles publiques',
      f: ['Seulement dans les mairies', 'Dans les supermarchés', 'Nulle part'],
      e: 'Depuis 2013, la Charte de la laïcité est affichée dans les écoles publiques.',
    },
    {
      id: 'article1',
      niv: 'p',
      q: 'Que dit l’article 1 de la Déclaration des droits de l’homme et du citoyen ?',
      r: 'Les hommes naissent et demeurent libres et égaux en droits.',
      f: [
        'Le roi décide de tout.',
        'Les plus forts ont plus de droits.',
        'Chacun doit avoir la même religion.',
      ],
      e: 'Ce texte de 1789 fonde les valeurs de la République.',
    },
    {
      id: 'qui-marianne',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Marianne',
      f: ['Jeanne d’Arc', 'Marie-Antoinette', 'Olympe de Gouges'],
      hints: [
        'Je suis une femme, mais je n’ai jamais existé.',
        'Je porte souvent un bonnet phrygien.',
        'Mon buste se trouve dans les mairies.',
        'Je représente la République française.',
      ],
      img: '🇫🇷',
      e: 'Marianne est l’allégorie de la République.',
    },
    {
      id: 'qui-devise',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'La devise de la République',
      f: ['L’hymne national', 'Le drapeau', 'La fête nationale'],
      hints: [
        'Je suis faite de trois mots.',
        'On me lit au fronton des mairies et des écoles.',
        'Mon premier mot est « Liberté ».',
      ],
      img: '🏛️',
      e: 'La devise « Liberté, Égalité, Fraternité ».',
    },
    {
      id: 'nouvel-eleve',
      niv: 'f',
      g: false,
      q: 'Un nouvel élève arrive et ne parle pas encore bien français. Que fais-tu ?',
      r: 'Je l’aide et je l’invite à jouer avec nous.',
      f: [
        'Je me moque de son accent.',
        'Je fais comme s’il n’existait pas.',
        'Je dis aux autres de ne pas lui parler.',
      ],
      img: '🤝',
      e: 'Accueillir et aider, c’est la fraternité.',
    },
    {
      id: 'croyances',
      niv: 'n',
      g: false,
      q: 'À la cantine, Léo se moque de Sami parce que sa famille a une autre religion. Que dis-tu ?',
      r: 'Chacun est libre de croire ou de ne pas croire : on se respecte.',
      f: ['Léo a raison de se moquer.', 'Sami doit changer de religion.', 'Je ris avec Léo.'],
      img: '🍽️',
      e: 'La laïcité et le respect protègent la liberté de chacun.',
    },
  ],
  vf: [
    {
      id: 'devise',
      niv: 'f',
      s: 'La devise de la République est « Liberté, Égalité, Fraternité ».',
      v: true,
      e: 'Elle est inscrite sur les bâtiments publics.',
    },
    {
      id: 'marianne',
      niv: 'f',
      s: 'Marianne est un symbole de la République française.',
      v: true,
      e: 'Son buste est dans les mairies.',
    },
    {
      id: 'drapeau',
      niv: 'f',
      s: 'Le drapeau français est bleu, blanc et vert.',
      v: false,
      e: 'Il est bleu, blanc et rouge.',
    },
    { id: '14', niv: 'f', s: 'Le 14 Juillet est la fête nationale.', v: true, e: 'Depuis 1880.' },
    {
      id: 'moquer',
      niv: 'f',
      s: 'La fraternité, c’est se moquer de ceux qui sont différents.',
      v: false,
      e: 'La fraternité, c’est s’entraider et se respecter.',
    },
    {
      id: 'hymne-ue',
      niv: 'n',
      s: 'La Marseillaise est l’hymne de l’Union européenne.',
      v: false,
      e: 'C’est l’hymne de la France ; celui de l’Union européenne est l’Hymne à la joie.',
    },
    {
      id: 'croire',
      niv: 'n',
      s: 'La laïcité permet à chacun de croire ou de ne pas croire.',
      v: true,
      e: 'C’est la liberté de conscience.',
    },
    {
      id: 'religion',
      niv: 'n',
      s: 'À l’école publique, on enseigne une religion obligatoire.',
      v: false,
      e: 'L’école publique est laïque.',
    },
    {
      id: 'loi',
      niv: 'n',
      s: 'L’égalité signifie que la loi est la même pour tous.',
      v: true,
      e: 'Sans distinction d’origine, de sexe ou de religion.',
    },
    {
      id: 'coq',
      niv: 'p',
      s: 'Le coq est un symbole officiel inscrit dans la Constitution.',
      v: false,
      e: 'Le coq est un emblème populaire, mais la Constitution cite le drapeau, l’hymne et la devise.',
    },
    {
      id: 'constitution',
      niv: 'p',
      s: 'La Constitution de la France cite le drapeau tricolore, La Marseillaise et la devise.',
      v: true,
      e: 'C’est son article 2.',
    },
    {
      id: 'conscience',
      niv: 'p',
      s: 'La laïcité protège la liberté de conscience.',
      v: true,
      e: 'Chacun pense et croit librement, dans le respect de la loi.',
    },
  ],
  paires: [{ id: 'symboles', niv: 'f', ...PAIRES_SYMBOLES }],
};

const INSTITUTIONS: Fiche = {
  lecon: 'CM2.EMC.INSTITUTIONS',
  qcm: [
    {
      id: 'maire',
      niv: 'f',
      q: 'Qui dirige la commune ?',
      r: 'Le maire',
      f: ['Le président de la République', 'Le préfet', 'Le directeur de l’école'],
      img: '🏛️',
      e: 'Le maire, avec le conseil municipal, dirige la commune.',
    },
    {
      id: 'conseil',
      niv: 'n',
      q: 'Qui élit le conseil municipal ?',
      r: 'Les habitants de la commune qui ont le droit de vote',
      f: ['Le président de la République', 'Les enfants de l’école', 'Le maire tout seul'],
      e: 'Les électeurs de la commune votent pour le conseil municipal, qui élit ensuite le maire.',
    },
    {
      id: 'cinq',
      niv: 'n',
      q: 'Pour combien d’années le président de la République est-il élu ?',
      r: '5 ans',
      f: ['1 an', '10 ans', 'Toute sa vie'],
      e: 'C’est le quinquennat : un mandat de 5 ans.',
    },
    {
      id: 'lois',
      niv: 'n',
      q: 'Qui vote les lois en France ?',
      r: 'Le Parlement (l’Assemblée nationale et le Sénat)',
      f: ['Le maire', 'Le président tout seul', 'Les juges'],
      e: 'Les députés et les sénateurs votent les lois.',
    },
    {
      id: 'deputes',
      niv: 'n',
      q: 'Comment s’appellent les élus de l’Assemblée nationale ?',
      r: 'Les députés',
      f: ['Les sénateurs', 'Les maires', 'Les préfets'],
      e: 'Les députés siègent à l’Assemblée nationale.',
    },
    {
      id: '577',
      niv: 'p',
      q: 'Combien y a-t-il de députés à l’Assemblée nationale ?',
      r: '577',
      f: ['27', '100', '1 000'],
      e: 'L’Assemblée nationale compte 577 députés.',
    },
    {
      id: 'elysee',
      niv: 'n',
      q: 'Où travaille le président de la République ?',
      r: 'Au palais de l’Élysée',
      f: ['Au château de Versailles', 'À la tour Eiffel', 'Au musée du Louvre'],
      e: 'Le palais de l’Élysée est à Paris.',
    },
    {
      id: 'premier-ministre',
      niv: 'p',
      q: 'Qui nomme le Premier ministre ?',
      r: 'Le président de la République',
      f: ['Le maire de Paris', 'Les sénateurs', 'Les citoyens, directement'],
      e: 'Le président nomme le Premier ministre, qui dirige le gouvernement.',
    },
    {
      id: '18',
      niv: 'f',
      q: 'À partir de quel âge peut-on voter en France ?',
      r: '18 ans',
      f: ['10 ans', '16 ans', '25 ans'],
      e: 'On devient électeur à 18 ans.',
    },
    {
      id: 'conseil-role',
      niv: 'n',
      q: 'Que fait le conseil municipal ?',
      r: 'Il décide des projets de la commune (écoles, cantine, parcs…).',
      f: ['Il vote les lois de la France.', 'Il choisit le président.', 'Il juge les voleurs.'],
      e: 'Le conseil municipal gère la commune.',
    },
    {
      id: 'mairie',
      niv: 'f',
      q: 'Comment s’appelle le bâtiment où travaille le maire ?',
      r: 'La mairie (l’hôtel de ville)',
      f: ['La préfecture', 'Le palais de l’Élysée', 'Le Sénat'],
      e: 'La mairie est la maison commune des habitants.',
    },
    {
      id: 'qui-maire',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le maire',
      f: ['Le président de la République', 'Le député', 'Le préfet'],
      hints: [
        'Je suis élu par le conseil municipal.',
        'Je célèbre les mariages.',
        'Je m’occupe des bâtiments des écoles de ma commune.',
        'Je porte une écharpe tricolore et je travaille à la mairie.',
      ],
      img: '🏛️',
      e: 'Le maire dirige la commune.',
    },
    {
      id: 'qui-president',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le président de la République',
      f: ['Le Premier ministre', 'Le maire de Paris', 'Le président du Sénat'],
      hints: [
        'Je suis élu pour 5 ans.',
        'Tous les électeurs de France peuvent voter pour moi.',
        'Je suis le chef des armées.',
        'Je travaille au palais de l’Élysée.',
      ],
      img: '🇫🇷',
      e: 'Le président de la République est élu au suffrage universel direct pour 5 ans.',
    },
  ],
  vf: [
    { id: 'maire', niv: 'f', s: 'Le maire dirige la commune.', v: true, e: 'Avec le conseil municipal.' },
    {
      id: 'lois-maire',
      niv: 'f',
      s: 'Les lois de la France sont votées par le maire.',
      v: false,
      e: 'Elles sont votées par le Parlement.',
    },
    {
      id: 'enfants',
      niv: 'f',
      s: 'Les enfants de 10 ans peuvent voter aux élections municipales.',
      v: false,
      e: 'Il faut avoir 18 ans pour voter.',
    },
    {
      id: 'echarpe',
      niv: 'f',
      s: 'Le maire porte une écharpe tricolore lors des cérémonies.',
      v: true,
      e: 'Elle est bleu, blanc, rouge.',
    },
    {
      id: 'cinq',
      niv: 'n',
      s: 'Le président de la République est élu pour 5 ans.',
      v: true,
      e: 'C’est le quinquennat.',
    },
    {
      id: 'parlement',
      niv: 'n',
      s: 'Le Parlement est composé de l’Assemblée nationale et du Sénat.',
      v: true,
      e: 'Les députés et les sénateurs.',
    },
    {
      id: 'conseil',
      niv: 'n',
      s: 'Le conseil municipal est élu par les habitants de la commune.',
      v: true,
      e: 'Lors des élections municipales.',
    },
    {
      id: 'roi',
      niv: 'n',
      s: 'En France, c’est un roi qui vote les lois.',
      v: false,
      e: 'La France est une république : le Parlement vote les lois.',
    },
    {
      id: 'senat',
      niv: 'p',
      s: 'Le Sénat siège au palais de l’Élysée.',
      v: false,
      e: 'Le Sénat siège au palais du Luxembourg ; l’Élysée est la résidence du président.',
    },
    {
      id: 'direct',
      niv: 'p',
      s: 'Le président de la République est élu directement par les citoyens.',
      v: true,
      e: 'C’est le suffrage universel direct.',
    },
    {
      id: '577',
      niv: 'p',
      s: 'L’Assemblée nationale compte 577 députés.',
      v: true,
      e: 'Chaque député représente une circonscription.',
    },
    {
      id: 'prefet',
      niv: 'p',
      s: 'Le préfet est élu par les habitants.',
      v: false,
      e: 'Le préfet est nommé par le gouvernement.',
    },
  ],
  paires: [
    {
      id: 'lieux',
      niv: 'n',
      prompt: 'Associe chaque responsable au lieu où il travaille.',
      relation: 'élu → lieu',
      pairs: [
        ['le maire', 'la mairie'],
        ['le président de la République', 'le palais de l’Élysée'],
        ['le député', 'l’Assemblée nationale'],
        ['le sénateur', 'le Sénat'],
        ['le préfet', 'la préfecture'],
      ],
      e: 'Chaque responsable travaille dans un lieu de la République.',
    },
  ],
  etapes: [
    {
      id: 'vote',
      niv: 'n',
      prompt: 'Remets dans l’ordre les étapes d’un vote au bureau de vote.',
      els: [
        'Je prends les bulletins et une enveloppe.',
        'Je passe dans l’isoloir et je mets mon bulletin dans l’enveloppe.',
        'Je glisse l’enveloppe dans l’urne.',
        'Je signe la liste des électeurs.',
        'Le soir, on compte les bulletins : c’est le dépouillement.',
      ],
      e: 'Le vote est secret grâce à l’isoloir ; le dépouillement est public.',
    },
    {
      id: 'loi',
      niv: 'p',
      prompt: 'Remets dans l’ordre le chemin d’une loi (version simplifiée).',
      els: [
        'Un projet de loi est proposé.',
        'Les députés en débattent et le votent.',
        'Les sénateurs en débattent et le votent.',
        'Le président de la République promulgue la loi.',
        'La loi s’applique à tous.',
      ],
      e: 'Le Parlement vote la loi, puis le président la promulgue.',
    },
  ],
};

const DROITS: Fiche = {
  lecon: 'CM2.EMC.DROITS',
  evts: [
    {
      id: 'ddhc',
      niv: 'n',
      label: 'Déclaration des droits de l’homme et du citoyen',
      date: '1789',
      t: 1789.08,
    },
    { id: 'vote-femmes', niv: 'n', label: 'Droit de vote des femmes en France', date: '1944', t: 1944.04 },
    {
      id: 'dudh',
      niv: 'p',
      label: 'Déclaration universelle des droits de l’homme',
      date: '1948',
      t: 1948.12,
    },
    {
      id: 'cide',
      niv: 'f',
      label: 'Convention internationale des droits de l’enfant',
      date: '1989',
      t: 1989.11,
      e: 'Le 20 novembre 1989, l’ONU adopte la Convention internationale des droits de l’enfant.',
    },
  ],
  qcm: [
    {
      id: 'cide',
      niv: 'f',
      q: 'Quel texte protège les droits de tous les enfants du monde ?',
      r: 'La Convention internationale des droits de l’enfant',
      f: ['Le Code de la route', 'Le règlement de la cantine', 'Le traité de Rome'],
      e: 'Elle a été adoptée en 1989 par l’ONU.',
    },
    {
      id: '20-novembre',
      niv: 'n',
      q: 'Quel jour célèbre-t-on la Journée internationale des droits de l’enfant ?',
      r: 'Le 20 novembre',
      f: ['Le 14 juillet', 'Le 1er avril', 'Le 25 décembre'],
      e: 'C’est l’anniversaire de la Convention, adoptée le 20 novembre 1989.',
    },
    {
      id: 'ecole',
      niv: 'f',
      q: 'Lequel est un droit de l’enfant ?',
      r: 'Aller à l’école',
      f: ['Conduire une voiture', 'Voter', 'Travailler à l’usine'],
      e: 'Tous les enfants ont droit à l’éducation.',
    },
    {
      id: '18',
      niv: 'n',
      q: 'Selon la Convention, jusqu’à quel âge est-on un enfant ?',
      r: 'Jusqu’à 18 ans',
      f: ['Jusqu’à 10 ans', 'Jusqu’à 12 ans', 'Jusqu’à 25 ans'],
      e: 'La Convention protège tous les jeunes de moins de 18 ans.',
    },
    {
      id: 'onu',
      niv: 'p',
      q: 'Quelle organisation a adopté la Convention des droits de l’enfant ?',
      r: 'L’ONU (Organisation des Nations unies)',
      f: ['L’Union européenne', 'La mairie de Paris', 'Le Parlement français'],
      e: 'L’ONU réunit presque tous les pays du monde.',
    },
    {
      id: '119',
      niv: 'n',
      g: false,
      q: 'Quel numéro gratuit peut-on appeler si un enfant est en danger ?',
      r: 'Le 119',
      f: ['Le 3615', 'Le 1234', 'Le 007'],
      img: '📞',
      e: 'Le 119 (Allô Enfance en danger) répond jour et nuit, gratuitement.',
    },
    {
      id: 'egaux',
      niv: 'f',
      q: 'Les filles et les garçons ont…',
      r: 'les mêmes droits',
      f: ['des droits différents', 'aucun droit', 'des droits seulement à 18 ans'],
      e: 'L’égalité entre les filles et les garçons est un principe de la République.',
    },
    {
      id: 'foot',
      niv: 'n',
      g: false,
      q: 'À la récré, des garçons disent à Inès qu’elle ne peut pas jouer au foot « parce que c’est un jeu de garçons ». Que fais-tu ?',
      r: 'Je leur rappelle que filles et garçons peuvent jouer à tous les jeux.',
      f: ['Je suis d’accord avec eux.', 'Je ne dis rien.', 'Je dis à Inès d’aller jouer ailleurs.'],
      img: '⚽',
      e: 'Filles et garçons ont les mêmes droits, y compris pour jouer.',
    },
    {
      id: 'devoir',
      niv: 'n',
      g: false,
      q: 'Les droits vont avec des devoirs. Lequel est un devoir de l’élève ?',
      r: 'Respecter les autres et le règlement',
      f: ['Ne jamais faire ses devoirs', 'Décider seul des règles de la classe', 'Se moquer des autres'],
      e: 'Avoir des droits, c’est aussi respecter ceux des autres.',
    },
    {
      id: 'qui-cide',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'La Convention internationale des droits de l’enfant',
      f: ['La Déclaration des droits de l’homme et du citoyen', 'Le Code civil', 'La Constitution'],
      hints: [
        'Je suis un texte international.',
        'J’ai été adoptée par l’ONU le 20 novembre 1989.',
        'J’ai 54 articles.',
        'Je protège les droits de tous les enfants du monde.',
      ],
      img: '📜',
      e: 'La Convention internationale des droits de l’enfant protège les moins de 18 ans.',
    },
  ],
  vf: [
    {
      id: 'ecole',
      niv: 'f',
      s: 'Tous les enfants ont le droit d’aller à l’école.',
      v: true,
      e: 'C’est le droit à l’éducation.',
    },
    {
      id: 'egaux',
      niv: 'f',
      s: 'Les filles et les garçons ont les mêmes droits.',
      v: true,
      e: 'C’est l’égalité.',
    },
    {
      id: 'violence',
      niv: 'f',
      s: 'Un enfant a le droit d’être protégé contre la violence.',
      v: true,
      e: 'Les adultes doivent le protéger.',
    },
    {
      id: 'menage',
      niv: 'f',
      s: 'Les tâches de la maison sont réservées aux filles.',
      v: false,
      e: 'Filles et garçons peuvent et doivent participer aux tâches de la maison.',
    },
    {
      id: 'aucun',
      niv: 'f',
      s: 'Un enfant n’a aucun droit avant 18 ans.',
      v: false,
      e: 'Les enfants ont des droits, protégés par la Convention de 1989.',
    },
    {
      id: '1989',
      niv: 'n',
      s: 'La Convention internationale des droits de l’enfant a été adoptée en 1989.',
      v: true,
      e: 'Le 20 novembre 1989.',
    },
    {
      id: 'metiers',
      niv: 'n',
      s: 'En France, certains métiers sont interdits aux filles.',
      v: false,
      e: 'Tous les métiers sont ouverts aux filles comme aux garçons.',
    },
    {
      id: 'avis',
      niv: 'n',
      s: 'Les enfants n’ont pas le droit de donner leur avis.',
      v: false,
      e: 'Ils ont le droit de s’exprimer sur ce qui les concerne.',
    },
    {
      id: '119',
      niv: 'n',
      s: 'Le 119 est un numéro gratuit pour aider les enfants en danger.',
      v: true,
      e: 'Il répond jour et nuit.',
    },
    {
      id: 'francais',
      niv: 'p',
      s: 'La Convention des droits de l’enfant ne concerne que les enfants français.',
      v: false,
      e: 'Elle concerne les enfants du monde entier.',
    },
    {
      id: 'respecter',
      niv: 'p',
      s: 'Avoir des droits, c’est aussi respecter ceux des autres.',
      v: true,
      e: 'Droits et devoirs vont ensemble.',
    },
    {
      id: 'nom',
      niv: 'p',
      s: 'Un enfant a droit à un nom et à une nationalité.',
      v: true,
      e: 'C’est le droit à l’identité.',
    },
    {
      id: 'loisirs',
      niv: 'p',
      s: 'Le droit de jouer et d’avoir des loisirs fait partie des droits de l’enfant.',
      v: true,
      e: 'C’est l’article 31 de la Convention.',
    },
  ],
  paires: [
    {
      id: 'droits',
      niv: 'n',
      prompt: 'Associe chaque droit à un exemple.',
      relation: 'droit → exemple',
      pairs: [
        ['le droit à l’éducation', 'aller à l’école'],
        ['le droit à la santé', 'être soigné quand on est malade'],
        ['le droit aux loisirs', 'jouer et se reposer'],
        ['le droit à une identité', 'avoir un nom et une nationalité'],
        ['le droit d’expression', 'donner son avis'],
        ['le droit à la protection', 'être protégé de la violence'],
      ],
      e: 'La Convention de 1989 protège tous ces droits.',
    },
  ],
};

const HARCELEMENT: Fiche = {
  lecon: 'CM2.EMC.HARCELEMENT',
  qcm: [
    {
      id: 'yanis',
      niv: 'f',
      g: false,
      q: 'Depuis plusieurs jours, des élèves se moquent de Yanis et le bousculent. Que faut-il faire ?',
      r: 'En parler tout de suite à un adulte de confiance.',
      f: [
        'Ne rien dire, ça va passer tout seul.',
        'Se moquer aussi pour ne pas être embêté.',
        'Garder le secret pour toujours.',
      ],
      img: '🛑',
      e: 'Des moqueries répétées, c’est du harcèlement : on en parle à un adulte.',
    },
    {
      id: 'definition',
      niv: 'n',
      g: false,
      q: 'Qu’est-ce que le harcèlement ?',
      r: 'Des violences (moqueries, coups, mise à l’écart) répétées contre une même personne',
      f: [
        'Une dispute qui arrive une seule fois',
        'Un jeu où tout le monde s’amuse',
        'Un désaccord pendant un débat',
      ],
      e: 'Le harcèlement, c’est la répétition qui fait souffrir.',
    },
    {
      id: '3018',
      niv: 'n',
      g: false,
      q: 'Quel numéro gratuit peut-on appeler en cas de harcèlement ou de cyberharcèlement ?',
      r: 'Le 3018',
      f: ['Le 3615', 'Le 1515', 'Le 0101'],
      img: '📞',
      e: 'Le 3018 est gratuit, anonyme et confidentiel.',
    },
    {
      id: 'cyber',
      niv: 'n',
      g: false,
      q: 'Qu’est-ce que le cyberharcèlement ?',
      r: 'Du harcèlement sur Internet, les réseaux sociaux ou les téléphones',
      f: ['Un jeu vidéo', 'Un virus informatique', 'Une panne d’Internet'],
      e: 'Les messages méchants répétés en ligne sont du cyberharcèlement.',
    },
    {
      id: 'temoin',
      niv: 'f',
      g: false,
      q: 'Tu vois des moqueries répétées contre un camarade. Que fais-tu ?',
      r: 'Je soutiens la victime et je préviens un adulte.',
      f: [
        'Je ris avec les autres.',
        'Je filme la scène pour la partager.',
        'Je fais comme si je n’avais rien vu.',
      ],
      e: 'Le témoin peut aider la victime en réagissant.',
    },
    {
      id: 'photo',
      niv: 'n',
      g: false,
      q: 'Quelqu’un publie une photo de toi sans ton accord pour se moquer. Que fais-tu ?',
      r: 'Je garde une preuve (capture d’écran) et j’en parle à un adulte.',
      f: [
        'Je réponds par des insultes.',
        'Je ne dis rien à personne.',
        'Je publie une photo de lui pour me venger.',
      ],
      e: 'On ne répond pas, on garde des preuves et on demande de l’aide.',
    },
    {
      id: 'like',
      niv: 'n',
      g: false,
      q: 'Pourquoi ne faut-il pas « aimer » ni partager un message méchant ?',
      r: 'Parce que cela participe au harcèlement et blesse la victime.',
      f: [
        'Parce que cela coûte de l’argent.',
        'Parce que cela abîme le téléphone.',
        'Ce n’est pas grave de le partager.',
      ],
      e: 'Partager un message méchant, c’est aussi harceler.',
    },
    {
      id: 'secret',
      niv: 'p',
      g: false,
      q: 'Un élève te dit qu’il est harcelé mais te demande de garder le secret. Que fais-tu ?',
      r: 'J’en parle quand même à un adulte de confiance pour l’aider.',
      f: [
        'Je garde le secret pour toujours.',
        'Je le raconte à toute la classe.',
        'Je lui dis que ce n’est pas grave.',
      ],
      e: 'Ce n’est pas trahir : c’est protéger ton camarade.',
    },
    {
      id: 'loi',
      niv: 'p',
      g: false,
      q: 'Le harcèlement scolaire est-il puni par la loi en France ?',
      r: 'Oui, c’est un délit depuis 2022.',
      f: ['Non, c’est autorisé.', 'Seulement le week-end.', 'Seulement entre adultes.'],
      e: 'La loi de 2022 fait du harcèlement scolaire un délit.',
    },
    {
      id: 'adulte',
      niv: 'f',
      g: false,
      q: 'Qu’est-ce qu’un adulte de confiance ?',
      r: 'Un adulte qui peut t’écouter et t’aider : parent, enseignant, infirmière…',
      f: ['Un inconnu rencontré en ligne', 'Un élève plus grand', 'Personne'],
      e: 'Il faut toujours pouvoir parler à un adulte de confiance.',
    },
    {
      id: 'qui-temoin',
      niv: 'n',
      g: false,
      q: 'Qui suis-je ?',
      r: 'Le témoin',
      f: ['Le harceleur', 'La victime', 'L’arbitre'],
      hints: [
        'Je ne suis ni la victime ni celui qui harcèle.',
        'Je vois ce qui se passe.',
        'Si je ris, j’encourage le harceleur.',
        'Si je réagis et préviens un adulte, j’aide la victime.',
      ],
      img: '👀',
      e: 'Le témoin a un grand pouvoir : il peut faire cesser le harcèlement.',
    },
  ],
  vf: [
    {
      id: 'repetees',
      niv: 'f',
      s: 'Des moqueries répétées contre la même personne, c’est du harcèlement.',
      v: true,
      e: 'C’est la répétition qui en fait du harcèlement.',
    },
    {
      id: 'secret',
      niv: 'f',
      s: 'Si on est harcelé, il vaut mieux garder le secret.',
      v: false,
      e: 'Il faut en parler à un adulte de confiance.',
    },
    {
      id: 'temoin',
      niv: 'f',
      s: 'Un témoin peut aider la victime en prévenant un adulte.',
      v: true,
      e: 'Réagir, c’est aider.',
    },
    {
      id: 'stop',
      niv: 'f',
      s: 'On peut dire « stop » et demander de l’aide.',
      v: true,
      e: 'Personne ne doit rester seul face au harcèlement.',
    },
    {
      id: 'jeu',
      niv: 'f',
      s: 'Se moquer d’un camarade tous les jours, c’est juste un jeu.',
      v: false,
      e: 'C’est du harcèlement, et cela fait souffrir.',
    },
    {
      id: 'cyber',
      niv: 'n',
      s: 'Le cyberharcèlement se passe sur Internet et sur les téléphones.',
      v: true,
      e: 'Messages, photos, vidéos méchantes répétées.',
    },
    {
      id: 'photo',
      niv: 'n',
      s: 'Partager une photo moqueuse d’un camarade, ce n’est pas grave.',
      v: false,
      e: 'C’est blessant et cela participe au harcèlement.',
    },
    {
      id: '3018',
      niv: 'n',
      s: 'Le 3018 est un numéro gratuit pour les victimes de harcèlement et de cyberharcèlement.',
      v: true,
      e: 'Il est aussi joignable par une application.',
    },
    {
      id: 'anonyme',
      niv: 'n',
      s: 'Sur Internet, on peut tout écrire car personne ne sait qui on est.',
      v: false,
      e: 'On peut retrouver l’auteur d’un message, et la loi s’applique aussi en ligne.',
    },
    {
      id: 'une-fois',
      niv: 'p',
      s: 'Une dispute qui arrive une seule fois est toujours du harcèlement.',
      v: false,
      e: 'Le harcèlement, ce sont des violences répétées.',
    },
    {
      id: 'delit',
      niv: 'p',
      s: 'Le harcèlement scolaire est puni par la loi.',
      v: true,
      e: 'C’est un délit depuis 2022.',
    },
    {
      id: 'rire',
      niv: 'p',
      s: 'Quand on voit du harcèlement, rire avec les autres encourage le harceleur.',
      v: true,
      e: 'Le harceleur a besoin de spectateurs.',
    },
    {
      id: 'faute',
      niv: 'p',
      s: 'Les victimes de harcèlement sont responsables de ce qui leur arrive.',
      v: false,
      e: 'La victime n’y est pour rien : c’est le harceleur qui est en faute.',
    },
  ],
  paires: [
    {
      id: 'roles',
      niv: 'n',
      prompt: 'Associe chaque personne à ce qu’elle peut faire.',
      relation: 'personne → action',
      pairs: [
        ['la victime', 'en parler à un adulte'],
        ['le témoin', 'soutenir et alerter'],
        ['l’adulte de confiance', 'protéger et agir'],
        ['le 3018', 'écouter et conseiller gratuitement'],
      ],
      e: 'Contre le harcèlement, chacun a un rôle à jouer.',
    },
  ],
};

const NUMERIQUE: Fiche = {
  lecon: 'CM2.EMC.NUMERIQUE',
  qcm: [
    {
      id: 'adresse',
      niv: 'f',
      g: false,
      q: 'Un inconnu te demande ton adresse dans un jeu en ligne. Que fais-tu ?',
      r: 'Je ne la donne pas et je préviens un adulte.',
      f: [
        'Je la donne, il a l’air gentil.',
        'Je lui envoie aussi une photo.',
        'Je lui donne mon numéro de téléphone.',
      ],
      img: '🔒',
      e: 'On ne donne jamais d’informations personnelles à un inconnu.',
    },
    {
      id: 'mdp',
      niv: 'n',
      q: 'Un bon mot de passe est…',
      r: 'long, avec des lettres, des chiffres et des symboles, et secret',
      f: ['ton prénom', '1234', 'la date de ton anniversaire'],
      e: 'Un mot de passe long et varié est difficile à deviner.',
    },
    {
      id: 'mdp-qui',
      niv: 'f',
      g: false,
      q: 'À qui peux-tu confier ton mot de passe ?',
      r: 'À tes parents seulement',
      f: ['À tes copains', 'À un inconnu sympa', 'À tout le monde'],
      e: 'Un mot de passe est secret ; seuls tes parents peuvent le connaître.',
    },
    {
      id: 'infox',
      niv: 'n',
      q: 'Qu’est-ce qu’une fausse information (une infox) ?',
      r: 'Une information inventée ou trompeuse présentée comme vraie',
      f: ['Une information très ancienne', 'Une information en anglais', 'Une information drôle'],
      e: 'Les fausses informations circulent vite : il faut les vérifier.',
    },
    {
      id: 'verifier',
      niv: 'n',
      q: 'Comment vérifier une information trouvée sur Internet ?',
      r: 'Regarder qui l’a écrite et la comparer avec d’autres sources sérieuses',
      f: [
        'La croire si elle a beaucoup de « j’aime »',
        'La partager tout de suite',
        'La croire si elle fait peur',
      ],
      e: 'On cherche l’auteur, la date et d’autres sources fiables.',
    },
    {
      id: 'droit-image',
      niv: 'n',
      g: false,
      q: 'Avant de publier la photo d’un ami, il faut…',
      r: 'lui demander son accord',
      f: ['la modifier pour qu’il soit ridicule', 'la publier très vite', 'l’envoyer à des inconnus'],
      e: 'Chacun a un droit à l’image : on demande toujours l’accord.',
    },
    {
      id: 'donnees',
      niv: 'p',
      q: 'Que sont les données personnelles ?',
      r: 'Les informations qui permettent de t’identifier (nom, adresse, photo…)',
      f: ['Les jeux installés sur une tablette', 'Les dessins de la classe', 'La météo du jour'],
      e: 'Tes données personnelles doivent être protégées.',
    },
    {
      id: 'arnaque',
      niv: 'n',
      g: false,
      q: 'Un message dit : « Tu as gagné un téléphone ! Clique vite ici ! » C’est sûrement…',
      r: 'une arnaque',
      f: ['un vrai cadeau', 'un message de l’école', 'une information sûre'],
      e: 'On ne clique pas : on montre le message à un adulte.',
    },
    {
      id: 'ecrans',
      niv: 'f',
      q: 'Pourquoi faut-il limiter le temps passé devant les écrans ?',
      r: 'Pour bien dormir, bouger et garder du temps pour d’autres activités',
      f: ['Parce que les écrans s’usent', 'Parce que c’est interdit par la loi', 'Il ne faut pas le limiter'],
      e: 'Trop d’écrans fatigue et empêche de bouger et de bien dormir.',
    },
    {
      id: 'source',
      niv: 'p',
      q: 'Qu’est-ce qu’une source d’information ?',
      r: 'L’origine d’une information : un journal, un site, un auteur…',
      f: ['Une fontaine', 'Un ordinateur en panne', 'Un mot de passe'],
      e: 'Connaître la source aide à juger si l’information est fiable.',
    },
    {
      id: 'qui-mdp',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le mot de passe',
      f: ['Le pseudo', 'L’adresse électronique', 'Le nom d’utilisateur'],
      hints: [
        'Je suis secret.',
        'Je protège tes comptes.',
        'Plus je suis long et compliqué, mieux je te protège.',
        'On me tape pour se connecter.',
      ],
      img: '🔑',
      e: 'Le mot de passe protège tes comptes : garde-le secret.',
    },
  ],
  vf: [
    {
      id: 'amis',
      niv: 'f',
      s: 'Je peux donner mon mot de passe à mes amis.',
      v: false,
      e: 'Un mot de passe reste secret.',
    },
    {
      id: 'tout-vrai',
      niv: 'f',
      s: 'Tout ce qui est écrit sur Internet est vrai.',
      v: false,
      e: 'Il y a aussi des erreurs et des fausses informations.',
    },
    {
      id: 'inconnu',
      niv: 'f',
      s: 'Un inconnu rencontré en ligne peut mentir sur son âge.',
      v: true,
      e: 'On ne sait jamais vraiment qui est derrière l’écran.',
    },
    {
      id: 'malaise',
      niv: 'f',
      s: 'Si un message en ligne me met mal à l’aise, j’en parle à un adulte.',
      v: true,
      e: 'C’est le bon réflexe.',
    },
    {
      id: 'accord',
      niv: 'n',
      s: 'Avant de publier la photo de quelqu’un, il faut lui demander son accord.',
      v: true,
      e: 'C’est le droit à l’image.',
    },
    {
      id: 'sources',
      niv: 'n',
      s: 'Pour vérifier une information, on peut la comparer avec plusieurs sources.',
      v: true,
      e: 'Si plusieurs sources sérieuses la confirment, elle est plus fiable.',
    },
    {
      id: 'partagee',
      niv: 'n',
      s: 'Une information partagée des milliers de fois est forcément vraie.',
      v: false,
      e: 'Une fausse information peut aussi être très partagée.',
    },
    {
      id: '123456',
      niv: 'n',
      s: '« 123456 » est un bon mot de passe.',
      v: false,
      e: 'Il est beaucoup trop facile à deviner.',
    },
    {
      id: 'donnees',
      niv: 'p',
      s: 'Les données personnelles doivent être protégées.',
      v: true,
      e: 'Elles permettent de t’identifier.',
    },
    {
      id: 'truquee',
      niv: 'p',
      s: 'Une photo ou une vidéo peut être truquée.',
      v: true,
      e: 'Il existe des logiciels pour modifier les images.',
    },
    {
      id: 'longtemps',
      niv: 'p',
      s: 'Ce que l’on publie sur Internet peut rester très longtemps.',
      v: true,
      e: 'Même effacé, un contenu peut avoir été copié.',
    },
    {
      id: 'serieux',
      niv: 'p',
      s: 'Un site sérieux indique qui a écrit l’information et quand.',
      v: true,
      e: 'L’auteur et la date sont des indices de fiabilité.',
    },
    {
      id: 'images',
      niv: 'p',
      s: 'On peut utiliser n’importe quelle image trouvée sur Internet sans demander.',
      v: false,
      e: 'Les images ont des auteurs : il faut respecter leurs droits.',
    },
  ],
  paires: [
    {
      id: 'reflexes',
      niv: 'n',
      prompt: 'Associe chaque situation au bon réflexe.',
      relation: 'situation → réflexe',
      pairs: [
        ['un inconnu demande mon adresse', 'je ne réponds pas et je préviens un adulte'],
        ['un message « tu as gagné ! »', 'je ne clique pas'],
        ['une information étonnante', 'je vérifie la source'],
        ['je veux publier la photo d’un ami', 'je lui demande son accord'],
        ['je crée un compte', 'je choisis un mot de passe long et secret'],
      ],
      e: 'Sur Internet, de bons réflexes protègent de nombreux dangers.',
    },
  ],
  etapes: [
    {
      id: 'verifier',
      niv: 'n',
      prompt: 'Remets dans l’ordre les étapes pour vérifier une information.',
      els: [
        'Je lis l’information en entier.',
        'Je regarde qui l’a publiée et quand.',
        'Je cherche si d’autres sources sérieuses disent la même chose.',
        'Je décide si je peux y croire avant de la partager.',
      ],
      e: 'Lire, chercher la source, comparer, puis décider : c’est l’esprit critique.',
    },
  ],
};

const ENGAGEMENT: Fiche = {
  lecon: 'CM2.EMC.ENGAGEMENT',
  qcm: [
    {
      id: 'delegues',
      niv: 'f',
      q: 'Comment élit-on les délégués de classe ?',
      r: 'Par un vote à bulletin secret',
      f: [
        'On choisit le plus grand de la classe',
        'Ils se choisissent eux-mêmes',
        'On choisit celui qui crie le plus fort',
      ],
      img: '🗳️',
      e: 'Chaque élève vote en secret pour le candidat de son choix.',
    },
    {
      id: 'role',
      niv: 'n',
      q: 'Quel est le rôle d’un délégué de classe ?',
      r: 'Représenter les élèves et porter leurs idées',
      f: ['Punir les autres élèves', 'Faire les devoirs des autres', 'Décider seul de tout'],
      e: 'Le délégué est le porte-parole de la classe.',
    },
    {
      id: 'engagement',
      niv: 'n',
      q: 'Qu’est-ce que s’engager ?',
      r: 'Agir volontairement pour les autres ou pour une cause',
      f: ['Rester chez soi sans rien faire', 'Obéir sans réfléchir', 'Gagner de l’argent'],
      e: 'On peut s’engager à l’école, dans une association, dans sa commune.',
    },
    {
      id: 'benevole',
      niv: 'n',
      q: 'Qu’est-ce qu’un bénévole ?',
      r: 'Une personne qui aide une association sans être payée',
      f: ['Un vendeur de magasin', 'Un ministre', 'Un élève puni'],
      e: 'Les bénévoles donnent de leur temps pour aider.',
    },
    {
      id: 'ecogeste',
      niv: 'f',
      q: 'Quel geste aide à protéger la planète ?',
      r: 'Éteindre la lumière et trier ses déchets',
      f: ['Laisser couler l’eau', 'Jeter ses papiers par terre', 'Laisser la télévision allumée'],
      e: 'Les petits gestes du quotidien comptent.',
    },
    {
      id: 'eco-delegue',
      niv: 'n',
      q: 'Que fait un éco-délégué ?',
      r: 'Il propose des actions pour protéger l’environnement à l’école.',
      f: ['Il distribue les goûters.', 'Il surveille la récréation.', 'Il range les cahiers.'],
      e: 'Les éco-délégués agissent pour le développement durable.',
    },
    {
      id: 'solidarite',
      niv: 'f',
      q: 'Qu’est-ce que la solidarité ?',
      r: 'S’entraider, surtout envers ceux qui en ont besoin',
      f: ['Rester seul', 'Gagner à tout prix', 'Garder tout pour soi'],
      e: 'Aider un camarade, collecter des dons : c’est être solidaire.',
    },
    {
      id: 'secret',
      niv: 'p',
      q: 'Pourquoi le vote est-il secret ?',
      r: 'Pour que chacun choisisse librement, sans pression',
      f: ['Pour que personne ne vote', 'Pour aller plus vite', 'Parce que c’est un jeu'],
      e: 'Le secret du vote protège la liberté de chaque électeur.',
    },
    {
      id: 'candidat',
      niv: 'n',
      q: 'Qui peut se présenter comme délégué ?',
      r: 'Tout élève de la classe qui le souhaite',
      f: ['Seulement les garçons', 'Seulement les meilleurs élèves', 'Seulement les plus âgés'],
      e: 'Tous les élèves peuvent être candidats.',
    },
    {
      id: 'perdu',
      niv: 'n',
      g: false,
      q: 'Ton camarade a perdu l’élection de délégué. Que fais-tu ?',
      r: 'Je le réconforte et je respecte le résultat du vote.',
      f: ['Je me moque de lui.', 'Je demande d’annuler le vote.', 'Je refuse de parler au gagnant.'],
      e: 'Respecter le résultat d’un vote, c’est la démocratie.',
    },
    {
      id: 'qui-urne',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'L’urne',
      f: ['L’isoloir', 'Le bulletin', 'La mairie'],
      hints: [
        'Je suis une boîte, souvent transparente.',
        'On me trouve dans les bureaux de vote.',
        'On glisse des enveloppes dans ma fente.',
        'Je garde les bulletins jusqu’au dépouillement.',
      ],
      img: '🗳️',
      e: 'L’urne reçoit les enveloppes des électeurs.',
    },
  ],
  vf: [
    {
      id: 'secret',
      niv: 'f',
      s: 'Le vote pour élire les délégués est secret.',
      v: true,
      e: 'Chacun vote librement.',
    },
    {
      id: 'tout',
      niv: 'f',
      s: 'Un délégué peut décider de tout à la place de la classe.',
      v: false,
      e: 'Il représente la classe et porte ses idées.',
    },
    {
      id: 'lumiere',
      niv: 'f',
      s: 'Éteindre la lumière en sortant d’une pièce permet d’économiser l’énergie.',
      v: true,
      e: 'C’est un écogeste.',
    },
    {
      id: 'solidarite',
      niv: 'f',
      s: 'La solidarité, c’est s’entraider.',
      v: true,
      e: 'Surtout envers ceux qui en ont besoin.',
    },
    {
      id: 'robinet',
      niv: 'f',
      s: 'Laisser le robinet ouvert protège l’eau.',
      v: false,
      e: 'On ferme le robinet pour économiser l’eau.',
    },
    {
      id: 'benevole',
      niv: 'n',
      s: 'Un bénévole est payé pour aider une association.',
      v: false,
      e: 'Un bénévole n’est pas payé.',
    },
    {
      id: 'eco-delegues',
      niv: 'n',
      s: 'Les éco-délégués proposent des actions pour l’environnement.',
      v: true,
      e: 'Par exemple le tri ou un potager à l’école.',
    },
    {
      id: 'resultat',
      niv: 'n',
      s: 'Respecter le résultat d’un vote fait partie de la démocratie.',
      v: true,
      e: 'Même quand notre candidat a perdu.',
    },
    {
      id: 'adultes',
      niv: 'n',
      s: 'Seuls les adultes peuvent agir pour protéger la planète.',
      v: false,
      e: 'Les enfants aussi peuvent agir, à l’école et à la maison.',
    },
    {
      id: 'age',
      niv: 'p',
      s: 'On peut s’engager à tout âge, par exemple en aidant les autres à l’école.',
      v: true,
      e: 'L’engagement commence dans la classe.',
    },
    {
      id: 'depouillement',
      niv: 'p',
      s: 'Le dépouillement, c’est le moment où l’on compte les bulletins.',
      v: true,
      e: 'Il se fait en public.',
    },
    {
      id: 'forcer',
      niv: 'p',
      s: 'Pendant une élection, on a le droit de forcer un camarade à voter pour soi.',
      v: false,
      e: 'Chacun doit voter librement.',
    },
  ],
  paires: [
    {
      id: 'actions',
      niv: 'f',
      prompt: 'Associe chaque action à ce qu’elle défend.',
      relation: 'action → valeur',
      pairs: [
        ['ramasser les déchets dans un parc', 'l’environnement'],
        ['aider un camarade en difficulté', 'la solidarité'],
        ['voter pour les délégués', 'la démocratie'],
        ['collecter des jouets pour les enfants démunis', 'l’entraide'],
      ],
      e: 'S’engager, c’est agir pour des valeurs.',
    },
  ],
  etapes: [
    {
      id: 'election',
      niv: 'n',
      prompt: 'Remets dans l’ordre l’élection des délégués de classe.',
      els: [
        'Les candidats se présentent.',
        'Ils expliquent leurs idées à la classe.',
        'Chaque élève vote en secret.',
        'On compte les bulletins : c’est le dépouillement.',
        'On annonce les délégués élus.',
      ],
      e: 'Candidature, campagne, vote secret, dépouillement, résultats : c’est une élection démocratique.',
    },
  ],
};

export const EMC: Fiche[] = [VALEURS, INSTITUTIONS, DROITS, HARCELEMENT, NUMERIQUE, ENGAGEMENT];
