/**
 * Géographie CM2 — programme 2020 (thèmes « Se déplacer », « Communiquer grâce à l'Internet »,
 * « Mieux habiter », repères cartographiques) et programme 2026 (BO n°22 du 28/05/2026 : organisation du
 * territoire, eau douce, Union européenne). Les cartes utilisent les identifiants EXACTS de
 * `src/games/_cartes/IDS.md` (vérifiés par les tests avec `IDS_CARTES`).
 */
import type { Fiche, Lieu, Niv, Paires, Qcm } from './outils';

/* ------------------------------------------------------------------ */
/* Données de repère                                                   */
/* ------------------------------------------------------------------ */

/** [id carte, nom avec article, capitale régionale, niveau, explication] — découpage de 2016. */
export const REGIONS: [string, string, string, Niv, string][] = [
  [
    'hauts-de-france',
    'les Hauts-de-France',
    'Lille',
    'n',
    'Les Hauts-de-France sont tout au nord, à la frontière avec la Belgique.',
  ],
  ['normandie', 'la Normandie', 'Rouen', 'n', 'La Normandie est au nord-ouest, au bord de la Manche.'],
  [
    'ile-de-france',
    'l’Île-de-France',
    'Paris',
    'f',
    'L’Île-de-France est la région de Paris, la capitale, dans le nord de la France.',
  ],
  [
    'grand-est',
    'le Grand Est',
    'Strasbourg',
    'n',
    'Le Grand Est est au nord-est, à la frontière avec l’Allemagne.',
  ],
  [
    'bretagne',
    'la Bretagne',
    'Rennes',
    'f',
    'La Bretagne est tout à l’ouest, entourée par la mer sur trois côtés.',
  ],
  [
    'pays-de-la-loire',
    'les Pays de la Loire',
    'Nantes',
    'n',
    'Les Pays de la Loire sont à l’ouest, au bord de l’océan Atlantique, là où se jette la Loire.',
  ],
  [
    'centre-val-de-loire',
    'le Centre-Val de Loire',
    'Orléans',
    'n',
    'Le Centre-Val de Loire est au centre de la France, traversé par la Loire.',
  ],
  [
    'bourgogne-franche-comte',
    'la Bourgogne-Franche-Comté',
    'Dijon',
    'n',
    'La Bourgogne-Franche-Comté est à l’est, à la frontière avec la Suisse.',
  ],
  [
    'nouvelle-aquitaine',
    'la Nouvelle-Aquitaine',
    'Bordeaux',
    'n',
    'La Nouvelle-Aquitaine est au sud-ouest : c’est la plus grande région de France métropolitaine.',
  ],
  [
    'auvergne-rhone-alpes',
    'l’Auvergne-Rhône-Alpes',
    'Lyon',
    'n',
    'L’Auvergne-Rhône-Alpes est au centre-est, avec le Massif central et les Alpes.',
  ],
  [
    'occitanie',
    'l’Occitanie',
    'Toulouse',
    'n',
    'L’Occitanie est au sud, entre les Pyrénées et la mer Méditerranée.',
  ],
  [
    'provence-alpes-cote-d-azur',
    'la Provence-Alpes-Côte d’Azur',
    'Marseille',
    'n',
    'La Provence-Alpes-Côte d’Azur est au sud-est, au bord de la mer Méditerranée.',
  ],
  [
    'corse',
    'la Corse',
    'Ajaccio',
    'f',
    'La Corse est une île de la mer Méditerranée, au sud-est de la France.',
  ],
  [
    'guadeloupe',
    'la Guadeloupe',
    'Basse-Terre',
    'n',
    'La Guadeloupe est un archipel des Antilles, dans la mer des Caraïbes.',
  ],
  [
    'martinique',
    'la Martinique',
    'Fort-de-France',
    'n',
    'La Martinique est une île des Antilles, dans la mer des Caraïbes.',
  ],
  [
    'guyane',
    'la Guyane',
    'Cayenne',
    'n',
    'La Guyane est en Amérique du Sud, couverte par la forêt amazonienne.',
  ],
  ['la-reunion', 'La Réunion', 'Saint-Denis', 'n', 'La Réunion est une île de l’océan Indien.'],
  [
    'mayotte',
    'Mayotte',
    'Mamoudzou',
    'p',
    'Mayotte est une île de l’océan Indien, entre l’Afrique et Madagascar.',
  ],
];

/** [id carte, nom avec article, capitale, niveau, fondateur, explication] — pays de l'Union européenne. */
export const PAYS_UE: [string, string, string, Niv, boolean, string][] = [
  [
    'allemagne',
    'l’Allemagne',
    'Berlin',
    'f',
    true,
    'L’Allemagne est à l’est de la France ; sa capitale est Berlin.',
  ],
  [
    'autriche',
    'l’Autriche',
    'Vienne',
    'p',
    false,
    'L’Autriche est au centre de l’Europe, à l’est de la Suisse ; sa capitale est Vienne.',
  ],
  [
    'belgique',
    'la Belgique',
    'Bruxelles',
    'n',
    true,
    'La Belgique est au nord de la France ; sa capitale est Bruxelles.',
  ],
  [
    'bulgarie',
    'la Bulgarie',
    'Sofia',
    'p',
    false,
    'La Bulgarie est au sud-est de l’Europe, au bord de la mer Noire ; sa capitale est Sofia.',
  ],
  [
    'chypre',
    'Chypre',
    'Nicosie',
    'p',
    false,
    'Chypre est une île de l’est de la mer Méditerranée ; sa capitale est Nicosie.',
  ],
  [
    'croatie',
    'la Croatie',
    'Zagreb',
    'p',
    false,
    'La Croatie borde la mer Adriatique, à l’est de l’Italie ; sa capitale est Zagreb.',
  ],
  [
    'danemark',
    'le Danemark',
    'Copenhague',
    'n',
    false,
    'Le Danemark est au nord de l’Allemagne ; sa capitale est Copenhague.',
  ],
  [
    'espagne',
    'l’Espagne',
    'Madrid',
    'f',
    false,
    'L’Espagne est au sud-ouest de la France, de l’autre côté des Pyrénées ; sa capitale est Madrid.',
  ],
  [
    'estonie',
    'l’Estonie',
    'Tallinn',
    'p',
    false,
    'L’Estonie est au nord-est de l’Europe, au bord de la mer Baltique ; sa capitale est Tallinn.',
  ],
  [
    'finlande',
    'la Finlande',
    'Helsinki',
    'p',
    false,
    'La Finlande est tout au nord-est de l’Europe ; sa capitale est Helsinki.',
  ],
  ['france', 'la France', 'Paris', 'f', true, 'La France est à l’ouest de l’Europe ; sa capitale est Paris.'],
  [
    'grece',
    'la Grèce',
    'Athènes',
    'n',
    false,
    'La Grèce est au sud-est de l’Europe, au bord de la Méditerranée ; sa capitale est Athènes.',
  ],
  [
    'hongrie',
    'la Hongrie',
    'Budapest',
    'p',
    false,
    'La Hongrie est au centre de l’Europe, traversée par le Danube ; sa capitale est Budapest.',
  ],
  [
    'irlande',
    'l’Irlande',
    'Dublin',
    'n',
    false,
    'L’Irlande est une île à l’ouest de la Grande-Bretagne ; sa capitale est Dublin.',
  ],
  [
    'italie',
    'l’Italie',
    'Rome',
    'f',
    true,
    'L’Italie a la forme d’une botte, au sud-est de la France ; sa capitale est Rome.',
  ],
  [
    'lettonie',
    'la Lettonie',
    'Riga',
    'p',
    false,
    'La Lettonie borde la mer Baltique, entre l’Estonie et la Lituanie ; sa capitale est Riga.',
  ],
  [
    'lituanie',
    'la Lituanie',
    'Vilnius',
    'p',
    false,
    'La Lituanie borde la mer Baltique, au nord de la Pologne ; sa capitale est Vilnius.',
  ],
  [
    'luxembourg',
    'le Luxembourg',
    'Luxembourg',
    'n',
    true,
    'Le Luxembourg est un tout petit pays entre la France, la Belgique et l’Allemagne ; sa capitale porte le même nom.',
  ],
  [
    'malte',
    'Malte',
    'La Valette',
    'p',
    false,
    'Malte est une petite île de la Méditerranée, au sud de l’Italie ; sa capitale est La Valette.',
  ],
  [
    'pays-bas',
    'les Pays-Bas',
    'Amsterdam',
    'n',
    true,
    'Les Pays-Bas sont au nord de la Belgique, au bord de la mer du Nord ; leur capitale est Amsterdam.',
  ],
  [
    'pologne',
    'la Pologne',
    'Varsovie',
    'n',
    false,
    'La Pologne est à l’est de l’Allemagne ; sa capitale est Varsovie.',
  ],
  [
    'portugal',
    'le Portugal',
    'Lisbonne',
    'n',
    false,
    'Le Portugal est à l’ouest de l’Espagne, au bord de l’océan Atlantique ; sa capitale est Lisbonne.',
  ],
  [
    'republique-tcheque',
    'la Tchéquie',
    'Prague',
    'p',
    false,
    'La Tchéquie (République tchèque) est à l’est de l’Allemagne ; sa capitale est Prague.',
  ],
  [
    'roumanie',
    'la Roumanie',
    'Bucarest',
    'p',
    false,
    'La Roumanie est au sud-est de l’Europe, au bord de la mer Noire ; sa capitale est Bucarest.',
  ],
  [
    'slovaquie',
    'la Slovaquie',
    'Bratislava',
    'p',
    false,
    'La Slovaquie est au centre de l’Europe, au nord de la Hongrie ; sa capitale est Bratislava.',
  ],
  [
    'slovenie',
    'la Slovénie',
    'Ljubljana',
    'p',
    false,
    'La Slovénie est un petit pays entre l’Italie, l’Autriche et la Croatie ; sa capitale est Ljubljana.',
  ],
  [
    'suede',
    'la Suède',
    'Stockholm',
    'n',
    false,
    'La Suède est au nord de l’Europe, en Scandinavie ; sa capitale est Stockholm.',
  ],
];

/** [id, nom avec article, niveau, explication] */
const FLEUVES: [string, string, Niv, string][] = [
  ['seine', 'la Seine', 'f', 'La Seine traverse Paris et se jette dans la Manche, au Havre.'],
  [
    'loire',
    'la Loire',
    'f',
    'La Loire est le plus long fleuve de France ; elle se jette dans l’océan Atlantique.',
  ],
  [
    'garonne',
    'la Garonne',
    'n',
    'La Garonne naît dans les Pyrénées, passe à Toulouse et à Bordeaux et rejoint l’Atlantique.',
  ],
  [
    'rhone',
    'le Rhône',
    'n',
    'Le Rhône vient de Suisse, traverse le lac Léman, passe à Lyon et se jette dans la Méditerranée.',
  ],
  [
    'rhin',
    'le Rhin',
    'n',
    'Le Rhin marque la frontière avec l’Allemagne, passe près de Strasbourg et se jette dans la mer du Nord.',
  ],
];

const MASSIFS: [string, string, Niv, string][] = [
  [
    'alpes',
    'les Alpes',
    'f',
    'Les Alpes sont à l’est, à la frontière avec l’Italie et la Suisse ; le mont Blanc s’y trouve.',
  ],
  ['pyrenees', 'les Pyrénées', 'f', 'Les Pyrénées sont au sud-ouest, à la frontière avec l’Espagne.'],
  [
    'massif-central',
    'le Massif central',
    'n',
    'Le Massif central est au centre de la France ; on y trouve d’anciens volcans.',
  ],
  ['jura', 'le Jura', 'n', 'Le Jura est à l’est, le long de la frontière avec la Suisse.'],
  ['vosges', 'les Vosges', 'n', 'Les Vosges sont au nord-est, en Alsace et en Lorraine.'],
  ['massif-corse', 'le massif corse', 'n', 'Le massif corse occupe presque toute l’île de Corse.'],
];

const MONDE: [string, string, Niv, string][] = [
  ['europe', 'l’Europe', 'f', 'L’Europe est le continent où se trouve la France.'],
  ['afrique', 'l’Afrique', 'f', 'L’Afrique est au sud de l’Europe, de l’autre côté de la mer Méditerranée.'],
  ['asie', 'l’Asie', 'f', 'L’Asie est le plus grand continent ; elle est à l’est de l’Europe.'],
  [
    'amerique',
    'l’Amérique',
    'f',
    'L’Amérique est à l’ouest de l’océan Atlantique ; elle a deux parties, au nord et au sud.',
  ],
  [
    'oceanie',
    'l’Océanie',
    'n',
    'L’Océanie, avec l’Australie, est entre l’océan Indien et l’océan Pacifique.',
  ],
  ['antarctique', 'l’Antarctique', 'n', 'L’Antarctique est le continent glacé du pôle Sud.'],
  [
    'ocean-atlantique',
    'l’océan Atlantique',
    'f',
    'L’océan Atlantique sépare l’Europe et l’Afrique de l’Amérique.',
  ],
  [
    'ocean-pacifique',
    'l’océan Pacifique',
    'f',
    'Le Pacifique est le plus grand océan : il est entre l’Amérique, l’Asie et l’Océanie.',
  ],
  ['ocean-indien', 'l’océan Indien', 'n', 'L’océan Indien est entre l’Afrique, l’Asie et l’Océanie.'],
  ['ocean-arctique', 'l’océan Arctique', 'n', 'L’océan Arctique est autour du pôle Nord.'],
  ['ocean-austral', 'l’océan Austral', 'p', 'L’océan Austral entoure l’Antarctique, autour du pôle Sud.'],
];

/** « la Bretagne » → « de la Bretagne » ; « les Hauts-de-France » → « des Hauts-de-France ». */
export function de(label: string): string {
  if (label.startsWith('les ')) return `des ${label.slice(4)}`;
  if (label.startsWith('le ')) return `du ${label.slice(3)}`;
  return `de ${label}`;
}

const majuscule = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/** Lieux « touche… » à partir d'une liste [id, label, niv, explication]. */
const lieux = (map: Lieu['map'], l: [string, string, Niv, string][], prefixe: string): Lieu[] =>
  l.map(([target, label, niv, e]) => ({ id: `${prefixe}-${target}`, niv, map, target, label, e }));

/** Régions : par leur nom ; en Plus loin, par leur capitale. */
const lieuxRegions = (niveauNom: (n: Niv) => Niv = (n) => n): Lieu[] =>
  REGIONS.flatMap(([target, label, cap, niv, e]) => [
    { id: `reg-${target}`, niv: niveauNom(niv), map: 'france-regions' as const, target, label, e },
    {
      id: `cap-${target}`,
      niv: 'p' as const,
      map: 'france-regions' as const,
      target,
      label,
      prompt: `Touche la région dont la capitale est ${cap}.`,
      e: `${cap} est la capitale ${de(label)}. ${e}`,
    },
  ]);

const lieuxPays = (filtre: (p: (typeof PAYS_UE)[number]) => boolean, niveau?: Niv): Lieu[] =>
  PAYS_UE.filter(filtre).flatMap(([target, label, cap, niv, , e]) => [
    { id: `pays-${target}`, niv: niveau ?? niv, map: 'europe' as const, target, label, e },
    {
      id: `cap-${target}`,
      niv: 'p' as const,
      map: 'europe' as const,
      target,
      label,
      prompt: `Touche le pays dont la capitale est ${cap}.`,
      e,
    },
  ]);

/** Autres capitales tirées de la liste (distracteurs). */
function autres(capitales: string[], bonne: string, i: number): string[] {
  const reste = capitales.filter((c) => c !== bonne);
  return [0, 3, 7, 11].map((k) => reste[(i + k) % reste.length]!).filter((c, j, a) => a.indexOf(c) === j);
}

const qcmCapitalesRegions = (): Qcm[] => {
  const caps = REGIONS.map((r) => r[2]);
  return REGIONS.map(([id, label, cap, niv, e], i) => ({
    id: `capitale-${id}`,
    niv: niv === 'f' ? 'f' : niv === 'n' && i < 13 ? 'n' : 'p',
    q: `Quelle est la capitale régionale ${de(label)} ?`,
    r: cap,
    f: autres(caps, cap, i),
    e: `${cap} est la capitale ${de(label)}. ${e}`,
  }));
};

const qcmCapitalesPays = (): Qcm[] => {
  const caps = PAYS_UE.map((p) => p[2]);
  return PAYS_UE.map(([id, label, cap, niv, , e], i) => ({
    id: `capitale-${id}`,
    niv,
    q: `Quelle est la capitale ${de(label)} ?`,
    r: cap,
    f: autres(caps, cap, i),
    e,
  }));
};

/** Paires région ↔ capitale par groupes de 5. */
const pairesRegions = (): Paires[] => {
  const groupes: [Niv, number[]][] = [
    ['f', [2, 4, 12, 9, 11]],
    ['n', [0, 1, 3, 5, 6]],
    ['n', [7, 8, 10, 2, 4]],
    ['p', [13, 14, 15, 16, 17]],
  ];
  return groupes.map(([niv, idx], k) => ({
    id: `regions-${k + 1}`,
    niv,
    prompt: 'Associe chaque région à sa capitale régionale.',
    relation: 'région → capitale',
    pairs: idx.map((i) => [majuscule(REGIONS[i]![1]), REGIONS[i]![2]] as [string, string]),
    e: idx.map((i) => `${REGIONS[i]![2]} est la capitale ${de(REGIONS[i]![1])}`).join(' ; ') + '.',
  }));
};

const pairesPays = (): Paires[] => {
  const groupes: [Niv, string[]][] = [
    ['f', ['france', 'allemagne', 'italie', 'espagne']],
    ['n', ['belgique', 'pays-bas', 'luxembourg', 'portugal', 'grece']],
    ['n', ['pologne', 'suede', 'danemark', 'irlande', 'italie']],
    ['p', ['autriche', 'hongrie', 'republique-tcheque', 'roumanie', 'finlande']],
    ['p', ['croatie', 'bulgarie', 'slovaquie', 'slovenie', 'lituanie']],
  ];
  return groupes.map(([niv, ids], k) => {
    const pays = ids.map((id) => PAYS_UE.find((p) => p[0] === id)!);
    return {
      id: `pays-${k + 1}`,
      niv,
      prompt: 'Associe chaque pays à sa capitale.',
      relation: 'pays → capitale',
      pairs: pays.map((p) => [majuscule(p[1]), p[2]] as [string, string]),
      e: pays.map((p) => `${p[2]} est la capitale ${de(p[1])}`).join(' ; ') + '.',
    };
  });
};

/* ------------------------------------------------------------------ */
/* Repères cartographiques (transversal)                               */
/* ------------------------------------------------------------------ */

const REPERES: Fiche = {
  lecon: 'CM2.GE.REPERES',
  lieux: [
    ...lieuxRegions(),
    ...lieux('france-fleuves', FLEUVES, 'fleuve'),
    ...lieux('france-massifs', MASSIFS, 'massif'),
    ...lieux('monde', MONDE, 'monde'),
    ...lieuxPays(() => true),
    {
      id: 'fleuve-paris',
      niv: 'p',
      map: 'france-fleuves',
      target: 'seine',
      label: 'la Seine',
      prompt: 'Touche le fleuve qui traverse Paris.',
      e: 'La Seine traverse Paris avant de se jeter dans la Manche.',
    },
    {
      id: 'fleuve-bordeaux',
      niv: 'p',
      map: 'france-fleuves',
      target: 'garonne',
      label: 'la Garonne',
      prompt: 'Touche le fleuve qui passe à Toulouse et à Bordeaux.',
      e: 'La Garonne passe à Toulouse puis à Bordeaux.',
    },
    {
      id: 'massif-mont-blanc',
      niv: 'p',
      map: 'france-massifs',
      target: 'alpes',
      label: 'les Alpes',
      prompt: 'Touche le massif où se trouve le mont Blanc, le plus haut sommet de France.',
      e: 'Le mont Blanc se trouve dans les Alpes.',
    },
  ],
  qcm: [
    ...qcmCapitalesRegions(),
    ...qcmCapitalesPays().filter((q) => q.niv !== 'f' || ['france', 'italie'].some((p) => q.id.endsWith(p))),
    {
      id: 'loire',
      niv: 'f',
      q: 'Quel est le plus long fleuve de France ?',
      r: 'La Loire',
      f: ['La Seine', 'La Garonne', 'Le Rhin'],
      e: 'La Loire est le plus long fleuve de France : elle traverse le pays d’est en ouest.',
    },
    {
      id: 'seine',
      niv: 'f',
      q: 'Quel fleuve traverse Paris ?',
      r: 'La Seine',
      f: ['Le Rhône', 'La Loire', 'La Garonne'],
      e: 'La Seine traverse Paris puis se jette dans la Manche.',
    },
    {
      id: 'rhone',
      niv: 'n',
      q: 'Quel fleuve passe à Lyon et se jette dans la mer Méditerranée ?',
      r: 'Le Rhône',
      f: ['La Seine', 'Le Rhin', 'La Loire'],
      e: 'Le Rhône passe à Lyon et se jette dans la Méditerranée par la Camargue.',
    },
    {
      id: 'rhin',
      niv: 'n',
      q: 'Quel fleuve forme une frontière avec l’Allemagne ?',
      r: 'Le Rhin',
      f: ['La Garonne', 'La Seine', 'La Loire'],
      e: 'Le Rhin sépare l’Alsace de l’Allemagne.',
    },
    {
      id: 'mont-blanc',
      niv: 'n',
      q: 'Dans quel massif se trouve le mont Blanc, le plus haut sommet de France ?',
      r: 'Les Alpes',
      f: ['Les Pyrénées', 'Le Massif central', 'Les Vosges'],
      e: 'Le mont Blanc (environ 4 800 m) se trouve dans les Alpes.',
    },
    {
      id: 'pyrenees',
      niv: 'f',
      q: 'Quelle chaîne de montagnes sépare la France de l’Espagne ?',
      r: 'Les Pyrénées',
      f: ['Les Alpes', 'Le Jura', 'Les Vosges'],
      e: 'Les Pyrénées forment la frontière avec l’Espagne.',
    },
    {
      id: 'volcans',
      niv: 'n',
      q: 'Dans quel massif trouve-t-on d’anciens volcans, comme le puy de Dôme ?',
      r: 'Le Massif central',
      f: ['Les Alpes', 'Le Jura', 'Les Vosges'],
      e: 'Le Massif central contient la chaîne des Puys, d’anciens volcans.',
    },
    {
      id: 'pacifique',
      niv: 'f',
      q: 'Quel est le plus grand océan du monde ?',
      r: 'L’océan Pacifique',
      f: ['L’océan Atlantique', 'L’océan Indien', 'L’océan Arctique'],
      e: 'Le Pacifique est le plus grand océan : il couvre presque un tiers de la Terre.',
    },
    {
      id: 'continent-france',
      niv: 'f',
      q: 'Sur quel continent se trouve la France métropolitaine ?',
      r: 'L’Europe',
      f: ['L’Afrique', 'L’Asie', 'L’Amérique'],
      e: 'La France métropolitaine est en Europe ; certaines régions d’outre-mer sont sur d’autres continents.',
    },
    {
      id: 'nb-regions',
      niv: 'n',
      q: 'Combien la France compte-t-elle de régions en tout, outre-mer compris ?',
      r: '18',
      f: ['22', '27', '101'],
      e: 'La France compte 18 régions : 13 en métropole et 5 en outre-mer.',
    },
    {
      id: 'qui-loire',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'La Loire',
      f: ['La Seine', 'Le Rhône', 'La Garonne'],
      hints: [
        'Je suis un fleuve.',
        'Je prends ma source au mont Gerbier-de-Jonc, dans le Massif central.',
        'De nombreux châteaux sont construits sur mes rives.',
        'Je passe à Orléans, à Tours et à Nantes.',
        'Je suis le plus long fleuve de France.',
      ],
      img: '🏞️',
      e: 'La Loire est le plus long fleuve de France ; elle se jette dans l’Atlantique.',
    },
    {
      id: 'qui-corse',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'La Corse',
      f: ['La Bretagne', 'La Réunion', 'La Martinique'],
      hints: [
        'Je suis une région française.',
        'On me surnomme « l’île de Beauté ».',
        'Napoléon Bonaparte est né chez moi, à Ajaccio.',
        'Je suis une île de la mer Méditerranée.',
      ],
      img: '🏝️',
      e: 'La Corse est une île de la Méditerranée ; sa capitale est Ajaccio.',
    },
  ],
  vf: [
    {
      id: 'loire',
      niv: 'f',
      s: 'La Loire est le plus long fleuve de France.',
      v: true,
      e: 'Elle mesure environ 1 000 km.',
    },
    {
      id: 'seine-marseille',
      niv: 'f',
      s: 'La Seine traverse Marseille.',
      v: false,
      e: 'La Seine traverse Paris ; Marseille est au bord de la Méditerranée.',
    },
    {
      id: 'alpes',
      niv: 'f',
      s: 'Le mont Blanc se trouve dans les Alpes.',
      v: true,
      e: 'C’est le plus haut sommet de France.',
    },
    {
      id: 'pyrenees',
      niv: 'f',
      s: 'Les Pyrénées sont à la frontière avec l’Italie.',
      v: false,
      e: 'Les Pyrénées sont à la frontière avec l’Espagne ; les Alpes, avec l’Italie.',
    },
    { id: 'afrique', niv: 'f', s: 'L’Afrique est un océan.', v: false, e: 'L’Afrique est un continent.' },
    {
      id: 'pacifique',
      niv: 'f',
      s: 'Le Pacifique est le plus grand océan du monde.',
      v: true,
      e: 'Il est entre l’Amérique, l’Asie et l’Océanie.',
    },
    {
      id: 'rennes',
      niv: 'n',
      s: 'Rennes est la capitale de la Bretagne.',
      v: true,
      e: 'Rennes est la capitale régionale de la Bretagne.',
    },
    {
      id: 'lyon',
      niv: 'n',
      s: 'Lyon est la capitale de l’Occitanie.',
      v: false,
      e: 'Lyon est la capitale de l’Auvergne-Rhône-Alpes ; Toulouse est celle de l’Occitanie.',
    },
    {
      id: 'regions',
      niv: 'n',
      s: 'La France compte 18 régions, dont 5 en outre-mer.',
      v: true,
      e: '13 régions en métropole et 5 en outre-mer.',
    },
    {
      id: 'rhone',
      niv: 'n',
      s: 'Le Rhône se jette dans la mer Méditerranée.',
      v: true,
      e: 'Il se jette dans la Méditerranée par la Camargue.',
    },
    {
      id: 'madrid',
      niv: 'n',
      s: 'Madrid est la capitale du Portugal.',
      v: false,
      e: 'Madrid est la capitale de l’Espagne ; Lisbonne est celle du Portugal.',
    },
    {
      id: 'vosges',
      niv: 'n',
      s: 'Les Vosges sont un massif du sud-ouest de la France.',
      v: false,
      e: 'Les Vosges sont au nord-est de la France.',
    },
    {
      id: 'reunion',
      niv: 'p',
      s: 'La Réunion est une île de l’océan Indien.',
      v: true,
      e: 'C’est une région d’outre-mer.',
    },
    {
      id: 'rhin',
      niv: 'p',
      s: 'Le Rhin se jette dans la mer Méditerranée.',
      v: false,
      e: 'Le Rhin se jette dans la mer du Nord, aux Pays-Bas.',
    },
    {
      id: 'antarctique',
      niv: 'p',
      s: 'L’Antarctique est le continent du pôle Sud.',
      v: true,
      e: 'C’est un continent recouvert de glace.',
    },
    {
      id: 'guyane',
      niv: 'p',
      s: 'La Guyane est une région française d’Amérique du Sud.',
      v: true,
      e: 'Elle est couverte par la forêt amazonienne.',
    },
  ],
  paires: [...pairesRegions(), ...pairesPays()],
};

/* ------------------------------------------------------------------ */
/* Programme 2020                                                      */
/* ------------------------------------------------------------------ */

const DEPLACER: Fiche = {
  lecon: 'CM2.GE20.T1.DEPLACER',
  lieux: [
    {
      id: 'atlantique',
      niv: 'f',
      map: 'monde',
      target: 'ocean-atlantique',
      label: 'l’océan Atlantique',
      prompt: 'Touche l’océan que traversent les avions qui vont de Paris à New York.',
      e: 'Pour aller de Paris à New York, l’avion traverse l’océan Atlantique en 8 heures environ.',
    },
    {
      id: 'amerique-nord',
      niv: 'f',
      map: 'monde',
      target: 'amerique-du-nord',
      label: 'l’Amérique du Nord',
      prompt: 'Touche le continent où se trouve New York.',
      e: 'New York est aux États-Unis, en Amérique du Nord.',
    },
    {
      id: 'royaume-uni',
      niv: 'n',
      map: 'europe',
      target: 'royaume-uni',
      label: 'le Royaume-Uni',
      prompt: 'Touche le pays relié à la France par le tunnel sous la Manche.',
      e: 'Le tunnel sous la Manche relie la France au Royaume-Uni depuis 1994.',
    },
    {
      id: 'italie',
      niv: 'p',
      map: 'europe',
      target: 'italie',
      label: 'l’Italie',
      prompt: 'Touche le pays où l’on arrive en sortant du tunnel du Mont-Blanc.',
      e: 'Le tunnel du Mont-Blanc relie Chamonix, en France, à l’Italie.',
    },
    {
      id: 'lyon',
      niv: 'n',
      map: 'france-regions',
      target: 'auvergne-rhone-alpes',
      label: 'l’Auvergne-Rhône-Alpes',
      prompt: 'Touche la région de Lyon, reliée à Paris par la première ligne TGV en 1981.',
      e: 'La première ligne à grande vitesse relie Paris à Lyon depuis 1981.',
    },
    {
      id: 'roissy',
      niv: 'n',
      map: 'france-regions',
      target: 'ile-de-france',
      label: 'l’Île-de-France',
      prompt: 'Touche la région où se trouve l’aéroport de Roissy-Charles-de-Gaulle.',
      e: 'Roissy-Charles-de-Gaulle, le plus grand aéroport de France, est en Île-de-France.',
    },
  ],
  qcm: [
    {
      id: 'tgv',
      niv: 'f',
      q: 'Quel train peut rouler à plus de 300 km/h sur des lignes spéciales ?',
      r: 'Le TGV',
      f: ['Le tramway', 'Le métro', 'Le train à vapeur'],
      e: 'Le TGV (train à grande vitesse) roule sur des lignes à grande vitesse (LGV).',
    },
    {
      id: 'lgv',
      niv: 'n',
      q: 'En 1981, la première ligne à grande vitesse relie Paris à…',
      r: 'Lyon',
      f: ['Brest', 'Lille', 'Bordeaux'],
      e: 'La LGV Paris-Lyon est la première ligne à grande vitesse de France (1981).',
    },
    {
      id: 'aeroport',
      niv: 'n',
      q: 'Quel est le plus grand aéroport de France ?',
      r: 'Paris-Charles-de-Gaulle (Roissy)',
      f: ['Lyon-Saint-Exupéry', 'Nice-Côte d’Azur', 'Toulouse-Blagnac'],
      e: 'L’aéroport de Roissy-Charles-de-Gaulle, près de Paris, accueille des avions du monde entier.',
    },
    {
      id: 'tunnel',
      niv: 'n',
      q: 'Quel tunnel relie la France au Royaume-Uni sous la mer ?',
      r: 'Le tunnel sous la Manche',
      f: ['Le tunnel du Mont-Blanc', 'Le tunnel du Fréjus', 'Le métro de Londres'],
      e: 'Le tunnel sous la Manche, ouvert en 1994, permet d’aller de Calais à Folkestone en train.',
    },
    {
      id: 'new-york',
      niv: 'f',
      q: 'Quel moyen de transport est le plus rapide pour aller de Paris à New York ?',
      r: 'L’avion',
      f: ['Le bateau', 'Le train', 'La voiture'],
      e: 'Il faut environ 8 heures d’avion, mais plusieurs jours de bateau.',
    },
    {
      id: 'doux',
      niv: 'n',
      q: 'Qu’appelle-t-on un « mode de déplacement doux » ?',
      r: 'Un déplacement sans moteur, comme la marche ou le vélo',
      f: [
        'Un déplacement en avion',
        'Un déplacement très lent en voiture',
        'Un déplacement en bateau à moteur',
      ],
      e: 'La marche et le vélo ne polluent pas : ce sont des modes de déplacement doux.',
    },
    {
      id: 'pollution',
      niv: 'f',
      q: 'Quel moyen de transport pollue le moins ?',
      r: 'Le vélo',
      f: ['La voiture', 'L’avion', 'Le camion'],
      e: 'Le vélo n’a pas de moteur : il ne rejette pas de gaz polluant.',
    },
    {
      id: 'bouchons',
      niv: 'n',
      q: 'Pourquoi y a-t-il des embouteillages le matin et le soir autour des grandes villes ?',
      r: 'Beaucoup de personnes vont au travail ou en reviennent en même temps.',
      f: [
        'Les routes sont fermées la journée.',
        'Les voitures roulent mieux la nuit.',
        'Il n’y a pas de trains.',
      ],
      e: 'Les trajets entre la maison et le travail se font souvent aux mêmes heures.',
    },
    {
      id: 'mesure',
      niv: 'p',
      q: 'On peut mesurer un trajet en kilomètres, mais aussi…',
      r: 'en temps de trajet (minutes, heures)',
      f: ['en kilogrammes', 'en litres', 'en degrés'],
      e: 'Une distance peut se dire en kilomètres ou en temps : « l’école est à 10 minutes à pied ».',
    },
    {
      id: 'pendulaire',
      niv: 'p',
      q: 'Comment appelle-t-on l’aller-retour quotidien entre la maison et le travail ?',
      r: 'Un déplacement pendulaire',
      f: ['Un voyage touristique', 'Une migration', 'Une croisière'],
      e: 'Comme le balancier d’une pendule, on fait l’aller et le retour chaque jour.',
    },
    {
      id: 'qui-tgv',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le TGV',
      f: ['Le métro', 'Le tramway', 'L’avion'],
      hints: [
        'Je roule sur des rails.',
        'Je suis né en France en 1981.',
        'Je relie les grandes villes en quelques heures.',
        'Je peux rouler à plus de 300 km/h.',
      ],
      img: '🚄',
      e: 'Le TGV est un train à grande vitesse ; il roule sur des lignes spéciales (LGV).',
    },
  ],
  vf: [
    {
      id: 'tgv',
      niv: 'f',
      s: 'Le TGV roule sur des lignes à grande vitesse.',
      v: true,
      e: 'On les appelle les LGV.',
    },
    {
      id: 'atlantique',
      niv: 'f',
      s: 'Pour traverser l’océan Atlantique, on prend souvent l’avion.',
      v: true,
      e: 'C’est le moyen le plus rapide.',
    },
    {
      id: 'velo',
      niv: 'f',
      s: 'La marche et le vélo sont des déplacements qui polluent beaucoup.',
      v: false,
      e: 'Ils ne polluent pas : ce sont des modes de déplacement doux.',
    },
    {
      id: 'aeroport',
      niv: 'f',
      s: 'Un aéroport accueille des bateaux.',
      v: false,
      e: 'Un aéroport accueille des avions ; un port accueille des bateaux.',
    },
    { id: 'gare', niv: 'f', s: 'Une gare accueille des trains.', v: true, e: 'On prend le train à la gare.' },
    {
      id: 'manche',
      niv: 'n',
      s: 'Le tunnel sous la Manche relie la France au Royaume-Uni.',
      v: true,
      e: 'Il est ouvert depuis 1994.',
    },
    {
      id: 'commun',
      niv: 'n',
      s: 'En ville, le tramway et le métro sont des transports en commun.',
      v: true,
      e: 'Ils transportent beaucoup de voyageurs ensemble.',
    },
    {
      id: 'pied',
      niv: 'n',
      s: 'Tous les trajets entre la maison et le travail se font à pied.',
      v: false,
      e: 'Beaucoup de gens prennent la voiture, le bus, le train ou le vélo.',
    },
    {
      id: 'voitures',
      niv: 'n',
      s: 'Partout dans le monde, chaque famille possède une voiture.',
      v: false,
      e: 'Dans beaucoup de pays, la plupart des gens se déplacent à pied, en bus ou à vélo.',
    },
    {
      id: '1981',
      niv: 'p',
      s: 'La première ligne de TGV, ouverte en 1981, relie Paris à Lyon.',
      v: true,
      e: 'C’est la LGV Sud-Est.',
    },
    {
      id: 'etoile',
      niv: 'p',
      s: 'Beaucoup d’autoroutes et de LGV partent de Paris, comme les branches d’une étoile.',
      v: true,
      e: 'Le réseau français est centré sur Paris.',
    },
    {
      id: 'avion-train',
      niv: 'p',
      s: 'Pour un même trajet, l’avion pollue moins que le train.',
      v: false,
      e: 'L’avion rejette beaucoup plus de gaz à effet de serre que le train.',
    },
  ],
  paires: [
    {
      id: 'infrastructures',
      niv: 'f',
      prompt: 'Associe chaque moyen de transport au lieu où on le prend.',
      relation: 'transport → infrastructure',
      pairs: [
        ['l’avion', 'l’aéroport'],
        ['le bateau', 'le port'],
        ['le train', 'la gare'],
        ['la voiture', 'la route'],
        ['le métro', 'la station'],
        ['le vélo', 'la piste cyclable'],
      ],
      e: 'Avion → aéroport ; bateau → port ; train → gare ; voiture → route ; métro → station ; vélo → piste cyclable.',
    },
  ],
};

const INTERNET: Fiche = {
  lecon: 'CM2.GE20.T2.INTERNET',
  lieux: [
    {
      id: 'europe',
      niv: 'f',
      map: 'monde',
      target: 'europe',
      label: 'l’Europe',
      prompt: 'Touche le continent où tu vis, très bien relié à Internet.',
      e: 'L’Europe est très bien reliée à Internet.',
    },
    {
      id: 'amerique-nord',
      niv: 'f',
      map: 'monde',
      target: 'amerique-du-nord',
      label: 'l’Amérique du Nord',
      prompt: 'Touche l’Amérique du Nord, une région du monde très bien reliée à Internet.',
      e: 'Aux États-Unis et au Canada, presque tout le monde a accès à Internet.',
    },
    {
      id: 'atlantique',
      niv: 'n',
      map: 'monde',
      target: 'ocean-atlantique',
      label: 'l’océan Atlantique',
      prompt: 'Touche l’océan traversé par de nombreux câbles entre l’Europe et l’Amérique du Nord.',
      e: 'Des dizaines de câbles sous-marins traversent l’Atlantique.',
    },
    {
      id: 'afrique',
      niv: 'n',
      map: 'monde',
      target: 'afrique',
      label: 'l’Afrique',
      prompt: 'Touche le continent où la plus faible part des habitants a accès à Internet.',
      e: 'En Afrique, beaucoup d’habitants n’ont pas encore accès à Internet.',
    },
    {
      id: 'pacifique',
      niv: 'p',
      map: 'monde',
      target: 'ocean-pacifique',
      label: 'l’océan Pacifique',
      prompt: 'Touche l’océan traversé par les câbles qui relient l’Amérique à l’Asie.',
      e: 'Des câbles sous-marins traversent le Pacifique entre l’Amérique et l’Asie.',
    },
  ],
  qcm: [
    {
      id: 'cables',
      niv: 'n',
      q: 'Par où passent la plupart des données d’Internet entre les continents ?',
      r: 'Par des câbles sous-marins',
      f: ['Par des satellites seulement', 'Par des camions', 'Par la poste'],
      e: 'Presque toutes les données entre continents passent par des câbles posés au fond des océans.',
    },
    {
      id: 'internet',
      niv: 'f',
      q: 'Qu’est-ce qu’Internet ?',
      r: 'Un réseau mondial qui relie des ordinateurs',
      f: ['Un seul très gros ordinateur', 'Un jeu vidéo', 'Une chaîne de télévision'],
      e: 'Internet relie entre eux des millions d’ordinateurs, de téléphones et de serveurs du monde entier.',
    },
    {
      id: 'satellite',
      niv: 'n',
      q: 'À quoi sert un satellite de télécommunication ?',
      r: 'Il tourne autour de la Terre et transmet des informations.',
      f: [
        'Il éclaire la Terre la nuit.',
        'Il fabrique de l’électricité pour les maisons.',
        'Il mesure la température des océans seulement.',
      ],
      e: 'Les satellites relaient des communications, par exemple vers des régions isolées.',
    },
    {
      id: 'afrique',
      niv: 'n',
      q: 'Dans quelle partie du monde la part d’habitants reliés à Internet est-elle la plus faible ?',
      r: 'En Afrique',
      f: ['En Europe', 'En Amérique du Nord', 'En Asie de l’Est'],
      e: 'L’accès à Internet est inégal : en Afrique, beaucoup d’habitants ne sont pas encore connectés.',
    },
    {
      id: 'zone-blanche',
      niv: 'p',
      q: 'Qu’est-ce qu’une « zone blanche » ?',
      r: 'Un endroit où l’on ne capte pas, ou très mal, le réseau',
      f: ['Un endroit couvert de neige', 'Un quartier très bien connecté', 'Une salle d’ordinateurs'],
      e: 'Dans certaines campagnes ou montagnes, le réseau passe mal : ce sont des zones blanches.',
    },
    {
      id: 'box',
      niv: 'f',
      q: 'Quel appareil permet de se connecter à Internet depuis la maison ?',
      r: 'La box (le modem)',
      f: ['La lampe de poche', 'Le grille-pain', 'La radio à piles'],
      e: 'La box relie la maison au réseau Internet.',
    },
    {
      id: 'inegal',
      niv: 'p',
      q: 'Pourquoi certaines personnes n’ont-elles pas accès à Internet ?',
      r: 'Le réseau n’arrive pas là où elles vivent, ou c’est trop cher pour elles.',
      f: [
        'Internet est interdit aux enfants partout.',
        'Internet ne marche que le dimanche.',
        'Elles habitent trop près de la mer.',
      ],
      e: 'L’accès dépend des équipements du territoire et des moyens des habitants.',
    },
    {
      id: '5g',
      niv: 'n',
      q: 'Quelle technologie récente permet d’avoir un Internet très rapide sur un téléphone ?',
      r: 'La 5G',
      f: ['Le Minitel', 'Le télégraphe', 'La radio FM'],
      e: 'La 5G se déploie en France depuis 2020, d’abord dans les villes.',
    },
    {
      id: 'fibre',
      niv: 'p',
      q: 'Quel câble transporte Internet très vite grâce à la lumière ?',
      r: 'La fibre optique',
      f: ['Le câble d’une lampe', 'Le tuyau d’arrosage', 'La corde à linge'],
      e: 'Dans la fibre optique, les informations voyagent sous forme de lumière.',
    },
  ],
  vf: [
    {
      id: 'monde',
      niv: 'f',
      s: 'Internet relie des ordinateurs du monde entier.',
      v: true,
      e: 'C’est un réseau mondial.',
    },
    {
      id: 'tous',
      niv: 'f',
      s: 'Tout le monde sur Terre a accès à Internet.',
      v: false,
      e: 'Environ un tiers des habitants de la Terre n’y ont pas encore accès.',
    },
    {
      id: 'parler',
      niv: 'f',
      s: 'Avec Internet, on peut parler à quelqu’un qui vit à l’autre bout du monde.',
      v: true,
      e: 'Les messages traversent le monde en quelques fractions de seconde.',
    },
    {
      id: 'mail',
      niv: 'f',
      s: 'Un courriel peut arriver en quelques secondes à l’autre bout du monde.',
      v: true,
      e: 'Les informations circulent très vite dans les câbles.',
    },
    {
      id: 'moyen-age',
      niv: 'f',
      s: 'Internet a été inventé au Moyen Âge.',
      v: false,
      e: 'Internet s’est développé à la fin du XXe siècle.',
    },
    {
      id: 'cables',
      niv: 'n',
      s: 'D’un continent à l’autre, Internet passe surtout par des câbles posés au fond des océans.',
      v: true,
      e: 'Ce sont les câbles sous-marins.',
    },
    {
      id: 'sans-cable',
      niv: 'n',
      s: 'Internet fonctionne sans aucun câble.',
      v: false,
      e: 'Internet repose sur un immense réseau de câbles, et aussi sur des satellites et des antennes.',
    },
    {
      id: 'satellites',
      niv: 'n',
      s: 'Des satellites tournent autour de la Terre et transmettent des informations.',
      v: true,
      e: 'Ils aident à relier les endroits isolés.',
    },
    {
      id: 'france',
      niv: 'n',
      s: 'En France, toutes les communes ont la même qualité de connexion.',
      v: false,
      e: 'Certaines campagnes et montagnes sont moins bien couvertes que les villes.',
    },
    {
      id: 'oceans',
      niv: 'n',
      s: 'Des câbles sous-marins traversent les océans.',
      v: true,
      e: 'Ils relient les continents entre eux.',
    },
    {
      id: 'pauvres',
      niv: 'p',
      s: 'L’accès à Internet est plus difficile dans les pays pauvres.',
      v: true,
      e: 'Les équipements et les abonnements y coûtent cher.',
    },
    {
      id: 'blanche',
      niv: 'p',
      s: 'Une « zone blanche » est un endroit très bien couvert par le réseau.',
      v: false,
      e: 'C’est au contraire un endroit où le réseau ne passe pas.',
    },
    {
      id: 'fibre',
      niv: 'p',
      s: 'La fibre optique transporte les données grâce à la lumière.',
      v: true,
      e: 'C’est pour cela qu’elle est très rapide.',
    },
  ],
  paires: [
    {
      id: 'mots',
      niv: 'n',
      prompt: 'Associe chaque mot à sa définition.',
      relation: 'mot → définition',
      pairs: [
        ['un câble sous-marin', 'fil posé au fond de l’océan'],
        ['un satellite', 'engin qui tourne autour de la Terre'],
        ['une box', 'appareil qui connecte la maison'],
        ['un réseau', 'ensemble de liaisons reliées entre elles'],
        ['la fibre optique', 'câble qui transporte de la lumière'],
      ],
      e: 'Câbles, satellites, box et fibre forment le réseau Internet.',
    },
  ],
};

const HABITER: Fiche = {
  lecon: 'CM2.GE20.T3.HABITER',
  qcm: [
    {
      id: 'ecoquartier',
      niv: 'n',
      q: 'Qu’est-ce qu’un écoquartier ?',
      r: 'Un quartier construit pour respecter l’environnement',
      f: [
        'Un quartier sans habitants',
        'Un quartier réservé aux voitures',
        'Un quartier construit dans une forêt rasée',
      ],
      e: 'Un écoquartier économise l’énergie, l’eau, trie les déchets et laisse de la place à la nature.',
    },
    {
      id: 'compost',
      niv: 'f',
      q: 'Que met-on dans un composteur ?',
      r: 'Les épluchures de fruits et de légumes',
      f: ['Les piles', 'Les bouteilles en verre', 'Les sacs en plastique'],
      e: 'Les déchets de cuisine se transforment en compost, un engrais naturel.',
    },
    {
      id: 'trier',
      niv: 'f',
      q: 'Pourquoi trie-t-on ses déchets ?',
      r: 'Pour pouvoir les recycler',
      f: ['Pour remplir les poubelles plus vite', 'Pour les jeter dans la rivière', 'Pour les cacher'],
      e: 'Le tri permet de recycler le verre, le papier, les emballages… et de réduire les déchets.',
    },
    {
      id: 'piste',
      niv: 'f',
      q: 'Quel aménagement aide à se déplacer sans polluer ?',
      r: 'Une piste cyclable',
      f: ['Une autoroute', 'Un parking géant', 'Un aéroport'],
      e: 'Les pistes cyclables permettent de rouler à vélo en sécurité.',
    },
    {
      id: 'jardin',
      niv: 'n',
      q: 'À quoi sert un jardin partagé ?',
      r: 'À cultiver ensemble et à se rencontrer entre voisins',
      f: ['À garer les voitures', 'À stocker les déchets', 'À construire des immeubles'],
      e: 'Un jardin partagé crée des liens entre voisins et ramène la nature en ville.',
    },
    {
      id: 'durable',
      niv: 'p',
      q: 'Qu’est-ce que le développement durable ?',
      r: 'Répondre à nos besoins sans abîmer la planète pour ceux qui vivront après nous',
      f: [
        'Construire le plus vite possible',
        'Utiliser toutes les ressources tout de suite',
        'Arrêter de construire des maisons',
      ],
      e: 'Le développement durable pense à l’environnement, aux habitants et à l’avenir.',
    },
    {
      id: 'solaire',
      niv: 'n',
      q: 'Pourquoi installe-t-on des panneaux solaires sur les toits ?',
      r: 'Pour produire de l’électricité avec la lumière du soleil',
      f: ['Pour décorer les maisons', 'Pour empêcher la pluie de tomber', 'Pour attirer les oiseaux'],
      e: 'Le soleil est une énergie renouvelable qui ne pollue pas.',
    },
    {
      id: 'arbres',
      niv: 'n',
      q: 'Pourquoi plante-t-on des arbres et crée-t-on des parcs en ville ?',
      r: 'Pour rafraîchir l’air, accueillir les animaux et rendre la ville agréable',
      f: ['Pour cacher les voitures', 'Pour faire plus de bruit', 'Pour avoir moins de place pour jouer'],
      e: 'La nature en ville rafraîchit l’air en été et abrite la biodiversité.',
    },
    {
      id: 'dechetterie',
      niv: 'n',
      q: 'Où dépose-t-on les vieux appareils électriques et les gros déchets ?',
      r: 'À la déchetterie',
      f: ['Dans la poubelle de la cuisine', 'Dans le composteur', 'Dans la forêt'],
      e: 'À la déchetterie, les objets sont triés pour être recyclés ou traités sans polluer.',
    },
    {
      id: 'decideurs',
      niv: 'p',
      q: 'Qui décide des aménagements d’un quartier ?',
      r: 'La commune (le maire et le conseil municipal), avec les habitants',
      f: ['Un seul habitant', 'Les enfants de l’école seulement', 'Personne'],
      e: 'La commune décide, mais elle consulte souvent les habitants avant un projet.',
    },
    {
      id: 'chaleur',
      niv: 'p',
      q: 'Qu’est-ce qu’un « îlot de chaleur » en ville ?',
      r: 'Un endroit très bétonné où il fait plus chaud qu’ailleurs',
      f: ['Une île au milieu d’un lac', 'Un parc très ombragé', 'Une piscine chauffée'],
      e: 'Le béton et le goudron gardent la chaleur ; les arbres et l’eau rafraîchissent.',
    },
    {
      id: 'qui-composteur',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le composteur',
      f: ['La poubelle jaune', 'La déchetterie', 'Le recycleur de verre'],
      hints: [
        'Je suis souvent en bois.',
        'On me trouve dans les jardins ou au pied des immeubles.',
        'Les vers de terre et les petites bêtes travaillent pour moi.',
        'Je transforme les épluchures en engrais naturel.',
      ],
      img: '🌱',
      e: 'Le composteur transforme les déchets de cuisine en compost, un engrais naturel.',
    },
  ],
  vf: [
    {
      id: 'verre',
      niv: 'f',
      s: 'Le verre se recycle.',
      v: true,
      e: 'Une bouteille en verre peut redevenir une bouteille.',
    },
    {
      id: 'piles',
      niv: 'f',
      s: 'On peut mettre les piles dans le composteur avec les épluchures.',
      v: false,
      e: 'Les piles sont dangereuses : on les rapporte dans un point de collecte.',
    },
    {
      id: 'piste',
      niv: 'f',
      s: 'Une piste cyclable permet de se déplacer à vélo en sécurité.',
      v: true,
      e: 'Elle sépare les vélos des voitures.',
    },
    {
      id: 'lumiere',
      niv: 'f',
      s: 'Laisser la lumière allumée dans une pièce vide économise l’énergie.',
      v: false,
      e: 'Il faut éteindre la lumière en quittant une pièce.',
    },
    {
      id: 'ecoquartier',
      niv: 'n',
      s: 'Un écoquartier est construit sans penser à l’environnement.',
      v: false,
      e: 'Un écoquartier est justement construit pour respecter l’environnement.',
    },
    {
      id: 'arbres',
      niv: 'n',
      s: 'Les arbres en ville aident à rafraîchir l’air en été.',
      v: true,
      e: 'Leur ombre et leur eau rafraîchissent les rues.',
    },
    {
      id: 'plastique',
      niv: 'n',
      s: 'Recycler une bouteille en plastique permet de fabriquer de nouveaux objets.',
      v: true,
      e: 'Par exemple une nouvelle bouteille ou un pull en laine polaire.',
    },
    {
      id: 'jardin',
      niv: 'n',
      s: 'Un jardin partagé est cultivé par plusieurs habitants.',
      v: true,
      e: 'Les voisins jardinent ensemble.',
    },
    {
      id: 'meme-usine',
      niv: 'n',
      s: 'Tous les déchets vont dans la même usine sans être triés.',
      v: false,
      e: 'Les déchets triés vont dans un centre de tri, puis dans des usines de recyclage.',
    },
    {
      id: 'habitants',
      niv: 'p',
      s: 'Les habitants peuvent participer aux projets de leur quartier.',
      v: true,
      e: 'La commune organise souvent des réunions de concertation.',
    },
    {
      id: 'beton',
      niv: 'p',
      s: 'Le béton et le goudron rafraîchissent la ville en été.',
      v: false,
      e: 'Ils gardent la chaleur et créent des îlots de chaleur.',
    },
    {
      id: 'mer',
      niv: 'p',
      s: 'Les déchets jetés par terre finissent parfois dans les rivières et la mer.',
      v: true,
      e: 'La pluie et le vent les emportent.',
    },
  ],
  paires: [
    {
      id: 'amenagements',
      niv: 'n',
      prompt: 'Associe chaque aménagement à ce qu’il permet.',
      relation: 'aménagement → utilité',
      pairs: [
        ['la piste cyclable', 'circuler à vélo sans polluer'],
        ['le panneau solaire', 'produire de l’électricité'],
        ['le composteur', 'transformer les épluchures en engrais'],
        ['le jardin partagé', 'cultiver ensemble entre voisins'],
        ['le bac de tri', 'recycler les emballages'],
      ],
      e: 'Chacun de ces aménagements aide à mieux habiter en respectant l’environnement.',
    },
  ],
  etapes: [
    {
      id: 'recyclage',
      niv: 'n',
      prompt: 'Remets dans l’ordre le voyage d’une bouteille en plastique recyclée.',
      els: [
        'Je mets la bouteille vide dans le bac de tri.',
        'Le camion de collecte l’emporte.',
        'Au centre de tri, elle est séparée des autres déchets.',
        'À l’usine, elle est broyée et fondue.',
        'Elle devient un nouvel objet.',
      ],
      e: 'Tri à la maison, collecte, centre de tri, usine de recyclage, nouvel objet : c’est le recyclage.',
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Programme 2026                                                      */
/* ------------------------------------------------------------------ */

/** [région (index dans REGIONS), agglomération] — les cinq principales agglomérations. */
const AGGLOS: [number, string, string][] = [
  [
    2,
    'Paris',
    'Paris est de très loin la plus grande agglomération de France (plus de 10 millions d’habitants).',
  ],
  [9, 'Lyon', 'Lyon, au confluent du Rhône et de la Saône, est une des cinq principales agglomérations.'],
  [11, 'Marseille', 'Marseille, grand port de la Méditerranée, est une des cinq principales agglomérations.'],
  [0, 'Lille', 'Lille, près de la Belgique, est une des cinq principales agglomérations.'],
  [10, 'Toulouse', 'Toulouse, la « ville rose », est une des cinq principales agglomérations.'],
];

const GE26_T1: Fiche = {
  lecon: 'CM2.GE26.T1',
  lieux: [
    ...lieuxRegions((n) => (n === 'p' ? 'n' : n)),
    ...AGGLOS.map(([i, ville, e]) => ({
      id: `agglo-${ville.toLowerCase()}`,
      niv: (ville === 'Paris' ? 'f' : 'n') as Niv,
      map: 'france-regions' as const,
      target: REGIONS[i]![0],
      label: REGIONS[i]![1],
      prompt: `Touche la région de l’agglomération de ${ville}.`,
      e,
    })),
  ],
  qcm: [
    ...qcmCapitalesRegions().map((q) => ({ ...q, niv: q.niv === 'p' ? ('n' as const) : q.niv })),
    {
      id: 'maire',
      niv: 'f',
      q: 'Qui dirige la commune ?',
      r: 'Le maire',
      f: ['Le président de la République', 'Le préfet', 'Le directeur de l’école'],
      e: 'Le maire et le conseil municipal dirigent la commune.',
    },
    {
      id: 'decoupage',
      niv: 'n',
      q: 'Du plus petit au plus grand, comment est découpé le territoire français ?',
      r: 'Commune, département, région',
      f: ['Région, commune, département', 'Département, région, commune', 'Commune, région, département'],
      e: 'Une région regroupe plusieurs départements, et un département regroupe de nombreuses communes.',
    },
    {
      id: 'nb-regions',
      niv: 'f',
      q: 'Combien la France compte-t-elle de régions en tout, outre-mer compris ?',
      r: '18',
      f: ['22', '27', '101'],
      e: 'La France compte 18 régions administratives : 13 en métropole et 5 en outre-mer.',
    },
    {
      id: 'nb-departements',
      niv: 'p',
      q: 'Combien la France compte-t-elle environ de départements ?',
      r: 'Environ 100',
      f: ['Environ 10', 'Environ 1 000', 'Environ 35 000'],
      e: 'La France compte 101 départements ; elle compte aussi près de 35 000 communes.',
    },
    {
      id: 'plus-grande',
      niv: 'f',
      q: 'Quelle est la plus grande agglomération de France ?',
      r: 'Paris',
      f: ['Lyon', 'Lille', 'Toulouse'],
      e: 'L’agglomération de Paris compte plus de 10 millions d’habitants.',
    },
    {
      id: 'agglos',
      niv: 'n',
      q: 'Laquelle de ces villes fait partie des cinq principales agglomérations françaises ?',
      r: 'Toulouse',
      f: ['Rennes', 'Dijon', 'Ajaccio'],
      e: 'Les cinq principales agglomérations sont Paris, Lyon, Marseille, Lille et Toulouse.',
    },
    {
      id: 'tgv',
      niv: 'n',
      q: 'Quel train relie les grandes villes françaises à plus de 300 km/h ?',
      r: 'Le TGV',
      f: ['Le tramway', 'Le métro', 'Le RER'],
      e: 'Les lignes à grande vitesse partent surtout de Paris vers les grandes villes.',
    },
    {
      id: 'etoile',
      niv: 'p',
      q: 'Pourquoi dit-on que les grands axes de transport français forment une étoile ?',
      r: 'Parce que beaucoup d’autoroutes et de lignes TGV partent de Paris',
      f: [
        'Parce qu’ils sont dessinés en jaune',
        'Parce qu’ils ne servent que la nuit',
        'Parce qu’ils évitent Paris',
      ],
      e: 'Paris est au centre du réseau : les axes rayonnent vers les autres grandes villes.',
    },
    {
      id: 'departement-chef',
      niv: 'p',
      q: 'Qui représente l’État dans chaque département ?',
      r: 'Le préfet',
      f: ['Le maire', 'Le député', 'Le directeur d’école'],
      e: 'Le préfet est nommé par le gouvernement pour représenter l’État dans le département.',
    },
  ],
  vf: [
    {
      id: 'regions',
      niv: 'f',
      s: 'La France compte 18 régions.',
      v: true,
      e: '13 régions en métropole et 5 en outre-mer.',
    },
    {
      id: 'paris',
      niv: 'f',
      s: 'Paris est la plus grande agglomération de France.',
      v: true,
      e: 'Elle compte plus de 10 millions d’habitants.',
    },
    {
      id: 'maire',
      niv: 'f',
      s: 'Le maire dirige une région.',
      v: false,
      e: 'Le maire dirige une commune ; la région a un conseil régional.',
    },
    {
      id: 'ajaccio',
      niv: 'f',
      s: 'Ajaccio est la capitale de la Bretagne.',
      v: false,
      e: 'Ajaccio est la capitale de la Corse ; Rennes est celle de la Bretagne.',
    },
    {
      id: 'communes',
      niv: 'n',
      s: 'Un département regroupe plusieurs communes.',
      v: true,
      e: 'Et une région regroupe plusieurs départements.',
    },
    {
      id: 'lille',
      niv: 'n',
      s: 'Lille fait partie des cinq principales agglomérations françaises.',
      v: true,
      e: 'Avec Paris, Lyon, Marseille et Toulouse.',
    },
    {
      id: 'strasbourg',
      niv: 'n',
      s: 'Strasbourg est la capitale de la Nouvelle-Aquitaine.',
      v: false,
      e: 'Strasbourg est la capitale du Grand Est ; Bordeaux est celle de la Nouvelle-Aquitaine.',
    },
    {
      id: 'outre-mer',
      niv: 'n',
      s: 'La Guadeloupe, la Martinique, la Guyane, La Réunion et Mayotte sont des régions françaises.',
      v: true,
      e: 'Ce sont les 5 régions d’outre-mer.',
    },
    {
      id: 'region-plus-petite',
      niv: 'n',
      s: 'Une région est plus petite qu’une commune.',
      v: false,
      e: 'C’est l’inverse : une région contient de nombreuses communes.',
    },
    {
      id: 'prefet',
      niv: 'p',
      s: 'Le préfet est élu par les habitants du département.',
      v: false,
      e: 'Le préfet est nommé par le gouvernement.',
    },
    {
      id: 'lgv',
      niv: 'p',
      s: 'Beaucoup de lignes à grande vitesse partent de Paris.',
      v: true,
      e: 'Le réseau forme une étoile autour de Paris.',
    },
    {
      id: 'nouvelle-aquitaine',
      niv: 'p',
      s: 'La Nouvelle-Aquitaine est la plus grande région de France métropolitaine.',
      v: true,
      e: 'Elle s’étend du Poitou aux Pyrénées.',
    },
  ],
  paires: pairesRegions(),
};

const GE26_T2: Fiche = {
  lecon: 'CM2.GE26.T2',
  lieux: [
    ...lieux('france-fleuves', FLEUVES, 'fleuve'),
    {
      id: 'fleuve-maroni',
      niv: 'n',
      map: 'france-fleuves',
      target: 'maroni',
      label: 'le Maroni',
      e: 'Le Maroni est un fleuve de Guyane, à la frontière avec le Suriname.',
    },
    {
      id: 'lac-leman',
      niv: 'n',
      map: 'france-fleuves',
      target: 'lac-leman',
      label: 'le lac Léman',
      prompt: 'Touche le lac Léman, un grand lac naturel.',
      e: 'Le lac Léman est un lac naturel, partagé entre la France et la Suisse.',
    },
    {
      id: 'serre-poncon',
      niv: 'n',
      map: 'france-fleuves',
      target: 'lac-de-serre-poncon',
      label: 'le lac de Serre-Ponçon',
      prompt: 'Touche le lac de Serre-Ponçon, un grand lac artificiel.',
      e: 'Le lac de Serre-Ponçon, dans les Alpes, a été créé par un barrage sur la Durance.',
    },
    ...lieux('france-massifs', MASSIFS, 'massif'),
  ],
  qcm: [
    {
      id: 'usages',
      niv: 'f',
      q: 'Lequel de ces usages de l’eau se fait à la maison ?',
      r: 'Se laver et cuisiner',
      f: ['Arroser les champs de maïs', 'Refroidir une centrale électrique', 'Faire tourner une usine'],
      e: 'À la maison, l’eau sert à boire, à se laver, à cuisiner et à nettoyer : c’est l’usage domestique.',
    },
    {
      id: 'nappe',
      niv: 'n',
      q: 'Qu’est-ce qu’une nappe phréatique ?',
      r: 'Une réserve d’eau souterraine',
      f: ['Une nappe de pique-nique', 'Un lac en montagne', 'Une rivière gelée'],
      e: 'L’eau de pluie s’infiltre dans le sol et forme des réserves souterraines : les nappes phréatiques.',
    },
    {
      id: 'conflit',
      niv: 'n',
      q: 'Qu’est-ce qu’un conflit d’usages de l’eau ?',
      r: 'Un désaccord entre des personnes qui veulent utiliser la même eau',
      f: ['Une bataille sur un bateau', 'Une fuite d’eau dans une maison', 'Une inondation'],
      e: 'Agriculteurs, habitants, industriels, pêcheurs ou touristes peuvent vouloir la même eau, surtout en été.',
    },
    {
      id: 'limitee',
      niv: 'f',
      q: 'Pourquoi faut-il économiser l’eau douce ?',
      r: 'C’est une ressource limitée',
      f: ['Elle coule sans fin', 'Elle ne sert à rien', 'Elle est toujours salée'],
      e: 'L’eau douce n’est pas infinie : les sécheresses peuvent vider les rivières et les nappes.',
    },
    {
      id: 'maroni',
      niv: 'n',
      q: 'Dans quelle région coule le fleuve Maroni ?',
      r: 'En Guyane',
      f: ['En Bretagne', 'En Corse', 'En Normandie'],
      e: 'Le Maroni coule en Guyane, à la frontière avec le Suriname.',
    },
    {
      id: 'leman',
      niv: 'n',
      q: 'Lequel de ces lacs est un lac naturel ?',
      r: 'Le lac Léman',
      f: ['Le lac de Serre-Ponçon', 'Le lac de Vouglans', 'Le lac du Der'],
      e: 'Le lac Léman est naturel ; le lac de Serre-Ponçon a été créé par un barrage.',
    },
    {
      id: 'serre-poncon',
      niv: 'p',
      q: 'Comment le lac de Serre-Ponçon a-t-il été créé ?',
      r: 'Par un barrage construit sur la Durance',
      f: ['Par un volcan', 'Par la fonte d’un glacier', 'Par une météorite'],
      e: 'Le barrage, terminé en 1960, retient l’eau pour produire de l’électricité et irriguer les cultures.',
    },
    {
      id: 'agriculture',
      niv: 'p',
      q: 'En France, quelle activité consomme le plus d’eau en été ?',
      r: 'L’agriculture, pour irriguer les cultures',
      f: ['Les piscines privées', 'Le lavage des voitures', 'Les fontaines des villes'],
      e: 'L’irrigation des cultures consomme beaucoup d’eau, surtout pendant les étés secs.',
    },
    {
      id: 'loire',
      niv: 'f',
      q: 'Quel est le plus long fleuve de France ?',
      r: 'La Loire',
      f: ['La Seine', 'Le Maroni', 'Le Rhin'],
      e: 'La Loire est le plus long fleuve de France.',
    },
    {
      id: 'qui-leman',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le lac Léman',
      f: ['Le lac de Serre-Ponçon', 'Le lac d’Annecy', 'L’étang de Berre'],
      hints: [
        'Je suis un lac naturel.',
        'Le Rhône me traverse.',
        'Je suis partagé entre la France et la Suisse.',
        'La ville de Genève est à mon extrémité.',
      ],
      img: '🏞️',
      e: 'Le lac Léman est un grand lac naturel traversé par le Rhône.',
    },
  ],
  vf: [
    {
      id: 'limitee',
      niv: 'f',
      s: 'L’eau douce est une ressource limitée.',
      v: true,
      e: 'Il faut la partager et l’économiser.',
    },
    {
      id: 'robinet',
      niv: 'f',
      s: 'Laisser couler le robinet en se brossant les dents économise l’eau.',
      v: false,
      e: 'On ferme le robinet pendant le brossage.',
    },
    {
      id: 'pluie',
      niv: 'f',
      s: 'La pluie remplit les rivières et les nappes souterraines.',
      v: true,
      e: 'C’est le cycle de l’eau.',
    },
    {
      id: 'mer',
      niv: 'f',
      s: 'L’eau de mer est de l’eau douce.',
      v: false,
      e: 'L’eau de mer est salée ; l’eau douce est celle des rivières, des lacs et des nappes.',
    },
    {
      id: 'nappe',
      niv: 'n',
      s: 'Une nappe phréatique est une réserve d’eau souterraine.',
      v: true,
      e: 'On y puise de l’eau potable.',
    },
    {
      id: 'conflit',
      niv: 'n',
      s: 'Pendant une sécheresse, agriculteurs et habitants peuvent se disputer l’eau.',
      v: true,
      e: 'C’est un conflit d’usages.',
    },
    {
      id: 'maroni',
      niv: 'n',
      s: 'Le Maroni est un fleuve de Corse.',
      v: false,
      e: 'Le Maroni coule en Guyane.',
    },
    {
      id: 'serre-poncon',
      niv: 'n',
      s: 'Le lac de Serre-Ponçon est un lac naturel.',
      v: false,
      e: 'C’est un lac artificiel créé par un barrage.',
    },
    {
      id: 'electricite',
      niv: 'n',
      s: 'L’eau des barrages peut servir à produire de l’électricité.',
      v: true,
      e: 'C’est l’énergie hydroélectrique.',
    },
    {
      id: 'irrigation',
      niv: 'p',
      s: 'L’irrigation des champs consomme beaucoup d’eau en été.',
      v: true,
      e: 'Les cultures ont besoin d’eau quand il pleut peu.',
    },
    {
      id: 'restrictions',
      niv: 'p',
      s: 'Pendant une sécheresse, le préfet peut interdire d’arroser son jardin.',
      v: true,
      e: 'Ce sont des restrictions d’eau.',
    },
    {
      id: 'sans-fin',
      niv: 'p',
      s: 'Les nappes phréatiques se remplissent toujours, même sans pluie.',
      v: false,
      e: 'Sans pluie, les nappes baissent.',
    },
  ],
  paires: [
    {
      id: 'villes',
      niv: 'n',
      prompt: 'Associe chaque fleuve à une ville qu’il traverse.',
      relation: 'fleuve → ville',
      pairs: [
        ['la Seine', 'Paris'],
        ['la Loire', 'Nantes'],
        ['la Garonne', 'Bordeaux'],
        ['le Rhône', 'Lyon'],
        ['le Rhin', 'Strasbourg'],
        ['le Maroni', 'Saint-Laurent-du-Maroni'],
      ],
      e: 'Seine-Paris, Loire-Nantes, Garonne-Bordeaux, Rhône-Lyon, Rhin-Strasbourg, Maroni-Saint-Laurent-du-Maroni.',
    },
    {
      id: 'usages',
      niv: 'f',
      prompt: 'Associe chaque usage de l’eau à son exemple.',
      relation: 'usage → exemple',
      pairs: [
        ['usage domestique', 'prendre une douche'],
        ['agriculture', 'arroser les cultures'],
        ['industrie', 'fabriquer du papier'],
        ['énergie', 'faire tourner un barrage'],
        ['loisirs', 'se baigner dans un lac'],
      ],
      e: 'L’eau sert à la maison, aux agriculteurs, aux usines, à produire de l’énergie et aux loisirs.',
    },
  ],
  etapes: [
    {
      id: 'robinet',
      niv: 'n',
      prompt: 'Remets dans l’ordre le trajet de l’eau, du captage jusqu’à la rivière.',
      els: [
        'On pompe l’eau dans une nappe ou une rivière.',
        'L’usine la rend potable.',
        'Elle est stockée dans un château d’eau.',
        'Elle coule au robinet de la maison.',
        'Les eaux usées vont à la station d’épuration.',
        'L’eau nettoyée retourne à la rivière.',
      ],
      e: 'Captage, potabilisation, château d’eau, robinet, station d’épuration, retour à la rivière.',
    },
  ],
};

const UE_FONDATEURS = PAYS_UE.filter((p) => p[4]);
/** Les quatre pays membres ajoutés aux six fondateurs au niveau Normal (dix pays). */
const DIX = ['espagne', 'portugal', 'grece', 'pologne'];

const GE26_T3: Fiche = {
  lecon: 'CM2.GE26.T3',
  evts: [
    {
      id: 'rome',
      niv: 'f',
      label: 'Traité de Rome',
      date: '1957',
      t: 1957.03,
      e: 'En 1957, six pays signent le traité de Rome.',
    },
    {
      id: 'maastricht',
      niv: 'f',
      label: 'Traité de Maastricht : naissance de l’Union européenne',
      date: '1992',
      t: 1992.02,
      e: 'En 1992, le traité de Maastricht crée l’Union européenne.',
    },
    { id: 'ceca', niv: 'p', label: 'Création de la CECA', date: '1951', t: 1951.04 },
    {
      id: 'euro',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Les pièces et les billets en euros',
      date: '2002',
      t: 2002.01,
    },
    {
      id: 'dix',
      niv: 'p',
      label: 'Dix nouveaux pays entrent dans l’Union européenne',
      date: '2004',
      t: 2004.05,
    },
    {
      id: 'brexit',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Le Royaume-Uni quitte l’Union européenne',
      date: '2020',
      t: 2020.01,
    },
  ],
  lieux: [
    ...lieuxPays((p) => p[4], 'f').map((l) =>
      l.niv === 'f' ? { ...l, prompt: `Touche ${l.label}, un des six pays fondateurs.` } : l,
    ),
    // BO 2026 : « dix pays membres de l'UE (dont les six pays fondateurs) » au niveau Normal
    ...lieuxPays((p) => DIX.includes(p[0]), 'n'),
    ...lieuxPays((p) => !p[4] && !DIX.includes(p[0]), 'p'),
    {
      id: 'suisse',
      niv: 'p',
      map: 'europe',
      target: 'suisse',
      label: 'la Suisse',
      prompt: 'Touche la Suisse, un pays d’Europe qui ne fait pas partie de l’Union européenne.',
      e: 'La Suisse est en Europe mais n’est pas membre de l’Union européenne.',
    },
    {
      id: 'norvege',
      niv: 'p',
      map: 'europe',
      target: 'norvege',
      label: 'la Norvège',
      prompt: 'Touche la Norvège, un pays d’Europe qui ne fait pas partie de l’Union européenne.',
      e: 'La Norvège est en Europe mais n’est pas membre de l’Union européenne.',
    },
  ],
  qcm: [
    ...qcmCapitalesPays().filter(
      (q) => UE_FONDATEURS.some((p) => q.id === `capitale-${p[0]}`) || q.niv === 'p',
    ),
    {
      id: 'difference',
      niv: 'n',
      q: 'Quelle est la différence entre l’Europe et l’Union européenne ?',
      r: 'L’Europe est un continent ; l’Union européenne est un groupe de 27 pays qui coopèrent.',
      f: [
        'Ce sont deux noms pour la même chose.',
        'L’Union européenne est plus grande que l’Europe.',
        'L’Europe est un pays ; l’Union européenne est une ville.',
      ],
      e: 'Tous les pays d’Europe ne sont pas membres de l’Union européenne (la Suisse, la Norvège, le Royaume-Uni…).',
    },
    {
      id: 'membres',
      niv: 'f',
      q: 'Combien de pays font partie de l’Union européenne ?',
      r: '27',
      f: ['6', '10', '50'],
      e: 'L’Union européenne compte 27 pays membres.',
    },
    {
      id: 'fondateurs',
      niv: 'n',
      q: 'Combien de pays ont fondé la construction européenne ?',
      r: '6',
      f: ['27', '12', '2'],
      e: 'Les six fondateurs : France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg.',
    },
    {
      id: 'non-membre',
      niv: 'n',
      q: 'Lequel de ces pays d’Europe n’est PAS membre de l’Union européenne ?',
      r: 'La Suisse',
      f: ['La France', 'L’Espagne', 'La Belgique'],
      e: 'La Suisse est en Europe, mais elle n’a pas rejoint l’Union européenne.',
    },
    {
      id: 'drapeau',
      niv: 'f',
      q: 'Comment est le drapeau de l’Union européenne ?',
      r: 'Bleu, avec un cercle de 12 étoiles jaunes',
      f: ['Rouge, avec une étoile jaune', 'Blanc, avec une croix bleue', 'Vert, avec 27 étoiles'],
      img: '🇪🇺',
      e: 'Les 12 étoiles en cercle symbolisent l’unité des peuples d’Europe.',
    },
    {
      id: 'amenagement',
      niv: 'p',
      q: 'Que peut financer l’Union européenne près de chez toi ?',
      r: 'Un aménagement comme une route, une gare ou une piste cyclable',
      f: ['Les devoirs des élèves', 'Les vacances de chaque famille', 'Les jouets des enfants'],
      e: 'L’Union européenne aide à financer des aménagements dans les régions ; un panneau l’indique souvent.',
    },
    {
      id: 'qui-ue',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'L’Union européenne',
      f: ['L’Europe', 'L’ONU', 'La France'],
      hints: [
        'Je ne suis pas un continent.',
        'Je suis née en 1992, avec le traité de Maastricht.',
        'Mon drapeau est bleu avec 12 étoiles.',
        'Je réunis 27 pays qui coopèrent.',
      ],
      img: '🇪🇺',
      e: 'L’Union européenne réunit 27 pays ; ce n’est pas un continent.',
    },
  ],
  vf: [
    {
      id: 'meme-chose',
      niv: 'f',
      s: 'L’Europe et l’Union européenne, c’est la même chose.',
      v: false,
      e: 'L’Europe est un continent ; l’Union européenne réunit 27 pays.',
    },
    {
      id: 'france',
      niv: 'f',
      s: 'La France est membre de l’Union européenne.',
      v: true,
      e: 'C’est même un des six pays fondateurs.',
    },
    {
      id: '27',
      niv: 'f',
      s: 'L’Union européenne compte 27 pays.',
      v: true,
      e: 'Depuis le départ du Royaume-Uni en 2020.',
    },
    {
      id: 'suisse',
      niv: 'f',
      s: 'La Suisse est membre de l’Union européenne.',
      v: false,
      e: 'La Suisse n’est pas membre de l’Union européenne.',
    },
    { id: 'rome', niv: 'n', s: 'Le traité de Rome a été signé en 1957.', v: true, e: 'Par six pays.' },
    {
      id: 'maastricht',
      niv: 'n',
      s: 'Le traité de Maastricht a créé l’Union européenne en 1992.',
      v: true,
      e: 'Maastricht est une ville des Pays-Bas.',
    },
    {
      id: 'espagne',
      niv: 'n',
      s: 'L’Espagne fait partie des six pays fondateurs.',
      v: false,
      e: 'Les fondateurs sont la France, l’Allemagne, l’Italie, la Belgique, les Pays-Bas et le Luxembourg.',
    },
    {
      id: 'royaume-uni',
      niv: 'n',
      s: 'Le Royaume-Uni est toujours membre de l’Union européenne.',
      v: false,
      e: 'Il l’a quittée en 2020.',
    },
    {
      id: 'italie',
      niv: 'n',
      s: 'L’Italie est un pays fondateur.',
      v: true,
      e: 'Le traité de Rome a été signé dans sa capitale.',
    },
    {
      id: 'etoiles',
      niv: 'p',
      s: 'Le drapeau européen a une étoile par pays membre.',
      v: false,
      e: 'Il a toujours 12 étoiles, quel que soit le nombre de pays.',
    },
    {
      id: 'amenagement',
      niv: 'p',
      s: 'L’Union européenne aide à financer des aménagements dans les régions françaises.',
      v: true,
      e: 'Routes, gares, équipements…',
    },
    {
      id: 'norvege',
      niv: 'p',
      s: 'La Norvège est un pays d’Europe qui n’est pas membre de l’Union européenne.',
      v: true,
      e: 'Les Norvégiens ont refusé d’entrer dans l’Union européenne.',
    },
  ],
  paires: pairesPays(),
};

export const GEOGRAPHIE: Fiche[] = [REPERES, DEPLACER, INTERNET, HABITER, GE26_T1, GE26_T2, GE26_T3];
