/**
 * Histoire CM2 — programme 2026 (BO n°22 du 28/05/2026, applicable au CM2 à la rentrée 2027).
 * Repères recopiés du PDF officiel (`cycle3_histoire-geo_BO22-2026.pdf`, p. 6-8) et de
 * `docs/programmes/VERIFICATION_PDF.md` :
 * - T1 : mars 1792 pétition de 319 femmes (Pauline Léon) ; avril 1792 La Marseillaise ; septembre 1792 ;
 *   1794 ; 1802 ; 2 décembre 1804.
 * - T2 : 1848 ; 1882-1886 lois Ferry sur l'École ; 9 décembre 1905.
 * - T3 : le BO date par période (« début XIXe » Stephenson, « fin XIXe » Pasteur, « seconde moitié du XIXe »
 *   grève et syndicats) : les années précises (1864, 1884, 1885) ne sont demandées qu'en Plus loin.
 * - T4 : 1914-1918 ; une grande bataille ; 11 novembre 1918 ; « 10 millions dont 1,4 million de Français ».
 * - T5 : 18 juin 1940 ; 1942 Vel d'Hiv ; 6 juin 1944 ; 8 mai 1945 ; 60 à 70 millions de morts dont 6 millions
 *   de Juifs (60 % des Juifs d'Europe) ; Tsiganes ; Justes parmi les Nations ; « drôle de guerre ».
 * - T6 : 1944 ; 1957 traité de Rome créant la CEE ; 1958 Ve République avec le général de Gaulle ; 1965 ;
 *   « 2000 : l'euro remplace le franc » (pièces et billets en 2002, expliqué à l'enfant).
 */
import { PAIRES_SYMBOLES } from './histoire2020';
import type { Fiche } from './outils';

const T1: Fiche = {
  lecon: 'CM2.HI26.T1',
  evts: [
    {
      id: 'petition',
      niv: 'n',
      label: 'Pétition de 319 femmes (Pauline Léon) pour s’organiser en garde nationale',
      date: 'mars 1792',
      t: 1792.03,
      e: 'En mars 1792, Pauline Léon lit une pétition signée par 319 femmes qui veulent s’armer pour défendre la Révolution.',
    },
    {
      id: 'marseillaise',
      niv: 'n',
      label: 'Composition de La Marseillaise',
      date: 'avril 1792',
      t: 1792.04,
      e: 'En avril 1792, Rouget de Lisle compose à Strasbourg le chant qui deviendra La Marseillaise.',
    },
    {
      id: 'republique',
      niv: 'f',
      label: 'Naissance de la République',
      date: 'septembre 1792',
      t: 1792.09,
      e: 'En septembre 1792, la royauté est abolie et la République naît.',
    },
    {
      id: 'louis16',
      niv: 'p',
      sens: true,
      label: 'Exécution de Louis XVI',
      date: 'janvier 1793',
      t: 1793.01,
    },
    {
      id: 'abolition',
      niv: 'n',
      sens: true,
      label: 'Première abolition de l’esclavage',
      date: '1794',
      t: 1794.02,
      e: 'En 1794, la Convention abolit l’esclavage dans les colonies françaises pour la première fois.',
    },
    { id: 'prefets', niv: 'p', label: 'Création des préfets', date: '1800', t: 1800.02 },
    {
      id: 'brumaire',
      niv: 'p',
      label: 'Bonaparte prend le pouvoir (coup d’État)',
      date: 'novembre 1799',
      t: 1799.11,
    },
    {
      id: 'retablissement',
      niv: 'n',
      sens: true,
      label: 'Rétablissement de l’esclavage par Bonaparte',
      date: '1802',
      t: 1802.05,
      e: 'En 1802, Napoléon Bonaparte rétablit l’esclavage dans les colonies françaises.',
    },
    { id: 'code', niv: 'p', label: 'Publication du Code civil', date: 'mars 1804', t: 1804.03 },
    {
      id: 'sacre',
      niv: 'f',
      label: 'Sacre de Napoléon Ier',
      date: '2 décembre 1804',
      t: 1804.1202,
      e: 'Le 2 décembre 1804, Napoléon Bonaparte est sacré empereur à Notre-Dame de Paris.',
    },
    { id: 'fin-empire', niv: 'f', label: 'Fin de l’Empire de Napoléon Ier', date: '1815', t: 1815.06 },
  ],
  qcm: [
    {
      id: 'qui-leon',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Pauline Léon',
      f: ['Marie-Antoinette', 'Joséphine de Beauharnais', 'Marie Curie'],
      hints: [
        'Je suis une Parisienne qui fabrique du chocolat.',
        'Je participe aux clubs révolutionnaires.',
        'En mars 1792, je lis une pétition signée par 319 femmes.',
        'Je demande que les femmes puissent s’armer pour défendre la Révolution.',
      ],
      img: '📜',
      e: 'Pauline Léon montre que les femmes veulent participer à la vie politique de la Révolution.',
    },
    {
      id: 'qui-rouget',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Rouget de Lisle',
      f: ['Victor Hugo', 'Napoléon Bonaparte', 'Louis XVI'],
      hints: [
        'Je suis un officier de l’armée française.',
        'En avril 1792, je suis à Strasbourg.',
        'J’écris un chant pour les soldats de l’armée du Rhin.',
        'Des soldats venus de Marseille le chantent à Paris : il prend le nom de leur ville.',
      ],
      img: '🎶',
      e: 'Rouget de Lisle compose en avril 1792 le chant qui deviendra La Marseillaise.',
    },
    {
      id: 'qui-napoleon',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'Napoléon Bonaparte',
      f: ['Louis XVI', 'Charlemagne', 'Jules Ferry'],
      hints: [
        'Je suis né en Corse en 1769.',
        'Je suis un général victorieux pendant la Révolution.',
        'En 1799, je prends le pouvoir.',
        'Le 2 décembre 1804, je suis sacré empereur à Notre-Dame de Paris.',
      ],
      img: '🎖️',
      e: 'Napoléon Bonaparte prend le pouvoir en 1799 et devient l’empereur Napoléon Ier en 1804.',
    },
    {
      id: 'qui-louverture',
      niv: 'p',
      sens: true,
      q: 'Qui suis-je ?',
      r: 'Toussaint Louverture',
      f: ['Victor Schœlcher', 'Napoléon Bonaparte', 'Rouget de Lisle'],
      hints: [
        'Je suis né esclave à Saint-Domingue, une île des Antilles.',
        'Devenu libre, je deviens un grand chef.',
        'Je lutte pour la liberté des esclaves de mon île.',
        'Mon île deviendra Haïti, premier pays fondé par d’anciens esclaves, en 1804.',
      ],
      e: 'Toussaint Louverture a combattu pour la liberté des esclaves de Saint-Domingue, devenue Haïti.',
    },
    {
      id: 'empereur',
      niv: 'f',
      q: 'Que devient Napoléon Bonaparte en 1804 ?',
      r: 'Empereur des Français',
      f: ['Roi de France', 'Président de la République', 'Maire de Paris'],
      e: 'Le 2 décembre 1804, Napoléon Bonaparte devient Napoléon Ier, empereur des Français.',
    },
    {
      id: 'code',
      niv: 'n',
      q: 'Qu’est-ce que le Code civil ?',
      r: 'Un recueil de lois communes à tous les Français',
      f: ['Un code secret de l’armée', 'Le règlement d’une école', 'Un livre de cuisine'],
      e: 'Le Code civil (1804) rassemble les lois sur la famille, le mariage et la propriété.',
    },
    {
      id: 'petition',
      niv: 'n',
      q: 'Qu’est-ce qu’une pétition ?',
      r: 'Un texte signé par plusieurs personnes pour demander quelque chose',
      f: ['Un chant révolutionnaire', 'Une loi votée par le roi', 'Un impôt'],
      e: 'En 1792, 319 femmes signent une pétition pour pouvoir s’armer.',
    },
    {
      id: 'sacre-lieu',
      niv: 'p',
      q: 'Où Napoléon est-il sacré empereur en 1804 ?',
      r: 'À Notre-Dame de Paris',
      f: ['À la cathédrale de Reims', 'Au château de Versailles', 'À Marseille'],
      e: 'Les rois étaient sacrés à Reims ; Napoléon choisit Notre-Dame de Paris.',
    },
    {
      id: 'acquis',
      niv: 'p',
      sens: true,
      q: 'Quels acquis de la Révolution Napoléon remet-il en cause ?',
      r: 'Il rétablit l’esclavage et limite la liberté de la presse.',
      f: [
        'Il donne le droit de vote aux femmes.',
        'Il supprime les préfets.',
        'Il rend l’école gratuite pour tous.',
      ],
      e: 'Napoléon rétablit l’esclavage en 1802 et surveille les journaux : certaines libertés reculent.',
    },
    {
      id: 'lycees',
      niv: 'p',
      q: 'Quels établissements scolaires Napoléon crée-t-il en 1802 ?',
      r: 'Les lycées',
      f: ['Les écoles maternelles', 'Les collèges uniques', 'Les crèches'],
      e: 'Napoléon crée les lycées pour former les futurs officiers et fonctionnaires.',
    },
  ],
  vf: [
    {
      id: 'republique',
      niv: 'f',
      s: 'La République naît en septembre 1792.',
      v: true,
      e: 'La royauté est abolie et la République est proclamée en septembre 1792.',
    },
    {
      id: 'sacre',
      niv: 'f',
      s: 'Napoléon Ier est sacré empereur le 2 décembre 1804.',
      v: true,
      e: 'Le sacre a lieu à Notre-Dame de Paris.',
    },
    {
      id: 'roi',
      niv: 'f',
      s: 'Napoléon Bonaparte était roi de France.',
      v: false,
      e: 'Il était empereur des Français.',
    },
    {
      id: 'avant',
      niv: 'f',
      s: 'La République est née avant la Révolution de 1789.',
      v: false,
      e: 'La République naît en 1792, après le début de la Révolution.',
    },
    {
      id: 'chute',
      niv: 'f',
      s: 'Après la chute du roi en 1792, la France devient une république.',
      v: true,
      e: 'La royauté est abolie en septembre 1792.',
    },
    {
      id: 'marseillaise',
      niv: 'n',
      s: 'La Marseillaise a été composée en 1815.',
      v: false,
      e: 'Elle a été composée en avril 1792.',
    },
    {
      id: '1794',
      niv: 'n',
      sens: true,
      s: 'L’esclavage est aboli une première fois en 1794.',
      v: true,
      e: 'La Convention l’abolit en 1794.',
    },
    {
      id: '1802',
      niv: 'n',
      sens: true,
      s: 'En 1802, Napoléon Bonaparte rétablit l’esclavage.',
      v: true,
      e: 'C’est un recul des droits obtenus pendant la Révolution.',
    },
    {
      id: 'code',
      niv: 'n',
      s: 'Le Code civil est un recueil de lois.',
      v: true,
      e: 'Il est publié en 1804 et existe encore aujourd’hui.',
    },
    {
      id: 'lycees',
      niv: 'p',
      s: 'Napoléon a créé les lycées.',
      v: true,
      e: 'Les lycées sont créés en 1802.',
    },
    {
      id: 'leon',
      niv: 'p',
      s: 'Pauline Léon demandait que les femmes puissent s’armer pour défendre la Révolution.',
      v: true,
      e: 'C’est la pétition de mars 1792.',
    },
    {
      id: 'prefet',
      niv: 'p',
      s: 'Le préfet dirige une commune.',
      v: false,
      e: 'Le préfet représente l’État dans un département ; c’est le maire qui dirige la commune.',
    },
    {
      id: 'presse',
      niv: 'p',
      s: 'Napoléon a renforcé la liberté de la presse.',
      v: false,
      e: 'Il a au contraire surveillé et limité les journaux.',
    },
    {
      id: '1799',
      niv: 'p',
      s: 'Bonaparte prend le pouvoir en 1799.',
      v: true,
      e: 'C’est le coup d’État de novembre 1799.',
    },
  ],
};

const T2: Fiche = {
  lecon: 'CM2.HI26.T2',
  evts: [
    {
      id: 'suffrage',
      niv: 'f',
      excl: '1848',
      label: 'Suffrage universel masculin',
      date: '1848',
      t: 1848.03,
      e: 'En 1848, tous les hommes de 21 ans et plus obtiennent le droit de vote.',
    },
    {
      id: 'abolition',
      niv: 'n',
      sens: true,
      excl: '1848',
      label: 'Abolition définitive de l’esclavage',
      date: 'avril 1848',
      t: 1848.04,
      e: 'En 1848, l’esclavage est définitivement aboli dans les colonies françaises.',
    },
    {
      id: 'algerie',
      niv: 'p',
      sens: true,
      label: 'Début de la conquête de l’Algérie',
      date: '1830',
      t: 1830.07,
    },
    { id: 'rep3', niv: 'n', label: 'Naissance de la IIIe République', date: '1870', t: 1870.09 },
    { id: 'hymne', niv: 'p', label: 'La Marseillaise devient l’hymne national', date: '1879', t: 1879.02 },
    { id: 'fete', niv: 'p', label: 'Le 14 Juillet devient la fête nationale', date: '1880', t: 1880.07 },
    { id: 'presse', niv: 'p', label: 'Loi sur la liberté de la presse', date: '1881', t: 1881.07 },
    { id: 'ferry', niv: 'f', label: 'Lois Ferry sur l’École', date: '1882-1886', t: 1882.03 },
    {
      id: 'separation',
      niv: 'f',
      label: 'Séparation des Églises et de l’État',
      date: '9 décembre 1905',
      t: 1905.1209,
      e: 'La loi du 9 décembre 1905 sépare les Églises et l’État : c’est la laïcité.',
    },
  ],
  lieux: [
    {
      id: 'afrique',
      niv: 'n',
      sens: true,
      map: 'monde',
      target: 'afrique',
      label: 'l’Afrique',
      prompt:
        'Touche le continent où se trouvait la plus grande partie de l’empire colonial français vers 1914.',
      e: 'Vers 1914, la France domine une grande partie de l’Afrique du Nord et de l’Ouest, et Madagascar.',
    },
    {
      id: 'asie',
      niv: 'n',
      sens: true,
      map: 'monde',
      target: 'asie',
      label: 'l’Asie',
      prompt: 'Touche le continent où se trouvait l’Indochine française.',
      e: 'L’Indochine (aujourd’hui le Viêt Nam, le Laos et le Cambodge) se trouve en Asie.',
    },
    {
      id: 'oceanie',
      niv: 'p',
      sens: true,
      map: 'monde',
      target: 'oceanie',
      label: 'l’Océanie',
      prompt: 'Touche le continent où se trouve la Nouvelle-Calédonie, colonisée par la France en 1853.',
      e: 'La Nouvelle-Calédonie est une île de l’océan Pacifique, en Océanie.',
    },
    {
      id: 'amerique',
      niv: 'p',
      sens: true,
      map: 'monde',
      target: 'amerique-du-sud',
      label: 'l’Amérique du Sud',
      prompt: 'Touche le continent où se trouve la Guyane, colonie française au XIXe siècle.',
      e: 'La Guyane est en Amérique du Sud ; c’est aujourd’hui une région française.',
    },
  ],
  qcm: [
    {
      id: 'qui-ferry',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Jules Ferry',
      f: ['Victor Hugo', 'Louis Pasteur', 'Napoléon III'],
      hints: [
        'Je suis un homme politique de la IIIe République.',
        'J’ai été ministre de l’Instruction publique.',
        'Des lois sur l’École portent mon nom.',
        'Grâce à moi, l’école primaire devient gratuite, laïque et obligatoire.',
      ],
      img: '🏫',
      e: 'Les lois Ferry organisent l’école primaire gratuite, laïque et obligatoire.',
    },
    {
      id: 'qui-schoelcher',
      niv: 'n',
      sens: true,
      q: 'Qui suis-je ?',
      r: 'Victor Schœlcher',
      f: ['Jules Ferry', 'Victor Hugo', 'Jean Jaurès'],
      hints: [
        'Je suis un homme politique français du XIXe siècle.',
        'J’ai voyagé dans les colonies et j’ai été révolté par l’esclavage.',
        'En 1848, je prépare le décret d’abolition de l’esclavage.',
        'Je repose au Panthéon.',
      ],
      e: 'Victor Schœlcher a fait abolir définitivement l’esclavage en 1848.',
    },
    {
      id: 'qui-hugo',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Victor Hugo',
      f: ['Émile Zola', 'Jules Verne', 'Jules Ferry'],
      hints: [
        'Je suis un écrivain et un poète.',
        'J’ai écrit Les Misérables.',
        'Je m’oppose à Napoléon III et je pars en exil pendant près de vingt ans.',
        'À ma mort, en 1885, je suis enterré au Panthéon.',
      ],
      img: '✒️',
      e: 'Victor Hugo, grand écrivain, a défendu la République contre Napoléon III.',
    },
    {
      id: 'symbole',
      niv: 'n',
      q: 'Lequel de ces éléments n’est PAS un symbole de la République ?',
      r: 'La couronne',
      f: ['Marianne', 'Le drapeau tricolore', 'La Marseillaise'],
      e: 'La couronne est un symbole de la royauté ; Marianne, le drapeau, la Marseillaise, le 14 Juillet et la devise sont les symboles de la République.',
    },
    {
      id: 'vote-1848',
      niv: 'n',
      q: 'Qui peut voter en 1848 ?',
      r: 'Tous les hommes de 21 ans et plus',
      f: ['Tous les hommes et toutes les femmes', 'Seulement les hommes riches', 'Seulement les nobles'],
      e: 'C’est le suffrage universel masculin : les femmes votent seulement à partir de 1944.',
    },
    {
      id: 'laicite',
      niv: 'n',
      q: 'Qu’est-ce que la laïcité ?',
      r: 'L’État ne favorise aucune religion et chacun est libre de croire ou non.',
      f: [
        'Tout le monde doit avoir la même religion.',
        'Les religions sont interdites.',
        'Le roi choisit la religion du pays.',
      ],
      e: 'Depuis la loi de 1905, l’État est neutre et protège la liberté de croire ou de ne pas croire.',
    },
    {
      id: 'presse',
      niv: 'p',
      q: 'Que permet la loi de 1881 sur la presse ?',
      r: 'Publier librement des journaux',
      f: ['Interdire les journaux', 'Fermer les imprimeries', 'Réserver les journaux au gouvernement'],
      e: 'La loi de 1881 garantit la liberté de la presse.',
    },
    {
      id: 'empire',
      niv: 'p',
      sens: true,
      q: 'Qu’est-ce qu’un empire colonial ?',
      r: 'L’ensemble des territoires conquis et dominés par un pays',
      f: ['Une très grande ville', 'Le palais d’un empereur', 'Une armée de volontaires'],
      e: 'Au XIXe siècle, la France conquiert des territoires en Afrique, en Asie et en Océanie.',
    },
    {
      id: 'devise',
      niv: 'f',
      q: 'Quelle est la devise de la République ?',
      r: 'Liberté, Égalité, Fraternité',
      f: ['Paix, Joie, Amitié', 'Un pour tous, tous pour un', 'Honneur et Courage'],
      e: 'La devise « Liberté, Égalité, Fraternité » est inscrite sur les mairies et les écoles.',
    },
  ],
  vf: [
    {
      id: 'hommes',
      niv: 'f',
      s: 'En 1848, tous les hommes adultes obtiennent le droit de vote.',
      v: true,
      e: 'C’est le suffrage universel masculin.',
    },
    {
      id: 'femmes',
      niv: 'f',
      s: 'En 1848, les femmes obtiennent le droit de vote.',
      v: false,
      e: 'Les femmes obtiennent le droit de vote en 1944.',
    },
    {
      id: 'symboles',
      niv: 'f',
      s: 'Marianne, le drapeau tricolore et la Marseillaise sont des symboles de la République.',
      v: true,
      e: 'Avec le 14 Juillet et la devise.',
    },
    {
      id: 'ferry',
      niv: 'f',
      s: 'Les lois Ferry rendent l’école gratuite, laïque et obligatoire.',
      v: true,
      e: 'Ce sont les lois scolaires des années 1880.',
    },
    {
      id: 'drapeau',
      niv: 'f',
      s: 'Le drapeau tricolore est vert, blanc et rouge.',
      v: false,
      e: 'Il est bleu, blanc et rouge.',
    },
    {
      id: 'devise',
      niv: 'f',
      s: 'La devise de la République est « Liberté, Égalité, Fraternité ».',
      v: true,
      e: 'Elle est écrite sur les bâtiments publics.',
    },
    {
      id: 'abolition',
      niv: 'n',
      sens: true,
      s: 'L’esclavage est définitivement aboli en 1848.',
      v: true,
      e: 'Après une première abolition en 1794 et son rétablissement en 1802.',
    },
    {
      id: '1905',
      niv: 'n',
      s: 'La loi du 9 décembre 1905 sépare les Églises et l’État.',
      v: true,
      e: 'C’est une grande loi de laïcité.',
    },
    {
      id: 'rep3',
      niv: 'n',
      s: 'La IIIe République commence en 1914.',
      v: false,
      e: 'Elle commence en 1870.',
    },
    {
      id: 'laicite',
      niv: 'n',
      s: 'La laïcité interdit aux citoyens d’avoir une religion.',
      v: false,
      e: 'Elle protège au contraire la liberté de croire ou de ne pas croire.',
    },
    {
      id: 'presse',
      niv: 'p',
      s: 'La loi de 1881 supprime la liberté de la presse.',
      v: false,
      e: 'Elle garantit la liberté de la presse.',
    },
    {
      id: 'colonies',
      niv: 'p',
      sens: true,
      s: 'Au début du XXe siècle, la France possède un empire colonial en Afrique et en Asie.',
      v: true,
      e: 'C’est le deuxième empire colonial du monde.',
    },
    {
      id: 'rep2',
      niv: 'p',
      s: 'La IIe République dure de 1848 à 1852.',
      v: true,
      e: 'Elle se termine quand Louis-Napoléon Bonaparte devient l’empereur Napoléon III.',
    },
    {
      id: '1880',
      niv: 'p',
      s: 'Le 14 Juillet est la fête nationale depuis 1880.',
      v: true,
      e: 'C’est une loi de 1880.',
    },
  ],
  paires: [{ id: 'symboles', niv: 'n', ...PAIRES_SYMBOLES }],
};

const T3: Fiche = {
  lecon: 'CM2.HI26.T3',
  evts: [
    {
      id: 'stephenson',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Première ligne de chemin de fer avec une locomotive de Stephenson, en Angleterre',
      date: 'début du XIXe siècle, 1825',
      t: 1825.09,
      e: 'Au début du XIXe siècle, George Stephenson invente la locomotive à vapeur ; sa première ligne ouvre en 1825 en Angleterre.',
    },
    {
      id: 'train-fr',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Première ligne de chemin de fer pour voyageurs au départ de Paris',
      date: 'première moitié du XIXe siècle, 1837',
      t: 1837.08,
    },
    {
      id: 'loi-enfants',
      niv: 'p',
      sens: true,
      label: 'Première loi limitant le travail des enfants',
      date: '1841',
      t: 1841.03,
    },
    { id: 'bon-marche', niv: 'p', label: 'Ouverture du grand magasin Le Bon Marché', date: '1852', t: 1852 },
    {
      id: 'greve',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Droit de grève',
      date: 'seconde moitié du XIXe siècle, 1864',
      t: 1864.05,
      e: 'Dans la seconde moitié du XIXe siècle, les ouvriers obtiennent le droit de grève (1864).',
    },
    {
      id: 'syndicats',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Loi sur la liberté syndicale',
      date: 'seconde moitié du XIXe siècle, 1884',
      t: 1884.03,
      e: 'Dans la seconde moitié du XIXe siècle, une loi autorise les syndicats (1884).',
    },
    {
      id: 'pasteur',
      niv: 'n',
      nivAnnee: 'p',
      label: 'Vaccin contre la rage de Louis Pasteur',
      date: 'fin du XIXe siècle, 1885',
      t: 1885.07,
      e: 'À la fin du XIXe siècle, Louis Pasteur met au point le vaccin contre la rage (1885).',
    },
    { id: 'eiffel', niv: 'f', label: 'Construction de la tour Eiffel', date: '1889', t: 1889 },
    { id: 'metro', niv: 'f', label: 'Première ligne du métro de Paris', date: '1900', t: 1900.07 },
  ],
  qcm: [
    {
      id: 'pasteur',
      niv: 'f',
      q: 'Qui a mis au point le vaccin contre la rage ?',
      r: 'Louis Pasteur',
      f: ['Gustave Eiffel', 'Jules Ferry', 'Victor Hugo'],
      e: 'À la fin du XIXe siècle, Louis Pasteur invente le vaccin contre la rage.',
    },
    {
      id: 'qui-pasteur',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Louis Pasteur',
      f: ['Marie Curie', 'Thomas Edison', 'Gustave Eiffel'],
      hints: [
        'Je suis un scientifique français.',
        'J’ai montré que des microbes provoquent des maladies.',
        'Ma méthode pour conserver le lait porte mon nom : la pasteurisation.',
        'En 1885, je sauve un enfant mordu par un chien enragé grâce à un vaccin.',
      ],
      img: '🔬',
      e: 'Louis Pasteur a découvert le rôle des microbes et mis au point le vaccin contre la rage.',
    },
    {
      id: 'qui-stephenson',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'George Stephenson',
      f: ['James Watt', 'Thomas Edison', 'Gustave Eiffel'],
      hints: [
        'Je suis un ingénieur anglais.',
        'J’ai commencé à travailler très jeune dans une mine de charbon.',
        'Je construis des machines à vapeur qui roulent sur des rails.',
        'On me surnomme le « père des chemins de fer ».',
      ],
      img: '🚂',
      e: 'Au début du XIXe siècle, George Stephenson invente la locomotive à vapeur.',
    },
    {
      id: 'industrialisation',
      niv: 'n',
      q: 'Qu’est-ce que l’industrialisation ?',
      r: 'Le développement des usines et des machines',
      f: ['Le retour à la vie à la campagne', 'La construction de châteaux forts', 'La fin du commerce'],
      e: 'Au XIXe siècle, les usines et les machines se multiplient : c’est l’industrialisation.',
    },
    {
      id: 'urbanisation',
      niv: 'n',
      q: 'Qu’est-ce que l’urbanisation ?',
      r: 'La croissance des villes',
      f: ['La construction de routes', 'Le départ des habitants des villes', 'La culture des champs'],
      e: 'Les villes grandissent car les gens viennent travailler dans les usines.',
    },
    {
      id: 'energie',
      niv: 'f',
      q: 'Quelle était la principale source d’énergie des usines au XIXe siècle ?',
      r: 'Le charbon',
      f: ['Le nucléaire', 'Le soleil', 'Le vent'],
      e: 'Le charbon fait fonctionner les machines à vapeur.',
    },
    {
      id: 'bourgeois',
      niv: 'n',
      q: 'Qui est un bourgeois au XIXe siècle ?',
      r: 'Un patron d’usine, un banquier ou un médecin aisé',
      f: ['Un ouvrier de la mine', 'Un paysan pauvre', 'Un jeune apprenti'],
      e: 'Les bourgeois vivent dans le confort, alors que les ouvriers vivent souvent dans la pauvreté.',
    },
    {
      id: 'rurale',
      niv: 'n',
      q: 'Au XIXe siècle, où vit la majorité des Français ?',
      r: 'À la campagne',
      f: ['En ville', 'À l’étranger', 'Dans les usines'],
      e: 'Malgré l’industrialisation, la société française reste très majoritairement rurale.',
    },
    {
      id: 'greve',
      niv: 'n',
      q: 'Que réclament les ouvriers quand ils font grève ?',
      r: 'De meilleurs salaires et moins d’heures de travail',
      f: ['La fermeture des écoles', 'Le retour du roi', 'Des journées de travail plus longues'],
      e: 'La grève est un moyen de lutter pour de meilleures conditions de travail.',
    },
    {
      id: 'medecine',
      niv: 'p',
      q: 'Quel progrès de la médecine se développe au XIXe siècle ?',
      r: 'Les vaccins',
      f: ['Les robots chirurgiens', 'Les scanners', 'Les greffes de cœur'],
      e: 'Au XIXe siècle, Pasteur et d’autres savants développent les vaccins et l’hygiène.',
    },
  ],
  vf: [
    {
      id: 'vapeur',
      niv: 'f',
      s: 'Au XIXe siècle, les machines à vapeur fonctionnent au charbon.',
      v: true,
      e: 'Le charbon chauffe l’eau qui produit la vapeur.',
    },
    {
      id: 'pasteur',
      niv: 'f',
      s: 'Louis Pasteur a mis au point le vaccin contre la rage.',
      v: true,
      e: 'C’est à la fin du XIXe siècle.',
    },
    {
      id: 'ouvriers',
      niv: 'f',
      s: 'Les ouvrières et les ouvriers travaillent dans les usines, les mines et les ateliers.',
      v: true,
      e: 'Ce sont les lieux de travail de l’âge industriel.',
    },
    {
      id: 'bourgeois',
      niv: 'f',
      s: 'Les bourgeois sont des ouvriers pauvres.',
      v: false,
      e: 'Les bourgeois sont des habitants aisés : patrons, banquiers, médecins…',
    },
    {
      id: 'nucleaire',
      niv: 'f',
      s: 'Au XIXe siècle, les usines fonctionnent grâce à l’énergie nucléaire.',
      v: false,
      e: 'Elles fonctionnent au charbon ; le nucléaire arrive au XXe siècle.',
    },
    {
      id: 'ville',
      niv: 'n',
      s: 'Au XIXe siècle, la majorité des Français vivent en ville.',
      v: false,
      e: 'La majorité vit encore à la campagne.',
    },
    {
      id: 'greve',
      niv: 'n',
      s: 'Faire grève, c’est arrêter de travailler pour obtenir de meilleures conditions.',
      v: true,
      e: 'Le droit de grève est obtenu dans la seconde moitié du XIXe siècle.',
    },
    {
      id: 'syndicat',
      niv: 'n',
      s: 'Un syndicat défend les droits des travailleurs.',
      v: true,
      e: 'Les syndicats sont autorisés dans la seconde moitié du XIXe siècle.',
    },
    {
      id: 'locomotive',
      niv: 'n',
      s: 'La locomotive a été inventée au XXe siècle.',
      v: false,
      e: 'Elle a été inventée au début du XIXe siècle par Stephenson.',
    },
    {
      id: 'usines',
      niv: 'n',
      s: 'Les usines se construisent souvent près des mines de charbon ou des ports.',
      v: true,
      e: 'Elles ont besoin d’énergie et de transports.',
    },
    {
      id: '1864',
      niv: 'p',
      s: 'Le droit de grève est reconnu en 1864.',
      v: true,
      e: 'C’est une loi de 1864.',
    },
    {
      id: '1884',
      niv: 'p',
      s: 'La loi sur la liberté syndicale date de 1884.',
      v: true,
      e: 'Elle autorise les syndicats.',
    },
    {
      id: '1885',
      niv: 'p',
      s: 'Pasteur a soigné un enfant mordu par un chien enragé en 1885.',
      v: true,
      e: 'Grâce au vaccin, l’enfant, Joseph Meister, a survécu.',
    },
    {
      id: 'enfants',
      niv: 'p',
      sens: true,
      s: 'Les enfants n’ont jamais travaillé dans les usines.',
      v: false,
      e: 'Des enfants travaillaient dans les usines et les mines ; des lois ont peu à peu limité ce travail.',
    },
    {
      id: 'urbanisation',
      niv: 'p',
      s: 'L’urbanisation, c’est quand les villes se vident.',
      v: false,
      e: 'L’urbanisation, c’est la croissance des villes.',
    },
  ],
  paires: [
    {
      id: 'mots',
      niv: 'n',
      prompt: 'Associe chaque mot à sa définition.',
      relation: 'mot → définition',
      pairs: [
        ['l’usine', 'grand bâtiment où des machines fabriquent des produits'],
        ['la grève', 'arrêt du travail pour réclamer'],
        ['le syndicat', 'association qui défend les travailleurs'],
        ['le vaccin', 'protège contre une maladie'],
        ['l’atelier', 'petit lieu de travail d’un artisan'],
      ],
      e: 'Usine, grève, syndicat, vaccin, atelier : ce sont des mots clés de l’âge industriel.',
    },
  ],
};

const T4: Fiche = {
  lecon: 'CM2.HI26.T4',
  sens: true,
  evts: [
    { id: 'debut', niv: 'f', label: 'Début de la Première Guerre mondiale', date: 'août 1914', t: 1914.08 },
    { id: 'marne', niv: 'p', label: 'Bataille de la Marne', date: 'septembre 1914', t: 1914.09 },
    {
      id: 'verdun',
      niv: 'n',
      excl: '1916',
      label: 'Bataille de Verdun',
      date: '1916',
      t: 1916.02,
      e: 'La bataille de Verdun dure de février à décembre 1916 : c’est une des plus grandes batailles de la guerre.',
    },
    { id: 'somme', niv: 'p', label: 'Bataille de la Somme', date: 'juillet 1916', t: 1916.07, excl: '1916' },
    { id: 'usa', niv: 'p', label: 'Les États-Unis entrent en guerre', date: 'avril 1917', t: 1917.04 },
    {
      id: 'armistice',
      niv: 'f',
      label: 'Armistice',
      date: '11 novembre 1918',
      t: 1918.1111,
      e: 'Le 11 novembre 1918, l’armistice met fin aux combats.',
    },
    { id: 'versailles', niv: 'p', label: 'Traité de Versailles', date: 'juin 1919', t: 1919.06 },
  ],
  qcm: [
    {
      id: 'front',
      niv: 'n',
      q: 'Où se trouvent les principaux combats en France ?',
      r: 'Dans le nord et l’est du pays',
      f: ['Dans le sud-ouest', 'En Bretagne', 'En Corse'],
      e: 'Le front occidental traverse le nord et l’est de la France.',
    },
    {
      id: 'poilus',
      niv: 'f',
      q: 'Comment surnomme-t-on les soldats français de la Première Guerre mondiale ?',
      r: 'Les poilus',
      f: ['Les grognards', 'Les mousquetaires', 'Les chevaliers'],
      e: 'On les appelle les poilus, à cause de leur barbe et de leur courage.',
    },
    {
      id: 'qui-poilu',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le poilu',
      f: ['Le grognard', 'Le mousquetaire', 'Le chevalier'],
      hints: [
        'Je suis un soldat français de 1914-1918.',
        'Je vis dans les tranchées, dans la boue et le froid.',
        'J’écris des lettres à ma famille.',
        'On me surnomme ainsi à cause de ma barbe et de mon courage.',
      ],
      e: 'Le poilu est le soldat français de la Première Guerre mondiale.',
    },
    {
      id: 'bilan',
      niv: 'n',
      q: 'Combien de soldats sont morts au combat pendant la Première Guerre mondiale ?',
      r: 'Environ 10 millions, dont 1,4 million de Français',
      f: [
        'Environ 1 000, dont 100 Français',
        'Environ 100 000, dont 10 000 Français',
        'Environ 1 milliard, dont 100 millions de Français',
      ],
      e: 'Le programme retient : 10 millions de morts au combat, dont 1,4 million de Français.',
    },
    {
      id: 'position',
      niv: 'n',
      q: 'Qu’est-ce que la guerre de position ?',
      r: 'Les armées restent face à face, enterrées dans des tranchées.',
      f: [
        'Les armées avancent très vite.',
        'Les soldats se battent à cheval dans les villes.',
        'Il n’y a plus de soldats.',
      ],
      e: 'De fin 1914 au printemps 1918, le front bouge très peu : c’est la guerre de position.',
    },
    {
      id: 'mouvement',
      niv: 'p',
      q: 'Qu’est-ce que la guerre de mouvement ?',
      r: 'Les armées avancent et reculent rapidement.',
      f: [
        'Les armées restent dans les tranchées.',
        'Les soldats ne bougent plus.',
        'La guerre se fait seulement en mer.',
      ],
      e: 'Au début (1914) et à la fin (1918) de la guerre, les armées avancent et reculent : c’est la guerre de mouvement.',
    },
    {
      id: 'femmes',
      niv: 'n',
      q: 'Quel rôle jouent beaucoup de femmes pendant la guerre ?',
      r: 'Elles remplacent les hommes dans les usines et dans les champs.',
      f: [
        'Elles ne travaillent plus.',
        'Elles deviennent toutes institutrices.',
        'Elles partent toutes au front comme soldats.',
      ],
      e: 'Les femmes font tourner les usines, les fermes et les transports pendant que les hommes sont au front.',
    },
    {
      id: 'munitionnettes',
      niv: 'p',
      q: 'Qui sont les « munitionnettes » ?',
      r: 'Des ouvrières qui fabriquent des obus',
      f: ['Des infirmières', 'Des institutrices', 'Des paysannes'],
      e: 'Dans les usines d’armement, des milliers de femmes fabriquent des obus.',
    },
    {
      id: '11-novembre',
      niv: 'f',
      q: 'Que se passe-t-il le 11 novembre 1918 ?',
      r: 'L’armistice met fin aux combats.',
      f: ['La guerre commence.', 'Les Alliés débarquent en Normandie.', 'La Bastille est prise.'],
      e: 'Le 11 novembre est devenu un jour de commémoration.',
    },
    {
      id: 'mondiale',
      niv: 'p',
      q: 'Pourquoi parle-t-on de guerre « mondiale » ?',
      r: 'Parce que de nombreux pays de plusieurs continents y participent',
      f: [
        'Parce qu’elle a duré cent ans',
        'Parce qu’elle a eu lieu seulement en France',
        'Parce qu’un seul pays s’est battu',
      ],
      e: 'Des pays d’Europe, d’Amérique, d’Asie et des colonies d’Afrique y participent.',
    },
    {
      id: 'colonies',
      niv: 'p',
      q: 'Qui sont les tirailleurs sénégalais ?',
      r: 'Des soldats venus des colonies françaises d’Afrique',
      f: ['Des soldats allemands', 'Des marins anglais', 'Des ouvriers des usines de Paris'],
      e: 'La guerre mobilise aussi les colonies : des soldats africains et asiatiques combattent pour la France.',
    },
  ],
  vf: [
    {
      id: 'duree',
      niv: 'f',
      s: 'La Première Guerre mondiale a duré de 1914 à 1918.',
      v: true,
      e: 'Elle s’arrête avec l’armistice du 11 novembre 1918.',
    },
    {
      id: 'armistice',
      niv: 'f',
      s: 'L’armistice est signé le 11 novembre 1918.',
      v: true,
      e: 'Il met fin aux combats.',
    },
    {
      id: 'poilus',
      niv: 'f',
      s: 'Les soldats français sont surnommés les poilus.',
      v: true,
      e: 'À cause de leur barbe et de leur courage.',
    },
    {
      id: '1939',
      niv: 'f',
      s: 'La Première Guerre mondiale commence en 1939.',
      v: false,
      e: 'Elle commence en 1914 ; 1939 est le début de la Seconde Guerre mondiale.',
    },
    {
      id: 'napoleon',
      niv: 'f',
      s: 'Les poilus sont des soldats de Napoléon.',
      v: false,
      e: 'Ce sont les soldats français de 1914-1918.',
    },
    {
      id: 'sud-ouest',
      niv: 'n',
      s: 'Les principaux combats en France ont lieu dans le sud-ouest.',
      v: false,
      e: 'Ils ont lieu dans le nord et l’est de la France.',
    },
    {
      id: 'usines',
      niv: 'n',
      s: 'Pendant la guerre, des femmes travaillent dans les usines d’armement.',
      v: true,
      e: 'On les appelle les munitionnettes.',
    },
    {
      id: 'verdun',
      niv: 'n',
      s: 'La bataille de Verdun a eu lieu en 1916.',
      v: true,
      e: 'Elle dure de février à décembre 1916.',
    },
    {
      id: 'bilan',
      niv: 'n',
      s: 'Environ 1,4 million de soldats français sont morts au combat.',
      v: true,
      e: 'Sur environ 10 millions de soldats tués.',
    },
    {
      id: 'apres',
      niv: 'n',
      s: 'Après l’armistice, les combats continuent plusieurs années.',
      v: false,
      e: 'L’armistice arrête les combats le 11 novembre 1918.',
    },
    {
      id: 'deux-pays',
      niv: 'p',
      s: 'La guerre de 1914-1918 n’a concerné que la France et l’Allemagne.',
      v: false,
      e: 'Elle a concerné des pays de plusieurs continents.',
    },
    {
      id: 'tranchees',
      niv: 'p',
      s: 'Pendant la guerre de position, les soldats vivent dans des tranchées.',
      v: true,
      e: 'Le front bouge très peu de 1915 à 1917.',
    },
    {
      id: 'colonies',
      niv: 'p',
      s: 'Des soldats venus des colonies ont combattu pour la France.',
      v: true,
      e: 'Par exemple les tirailleurs sénégalais.',
    },
    {
      id: 'fete',
      niv: 'p',
      s: 'Le 11 novembre est la fête nationale, comme le 14 juillet.',
      v: false,
      e: 'Le 11 novembre est un jour de commémoration ; la fête nationale est le 14 juillet.',
    },
  ],
};

const T5: Fiche = {
  lecon: 'CM2.HI26.T5',
  sens: true,
  evts: [
    {
      id: 'debut',
      niv: 'f',
      excl: '1939',
      label: 'Début de la Seconde Guerre mondiale',
      date: 'septembre 1939',
      t: 1939.09,
    },
    {
      id: 'drole',
      niv: 'p',
      excl: '1939',
      label: '« Drôle de guerre » : peu de combats en France',
      date: 'septembre 1939 - mai 1940',
      t: 1939.1,
    },
    {
      id: 'defaite',
      niv: 'n',
      excl: 'juin40',
      label: 'Défaite de l’armée française',
      date: 'juin 1940',
      t: 1940.061,
    },
    {
      id: 'appel',
      niv: 'f',
      excl: 'juin40',
      label: 'Appel du général de Gaulle',
      date: '18 juin 1940',
      t: 1940.0618,
      e: 'Le 18 juin 1940, depuis Londres, le général de Gaulle appelle les Français à continuer le combat.',
    },
    {
      id: 'vichy',
      niv: 'n',
      label: 'Pétain prend le pouvoir : début du régime de Vichy',
      date: 'juillet 1940',
      t: 1940.071,
    },
    {
      id: 'veldhiv',
      niv: 'n',
      label: 'Rafle du Vel d’Hiv',
      date: 'juillet 1942',
      t: 1942.0716,
      e: 'En juillet 1942, la police française arrête plus de 13 000 Juifs à Paris, dont des enfants : c’est la rafle du Vel d’Hiv.',
    },
    {
      id: 'cnr',
      niv: 'p',
      label: 'Jean Moulin réunit le Conseil national de la Résistance',
      date: 'mai 1943',
      t: 1943.0527,
    },
    {
      id: 'debarquement',
      niv: 'f',
      label: 'Débarquement des Alliés en Normandie',
      date: '6 juin 1944',
      t: 1944.0606,
      e: 'Le 6 juin 1944, les Alliés débarquent en Normandie.',
    },
    { id: 'liberation', niv: 'p', label: 'Libération de Paris', date: 'août 1944', t: 1944.0825 },
    {
      id: 'capitulation',
      niv: 'f',
      label: 'Capitulation de l’Allemagne nazie',
      date: '8 mai 1945',
      t: 1945.0508,
      e: 'Le 8 mai 1945, l’Allemagne nazie capitule : la guerre est finie en Europe.',
    },
  ],
  qcm: [
    {
      id: 'appel',
      niv: 'f',
      q: 'Qui lance un appel à la radio le 18 juin 1940 ?',
      r: 'Le général de Gaulle',
      f: ['Philippe Pétain', 'Jules Ferry', 'Napoléon'],
      e: 'Depuis Londres, le général de Gaulle appelle les Français à continuer le combat.',
    },
    {
      id: 'qui-moulin',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Jean Moulin',
      f: ['Charles de Gaulle', 'Philippe Pétain', 'Jules Ferry'],
      hints: [
        'Avant la guerre, j’étais préfet.',
        'Je rejoins le général de Gaulle à Londres.',
        'Je reviens en France en parachute pour unir les résistants.',
        'En 1943, je réunis le Conseil national de la Résistance.',
      ],
      e: 'Jean Moulin a unifié les mouvements de la Résistance intérieure française.',
    },
    {
      id: 'qui-de-gaulle',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Charles de Gaulle',
      f: ['Philippe Pétain', 'Jean Moulin', 'Georges Clemenceau'],
      hints: [
        'Je suis un militaire français.',
        'En juin 1940, je refuse la défaite.',
        'Depuis Londres, je parle aux Français à la radio.',
        'Je dirige la France libre.',
      ],
      e: 'Le général de Gaulle lance l’appel du 18 juin 1940 et dirige la France libre.',
    },
    {
      id: 'qui-petain',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Philippe Pétain',
      f: ['Charles de Gaulle', 'Jean Moulin', 'Georges Clemenceau'],
      hints: [
        'Je suis un maréchal.',
        'J’étais célèbre pour la bataille de Verdun, en 1916.',
        'En juin 1940, je demande l’armistice à l’Allemagne nazie.',
        'Je dirige le régime de Vichy, qui collabore avec l’occupant.',
      ],
      e: 'Philippe Pétain dirige le régime de Vichy, qui collabore avec l’Allemagne nazie.',
    },
    {
      id: 'vichy',
      niv: 'n',
      q: 'Comment appelle-t-on le régime dirigé par Philippe Pétain de 1940 à 1944 ?',
      r: 'Le régime de Vichy',
      f: ['La IIIe République', 'Le Second Empire', 'La France libre'],
      e: 'Le gouvernement de Pétain s’installe à Vichy ; il supprime la République et collabore avec l’occupant.',
    },
    {
      id: 'collaboration',
      niv: 'n',
      q: 'Qu’est-ce que la collaboration ?',
      r: 'L’aide apportée par le régime de Vichy à l’occupant nazi',
      f: ['La lutte contre l’occupant', 'Un traité de paix', 'La fête de la Libération'],
      e: 'Le régime de Vichy a aidé l’Allemagne nazie, notamment en arrêtant des Juifs.',
    },
    {
      id: 'justes',
      niv: 'n',
      q: 'Qui sont les « Justes parmi les Nations » ?',
      r: 'Des personnes qui ont sauvé des Juifs en risquant leur vie',
      f: ['Des juges du régime de Vichy', 'Des soldats allemands', 'Des ministres de Pétain'],
      e: 'Beaucoup de Français ont caché des enfants et des familles juives : ils sont honorés comme Justes.',
    },
    {
      id: 'shoah',
      niv: 'n',
      q: 'Environ combien de Juifs ont été assassinés pendant la Shoah ?',
      r: 'Environ 6 millions',
      f: ['Environ 60 000', 'Environ 600 000', 'Environ 60 millions'],
      e: 'Environ 6 millions de Juifs, soit 60 % des Juifs d’Europe, ont été assassinés par les nazis.',
    },
    {
      id: 'bilan',
      niv: 'n',
      q: 'Combien de morts la Seconde Guerre mondiale a-t-elle faits dans le monde ?',
      r: 'Entre 60 et 70 millions',
      f: ['Environ 1 million', 'Environ 10 000', 'Environ 500 millions'],
      e: 'La Seconde Guerre mondiale a fait entre 60 et 70 millions de morts dans le monde.',
    },
    {
      id: '6-juin',
      niv: 'f',
      q: 'Que se passe-t-il le 6 juin 1944 ?',
      r: 'Le débarquement des Alliés en Normandie',
      f: ['La capitulation de l’Allemagne', 'L’appel du 18 juin', 'L’armistice de 1918'],
      e: 'Le débarquement en Normandie commence la libération de la France.',
    },
    {
      id: '8-mai',
      niv: 'f',
      q: 'Que se passe-t-il le 8 mai 1945 ?',
      r: 'L’Allemagne nazie capitule : la guerre s’arrête en Europe.',
      f: [
        'La guerre commence.',
        'Les Alliés débarquent en Normandie.',
        'Le général de Gaulle lance son appel.',
      ],
      e: 'Le 8 mai est un jour de commémoration de la victoire de 1945.',
    },
    {
      id: 'rationnement',
      niv: 'n',
      q: 'Pendant l’Occupation, à quoi servent les tickets de rationnement ?',
      r: 'À acheter une petite quantité de nourriture',
      f: ['À prendre le train gratuitement', 'À aller au cinéma', 'À partir en vacances'],
      e: 'La nourriture manque : chaque personne n’a droit qu’à une petite quantité.',
    },
    {
      id: 'drole',
      niv: 'p',
      q: 'Comment appelle-t-on la période (1939-1940) où la guerre est déclarée mais où il y a peu de combats en France ?',
      r: 'La « drôle de guerre »',
      f: ['La guerre de position', 'La Libération', 'La guerre éclair'],
      e: 'De septembre 1939 à mai 1940, les armées s’attendent sans vraiment combattre : c’est la « drôle de guerre ».',
    },
  ],
  vf: [
    {
      id: 'duree',
      niv: 'f',
      s: 'La Seconde Guerre mondiale a duré de 1939 à 1945.',
      v: true,
      e: 'Elle s’arrête en Europe le 8 mai 1945.',
    },
    {
      id: 'appel',
      niv: 'f',
      s: 'Le 18 juin 1940, le général de Gaulle appelle à continuer le combat.',
      v: true,
      e: 'Il parle depuis Londres, à la radio.',
    },
    {
      id: 'debarquement',
      niv: 'f',
      s: 'Le débarquement en Normandie a lieu le 8 mai 1945.',
      v: false,
      e: 'Il a lieu le 6 juin 1944 ; le 8 mai 1945 est la fin de la guerre en Europe.',
    },
    {
      id: 'fin',
      niv: 'f',
      s: 'La Seconde Guerre mondiale s’arrête en Europe le 11 novembre 1945.',
      v: false,
      e: 'Elle s’arrête le 8 mai 1945 ; le 11 novembre rappelle la fin de la Première Guerre mondiale (1918).',
    },
    {
      id: 'vichy',
      niv: 'n',
      s: 'Le régime de Vichy, dirigé par Philippe Pétain, a collaboré avec l’occupant nazi.',
      v: true,
      e: 'Il a notamment participé à l’arrestation des Juifs.',
    },
    {
      id: 'veldhiv',
      niv: 'n',
      s: 'La rafle du Vel d’Hiv a eu lieu en 1942.',
      v: true,
      e: 'Elle a lieu à Paris, en juillet 1942.',
    },
    {
      id: 'resistants',
      niv: 'n',
      s: 'Les résistants aidaient l’occupant allemand.',
      v: false,
      e: 'Les résistants luttaient contre l’occupant.',
    },
    {
      id: 'rationnement',
      niv: 'n',
      s: 'Pendant l’Occupation, la nourriture était rationnée.',
      v: true,
      e: 'Il fallait des tickets de rationnement.',
    },
    {
      id: 'shoah',
      niv: 'n',
      s: 'Environ 6 millions de Juifs ont été assassinés pendant la Shoah.',
      v: true,
      e: 'Soit 60 % des Juifs d’Europe.',
    },
    {
      id: 'tsiganes',
      niv: 'p',
      s: 'Les Tsiganes ont aussi été persécutés par les nazis et par le régime de Vichy.',
      v: true,
      e: 'Ils ont été internés dans des camps.',
    },
    {
      id: 'moulin',
      niv: 'p',
      s: 'Jean Moulin a unifié les mouvements de la Résistance.',
      v: true,
      e: 'Il réunit le Conseil national de la Résistance en 1943.',
    },
    {
      id: 'justes',
      niv: 'p',
      s: 'Les « Justes parmi les Nations » ont dénoncé des Juifs.',
      v: false,
      e: 'Au contraire, ils ont sauvé des Juifs en risquant leur vie.',
    },
    {
      id: 'paris',
      niv: 'p',
      s: 'Paris a été libérée en août 1944.',
      v: true,
      e: 'Paris est libérée le 25 août 1944.',
    },
    {
      id: 'drole',
      niv: 'p',
      s: 'Pendant la « drôle de guerre », d’immenses batailles ont lieu en France.',
      v: false,
      e: 'Pendant la « drôle de guerre », il y a très peu de combats.',
    },
  ],
};

const T6: Fiche = {
  lecon: 'CM2.HI26.T6',
  evts: [
    {
      id: 'vote-femmes',
      niv: 'f',
      label: 'Droit de vote des femmes',
      date: '1944',
      t: 1944.04,
      e: 'En 1944, les Françaises obtiennent le droit de vote.',
    },
    { id: 'secu', niv: 'n', label: 'Création de la Sécurité sociale', date: '1945', t: 1945.1 },
    {
      id: 'rome',
      niv: 'n',
      label: 'Traité de Rome créant la CEE',
      date: '1957',
      t: 1957.03,
      e: 'En 1957, le traité de Rome crée la Communauté économique européenne (CEE).',
    },
    {
      id: 've',
      niv: 'f',
      label: 'Fondation de la Ve République avec le général de Gaulle',
      date: '1958',
      t: 1958.1,
      e: 'En 1958, la Ve République est fondée avec le général de Gaulle.',
    },
    {
      id: 'femmes-1965',
      niv: 'n',
      label:
        'Les Françaises peuvent travailler et ouvrir un compte bancaire sans l’autorisation de leur mari',
      date: '1965',
      t: 1965.07,
      e: 'Depuis 1965, une femme mariée peut travailler et ouvrir un compte bancaire sans l’autorisation de son mari.',
    },
    { id: 'majorite', niv: 'p', label: 'Majorité et droit de vote à 18 ans', date: '1974', t: 1974.07 },
    { id: 'tgv', niv: 'p', label: 'Premier TGV entre Paris et Lyon', date: '1981', t: 1981.09 },
    { id: 'maastricht', niv: 'p', label: 'Traité de Maastricht', date: '1992', t: 1992.02 },
    {
      id: 'euro',
      niv: 'n',
      label: 'L’euro remplace le franc',
      date: '2000 — pièces et billets en 2002',
      t: 2000,
      e: 'Le programme retient « 2000 : l’euro remplace le franc » ; les pièces et les billets arrivent le 1er janvier 2002.',
    },
  ],
  qcm: [
    {
      id: 'secu',
      niv: 'n',
      q: 'Qu’est-ce que la Sécurité sociale ?',
      r: 'Un système qui aide à payer les soins quand on est malade',
      f: ['Une police de sécurité', 'Une banque pour les riches', 'Une armée'],
      e: 'Créée en 1945, la Sécurité sociale aide à payer les soins, les retraites et soutient les familles.',
    },
    {
      id: 've',
      niv: 'f',
      q: 'Qui fonde la Ve République en 1958 ?',
      r: 'Le général de Gaulle',
      f: ['Jules Ferry', 'Napoléon III', 'Louis XVI'],
      e: 'Le général de Gaulle fonde la Ve République en 1958 ; il en est le premier président.',
    },
    {
      id: 'qui-de-gaulle',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Charles de Gaulle',
      f: ['Jules Ferry', 'Jean Jaurès', 'Georges Pompidou'],
      hints: [
        'Je suis un militaire devenu chef de l’État.',
        'J’ai dirigé la France libre.',
        'En 1958, je fonde la Ve République.',
        'Je suis le premier président de la Ve République.',
      ],
      e: 'Charles de Gaulle a fondé la Ve République en 1958.',
    },
    {
      id: '1965',
      niv: 'n',
      q: 'Que change la loi de 1965 pour les femmes mariées ?',
      r: 'Elles peuvent travailler et ouvrir un compte bancaire sans l’autorisation de leur mari.',
      f: [
        'Elles obtiennent le droit de vote.',
        'Elles peuvent enfin aller à l’école.',
        'Elles doivent arrêter de travailler.',
      ],
      e: 'C’est une étape importante vers l’égalité entre les femmes et les hommes.',
    },
    {
      id: 'rome',
      niv: 'n',
      q: 'Quel traité crée la CEE en 1957 ?',
      r: 'Le traité de Rome',
      f: ['Le traité de Versailles', 'Le traité de Maastricht', 'Le traité de Paris'],
      e: 'Le traité de Rome crée la Communauté économique européenne avec six pays.',
    },
    {
      id: 'consommation',
      niv: 'p',
      q: 'Qu’appelle-t-on la « société de consommation » ?',
      r: 'Une société où l’on achète beaucoup de produits : voitures, télévisions, appareils ménagers',
      f: [
        'Une société où l’on ne mange que des conserves',
        'Une société sans magasins',
        'Une société où tout est gratuit',
      ],
      e: 'Après 1945, beaucoup de familles achètent une voiture, une télévision, un réfrigérateur…',
    },
    {
      id: 'tele',
      niv: 'n',
      q: 'Quel objet entre dans la plupart des foyers français dans les années 1960-1970 ?',
      r: 'La télévision',
      f: ['Le smartphone', 'La tablette numérique', 'Le casque de réalité virtuelle'],
      e: 'La télévision se répand dans les années 1960-1970 ; smartphones et tablettes arrivent bien plus tard.',
    },
    {
      id: 'paix',
      niv: 'p',
      sens: true,
      q: 'Pourquoi la paix dure-t-elle entre les pays d’Europe de l’Ouest depuis 1945 ?',
      r: 'Parce qu’ils coopèrent au lieu de se faire la guerre',
      f: [
        'Parce qu’ils n’ont plus d’armée',
        'Parce qu’ils ont un seul roi',
        'Parce qu’ils ne se parlent plus',
      ],
      e: 'La construction européenne relie les pays entre eux et aide à garder la paix.',
    },
    {
      id: '1974',
      niv: 'p',
      q: 'Que permet la loi de 1974 ?',
      r: 'Voter dès 18 ans',
      f: ['Voter dès 12 ans', 'Conduire dès 14 ans', 'Quitter l’école à 10 ans'],
      e: 'En 1974, l’âge de la majorité passe de 21 à 18 ans.',
    },
    {
      id: 'vote',
      niv: 'f',
      q: 'Qui peut voter en France depuis 1944 ?',
      r: 'Les hommes et les femmes',
      f: ['Seulement les hommes', 'Seulement les femmes', 'Seulement les maires'],
      e: 'Depuis 1944, les femmes ont, elles aussi, le droit de vote.',
    },
    {
      id: 'franc',
      niv: 'f',
      q: 'Avant l’euro, quelle était la monnaie de la France ?',
      r: 'Le franc',
      f: ['Le dollar', 'La livre', 'Le yen'],
      e: 'L’euro a remplacé le franc : pièces et billets en euros depuis 2002.',
    },
    {
      id: 'euro',
      niv: 'n',
      q: 'Quelle monnaie remplace le franc au début des années 2000 ?',
      r: 'L’euro',
      f: ['Le dollar', 'La livre', 'Le mark'],
      e: 'Le programme retient « 2000 : l’euro remplace le franc » ; les pièces et les billets arrivent en 2002.',
    },
    {
      id: 'euro-2002',
      niv: 'p',
      q: 'En quelle année les pièces et les billets en euros arrivent-ils dans les porte-monnaie ?',
      r: '2002',
      f: ['1992', '1999', '2010'],
      e: 'L’euro existe pour les banques depuis 1999 (le programme retient 2000) ; les pièces et les billets arrivent le 1er janvier 2002.',
    },
  ],
  vf: [
    {
      id: 'femmes',
      niv: 'f',
      s: 'Les femmes votent en France depuis 1944.',
      v: true,
      e: 'Elles ont obtenu le droit de vote en 1944.',
    },
    {
      id: 've',
      niv: 'f',
      s: 'La Ve République a été fondée en 1958 avec le général de Gaulle.',
      v: true,
      e: 'C’est la République dans laquelle nous vivons.',
    },
    {
      id: 'dollar',
      niv: 'f',
      s: 'L’euro a remplacé le dollar en France.',
      v: false,
      e: 'L’euro a remplacé le franc.',
    },
    {
      id: 'napoleon',
      niv: 'f',
      s: 'La Ve République a été fondée par Napoléon.',
      v: false,
      e: 'Elle a été fondée en 1958 avec le général de Gaulle.',
    },
    {
      id: 'secu',
      niv: 'n',
      s: 'La Sécurité sociale aide à payer les soins des malades.',
      v: true,
      e: 'Elle est créée en 1945.',
    },
    {
      id: '1965',
      niv: 'n',
      s: 'Avant 1965, une femme mariée devait avoir l’autorisation de son mari pour travailler.',
      v: true,
      e: 'La loi de 1965 supprime cette obligation.',
    },
    {
      id: 'rome',
      niv: 'n',
      s: 'Le traité de Rome de 1957 a créé la CEE.',
      v: true,
      e: 'La Communauté économique européenne.',
    },
    {
      id: 'vie',
      niv: 'n',
      s: 'Depuis 1945, la vie quotidienne a très peu changé en France.',
      v: false,
      e: 'Elle a beaucoup changé : voitures, électroménager, télévision, puis Internet…',
    },
    {
      id: 'objets',
      niv: 'n',
      s: 'Après 1945, beaucoup de familles achètent une voiture, un réfrigérateur et une télévision.',
      v: true,
      e: 'C’est la société de consommation.',
    },
    {
      id: 'droits',
      niv: 'n',
      s: 'Après 1945, les femmes n’obtiennent aucun droit nouveau.',
      v: false,
      e: 'Faux : en 1945, les Françaises votent pour la première fois (droit obtenu en 1944) ; en 1965, elles peuvent travailler et ouvrir un compte bancaire sans l’autorisation de leur mari.',
    },
    {
      id: 'tgv',
      niv: 'p',
      s: 'Le TGV a été mis en service en 1981 entre Paris et Lyon.',
      v: true,
      e: 'C’est un symbole des transports modernes.',
    },
    {
      id: '1974',
      niv: 'p',
      s: 'En 1974, l’âge du droit de vote passe de 21 à 18 ans.',
      v: true,
      e: 'Les jeunes de 18 ans deviennent majeurs.',
    },
    {
      id: '2002',
      niv: 'p',
      s: 'Les pièces et les billets en euros sont arrivés en 2002.',
      v: true,
      e: 'Le 1er janvier 2002.',
    },
    {
      id: 'maastricht',
      niv: 'p',
      s: 'Le traité de Maastricht date de 1957.',
      v: false,
      e: 'Il date de 1992 ; 1957 est le traité de Rome.',
    },
  ],
};

export const HISTOIRE_2026: Fiche[] = [T1, T2, T3, T4, T5, T6];
