/**
 * Histoire CM2 — programme 2020 (BO n°31 du 30/07/2020, en vigueur en 2026-2027) et rappel du CM1.
 * Repères vérifiés dans les fiches Éduscol CM2 (`resources/eduscol/cm2_hist2020_*.pdf`) :
 * thème 1 « 1880 : 14 juillet, fête nationale ; 1881-1882 : lois Ferry ; 1905 ; 1944 » ;
 * thème 2 « après 1830 : essor de l'industrialisation ; 1931 : population majoritairement urbaine » ;
 * thème 3 « 1914-1918 ; 1939-1945 ; 1951 ; 1957 ; 1992 », l'euro fiduciaire en 2002.
 * Les QCM « simples » complémentaires sont dans `data/histoire/cm2_questions.json`.
 */
import type { Fiche } from './outils';

/* ------------------------------------------------------------------ */
/* Rappel du CM1 : 1789, la Révolution française                       */
/* ------------------------------------------------------------------ */

const REVOLUTION: Fiche = {
  lecon: 'CM2.HI.RAPPEL_CM1.REVOLUTION',
  evts: [
    {
      id: 'etats',
      niv: 'n',
      label: 'Réunion des États généraux à Versailles',
      date: '5 mai 1789',
      t: 1789.0505,
      e: 'Le 5 mai 1789, Louis XVI réunit à Versailles les députés des trois ordres : ce sont les États généraux.',
    },
    { id: 'jeu-paume', niv: 'p', label: 'Serment du Jeu de paume', date: '20 juin 1789', t: 1789.062 },
    {
      id: 'bastille',
      niv: 'f',
      label: 'Prise de la Bastille',
      date: '14 juillet 1789',
      t: 1789.0714,
      e: 'Le 14 juillet 1789, les Parisiens prennent la Bastille, une prison qui symbolise le pouvoir absolu du roi.',
    },
    {
      id: 'privileges',
      niv: 'n',
      label: 'Abolition des privilèges',
      date: '4 août 1789',
      t: 1789.0804,
      e: 'Dans la nuit du 4 août 1789, les députés suppriment les privilèges de la noblesse et du clergé.',
    },
    {
      id: 'ddhc',
      niv: 'n',
      label: 'Déclaration des droits de l’homme et du citoyen',
      date: '26 août 1789',
      t: 1789.0826,
      e: 'Le 26 août 1789, la Déclaration affirme que les hommes naissent libres et égaux en droits.',
    },
    { id: 'versailles', niv: 'p', label: 'Marche des femmes sur Versailles', date: '5-6 octobre 1789', t: 1789.1005 },
    {
      id: 'republique',
      niv: 'f',
      label: 'Proclamation de la Ire République',
      date: 'septembre 1792',
      t: 1792.0921,
      e: 'En septembre 1792, la monarchie est abolie et la République est proclamée.',
    },
    {
      id: 'louis16',
      niv: 'p',
      sens: true,
      label: 'Exécution de Louis XVI',
      date: 'janvier 1793',
      t: 1793.0121,
      e: 'Louis XVI est jugé et exécuté en janvier 1793.',
    },
    {
      id: 'sacre',
      niv: 'n',
      label: 'Sacre de Napoléon Ier',
      date: '2 décembre 1804',
      t: 1804.1202,
      e: 'Le 2 décembre 1804, Napoléon Bonaparte est sacré empereur des Français.',
    },
  ],
  qcm: [
    {
      id: 'qui-louis16',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'Louis XVI',
      f: ['Napoléon Ier', 'Louis XIV', 'Henri IV'],
      hints: [
        'Je suis né à Versailles en 1754.',
        'Mon épouse s’appelle Marie-Antoinette.',
        'En 1789, je réunis les États généraux.',
        'Je suis le roi de France au début de la Révolution.',
      ],
      img: '👑',
      e: 'Louis XVI est le roi de France quand la Révolution commence, en 1789.',
    },
    {
      id: 'qui-gouges',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Olympe de Gouges',
      f: ['Marie-Antoinette', 'Joséphine de Beauharnais', 'Marie Curie'],
      hints: [
        'Je suis une femme de lettres du XVIIIe siècle.',
        'J’écris des pièces de théâtre et des textes politiques.',
        'Je trouve injuste que les femmes soient oubliées par la Révolution.',
        'En 1791, j’écris la Déclaration des droits de la femme et de la citoyenne.',
      ],
      img: '✒️',
      e: 'Olympe de Gouges réclame les mêmes droits pour les femmes et pour les hommes.',
    },
    {
      id: 'qui-bonaparte',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Napoléon Bonaparte',
      f: ['Louis XVI', 'La Fayette', 'Robespierre'],
      hints: [
        'Je suis né en Corse en 1769.',
        'Je deviens un général célèbre pendant la Révolution.',
        'En 1799, je prends le pouvoir.',
        'En 1804, je suis sacré empereur des Français.',
      ],
      img: '🎖️',
      e: 'Napoléon Bonaparte prend le pouvoir en 1799 et devient empereur en 1804.',
    },
    {
      id: 'absolue',
      niv: 'n',
      q: 'Avant 1789, comment s’appelle le régime où le roi a tous les pouvoirs ?',
      r: 'La monarchie absolue',
      f: ['La République', 'La démocratie', 'L’Empire'],
      e: 'Avant 1789, le roi décide de tout : c’est la monarchie absolue.',
    },
    {
      id: 'impots',
      niv: 'n',
      q: 'Avant 1789, quel ordre paie presque tous les impôts ?',
      r: 'Le tiers état',
      f: ['La noblesse', 'Le clergé', 'La famille royale'],
      e: 'La noblesse et le clergé ont des privilèges : c’est le tiers état qui paie presque tous les impôts.',
    },
    {
      id: 'article1',
      niv: 'p',
      q: 'Que dit l’article 1 de la Déclaration des droits de l’homme et du citoyen ?',
      r: 'Les hommes naissent et demeurent libres et égaux en droits.',
      f: [
        'Le roi a tous les pouvoirs.',
        'Les nobles ne paient pas d’impôts.',
        'Chacun doit obéir à son seigneur.',
      ],
      e: 'L’article 1 dit : « Les hommes naissent et demeurent libres et égaux en droits. »',
    },
    {
      id: 'bastille-pourquoi',
      niv: 'p',
      q: 'Pourquoi la prise de la Bastille est-elle devenue un symbole ?',
      r: 'C’était une prison qui représentait le pouvoir absolu du roi.',
      f: ['C’était le palais du roi.', 'C’était la plus grande église de Paris.', 'C’était une école.'],
      e: 'Le roi pouvait y enfermer des gens sans jugement : en la prenant, le peuple s’attaque au pouvoir absolu.',
    },
    {
      id: 'lumieres',
      niv: 'n',
      q: 'Lequel de ces hommes est un philosophe des Lumières ?',
      r: 'Voltaire',
      f: ['Jules Ferry', 'Louis Pasteur', 'Charlemagne'],
      e: 'Voltaire, Rousseau, Montesquieu et Diderot sont des philosophes des Lumières : ils défendent la raison et la liberté.',
    },
  ],
  vf: [
    { id: 'bastille', niv: 'f', s: 'La prise de la Bastille a lieu le 14 juillet 1789.', v: true, e: 'Oui : le 14 juillet 1789, les Parisiens prennent la Bastille.' },
    { id: 'impots', niv: 'f', s: 'Avant 1789, la noblesse payait la plupart des impôts.', v: false, e: 'C’est le tiers état qui payait la plupart des impôts ; la noblesse et le clergé avaient des privilèges.' },
    { id: 'ddhc', niv: 'n', s: 'La Déclaration de 1789 dit que les hommes naissent libres et égaux en droits.', v: true, e: 'C’est l’article 1 de la Déclaration des droits de l’homme et du citoyen.' },
    { id: 'empereur', niv: 'f', s: 'Louis XVI était un empereur.', v: false, e: 'Louis XVI était le roi de France. Napoléon Ier, lui, sera empereur.' },
    { id: 'privileges', niv: 'n', s: 'Dans la nuit du 4 août 1789, les députés abolissent les privilèges.', v: true, e: 'La nuit du 4 août 1789 met fin aux privilèges de la noblesse et du clergé.' },
    { id: 'republique', niv: 'n', s: 'La République est proclamée en 1789.', v: false, e: 'La République est proclamée en septembre 1792, trois ans après le début de la Révolution.' },
    { id: 'doleances', niv: 'n', s: 'Les cahiers de doléances contiennent les plaintes et les souhaits des Français.', v: true, e: 'Au printemps 1789, les Français écrivent leurs plaintes dans les cahiers de doléances.' },
    { id: 'femmes', niv: 'p', s: 'Les femmes de Paris marchent sur Versailles en octobre 1789.', v: true, e: 'Les 5 et 6 octobre 1789, des femmes de Paris marchent sur Versailles et ramènent le roi à Paris.' },
    { id: 'serment', niv: 'p', s: 'Le serment du Jeu de paume a été prêté par des paysans.', v: false, e: 'Ce sont les députés du tiers état qui prêtent le serment du Jeu de paume, le 20 juin 1789.' },
    { id: 'empire', niv: 'p', s: 'Napoléon Bonaparte devient empereur en 1804.', v: true, e: 'Napoléon Bonaparte est sacré empereur le 2 décembre 1804.' },
    { id: 'auteur', niv: 'p', s: 'La Déclaration des droits de l’homme a été écrite par Napoléon.', v: false, e: 'La Déclaration est votée par les députés de l’Assemblée nationale en août 1789.' },
  ],
  paires: [
    {
      id: 'personnages',
      niv: 'n',
      prompt: 'Associe chaque personnage à ce qu’il a fait.',
      relation: 'personnage → action',
      pairs: [
        ['Louis XVI', 'roi de France en 1789'],
        ['Olympe de Gouges', 'défend les droits des femmes'],
        ['Rouget de Lisle', 'compose La Marseillaise'],
        ['Napoléon Bonaparte', 'devient empereur en 1804'],
        ['Voltaire', 'philosophe des Lumières'],
      ],
      e: 'Louis XVI est roi, Olympe de Gouges défend les femmes, Rouget de Lisle compose La Marseillaise, Napoléon devient empereur, Voltaire est un philosophe.',
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Thème 1 — Le temps de la République                                 */
/* ------------------------------------------------------------------ */

const PAIRES_SYMBOLES = {
  prompt: 'Associe chaque symbole de la République à ce qu’il est.',
  relation: 'symbole → définition',
  pairs: [
    ['Marianne', 'la femme qui représente la République'],
    ['La Marseillaise', 'l’hymne national'],
    ['Le 14 Juillet', 'la fête nationale'],
    ['Bleu, blanc, rouge', 'les couleurs du drapeau'],
    ['Liberté, Égalité, Fraternité', 'la devise'],
  ] as [string, string][],
  e: 'Marianne, La Marseillaise, le 14 Juillet, le drapeau tricolore et la devise sont les symboles de la République.',
};

const REPUBLIQUE100: Fiche = {
  lecon: 'CM2.HI20.T1.REPUBLIQUE100',
  evts: [
    { id: 'rep1', niv: 'f', label: 'Proclamation de la Ire République', date: 'septembre 1792', t: 1792.09 },
    { id: 'rep2', niv: 'n', label: 'Naissance de la IIe République', date: '1848', t: 1848.02 },
    { id: 'rep3', niv: 'f', label: 'Naissance de la IIIe République', date: '1870', t: 1870.09 },
    { id: 'hymne', niv: 'p', label: 'La Marseillaise devient l’hymne national', date: '1879', t: 1879.02 },
    {
      id: 'fete',
      niv: 'n',
      label: 'Le 14 Juillet devient la fête nationale',
      date: '1880',
      t: 1880.07,
      e: 'Depuis la loi de 1880, le 14 Juillet est la fête nationale.',
    },
    {
      id: 'centenaire',
      niv: 'f',
      label: 'La République fête ses 100 ans',
      date: '1892',
      t: 1892.09,
      e: 'En 1892, on fête les 100 ans de la proclamation de la République (1792).',
    },
    { id: 'rep5', niv: 'n', label: 'Naissance de la Ve République', date: '1958', t: 1958.1 },
  ],
  qcm: [
    {
      id: 'qui-marianne',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Marianne',
      f: ['Jeanne d’Arc', 'Marie-Antoinette', 'Olympe de Gouges'],
      hints: [
        'Je suis une femme, mais je n’ai jamais existé.',
        'Je porte souvent un bonnet phrygien, symbole de liberté.',
        'Mon buste se trouve dans les mairies.',
        'On me voit sur des timbres et sur des pièces de monnaie.',
        'Je représente la République française.',
      ],
      img: '🇫🇷',
      e: 'Marianne est le symbole de la République ; son buste est dans les mairies.',
    },
    {
      id: 'qui-marseillaise',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'La Marseillaise',
      f: ['Le Chant du départ', 'La Carmagnole', 'L’Hymne à la joie'],
      hints: [
        'J’ai été écrite à Strasbourg en 1792.',
        'Mon auteur s’appelle Rouget de Lisle.',
        'Des soldats venus de Marseille m’ont chantée en arrivant à Paris.',
        'On me chante avant les matchs de l’équipe de France.',
        'Je suis l’hymne national.',
      ],
      img: '🎶',
      e: 'La Marseillaise, composée en 1792 par Rouget de Lisle, est l’hymne national.',
    },
    {
      id: 'devise',
      niv: 'f',
      q: 'Quelle est la devise de la République française ?',
      r: 'Liberté, Égalité, Fraternité',
      f: ['Paix, Joie, Amitié', 'Un pour tous, tous pour un', 'Honneur et Courage'],
      e: 'La devise de la République est « Liberté, Égalité, Fraternité ».',
    },
    {
      id: 'mairie',
      niv: 'f',
      q: 'Dans quel bâtiment de la commune trouve-t-on le buste de Marianne ?',
      r: 'À la mairie',
      f: ['À la boulangerie', 'À la gare', 'Au stade'],
      e: 'Le buste de Marianne est placé dans la salle du conseil ou la salle des mariages des mairies.',
    },
    {
      id: '14juillet',
      niv: 'n',
      q: 'Le 14 Juillet rappelle un événement de 1789. Lequel ?',
      r: 'La prise de la Bastille',
      f: ['Le sacre de Napoléon', 'L’armistice de 1918', 'Les lois Ferry'],
      e: 'La fête nationale rappelle la prise de la Bastille (1789) et la fête de la Fédération (1790).',
    },
    {
      id: 'centenaire-pourquoi',
      niv: 'p',
      q: 'Pourquoi la République fête-t-elle ses 100 ans en 1892 ?',
      r: 'Parce qu’elle a été proclamée en 1792.',
      f: [
        'Parce que le roi est revenu en 1892.',
        'Parce que la tour Eiffel vient d’être construite.',
        'Parce que l’école devient obligatoire en 1892.',
      ],
      e: 'De 1792 à 1892, il s’est écoulé 100 ans : c’est le centenaire de la République.',
    },
    {
      id: 'republique',
      niv: 'n',
      q: 'Qu’est-ce qu’une république ?',
      r: 'Un régime où les citoyens élisent leurs dirigeants',
      f: ['Un pays gouverné par un roi', 'Un pays gouverné par un empereur', 'Un pays sans aucune loi'],
      e: 'Dans une république, le pouvoir vient des citoyens, qui votent pour choisir leurs représentants.',
    },
    {
      id: 'coq',
      niv: 'p',
      q: 'Quel animal représente souvent la France, sans être un symbole officiel ?',
      r: 'Le coq',
      f: ['Le lion', 'L’aigle', 'L’ours'],
      e: 'Le coq gaulois est un emblème populaire de la France, par exemple sur les maillots des sportifs.',
    },
  ],
  vf: [
    { id: 'marianne', niv: 'f', s: 'Marianne est le symbole de la République française.', v: true, e: 'Marianne représente la République ; son buste est dans les mairies.' },
    { id: 'fete', niv: 'n', s: 'Le 14 Juillet est la fête nationale depuis 1880.', v: true, e: 'C’est une loi de 1880 qui fait du 14 Juillet la fête nationale.' },
    { id: 'devise', niv: 'f', s: 'La devise de la République est « Liberté, Égalité, Fraternité ».', v: true, e: 'Elle est écrite sur la façade des mairies et des écoles.' },
    { id: 'drapeau', niv: 'f', s: 'Le drapeau français est bleu, blanc et vert.', v: false, e: 'Le drapeau français est bleu, blanc et rouge.' },
    { id: 'marseillaise', niv: 'n', s: 'La Marseillaise a été composée en 1792.', v: true, e: 'Rouget de Lisle la compose en avril 1792.' },
    { id: 'monarchie', niv: 'n', s: 'En 1892, la France fête les 100 ans de la monarchie.', v: false, e: 'En 1892, la France fête les 100 ans de la République, proclamée en 1792.' },
    { id: 'rep3', niv: 'p', s: 'La IIIe République commence en 1870.', v: true, e: 'La IIIe République est proclamée en septembre 1870.' },
    { id: 'roi', niv: 'n', s: 'Dans une république, le chef de l’État est un roi.', v: false, e: 'Dans une république, il n’y a pas de roi : les citoyens élisent leurs dirigeants.' },
    { id: 'bonnet', niv: 'p', s: 'Le bonnet phrygien de Marianne est un symbole de liberté.', v: true, e: 'Pendant la Révolution, le bonnet phrygien est devenu un symbole de liberté.' },
    { id: 'auteur', niv: 'p', s: 'La Marseillaise a été écrite par Napoléon.', v: false, e: 'La Marseillaise a été écrite par Rouget de Lisle en 1792.' },
  ],
  paires: [{ id: 'symboles', niv: 'f', ...PAIRES_SYMBOLES }],
};

const FERRY: Fiche = {
  lecon: 'CM2.HI20.T1.FERRY',
  evts: [
    { id: 'revolution', niv: 'f', label: 'Début de la Révolution française', date: '1789', t: 1789 },
    { id: 'guizot', niv: 'p', label: 'Loi Guizot : une école de garçons dans chaque commune', date: '1833', t: 1833 },
    { id: 'rep3', niv: 'n', label: 'Naissance de la IIIe République', date: '1870', t: 1870.09 },
    {
      id: 'ferry',
      niv: 'f',
      excl: 'ferry',
      label: 'Lois Ferry : l’école devient gratuite, laïque et obligatoire',
      date: '1881-1882',
      t: 1881.5,
    },
    {
      id: 'gratuite',
      niv: 'p',
      excl: 'ferry',
      label: 'Loi rendant l’école primaire publique gratuite',
      date: 'juin 1881',
      t: 1881.0616,
      e: 'La loi du 16 juin 1881 rend l’école primaire publique gratuite.',
    },
    {
      id: 'obligatoire',
      niv: 'n',
      excl: 'ferry',
      label: 'Loi rendant l’école obligatoire et laïque',
      date: 'mars 1882',
      t: 1882.0328,
      e: 'La loi du 28 mars 1882 rend l’école obligatoire de 6 à 13 ans et laïque.',
    },
    { id: 'goblet', niv: 'p', label: 'Loi Goblet : les maîtres des écoles publiques sont tous laïcs', date: '1886', t: 1886.1 },
    { id: 'separation', niv: 'n', label: 'Loi de séparation des Églises et de l’État', date: '1905', t: 1905.12 },
    { id: 'vote-femmes', niv: 'f', label: 'Droit de vote des femmes', date: '1944', t: 1944.04 },
    { id: 'seize', niv: 'p', label: 'L’école devient obligatoire jusqu’à 16 ans', date: '1959', t: 1959.01 },
  ],
  qcm: [
    {
      id: 'qui-ferry',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Jules Ferry',
      f: ['Victor Hugo', 'Louis Pasteur', 'Napoléon Ier'],
      hints: [
        'J’ai vécu au XIXe siècle et j’ai été ministre.',
        'Je suis un homme politique de la IIIe République.',
        'Des lois portent mon nom, en 1881 et en 1882.',
        'Grâce à moi, l’école primaire devient gratuite, laïque et obligatoire.',
        'Beaucoup d’écoles en France portent mon nom.',
      ],
      img: '🏫',
      e: 'Jules Ferry a fait voter les lois de 1881-1882 : l’école primaire devient gratuite, laïque et obligatoire.',
    },
    {
      id: 'laique',
      niv: 'n',
      q: 'Que veut dire « l’école publique est laïque » ?',
      r: 'Elle est neutre : on n’y enseigne aucune religion.',
      f: ['On y apprend une religion obligatoire.', 'Elle est payante.', 'Elle est réservée aux garçons.'],
      e: 'L’école laïque respecte toutes les croyances : on n’y enseigne pas de religion.',
    },
    {
      id: 'hussards',
      niv: 'p',
      q: 'Comment surnommait-on les instituteurs de la IIIe République ?',
      r: 'Les hussards noirs de la République',
      f: ['Les poilus', 'Les sans-culottes', 'Les grognards'],
      e: 'On les appelait ainsi à cause de leur tenue sombre et de leur mission : instruire tous les enfants.',
    },
    {
      id: 'plume',
      niv: 'f',
      q: 'Avec quoi les élèves écrivaient-ils à l’école de Jules Ferry ?',
      r: 'Avec un porte-plume trempé dans l’encrier',
      f: ['Avec un stylo à bille', 'Avec un ordinateur', 'Avec une tablette numérique'],
      e: 'Les élèves écrivaient à l’encre, avec une plume qu’ils trempaient dans l’encrier de leur pupitre.',
    },
    {
      id: 'morale',
      niv: 'p',
      q: 'Quelle matière remplace l’instruction religieuse à l’école publique en 1882 ?',
      r: 'L’instruction morale et civique',
      f: ['Le latin', 'L’informatique', 'L’anglais'],
      e: 'Avec la loi de 1882, l’instruction religieuse devient l’instruction morale et civique.',
    },
    {
      id: 'pourquoi',
      niv: 'p',
      q: 'Pourquoi la République veut-elle que tous les enfants aillent à l’école ?',
      r: 'Pour former des citoyens instruits, capables de lire, d’écrire et de voter',
      f: [
        'Pour qu’ils deviennent tous soldats',
        'Pour qu’ils apprennent à obéir au roi',
        'Pour qu’ils travaillent plus tôt à l’usine',
      ],
      e: 'Pour Jules Ferry, un citoyen doit savoir lire et écrire pour comprendre les lois et voter.',
    },
    {
      id: 'age',
      niv: 'n',
      q: 'Avec les lois Ferry, jusqu’à quel âge l’école est-elle obligatoire ?',
      r: '13 ans',
      f: ['8 ans', '18 ans', '16 ans'],
      e: 'La loi de 1882 rend l’instruction obligatoire de 6 à 13 ans.',
    },
  ],
  vf: [
    { id: 'gratuite', niv: 'f', s: 'Avec les lois Ferry, l’école primaire publique devient gratuite.', v: true, e: 'La loi de 1881 rend l’école primaire publique gratuite.' },
    { id: 'avant', niv: 'f', s: 'Avant les lois Ferry, tous les enfants allaient à l’école.', v: false, e: 'Avant 1882, beaucoup d’enfants n’allaient pas à l’école ou y allaient peu, surtout à la campagne.' },
    { id: 'ferry', niv: 'f', s: 'Jules Ferry a fait voter des lois sur l’école.', v: true, e: 'Les lois Ferry de 1881 et 1882 organisent l’école primaire.' },
    { id: 'age', niv: 'n', s: 'Avec les lois Ferry, l’école devient obligatoire de 6 à 13 ans.', v: true, e: 'C’est la loi du 28 mars 1882.' },
    { id: 'stylo', niv: 'f', s: 'À l’école de Jules Ferry, les élèves écrivaient avec un stylo à bille.', v: false, e: 'Ils écrivaient avec un porte-plume trempé dans l’encre.' },
    { id: 'religion', niv: 'n', s: 'L’école publique laïque n’enseigne aucune religion.', v: true, e: 'L’école laïque est neutre et respecte toutes les croyances.' },
    { id: '1905', niv: 'n', s: 'Les lois Ferry datent de 1905.', v: false, e: 'Les lois Ferry datent de 1881-1882 ; 1905 est la loi de séparation des Églises et de l’État.' },
    { id: 'certificat', niv: 'p', s: 'Le certificat d’études récompensait les élèves à la fin de l’école primaire.', v: true, e: 'Le certificat d’études primaires était un examen passé vers 12 ans.' },
    { id: 'hussards', niv: 'p', s: 'Les instituteurs étaient surnommés les « hussards noirs de la République ».', v: true, e: 'On les appelait ainsi à cause de leur tenue sombre.' },
    { id: 'roi', niv: 'f', s: 'Jules Ferry était un roi de France.', v: false, e: 'Jules Ferry était un ministre de la IIIe République.' },
    { id: 'separees', niv: 'p', s: 'À l’école de Jules Ferry, filles et garçons étaient le plus souvent dans des classes séparées.', v: true, e: 'L’école mixte ne se généralise qu’au XXe siècle.' },
    { id: 'payante', niv: 'p', s: 'Les lois Ferry ont rendu l’école payante pour les familles riches.', v: false, e: 'L’école primaire publique devient gratuite pour tous.' },
    { id: '18ans', niv: 'p', s: 'L’école de Jules Ferry accueillait obligatoirement les enfants jusqu’à 18 ans.', v: false, e: 'L’obligation allait de 6 à 13 ans.' },
  ],
};

const CITOYENS: Fiche = {
  lecon: 'CM2.HI20.T1.CITOYENS',
  evts: [
    {
      id: 'suffrage',
      niv: 'f',
      excl: '1848',
      label: 'Suffrage universel masculin : tous les hommes peuvent voter',
      date: '1848',
      t: 1848.03,
      e: 'En 1848, tous les hommes de 21 ans et plus obtiennent le droit de vote.',
    },
    {
      id: 'abolition',
      niv: 'n',
      sens: true,
      excl: '1848',
      label: 'Abolition définitive de l’esclavage dans les colonies',
      date: 'avril 1848',
      t: 1848.04,
      e: 'En 1848, grâce à Victor Schœlcher, l’esclavage est définitivement aboli dans les colonies françaises.',
    },
    { id: 'ferry', niv: 'n', label: 'Lois Ferry sur l’école', date: '1881-1882', t: 1881.5 },
    { id: 'syndicats', niv: 'p', label: 'Loi sur la liberté syndicale', date: '1884', t: 1884.03 },
    {
      id: 'separation',
      niv: 'f',
      label: 'Loi de séparation des Églises et de l’État',
      date: '1905',
      t: 1905.12,
      e: 'La loi de 1905 sépare les Églises et l’État : chacun est libre de croire ou de ne pas croire.',
    },
    {
      id: 'vote-femmes',
      niv: 'f',
      label: 'Droit de vote des femmes',
      date: '1944',
      t: 1944.04,
      e: 'En 1944, les femmes obtiennent le droit de vote ; elles votent pour la première fois en 1945.',
    },
    { id: 'premier-vote', niv: 'p', label: 'Premier vote des Françaises', date: '1945', t: 1945.04 },
    {
      id: 've',
      niv: 'n',
      label: 'Fondation de la Ve République',
      date: '1958',
      t: 1958.1,
      e: 'La Ve République est fondée en 1958 avec le général de Gaulle.',
    },
    {
      id: 'majorite',
      niv: 'n',
      label: 'Droit de vote à 18 ans',
      date: '1974',
      t: 1974.07,
      e: 'Depuis 1974, on peut voter dès 18 ans (avant, c’était 21 ans).',
    },
  ],
  qcm: [
    {
      id: 'qui-schoelcher',
      niv: 'n',
      sens: true,
      q: 'Qui suis-je ?',
      r: 'Victor Schœlcher',
      f: ['Jean Moulin', 'Jules Ferry', 'Louis Pasteur'],
      hints: [
        'Je suis un homme politique français du XIXe siècle.',
        'J’ai voyagé et j’ai été révolté par ce que j’ai vu dans les colonies.',
        'Je me suis battu toute ma vie pour la liberté de tous les êtres humains.',
        'En 1848, je fais signer le décret d’abolition de l’esclavage.',
      ],
      e: 'Victor Schœlcher a obtenu l’abolition définitive de l’esclavage dans les colonies françaises en 1848.',
    },
    {
      id: 'qui-de-gaulle',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Charles de Gaulle',
      f: ['Jules Ferry', 'Jean Jaurès', 'Victor Hugo'],
      hints: [
        'Je suis un militaire devenu homme politique.',
        'Je suis né à Lille en 1890.',
        'En 1958, je fonde la Ve République.',
        'Je suis le premier président de la Ve République.',
      ],
      e: 'Le général de Gaulle fonde la Ve République en 1958 et en devient le premier président.',
    },
    {
      id: 'qui-auclert',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Hubertine Auclert',
      f: ['Marie Curie', 'Olympe de Gouges', 'Simone Veil'],
      hints: [
        'Je suis une femme du XIXe siècle.',
        'Je fonde un journal qui s’appelle La Citoyenne.',
        'Je me bats pour que les femmes puissent voter.',
        'On me considère comme la première « suffragette » française.',
      ],
      e: 'Hubertine Auclert a lutté pour le droit de vote des femmes, obtenu seulement en 1944.',
    },
    {
      id: 'suffrage',
      niv: 'n',
      q: 'Qu’est-ce que le suffrage universel ?',
      r: 'Le droit de vote pour tous les citoyens adultes',
      f: ['Le droit de vote réservé aux riches', 'Le choix du roi par les nobles', 'Un impôt sur les salaires'],
      e: 'Le suffrage universel, c’est le droit de vote pour tous les citoyens adultes.',
    },
    {
      id: '1848',
      niv: 'n',
      q: 'En 1848, qui obtient le droit de vote ?',
      r: 'Tous les hommes de 21 ans et plus',
      f: ['Toutes les femmes', 'Seulement les hommes riches', 'Tous les enfants'],
      e: 'En 1848, c’est le suffrage universel masculin : les femmes devront attendre 1944.',
    },
    {
      id: 'laicite',
      niv: 'n',
      q: 'Que garantit la laïcité ?',
      r: 'Chacun est libre de croire ou de ne pas croire.',
      f: ['Tout le monde doit avoir la même religion.', 'Les religions sont interdites.', 'L’État choisit la religion des citoyens.'],
      e: 'La laïcité protège la liberté de conscience : l’État ne favorise aucune religion.',
    },
    {
      id: 'isoloir',
      niv: 'f',
      q: 'Où l’électeur choisit-il son bulletin en secret ?',
      r: 'Dans l’isoloir',
      f: ['Sur la place publique', 'Dans la cour de l’école', 'À la boulangerie'],
      e: 'L’isoloir est une petite cabine fermée par un rideau : le vote est secret.',
    },
    {
      id: 'urne',
      niv: 'f',
      q: 'Que met-on dans l’urne quand on vote ?',
      r: 'Une enveloppe avec son bulletin de vote',
      f: ['Une pièce de monnaie', 'Une lettre au roi', 'Son cahier'],
      e: 'On glisse l’enveloppe qui contient son bulletin dans l’urne.',
    },
    {
      id: 'femmes-pourquoi',
      niv: 'p',
      q: 'Pourquoi les femmes ont-elles dû attendre 1944 pour voter en France ?',
      r: 'Parce que beaucoup d’hommes politiques refusaient de leur donner ce droit',
      f: [
        'Parce qu’elles ne voulaient pas voter',
        'Parce qu’il n’y avait pas d’élections avant',
        'Parce qu’elles n’avaient pas l’âge',
      ],
      e: 'Des femmes ont réclamé ce droit pendant longtemps, mais les députés et les sénateurs l’ont souvent refusé.',
    },
  ],
  vf: [
    { id: 'femmes', niv: 'f', s: 'Depuis 1944, les femmes ont le droit de voter en France.', v: true, e: 'Les femmes obtiennent le droit de vote en 1944 et votent pour la première fois en 1945.' },
    { id: 'femmes-1848', niv: 'n', s: 'En 1848, les femmes obtiennent le droit de vote.', v: false, e: 'En 1848, seuls les hommes obtiennent le droit de vote ; les femmes l’obtiennent en 1944.' },
    { id: 'isoloir', niv: 'f', s: 'Pour voter, on passe dans l’isoloir puis on met son enveloppe dans l’urne.', v: true, e: 'L’isoloir garantit que le vote est secret.' },
    { id: '16ans', niv: 'f', s: 'Aujourd’hui, on peut voter dès 16 ans en France.', v: false, e: 'En France, on peut voter à partir de 18 ans.' },
    { id: 'public', niv: 'f', s: 'Le vote est public : tout le monde voit ton bulletin.', v: false, e: 'Le vote est secret : personne ne doit savoir pour qui tu votes.' },
    { id: 'representants', niv: 'f', s: 'En République, les citoyens choisissent leurs représentants en votant.', v: true, e: 'Les citoyens élisent le maire, les députés, le président…' },
    { id: '1905', niv: 'n', s: 'La loi de 1905 sépare les Églises et l’État.', v: true, e: 'Depuis 1905, l’État ne reconnaît et ne paie aucune religion.' },
    { id: 've', niv: 'n', s: 'La Ve République a été fondée en 1958.', v: true, e: 'Elle est fondée en 1958 avec le général de Gaulle.' },
    { id: 'esclavage', niv: 'n', sens: true, s: 'L’esclavage a été définitivement aboli en 1848 dans les colonies françaises.', v: true, e: 'C’est le décret d’abolition préparé par Victor Schœlcher.' },
    { id: 'suffrage', niv: 'n', s: 'Le suffrage universel masculin donne le droit de vote à tous les hommes adultes.', v: true, e: 'C’est ce qui est décidé en 1848.' },
    { id: 'laicite', niv: 'n', s: 'La laïcité oblige tous les Français à avoir une religion.', v: false, e: 'La laïcité laisse chacun libre de croire ou de ne pas croire.' },
    { id: '1974', niv: 'p', s: 'Depuis 1974, on peut voter à 18 ans.', v: true, e: 'Avant 1974, il fallait avoir 21 ans pour voter.' },
    { id: 'schoelcher', niv: 'p', sens: true, s: 'Victor Schœlcher a lutté pour l’abolition de l’esclavage.', v: true, e: 'Il a préparé le décret d’abolition de 1848.' },
    { id: '1789', niv: 'p', s: 'Les femmes ont voté pour la première fois en 1789.', v: false, e: 'Les Françaises votent pour la première fois en 1945.' },
    { id: '1958', niv: 'p', s: 'Le droit de vote des femmes date de 1958.', v: false, e: 'Il date de 1944 ; 1958 est la fondation de la Ve République.' },
  ],
};

/* ------------------------------------------------------------------ */
/* Thème 2 — L'âge industriel en France                                */
/* ------------------------------------------------------------------ */

const ENERGIES: Fiche = {
  lecon: 'CM2.HI20.T2.ENERGIES',
  evts: [
    { id: 'watt', niv: 'p', label: 'Machine à vapeur perfectionnée par James Watt', date: '1769', t: 1769 },
    {
      id: 'essor',
      niv: 'n',
      label: 'Essor de l’industrialisation en France',
      date: 'après 1830',
      t: 1830.5,
      nivAnnee: null,
    },
    {
      id: 'train',
      niv: 'f',
      label: 'Première ligne de chemin de fer pour voyageurs en France',
      date: '1837',
      t: 1837.08,
      e: 'En 1837, la première ligne pour voyageurs relie Paris à Saint-Germain-en-Laye.',
    },
    { id: 'telephone', niv: 'p', label: 'Invention du téléphone par Graham Bell', date: '1876', t: 1876 },
    {
      id: 'ampoule',
      niv: 'f',
      label: 'Ampoule électrique d’Edison',
      date: '1879',
      t: 1879,
      e: 'En 1879, Thomas Edison met au point une ampoule électrique qui dure longtemps.',
    },
    { id: 'automobile', niv: 'p', label: 'Première automobile à moteur à essence (Benz)', date: '1886', t: 1886 },
    { id: 'eiffel', niv: 'f', label: 'Construction de la tour Eiffel', date: '1889', t: 1889 },
    { id: 'cinema', niv: 'n', label: 'Première séance de cinéma des frères Lumière', date: '1895', t: 1895.12 },
    { id: 'metro', niv: 'n', label: 'Première ligne du métro de Paris', date: '1900', t: 1900.07 },
    { id: 'wright', niv: 'p', label: 'Premier vol en avion à moteur des frères Wright', date: '1903', t: 1903.12 },
  ],
  qcm: [
    {
      id: 'qui-edison',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Thomas Edison',
      f: ['Louis Pasteur', 'Gustave Eiffel', 'Jules Verne'],
      hints: [
        'Je suis un inventeur américain.',
        'J’ai déposé plus de 1 000 brevets.',
        'J’ai inventé le phonographe, qui enregistre les sons.',
        'En 1879, je mets au point une ampoule électrique qui dure longtemps.',
      ],
      img: '💡',
      e: 'Thomas Edison a inventé le phonographe et perfectionné l’ampoule électrique.',
    },
    {
      id: 'qui-eiffel',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Gustave Eiffel',
      f: ['Thomas Edison', 'Le baron Haussmann', 'Louis Lumière'],
      hints: [
        'Je suis un ingénieur français.',
        'Je construis des ponts et des viaducs en fer.',
        'J’ai fabriqué la structure intérieure de la statue de la Liberté.',
        'Ma construction la plus célèbre est faite pour l’Exposition universelle de 1889.',
        'Une tour de Paris porte mon nom.',
      ],
      img: '🗼',
      e: 'Gustave Eiffel est l’ingénieur de la tour Eiffel, construite pour l’Exposition universelle de 1889.',
    },
    {
      id: 'vapeur',
      niv: 'n',
      q: 'Comment fonctionne une machine à vapeur ?',
      r: 'On brûle du charbon pour chauffer de l’eau : la vapeur fait bouger des pistons.',
      f: [
        'Le vent fait tourner ses ailes.',
        'Une pile électrique la fait avancer.',
        'Des chevaux la tirent.',
      ],
      e: 'Le feu de charbon fait bouillir l’eau ; la vapeur pousse des pistons qui font tourner les roues ou les machines.',
    },
    {
      id: 'electricite',
      niv: 'n',
      q: 'Quelle nouvelle énergie éclaire peu à peu les villes à la fin du XIXe siècle ?',
      r: 'L’électricité',
      f: ['La bougie', 'Le charbon de bois', 'Le vent'],
      e: 'À la fin du XIXe siècle, l’électricité commence à éclairer les rues et à faire rouler les tramways.',
    },
    {
      id: 'mine',
      niv: 'f',
      q: 'Où extrait-on le charbon ?',
      r: 'Dans une mine',
      f: ['Dans la mer', 'Dans une forêt', 'Dans un moulin'],
      e: 'Le charbon est extrait sous la terre, dans les mines, par les mineurs.',
    },
    {
      id: 'essence',
      niv: 'p',
      q: 'Quel carburant, tiré du pétrole, fait rouler l’automobile de Benz en 1886 ?',
      r: 'L’essence',
      f: ['Le charbon', 'Le bois', 'L’huile d’olive'],
      e: 'Le moteur à explosion fonctionne avec de l’essence, fabriquée à partir du pétrole.',
    },
    {
      id: 'usines-mines',
      niv: 'p',
      q: 'Pourquoi beaucoup d’usines s’installent-elles près des mines de charbon ?',
      r: 'Pour avoir facilement l’énergie qui fait marcher leurs machines',
      f: ['Pour être loin des villes', 'Parce que le charbon est joli', 'Pour que les ouvriers soient au soleil'],
      e: 'Le charbon fait marcher les machines à vapeur : près de la mine, il coûte moins cher à transporter.',
    },
    {
      id: 'telephone',
      niv: 'n',
      q: 'Quelle invention de 1876 permet de se parler à distance ?',
      r: 'Le téléphone',
      f: ['Le télescope', 'La locomotive', 'L’ampoule'],
      e: 'Graham Bell invente le téléphone en 1876.',
    },
  ],
  vf: [
    { id: 'charbon', niv: 'f', s: 'Au XIXe siècle, le charbon est l’énergie principale des usines.', v: true, e: 'Le charbon fait fonctionner les machines à vapeur.' },
    { id: 'vapeur-elec', niv: 'f', s: 'La machine à vapeur fonctionne avec de l’électricité.', v: false, e: 'La machine à vapeur fonctionne avec du charbon qui fait bouillir de l’eau.' },
    { id: 'train', niv: 'f', s: 'Le chemin de fer se développe en France au XIXe siècle.', v: true, e: 'Les lignes de chemin de fer se multiplient à partir de 1840.' },
    { id: 'ampoule', niv: 'f', s: 'Les premières ampoules électriques datent de l’an 1500.', v: false, e: 'L’ampoule électrique d’Edison date de 1879.' },
    { id: 'eiffel', niv: 'n', s: 'La tour Eiffel a été construite pour l’Exposition universelle de 1889.', v: true, e: 'Elle est construite en fer pour montrer les progrès de l’industrie.' },
    { id: 'metro', niv: 'n', s: 'Le métro de Paris a été inauguré en 1900.', v: true, e: 'La première ligne ouvre pendant l’Exposition universelle de 1900.' },
    { id: 'petrole', niv: 'n', s: 'Le pétrole permet de faire rouler les automobiles.', v: true, e: 'L’essence est fabriquée à partir du pétrole.' },
    { id: 'maisons', niv: 'n', s: 'Vers 1850, presque toutes les maisons ont l’électricité.', v: false, e: 'L’électricité n’arrive dans la plupart des maisons qu’au XXe siècle.' },
    { id: 'lumiere', niv: 'p', s: 'Les frères Lumière ont inventé le cinématographe.', v: true, e: 'Leur première séance publique a lieu à Paris en 1895.' },
    { id: 'marseille', niv: 'p', s: 'La première ligne de chemin de fer pour voyageurs en France relie Paris à Marseille.', v: false, e: 'Elle relie Paris à Saint-Germain-en-Laye, en 1837.' },
    { id: 'gaz', niv: 'p', s: 'L’électricité remplace peu à peu les lampes à gaz dans les rues des villes.', v: true, e: 'À la fin du XIXe siècle, l’éclairage électrique se répand.' },
    { id: 'verne', niv: 'p', s: 'Le téléphone a été inventé par Jules Verne.', v: false, e: 'Il a été inventé par Graham Bell en 1876 ; Jules Verne était un écrivain.' },
  ],
  paires: [
    {
      id: 'inventeurs',
      niv: 'n',
      prompt: 'Associe chaque invention à son inventeur.',
      relation: 'invention → inventeur',
      pairs: [
        ['l’ampoule électrique', 'Thomas Edison'],
        ['le téléphone', 'Graham Bell'],
        ['le cinématographe', 'les frères Lumière'],
        ['la tour Eiffel', 'Gustave Eiffel'],
        ['la locomotive', 'George Stephenson'],
      ],
      e: 'Edison : l’ampoule ; Bell : le téléphone ; les frères Lumière : le cinéma ; Eiffel : la tour ; Stephenson : la locomotive.',
    },
    {
      id: 'energies',
      niv: 'p',
      prompt: 'Associe chaque machine à l’énergie qui la fait fonctionner.',
      relation: 'machine → énergie',
      pairs: [
        ['la locomotive à vapeur', 'le charbon'],
        ['le tramway électrique', 'l’électricité'],
        ['l’automobile de Benz', 'l’essence'],
        ['le moulin', 'le vent ou l’eau'],
      ],
      e: 'La locomotive brûle du charbon, le tramway utilise l’électricité, l’automobile l’essence et le moulin le vent ou l’eau.',
    },
  ],
};

const TRAVAIL: Fiche = {
  lecon: 'CM2.HI20.T2.TRAVAIL',
  evts: [
    {
      id: 'loi-enfants',
      niv: 'p',
      sens: true,
      label: 'Première loi limitant le travail des enfants dans les usines',
      date: '1841',
      t: 1841.03,
      e: 'La loi de 1841 interdit de faire travailler les enfants de moins de 8 ans dans les grandes usines.',
    },
    {
      id: 'bon-marche',
      niv: 'f',
      label: 'Ouverture du Bon Marché, un des premiers grands magasins',
      date: '1852',
      t: 1852,
      e: 'En 1852, Aristide Boucicaut développe à Paris le Bon Marché, un des premiers grands magasins.',
    },
    {
      id: 'greve',
      niv: 'f',
      label: 'Droit de grève',
      date: '1864',
      t: 1864.05,
      e: 'Depuis 1864, les ouvriers ont le droit de faire grève.',
    },
    {
      id: 'syndicats',
      niv: 'n',
      label: 'Liberté syndicale : les ouvriers peuvent créer des syndicats',
      date: '1884',
      t: 1884.03,
      e: 'La loi de 1884 autorise les syndicats, qui défendent les travailleurs.',
    },
    { id: 'germinal', niv: 'p', label: 'Émile Zola publie Germinal, un roman sur les mineurs', date: '1885', t: 1885 },
    { id: 'repos', niv: 'p', label: 'Repos obligatoire le dimanche', date: '1906', t: 1906.07 },
    { id: 'huit-heures', niv: 'n', label: 'Journée de travail limitée à 8 heures', date: '1919', t: 1919.04 },
    { id: 'conges', niv: 'f', label: 'Premiers congés payés', date: '1936', t: 1936.06 },
  ],
  qcm: [
    {
      id: 'mineur',
      niv: 'f',
      q: 'Comment appelle-t-on l’ouvrier qui travaille au fond de la mine ?',
      r: 'Un mineur',
      f: ['Un meunier', 'Un marin', 'Un boulanger'],
      e: 'Le mineur extrait le charbon au fond de la mine.',
    },
    {
      id: 'greve',
      niv: 'n',
      q: 'Qu’est-ce qu’une grève ?',
      r: 'Un arrêt du travail pour réclamer de meilleures conditions',
      f: ['Une fête à l’usine', 'Une machine à vapeur', 'Un jour de vacances payé'],
      e: 'Faire grève, c’est arrêter de travailler pour obtenir de meilleurs salaires ou moins d’heures de travail.',
    },
    {
      id: 'syndicat',
      niv: 'n',
      q: 'Qu’est-ce qu’un syndicat ?',
      r: 'Une association qui défend les droits des travailleurs',
      f: ['Un grand magasin', 'Une usine de charbon', 'Une école pour ouvriers'],
      e: 'Les syndicats, autorisés en 1884, défendent les ouvriers.',
    },
    {
      id: 'enfants',
      niv: 'n',
      sens: true,
      q: 'Au XIXe siècle, pourquoi des enfants travaillaient-ils dans les mines et les usines ?',
      r: 'Leur famille était pauvre et avait besoin de leur salaire.',
      f: ['Ils voulaient s’amuser.', 'Ils étaient mieux payés que les adultes.', 'C’était obligatoire pour tous les enfants.'],
      e: 'Les familles ouvrières étaient pauvres ; des lois ont peu à peu interdit le travail des jeunes enfants.',
    },
    {
      id: 'heures',
      niv: 'n',
      q: 'Vers 1850, combien d’heures par jour travaille souvent un ouvrier ?',
      r: '12 heures ou plus',
      f: ['2 heures', '5 heures', '7 heures'],
      e: 'Les journées de travail étaient très longues, souvent 12 heures ou plus, six jours sur sept.',
    },
    {
      id: 'qui-zola',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Émile Zola',
      f: ['Victor Hugo', 'Jules Verne', 'Jules Ferry'],
      hints: [
        'Je suis un écrivain français du XIXe siècle.',
        'Je suis descendu dans une mine pour préparer un livre.',
        'Mon roman raconte une grève de mineurs dans le nord de la France.',
        'J’ai écrit Germinal en 1885.',
      ],
      img: '📖',
      e: 'Émile Zola raconte la vie des mineurs dans Germinal (1885).',
    },
    {
      id: 'grand-magasin',
      niv: 'p',
      q: 'Quelle nouveauté les grands magasins proposent-ils à leurs clients ?',
      r: 'Des prix fixes affichés et le droit d’entrer sans rien acheter',
      f: ['Des produits gratuits', 'Des magasins sans vendeurs', 'Des achats sur Internet'],
      e: 'Dans les grands magasins, les prix sont affichés et l’on peut se promener librement entre les rayons.',
    },
    {
      id: 'atelier',
      niv: 'f',
      q: 'Qui travaille dans un atelier ?',
      r: 'Un artisan',
      f: ['Un mineur', 'Un roi', 'Un moine'],
      e: 'L’artisan fabrique des objets à la main ou avec de petites machines, dans un atelier.',
    },
  ],
  vf: [
    { id: 'enfants', niv: 'f', sens: true, s: 'Au XIXe siècle, des enfants travaillaient dans les mines et les usines.', v: true, e: 'Des enfants travaillaient très jeunes, parfois dès 8 ans.' },
    { id: '35h', niv: 'f', s: 'Les ouvriers du XIXe siècle travaillaient 35 heures par semaine.', v: false, e: 'Ils travaillaient souvent plus de 12 heures par jour.' },
    { id: 'mineur', niv: 'f', s: 'Un mineur travaille au fond d’une mine pour extraire du charbon.', v: true, e: 'Le charbon est l’énergie de l’âge industriel.' },
    { id: 'danger', niv: 'f', s: 'Le travail dans les mines était souvent dangereux.', v: true, e: 'Les éboulements et les coups de grisou faisaient des victimes.' },
    { id: 'machines', niv: 'f', s: 'Dans une usine du XIXe siècle, les machines font tout le travail sans ouvriers.', v: false, e: 'Les ouvriers et les ouvrières font fonctionner les machines.' },
    { id: 'greve', niv: 'n', s: 'Faire grève, c’est arrêter le travail pour réclamer de meilleures conditions.', v: true, e: 'Le droit de grève est reconnu en 1864.' },
    { id: 'syndicat', niv: 'n', s: 'Un syndicat est une usine.', v: false, e: 'Un syndicat est une association qui défend les travailleurs.' },
    { id: 'magasins', niv: 'n', s: 'Les grands magasins apparaissent à Paris au XIXe siècle.', v: true, e: 'Le Bon Marché se développe à partir de 1852.' },
    { id: 'conges', niv: 'n', s: 'Au XIXe siècle, les ouvriers avaient cinq semaines de congés payés.', v: false, e: 'Les premiers congés payés (deux semaines) datent de 1936.' },
    { id: '1864', niv: 'p', s: 'Le droit de grève est reconnu en 1864.', v: true, e: 'C’est la loi Ollivier de 1864.' },
    { id: '1841', niv: 'p', sens: true, s: 'La loi de 1841 interdit de faire travailler les enfants de moins de 8 ans dans les grandes usines.', v: true, e: 'C’est la première loi qui protège les enfants au travail.' },
    { id: 'germinal', niv: 'p', s: 'Germinal est un roman de Victor Hugo.', v: false, e: 'Germinal est un roman d’Émile Zola.' },
    { id: '1936', niv: 'p', s: 'Les premiers congés payés datent de 1936.', v: true, e: 'En 1936, les salariés obtiennent deux semaines de congés payés.' },
    { id: '1884', niv: 'p', s: 'Les syndicats sont autorisés en 1884.', v: true, e: 'C’est la loi sur la liberté syndicale.' },
  ],
  paires: [
    {
      id: 'metiers',
      niv: 'f',
      prompt: 'Associe chaque travailleur à son lieu de travail.',
      relation: 'travailleur → lieu',
      pairs: [
        ['le mineur', 'la mine'],
        ['l’ouvrière du textile', 'l’usine'],
        ['l’artisan', 'l’atelier'],
        ['la vendeuse', 'le grand magasin'],
        ['le paysan', 'les champs'],
      ],
      e: 'Mineur à la mine, ouvrière à l’usine, artisan à l’atelier, vendeuse au grand magasin, paysan aux champs.',
    },
  ],
};

const VILLE: Fiche = {
  lecon: 'CM2.HI20.T2.VILLE',
  evts: [
    { id: 'essor', niv: 'f', label: 'Essor de l’industrialisation en France', date: 'après 1830', t: 1830.5, nivAnnee: null },
    { id: 'train', niv: 'f', label: 'Première ligne de chemin de fer pour voyageurs en France', date: '1837', t: 1837.08 },
    {
      id: 'haussmann',
      niv: 'n',
      label: 'Grands travaux d’Haussmann à Paris',
      date: '1853-1870',
      t: 1853.06,
      e: 'De 1853 à 1870, le préfet Haussmann transforme Paris avec de larges avenues, des égouts et des parcs.',
    },
    { id: 'eiffel', niv: 'n', label: 'Exposition universelle et tour Eiffel', date: '1889', t: 1889 },
    { id: 'egouts', niv: 'p', label: 'Le tout-à-l’égout devient obligatoire à Paris', date: '1894', t: 1894.07 },
    { id: 'metro', niv: 'f', label: 'Première ligne du métro de Paris', date: '1900', t: 1900.07 },
    {
      id: 'urbaine',
      niv: 'n',
      label: 'Plus de la moitié des Français vivent en ville',
      date: '1931',
      t: 1931,
      e: 'En 1931, pour la première fois, plus de la moitié des Français vivent en ville.',
    },
    { id: 'electricite', niv: 'p', label: '8 communes rurales sur 10 ont l’électricité', date: '1932', t: 1932 },
  ],
  qcm: [
    {
      id: 'pourquoi',
      niv: 'n',
      q: 'Pourquoi beaucoup de paysans partent-ils vivre en ville au XIXe siècle ?',
      r: 'Pour trouver du travail dans les usines',
      f: ['Pour partir en vacances', 'Parce que les villes sont plus calmes', 'Pour cultiver de plus grands champs'],
      e: 'Les usines des villes ont besoin d’ouvriers : c’est l’exode rural.',
    },
    {
      id: 'haussmann',
      niv: 'n',
      q: 'Quel préfet transforme Paris avec de larges avenues ?',
      r: 'Le baron Haussmann',
      f: ['Jules Ferry', 'Gustave Eiffel', 'Louis Pasteur'],
      e: 'Le baron Haussmann dirige les grands travaux de Paris de 1853 à 1870.',
    },
    {
      id: 'quartiers',
      niv: 'n',
      q: 'Où vivent souvent les ouvriers dans les villes industrielles ?',
      r: 'Dans des quartiers pauvres, près des usines',
      f: ['Dans des châteaux', 'Dans les beaux quartiers du centre', 'À la campagne, loin des usines'],
      e: 'Les ouvriers vivent souvent dans des logements petits et mal chauffés, près des usines.',
    },
    {
      id: 'campagne',
      niv: 'f',
      q: 'Au XIXe siècle, où vivent la plupart des Français ?',
      r: 'À la campagne',
      f: ['En ville', 'À l’étranger', 'Dans des usines'],
      e: 'Jusqu’en 1931, la majorité des Français vivent à la campagne.',
    },
    {
      id: 'metro',
      niv: 'f',
      q: 'Quel moyen de transport souterrain ouvre à Paris en 1900 ?',
      r: 'Le métro',
      f: ['Le TGV', 'L’avion', 'Le bateau-mouche'],
      e: 'La première ligne du métro de Paris ouvre en 1900.',
    },
    {
      id: 'moissonneuse',
      niv: 'p',
      q: 'Dans les campagnes, quelle machine remplace peu à peu la faux pour couper les céréales ?',
      r: 'La moissonneuse',
      f: ['La locomotive', 'Le métier à tisser', 'Le marteau-pilon'],
      e: 'Les machines agricoles, comme la moissonneuse, arrivent peu à peu dans les campagnes.',
    },
    {
      id: 'hygiene',
      niv: 'p',
      q: 'Quel progrès améliore la propreté des villes à la fin du XIXe siècle ?',
      r: 'Les égouts et l’eau courante',
      f: ['Les remparts', 'Les lampes à huile', 'Les châteaux forts'],
      e: 'Les égouts et l’eau courante réduisent les maladies dans les villes.',
    },
    {
      id: 'bourgeois',
      niv: 'n',
      q: 'Où vivent souvent les familles bourgeoises ?',
      r: 'Dans de grands immeubles des beaux quartiers',
      f: ['Dans les cités ouvrières', 'Au fond des mines', 'Dans des cabanes'],
      e: 'Les bourgeois (patrons, médecins, avocats) habitent des appartements confortables dans les beaux quartiers.',
    },
  ],
  vf: [
    { id: 'exode', niv: 'f', s: 'Au XIXe siècle, beaucoup de paysans partent travailler en ville.', v: true, e: 'C’est l’exode rural.' },
    { id: 'metro-1800', niv: 'f', s: 'Le métro de Paris existait déjà en 1800.', v: false, e: 'La première ligne de métro ouvre en 1900.' },
    { id: 'gares', niv: 'f', s: 'Les villes industrielles grandissent autour des usines et des gares.', v: true, e: 'Les usines et le chemin de fer attirent les habitants.' },
    { id: 'villages', niv: 'f', s: 'Pendant l’exode rural, les villages se remplissent.', v: false, e: 'Pendant l’exode rural, les villages se vident au profit des villes.' },
    { id: 'majorite', niv: 'n', s: 'Au XIXe siècle, la majorité des Français vivent déjà en ville.', v: false, e: 'Il faut attendre 1931 pour que plus de la moitié des Français vivent en ville.' },
    { id: 'avenues', niv: 'n', s: 'Haussmann a fait construire de larges avenues à Paris.', v: true, e: 'Ce sont les grands travaux d’Haussmann (1853-1870).' },
    { id: 'pauvres', niv: 'n', s: 'Les quartiers ouvriers étaient souvent pauvres et surpeuplés.', v: true, e: 'Les familles ouvrières s’entassaient dans de petits logements.' },
    { id: 'definition', niv: 'n', s: 'On appelle « exode rural » le départ des habitants des villes vers la campagne.', v: false, e: 'L’exode rural, c’est le départ des habitants des campagnes vers les villes.' },
    { id: 'bourgeois', niv: 'n', s: 'Les bourgeois vivent souvent dans des immeubles confortables des beaux quartiers.', v: true, e: 'Ville bourgeoise et quartiers ouvriers sont très différents.' },
    { id: '1931', niv: 'p', s: 'C’est en 1931 que la population française devient majoritairement urbaine.', v: true, e: 'En 1931, plus de la moitié des Français vivent en ville.' },
    { id: 'machines', niv: 'p', s: 'Dans les campagnes, les machines agricoles se développent peu à peu.', v: true, e: 'Moissonneuses et batteuses arrivent dans les fermes.' },
    { id: 'electricite', niv: 'p', s: 'Au XIXe siècle, toutes les maisons des campagnes ont l’électricité.', v: false, e: 'L’électricité arrive dans la plupart des campagnes au XXe siècle.' },
    { id: 'egouts', niv: 'p', s: 'Le tout-à-l’égout améliore la propreté des villes.', v: true, e: 'Les eaux sales sont évacuées par les égouts.' },
  ],
  paires: [
    {
      id: 'mots',
      niv: 'n',
      prompt: 'Associe chaque mot à sa définition.',
      relation: 'mot → définition',
      pairs: [
        ['l’exode rural', 'le départ des campagnes vers les villes'],
        ['l’urbanisation', 'la croissance des villes'],
        ['un ouvrier', 'il travaille dans une usine'],
        ['un bourgeois', 'un habitant aisé de la ville'],
        ['un paysan', 'il cultive la terre'],
      ],
      e: 'Exode rural, urbanisation, ouvrier, bourgeois et paysan : ce sont les mots clés de la ville industrielle et du monde rural.',
    },
  ],
};

/* ------------------------------------------------------------------ */
/* Thème 3 — La France, des guerres mondiales à l'Union européenne      */
/* ------------------------------------------------------------------ */

const GUERRES: Fiche = {
  lecon: 'CM2.HI20.T3.GUERRES',
  sens: true,
  evts: [
    { id: 'debut-14', niv: 'f', label: 'Début de la Première Guerre mondiale', date: '1914', t: 1914.08 },
    {
      id: 'verdun',
      niv: 'n',
      label: 'Bataille de Verdun',
      date: '1916',
      t: 1916.02,
      e: 'En 1916, la bataille de Verdun dure dix mois et fait des centaines de milliers de victimes.',
    },
    {
      id: 'armistice',
      niv: 'f',
      label: 'Armistice de la Première Guerre mondiale',
      date: '11 novembre 1918',
      t: 1918.1111,
      e: 'Le 11 novembre 1918, l’armistice met fin aux combats de la Première Guerre mondiale.',
    },
    { id: 'debut-39', niv: 'f', label: 'Début de la Seconde Guerre mondiale', date: '1939', t: 1939.09 },
    {
      id: 'appel',
      niv: 'n',
      label: 'Appel du 18 juin du général de Gaulle',
      date: '18 juin 1940',
      t: 1940.0618,
      e: 'Le 18 juin 1940, depuis Londres, le général de Gaulle appelle les Français à continuer le combat.',
    },
    { id: 'veldhiv', niv: 'p', label: 'Rafle du Vel d’Hiv à Paris', date: 'juillet 1942', t: 1942.0716 },
    { id: 'cnr', niv: 'p', label: 'Jean Moulin réunit le Conseil national de la Résistance', date: 'mai 1943', t: 1943.0527 },
    {
      id: 'debarquement',
      niv: 'n',
      label: 'Débarquement des Alliés en Normandie',
      date: '6 juin 1944',
      t: 1944.0606,
      e: 'Le 6 juin 1944, les Alliés débarquent en Normandie : c’est le début de la libération de la France.',
    },
    { id: 'liberation', niv: 'p', label: 'Libération de Paris', date: 'août 1944', t: 1944.0825 },
    {
      id: 'fin-39',
      niv: 'f',
      label: 'Fin de la Seconde Guerre mondiale en Europe',
      date: '8 mai 1945',
      t: 1945.0508,
      e: 'Le 8 mai 1945, l’Allemagne nazie capitule : la guerre s’arrête en Europe.',
    },
  ],
  qcm: [
    {
      id: 'qui-moulin',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Jean Moulin',
      f: ['Charles de Gaulle', 'Jules Ferry', 'Philippe Pétain'],
      hints: [
        'Avant la guerre, j’étais préfet.',
        'Je rejoins le général de Gaulle à Londres.',
        'Je reviens en France pour unir les résistants.',
        'En 1943, je réunis le Conseil national de la Résistance.',
      ],
      e: 'Jean Moulin a unifié les mouvements de la Résistance intérieure française.',
    },
    {
      id: 'qui-de-gaulle',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Charles de Gaulle',
      f: ['Philippe Pétain', 'Jean Moulin', 'Georges Clemenceau'],
      hints: [
        'Je suis un militaire français.',
        'En juin 1940, je refuse la défaite.',
        'Depuis Londres, je parle aux Français à la radio.',
        'Mon appel du 18 juin 1940 invite les Français à continuer le combat.',
      ],
      e: 'Le général de Gaulle lance l’appel du 18 juin 1940 et dirige la France libre.',
    },
    {
      id: 'tranchees',
      niv: 'n',
      q: 'Comment appelle-t-on les longs fossés où vivaient les soldats de 1914-1918 ?',
      r: 'Les tranchées',
      f: ['Les casernes', 'Les châteaux forts', 'Les tunnels du métro'],
      e: 'Les soldats vivaient dans les tranchées, dans la boue et le froid.',
    },
    {
      id: 'armistice',
      niv: 'n',
      q: 'Qu’est-ce qu’un armistice ?',
      r: 'Un accord pour arrêter les combats',
      f: ['Une grande bataille', 'Une fête nationale', 'Une arme nouvelle'],
      e: 'Un armistice arrête les combats ; la paix est signée ensuite par un traité.',
    },
    {
      id: '11-novembre',
      niv: 'f',
      q: 'Pourquoi le 11 novembre est-il un jour férié en France ?',
      r: 'Pour se souvenir de la fin des combats de 1918 et des soldats morts',
      f: ['Pour fêter la prise de la Bastille', 'Pour fêter la rentrée des classes', 'Pour fêter Noël'],
      e: 'Le 11 novembre, on rend hommage aux soldats morts, devant les monuments aux morts.',
    },
    {
      id: 'monuments',
      niv: 'f',
      q: 'Comment appelle-t-on les monuments élevés dans chaque commune en hommage aux soldats morts ?',
      r: 'Les monuments aux morts',
      f: ['Les arcs de triomphe', 'Les fontaines', 'Les statues de Marianne'],
      e: 'Presque chaque commune a un monument aux morts avec les noms de ses soldats.',
    },
    {
      id: 'dates-39',
      niv: 'f',
      q: 'Quelles sont les dates de la Seconde Guerre mondiale ?',
      r: '1939-1945',
      f: ['1914-1918', '1789-1799', '1870-1871'],
      e: 'La Seconde Guerre mondiale dure de 1939 à 1945.',
    },
    {
      id: 'shoah',
      niv: 'n',
      q: 'Qu’est-ce que la Shoah ?',
      r: 'Le génocide des Juifs d’Europe par les nazis',
      f: ['Une bataille de 1916', 'Un traité de paix', 'Le débarquement en Normandie'],
      e: 'Pendant la Seconde Guerre mondiale, les nazis ont assassiné environ 6 millions de Juifs : c’est la Shoah.',
    },
    {
      id: 'occupation',
      niv: 'n',
      q: 'Pendant la Seconde Guerre mondiale, qu’appelle-t-on l’Occupation ?',
      r: 'La présence de l’armée allemande qui contrôle la France',
      f: ['Un métier', 'Une fête', 'Une loi sur l’école'],
      e: 'De 1940 à 1944, l’armée allemande occupe la France.',
    },
    {
      id: 'resistants',
      niv: 'n',
      q: 'Qui sont les résistants ?',
      r: 'Des personnes qui luttent contre l’occupant nazi',
      f: ['Des soldats de Napoléon', 'Des ouvriers en grève', 'Des explorateurs'],
      e: 'Les résistants luttent, souvent au péril de leur vie, contre l’occupant et le régime de Vichy.',
    },
    {
      id: 'bilan',
      niv: 'p',
      q: 'Combien de soldats français sont morts au combat pendant la Première Guerre mondiale ?',
      r: 'Environ 1,4 million',
      f: ['Environ 1 000', 'Environ 50 000', 'Environ 50 millions'],
      e: 'Environ 1,4 million de soldats français sont morts sur les 10 millions de soldats tués.',
    },
    {
      id: 'front',
      niv: 'p',
      q: 'Où se trouvent les principaux combats en France pendant la Première Guerre mondiale ?',
      r: 'Dans le nord et l’est du pays',
      f: ['Dans le sud-ouest', 'En Bretagne', 'En Corse'],
      e: 'Le front s’étend dans le nord et l’est de la France, de la mer du Nord à la Suisse.',
    },
  ],
  vf: [
    { id: 'duree-14', niv: 'f', s: 'La Première Guerre mondiale a duré de 1914 à 1918.', v: true, e: 'Elle commence en 1914 et s’arrête avec l’armistice du 11 novembre 1918.' },
    { id: 'duree-39', niv: 'f', s: 'La Seconde Guerre mondiale a duré de 1939 à 1945.', v: true, e: 'Elle s’arrête en Europe le 8 mai 1945.' },
    { id: '11-nov', niv: 'f', s: 'Le 11 novembre, on se souvient de la fin de la Seconde Guerre mondiale.', v: false, e: 'Le 11 novembre rappelle l’armistice de 1918 ; le 8 mai rappelle la fin de la Seconde Guerre mondiale en Europe.' },
    { id: 'siecle', niv: 'f', s: 'La Première Guerre mondiale a eu lieu au XIXe siècle.', v: false, e: 'Elle a eu lieu au XXe siècle (1914-1918).' },
    { id: 'tranchees', niv: 'n', s: 'Les poilus vivaient dans des tranchées.', v: true, e: 'Les tranchées étaient de longs fossés boueux.' },
    { id: '8-mai', niv: 'n', s: 'L’armistice de 1918 est signé le 8 mai.', v: false, e: 'Il est signé le 11 novembre 1918.' },
    { id: 'debarquement', niv: 'n', s: 'Le débarquement en Normandie a eu lieu le 6 juin 1944.', v: true, e: 'C’est le début de la libération de la France.' },
    { id: 'londres', niv: 'n', s: 'Le général de Gaulle a lancé son appel du 18 juin depuis Londres.', v: true, e: 'Il parle à la radio de la BBC.' },
    { id: 'fin', niv: 'n', s: 'Le 8 mai 1945, la guerre s’arrête en Europe.', v: true, e: 'L’Allemagne nazie capitule.' },
    { id: 'occupation', niv: 'n', s: 'Pendant l’Occupation, la vie quotidienne était facile pour les Français.', v: false, e: 'La nourriture manquait, il fallait des tickets de rationnement et les libertés étaient supprimées.' },
    { id: 'moulin', niv: 'p', s: 'Jean Moulin a unifié les mouvements de la Résistance.', v: true, e: 'Il réunit le Conseil national de la Résistance en 1943.' },
    { id: 'shoah', niv: 'p', s: 'La Shoah est le génocide des Juifs d’Europe par les nazis.', v: true, e: 'Environ 6 millions de Juifs ont été assassinés.' },
    { id: 'verdun', niv: 'p', s: 'La bataille de Verdun a eu lieu en 1940.', v: false, e: 'La bataille de Verdun a eu lieu en 1916.' },
  ],
};

const EUROPE: Fiche = {
  lecon: 'CM2.HI20.T3.EUROPE',
  evts: [
    { id: 'paix', niv: 'f', sens: true, label: 'Fin de la Seconde Guerre mondiale', date: '1945', t: 1945.05 },
    {
      id: 'ceca',
      niv: 'n',
      label: 'Création de la CECA (charbon et acier) : début de la construction européenne',
      date: '1951',
      t: 1951.04,
      e: 'En 1951, six pays mettent en commun leur charbon et leur acier : c’est la CECA.',
    },
    {
      id: 'rome',
      niv: 'f',
      label: 'Traité de Rome',
      date: '1957',
      t: 1957.03,
      e: 'En 1957, le traité de Rome crée la Communauté économique européenne avec six pays.',
    },
    { id: 'ru-entre', niv: 'p', label: 'Le Royaume-Uni entre dans la CEE', date: '1973', t: 1973.01 },
    { id: 'parlement', niv: 'p', label: 'Premières élections du Parlement européen', date: '1979', t: 1979.06 },
    {
      id: 'maastricht',
      niv: 'n',
      label: 'Traité de Maastricht : naissance de l’Union européenne',
      date: '1992',
      t: 1992.02,
      e: 'En 1992, le traité de Maastricht crée l’Union européenne.',
    },
    {
      id: 'euro',
      niv: 'f',
      label: 'L’euro en pièces et en billets',
      date: '2002',
      t: 2002.01,
      e: 'Le 1er janvier 2002, les pièces et les billets en euros remplacent le franc.',
    },
    { id: 'dix', niv: 'p', label: 'Dix nouveaux pays entrent dans l’Union européenne', date: '2004', t: 2004.05 },
    { id: 'brexit', niv: 'p', label: 'Le Royaume-Uni quitte l’Union européenne', date: '2020', t: 2020.01 },
  ],
  lieux: [
    { id: 'france', niv: 'f', map: 'europe', target: 'france', label: 'la France', prompt: 'Touche la France, un des six pays fondateurs.', e: 'La France est un des six pays fondateurs de la construction européenne.' },
    { id: 'allemagne', niv: 'f', map: 'europe', target: 'allemagne', label: 'l’Allemagne', prompt: 'Touche l’Allemagne, un des six pays fondateurs.', e: 'L’Allemagne (à l’époque, l’Allemagne de l’Ouest) est un pays fondateur ; elle est à l’est de la France.' },
    { id: 'italie', niv: 'f', map: 'europe', target: 'italie', label: 'l’Italie', prompt: 'Touche l’Italie, un des six pays fondateurs.', e: 'L’Italie, en forme de botte, est un pays fondateur ; le traité de Rome a été signé dans sa capitale.' },
    { id: 'belgique', niv: 'n', map: 'europe', target: 'belgique', label: 'la Belgique', prompt: 'Touche la Belgique, un des six pays fondateurs.', e: 'La Belgique, au nord de la France, est un pays fondateur.' },
    { id: 'pays-bas', niv: 'n', map: 'europe', target: 'pays-bas', label: 'les Pays-Bas', prompt: 'Touche les Pays-Bas, un des six pays fondateurs.', e: 'Les Pays-Bas, au nord de la Belgique, sont un pays fondateur ; Maastricht est une de leurs villes.' },
    { id: 'luxembourg', niv: 'n', map: 'europe', target: 'luxembourg', label: 'le Luxembourg', prompt: 'Touche le Luxembourg, un des six pays fondateurs.', e: 'Le Luxembourg, tout petit pays entre la France, la Belgique et l’Allemagne, est un pays fondateur.' },
    { id: 'royaume-uni', niv: 'p', map: 'europe', target: 'royaume-uni', label: 'le Royaume-Uni', prompt: 'Touche le pays qui a quitté l’Union européenne en 2020.', e: 'Le Royaume-Uni, entré en 1973, a quitté l’Union européenne en 2020.' },
  ],
  qcm: [
    {
      id: 'six',
      niv: 'n',
      q: 'Combien de pays signent le traité de Rome en 1957 ?',
      r: '6',
      f: ['27', '12', '2'],
      e: 'Six pays : la France, l’Allemagne de l’Ouest, l’Italie, la Belgique, les Pays-Bas et le Luxembourg.',
    },
    {
      id: 'vingt-sept',
      niv: 'n',
      q: 'Combien de pays font partie de l’Union européenne aujourd’hui ?',
      r: '27',
      f: ['6', '12', '50'],
      e: 'L’Union européenne compte 27 pays membres depuis le départ du Royaume-Uni en 2020.',
    },
    {
      id: 'pourquoi',
      niv: 'p',
      q: 'Pourquoi des pays d’Europe décident-ils de s’unir après 1945 ?',
      r: 'Pour garder la paix après deux guerres terribles',
      f: ['Pour faire la guerre ensemble', 'Pour avoir un seul roi', 'Pour supprimer les langues nationales'],
      e: 'Après deux guerres mondiales, les pays européens veulent coopérer pour ne plus se faire la guerre.',
    },
    {
      id: 'euro',
      niv: 'f',
      q: 'Quelle est la monnaie commune de nombreux pays de l’Union européenne ?',
      r: 'L’euro',
      f: ['Le dollar', 'Le franc', 'La livre'],
      e: 'L’euro est utilisé en pièces et en billets depuis 2002.',
    },
    {
      id: 'etoiles',
      niv: 'n',
      q: 'Combien d’étoiles y a-t-il sur le drapeau européen ?',
      r: '12',
      f: ['27', '6', '50'],
      img: '🇪🇺',
      e: 'Le drapeau européen a toujours 12 étoiles en cercle : elles symbolisent l’unité, pas le nombre de pays.',
    },
    {
      id: 'qui-schuman',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Robert Schuman',
      f: ['Jules Ferry', 'Jean Moulin', 'Victor Schœlcher'],
      hints: [
        'Je suis un homme politique français.',
        'Le 9 mai 1950, je propose de mettre en commun le charbon et l’acier.',
        'On me considère comme un des « pères de l’Europe ».',
        'Le 9 mai, la journée de l’Europe, rappelle ma déclaration.',
      ],
      e: 'Robert Schuman a lancé la construction européenne par sa déclaration du 9 mai 1950.',
    },
    {
      id: 'strasbourg',
      niv: 'p',
      q: 'Dans quelle ville française siège le Parlement européen ?',
      r: 'Strasbourg',
      f: ['Marseille', 'Lyon', 'Bordeaux'],
      e: 'Le Parlement européen se réunit à Strasbourg ; d’autres institutions sont à Bruxelles.',
    },
    {
      id: 'fondateur',
      niv: 'n',
      q: 'Lequel de ces pays fait partie des six pays fondateurs ?',
      r: 'La Belgique',
      f: ['L’Espagne', 'La Pologne', 'La Suède'],
      e: 'Les six fondateurs : France, Allemagne de l’Ouest, Italie, Belgique, Pays-Bas, Luxembourg.',
    },
    {
      id: 'brexit',
      niv: 'p',
      q: 'Quel pays a quitté l’Union européenne en 2020 ?',
      r: 'Le Royaume-Uni',
      f: ['La France', 'L’Italie', 'L’Allemagne'],
      e: 'Le Royaume-Uni a quitté l’Union européenne le 31 janvier 2020.',
    },
  ],
  vf: [
    { id: 'euro', niv: 'f', s: 'Les pièces et les billets en euros sont utilisés en France depuis 2002.', v: true, e: 'Ils remplacent le franc le 1er janvier 2002.' },
    { id: 'france', niv: 'f', s: 'La France est un des pays fondateurs de la construction européenne.', v: true, e: 'Elle fait partie des six pays fondateurs.' },
    { id: 'drapeau', niv: 'f', s: 'Le drapeau européen est bleu avec un cercle d’étoiles jaunes.', v: true, e: 'Il compte 12 étoiles jaunes sur fond bleu.' },
    { id: 'franc', niv: 'f', s: 'Le franc est toujours la monnaie de la France.', v: false, e: 'Depuis 2002, la monnaie de la France est l’euro.' },
    { id: 'rouge', niv: 'f', s: 'Le drapeau européen est rouge avec une seule étoile.', v: false, e: 'Il est bleu avec 12 étoiles jaunes.' },
    { id: 'rome', niv: 'n', s: 'Le traité de Rome a été signé en 1957 par six pays.', v: true, e: 'Il crée la Communauté économique européenne.' },
    { id: 'six', niv: 'n', s: 'L’Union européenne compte aujourd’hui 6 pays.', v: false, e: 'Elle compte 27 pays ; 6 étaient les fondateurs.' },
    { id: 'espagne', niv: 'n', s: 'L’Espagne fait partie des six pays fondateurs.', v: false, e: 'L’Espagne est entrée en 1986 ; elle n’est pas un pays fondateur.' },
    { id: 'tous', niv: 'n', s: 'Tous les pays d’Europe font partie de l’Union européenne.', v: false, e: 'La Suisse, la Norvège ou le Royaume-Uni, par exemple, n’en font pas partie.' },
    { id: 'maastricht', niv: 'p', s: 'Le traité de Maastricht crée l’Union européenne en 1992.', v: true, e: 'La Communauté devient l’Union européenne.' },
    { id: 'paix', niv: 'p', s: 'La construction européenne a commencé pour garder la paix entre les pays.', v: true, e: 'Après 1945, coopérer permet d’éviter une nouvelle guerre.' },
    { id: 'ru', niv: 'p', s: 'Le Royaume-Uni fait toujours partie de l’Union européenne.', v: false, e: 'Il l’a quittée en 2020.' },
  ],
};

export const HISTOIRE_2020: Fiche[] = [REVOLUTION, REPUBLIQUE100, FERRY, CITOYENS, ENERGIES, TRAVAIL, VILLE, GUERRES, EUROPE];
export { PAIRES_SYMBOLES };
