/**
 * Mots-clés à savoir écrire en histoire, géographie, sciences et EMC du CM2 (jeux d'écriture :
 * Ascension, Appareil photo, Wordle, Mots croisés…). Chaque mot a une définition d'enfant qui ne
 * contient pas le mot (indice des mots croisés). Niveaux : f = mot essentiel, n = vocabulaire du BO,
 * p = Plus loin. Les thèmes sensibles restent sobres (aucun mot violent).
 */
import type { M } from '../../generators/mots-cles';

export const MOTS_CM2: Record<string, readonly M[]> = {
  /* ------------------------------ Histoire ------------------------------ */
  'CM2.HI.RAPPEL_CM1.REVOLUTION': [
    ['roi', 'personne qui gouverne un royaume, comme Louis XVI', 'f'],
    ['peuple', 'ensemble des habitants d’un pays', 'f'],
    ['liberté', 'droit de faire ce que l’on veut sans nuire aux autres', 'f'],
    ['égalité', 'fait d’avoir les mêmes droits que les autres', 'f'],
    ['Bastille', 'forteresse-prison de Paris prise par le peuple le 14 juillet 1789', 'f'],
    ['révolution', 'grand changement, souvent brutal, de la façon de gouverner un pays', 'n'],
    ['privilège', 'avantage réservé à la noblesse et au clergé, aboli le 4 août 1789', 'n'],
    ['monarchie', 'régime politique où un roi gouverne', 'n'],
    ['citoyen', 'membre d’un pays qui a des droits, comme celui de voter, et des devoirs', 'n'],
    ['noblesse', 'groupe des nobles, qui avaient des privilèges avant 1789', 'n'],
    ['clergé', 'ensemble des prêtres et des religieux', 'n'],
    ['constitution', 'texte qui fixe les règles de fonctionnement d’un État', 'p'],
    ['doléances', 'plaintes et demandes écrites par les Français dans des cahiers en 1789', 'p'],
    ['déclaration', 'texte officiel : celle des droits de l’homme et du citoyen date du 26 août 1789', 'p'],
  ],
  'CM2.HI20.T1.REPUBLIQUE100': [
    ['république', 'régime politique sans roi, où les dirigeants sont élus', 'f'],
    ['Marianne', 'figure de femme qui représente la République française', 'f'],
    ['drapeau', 'emblème en tissu d’un pays ; celui de la France est bleu, blanc, rouge', 'f'],
    ['devise', 'courte phrase qui résume des valeurs : Liberté, Égalité, Fraternité', 'f'],
    ['hymne', 'chant officiel d’un pays', 'f'],
    ['fête', 'jour de célébration, comme le 14 Juillet', 'f'],
    ['Marseillaise', 'hymne national de la France, écrit en 1792', 'n'],
    ['fraternité', 'lien d’entraide et d’amitié entre tous les citoyens', 'n'],
    ['symbole', 'image ou objet qui représente une idée', 'n'],
    ['centenaire', 'anniversaire des cent ans', 'n'],
    ['tricolore', 'qui a trois couleurs, comme le drapeau français', 'n'],
    ['proclamation', 'annonce officielle, comme celle de la République en septembre 1792', 'p'],
    ['républicain', 'partisan du régime sans roi, où les dirigeants sont élus', 'p'],
    ['commémoration', 'cérémonie pour se souvenir d’un événement', 'p'],
  ],
  'CM2.HI20.T1.FERRY': [
    ['école', 'lieu où les enfants apprennent', 'f'],
    ['maître', 'personne qui fait la classe aux élèves', 'f'],
    ['ardoise', 'petite plaque sur laquelle on écrit à la craie', 'f'],
    ['plume', 'petite pointe de métal trempée dans l’encre pour écrire', 'f'],
    ['encre', 'liquide coloré pour écrire', 'f'],
    ['gratuite', 'se dit de l’école qu’on n’a pas besoin de payer depuis 1881', 'n'],
    ['obligatoire', 'imposé par la loi : l’instruction l’est depuis 1882', 'n'],
    ['laïque', 'qui ne dépend d’aucune religion, comme l’école publique', 'n'],
    ['instituteur', 'ancien nom du maître d’école primaire', 'n'],
    ['certificat', 'le ___ d’études : diplôme de fin d’école primaire', 'n'],
    ['encrier', 'petit pot d’encre posé sur le pupitre', 'n'],
    ['pupitre', 'table d’écolier dont le dessus s’ouvre', 'p'],
    ['hussards', 'les « ___ noirs » : surnom des instituteurs de la République', 'p'],
    ['scolarité', 'temps passé à l’école', 'p'],
  ],
  'CM2.HI20.T1.CITOYENS': [
    ['vote', 'choix exprimé par un électeur', 'f'],
    ['loi', 'règle votée qui s’applique à tous', 'f'],
    ['citoyen', 'membre d’un pays qui a des droits et des devoirs', 'f'],
    ['élection', 'choix de représentants par un vote', 'f'],
    ['urne', 'boîte où l’on dépose son bulletin de vote', 'f'],
    ['bulletin', 'papier sur lequel on indique son choix pour voter', 'f'],
    ['suffrage', 'vote ; il devient universel pour les hommes en 1848', 'n'],
    ['universel', 'qui concerne tout le monde', 'n'],
    ['esclavage', 'situation d’une personne privée de liberté et vendue ; aboli en France en 1848', 'n'],
    ['abolition', 'suppression d’une loi ou d’une pratique', 'n'],
    ['laïcité', 'principe qui sépare les religions et l’État (loi de 1905)', 'n'],
    ['démocratie', 'régime où le pouvoir appartient au peuple', 'n'],
    ['majorité', 'âge à partir duquel on peut voter : 18 ans depuis 1974', 'p'],
    ['séparation', 'fait de séparer : celle des Églises et de l’État date de 1905', 'p'],
    ['constitution', 'texte qui fixe les règles de fonctionnement d’un État', 'p'],
  ],
  'CM2.HI20.T2.ENERGIES': [
    ['charbon', 'roche noire qu’on brûle pour produire de la chaleur', 'f'],
    ['vapeur', 'eau devenue gaz en chauffant ; elle fait avancer les locomotives', 'f'],
    ['usine', 'grand bâtiment où l’on fabrique des objets avec des machines', 'f'],
    ['train', 'suite de wagons tirés par une locomotive', 'f'],
    ['machine', 'appareil qui fait un travail à la place de l’homme', 'f'],
    ['pétrole', 'liquide noir tiré du sous-sol, qui donne l’essence', 'f'],
    ['locomotive', 'machine qui tire les wagons d’un train', 'n'],
    ['électricité', 'énergie qui fait briller les ampoules et tourner les moteurs', 'n'],
    ['industrie', 'activités qui fabriquent des produits en grande quantité', 'n'],
    ['invention', 'création d’un objet ou d’une machine qui n’existait pas', 'n'],
    ['énergie', 'ce qui permet de produire un mouvement, de la chaleur ou de la lumière', 'n'],
    ['moteur', 'appareil qui transforme une énergie en mouvement', 'n'],
    ['combustible', 'matière qu’on brûle pour produire de l’énergie', 'p'],
    ['mécanisation', 'remplacement du travail à la main par des machines', 'p'],
    ['industrialisation', 'développement des usines et des machines dans un pays', 'p'],
  ],
  'CM2.HI20.T2.TRAVAIL': [
    ['ouvrier', 'personne qui travaille de ses mains, à l’usine ou à l’atelier', 'f'],
    ['usine', 'grand bâtiment où l’on fabrique des objets avec des machines', 'f'],
    ['mine', 'lieu creusé sous terre pour extraire le charbon', 'f'],
    ['salaire', 'argent gagné en échange de son travail', 'f'],
    ['atelier', 'lieu où des artisans ou des ouvriers fabriquent des objets', 'f'],
    ['magasin', 'lieu où l’on vend des marchandises', 'f'],
    ['grève', 'arrêt du travail pour réclamer de meilleures conditions', 'n'],
    ['syndicat', 'association de travailleurs qui défendent leurs droits', 'n'],
    [
      'mineur',
      'ouvrier qui travaille dans une mine',
      'n',
      'Le mineur descend chaque matin au fond de la mine.',
    ],
    ['patron', 'personne qui dirige une entreprise et emploie des ouvriers', 'n'],
    ['galerie', 'couloir creusé sous terre dans une mine', 'n'],
    ['vendeuse', 'employée d’un magasin qui sert les clients', 'n'],
    ['chômage', 'situation d’une personne qui cherche un travail sans en trouver', 'p'],
    ['manufacture', 'grand atelier où de nombreux ouvriers fabriquent des objets', 'p'],
    ['coron', 'maison d’ouvrier mineur, alignée avec d’autres près de la mine', 'p'],
  ],
  'CM2.HI20.T2.VILLE': [
    ['ville', 'grande agglomération où vivent beaucoup d’habitants', 'f'],
    ['campagne', 'espace de champs, de prés et de villages', 'f'],
    ['paysan', 'personne qui cultive la terre et élève des animaux', 'f'],
    ['village', 'petite agglomération à la campagne', 'f'],
    ['ferme', 'maison et bâtiments d’une exploitation agricole', 'f'],
    ['rue', 'voie bordée de maisons, dans une ville ou un village', 'f'],
    ['exode', 'départ d’un grand nombre de personnes : l’___ rural', 'n'],
    ['rural', 'qui concerne la campagne', 'n'],
    ['urbain', 'qui concerne la ville', 'n'],
    ['boulevard', 'large avenue souvent bordée d’arbres', 'n'],
    ['immeuble', 'grand bâtiment de plusieurs étages', 'n'],
    ['banlieue', 'communes situées autour d’une grande ville', 'n'],
    ['urbanisation', 'croissance des villes', 'p'],
    ['agglomération', 'ville et ses communes voisines qui se touchent', 'p'],
    ['Haussmann', 'préfet qui a transformé Paris sous Napoléon III', 'p'],
  ],
  'CM2.HI20.T3.GUERRES': [
    ['guerre', 'conflit armé entre des pays', 'f'],
    ['paix', 'situation d’un pays qui n’est pas en guerre', 'f'],
    ['soldat', 'personne qui fait partie d’une armée', 'f'],
    ['poilu', 'surnom des soldats français de la Première Guerre mondiale', 'f'],
    ['armée', 'ensemble des soldats d’un pays', 'f'],
    ['tranchée', 'long fossé où vivaient et combattaient les soldats de 1914-1918', 'f'],
    ['armistice', 'accord qui arrête les combats, signé le 11 novembre 1918', 'n'],
    ['résistant', 'personne qui combattait en secret l’occupation allemande', 'n'],
    ['occupation', 'contrôle d’un pays par une armée ennemie', 'n'],
    ['débarquement', 'arrivée des soldats alliés en Normandie, le 6 juin 1944', 'n'],
    ['mondiale', 'se dit d’une guerre qui touche le monde entier', 'n'],
    ['libération', 'fin de l’occupation allemande, en 1944', 'n'],
    ['collaboration', 'aide apportée à l’occupant allemand par le régime de Vichy', 'p'],
    ['Shoah', 'génocide des Juifs d’Europe pendant la Seconde Guerre mondiale', 'p'],
    ['déportation', 'transfert forcé de personnes vers des camps', 'p'],
  ],
  'CM2.HI20.T3.EUROPE': [
    ['Europe', 'continent où se trouve la France', 'f'],
    ['paix', 'situation de pays qui ne se font pas la guerre', 'f'],
    ['euro', 'monnaie commune de nombreux pays de l’Union européenne', 'f'],
    ['pays', 'territoire avec ses habitants et son gouvernement', 'f'],
    ['drapeau', 'emblème : celui de l’Union européenne a douze étoiles sur fond bleu', 'f'],
    ['union', 'association de plusieurs pays : l’___ européenne', 'f'],
    ['traité', 'accord écrit signé entre plusieurs pays', 'n'],
    ['fondateur', 'qui a créé quelque chose : six pays l’ont été pour l’Europe en 1957', 'n'],
    ['monnaie', 'pièces et billets qui servent à payer', 'n'],
    ['frontière', 'limite entre deux pays', 'n'],
    ['européen', 'qui concerne l’Europe', 'n'],
    ['membre', 'pays qui fait partie de l’Union européenne', 'n'],
    ['communauté', 'groupe de pays : la ___ économique européenne date de 1957', 'p'],
    ['Parlement', 'assemblée élue qui vote les lois', 'p'],
    ['citoyenneté', 'fait d’être citoyen, avec des droits et des devoirs', 'p'],
  ],
  'CM2.HI26.T1': [
    ['empereur', 'souverain qui dirige un empire, comme Napoléon Ier', 'f'],
    ['Napoléon', 'général devenu empereur des Français en 1804', 'f'],
    ['sacre', 'cérémonie religieuse qui consacre un roi ou un empereur', 'f'],
    ['république', 'régime politique sans roi, où les dirigeants sont élus', 'f'],
    ['empire', 'État dirigé par un empereur', 'f'],
    ['armée', 'ensemble des soldats d’un pays', 'f'],
    ['Marseillaise', 'chant écrit en avril 1792, devenu l’hymne national', 'n'],
    ['préfet', 'représentant de l’État dans un département, créé par Napoléon', 'n'],
    ['lycée', 'établissement créé par Napoléon pour former les futurs dirigeants', 'n'],
    ['code', 'recueil de lois : le ___ civil date de 1804', 'n'],
    ['pétition', 'demande écrite signée par plusieurs personnes', 'n'],
    [
      'esclavage',
      'situation d’une personne privée de liberté et vendue ; aboli une première fois en 1794',
      'n',
    ],
    ['consul', 'titre de Napoléon Bonaparte avant qu’il devienne empereur', 'p'],
    ['abolition', 'suppression d’une loi ou d’une pratique', 'p'],
    ['rétablissement', 'fait de remettre en place ce qui avait été supprimé', 'p'],
  ],
  'CM2.HI26.T2': [
    ['vote', 'choix exprimé par un électeur', 'f'],
    ['école', 'lieu où les enfants apprennent', 'f'],
    ['presse', 'ensemble des journaux', 'f'],
    ['Marianne', 'figure de femme qui représente la République', 'f'],
    ['loi', 'règle votée qui s’applique à tous', 'f'],
    ['liberté', 'droit de faire ce que l’on veut sans nuire aux autres', 'f'],
    ['suffrage', 'vote ; il devient universel pour les hommes en 1848', 'n'],
    ['universel', 'qui concerne tout le monde', 'n'],
    ['abolition', 'suppression d’une pratique, comme l’esclavage en 1848', 'n'],
    ['laïque', 'qui ne dépend d’aucune religion, comme l’école publique', 'n'],
    ['séparation', 'fait de séparer : celle des Églises et de l’État date de 1905', 'n'],
    ['colonie', 'territoire dominé et exploité par un pays étranger', 'n'],
    ['laïcité', 'principe qui sépare les religions et l’État', 'p'],
    ['obligatoire', 'imposé par la loi : l’instruction l’est depuis 1882', 'p'],
    ['colonial', 'qui concerne les colonies : l’empire ___ français', 'p'],
  ],
  'CM2.HI26.T3': [
    ['usine', 'grand bâtiment où l’on fabrique des objets avec des machines', 'f'],
    ['charbon', 'roche noire qu’on brûle pour produire de la chaleur', 'f'],
    ['ouvrier', 'personne qui travaille de ses mains, à l’usine ou à l’atelier', 'f'],
    ['train', 'suite de wagons tirés par une locomotive', 'f'],
    ['vaccin', 'produit qui protège d’une maladie', 'f'],
    ['ville', 'grande agglomération où vivent beaucoup d’habitants', 'f'],
    ['locomotive', 'machine à vapeur qui tire les wagons d’un train', 'n'],
    ['rage', 'maladie grave contre laquelle Pasteur a créé un vaccin en 1885', 'n'],
    ['bourgeois', 'personne aisée de la ville : patron, banquier, commerçant…', 'n'],
    ['grève', 'arrêt du travail pour réclamer de meilleures conditions', 'n'],
    ['syndicat', 'association de travailleurs qui défendent leurs droits', 'n'],
    ['Pasteur', 'savant qui a mis au point le vaccin contre la rage', 'n'],
    ['urbanisation', 'croissance des villes', 'p'],
    ['exode', 'départ d’un grand nombre de personnes : l’___ rural', 'p'],
    ['industrialisation', 'développement des usines et des machines dans un pays', 'p'],
  ],
  'CM2.HI26.T4': [
    ['guerre', 'conflit armé entre des pays', 'f'],
    ['soldat', 'personne qui fait partie d’une armée', 'f'],
    ['poilu', 'surnom des soldats français de 1914-1918', 'f'],
    ['front', 'ligne où les armées ennemies se font face', 'f'],
    ['paix', 'situation d’un pays qui n’est pas en guerre', 'f'],
    ['casque', 'protection en métal que les soldats portent sur la tête', 'f'],
    ['tranchée', 'long fossé où vivaient et combattaient les soldats', 'n'],
    ['armistice', 'accord qui arrête les combats, signé le 11 novembre 1918', 'n'],
    ['Verdun', 'grande bataille de 1916, dans l’est de la France', 'n'],
    ['mobilisation', 'appel des hommes à rejoindre l’armée', 'n'],
    ['bataille', 'combat entre deux armées', 'n'],
    ['monument', 'construction qui rappelle un événement ou des personnes : celui aux morts', 'n'],
    ['colonie', 'territoire dominé par un pays étranger ; beaucoup de soldats en sont venus', 'p'],
    ['commémoration', 'cérémonie du souvenir, comme chaque 11 novembre', 'p'],
    ['position', 'la guerre de ___ : chaque armée reste dans ses tranchées', 'p'],
  ],
  'CM2.HI26.T5': [
    ['guerre', 'conflit armé entre des pays', 'f'],
    ['paix', 'situation d’un pays qui n’est pas en guerre', 'f'],
    ['appel', 'message radio du général de Gaulle, le 18 juin 1940', 'f'],
    ['armée', 'ensemble des soldats d’un pays', 'f'],
    ['résistant', 'personne qui combattait en secret l’occupation allemande', 'f'],
    ['défaite', 'fait de perdre une guerre ou une bataille', 'f'],
    ['occupation', 'contrôle d’un pays par une armée ennemie', 'n'],
    ['collaboration', 'aide apportée à l’occupant allemand par le régime de Vichy', 'n'],
    ['débarquement', 'arrivée des soldats alliés en Normandie, le 6 juin 1944', 'n'],
    ['Vichy', 'ville où s’installe le gouvernement du maréchal Pétain', 'n'],
    ['libération', 'fin de l’occupation allemande, en 1944', 'n'],
    ['Résistance', 'ensemble des personnes et des groupes qui luttaient contre l’occupant', 'n'],
    ['Shoah', 'génocide des Juifs d’Europe pendant la Seconde Guerre mondiale', 'p'],
    ['déportation', 'transfert forcé de personnes vers des camps', 'p'],
    ['rafle', 'arrestation de nombreuses personnes en même temps, comme celle du Vél d’Hiv', 'p'],
  ],
  'CM2.HI26.T6': [
    ['vote', 'choix exprimé par un électeur', 'f'],
    ['euro', 'monnaie qui remplace le franc', 'f'],
    ['franc', 'ancienne monnaie de la France, avant l’euro', 'f', 'Mes grands-parents payaient en francs.'],
    ['président', 'chef de l’État élu, dans la République française', 'f'],
    ['Europe', 'continent où se trouve la France', 'f'],
    ['femme', 'en 1944, elle obtient le droit de vote en France', 'f'],
    ['constitution', 'texte qui fixe les règles de l’État : celle de la Ve République date de 1958', 'n'],
    ['traité', 'accord écrit signé entre plusieurs pays', 'n'],
    ['monnaie', 'pièces et billets qui servent à payer', 'n'],
    ['égalité', 'fait d’avoir les mêmes droits que les autres', 'n'],
    ['référendum', 'vote où les citoyens répondent par oui ou par non', 'n'],
    ['sécurité', 'la ___ sociale rembourse les soins depuis 1945', 'n'],
    ['communauté', 'groupe de pays : la ___ économique européenne date de 1957', 'p'],
    ['décolonisation', 'fait pour un territoire dominé par un autre pays de devenir libre', 'p'],
    ['indépendance', 'situation d’un pays libre de se gouverner lui-même', 'p'],
  ],

  /* ------------------------------ Géographie ------------------------------ */
  'CM2.GE20.T1.DEPLACER': [
    ['train', 'suite de wagons qui roulent sur des rails', 'f'],
    ['avion', 'appareil qui vole et transporte des passagers', 'f'],
    ['voiture', 'véhicule à quatre roues avec un moteur', 'f'],
    ['vélo', 'véhicule à deux roues qu’on fait avancer avec des pédales', 'f'],
    ['métro', 'train qui circule souvent sous terre dans une grande ville', 'f'],
    ['route', 'voie pour les voitures et les camions', 'f'],
    ['aéroport', 'lieu où les avions décollent et atterrissent', 'n'],
    ['autoroute', 'large route rapide, sans croisement', 'n'],
    ['réseau', 'ensemble de routes ou de lignes reliées entre elles', 'n'],
    ['transport', 'moyen de se déplacer ou de déplacer des marchandises', 'n'],
    ['tramway', 'train léger qui roule sur des rails dans la ville', 'n'],
    ['gare', 'lieu où les trains s’arrêtent', 'n'],
    ['embouteillage', 'bouchon de voitures qui avancent très lentement', 'p'],
    ['covoiturage', 'fait de partager une voiture pour faire le même trajet', 'p'],
    ['pendulaire', 'se dit des trajets de chaque jour entre la maison et le travail', 'p'],
  ],
  'CM2.GE20.T2.INTERNET': [
    ['écran', 'surface sur laquelle s’affichent les images', 'f'],
    ['câble', 'gros fil qui transporte l’électricité ou les données', 'f'],
    ['message', 'information envoyée à quelqu’un', 'f'],
    ['réseau', 'ensemble d’appareils ou de lignes reliés entre eux', 'f'],
    ['ordinateur', 'machine électronique qui traite des informations', 'f'],
    ['antenne', 'appareil qui envoie ou reçoit des ondes', 'f'],
    ['satellite', 'engin placé en orbite autour de la Terre', 'n'],
    ['connexion', 'fait d’être relié à Internet', 'n'],
    ['numérique', 'qui concerne les ordinateurs et Internet', 'n'],
    ['fibre', 'fil très fin qui transporte Internet à grande vitesse', 'n'],
    [
      'serveur',
      'ordinateur puissant qui stocke des données pour Internet',
      'n',
      'Le site est stocké sur un serveur.',
    ],
    ['données', 'informations stockées et échangées par les ordinateurs', 'n'],
    ['inégalité', 'différence injuste : tout le monde n’a pas accès à Internet', 'p'],
    ['couverture', 'zone où un réseau est disponible', 'p'],
    ['télétravail', 'travail fait depuis chez soi grâce à Internet', 'p'],
  ],
  'CM2.GE20.T3.HABITER': [
    ['maison', 'bâtiment où l’on habite', 'f'],
    ['jardin', 'terrain où l’on cultive des fleurs ou des légumes', 'f'],
    ['arbre', 'grande plante au tronc de bois', 'f'],
    ['parc', 'grand jardin public', 'f'],
    ['quartier', 'partie d’une ville', 'f'],
    ['déchet', 'ce qui reste et qu’on jette', 'f'],
    ['écoquartier', 'ensemble d’habitations construit pour respecter l’environnement', 'n'],
    ['recyclage', 'transformation d’un déchet en nouvel objet', 'n'],
    ['compost', 'mélange de déchets végétaux qui devient de l’engrais', 'n'],
    ['pollution', 'salissure de l’air, de l’eau ou du sol', 'n'],
    ['logement', 'lieu où l’on habite : maison ou appartement', 'n'],
    ['énergie', 'ce qui permet de chauffer, d’éclairer, de faire fonctionner les machines', 'n'],
    ['isolation', 'ce qui empêche la chaleur de sortir d’un bâtiment', 'p'],
    ['biodiversité', 'variété des êtres vivants dans un milieu', 'p'],
    ['végétalisation', 'fait d’installer des plantes sur les murs, les toits ou les places', 'p'],
  ],
  'CM2.GE.REPERES': [
    ['fleuve', 'cours d’eau qui se jette dans la mer', 'f'],
    ['mer', 'grande étendue d’eau salée, plus petite qu’un océan', 'f', 'La Méditerranée est une mer.'],
    ['océan', 'très grande étendue d’eau salée entre les continents', 'f'],
    ['montagne', 'relief très élevé', 'f'],
    ['continent', 'très grande étendue de terre, comme l’Afrique', 'f'],
    ['région', 'partie du territoire : la France en compte 18', 'f'],
    ['carte', 'représentation d’un territoire vu d’en haut', 'f'],
    ['massif', 'ensemble de montagnes', 'n'],
    ['capitale', 'ville où siège le gouvernement d’un pays', 'n'],
    ['frontière', 'limite entre deux pays', 'n'],
    ['Pyrénées', 'massif à la frontière entre la France et l’Espagne', 'n'],
    ['Garonne', 'fleuve qui passe à Toulouse et à Bordeaux', 'n'],
    ['Rhône', 'fleuve qui passe à Lyon et se jette dans la Méditerranée', 'n'],
    ['planisphère', 'carte du monde entier à plat', 'p'],
    ['hémisphère', 'moitié de la Terre, au nord ou au sud de l’équateur', 'p'],
    ['Méditerranée', 'mer au sud de la France', 'p'],
  ],
  'CM2.GE26.T1': [
    ['commune', 'plus petite division du territoire, dirigée par un maire', 'f'],
    ['région', 'grande partie du territoire : la France en compte 18', 'f'],
    ['ville', 'grande agglomération où vivent beaucoup d’habitants', 'f'],
    ['carte', 'représentation d’un territoire vu d’en haut', 'f'],
    ['route', 'voie pour les voitures et les camions', 'f'],
    ['maire', 'personne élue qui dirige la commune', 'f', 'Le maire dirige la commune.'],
    ['département', 'division du territoire entre la commune et la région', 'n'],
    ['agglomération', 'grande ville et ses communes voisines qui se touchent', 'n'],
    ['préfecture', 'ville où siège le préfet d’un département ou d’une région', 'n'],
    ['autoroute', 'large route rapide, sans croisement', 'n'],
    ['territoire', 'espace qui appartient à un pays', 'n'],
    ['métropole', 'très grande ville qui attire les habitants et les entreprises', 'n'],
    ['périurbain', 'situé autour d’une ville, entre ville et campagne', 'p'],
    ['littoral', 'bande de terre au bord de la mer', 'p'],
    ['intercommunalité', 'regroupement de villes et de villages qui travaillent ensemble', 'p'],
  ],
  'CM2.GE26.T2': [
    ['eau', 'liquide indispensable à la vie', 'f'],
    ['fleuve', 'cours d’eau qui se jette dans la mer', 'f'],
    ['lac', 'étendue d’eau douce entourée de terre', 'f'],
    ['rivière', 'cours d’eau qui se jette dans un autre cours d’eau', 'f'],
    ['pluie', 'eau qui tombe des nuages', 'f'],
    ['source', 'endroit où l’eau sort de la terre', 'f'],
    ['barrage', 'mur qui retient l’eau d’une rivière', 'n'],
    ['irrigation', 'arrosage des champs grâce à des canaux ou des tuyaux', 'n'],
    ['nappe', 'une ___ phréatique : eau stockée sous la terre', 'n'],
    ['potable', 'qu’on peut boire sans danger', 'n'],
    ['Léman', 'grand lac naturel entre la France et la Suisse', 'n'],
    ['sécheresse', 'longue période sans pluie', 'n'],
    ['phréatique', 'se dit de la nappe d’eau stockée sous la terre', 'p'],
    ['hydroélectricité', 'courant électrique produit grâce à la force de l’eau', 'p'],
    ['assainissement', 'nettoyage des eaux usées avant de les rendre à la nature', 'p'],
  ],
  'CM2.GE26.T3': [
    ['Europe', 'continent où se trouve la France', 'f'],
    ['pays', 'territoire avec ses habitants et son gouvernement', 'f'],
    ['euro', 'monnaie commune de nombreux pays de l’Union européenne', 'f'],
    ['drapeau', 'emblème : celui de l’Union européenne a douze étoiles sur fond bleu', 'f'],
    ['union', 'association de plusieurs pays : l’___ européenne', 'f'],
    ['carte', 'représentation d’un territoire vu d’en haut', 'f'],
    ['membre', 'pays qui fait partie de l’Union européenne', 'n'],
    ['traité', 'accord écrit signé entre plusieurs pays', 'n'],
    ['frontière', 'limite entre deux pays', 'n'],
    ['Parlement', 'assemblée élue qui vote les lois européennes', 'n'],
    ['fondateur', 'qui a créé quelque chose : six pays l’ont été en 1957', 'n'],
    ['continent', 'très grande étendue de terre, comme l’Europe', 'n'],
    ['Strasbourg', 'ville française où siège le Parlement européen', 'p'],
    ['Bruxelles', 'capitale de la Belgique, où siège la Commission européenne', 'p'],
    ['élargissement', 'arrivée de nouveaux pays dans l’Union européenne', 'p'],
  ],

  /* ------------------------------ Sciences ------------------------------ */
  'CM2.SC.MATIERE': [
    ['solide', 'état de la matière qui a une forme propre, comme la glace', 'f'],
    ['liquide', 'état de la matière qui coule et prend la forme du récipient', 'f'],
    ['gaz', 'état de la matière qui occupe tout l’espace, comme l’air', 'f'],
    ['glace', 'eau à l’état solide', 'f'],
    ['vapeur', 'eau à l’état de gaz', 'f'],
    ['mélange', 'ensemble de plusieurs matières mises ensemble', 'f'],
    ['fusion', 'passage de l’état solide à l’état liquide', 'n'],
    ['évaporation', 'passage lent de l’état liquide à l’état gazeux', 'n'],
    ['solidification', 'passage de l’état liquide à l’état solide', 'n'],
    ['dissolution', 'fait qu’un solide disparaît dans un liquide, comme le sucre dans l’eau', 'n'],
    ['masse', 'ce que mesure une balance, en grammes ou en kilogrammes', 'n'],
    ['volume', 'place occupée par un objet, en litres par exemple', 'n'],
    ['condensation', 'passage de l’état gazeux à l’état liquide', 'p'],
    ['ébullition', 'état d’un liquide qui bout, à 100 °C pour l’eau', 'p'],
    ['filtration', 'séparation d’un mélange en le faisant passer dans un filtre', 'p'],
    ['soluble', 'se dit d’une matière qui peut se dissoudre dans un liquide', 'p'],
  ],
  'CM2.SC.ENERGIE': [
    ['soleil', 'étoile qui nous donne lumière et chaleur', 'f', 'Le soleil chauffe la Terre.'],
    ['vent', 'air qui se déplace', 'f'],
    ['éolienne', 'grande hélice qui produit de l’électricité grâce au vent', 'f'],
    ['charbon', 'roche noire qu’on brûle pour produire de la chaleur', 'f'],
    ['pétrole', 'liquide noir tiré du sous-sol, qui donne l’essence', 'f'],
    ['pile', 'petit objet qui stocke de l’énergie électrique', 'f'],
    ['énergie', 'ce qui permet de produire un mouvement, de la chaleur ou de la lumière', 'n'],
    ['renouvelable', 'se dit d’une énergie qui ne s’épuise pas, comme le vent', 'n'],
    ['barrage', 'mur qui retient l’eau pour produire de l’électricité', 'n'],
    ['électricité', 'énergie qui fait briller les ampoules et tourner les moteurs', 'n'],
    ['dynamo', 'petit appareil qui produit de l’électricité quand on pédale', 'n'],
    ['centrale', 'usine qui produit de l’électricité', 'n'],
    ['fossile', 'se dit d’une énergie formée sous terre en des millions d’années', 'p'],
    ['géothermie', 'énergie tirée de la chaleur du sous-sol', 'p'],
    ['biomasse', 'énergie tirée du bois et des déchets végétaux', 'p'],
  ],
  'CM2.SC.MOUVEMENT': [
    ['vitesse', 'distance parcourue en un temps donné', 'f'],
    ['trajet', 'chemin parcouru pour aller d’un endroit à un autre', 'f'],
    ['rapide', 'qui va vite', 'f'],
    ['lent', 'qui ne va pas vite', 'f'],
    ['mouvement', 'déplacement d’un objet', 'f'],
    ['course', 'action de courir ou compétition de vitesse', 'f'],
    ['trajectoire', 'ligne suivie par un objet qui se déplace', 'n'],
    ['rectiligne', 'en ligne droite', 'n'],
    ['circulaire', 'en forme de cercle', 'n'],
    ['uniforme', 'se dit d’un mouvement dont la vitesse ne change pas', 'n'],
    ['accéléré', 'se dit d’un mouvement de plus en plus rapide', 'n'],
    ['ralenti', 'se dit d’un mouvement de plus en plus lent', 'n'],
    ['chronomètre', 'montre qui mesure une durée très précisément', 'p'],
    ['relatif', 'se dit d’un mouvement qui dépend de l’endroit d’où on l’observe', 'p'],
    ['kilomètre', 'unité de longueur égale à 1 000 mètres', 'p'],
  ],
  'CM2.SC.SIGNAL': [
    ['signal', 'son, lumière ou geste qui transmet un message', 'f'],
    ['son', 'ce qu’on entend', 'f', 'J’entends le son de la cloche.'],
    ['lumière', 'ce qui éclaire et permet de voir', 'f'],
    ['alarme', 'signal qui prévient d’un danger', 'f'],
    ['sonnerie', 'bruit d’une sonnette ou d’un téléphone qui sonne', 'f'],
    ['feu', 'le ___ tricolore règle la circulation', 'f'],
    ['Morse', 'code fait de traits et de points, inventé pour le télégraphe', 'n'],
    ['détecteur', 'appareil qui repère la fumée, un mouvement ou du métal', 'n'],
    ['capteur', 'élément qui mesure ou repère quelque chose, comme la lumière', 'n'],
    ['information', 'renseignement qu’on transmet', 'n'],
    ['message', 'information envoyée à quelqu’un', 'n'],
    ['émetteur', 'appareil ou personne qui envoie un signal', 'n'],
    ['récepteur', 'appareil ou personne qui reçoit un signal', 'p'],
    ['télégraphe', 'ancien appareil qui envoyait des messages à distance', 'p'],
    ['codage', 'transformation d’un message en signes', 'p'],
  ],
  'CM2.SC.VIVANT.CLASSER': [
    ['oiseau', 'animal qui a des plumes et un bec', 'f'],
    ['poisson', 'animal qui vit dans l’eau et respire avec des branchies', 'f'],
    ['insecte', 'petit animal qui a six pattes', 'f'],
    ['plume', 'ce qui recouvre le corps des oiseaux', 'f'],
    ['poil', 'ce qui recouvre le corps des mammifères', 'f'],
    ['mammifère', 'animal à poils dont les petits boivent le lait de leur mère', 'f'],
    ['vertébré', 'animal qui a une colonne vertébrale', 'n'],
    ['invertébré', 'animal qui n’a pas de colonne vertébrale', 'n'],
    ['reptile', 'animal à écailles, comme le lézard ou le serpent', 'n'],
    ['amphibien', 'animal qui vit dans l’eau puis sur terre, comme la grenouille', 'n'],
    ['arachnide', 'animal à huit pattes, comme l’araignée', 'n'],
    ['écaille', 'petite plaque qui recouvre la peau des poissons et des reptiles', 'n'],
    ['squelette', 'ensemble des os du corps', 'n'],
    ['classification', 'rangement des êtres vivants en groupes', 'p'],
    ['mollusque', 'animal au corps mou, souvent avec une coquille, comme l’escargot', 'p'],
    ['crustacé', 'animal à carapace, comme le crabe', 'p'],
  ],
  'CM2.SC.VIVANT.CORPS': [
    ['cœur', 'organe qui envoie le sang dans tout le corps', 'f'],
    ['poumon', 'organe de la respiration', 'f'],
    ['os', 'partie dure du squelette', 'f', 'Le fémur est un os de la jambe.'],
    ['muscle', 'organe qui se contracte pour faire bouger le corps', 'f'],
    ['sang', 'liquide rouge qui circule dans le corps', 'f', 'Le sang circule dans les vaisseaux.'],
    ['estomac', 'poche où les aliments sont malaxés pendant la digestion', 'f'],
    ['digestion', 'transformation des aliments en nutriments', 'n'],
    ['respiration', 'échanges d’air entre le corps et l’extérieur', 'n'],
    ['circulation', 'trajet du sang dans le corps', 'n'],
    ['articulation', 'endroit où deux os se rejoignent, comme le genou', 'n'],
    ['intestin', 'long tube où les nutriments passent dans le sang', 'n'],
    ['artère', 'vaisseau qui transporte le sang du cœur vers les organes', 'n'],
    ['oxygène', 'gaz de l’air indispensable à la vie', 'n'],
    ['œsophage', 'tube qui conduit les aliments de la bouche à l’estomac', 'p'],
    ['alvéole', 'minuscule sac des poumons où l’oxygène passe dans le sang', 'p'],
    ['tendon', 'attache qui relie un muscle à un os', 'p'],
    ['nutriment', 'petite partie des aliments que le sang transporte', 'p'],
  ],
  'CM2.SC.VIVANT.ECOSYS': [
    ['plante', 'être vivant qui fabrique sa nourriture grâce à la lumière', 'f'],
    ['proie', 'animal mangé par un autre', 'f'],
    ['herbivore', 'animal qui se nourrit de végétaux', 'f'],
    ['carnivore', 'animal qui se nourrit d’autres animaux', 'f'],
    ['forêt', 'grand espace couvert d’arbres', 'f'],
    ['prédateur', 'animal qui chasse d’autres animaux pour les manger', 'f'],
    ['producteur', 'être vivant qui fabrique sa matière, comme une plante verte', 'n'],
    ['consommateur', 'être vivant qui mange d’autres êtres vivants', 'n'],
    ['décomposeur', 'être vivant qui transforme les restes morts en sels minéraux', 'n'],
    ['chaîne', 'une ___ alimentaire : qui est mangé par qui', 'n'],
    ['omnivore', 'animal qui mange de tout, végétaux et animaux', 'n'],
    ['biodiversité', 'variété des êtres vivants dans un milieu', 'n'],
    ['écosystème', 'milieu et ensemble des êtres vivants qui y vivent', 'p'],
    ['photosynthèse', 'fabrication de matière par les plantes grâce à la lumière', 'p'],
    ['espèce', 'groupe d’êtres vivants semblables qui peuvent se reproduire entre eux', 'p'],
  ],
  'CM2.SC.TERRE': [
    ['Terre', 'planète sur laquelle nous vivons', 'f'],
    ['Soleil', 'étoile au centre du système solaire', 'f'],
    ['Lune', 'satellite naturel de la Terre', 'f'],
    ['planète', 'astre qui tourne autour d’une étoile', 'f'],
    ['étoile', 'astre qui produit sa propre lumière', 'f'],
    ['saison', 'chacune des quatre parties de l’année', 'f'],
    ['rotation', 'mouvement de la Terre sur elle-même, en 24 heures', 'n'],
    ['révolution', 'tour complet de la Terre autour du Soleil, en un an', 'n'],
    ['volcan', 'montagne d’où peut sortir de la lave', 'n'],
    ['séisme', 'tremblement de terre', 'n'],
    ['orbite', 'trajet d’un astre autour d’un autre', 'n'],
    ['satellite', 'objet qui tourne autour d’une planète', 'n'],
    ['équateur', 'ligne imaginaire qui partage la Terre en deux moitiés', 'n'],
    ['éclipse', 'disparition du Soleil ou de la Lune caché par un autre astre', 'p'],
    ['hémisphère', 'moitié de la Terre, au nord ou au sud de l’équateur', 'p'],
    ['magma', 'roche fondue sous la surface de la Terre', 'p'],
    ['solstice', 'jour le plus long ou le plus court de l’année', 'p'],
  ],
  'CM2.SC.TECHNO': [
    ['objet', 'chose fabriquée qu’on peut voir et toucher', 'f'],
    ['bois', 'matériau tiré des arbres', 'f'],
    ['métal', 'matériau dur et brillant, comme le fer ou le cuivre', 'f'],
    ['verre', 'matériau transparent et fragile', 'f'],
    ['plastique', 'matériau fabriqué à partir du pétrole', 'f'],
    ['outil', 'objet qui sert à faire un travail', 'f'],
    ['matériau', 'matière qui sert à fabriquer un objet', 'n'],
    ['conducteur', 'matériau qui laisse passer le courant électrique', 'n'],
    ['isolant', 'matériau qui ne laisse pas passer le courant électrique', 'n'],
    ['algorithme', 'suite d’instructions pour résoudre un problème', 'n'],
    ['fonction', 'à quoi sert un objet', 'n'],
    ['programme', 'suite d’instructions donnée à un robot ou à un ordinateur', 'n'],
    ['prototype', 'premier modèle d’un objet, fabriqué pour l’essayer', 'p'],
    ['programmation', 'fait d’écrire des instructions pour une machine', 'p'],
    ['recyclable', 'qui peut être transformé en un nouvel objet', 'p'],
  ],

  /* ------------------------------ EMC ------------------------------ */
  'CM2.EMC.VALEURS': [
    ['liberté', 'droit de faire ce que l’on veut sans nuire aux autres', 'f'],
    ['égalité', 'fait d’avoir les mêmes droits que les autres', 'f'],
    ['fraternité', 'lien d’entraide et d’amitié entre les citoyens', 'f'],
    ['drapeau', 'emblème bleu, blanc, rouge de la France', 'f'],
    ['Marianne', 'figure de femme qui représente la République', 'f'],
    ['devise', 'courte phrase qui résume des valeurs', 'f'],
    ['laïcité', 'principe qui sépare les religions et l’État et protège la liberté de croire ou non', 'n'],
    ['République', 'régime politique de la France, sans roi, où les dirigeants sont élus', 'n'],
    ['Marseillaise', 'hymne national de la France', 'n'],
    ['symbole', 'image ou objet qui représente une idée', 'n'],
    ['citoyen', 'membre d’un pays qui a des droits et des devoirs', 'n'],
    ['tricolore', 'qui a trois couleurs, comme le drapeau français', 'n'],
    ['charte', 'texte qui rappelle des règles : celle de la laïcité est affichée à l’école', 'p'],
    ['discrimination', 'fait de traiter une personne plus mal à cause de ce qu’elle est', 'p'],
    ['tolérance', 'respect des idées et des façons de vivre des autres', 'p'],
  ],
  'CM2.EMC.INSTITUTIONS': [
    ['maire', 'personne élue qui dirige la commune', 'f', 'Le maire dirige la commune.'],
    ['vote', 'choix exprimé par un électeur', 'f'],
    ['loi', 'règle votée qui s’applique à tous', 'f'],
    ['président', 'chef de l’État, élu pour cinq ans', 'f'],
    ['commune', 'plus petite division du territoire, dirigée par un maire', 'f'],
    ['élection', 'choix de représentants par un vote', 'f'],
    ['Parlement', 'Assemblée nationale et Sénat, qui votent les lois', 'n'],
    ['Sénat', 'une des deux assemblées du Parlement, avec l’Assemblée nationale', 'n'],
    ['député', 'élu de l’Assemblée nationale', 'n'],
    ['sénateur', 'membre du Sénat', 'n'],
    ['gouvernement', 'Premier ministre et ministres qui dirigent la politique du pays', 'n'],
    ['ministre', 'membre du gouvernement chargé d’un domaine, comme l’éducation', 'n'],
    ['municipal', 'qui concerne la commune : le conseil ___', 'p'],
    ['mandat', 'durée pendant laquelle un élu exerce sa fonction', 'p'],
    ['scrutin', 'vote, élection', 'p'],
  ],
  'CM2.EMC.DROITS': [
    ['droit', 'ce que chacun peut faire ou recevoir, et qui est protégé', 'f'],
    ['devoir', 'ce que chacun doit faire', 'f'],
    ['enfant', 'personne de moins de 18 ans, protégée par une convention de 1989', 'f'],
    ['égalité', 'fait d’avoir les mêmes droits que les autres', 'f'],
    ['école', 'lieu où les enfants ont le droit d’apprendre', 'f'],
    ['famille', 'parents et enfants qui vivent ensemble', 'f'],
    ['convention', 'accord signé par des pays : celle des droits de l’enfant date de 1989', 'n'],
    ['protection', 'ce qui met à l’abri d’un danger', 'n'],
    ['éducation', 'droit d’apprendre, d’aller à l’école', 'n'],
    ['santé', 'bon état du corps et de l’esprit', 'n'],
    ['respect', 'attention et politesse envers les autres', 'n'],
    ['mixité', 'fait que filles et garçons sont ensemble', 'n'],
    ['discrimination', 'fait de traiter une personne plus mal à cause de ce qu’elle est', 'p'],
    ['dignité', 'respect que mérite toute personne', 'p'],
    ['maltraitance', 'fait de faire du mal à un enfant ; on peut appeler le 119', 'p'],
  ],
  'CM2.EMC.HARCELEMENT': [
    ['victime', 'personne qui subit un tort', 'f'],
    ['témoin', 'personne qui voit ce qui se passe', 'f'],
    ['adulte', 'grande personne à qui l’on peut demander de l’aide', 'f'],
    ['aide', 'soutien qu’on apporte à quelqu’un', 'f'],
    ['respect', 'attention et politesse envers les autres', 'f'],
    ['moquerie', 'parole qui se moque de quelqu’un', 'f'],
    ['harcèlement', 'violences répétées, en paroles ou en gestes, contre une même personne', 'n'],
    ['insulte', 'parole blessante dite à quelqu’un', 'n'],
    ['rumeur', 'histoire qui circule sans qu’on sache si elle est vraie', 'n'],
    ['confiance', 'sentiment qui permet de compter sur quelqu’un', 'n'],
    ['solidarité', 'aide qu’on s’apporte les uns aux autres', 'n'],
    ['cyberharcèlement', 'violences répétées contre une personne, sur Internet ou par téléphone', 'n'],
    ['signalement', 'fait de prévenir un adulte ou d’appeler le 3018', 'p'],
    ['empathie', 'capacité à comprendre ce que ressent l’autre', 'p'],
    ['intimidation', 'fait de faire peur à quelqu’un pour le dominer', 'p'],
  ],
  'CM2.EMC.NUMERIQUE': [
    ['écran', 'surface sur laquelle s’affichent les images', 'f'],
    ['photo', 'image prise avec un appareil ou un téléphone', 'f'],
    ['message', 'information envoyée à quelqu’un', 'f'],
    ['inconnu', 'personne qu’on n’a jamais rencontrée', 'f'],
    ['parents', 'adultes à qui l’on parle de ce qui gêne sur Internet', 'f'],
    ['site', 'ensemble de pages sur Internet', 'f'],
    ['pseudonyme', 'nom inventé qu’on utilise sur Internet', 'n'],
    ['source', 'origine d’une information', 'n'],
    ['arnaque', 'tromperie pour voler de l’argent ou des informations', 'n'],
    ['réseau', 'un ___ social : site où l’on partage des messages et des photos', 'n'],
    ['sécurité', 'protection contre les dangers', 'n'],
    ['vérification', 'fait de contrôler qu’une information est vraie', 'n'],
    ['désinformation', 'diffusion volontaire de fausses informations', 'p'],
    ['confidentialité', 'protection des informations personnelles', 'p'],
    ['hameçonnage', 'faux message qui cherche à voler des informations personnelles', 'p'],
  ],
  'CM2.EMC.ENGAGEMENT': [
    ['délégué', 'élève élu pour représenter sa classe', 'f'],
    ['vote', 'choix exprimé par un électeur', 'f'],
    ['aide', 'soutien qu’on apporte à quelqu’un', 'f'],
    ['classe', 'groupe d’élèves qui travaillent ensemble', 'f'],
    ['planète', 'la Terre, qu’il faut protéger', 'f'],
    ['élection', 'choix de représentants par un vote', 'f'],
    ['solidarité', 'aide qu’on s’apporte les uns aux autres', 'n'],
    ['bénévole', 'personne qui aide sans être payée', 'n'],
    ['association', 'groupe de personnes réunies pour un même projet', 'n'],
    ['engagement', 'fait de participer à une action utile aux autres', 'n'],
    ['urne', 'boîte où l’on dépose son bulletin de vote', 'n'],
    ['candidat', 'personne qui se présente à une élection', 'n'],
    ['citoyenneté', 'fait d’être citoyen, avec des droits et des devoirs', 'p'],
    ['humanitaire', 'qui vient en aide aux personnes en difficulté', 'p'],
    ['écodélégué', 'élève élu pour mener des actions en faveur de l’environnement', 'p'],
  ],
};
