/**
 * Sciences et technologie CM2 — programme 2020 du cycle 3 (BO n°31 du 30/07/2020), en vigueur en 2026-2027.
 * Le corps humain est traité de façon sobre et scientifique ; les deux items sur la puberté portent
 * `meta.puberte = true` pour qu'un futur réglage parent puisse les masquer.
 */
import type { Fiche } from './outils';

const MATIERE: Fiche = {
  lecon: 'CM2.SC.MATIERE',
  classements: [
    {
      id: 'etats',
      niv: 'f',
      prompt: 'Solide, liquide ou gaz ?',
      cats: ['solide', 'liquide', 'gaz'],
      els: [
        ['le glaçon', 0, '🧊'],
        ['le caillou', 0, '🪨'],
        ['la planche de bois', 0, '🪵'],
        ['le jus de pomme', 1, '🧃'],
        ['le lait', 1, '🥛'],
        ['l’huile', 1],
        ['l’air', 2, '🌬️'],
        ['la vapeur d’eau', 2, '♨️'],
      ],
      e: 'Un solide garde sa forme, un liquide coule et prend la forme du récipient, un gaz occupe tout l’espace.',
    },
    {
      id: 'dissoudre',
      niv: 'n',
      prompt: 'Dans l’eau, ces matières se dissolvent-elles ?',
      cats: ['se dissout (on ne la voit plus)', 'ne se dissout pas'],
      els: [
        ['le sel', 0, '🧂'],
        ['le sucre', 0, '🍬'],
        ['le café soluble', 0, '☕'],
        ['le sucre en morceau', 0],
        ['le sable', 1, '🏖️'],
        ['l’huile', 1],
        ['les cailloux', 1, '🪨'],
        ['le poivre', 1],
      ],
      e: 'Le sel et le sucre se dissolvent : on ne les voit plus, mais ils sont toujours là. Le sable et l’huile restent visibles.',
    },
    {
      id: 'changements',
      niv: 'n',
      prompt: 'Quel changement d’état se produit ?',
      cats: [
        'fusion (solide → liquide)',
        'solidification (liquide → solide)',
        'vaporisation (liquide → gaz)',
        'condensation (gaz → liquide)',
      ],
      els: [
        ['le glaçon fond au soleil', 0, '🧊'],
        ['le beurre fond dans la poêle', 0, '🧈'],
        ['l’eau gèle au congélateur', 1, '❄️'],
        ['la cire de la bougie durcit', 1, '🕯️'],
        ['l’eau bout dans la casserole', 2, '♨️'],
        ['la flaque sèche au soleil', 2, '☀️'],
        ['de la buée se forme sur le miroir', 3, '🪞'],
        ['la rosée se dépose le matin', 3, '💧'],
      ],
      e: 'Fusion : solide → liquide ; solidification : liquide → solide ; vaporisation : liquide → gaz ; condensation : gaz → liquide.',
    },
    {
      id: 'melanges',
      niv: 'p',
      prompt:
        'Mélange homogène (on ne distingue qu’une seule matière) ou hétérogène (on en voit plusieurs) ?',
      cats: ['homogène', 'hétérogène'],
      els: [
        ['l’eau salée', 0],
        ['l’eau sucrée', 0],
        ['le sirop à l’eau', 0],
        ['l’eau et l’huile', 1],
        ['l’eau boueuse', 1],
        ['l’eau et le sable', 1],
      ],
      e: 'Dans un mélange homogène, on ne voit qu’une seule matière ; dans un mélange hétérogène, on distingue plusieurs constituants.',
    },
  ],
  etapes: [
    {
      id: 'glacon',
      niv: 'f',
      prompt: 'On chauffe un glaçon dans une casserole : remets les étapes dans l’ordre.',
      els: ['de la glace (solide)', 'de l’eau (liquide)', 'de la vapeur d’eau (gaz)'],
      e: 'En chauffant, la glace fond et devient de l’eau liquide, puis l’eau bout et devient de la vapeur.',
    },
    {
      id: 'sel',
      niv: 'n',
      prompt: 'Comment récupérer le sel d’une eau salée ? Remets les étapes dans l’ordre.',
      els: [
        'On dissout du sel dans de l’eau.',
        'On verse l’eau salée dans une coupelle.',
        'On laisse la coupelle au soleil.',
        'L’eau s’évapore peu à peu.',
        'Il reste des cristaux de sel.',
      ],
      e: 'L’eau s’évapore mais le sel, lui, reste : c’est ainsi que fonctionnent les marais salants.',
    },
    {
      id: 'sable',
      niv: 'n',
      prompt: 'Comment séparer l’eau et le sable ? Remets les étapes dans l’ordre.',
      els: [
        'On mélange l’eau et le sable.',
        'On laisse reposer : le sable tombe au fond.',
        'On verse doucement l’eau du dessus.',
        'On filtre cette eau avec un filtre à café.',
        'On obtient une eau plus claire.',
      ],
      e: 'La décantation puis la filtration séparent le sable de l’eau.',
    },
    {
      id: 'cycle-eau',
      niv: 'p',
      cycle: true,
      prompt: 'Remets dans l’ordre le cycle de l’eau.',
      els: [
        'L’eau des océans s’évapore avec la chaleur du soleil.',
        'La vapeur d’eau se condense en nuages.',
        'Il pleut ou il neige.',
        'L’eau ruisselle vers les rivières.',
        'Les rivières ramènent l’eau à la mer.',
      ],
      e: 'Évaporation, condensation, précipitations, ruissellement : l’eau tourne en boucle.',
    },
  ],
  qcm: [
    {
      id: 'glacon',
      niv: 'f',
      q: 'Dans quel état est l’eau d’un glaçon ?',
      r: 'Solide',
      f: ['Gazeux', 'Liquide'],
      img: '🧊',
      e: 'La glace est de l’eau à l’état solide.',
    },
    {
      id: 'gel',
      niv: 'n',
      q: 'À quelle température l’eau pure gèle-t-elle ?',
      r: '0 °C',
      f: ['100 °C', '50 °C', '37 °C'],
      e: 'L’eau pure gèle à 0 °C.',
    },
    {
      id: 'ebullition',
      niv: 'n',
      q: 'À quelle température l’eau pure bout-elle (au niveau de la mer) ?',
      r: '100 °C',
      f: ['0 °C', '37 °C', '1 000 °C'],
      e: 'L’eau pure bout à 100 °C au niveau de la mer.',
    },
    {
      id: 'fusion',
      niv: 'n',
      q: 'Comment s’appelle le passage de l’état solide à l’état liquide ?',
      r: 'La fusion',
      f: ['La condensation', 'La solidification', 'L’évaporation'],
      e: 'Quand un solide devient liquide, c’est la fusion.',
    },
    {
      id: 'condensation',
      niv: 'p',
      q: 'Comment s’appelle le passage de la vapeur d’eau à l’eau liquide (la buée) ?',
      r: 'La condensation',
      f: ['La fusion', 'La solidification', 'La vaporisation'],
      e: 'La vapeur d’eau se refroidit et redevient liquide : c’est la condensation.',
    },
    {
      id: 'sucre',
      niv: 'n',
      q: 'Que se passe-t-il quand on mélange du sucre dans de l’eau ?',
      r: 'Il se dissout : on ne le voit plus, mais il est toujours là.',
      f: ['Il disparaît pour toujours.', 'Il se transforme en sel.', 'Il flotte à la surface.'],
      e: 'Le sucre dissous donne un goût sucré à l’eau : il est toujours là.',
    },
    {
      id: 'litre',
      niv: 'p',
      q: 'Quelle est la masse d’un litre d’eau ?',
      r: 'Environ 1 kg',
      f: ['Environ 1 g', 'Environ 10 kg', 'Environ 100 kg'],
      e: 'Un litre d’eau pèse environ 1 kilogramme.',
    },
    {
      id: 'air',
      niv: 'p',
      q: 'L’air a-t-il une masse ?',
      r: 'Oui : l’air est de la matière, il a une masse.',
      f: ['Non, l’air ne pèse rien.', 'Seulement quand il fait chaud.', 'Seulement sous l’eau.'],
      e: 'Un ballon gonflé est un peu plus lourd qu’un ballon dégonflé : l’air a une masse.',
    },
    {
      id: 'balance',
      niv: 'f',
      q: 'Quel instrument sert à mesurer une masse ?',
      r: 'La balance',
      f: ['Le thermomètre', 'La règle', 'Le chronomètre'],
      img: '⚖️',
      e: 'On mesure une masse avec une balance, en grammes ou en kilogrammes.',
    },
    {
      id: 'eprouvette',
      niv: 'n',
      q: 'Quel instrument sert à mesurer un volume de liquide ?',
      r: 'L’éprouvette graduée',
      f: ['La balance', 'Le thermomètre', 'Le compas'],
      e: 'L’éprouvette graduée mesure les volumes en millilitres.',
    },
    {
      id: 'volume',
      niv: 'n',
      q: 'Sur une bouteille, « 1,5 L » indique…',
      r: 'un volume',
      f: ['une masse', 'une température', 'une durée'],
      e: 'Le litre (L) est une unité de volume.',
    },
    {
      id: 'qui-vapeur',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'La vapeur d’eau',
      f: ['La buée', 'La glace', 'La neige'],
      hints: [
        'Je suis de l’eau.',
        'On ne peut pas me voir.',
        'Je me forme quand l’eau bout.',
        'Je suis l’eau à l’état de gaz.',
      ],
      img: '♨️',
      e: 'La vapeur d’eau est invisible ; la buée et les nuages sont déjà de petites gouttes d’eau liquide.',
    },
  ],
  vf: [
    {
      id: 'liquide',
      niv: 'f',
      s: 'Un liquide prend la forme du récipient qui le contient.',
      v: true,
      e: 'Un liquide coule et épouse la forme du récipient.',
    },
    { id: 'solide', niv: 'f', s: 'Un solide coule comme l’eau.', v: false, e: 'Un solide garde sa forme.' },
    {
      id: 'fond',
      niv: 'f',
      s: 'La glace fond si on la chauffe.',
      v: true,
      e: 'Elle devient de l’eau liquide : c’est la fusion.',
    },
    {
      id: 'beurre',
      niv: 'f',
      s: 'Le beurre est solide au réfrigérateur et devient liquide quand on le chauffe.',
      v: true,
      e: 'La chaleur fait fondre le beurre.',
    },
    {
      id: 'vapeur',
      niv: 'f',
      s: 'La vapeur d’eau est un solide.',
      v: false,
      e: 'La vapeur d’eau est un gaz.',
    },
    {
      id: 'sel',
      niv: 'n',
      s: 'Le sel se dissout dans l’eau.',
      v: true,
      e: 'On ne le voit plus, mais l’eau devient salée.',
    },
    {
      id: 'sable',
      niv: 'n',
      s: 'Le sable se dissout dans l’eau.',
      v: false,
      e: 'Le sable reste visible et tombe au fond.',
    },
    {
      id: 'bout',
      niv: 'n',
      s: 'L’eau pure bout à 0 °C.',
      v: false,
      e: 'Elle bout à 100 °C ; elle gèle à 0 °C.',
    },
    {
      id: 'gaz',
      niv: 'n',
      s: 'Un gaz occupe tout l’espace disponible.',
      v: true,
      e: 'Un gaz se répand dans tout le récipient.',
    },
    {
      id: 'buee',
      niv: 'p',
      s: 'La buée sur une vitre vient de la vapeur d’eau qui se condense en petites gouttes.',
      v: true,
      e: 'Au contact de la vitre froide, la vapeur redevient liquide.',
    },
    {
      id: 'masse-sucre',
      niv: 'p',
      s: 'Quand le sucre se dissout, l’eau sucrée pèse autant que l’eau seule.',
      v: false,
      e: 'La masse de l’eau sucrée est égale à la masse de l’eau plus celle du sucre.',
    },
    {
      id: 'air',
      niv: 'p',
      s: 'L’air n’est pas de la matière.',
      v: false,
      e: 'L’air est un mélange de gaz : c’est de la matière, il a une masse.',
    },
    {
      id: 'horizontale',
      niv: 'p',
      s: 'La surface d’un liquide au repos est horizontale.',
      v: true,
      e: 'Même si l’on penche le verre, la surface reste horizontale.',
    },
  ],
  paires: [
    {
      id: 'changements',
      niv: 'n',
      prompt: 'Associe chaque changement d’état à sa définition.',
      relation: 'mot → définition',
      pairs: [
        ['la fusion', 'solide → liquide'],
        ['la solidification', 'liquide → solide'],
        ['la vaporisation', 'liquide → gaz'],
        ['la condensation', 'gaz → liquide'],
      ],
      e: 'Fusion, solidification, vaporisation et condensation sont les changements d’état.',
    },
  ],
};

const ENERGIE: Fiche = {
  lecon: 'CM2.SC.ENERGIE',
  classements: [
    {
      id: 'renouvelables',
      niv: 'f',
      prompt: 'Source d’énergie renouvelable ou non renouvelable ?',
      cats: ['renouvelable', 'non renouvelable'],
      els: [
        ['le soleil', 0, '☀️'],
        ['le vent', 0, '🌬️'],
        ['l’eau des rivières', 0, '🌊'],
        ['le bois des forêts replantées', 0, '🪵'],
        ['le pétrole', 1, '🛢️'],
        ['le charbon', 1],
        ['le gaz naturel', 1, '🔥'],
        ['l’uranium', 1, '☢️'],
      ],
      e: 'Le soleil, le vent et l’eau se renouvellent sans cesse ; le pétrole, le charbon, le gaz et l’uranium s’épuisent.',
    },
    {
      id: 'appareils',
      niv: 'n',
      prompt: 'Quelle énergie fait fonctionner ces objets ?',
      cats: ['l’électricité', 'un carburant (tiré du pétrole)', 'la force des muscles'],
      els: [
        ['la lampe de bureau', 0, '💡'],
        ['le réfrigérateur', 0],
        ['l’ordinateur', 0, '💻'],
        ['la voiture à essence', 1, '🚗'],
        ['l’avion', 1, '✈️'],
        ['le vélo', 2, '🚲'],
        ['la trottinette classique', 2, '🛴'],
      ],
      e: 'Les appareils électriques utilisent l’électricité ; les moteurs thermiques, un carburant ; le vélo, nos muscles.',
    },
    {
      id: 'centrales',
      niv: 'p',
      prompt: 'Cette installation utilise-t-elle une énergie renouvelable ?',
      cats: ['énergie renouvelable', 'énergie non renouvelable'],
      els: [
        ['l’éolienne', 0],
        ['le barrage hydroélectrique', 0],
        ['le panneau solaire', 0, '☀️'],
        ['la centrale nucléaire', 1, '☢️'],
        ['la centrale à charbon', 1, '🏭'],
        ['la centrale au gaz', 1, '🔥'],
      ],
      e: 'Éolienne, barrage et panneau solaire utilisent des énergies renouvelables ; les centrales nucléaires, à charbon ou au gaz, non.',
    },
  ],
  etapes: [
    {
      id: 'eolienne',
      niv: 'n',
      prompt: 'Remets dans l’ordre la chaîne d’énergie d’une éolienne.',
      els: [
        'Le vent fait tourner les pales.',
        'L’alternateur produit de l’électricité.',
        'L’électricité circule dans les câbles.',
        'La lampe s’allume et éclaire.',
      ],
      e: 'L’énergie du vent est transformée en électricité, puis en lumière.',
    },
    {
      id: 'barrage',
      niv: 'n',
      prompt: 'Remets dans l’ordre la chaîne d’énergie d’un barrage.',
      els: [
        'L’eau est retenue derrière le barrage.',
        'L’eau descend et fait tourner une turbine.',
        'L’alternateur produit de l’électricité.',
        'Les lignes électriques transportent le courant.',
        'Les maisons sont éclairées.',
      ],
      e: 'La force de l’eau qui descend est transformée en électricité.',
    },
    {
      id: 'dynamo',
      niv: 'p',
      prompt: 'Remets dans l’ordre la chaîne d’énergie du phare d’un vélo à dynamo.',
      els: [
        'Les aliments donnent de l’énergie au cycliste.',
        'Ses muscles font tourner les roues.',
        'La dynamo produit de l’électricité.',
        'Le phare du vélo s’allume.',
      ],
      e: 'L’énergie des aliments devient mouvement, puis électricité, puis lumière.',
    },
    {
      id: 'soleil',
      niv: 'f',
      prompt: 'Remets dans l’ordre : comment un panneau solaire allume une lampe.',
      els: ['Le soleil éclaire le panneau.', 'Le panneau produit de l’électricité.', 'La lampe s’allume.'],
      e: 'Le panneau solaire transforme la lumière du soleil en électricité.',
    },
  ],
  qcm: [
    {
      id: 'renouvelable',
      niv: 'f',
      q: 'Quelle source d’énergie est renouvelable ?',
      r: 'Le soleil',
      f: ['Le pétrole', 'Le charbon', 'Le gaz naturel'],
      img: '☀️',
      e: 'Le soleil brille chaque jour : son énergie ne s’épuise pas.',
    },
    {
      id: 'non-renouvelable',
      niv: 'f',
      q: 'Quelle source d’énergie n’est PAS renouvelable ?',
      r: 'Le pétrole',
      f: ['Le vent', 'Le soleil', 'L’eau des rivières'],
      e: 'Le pétrole a mis des millions d’années à se former : ses réserves s’épuisent.',
    },
    {
      id: 'petrole',
      niv: 'n',
      q: 'Pourquoi dit-on que le pétrole n’est pas renouvelable ?',
      r: 'Il a mis des millions d’années à se former et ses réserves s’épuisent.',
      f: ['Il se reforme chaque année.', 'Il vient du soleil.', 'Il ne sert à rien.'],
      e: 'Une fois brûlé, le pétrole ne se reforme pas à l’échelle d’une vie humaine.',
    },
    {
      id: 'eolienne',
      niv: 'n',
      q: 'Quelle installation transforme l’énergie du vent en électricité ?',
      r: 'L’éolienne',
      f: ['Le panneau solaire', 'Le barrage', 'La pile'],
      e: 'Le vent fait tourner les pales de l’éolienne, qui produit de l’électricité.',
    },
    {
      id: 'panneau',
      niv: 'n',
      q: 'Quel appareil transforme la lumière du soleil en électricité ?',
      r: 'Le panneau solaire photovoltaïque',
      f: ['L’éolienne', 'Le moulin à eau', 'La dynamo'],
      e: 'Le panneau photovoltaïque produit de l’électricité avec la lumière.',
    },
    {
      id: 'uranium',
      niv: 'p',
      q: 'Quel combustible utilise une centrale nucléaire ?',
      r: 'L’uranium',
      f: ['Le bois', 'Le vent', 'Le sable'],
      e: 'Les centrales nucléaires utilisent l’uranium, un métal extrait de mines.',
    },
    {
      id: 'aliments',
      niv: 'n',
      q: 'D’où vient l’énergie qui nous permet de bouger ?',
      r: 'Des aliments que nous mangeons',
      f: ['Des piles', 'De l’électricité', 'Du vent'],
      e: 'Notre corps tire son énergie des aliments.',
    },
    {
      id: 'co2',
      niv: 'p',
      q: 'Que rejette la combustion du pétrole, du charbon et du gaz ?',
      r: 'Du dioxyde de carbone, qui réchauffe le climat',
      f: ['De l’eau pure seulement', 'Du dioxygène', 'Rien du tout'],
      e: 'Ces gaz à effet de serre contribuent au réchauffement climatique.',
    },
    {
      id: 'economie',
      niv: 'f',
      q: 'Quel geste permet d’économiser l’énergie ?',
      r: 'Éteindre la lumière en quittant une pièce',
      f: [
        'Laisser la télévision allumée',
        'Ouvrir la fenêtre quand le chauffage marche',
        'Laisser le chargeur branché',
      ],
      e: 'Éteindre ce qui ne sert pas évite de gaspiller l’énergie.',
    },
    {
      id: 'france',
      niv: 'p',
      q: 'En France, d’où vient la plus grande partie de l’électricité ?',
      r: 'Des centrales nucléaires',
      f: ['Des éoliennes', 'Des panneaux solaires', 'Des centrales à charbon'],
      e: 'Environ deux tiers de l’électricité française viennent des centrales nucléaires.',
    },
    {
      id: 'qui-eolienne',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'L’éolienne',
      f: ['Le moulin à eau', 'Le panneau solaire', 'Le barrage'],
      hints: [
        'Je suis très grande et souvent blanche.',
        'On me trouve dans les champs ou en mer.',
        'J’ai trois grandes pales.',
        'Le vent me fait tourner pour produire de l’électricité.',
      ],
      img: '🌬️',
      e: 'L’éolienne transforme l’énergie du vent en électricité.',
    },
  ],
  vf: [
    {
      id: 'soleil',
      niv: 'f',
      s: 'Le soleil est une source d’énergie renouvelable.',
      v: true,
      e: 'Il ne s’épuise pas.',
    },
    {
      id: 'charbon',
      niv: 'f',
      s: 'Le charbon est une énergie renouvelable.',
      v: false,
      e: 'Ses réserves s’épuisent : il n’est pas renouvelable.',
    },
    {
      id: 'eolienne',
      niv: 'f',
      s: 'Une éolienne utilise l’énergie du vent.',
      v: true,
      e: 'Le vent fait tourner ses pales.',
    },
    {
      id: 'corps',
      niv: 'f',
      s: 'Notre corps tire son énergie des aliments.',
      v: true,
      e: 'Manger nous donne l’énergie pour bouger et grandir.',
    },
    {
      id: 'voiture',
      niv: 'f',
      s: 'Une voiture à essence roule grâce à l’énergie du vent.',
      v: false,
      e: 'Elle roule grâce à l’essence, tirée du pétrole.',
    },
    {
      id: 'petrole',
      niv: 'n',
      s: 'Le pétrole se reforme en quelques années.',
      v: false,
      e: 'Il met des millions d’années à se former.',
    },
    {
      id: 'barrage',
      niv: 'n',
      s: 'Un barrage peut produire de l’électricité grâce à la force de l’eau.',
      v: true,
      e: 'C’est l’énergie hydroélectrique.',
    },
    {
      id: 'lampe',
      niv: 'n',
      s: 'Une lampe transforme l’électricité en lumière (et un peu en chaleur).',
      v: true,
      e: 'Une ampoule chauffe un peu en éclairant.',
    },
    {
      id: 'nuit',
      niv: 'n',
      s: 'Les panneaux solaires produisent plus d’électricité la nuit.',
      v: false,
      e: 'Sans lumière, un panneau solaire ne produit rien.',
    },
    {
      id: 'climat',
      niv: 'p',
      s: 'Brûler du pétrole ou du charbon rejette des gaz qui réchauffent le climat.',
      v: true,
      e: 'Notamment du dioxyde de carbone.',
    },
    {
      id: 'nucleaire',
      niv: 'p',
      s: 'En France, la plus grande partie de l’électricité vient des centrales nucléaires.',
      v: true,
      e: 'Environ deux tiers.',
    },
    {
      id: 'uranium',
      niv: 'p',
      s: 'L’uranium est une source d’énergie renouvelable.',
      v: false,
      e: 'L’uranium est extrait de mines : ses réserves s’épuisent.',
    },
  ],
  paires: [
    {
      id: 'sources',
      niv: 'n',
      prompt: 'Associe chaque source d’énergie à l’installation qui l’utilise.',
      relation: 'source → installation',
      pairs: [
        ['le vent', 'l’éolienne'],
        ['le soleil', 'le panneau solaire'],
        ['l’eau d’une rivière', 'le barrage'],
        ['l’uranium', 'la centrale nucléaire'],
        ['le pétrole', 'le moteur de voiture'],
      ],
      e: 'Chaque installation transforme une source d’énergie en électricité ou en mouvement.',
    },
  ],
};

const MOUVEMENT: Fiche = {
  lecon: 'CM2.SC.MOUVEMENT',
  classements: [
    {
      id: 'lent-rapide',
      niv: 'f',
      prompt: 'Lent ou très rapide ?',
      cats: ['lent (moins de 10 km/h)', 'très rapide (plus de 100 km/h)'],
      els: [
        ['l’escargot', 0, '🐌'],
        ['la tortue', 0, '🐢'],
        ['l’enfant qui marche', 0, '🚶'],
        ['l’avion', 1, '✈️'],
        ['le TGV', 1, '🚄'],
        ['la fusée', 1, '🚀'],
      ],
      e: 'Un piéton marche à environ 5 km/h ; un TGV roule à plus de 300 km/h.',
    },
    {
      id: 'trajectoires',
      niv: 'n',
      prompt: 'Quelle est la trajectoire ?',
      cats: ['rectiligne (en ligne droite)', 'circulaire (en cercle)', 'courbe'],
      els: [
        ['un train sur une voie toute droite', 0, '🚆'],
        ['une pomme qui tombe de l’arbre', 0, '🍎'],
        ['une nacelle de grande roue', 1, '🎡'],
        ['le bout de l’aiguille d’une montre', 1, '⌚'],
        ['un manège qui tourne', 1, '🎠'],
        ['un ballon lancé vers le panier', 2, '🏀'],
        ['un toboggan qui serpente', 2],
      ],
      e: 'Rectiligne : en ligne droite ; circulaire : en cercle ; courbe : ni l’un ni l’autre.',
    },
    {
      id: 'vitesse',
      niv: 'n',
      prompt: 'Que fait la vitesse ?',
      cats: ['elle augmente', 'elle reste la même', 'elle diminue'],
      els: [
        ['une voiture qui démarre au feu vert', 0, '🚦'],
        ['une fusée au décollage', 0, '🚀'],
        ['une bille qui tombe', 0],
        ['un tapis roulant d’aéroport', 1],
        ['un TGV qui roule toujours à 300 km/h', 1, '🚄'],
        ['une voiture qui freine avant le stop', 2, '🛑'],
        ['un skieur qui s’arrête en bas de la piste', 2, '⛷️'],
      ],
      e: 'Un mouvement peut être accéléré, uniforme (vitesse constante) ou ralenti.',
    },
  ],
  etapes: [
    {
      id: 'ballon',
      niv: 'n',
      prompt: 'On lance un ballon vers le haut : remets les étapes dans l’ordre.',
      els: [
        'Le ballon monte en ralentissant.',
        'Il s’arrête un court instant tout en haut.',
        'Il redescend en accélérant.',
        'Il touche le sol.',
      ],
      e: 'En montant, le ballon ralentit ; en descendant, il accélère.',
    },
    {
      id: 'calcul',
      niv: 'p',
      prompt: 'Comment calculer une vitesse moyenne ? Remets les étapes dans l’ordre.',
      els: [
        'Je mesure la distance parcourue.',
        'Je mesure la durée du trajet.',
        'Je divise la distance par la durée.',
        'J’écris le résultat avec son unité (km/h).',
      ],
      e: 'Vitesse moyenne = distance ÷ durée, par exemple 120 km en 2 h → 60 km/h.',
    },
  ],
  qcm: [
    {
      id: '100',
      niv: 'n',
      q: 'Une voiture parcourt 100 km en 1 heure. Quelle est sa vitesse moyenne ?',
      r: '100 km/h',
      f: ['1 km/h', '10 km/h', '1 000 km/h'],
      e: '100 km en 1 h, c’est 100 kilomètres par heure.',
    },
    {
      id: '15',
      niv: 'p',
      q: 'Un cycliste parcourt 30 km en 2 heures. Quelle est sa vitesse moyenne ?',
      r: '15 km/h',
      f: ['60 km/h', '30 km/h', '32 km/h'],
      e: '30 km ÷ 2 h = 15 km/h.',
    },
    {
      id: '300',
      niv: 'p',
      q: 'Un train parcourt 300 km en 3 heures. Quelle est sa vitesse moyenne ?',
      r: '100 km/h',
      f: ['900 km/h', '300 km/h', '3 km/h'],
      e: '300 km ÷ 3 h = 100 km/h.',
    },
    {
      id: 'unite',
      niv: 'f',
      q: 'Dans quelle unité exprime-t-on souvent la vitesse d’une voiture ?',
      r: 'En kilomètres par heure (km/h)',
      f: ['En kilogrammes (kg)', 'En litres (L)', 'En degrés (°C)'],
      e: 'La vitesse indique la distance parcourue en une heure : km/h.',
    },
    {
      id: 'roue',
      niv: 'n',
      q: 'Quelle est la trajectoire d’une nacelle de grande roue ?',
      r: 'Circulaire',
      f: ['Rectiligne', 'En zigzag'],
      img: '🎡',
      e: 'La nacelle tourne en cercle autour de l’axe de la roue.',
    },
    {
      id: 'train',
      niv: 'p',
      q: 'Je suis assis dans un train qui roule. Ma valise posée à côté de moi est…',
      r: 'immobile par rapport à moi, mais en mouvement par rapport au quai',
      f: ['en mouvement par rapport à moi', 'immobile par rapport au quai', 'toujours immobile'],
      e: 'Un mouvement se décrit toujours par rapport à quelque chose.',
    },
    {
      id: 'guepard',
      niv: 'f',
      q: 'Quel animal est le plus rapide ?',
      r: 'Le guépard',
      f: ['L’escargot', 'La tortue', 'La vache'],
      img: '🐆',
      e: 'Le guépard peut dépasser 100 km/h en courte course.',
    },
    {
      id: 'rectiligne',
      niv: 'n',
      q: 'Qu’est-ce qu’un mouvement rectiligne ?',
      r: 'Un mouvement en ligne droite',
      f: ['Un mouvement en cercle', 'Un mouvement qui s’arrête', 'Un mouvement en zigzag'],
      e: 'Rectiligne veut dire « en ligne droite ».',
    },
    {
      id: 'frein',
      niv: 'f',
      q: 'Quand une voiture freine, sa vitesse…',
      r: 'diminue',
      f: ['augmente', 'reste la même'],
      e: 'Freiner fait ralentir : la vitesse diminue.',
    },
  ],
  vf: [
    { id: 'demarre', niv: 'f', s: 'Une voiture qui démarre accélère.', v: true, e: 'Sa vitesse augmente.' },
    {
      id: 'escargot',
      niv: 'f',
      s: 'L’escargot est plus rapide que le TGV.',
      v: false,
      e: 'Le TGV est des milliers de fois plus rapide.',
    },
    {
      id: 'velo',
      niv: 'f',
      s: 'Quand on freine à vélo, la vitesse diminue.',
      v: true,
      e: 'Le vélo ralentit.',
    },
    {
      id: 'feu-rouge',
      niv: 'f',
      s: 'Une voiture arrêtée au feu rouge roule très vite.',
      v: false,
      e: 'Arrêtée, sa vitesse est nulle.',
    },
    {
      id: 'pomme',
      niv: 'n',
      s: 'La trajectoire d’une pomme qui tombe tout droit est rectiligne.',
      v: true,
      e: 'Elle tombe en ligne droite.',
    },
    {
      id: 'nacelle',
      niv: 'n',
      s: 'Une nacelle de grande roue a une trajectoire rectiligne.',
      v: false,
      e: 'Sa trajectoire est circulaire.',
    },
    {
      id: 'distance',
      niv: 'n',
      s: 'Plus on roule vite, plus il faut de distance pour s’arrêter.',
      v: true,
      e: 'C’est pour cela qu’on limite la vitesse.',
    },
    {
      id: '60',
      niv: 'n',
      s: 'Si je parcours 60 km en 1 heure, ma vitesse moyenne est de 60 km/h.',
      v: true,
      e: '60 km ÷ 1 h = 60 km/h.',
    },
    {
      id: '20',
      niv: 'n',
      s: 'Un cycliste qui fait 10 km en 2 heures roule à 20 km/h.',
      v: false,
      e: '10 km ÷ 2 h = 5 km/h.',
    },
    {
      id: 'passager',
      niv: 'p',
      s: 'Un passager assis dans un train qui roule est immobile par rapport au train.',
      v: true,
      e: 'Mais il est en mouvement par rapport au quai.',
    },
    {
      id: 'ralentit',
      niv: 'p',
      s: 'Quand un objet ralentit, sa vitesse augmente.',
      v: false,
      e: 'Ralentir, c’est voir sa vitesse diminuer.',
    },
    {
      id: 'formule',
      niv: 'p',
      s: 'La vitesse moyenne se calcule en divisant la distance par la durée.',
      v: true,
      e: 'Vitesse = distance ÷ durée.',
    },
    {
      id: 'monte',
      niv: 'p',
      s: 'Un ballon lancé vers le haut monte de plus en plus vite.',
      v: false,
      e: 'Il monte en ralentissant.',
    },
  ],
  paires: [
    {
      id: 'unites',
      niv: 'n',
      prompt: 'Associe chaque grandeur à une unité.',
      relation: 'grandeur → unité',
      pairs: [
        ['une vitesse', 'km/h'],
        ['une distance', 'km'],
        ['une durée', 'h'],
        ['une masse', 'kg'],
      ],
      e: 'Vitesse en km/h, distance en km, durée en heures, masse en kilogrammes.',
    },
  ],
};

const SIGNAL: Fiche = {
  lecon: 'CM2.SC.SIGNAL',
  classements: [
    {
      id: 'lumineux-sonore',
      niv: 'f',
      prompt: 'Signal lumineux ou signal sonore ?',
      cats: ['signal lumineux', 'signal sonore'],
      els: [
        ['le feu tricolore', 0, '🚦'],
        ['le clignotant de la voiture', 0],
        ['le phare au bord de la mer', 0],
        ['le voyant rouge de la télévision', 0],
        ['la sonnerie de l’école', 1, '🔔'],
        ['le sifflet de l’arbitre', 1],
        ['le réveil qui sonne', 1, '⏰'],
        ['le klaxon', 1, '📯'],
      ],
      e: 'Un signal lumineux se voit ; un signal sonore s’entend.',
    },
    {
      id: 'sens',
      niv: 'n',
      prompt: 'Avec quel sens reçoit-on ce signal ?',
      cats: ['la vue', 'l’ouïe', 'le toucher'],
      els: [
        ['le feu tricolore', 0, '🚦'],
        ['le phare au bord de la mer', 0],
        ['le clignotant de la voiture', 0],
        ['la sonnerie de l’école', 1, '🔔'],
        ['le sifflet de l’arbitre', 1],
        ['le vibreur du téléphone', 2, '📳'],
        ['l’écriture en braille', 2],
      ],
      e: 'On voit les signaux lumineux, on entend les signaux sonores, on sent les vibrations ou le braille.',
    },
  ],
  etapes: [
    {
      id: 'fumee',
      niv: 'n',
      prompt: 'Remets dans l’ordre le fonctionnement d’un détecteur de fumée.',
      els: [
        'De la fumée entre dans le détecteur.',
        'Le capteur repère la fumée.',
        'Il envoie un signal électrique à l’alarme.',
        'L’alarme émet un son très fort.',
        'Les habitants sont prévenus et sortent.',
      ],
      e: 'Le détecteur transforme une information (la fumée) en signal électrique, puis en signal sonore.',
    },
    {
      id: 'morse',
      niv: 'p',
      prompt: 'Remets dans l’ordre l’envoi d’un message en code Morse avec une lampe.',
      els: [
        'J’écris mon message.',
        'Je le traduis en points et en traits.',
        'J’envoie des éclats de lumière courts et longs.',
        'Mon ami voit les éclats.',
        'Il traduit le code en lettres.',
      ],
      e: 'Le message est codé, transmis par un signal lumineux, puis décodé par le récepteur.',
    },
  ],
  qcm: [
    {
      id: 'rouge',
      niv: 'f',
      q: 'Que signifie un feu tricolore rouge ?',
      r: 'S’arrêter',
      f: ['Avancer', 'Accélérer', 'Klaxonner'],
      img: '🚦',
      e: 'Le feu rouge est un signal lumineux qui veut dire « stop ».',
    },
    {
      id: 'lumineux',
      niv: 'f',
      q: 'Lequel de ces signaux est lumineux ?',
      r: 'Le clignotant d’une voiture',
      f: ['La sonnerie du réveil', 'Le sifflet', 'Le klaxon'],
      e: 'Le clignotant s’allume et s’éteint : c’est un signal lumineux.',
    },
    {
      id: 'morse',
      niv: 'n',
      q: 'Qu’est-ce que le code Morse ?',
      r: 'Un code fait de signaux courts et longs (points et traits)',
      f: ['Une langue parlée en Angleterre', 'Un mot de passe secret', 'Un dessin animé'],
      e: 'Chaque lettre est codée par des signaux courts et longs.',
    },
    {
      id: 'orage',
      niv: 'p',
      q: 'Pendant un orage, pourquoi voit-on l’éclair avant d’entendre le tonnerre ?',
      r: 'La lumière va beaucoup plus vite que le son.',
      f: [
        'Le son va plus vite que la lumière.',
        'Nos yeux sont plus près du ciel que nos oreilles.',
        'Le tonnerre se produit le lendemain.',
      ],
      e: 'La lumière arrive presque instantanément ; le son met environ 3 secondes pour parcourir 1 km.',
    },
    {
      id: 'role',
      niv: 'n',
      q: 'À quoi sert un signal ?',
      r: 'À transmettre une information',
      f: ['À fabriquer de l’énergie', 'À mesurer une masse', 'À nourrir les plantes'],
      e: 'Un signal transporte une information d’un émetteur vers un récepteur.',
    },
    {
      id: 'vide',
      niv: 'p',
      q: 'Le son peut-il se propager dans le vide de l’espace ?',
      r: 'Non, il a besoin d’air, d’eau ou d’un solide.',
      f: ['Oui, partout.', 'Oui, mais seulement la nuit.'],
      e: 'Dans le vide, il n’y a rien pour transporter le son.',
    },
    {
      id: 'telephone',
      niv: 'p',
      q: 'Quel signal le téléphone fixe transmet-il dans les fils ?',
      r: 'Un signal électrique',
      f: ['Un signal de fumée', 'Une odeur', 'Un signal sonore seulement'],
      e: 'La voix est transformée en signal électrique, puis de nouveau en son.',
    },
    {
      id: 'sos',
      niv: 'p',
      q: 'En code Morse, comment s’écrit SOS ?',
      r: '··· ––– ···',
      f: ['––– ··· –––', '··· ··· ···', '–·–· –·–·'],
      e: 'S = trois points, O = trois traits : ··· ––– ···.',
    },
    {
      id: 'qui-phare',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le phare',
      f: ['Le moulin', 'Le château d’eau', 'Le clocher'],
      hints: [
        'Je suis une haute tour.',
        'On me trouve au bord de la mer.',
        'La nuit, j’envoie des éclats de lumière.',
        'Je préviens les bateaux du danger des côtes.',
      ],
      e: 'Le phare envoie un signal lumineux pour guider les bateaux.',
    },
  ],
  vf: [
    {
      id: 'feu',
      niv: 'f',
      s: 'Le feu tricolore est un signal lumineux.',
      v: true,
      e: 'Il s’allume en rouge, orange ou vert.',
    },
    {
      id: 'sonnerie',
      niv: 'f',
      s: 'La sonnerie de l’école est un signal lumineux.',
      v: false,
      e: 'C’est un signal sonore.',
    },
    {
      id: 'detecteur',
      niv: 'f',
      s: 'Un détecteur de fumée envoie un signal sonore pour prévenir d’un danger.',
      v: true,
      e: 'Il sonne très fort.',
    },
    {
      id: 'sifflet',
      niv: 'f',
      s: 'Le sifflet de l’arbitre est un signal sonore.',
      v: true,
      e: 'On l’entend.',
    },
    {
      id: 'klaxon',
      niv: 'f',
      s: 'Le klaxon d’une voiture est un signal lumineux.',
      v: false,
      e: 'Le klaxon est un signal sonore.',
    },
    {
      id: 'information',
      niv: 'n',
      s: 'Un signal permet de transmettre une information.',
      v: true,
      e: 'Par exemple : « Attention, danger ! ».',
    },
    {
      id: 'lumiere-son',
      niv: 'n',
      s: 'La lumière va plus vite que le son.',
      v: true,
      e: 'C’est pour cela qu’on voit l’éclair avant d’entendre le tonnerre.',
    },
    {
      id: 'morse',
      niv: 'n',
      s: 'Le code Morse utilise des signaux courts et longs.',
      v: true,
      e: 'Des points et des traits.',
    },
    {
      id: 'que-sonore',
      niv: 'n',
      s: 'Un signal ne peut être que sonore.',
      v: false,
      e: 'Il peut aussi être lumineux, électrique, tactile…',
    },
    {
      id: 'vide',
      niv: 'p',
      s: 'Le son se propage dans le vide de l’espace.',
      v: false,
      e: 'Le son a besoin de matière pour se propager.',
    },
    {
      id: 'fils',
      niv: 'p',
      s: 'Les signaux électriques circulent dans des fils conducteurs.',
      v: true,
      e: 'Par exemple des fils de cuivre.',
    },
    {
      id: 'braille',
      niv: 'p',
      s: 'Les personnes aveugles peuvent lire grâce au braille, un code de points en relief.',
      v: true,
      e: 'On le lit avec le bout des doigts.',
    },
    {
      id: 'tonnerre',
      niv: 'p',
      s: 'Pendant un orage, on voit l’éclair après avoir entendu le tonnerre.',
      v: false,
      e: 'On voit d’abord l’éclair, car la lumière est plus rapide que le son.',
    },
  ],
  paires: [
    {
      id: 'messages',
      niv: 'f',
      prompt: 'Associe chaque signal à l’information qu’il donne.',
      relation: 'signal → information',
      pairs: [
        ['le feu rouge', 'on s’arrête'],
        ['le feu vert', 'on peut passer'],
        ['la sonnerie de l’école', 'la récréation commence ou finit'],
        ['le clignotant', 'la voiture va tourner'],
        ['la sirène d’alerte', 'danger, il faut se protéger'],
      ],
      e: 'Chaque signal transmet une information que l’on doit comprendre.',
    },
  ],
};

const CLASSER: Fiche = {
  lecon: 'CM2.SC.VIVANT.CLASSER',
  classements: [
    {
      id: 'vertebres',
      niv: 'f',
      prompt: 'Vertébré (squelette intérieur avec une colonne vertébrale) ou invertébré ?',
      cats: ['vertébré', 'invertébré'],
      els: [
        ['le chat', 0, '🐈'],
        ['le poisson', 0, '🐟'],
        ['l’oiseau', 0, '🐦'],
        ['la grenouille', 0, '🐸'],
        ['l’escargot', 1, '🐌'],
        ['l’araignée', 1, '🕷️'],
        ['le papillon', 1, '🦋'],
        ['le ver de terre', 1, '🪱'],
      ],
      e: 'Les vertébrés ont une colonne vertébrale ; les invertébrés n’en ont pas.',
    },
    {
      id: 'peau',
      niv: 'n',
      prompt: 'Qu’est-ce qui recouvre leur corps ?',
      cats: ['des poils', 'des plumes', 'des écailles', 'une peau nue'],
      els: [
        ['le chien', 0, '🐕'],
        ['la chauve-souris', 0, '🦇'],
        ['la poule', 1, '🐔'],
        ['le manchot', 1, '🐧'],
        ['le lézard', 2, '🦎'],
        ['le serpent', 2, '🐍'],
        ['la grenouille', 3, '🐸'],
      ],
      e: 'On classe les animaux selon ce qu’ils ont : poils, plumes, écailles ou peau nue.',
    },
    {
      id: 'groupes',
      niv: 'n',
      prompt: 'Range chaque vertébré dans son groupe.',
      cats: ['mammifères', 'oiseaux', 'poissons', 'reptiles', 'amphibiens'],
      els: [
        ['le dauphin', 0, '🐬'],
        ['la chauve-souris', 0, '🦇'],
        ['le manchot', 1, '🐧'],
        ['l’aigle', 1, '🦅'],
        ['le requin', 2, '🦈'],
        ['la tortue', 3, '🐢'],
        ['le crocodile', 3, '🐊'],
        ['la grenouille', 4, '🐸'],
      ],
      e: 'Mammifères : poils et lait ; oiseaux : plumes ; poissons : nageoires ; reptiles : écailles ; amphibiens : peau nue.',
    },
    {
      id: 'pattes',
      niv: 'p',
      prompt: 'Range ces invertébrés.',
      cats: ['6 pattes : insectes', '8 pattes : arachnides', 'autres invertébrés'],
      els: [
        ['la fourmi', 0, '🐜'],
        ['l’abeille', 0, '🐝'],
        ['la coccinelle', 0, '🐞'],
        ['l’araignée', 1, '🕷️'],
        ['le scorpion', 1, '🦂'],
        ['l’escargot', 2, '🐌'],
        ['le ver de terre', 2, '🪱'],
        ['le crabe', 2, '🦀'],
      ],
      e: 'Les insectes ont 6 pattes, les arachnides 8 ; l’escargot, le ver et le crabe sont d’autres invertébrés.',
    },
  ],
  etapes: [
    {
      id: 'emboites-chat',
      niv: 'n',
      prompt: 'Groupes emboîtés : range du groupe le plus grand au groupe le plus petit.',
      els: ['les animaux', 'les vertébrés', 'les mammifères', 'le chat'],
      e: 'Le chat est un mammifère ; les mammifères sont des vertébrés ; les vertébrés sont des animaux.',
    },
    {
      id: 'emboites-manchot',
      niv: 'p',
      prompt: 'Groupes emboîtés : range du groupe le plus grand au groupe le plus petit.',
      els: ['les êtres vivants', 'les animaux', 'les vertébrés', 'les oiseaux', 'le manchot'],
      e: 'Chaque groupe est inclus dans le groupe précédent, comme des poupées russes.',
    },
  ],
  qcm: [
    {
      id: 'vertebres',
      niv: 'n',
      q: 'Qu’ont en commun tous les vertébrés ?',
      r: 'Un squelette intérieur avec une colonne vertébrale',
      f: ['Des plumes', 'Six pattes', 'Une coquille'],
      e: 'La colonne vertébrale définit le groupe des vertébrés.',
    },
    {
      id: 'mammifere',
      niv: 'n',
      q: 'Lequel de ces animaux est un mammifère ?',
      r: 'La baleine',
      f: ['Le requin', 'La tortue', 'Le manchot'],
      img: '🐋',
      e: 'La baleine respire de l’air et allaite ses petits : c’est un mammifère.',
    },
    {
      id: 'oiseau',
      niv: 'n',
      q: 'Lequel de ces animaux est un oiseau ?',
      r: 'Le manchot',
      f: ['La chauve-souris', 'Le papillon', 'L’écureuil volant'],
      img: '🐧',
      e: 'Le manchot ne vole pas, mais il a des plumes : c’est un oiseau.',
    },
    {
      id: 'insecte',
      niv: 'f',
      q: 'Combien de pattes a un insecte ?',
      r: '6',
      f: ['8', '4', '10'],
      e: 'Tous les insectes ont 6 pattes.',
    },
    {
      id: 'araignee',
      niv: 'n',
      q: 'Combien de pattes a une araignée ?',
      r: '8',
      f: ['6', '4', '100'],
      e: 'L’araignée a 8 pattes : ce n’est pas un insecte.',
    },
    {
      id: 'plumes',
      niv: 'f',
      q: 'Qu’ont tous les oiseaux ?',
      r: 'Des plumes',
      f: ['Des poils', 'Des écailles', 'Une peau nue'],
      e: 'Seuls les oiseaux ont des plumes.',
    },
    {
      id: 'chauve-souris',
      niv: 'p',
      q: 'Pourquoi la chauve-souris est-elle un mammifère et non un oiseau ?',
      r: 'Elle a des poils et allaite ses petits.',
      f: ['Elle vole.', 'Elle a des ailes.', 'Elle vit la nuit.'],
      e: 'On classe selon ce que les animaux ont (poils, mamelles), pas selon ce qu’ils font (voler).',
    },
    {
      id: 'attributs',
      niv: 'p',
      q: 'Les scientifiques classent les êtres vivants selon…',
      r: 'les caractères qu’ils ont en commun',
      f: ['leur taille', 'leur couleur', 'l’endroit où ils vivent'],
      e: 'On regroupe les êtres vivants qui partagent les mêmes caractères (attributs).',
    },
    {
      id: 'qui-chauve-souris',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'La chauve-souris',
      f: ['Le hibou', 'Le papillon de nuit', 'La pie'],
      hints: [
        'Je suis un mammifère.',
        'Je dors la tête en bas.',
        'Je me repère grâce à l’écho de mes cris.',
        'Je suis le seul mammifère capable de vraiment voler.',
      ],
      img: '🦇',
      e: 'La chauve-souris a des poils et allaite ses petits : c’est un mammifère volant.',
    },
    {
      id: 'qui-dauphin',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le dauphin',
      f: ['Le requin', 'Le thon', 'La pieuvre'],
      hints: [
        'Je vis dans la mer.',
        'Je respire de l’air avec des poumons.',
        'J’allaite mes petits.',
        'Je suis un mammifère marin très joueur.',
      ],
      img: '🐬',
      e: 'Le dauphin respire de l’air et allaite : c’est un mammifère, pas un poisson.',
    },
    {
      id: 'qui-araignee',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'L’araignée',
      f: ['La fourmi', 'La mouche', 'Le scarabée'],
      hints: [
        'Je ne suis pas un insecte.',
        'J’ai huit pattes.',
        'Je fabrique de la soie.',
        'Je tisse une toile pour attraper des insectes.',
      ],
      img: '🕷️',
      e: 'L’araignée a 8 pattes : c’est un arachnide, pas un insecte.',
    },
  ],
  vf: [
    {
      id: 'baleine',
      niv: 'f',
      s: 'La baleine est un poisson.',
      v: false,
      e: 'La baleine est un mammifère : elle respire de l’air et allaite.',
    },
    { id: 'plumes', niv: 'f', s: 'Les oiseaux ont des plumes.', v: true, e: 'C’est leur caractère commun.' },
    { id: 'colonne', niv: 'f', s: 'Les vertébrés ont une colonne vertébrale.', v: true, e: 'D’où leur nom.' },
    { id: 'six', niv: 'f', s: 'Un insecte a six pattes.', v: true, e: 'Tous les insectes ont 6 pattes.' },
    { id: 'chat', niv: 'f', s: 'Le chat a des plumes.', v: false, e: 'Le chat a des poils.' },
    {
      id: 'araignee',
      niv: 'n',
      s: 'L’araignée est un insecte.',
      v: false,
      e: 'Elle a 8 pattes : c’est un arachnide.',
    },
    {
      id: 'dauphin',
      niv: 'n',
      s: 'Le dauphin respire avec des poumons.',
      v: true,
      e: 'Il remonte à la surface pour respirer.',
    },
    {
      id: 'chauve-souris',
      niv: 'n',
      s: 'La chauve-souris est un oiseau.',
      v: false,
      e: 'Elle a des poils et allaite : c’est un mammifère.',
    },
    {
      id: 'reptiles',
      niv: 'n',
      s: 'Les reptiles ont la peau couverte d’écailles.',
      v: true,
      e: 'Comme le lézard et le serpent.',
    },
    {
      id: 'escargot',
      niv: 'n',
      s: 'L’escargot n’a pas de squelette intérieur.',
      v: true,
      e: 'C’est un invertébré.',
    },
    {
      id: 'amphibiens',
      niv: 'p',
      s: 'Les amphibiens, comme la grenouille, ont une peau nue.',
      v: true,
      e: 'Leur peau est lisse et humide.',
    },
    {
      id: 'serpent',
      niv: 'p',
      s: 'Le serpent est un invertébré.',
      v: false,
      e: 'Le serpent a une colonne vertébrale : c’est un vertébré.',
    },
    {
      id: 'attributs',
      niv: 'p',
      s: 'Pour classer les animaux, on regarde ce qu’ils ont, pas ce qu’ils font.',
      v: true,
      e: 'On regarde leurs caractères : poils, plumes, squelette…',
    },
    {
      id: 'manchot',
      niv: 'p',
      s: 'Le manchot ne vole pas, donc ce n’est pas un oiseau.',
      v: false,
      e: 'Il a des plumes : c’est un oiseau.',
    },
  ],
  paires: [
    {
      id: 'caracteres',
      niv: 'n',
      prompt: 'Associe chaque animal à un caractère qu’il possède.',
      relation: 'animal → caractère',
      pairs: [
        ['le chat', 'des poils'],
        ['la poule', 'des plumes'],
        ['le lézard', 'des écailles'],
        ['la grenouille', 'une peau nue'],
        ['le papillon', 'six pattes'],
        ['l’araignée', 'huit pattes'],
      ],
      e: 'Ces caractères permettent de classer les animaux.',
    },
  ],
};

const CORPS: Fiche = {
  lecon: 'CM2.SC.VIVANT.CORPS',
  classements: [
    {
      id: 'aliments',
      niv: 'f',
      prompt: 'Range chaque aliment dans sa famille.',
      cats: ['fruits et légumes', 'féculents', 'produits laitiers', 'viandes, poissons, œufs'],
      els: [
        ['la pomme', 0, '🍎'],
        ['la carotte', 0, '🥕'],
        ['le pain', 1, '🍞'],
        ['les pâtes', 1, '🍝'],
        ['le riz', 1, '🍚'],
        ['le fromage', 2, '🧀'],
        ['le lait', 2, '🥛'],
        ['l’œuf', 3, '🥚'],
        ['le poisson', 3, '🐟'],
        ['le poulet', 3, '🍗'],
      ],
      e: 'Chaque famille d’aliments apporte quelque chose d’utile : il faut manger varié.',
    },
    {
      id: 'organes',
      niv: 'n',
      prompt: 'À quelle fonction participe chaque organe ?',
      cats: ['digestion', 'respiration', 'circulation du sang'],
      els: [
        ['l’estomac', 0],
        ['l’intestin', 0],
        ['l’œsophage', 0],
        ['les poumons', 1, '🫁'],
        ['la trachée', 1],
        ['le cœur', 2, '❤️'],
        ['les artères', 2],
        ['les veines', 2],
      ],
      e: 'Digestion : œsophage, estomac, intestin ; respiration : trachée, poumons ; circulation : cœur, artères, veines.',
    },
    {
      id: 'mouvement',
      niv: 'p',
      prompt: 'Os, muscle ou articulation ?',
      cats: ['os', 'muscle', 'articulation'],
      els: [
        ['le fémur', 0, '🦴'],
        ['le crâne', 0],
        ['le tibia', 0],
        ['le biceps', 1, '💪'],
        ['le muscle du mollet', 1],
        ['le genou', 2],
        ['le coude', 2],
        ['l’épaule', 2],
      ],
      e: 'Les muscles tirent sur les os, qui bougent autour des articulations.',
    },
  ],
  etapes: [
    {
      id: 'digestion-f',
      niv: 'f',
      prompt: 'Remets dans l’ordre le trajet des aliments.',
      els: ['la bouche', 'l’estomac', 'l’intestin'],
      e: 'Les aliments sont mâchés dans la bouche, brassés dans l’estomac, puis digérés dans l’intestin.',
    },
    {
      id: 'digestion',
      niv: 'n',
      prompt: 'Remets dans l’ordre le trajet des aliments dans le tube digestif.',
      els: ['la bouche', 'l’œsophage', 'l’estomac', 'l’intestin grêle', 'le gros intestin'],
      e: 'Bouche → œsophage → estomac → intestin grêle → gros intestin.',
    },
    {
      id: 'air',
      niv: 'n',
      prompt: 'Remets dans l’ordre le trajet de l’air quand on inspire.',
      els: ['le nez ou la bouche', 'la trachée', 'les bronches', 'les poumons'],
      e: 'L’air passe par le nez, la trachée et les bronches jusqu’aux poumons.',
    },
    {
      id: 'mouvement',
      niv: 'n',
      prompt: 'Remets dans l’ordre : comment je plie le bras.',
      els: [
        'Le cerveau envoie un ordre.',
        'Le muscle se contracte.',
        'Il tire sur l’os.',
        'L’os bouge autour de l’articulation du coude.',
      ],
      e: 'Le cerveau commande, le muscle se contracte et fait bouger l’os.',
    },
    {
      id: 'respiration',
      niv: 'p',
      prompt: 'Remets dans l’ordre le voyage du dioxygène dans le corps.',
      els: [
        'On inspire de l’air.',
        'L’air arrive dans les poumons.',
        'Le dioxygène passe dans le sang.',
        'Le cœur envoie le sang dans tout le corps.',
        'Les organes utilisent le dioxygène.',
        'On expire du dioxyde de carbone.',
      ],
      e: 'Respiration et circulation travaillent ensemble pour apporter le dioxygène aux organes.',
    },
  ],
  qcm: [
    {
      id: 'coeur',
      niv: 'f',
      q: 'Quel organe envoie le sang dans tout le corps ?',
      r: 'Le cœur',
      f: ['L’estomac', 'Les poumons', 'Le foie'],
      img: '❤️',
      e: 'Le cœur est un muscle qui pompe le sang.',
    },
    {
      id: 'poumons',
      niv: 'f',
      q: 'Dans quels organes l’air entre-t-il quand on respire ?',
      r: 'Les poumons',
      f: ['L’estomac', 'Le cœur', 'Les reins'],
      img: '🫁',
      e: 'L’air entre dans les poumons quand on inspire.',
    },
    {
      id: 'intestin',
      niv: 'n',
      q: 'Où les nutriments passent-ils dans le sang ?',
      r: 'Dans l’intestin grêle',
      f: ['Dans le cœur', 'Dans les poumons', 'Dans la bouche'],
      e: 'Dans l’intestin grêle, les nutriments passent dans le sang.',
    },
    {
      id: 'oxygene',
      niv: 'n',
      q: 'Quel gaz le sang transporte-t-il des poumons vers les organes ?',
      r: 'Le dioxygène',
      f: ['Le dioxyde de carbone', 'La vapeur d’eau', 'L’hélium'],
      e: 'Les organes ont besoin de dioxygène pour fonctionner.',
    },
    {
      id: 'expire',
      niv: 'p',
      q: 'Quand on expire, l’air qui sort contient…',
      r: 'plus de dioxyde de carbone que l’air inspiré',
      f: ['plus de dioxygène que l’air inspiré', 'de la nourriture', 'exactement le même air'],
      e: 'Le corps a utilisé du dioxygène et rejette du dioxyde de carbone.',
    },
    {
      id: 'muscle',
      niv: 'n',
      q: 'Que se passe-t-il quand un muscle se contracte ?',
      r: 'Il raccourcit et tire sur l’os.',
      f: ['Il s’allonge.', 'Il se transforme en os.', 'Il ne se passe rien.'],
      e: 'En se contractant, le muscle tire sur l’os et le fait bouger.',
    },
    {
      id: 'varie',
      niv: 'f',
      q: 'Pourquoi faut-il manger varié ?',
      r: 'Chaque famille d’aliments apporte ce dont le corps a besoin.',
      f: ['Pour manger plus de bonbons.', 'Parce que c’est plus joli.', 'Ce n’est pas utile.'],
      e: 'Une alimentation variée et équilibrée aide à grandir et à rester en bonne santé.',
    },
    {
      id: 'feculents',
      niv: 'n',
      q: 'Quel aliment fait partie des féculents ?',
      r: 'Les pâtes',
      f: ['La pomme', 'Le fromage', 'Le poulet'],
      img: '🍝',
      e: 'Pâtes, pain, riz et pommes de terre sont des féculents : ils donnent de l’énergie.',
    },
    {
      id: 'cinq',
      niv: 'n',
      q: 'Combien de fruits et légumes conseille-t-on de manger chaque jour ?',
      r: 'Au moins 5',
      f: ['Aucun', '1 par semaine', '1 par mois'],
      e: 'On conseille au moins 5 fruits et légumes par jour.',
    },
    {
      id: 'puberte',
      niv: 'p',
      meta: { puberte: true },
      q: 'Qu’est-ce que la puberté ?',
      r: 'La période où le corps de l’enfant se transforme peu à peu en corps d’adulte',
      f: ['Une maladie de l’enfance', 'Le moment où l’on perd ses dents de lait', 'Une période de vacances'],
      e: 'La puberté commence en général entre 8 et 14 ans ; chacun a son propre rythme.',
    },
    {
      id: 'qui-coeur',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le cœur',
      f: ['Les poumons', 'L’estomac', 'Le cerveau'],
      hints: [
        'Je suis un muscle.',
        'Je travaille jour et nuit sans m’arrêter.',
        'Je bats plus vite quand tu cours.',
        'J’envoie le sang dans tout ton corps.',
      ],
      img: '❤️',
      e: 'Le cœur est un muscle qui pompe le sang.',
    },
    {
      id: 'qui-estomac',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'L’estomac',
      f: ['L’intestin', 'Le foie', 'Les poumons'],
      hints: [
        'Je suis une poche.',
        'Je suis entre l’œsophage et l’intestin.',
        'Je brasse les aliments avec un liquide acide.',
        'Je fais partie du tube digestif.',
      ],
      e: 'L’estomac brasse et commence à transformer les aliments.',
    },
  ],
  vf: [
    {
      id: 'coeur',
      niv: 'f',
      s: 'Le cœur pompe le sang.',
      v: true,
      e: 'Il envoie le sang dans tout le corps.',
    },
    { id: 'estomac', niv: 'f', s: 'On respire avec l’estomac.', v: false, e: 'On respire avec les poumons.' },
    {
      id: 'sodas',
      niv: 'f',
      s: 'Il est conseillé de boire surtout des sodas.',
      v: false,
      e: 'La seule boisson indispensable est l’eau.',
    },
    {
      id: 'effort',
      niv: 'f',
      s: 'Pendant un effort, le cœur bat plus vite.',
      v: true,
      e: 'Les muscles ont besoin de plus de dioxygène.',
    },
    {
      id: 'fruits',
      niv: 'f',
      s: 'Les fruits et les légumes sont bons pour la santé.',
      v: true,
      e: 'On conseille d’en manger au moins 5 par jour.',
    },
    {
      id: 'oesophage',
      niv: 'n',
      s: 'Les aliments passent par l’œsophage pour aller dans l’estomac.',
      v: true,
      e: 'L’œsophage relie la bouche à l’estomac.',
    },
    {
      id: 'oxygene',
      niv: 'n',
      s: 'Le sang transporte le dioxygène vers les organes.',
      v: true,
      e: 'Il le prend dans les poumons.',
    },
    {
      id: 'muscles',
      niv: 'n',
      s: 'Les muscles se contractent pour faire bouger les os.',
      v: true,
      e: 'Ils tirent sur les os.',
    },
    {
      id: 'articulations',
      niv: 'n',
      s: 'Les os sont reliés entre eux par des articulations.',
      v: true,
      e: 'Comme le genou ou le coude.',
    },
    {
      id: 'air-estomac',
      niv: 'n',
      s: 'L’air que nous respirons va dans l’estomac.',
      v: false,
      e: 'L’air va dans les poumons.',
    },
    {
      id: 'muscles-os',
      niv: 'n',
      s: 'Les muscles sont des os.',
      v: false,
      e: 'Les muscles et les os sont différents : les muscles font bouger les os.',
    },
    {
      id: 'nutriments',
      niv: 'p',
      s: 'Les nutriments passent dans le sang au niveau de l’intestin grêle.',
      v: true,
      e: 'Le sang les transporte dans tout le corps.',
    },
    {
      id: 'expire',
      niv: 'p',
      s: 'On rejette du dioxyde de carbone quand on expire.',
      v: true,
      e: 'C’est un déchet de la respiration.',
    },
    {
      id: 'commence',
      niv: 'p',
      s: 'La digestion commence dans l’intestin.',
      v: false,
      e: 'Elle commence dans la bouche, avec les dents et la salive.',
    },
    {
      id: 'puberte',
      niv: 'p',
      meta: { puberte: true },
      s: 'À la puberté, le corps grandit et se transforme peu à peu.',
      v: true,
      e: 'Chacun a son propre rythme.',
    },
  ],
  paires: [
    {
      id: 'fonctions',
      niv: 'n',
      prompt: 'Associe chaque organe à son rôle.',
      relation: 'organe → rôle',
      pairs: [
        ['le cœur', 'pomper le sang'],
        ['les poumons', 'respirer'],
        ['l’estomac', 'brasser les aliments'],
        ['les muscles', 'faire bouger le corps'],
        ['le cerveau', 'commander le corps'],
        ['le squelette', 'soutenir le corps'],
      ],
      e: 'Chaque organe a un rôle ; ils travaillent tous ensemble.',
    },
  ],
};

const ECOSYS: Fiche = {
  lecon: 'CM2.SC.VIVANT.ECOSYS',
  classements: [
    {
      id: 'regimes',
      niv: 'f',
      prompt: 'Que mangent ces animaux ?',
      cats: ['herbivore', 'carnivore', 'omnivore'],
      els: [
        ['la vache', 0, '🐄'],
        ['le lapin', 0, '🐇'],
        ['la chèvre', 0, '🐐'],
        ['le lion', 1, '🦁'],
        ['le loup', 1, '🐺'],
        ['la chouette', 1, '🦉'],
        ['le sanglier', 2, '🐗'],
        ['l’ours brun', 2, '🐻'],
      ],
      e: 'L’herbivore mange des végétaux, le carnivore d’autres animaux, l’omnivore un peu de tout.',
    },
    {
      id: 'roles',
      niv: 'n',
      prompt: 'Producteur, consommateur ou décomposeur ?',
      cats: [
        'producteur (végétal)',
        'consommateur (mange d’autres êtres vivants)',
        'décomposeur (recycle les restes)',
      ],
      els: [
        ['l’herbe', 0, '🌿'],
        ['le chêne', 0, '🌳'],
        ['le lapin', 1, '🐇'],
        ['le renard', 1, '🦊'],
        ['la chouette', 1, '🦉'],
        ['le ver de terre', 2, '🪱'],
        ['le champignon', 2, '🍄'],
      ],
      e: 'Les végétaux produisent leur matière ; les animaux la consomment ; les décomposeurs recyclent les restes.',
    },
    {
      id: 'biodiversite',
      niv: 'p',
      prompt: 'Cette action aide-t-elle la biodiversité ou la menace-t-elle ?',
      cats: ['elle aide la biodiversité', 'elle menace la biodiversité'],
      els: [
        ['planter une haie', 0, '🌳'],
        ['installer un nichoir', 0, '🐦'],
        ['construire un hôtel à insectes', 0, '🐝'],
        ['laisser un coin d’herbes sauvages', 0, '🌼'],
        ['utiliser beaucoup de pesticides', 1],
        ['bétonner une prairie', 1],
        ['jeter des déchets dans la nature', 1, '🗑️'],
      ],
      e: 'Haies, nichoirs et herbes sauvages abritent les êtres vivants ; pesticides, béton et déchets les menacent.',
    },
  ],
  etapes: [
    {
      id: 'lapin',
      niv: 'f',
      prompt: 'Chaîne alimentaire : range du végétal à l’animal qui mange les autres (« est mangé par »).',
      els: ['l’herbe', 'le lapin', 'le renard'],
      e: 'L’herbe est mangée par le lapin, qui est mangé par le renard.',
    },
    {
      id: 'chenille',
      niv: 'n',
      prompt: 'Chaîne alimentaire : range du végétal au dernier animal (« est mangé par »).',
      els: ['les feuilles de chêne', 'la chenille', 'la mésange', 'l’épervier'],
      e: 'Les feuilles sont mangées par la chenille, mangée par la mésange, mangée par l’épervier.',
    },
    {
      id: 'limace',
      niv: 'n',
      prompt: 'Chaîne alimentaire : range du végétal au dernier animal (« est mangé par »).',
      els: ['la salade', 'la limace', 'le hérisson', 'le blaireau'],
      e: 'La salade est mangée par la limace, mangée par le hérisson, lui-même proie du blaireau.',
    },
    {
      id: 'ocean',
      niv: 'p',
      prompt: 'Chaîne alimentaire de l’océan Austral : range du végétal au dernier animal.',
      els: ['les algues microscopiques', 'le krill', 'le manchot', 'le phoque léopard'],
      e: 'Dans l’océan, la chaîne commence aussi par des végétaux : de minuscules algues.',
    },
  ],
  qcm: [
    {
      id: 'fleche',
      niv: 'n',
      q: 'Dans une chaîne alimentaire, que veut dire la flèche ?',
      r: '« est mangé par »',
      f: ['« mange »', '« habite avec »', '« est plus grand que »'],
      e: 'herbe → lapin : l’herbe est mangée par le lapin.',
    },
    {
      id: 'debut',
      niv: 'n',
      q: 'Par quoi commence toujours une chaîne alimentaire ?',
      r: 'Par un végétal (un producteur)',
      f: ['Par un carnivore', 'Par un champignon', 'Par un humain'],
      e: 'Les végétaux fabriquent leur matière grâce à la lumière : ils sont au début de toutes les chaînes.',
    },
    {
      id: 'decomposeurs',
      niv: 'n',
      q: 'Quel est le rôle des décomposeurs (vers de terre, champignons) ?',
      r: 'Ils transforment les restes des êtres vivants en éléments minéraux pour le sol.',
      f: ['Ils mangent les gros animaux vivants.', 'Ils fabriquent de la lumière.', 'Ils n’ont aucun rôle.'],
      e: 'Grâce aux décomposeurs, le sol redevient riche pour les plantes.',
    },
    {
      id: 'herbivore',
      niv: 'f',
      q: 'Que mange un herbivore ?',
      r: 'Des végétaux',
      f: ['De la viande', 'Des pierres', 'Seulement des insectes'],
      e: 'La vache et le lapin sont herbivores.',
    },
    {
      id: 'biodiversite',
      niv: 'n',
      q: 'Qu’est-ce que la biodiversité ?',
      r: 'La diversité des êtres vivants et de leurs milieux',
      f: ['Le nombre d’arbres d’une forêt', 'Une espèce de papillon', 'Un produit pour les plantes'],
      e: 'La biodiversité, c’est toute la variété du vivant.',
    },
    {
      id: 'mesanges',
      niv: 'p',
      q: 'Si les mésanges disparaissent d’un jardin, que risque-t-il de se passer ?',
      r: 'Les chenilles risquent de se multiplier.',
      f: [
        'Il n’y aura plus de feuilles sur Terre.',
        'Les éperviers mangeront plus de mésanges.',
        'Rien ne change.',
      ],
      e: 'Quand un maillon disparaît, toute la chaîne est perturbée.',
    },
    {
      id: 'reseau',
      niv: 'p',
      q: 'Qu’est-ce qu’un réseau alimentaire ?',
      r: 'Plusieurs chaînes alimentaires reliées entre elles',
      f: ['Un magasin d’alimentation', 'Une seule chaîne très courte', 'Un filet de pêche'],
      e: 'Un animal mange souvent plusieurs espèces : les chaînes se croisent et forment un réseau.',
    },
    {
      id: 'plantes',
      niv: 'n',
      q: 'De quoi les plantes vertes ont-elles besoin pour fabriquer leur matière ?',
      r: 'De lumière, d’eau, d’air et de sels minéraux',
      f: ['De viande', 'De sucre en poudre', 'De rien du tout'],
      e: 'Avec la lumière, les plantes fabriquent leur propre matière.',
    },
    {
      id: 'qui-ver',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'Le ver de terre',
      f: ['Le serpent', 'La chenille', 'La limace'],
      hints: [
        'Je suis un invertébré.',
        'Je vis dans le sol.',
        'Je mange des feuilles mortes et je mélange la terre.',
        'Je suis un décomposeur long et sans pattes.',
      ],
      img: '🪱',
      e: 'Le ver de terre est un décomposeur qui enrichit le sol.',
    },
    {
      id: 'qui-abeille',
      niv: 'f',
      q: 'Qui suis-je ?',
      r: 'L’abeille',
      f: ['La guêpe', 'La mouche', 'La coccinelle'],
      hints: [
        'Je suis un insecte.',
        'Je vis dans une colonie avec une reine.',
        'En allant de fleur en fleur, je transporte le pollen.',
        'Je fabrique du miel.',
      ],
      img: '🐝',
      e: 'L’abeille transporte le pollen et aide les plantes à se reproduire.',
    },
  ],
  vf: [
    {
      id: 'lapin',
      niv: 'f',
      s: 'Le lapin est un carnivore.',
      v: false,
      e: 'Le lapin mange des végétaux : c’est un herbivore.',
    },
    { id: 'lion', niv: 'f', s: 'Le lion mange de l’herbe.', v: false, e: 'Le lion est carnivore.' },
    {
      id: 'haie',
      niv: 'f',
      s: 'Une haie abrite de nombreux animaux.',
      v: true,
      e: 'Oiseaux, insectes, hérissons y trouvent refuge.',
    },
    { id: 'vache', niv: 'f', s: 'La vache est un herbivore.', v: true, e: 'Elle mange de l’herbe.' },
    {
      id: 'vegetal',
      niv: 'n',
      s: 'Une chaîne alimentaire commence toujours par un végétal.',
      v: true,
      e: 'Les végétaux sont les producteurs.',
    },
    {
      id: 'decomposeurs',
      niv: 'n',
      s: 'Les champignons et les vers de terre sont des décomposeurs.',
      v: true,
      e: 'Ils recyclent la matière morte.',
    },
    {
      id: 'fleche',
      niv: 'n',
      s: 'Dans une chaîne alimentaire, la flèche veut dire « mange ».',
      v: false,
      e: 'Elle veut dire « est mangé par ».',
    },
    {
      id: 'lumiere',
      niv: 'n',
      s: 'Les plantes vertes fabriquent leur propre matière grâce à la lumière.',
      v: true,
      e: 'Avec de l’eau, de l’air et des sels minéraux.',
    },
    {
      id: 'oiseaux',
      niv: 'n',
      s: 'La biodiversité, c’est seulement le nombre d’oiseaux.',
      v: false,
      e: 'C’est la diversité de tous les êtres vivants.',
    },
    {
      id: 'abeilles',
      niv: 'p',
      s: 'Les abeilles aident les plantes à se reproduire en transportant le pollen.',
      v: true,
      e: 'C’est la pollinisation.',
    },
    {
      id: 'disparition',
      niv: 'p',
      s: 'Si une espèce disparaît, cela peut perturber toute la chaîne alimentaire.',
      v: true,
      e: 'Tous les êtres vivants sont liés.',
    },
    {
      id: 'pesticides',
      niv: 'p',
      s: 'Les pesticides protègent tous les insectes.',
      v: false,
      e: 'Ils tuent aussi des insectes utiles, comme les abeilles.',
    },
  ],
  paires: [
    {
      id: 'menus',
      niv: 'n',
      prompt: 'Associe chaque animal à ce qu’il mange.',
      relation: 'animal → nourriture',
      pairs: [
        ['le lapin', 'de l’herbe'],
        ['la mésange', 'des chenilles'],
        ['le ver de terre', 'des feuilles mortes'],
        ['le hérisson', 'des limaces'],
        ['l’abeille', 'le nectar des fleurs'],
      ],
      e: 'Chaque animal a son régime alimentaire.',
    },
  ],
};

const TERRE: Fiche = {
  lecon: 'CM2.SC.TERRE',
  classements: [
    {
      id: 'astres',
      niv: 'f',
      prompt: 'Étoile, planète ou satellite naturel ?',
      cats: ['étoile', 'planète', 'satellite naturel'],
      els: [
        ['le Soleil', 0, '☀️'],
        ['l’étoile Polaire', 0, '⭐'],
        ['la Terre', 1, '🌍'],
        ['Mars', 1],
        ['Saturne', 1, '🪐'],
        ['la Lune', 2, '🌙'],
      ],
      e: 'Une étoile produit sa lumière ; une planète tourne autour d’une étoile ; un satellite tourne autour d’une planète.',
    },
    {
      id: 'planetes',
      niv: 'n',
      prompt: 'Planète rocheuse ou planète géante ?',
      cats: ['planète rocheuse', 'planète géante'],
      els: [
        ['Mercure', 0],
        ['Vénus', 0],
        ['la Terre', 0, '🌍'],
        ['Mars', 0],
        ['Jupiter', 1],
        ['Saturne', 1, '🪐'],
        ['Uranus', 1],
        ['Neptune', 1],
      ],
      e: 'Les quatre planètes proches du Soleil sont rocheuses ; les quatre plus lointaines sont des planètes géantes.',
    },
    {
      id: 'risques',
      niv: 'n',
      prompt: 'Phénomène venu de l’intérieur de la Terre ou de l’atmosphère (la météo) ?',
      cats: ['intérieur de la Terre', 'météo'],
      els: [
        ['le séisme', 0],
        ['l’éruption volcanique', 0, '🌋'],
        ['le tsunami causé par un séisme', 0, '🌊'],
        ['la tempête', 1, '🌬️'],
        ['l’inondation après de fortes pluies', 1, '🌧️'],
        ['le cyclone', 1, '🌀'],
      ],
      e: 'Séismes et volcans viennent de l’intérieur de la Terre ; tempêtes, pluies et cyclones viennent de l’atmosphère.',
    },
    {
      id: 'mouvements',
      niv: 'p',
      prompt:
        'Ce phénomène s’explique par la rotation de la Terre sur elle-même ou par sa révolution autour du Soleil ?',
      cats: ['rotation (1 tour en 24 h)', 'révolution (1 tour en 1 an)'],
      els: [
        ['l’alternance du jour et de la nuit', 0],
        ['le Soleil semble se lever à l’est', 0, '🌅'],
        ['les étoiles semblent tourner dans le ciel la nuit', 0],
        ['la durée d’une année', 1],
        ['le retour des saisons chaque année', 1],
      ],
      e: 'La rotation explique le jour et la nuit ; la révolution, avec l’inclinaison de la Terre, explique l’année et les saisons.',
    },
  ],
  etapes: [
    {
      id: 'planetes-f',
      niv: 'f',
      prompt: 'Range ces planètes de la plus proche à la plus éloignée du Soleil.',
      els: ['Mercure', 'Vénus', 'la Terre', 'Mars'],
      e: 'Mercure, Vénus, la Terre puis Mars.',
    },
    {
      id: 'planetes',
      niv: 'n',
      prompt: 'Range les planètes de la plus proche à la plus éloignée du Soleil.',
      els: ['Mercure', 'Vénus', 'la Terre', 'Mars', 'Jupiter', 'Saturne', 'Uranus', 'Neptune'],
      e: 'Mercure, Vénus, la Terre, Mars, Jupiter, Saturne, Uranus, Neptune.',
    },
    {
      id: 'lune',
      niv: 'n',
      cycle: true,
      prompt: 'Remets dans l’ordre le cycle des phases de la Lune.',
      els: ['la nouvelle lune', 'le premier quartier', 'la pleine lune', 'le dernier quartier'],
      e: 'Le cycle des phases de la Lune dure environ 29 jours et demi.',
    },
    {
      id: 'saisons',
      niv: 'f',
      cycle: true,
      prompt: 'Remets dans l’ordre le cycle des saisons, en commençant par le printemps.',
      els: ['le printemps', 'l’été', 'l’automne', 'l’hiver'],
      e: 'Les saisons reviennent chaque année dans le même ordre.',
    },
    {
      id: 'volcan',
      niv: 'p',
      prompt: 'Remets dans l’ordre une éruption volcanique.',
      els: [
        'Le magma remonte dans la cheminée du volcan.',
        'Il sort par le cratère.',
        'La lave coule sur les pentes.',
        'La lave refroidit et devient de la roche.',
      ],
      e: 'Le magma qui sort du volcan s’appelle la lave ; en refroidissant, elle forme une roche.',
    },
  ],
  qcm: [
    {
      id: 'rotation',
      niv: 'n',
      q: 'En combien de temps la Terre fait-elle un tour sur elle-même ?',
      r: 'En 24 heures environ',
      f: ['En 365 jours', 'En 1 heure', 'En 1 mois'],
      e: 'Un tour sur elle-même en 24 heures environ : c’est une journée.',
    },
    {
      id: 'revolution',
      niv: 'n',
      q: 'En combien de temps la Terre fait-elle le tour du Soleil ?',
      r: 'En 365 jours environ (un an)',
      f: ['En 24 heures', 'En 30 jours', 'En 100 ans'],
      e: 'La révolution de la Terre autour du Soleil dure environ 365 jours et un quart.',
    },
    {
      id: 'jour-nuit',
      niv: 'n',
      q: 'Pourquoi y a-t-il le jour et la nuit ?',
      r: 'Parce que la Terre tourne sur elle-même',
      f: [
        'Parce que le Soleil s’éteint la nuit',
        'Parce que la Lune cache le Soleil chaque soir',
        'Parce que la Terre s’éloigne du Soleil',
      ],
      e: 'La moitié de la Terre tournée vers le Soleil est dans le jour, l’autre dans la nuit.',
    },
    {
      id: 'saisons',
      niv: 'p',
      q: 'Pourquoi y a-t-il des saisons ?',
      r: 'Parce que l’axe de la Terre est penché pendant qu’elle tourne autour du Soleil',
      f: [
        'Parce que la Terre s’approche et s’éloigne beaucoup du Soleil',
        'Parce que le Soleil change de couleur',
        'Parce que la Lune réchauffe la Terre',
      ],
      e: 'Selon la période de l’année, notre hémisphère reçoit les rayons du Soleil plus ou moins directement.',
    },
    {
      id: 'etoile',
      niv: 'f',
      q: 'Quelle est l’étoile la plus proche de la Terre ?',
      r: 'Le Soleil',
      f: ['La Lune', 'L’étoile Polaire', 'Mars'],
      img: '☀️',
      e: 'Le Soleil est une étoile : il produit sa propre lumière.',
    },
    {
      id: 'huit',
      niv: 'n',
      q: 'Combien de planètes tournent autour du Soleil ?',
      r: '8',
      f: ['9', '5', '12'],
      e: 'Il y a 8 planètes dans le système solaire.',
    },
    {
      id: 'jupiter',
      niv: 'n',
      q: 'Quelle est la plus grande planète du système solaire ?',
      r: 'Jupiter',
      f: ['La Terre', 'Mars', 'Mercure'],
      e: 'Jupiter est une géante gazeuse, bien plus grande que la Terre.',
    },
    {
      id: 'lune',
      niv: 'f',
      q: 'Qu’est-ce que la Lune ?',
      r: 'Le satellite naturel de la Terre',
      f: ['Une étoile', 'Une planète', 'Un nuage'],
      img: '🌙',
      e: 'La Lune tourne autour de la Terre.',
    },
    {
      id: 'seisme',
      niv: 'n',
      q: 'Qu’est-ce qu’un séisme ?',
      r: 'Un tremblement de terre',
      f: ['Une éruption volcanique', 'Une grosse tempête', 'Une marée haute'],
      e: 'Lors d’un séisme, le sol tremble.',
    },
    {
      id: 'volcan',
      niv: 'f',
      q: 'Que sort-il d’un volcan en éruption ?',
      r: 'De la lave, des gaz et des cendres',
      f: ['De l’eau douce', 'Du sable de plage', 'De la neige'],
      img: '🌋',
      e: 'La lave est de la roche fondue.',
    },
    {
      id: 'consigne',
      niv: 'p',
      q: 'En cas de séisme, que faut-il faire en classe ?',
      r: 'Se mettre sous une table solide et protéger sa tête',
      f: ['Courir dans les escaliers', 'Se mettre près des fenêtres', 'Prendre l’ascenseur'],
      e: 'On s’abrite sous une table, loin des fenêtres, puis on évacue calmement quand le sol ne tremble plus.',
    },
    {
      id: 'qui-lune',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'La Lune',
      f: ['Le Soleil', 'Mars', 'L’étoile Polaire'],
      hints: [
        'Je ne produis pas de lumière : le Soleil m’éclaire.',
        'Ma forme semble changer au fil des jours.',
        'Des astronautes ont marché sur moi en 1969.',
        'Je tourne autour de la Terre.',
      ],
      img: '🌙',
      e: 'La Lune est le satellite naturel de la Terre.',
    },
    {
      id: 'qui-mars',
      niv: 'p',
      q: 'Qui suis-je ?',
      r: 'Mars',
      f: ['Vénus', 'Jupiter', 'Mercure'],
      hints: [
        'Je suis une planète rocheuse.',
        'Je suis la quatrième planète en partant du Soleil.',
        'Des robots me parcourent pour m’étudier.',
        'On me surnomme la planète rouge.',
      ],
      e: 'Mars, la planète rouge, est la quatrième planète du système solaire.',
    },
  ],
  vf: [
    { id: 'soleil', niv: 'f', s: 'Le Soleil est une étoile.', v: true, e: 'Il produit sa propre lumière.' },
    {
      id: 'lune',
      niv: 'f',
      s: 'La Lune est une planète.',
      v: false,
      e: 'La Lune est le satellite naturel de la Terre.',
    },
    {
      id: 'tourne',
      niv: 'f',
      s: 'La Terre tourne autour du Soleil.',
      v: true,
      e: 'Elle fait un tour en un an.',
    },
    {
      id: 'soleil-tourne',
      niv: 'f',
      s: 'Le Soleil tourne autour de la Terre.',
      v: false,
      e: 'C’est la Terre qui tourne autour du Soleil.',
    },
    {
      id: 'un-an',
      niv: 'n',
      s: 'La Terre fait un tour sur elle-même en un an.',
      v: false,
      e: 'Elle fait un tour sur elle-même en 24 heures environ.',
    },
    {
      id: 'rotation',
      niv: 'n',
      s: 'C’est la rotation de la Terre qui explique le jour et la nuit.',
      v: true,
      e: 'Une moitié est éclairée, l’autre est dans l’ombre.',
    },
    {
      id: 'huit',
      niv: 'n',
      s: 'Il y a 8 planètes dans le système solaire.',
      v: true,
      e: 'De Mercure à Neptune.',
    },
    {
      id: 'jupiter',
      niv: 'n',
      s: 'Jupiter est la plus grande planète du système solaire.',
      v: true,
      e: 'C’est une géante gazeuse.',
    },
    { id: 'seisme', niv: 'n', s: 'Un séisme est un tremblement de terre.', v: true, e: 'Le sol tremble.' },
    {
      id: 'mercure',
      niv: 'n',
      s: 'Mercure est la planète la plus éloignée du Soleil.',
      v: false,
      e: 'Mercure est la plus proche ; Neptune est la plus éloignée.',
    },
    {
      id: 'saisons',
      niv: 'p',
      s: 'C’est l’été en France parce que la Terre est alors plus près du Soleil.',
      v: false,
      e: 'Les saisons viennent de l’inclinaison de la Terre ; la Terre est même un peu plus près du Soleil en janvier.',
    },
    {
      id: 'australie',
      niv: 'p',
      s: 'Quand c’est l’été en France, c’est l’hiver en Australie.',
      v: true,
      e: 'Les deux hémisphères ont des saisons inversées.',
    },
    {
      id: 'lumiere',
      niv: 'p',
      s: 'La Lune produit sa propre lumière.',
      v: false,
      e: 'Elle renvoie la lumière du Soleil.',
    },
    {
      id: 'volcans',
      niv: 'p',
      s: 'Un volcan actif peut entrer en éruption.',
      v: true,
      e: 'Les scientifiques le surveillent.',
    },
  ],
  paires: [
    {
      id: 'planetes',
      niv: 'n',
      prompt: 'Associe chaque planète à son indice.',
      relation: 'planète → indice',
      pairs: [
        ['Mercure', 'la plus proche du Soleil'],
        ['la Terre', 'notre planète, avec de l’eau liquide'],
        ['Mars', 'la planète rouge'],
        ['Jupiter', 'la plus grande'],
        ['Saturne', 'entourée de grands anneaux'],
        ['Neptune', 'la plus éloignée du Soleil'],
      ],
      e: 'Chaque planète du système solaire a ses particularités.',
    },
  ],
};

const TECHNO: Fiche = {
  lecon: 'CM2.SC.TECHNO',
  classements: [
    {
      id: 'materiaux',
      niv: 'f',
      prompt: 'En quel matériau sont faits ces objets ?',
      cats: ['bois', 'métal', 'plastique', 'verre'],
      els: [
        ['le crayon de papier', 0, '✏️'],
        ['la planche', 0, '🪵'],
        ['la cuillère en inox', 1, '🥄'],
        ['le trombone', 1, '📎'],
        ['le sac de caisse', 2, '🛍️'],
        ['le pot de yaourt', 2],
        ['la vitre', 3, '🪟'],
        ['le bocal en verre', 3, '🫙'],
      ],
      e: 'On choisit le matériau selon ce que doit faire l’objet : solidité, légèreté, transparence…',
    },
    {
      id: 'circuit',
      niv: 'n',
      meta: { circuit: true },
      prompt: 'Place l’objet dans le circuit : l’ampoule s’allume-t-elle ?',
      cats: ['conducteur (l’ampoule s’allume)', 'isolant (l’ampoule reste éteinte)'],
      els: [
        ['une clé en métal', 0, '🔑'],
        ['une fourchette en métal', 0, '🍴'],
        ['une feuille d’aluminium', 0],
        ['une pièce de monnaie', 0, '🪙'],
        ['une gomme', 1],
        ['une règle en bois', 1, '📏'],
        ['un bouchon en liège', 1],
        ['un élastique', 1],
      ],
      e: 'Les métaux laissent passer le courant (conducteurs) ; le bois, le plastique, le caoutchouc et le liège non (isolants).',
    },
    {
      id: 'fonctions',
      niv: 'n',
      prompt: 'À quoi servent ces objets techniques ?',
      cats: ['s’éclairer', 'se déplacer', 'communiquer'],
      els: [
        ['la lampe de poche', 0, '🔦'],
        ['le lampadaire', 0],
        ['le vélo', 1, '🚲'],
        ['la trottinette', 1, '🛴'],
        ['la voiture', 1, '🚗'],
        ['le téléphone', 2, '📱'],
        ['l’ordinateur', 2, '💻'],
      ],
      e: 'Un objet technique est fabriqué pour répondre à un besoin : c’est sa fonction d’usage.',
    },
  ],
  etapes: [
    {
      id: 'telephone',
      niv: 'n',
      prompt: 'Range ces téléphones du plus ancien au plus récent.',
      els: [
        'le premier téléphone de Graham Bell',
        'le téléphone à cadran',
        'le téléphone à touches',
        'le téléphone portable',
        'le smartphone à écran tactile',
      ],
      labels: ['1876', 'vers 1930', 'vers 1980', 'vers 1995', '2007'],
      e: 'Les objets techniques évoluent : du téléphone de Bell (1876) au smartphone (2007).',
    },
    {
      id: 'transports',
      niv: 'p',
      prompt: 'Range ces moyens de transport du plus ancien au plus récent.',
      els: [
        'la diligence tirée par des chevaux',
        'la locomotive à vapeur',
        'l’automobile à essence',
        'l’avion à moteur',
        'la fusée qui va sur la Lune',
      ],
      labels: ['XVIIIe siècle', '1825', '1886', '1903', '1969'],
      e: 'De la diligence à la fusée Apollo, les transports ont beaucoup évolué en deux siècles.',
    },
    {
      id: 'conception',
      niv: 'n',
      prompt: 'Remets dans l’ordre les étapes de la fabrication d’un objet.',
      els: [
        'Je repère le besoin.',
        'J’imagine des solutions et je dessine un croquis.',
        'Je choisis les matériaux.',
        'Je fabrique l’objet.',
        'Je le teste et je l’améliore.',
      ],
      e: 'Concevoir un objet, c’est réfléchir avant de fabriquer, puis tester.',
    },
    {
      id: 'algorithme',
      niv: 'p',
      prompt: 'Remets dans l’ordre le programme d’un lampadaire automatique.',
      els: [
        'Lire le capteur de lumière.',
        'S’il fait sombre, allumer la lampe.',
        'Sinon, éteindre la lampe.',
        'Attendre une minute.',
        'Recommencer depuis le début.',
      ],
      e: 'Un programme est une suite d’instructions ; ici, on teste une condition et on répète.',
    },
  ],
  qcm: [
    {
      id: 'objet',
      niv: 'f',
      q: 'Qu’est-ce qu’un objet technique ?',
      r: 'Un objet fabriqué par l’être humain pour répondre à un besoin',
      f: ['Un objet de la nature', 'Un animal domestique', 'Un caillou trouvé dans la rivière'],
      e: 'Une paire de ciseaux, un vélo, un téléphone sont des objets techniques.',
    },
    {
      id: 'algorithme',
      niv: 'n',
      q: 'Qu’est-ce qu’un algorithme ?',
      r: 'Une suite d’instructions pour résoudre un problème',
      f: ['Un robot', 'Une maladie des ordinateurs', 'Un calcul faux'],
      e: 'Une recette de cuisine est un exemple d’algorithme.',
    },
    {
      id: 'conducteur',
      niv: 'f',
      q: 'Quel matériau laisse passer le courant électrique ?',
      r: 'Le métal',
      f: ['Le bois', 'Le plastique', 'Le verre'],
      e: 'Les métaux sont de bons conducteurs électriques.',
    },
    {
      id: 'casserole',
      niv: 'n',
      q: 'Pourquoi les poignées de casserole sont-elles souvent en bois ou en plastique ?',
      r: 'Ces matériaux conduisent mal la chaleur.',
      f: ['Ils sont plus lourds.', 'Ils brillent.', 'Ils conduisent bien la chaleur.'],
      e: 'On peut tenir la poignée sans se brûler.',
    },
    {
      id: 'velo',
      niv: 'f',
      q: 'Quelle est la fonction d’usage d’un vélo ?',
      r: 'Se déplacer',
      f: ['S’éclairer', 'Communiquer', 'Cuisiner'],
      img: '🚲',
      e: 'La fonction d’usage, c’est ce à quoi sert l’objet.',
    },
    {
      id: 'repeter',
      niv: 'n',
      q: 'Dans un programme, que veut dire « répéter 4 fois » ?',
      r: 'Faire la même instruction 4 fois de suite',
      f: ['Faire 4 instructions différentes', 'Attendre 4 secondes', 'Arrêter le programme'],
      e: 'Une boucle évite d’écrire plusieurs fois la même instruction.',
    },
    {
      id: 'circuit',
      niv: 'n',
      q: 'Que faut-il pour qu’une ampoule s’allume ?',
      r: 'Un circuit fermé avec une pile',
      f: ['Un circuit ouvert', 'Un fil en plastique', 'Une seule borne de la pile reliée'],
      e: 'Le courant doit pouvoir faire une boucle complète.',
    },
    {
      id: 'verre',
      niv: 'p',
      q: 'Quel matériau peut se recycler presque à l’infini ?',
      r: 'Le verre',
      f: ['Le papier', 'Le bois', 'Le tissu'],
      e: 'Le verre fondu peut redevenir une bouteille de nombreuses fois.',
    },
    {
      id: 'bell',
      niv: 'p',
      q: 'Qui a inventé le téléphone en 1876 ?',
      r: 'Graham Bell',
      f: ['Thomas Edison', 'Gustave Eiffel', 'Louis Pasteur'],
      e: 'Alexander Graham Bell a déposé le brevet du téléphone en 1876.',
    },
    {
      id: 'capteur',
      niv: 'p',
      q: 'Qu’est-ce qu’un capteur ?',
      r: 'Un composant qui détecte quelque chose : lumière, chaleur, mouvement…',
      f: ['Un fil électrique', 'Une pile', 'Un écran'],
      e: 'Un détecteur de mouvement allume la lumière quand on passe.',
    },
    {
      id: 'qui-ordinateur',
      niv: 'n',
      q: 'Qui suis-je ?',
      r: 'L’ordinateur',
      f: ['La télévision', 'La radio', 'La calculatrice'],
      hints: [
        'Je suis une machine.',
        'J’obéis à des programmes.',
        'J’ai souvent un clavier, un écran et une souris.',
        'Je calcule, j’écris et je me connecte à Internet.',
      ],
      img: '💻',
      e: 'L’ordinateur exécute des programmes écrits par des êtres humains.',
    },
  ],
  vf: [
    {
      id: 'humain',
      niv: 'f',
      s: 'Un objet technique est fabriqué par l’être humain.',
      v: true,
      e: 'Il répond à un besoin.',
    },
    {
      id: 'bois',
      niv: 'f',
      s: 'Le bois conduit le courant électrique.',
      v: false,
      e: 'Le bois est un isolant.',
    },
    {
      id: 'metal',
      niv: 'f',
      s: 'Le métal est un bon conducteur d’électricité.',
      v: true,
      e: 'C’est pour cela que les fils électriques sont en cuivre.',
    },
    { id: 'velo', niv: 'f', s: 'Le vélo sert à se déplacer.', v: true, e: 'C’est sa fonction d’usage.' },
    {
      id: 'vitre',
      niv: 'f',
      s: 'Une vitre est en métal.',
      v: false,
      e: 'Une vitre est en verre, un matériau transparent.',
    },
    {
      id: 'algorithme',
      niv: 'n',
      s: 'Un algorithme est une suite d’instructions dans un ordre précis.',
      v: true,
      e: 'L’ordre des instructions est important.',
    },
    {
      id: 'ouvert',
      niv: 'n',
      s: 'Pour qu’une ampoule brille, le circuit doit être ouvert.',
      v: false,
      e: 'Le circuit doit être fermé.',
    },
    {
      id: 'plastique',
      niv: 'n',
      s: 'Le plastique est souvent fabriqué à partir du pétrole.',
      v: true,
      e: 'C’est un matériau artificiel.',
    },
    {
      id: 'robot',
      niv: 'n',
      s: 'Un robot peut suivre un programme.',
      v: true,
      e: 'Il exécute les instructions dans l’ordre.',
    },
    {
      id: 'smartphone',
      niv: 'n',
      s: 'Le smartphone a été inventé avant le téléphone à cadran.',
      v: false,
      e: 'Le téléphone à cadran est bien plus ancien.',
    },
    {
      id: 'capteur',
      niv: 'p',
      s: 'Un capteur de lumière peut allumer automatiquement un lampadaire la nuit.',
      v: true,
      e: 'Il détecte quand il fait sombre.',
    },
    {
      id: 'boucle',
      niv: 'p',
      s: 'Une boucle « répéter » évite d’écrire plusieurs fois la même instruction.',
      v: true,
      e: 'C’est plus court et plus clair.',
    },
    {
      id: 'verre',
      niv: 'p',
      s: 'Le verre ne se recycle pas.',
      v: false,
      e: 'Le verre se recycle très bien.',
    },
    {
      id: 'court-circuit',
      niv: 'p',
      s: 'Relier directement les deux bornes d’une pile avec un fil est sans danger.',
      v: false,
      e: 'C’est un court-circuit : la pile chauffe et s’abîme.',
    },
  ],
  paires: [
    {
      id: 'materiaux',
      niv: 'f',
      prompt: 'Associe chaque objet à son matériau principal.',
      relation: 'objet → matériau',
      pairs: [
        ['une vitre', 'le verre'],
        ['une canette', 'le métal'],
        ['une planche', 'le bois'],
        ['un sac de caisse', 'le plastique'],
        ['un pull', 'la laine'],
      ],
      e: 'Chaque objet est fait d’un matériau adapté à son usage.',
    },
  ],
};

export const SCIENCES: Fiche[] = [MATIERE, ENERGIE, MOUVEMENT, SIGNAL, CLASSER, CORPS, ECOSYS, TERRE, TECHNO];
